### ISSUE TITLE
Vertical scroll singe step size

### ISSUE THREAD

**Issue by kkthx** [x64dbg/x64dbg#1000]
It should be possible to change/modify number of lines at time of one mouse scroll, like on windows (image attached). Currently it is fixed to 4 lines/notch.

![mousescroll](https://cloud.githubusercontent.com/assets/4583553/17846234/a94e7da2-6847-11e6-8f14-f22d34a212ae.png)

**Comment by torusrxxx** [comment]
HKEY_CURRENT_USER\Control Panel\Desktop : REG_SZ WheelScrollLines
"-1":One screen at a time.
