### ISSUE TITLE
Define functions and data instructions without confirmation

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1002]
I don't need a message box to ask me whether I want to define a function. I needn't these message boxes either for defining byte or code because it takes less time to press "B" key several times than enter a number and click "ok".

**Comment by mrexodia** [comment]
I agree with the reasoning of functions, but I disagree with the part about analysis. For this there should be additional hotkeys for the 'Threat selection head as' (which I forgot to add). That way you can rebind the hotkeys if you want the behavior of binding only one unit at a time.
