### ISSUE TITLE
bug with mouse preview?

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1008]
@torusrxxx today I saw some weird behavior with comments in the preview dialog.

![image 1](https://i.imgur.com/Gtvih0X.png)

It puts the comment on the same line as the address label instead of the instruction:

![image 2](https://i.imgur.com/H4KWx8i.png)

**Comment by torusrxxx** [comment]
I have not reproduced it. May be you have to fix it yourself.

**Comment by mrexodia** [comment]
Yeah I was just wondering if it maybe was intentional

**Comment by torusrxxx** [comment]
Oh, this behaviour is what I expected. There is nowhere else in the tooltip that can display a comment. Showing the comment for the entry address is useful since some users prefer to use comments as labels.
