### ISSUE TITLE
Monitor Breakpoint

### ISSUE THREAD

**Issue by faltur** [x64dbg/x64dbg#1014]
Let's suppose we have a target app that calls a function many times, passing a string as the first argument. We need to know every strings that are passed to that function, so we set a "Monitor Breakpoint" on the caller address. After this, when the target executes, the debugger will automatically log the content of the stack to a window or file and continue the execution without any human intervention. This is useful for sniffing incomming packets from a remote server in decrypted format, for example.

**Comment by torusrxxx** [comment]
Have you tried the log text before? Suppose you want to log argument 1 and
2, you can add the following text to "log text":
Arg1:{[esp+4]} Arg2:{[esp+8]}
And then set pause condition to 0 but still enable the breakpoint.
Refer to
http://help.x64dbg.com/en/latest/introduction/ConditionalBreakpoint.html
for more information.

**Comment by faltur** [comment]
Good, thanks for the info.
