### ISSUE TITLE
Help !!!

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#1019]
Hello !! Tell me how to debug a fall ?Can't record video material with the scripts.
Thread 15D8 exit
Process stopped with exit code 0xC0000374
https://exelab.ru/f/index.php?action=vthread&forum=13&topic=19719&page=22

**Comment by mrexodia** [comment]
Could you post more details (perhaps in Russian) maybe a community member here can properly translate it...

**Comment by apan65** [comment]
**mrexodia**, He claims that script engine of debugger crashing when he has used video capturing.

**Comment by Paliha** [comment]
Ок !!
Thank you for documented command, but it is not enough.Use this code:
bool DirExist(char *dirName_in)
{
	DWORD ftyp = GetFileAttributes(dirName_in);
	if (ftyp == INVALID_FILE_ATTRIBUTES)
		return false;
	if (ftyp & FILE_ATTRIBUTE_DIRECTORY)
		return true;
	return false;
}

CMDRESULT cbInstrSavedata(int argc, char* argv[])
{
    if(IsArgumentsLessThan(argc, 4))
        return STATUS_ERROR;
    duint addr, size;
    if(!valfromstring(argv[2], &addr, false) || !valfromstring(argv[3], &size, false))
        return STATUS_ERROR;

    Memory<unsigned char*> data(size);
    if(!MemRead(addr, data(), data.size()))
    {
        dputs(QT_TRANSLATE_NOOP("DBG", "Failed to read memory..."));
        return STATUS_ERROR;
    }

	// static string
	static std::string _name = ".\\minidump";

	// check folder
	if (!DirExist((char*)_name.c_str()))
		CreateDirectory(_name.c_str(), NULL);

	// convert adrr to str
	static std::stringstream stream;
	stream << std::setfill('0') << std::setw(sizeof(duint) * 2) << std::hex << addr;

	// update path
	_name.append("\\");
	_name.append(stream.str());
	_name.append(".mem");

    if(!FileHelper::WriteAllData(_name, data(), data.size()))
    {
        dputs(QT_TRANSLATE_NOOP("DBG", "Failed to write file..."));
        return STATUS_ERROR;
    }
#ifdef _WIN64
	dprintf(QT_TRANSLATE_NOOP("DBG", "%p[% llX] written to \"%s\" !\n"), addr, size, _name.c_str());
#else //x86
	dprintf(QT_TRANSLATE_NOOP("DBG", "%p[% X] written to \"%s\" !\n"), addr, size, _name.c_str());
#endif

    return STATUS_CONTINUE;
}
The code is stable, but video capture is broken stack.
https://www.sendspace.com/file/2b6c6q

**Comment by mrexodia** [comment]
I changed the `savedata` command:

> # savedata

> Save a memory region to disk.

> ## arguments

> `arg1`: The filename. If you use `:memdump:` as name it will save a file as "memdump_pid_addr_size.bin" in the x64dbg directory.

> `arg2`: The address of the memory region.

> `arg3`: The size of the memory region.

> ## results

> This command does not set any result variables.

As for your other issue is there a crash dump available?

**Comment by Paliha** [comment]
>> As for your other issue is there a crash dump available?
Debugger crashes earlier than create a dump file.
>>The filename. If you use :memdump: as name it will save a file as "memdump_pid_addr_size.bin" in the x64dbg directory.
We checked this problem in the latest snapshot (snapshot_2016-08-29_12-36) and old builds have this issue.

**Comment by mrexodia** [comment]
Well I cannot do anything with 100% accurate reproduction steps that I can follow. The change to `savedata` was only a convenience, unrelated to the issue.

**Comment by Paliha** [comment]
ок! 
source code downloaded. 
It will be enough to compile x64dbg.dll or should all ?

**Comment by mrexodia** [comment]
If you take the latest snapshot from http://releases.x64dbg.com you will have the latest version. If you want to make changes only the the dbg rebuilding x64dbg.dll is enough.

**Comment by Paliha** [comment]
not crash dump.
https://www.sendspace.com/file/bnz7ak

**Comment by mrexodia** [comment]
What exactly is the problem in this case? x64dbg appears to function properly, but Deus Ex simply terminates.

**Comment by Paliha** [comment]
Ок !
With my crutch and without video capture, the debugger runs until the end of the script and not falling.

**Comment by mrexodia** [comment]
The debugger does not fail. Probably your video recorder hooks some
functions and the drm detects it in some way.

Try another video recorder, maybe InstantDemo or OBS with a different
hooking method.

**Comment by Paliha** [comment]
Perhaps, but those de drop in on other devices and with other software for video capture.Without him, I repeat that everything works consistently.

**Comment by mrexodia** [comment]
Did you try recording with nvidia shadowplay or another hardware solution?
I cannot solve this problem because I haven't had any trouble with
recording software and you don't provide exact configuration to reproduce
the issue.

**Comment by Paliha** [comment]
Some how we ended up with video material. Wait when will rise eXeLaB and realisim video olomu Denuvo. You again thank you so much for the tool.

**Comment by mrexodia** [comment]
Sure, if you ever find a solution or the actual problem or more details, just reply to this issue but for now I cannot do anything.
