### ISSUE TITLE
Conditional expressions not working properly

### ISSUE THREAD

**Issue by kkthx** [x64dbg/x64dbg#1021]
Error in interpreting condition, i.e. [esp+20] is interpreted as equal to [esp+0x20]. It should be [esp+20] equal to [esp+0x14], because dec(20) == hex(14)

Bug occurs in "Break condition" and in "Log text". I didn't test "log/command condition" but it is probably also affected.

![2016_08_29_20_31_48_x32dbg](https://cloud.githubusercontent.com/assets/4583553/18083439/66f1ffee-6ea3-11e6-9370-1dd4183c23fe.png)

Condition used in photo: "ESP={esp}  [ESP+0x20]={[esp+0x20]}  [ESP+20]={[esp+20]}  [ESP+0x14]={[ESP+0x14]}"

**Comment by mrexodia** [comment]
This is the expected behavior. The default base for numbers is 16. If you
want decimal, use [esp+.20]
