### ISSUE TITLE
registered callback command, argc is never greater than 2.

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#1024]
I created a test plugin to verify, creating a registered command "testcmd"
typing `testcmd` on its own, it shows argc value  is 1
typing `testcmd one` will show the argc value as 2
typing `testcmd one two three four` will show argc value as 2

test plugin called cmdargc: https://dl.dropboxusercontent.com/u/17077376/x64dbg%20Plugins/cmdargc.dp32

Here is the basic code i used:

```
_plugin_registercommand(pluginHandle, "testcmd", cbTest, false);
```

```
extern "C" __declspec(dllexport) bool cbTest(int argc, char* argv[])
{
	_plugin_logputs("[testcmd] testcmd command!");
	_plugin_logprintf("[testcmd] argc: \"%d\"\n", argc);
	return true;
}
```

**Comment by mrexodia** [comment]
Commands in x64dbg are separated by commas, see https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions
