### ISSUE TITLE
Show JMP entry points 

### ISSUE THREAD

**Issue by t3hbb** [x64dbg/x64dbg#1030]
OllyDBG has a > on the left between the address and the hex to indicate that a jump arrives at this point which is really useful if the jump is not visable on the page of code you are looking at. It also shows in the window below the disassembly the address from which that jump is taken.

Any chance of something similar for x64dbg?

**Comment by mrexodia** [comment]
Already implemented. Use xref analysis.

**Comment by torusrxxx** [comment]
Need to add xref analysis to "cfanal" (the type of analysis used by Ctrl+A)

**Comment by mrexodia** [comment]
Hm right... Or perhaps run both cfanal and xanal on that hotkey.
