### ISSUE TITLE
Bad LEA syntax accepted by XEDParse

### ISSUE THREAD

**Issue by sdcode** [x64dbg/x64dbg#1031]
A minor issue with XEDParse:
```
	int 3
	lea rcx, [rdx + rax + 123h]	; source
	; lea rcx, [rax + rdx + 0x123]	; as seen by disassembler
	; lea rcx, [eax + rdx + 0x123]	; hit space and change rax to eax: accepted by XEDParse
	; lea rcx, [eax + 0x123]	; resulting code

```

**Comment by Nukem9** [comment]
Could you please move/reopen this issue in the [XEDParse repo](https://github.com/x64dbg/XEDParse/issues)?

**Comment by sdcode** [comment]
Opened in XEDParse repo. Is there actually a way to **move** an issue??

**Comment by mrexodia** [comment]
moved to https://github.com/x64dbg/XEDParse/issues/8

**Comment by mrexodia** [comment]
No, Github doesn't provide many moderation options for issues...
