### ISSUE TITLE
need api list for breakpoint.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1032]
hi, conveniently for user to set breakpoint, need a official integrated of API list or third plugin, Just like bp MessageBoxA/W, thanks.

**Comment by mrexodia** [comment]
Please make an ini or json file with all the apis and their categories,
perhaps copy from an olly plugin.

**Comment by cxj98** [comment]
yes, can copy ini file from OD 1.10.

**Comment by mrexodia** [comment]
Please make such a file, I will not do it and I cannot implement this without a file.

**Comment by torusrxxx** [comment]
You can already do that with a script file. You can also execute that script file on initialization if you want.

**Comment by cxj98** [comment]
脚本实现不如直接用 api 列表来设断点的好用。

**Comment by torusrxxx** [comment]
API列表很容易转成脚本的，只要每行加上"bp "三个字就行了。而且在符号搜索那里可以选择多个API设置断点。

**Comment by mrexodia** [comment]
@blaquee was working on a plugin to do this.

**Comment by cxj98** [comment]
that's really very good, thanks guys.

**Comment by cxj98** [comment]
where this plugin?

**Comment by mrexodia** [comment]
It is not yet finished but I think this is out of scope for x64dbg so thats
why I closed the issue.

**Comment by mrexodia** [comment]
@cxj98 The plugin has been finished: https://github.com/x64dbg/SlothBP

**Comment by cxj98** [comment]
thanks, will try it.
