### ISSUE TITLE
"tiit" does not work anymore

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1034]

**Comment by mrexodia** [comment]
Hm, it appears the problem is that the trace record is recorded before the condition is evaluated. If you use the equivalent conditional trace `TraceIntoConditional tr.enabled(cip) && !tr.hitcount(cip)` it will also end immediately.

**Comment by torusrxxx** [comment]
It works when I designed it. It works by evaluating the condition before
traceexecute is invoked.

**Comment by mrexodia** [comment]
The code that involves tracing and trace record is very complicated, I have absolutely no idea how to troubleshoot it.

**Comment by mrexodia** [comment]
One interesting observation is that the trace finishes are '0' steps which means the condition is never evaluated...
