### ISSUE TITLE
Hotkeys do not work after switching view with hotkey

### ISSUE THREAD

**Issue by whosdatdev** [x64dbg/x64dbg#1041]
Example: You navigate around, and search for references on something. You take a quick look and decide to go back to the CPU view with Alt+C. Now you press '-' to go to the previous address, however it won't work. If you click into the view once, it will start working again.
Version: v25 Aug 26 2016, 01:39:22

**Comment by mrexodia** [comment]
The reason for is is related to #565 basically the CPU tab has 6 different possible focus points, but the last widget that has focus is not restored when you switch tabs.

**Comment by mrexodia** [comment]
I worked on this quite a bit but I'm not sure if it's fully solved. Please comment.
