### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1042]
set animate step over or whatever animate action, then every time F3 reload from exe, it will always animate step over automaticly, unless delete it from db file, completely new reload exe. also, if enter a infinity loop then it will hand or crash, no stop button provided to stop it, unless terminate the debuger.

**Comment by mrexodia** [comment]
could be, @torusrxxx implemented this feature and I didnt use it yet

**Comment by torusrxxx** [comment]
The official way to stop animation is pause button.

**Comment by mrexodia** [comment]
I think this has been resolved since.
