### ISSUE TITLE
x64dbg crashes while attemping to access an address 

### ISSUE THREAD

**Issue by shiftre** [x64dbg/x64dbg#1044]
Tested on win7 / 32b / eleavted privileges with snapshot_2016-09-04_01-59

[https://www.sendspace.com/file/88g0qt](https://www.sendspace.com/file/88g0qt)

**Comment by mrexodia** [comment]
I cannot reproduce this is any way, could you share a screenshot/video and minidump files?

**Comment by ner0x652** [comment]
@shiftre can you please re-upload your test file(it isn't available anymore on the provided service). Also, please indicate what address you tried to access and x64dbg crashed. Thank you!

**Comment by shiftre** [comment]
That was on an older version, I don't have the file anymore.

You can close it if you wish.
