### ISSUE TITLE
Is Jenkins build server down ?

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1047]
For almost 2-3 weeks, Jenkins link __http://jenkins.x64dbg.com/__ seems to be down

**Comment by Chandlr** [comment]
mrfearless plugin is quite usefull:
https://dl.dropboxusercontent.com/u/17077376/x64dbg%20Plugins/x64dbgUpdateChecker.zip

**Comment by mrexodia** [comment]
The server has been shut down on purpose and will not come back. I still
have to remove the badges though 😀

**Comment by wk-952** [comment]
Alright then, i was asking because one feature that was really good about Jenkins was that you could see which snapshot corresponds to which commits (also downloading pre-compiled files).

@Chandlr Thanks for pointing out that plugin, didn't know about it.

**Comment by mrexodia** [comment]
@wk-952 In theory all new snapshots from now will contain a file called `commithash.txt` that has the full commit hash :+1:
