### ISSUE TITLE
rin0 instructions opcode

### ISSUE THREAD

**Issue by smoning** [x64dbg/x64dbg#1061]
Listing contains ring0 instructions in the ring3 programs.
Compiler FPC 3.0.0 (Lazarus 1.6).

![r0instr](https://cloud.githubusercontent.com/assets/22058186/18321546/15fce514-7537-11e6-9a14-d0b8b1c73cea.png)

**Comment by mrexodia** [comment]
Like I mentioned in the PM, Delphi mixes data and code, what you can try is select `004233FB` in the disassembler, press `B`, enter `5` as size and click `OK`.
