### ISSUE TITLE
CPU window doesn't show the correct code when bp breaks

### ISSUE THREAD

**Issue by hypnz** [x64dbg/x64dbg#1064]
CPU window doesn't show the correct code when bp breaks. I attach gifv for better explanation.
![2016-09-03_21-25-19](https://cloud.githubusercontent.com/assets/6961229/18360047/231c5d78-7605-11e6-84c9-ed5e8c04b82e.gif)

**Comment by mrexodia** [comment]
This can be reproduced on http://www.design8.eu/downloads/twinmotion_2016.zip

**Comment by hypnz** [comment]
And happens only at windows 8.1 native. At windows 7 x64 vm doesn't happening.

**Comment by mrexodia** [comment]
The reason for this is weird loading of .NET modules in Windows 8:

![s](https://i.imgur.com/GcvhvuN.png)

**Comment by mrexodia** [comment]
The interesting part:

```
DLL Loaded: 00007FFAACCD0000 C:\Program Files\Twinmotion 2016.02 Edition\bin\KaRa.Framework.dll
DLL Loaded: 000000CFEFB00000 C:\Program Files\Twinmotion 2016.02 Edition\bin\KaRa.Framework.dll
DLL Unloaded: 00007FFAACCD0000 kara.framework.dll
Thread 299C created, Entry: 00007FFAD83889B0
Thread 1838 created, Entry: 00007FFAD83889B0
Thread 18D0 created, Entry: 00007FFAD78E12B0
DLL Loaded: 00007FFAACCD0000 C:\Program Files\Twinmotion 2016.02 Edition\bin\KaRa.Framework.dll
```

Even though it says that it was loaded on `00007FFAACCD0000` in the end it really isn't (the memory doesn't exist).
