### ISSUE TITLE
Debug in graph ?

### ISSUE THREAD

**Issue by or75** [x64dbg/x64dbg#1065]
If it can, you will be able to do? It would be very convenient :+1:

**Comment by mrexodia** [comment]
Feel free to implement.

**Comment by or75** [comment]
Ty, and it? I could of course try to do, but I'm busy a lot )

![02121637bc3a4c9292372dd74c2f3892](https://cloud.githubusercontent.com/assets/5619678/18360893/8d5fc352-7608-11e6-8bd6-525021194252.png)

**Comment by blaquee** [comment]
You can do that in the dump view

**Comment by mrexodia** [comment]
Use the data copy and create separate issues. I am also very busy, I nearly
work on this full time and there are still 230 issues open.

**Comment by mrexodia** [comment]
Second request has been implemented: 

![s](https://i.imgur.com/NnLChjD.png)

**Comment by or75** [comment]
Thank you so much ^_^

**Comment by mrexodia** [comment]
The original issue was not solved. You can still not debug in the graph.

**Comment by or75** [comment]
wait :)

**Comment by gmastergreatee** [comment]
Has the original issue been implemented?

**Comment by mrexodia** [comment]
Yes
