### ISSUE TITLE
Debugger hangs when breakpoint bytes check returns a mismatch

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1066]
Prepare 2 applications, let's call the first `one.exe` and the second `two.exe`

1. Debug `one.exe` and place some software breakpoints anywhere
2. Rename `two.exe` to `one.exe`
3. Try to debug the newly renamed file (`one.exe`) and the debugger will hang

EDIT: log gets stuck at the last line:
```
Database file: E:\***\xxx.exe.dd32
Loading commandline...
Process Started: 00400000 E:\***\xxx.exe
Loading database...
0ms
Breakpoint xxxxxxxx has been disabled because the bytes don't match! Expected: XX XX, Found: YY YY
```

EDIT 2: Forgot to mention, manually deleting the breakpoints records from the db file will solve this issue.

Reproduced on `snapshot_2016-09-08_05-05`

**Comment by mrfearless** [comment]
Same thing would occur when debugging a program that I've recompiled during testing, mainly because the bytes would change - due to additions I've made to the code or commenting out code before recompiling. 

I would just delete the db for the particular file as well

**Comment by wk-952** [comment]
Last snapshot that doesn't have this issue: `snapshot_2016-09-07_06-08`,
on this snapshot, breakpoints with mismatching bytes are simply disabled without any hangs.

The issue was introduced on: `snapshot_2016-09-07_03-46`,
whose `commithash.txt` is: a0ef9a0d9c2704791f5e315f678543e6a5f9bf4d

**Comment by mrexodia** [comment]
Thanks for the report, should be fixed now!

**Comment by wk-952** [comment]
Thanks a lot.
