### ISSUE TITLE
assemble failed when with no "0x" prefix

### ISSUE THREAD

**Issue by JohnWins** [x64dbg/x64dbg#1067]
Hi,
There should be a bug when assemble command in constant without "0x" prefix by Keystone and asmjit assembler engine.
Here show you pictures.

![111](https://cloud.githubusercontent.com/assets/18698031/18378104/7d728bf6-769d-11e6-9a37-2b3af9be9f8c.png)

![2222](https://cloud.githubusercontent.com/assets/18698031/18378107/83d4345e-769d-11e6-88c1-1ad146a5e2fa.png)

![333](https://cloud.githubusercontent.com/assets/18698031/18378114/8fbab838-769d-11e6-81b1-d4f7f6af0d5d.png)

**Comment by mrexodia** [comment]
Keystone doesn't want to implement this, ask at https://github.com/keystone-engine/keystone/issues/11
