### ISSUE TITLE
Last 2 Snapshots are crashing on loading db files from older version.

### ISSUE THREAD

**Issue by MrIQZero** [x64dbg/x64dbg#1068]
Both snapshots versions after version snapshot_2016-09-07_06-08.7z are crashing on loading old db files.

I'm copy-pasting old db files from older snapshot version into recent snapshot version but they seems to be crashing/stops working on loading the .exe, meanwhile breakpoint windows don't show any breakpoints and software crashes when you try to go into memory tab.

In case old db are not placed in db folder, x64dbg seems to run just fine.

**Comment by mrexodia** [comment]
Could you upload some of these old db files?

**Comment by wk-952** [comment]
Can't reproduce this on `snapshot_2016-09-09_10-06`, here's what i did:
1. Using an old build `snapshot_2015_2_20` i debugged `x96dbg.exe` that comes with `snapshot_2016-09-09_10-06` and placed exactly 3 software breakpoints at RVAs `0x4FF4`, `0x502D` and `0x507C`
2. Copied the db file from `snapshot_2015_2_20` to `snapshot_2016-09-09_10-06` and again debugged `x96dbg.exe`, but the debugger didn't hang/crash.

@MrIQZero assuming you're using `snapshot_2016-09-09_10-06`, could you try this db file, it's created using `snapshot_2015_2_20`, change extension to `.dd32`
[x96dbg.exe.txt](https://github.com/x64dbg/x64dbg/files/463639/x96dbg.exe.txt)

**Comment by MrIQZero** [comment]
i was able to recreate the issue using x64dbg and mspaint.exe (windows 10). 
[mspaint.exe.dd64.txt](https://github.com/x64dbg/x64dbg/files/463729/mspaint.exe.dd64.txt)

It was created using build which was compiled on sep_5_2016 and its crashing/freezing the latest build viz compiled on sep_8_2016(latest snapshot) sorry i don't know the snapshot version of the x64dbg it was created in.

**Comment by mrexodia** [comment]
Is it freezing or actually crashing and throwing an exception?

**Comment by MrIQZero** [comment]
its freezing initially but when i click on memory tab then it crashes.

**Comment by mrexodia** [comment]
Alright, I will check it out when I'm back. Just put the db in the folder
and opening mspaint reproduces it?

**Comment by MrIQZero** [comment]
@wk-952 your db for 32dbg seems to run just fine for x96dbg.exe.

**Comment by MrIQZero** [comment]
@mrexodia yes

**Comment by wk-952** [comment]
@MrIQZero you mentioned that you're using snapshot from `sep_8_2016`, is that right ?
because that one had an issue with db files, see this #1066 .
The latest one is `sep_9_2016`
![untitled](https://cloud.githubusercontent.com/assets/11916365/18385176/3bd0090c-768f-11e6-90cc-513a1d2c7433.png)

**Comment by MrIQZero** [comment]
@wk-952 thanks i'll go and check it out. i downloaded the latest snapshot from SourceForge.net but seems like it was an older version. Thanks

**Comment by mrexodia** [comment]
The snapshots on sourceforge are daily they are uploaded around 6am
Amsterdam time.

**Comment by MrIQZero** [comment]
@wk-952 and @mrexodia thanks guys its working great. db seems to be loading just fine in the latest snapshot.

Thanks again.
