### ISSUE TITLE
Missing string references

### ISSUE THREAD

**Issue by piaoasd123** [x64dbg/x64dbg#1071]
Opening the attached sai2.exe will show a windows with string:"The program is started in the restricted mode because a license certificate is not installed." However, the string can only be manually accessed by putting in address: 00000001401D5840 and does not show up in string references.

[sai2.zip](https://github.com/x64dbg/x64dbg/files/464245/sai2.zip)

**Comment by mrexodia** [comment]
Are there actual references to the string that you know are missing? If the
string is not directly referenced in the disassembly it is not found.

**Comment by piaoasd123** [comment]
Yes, see attached picture:
![111](https://cloud.githubusercontent.com/assets/5825014/18394366/a63d58a6-7687-11e6-868f-fe85a1f53c02.png)

**Comment by piaoasd123** [comment]
Manually inspecting the binary shows the string is indeed inside the binary, but I suspect because those strings are stored as wchars, x64dbg does pick them up during string dump.

**Comment by piaoasd123** [comment]
Oh, sorry I misread your comment. I think the string pointer is calculated in runtime, but it referenced in the disassembly:
![222](https://cloud.githubusercontent.com/assets/5825014/18394557/8a6d3794-7688-11e6-9d6b-3584618e9cf2.jpg)

**Comment by Nukem9** [comment]
So you need a feature to list all of the strings like IDA does, even **un**referenced ones...Right now only addresses with a memory reference (`dword ptr [0xDEADCODE]`) will show up.
