### ISSUE TITLE
CallStack not showing correctly

### ISSUE THREAD

**Issue by Mark-Joy** [x64dbg/x64dbg#1072]
Here is a comparison between x64Dbg and Olly
![callstack1](https://cloud.githubusercontent.com/assets/22109528/18407734/d0e5dcec-7743-11e6-9aba-152b149e3a6b.png)

Stack Frame of x64Dbg
![callstack2](https://cloud.githubusercontent.com/assets/22109528/18407740/e42b3d38-7743-11e6-8a4d-5b9838364a42.png)

**Comment by mrexodia** [comment]
Is it the same thread?

**Comment by Mark-Joy** [comment]
They are all in main (same) thread.

**Comment by wk-952** [comment]
@Mark-Joy when this happens try the following:
1. Go to `Threads` tab
2. Right click on any thread other than `Main`
3. Select `Switch Thread`
4. Again go to `Threads` tab 
5. This time right click on the `Main` Thread and select `Switch Thread`

**Comment by Mark-Joy** [comment]
It's still showing the same, nothing changed.
I attached the target..

[DVDMenuStudio.zip](https://github.com/x64dbg/x64dbg/files/465324/DVDMenuStudio.zip)

**Comment by mrexodia** [comment]
You should try looking at the actual stacks and see that they are unrelated. `GetMessageA` or the address `5B0449` are nowhere to be seen in x64dbg.

**Comment by Mark-Joy** [comment]
GetMessageA is called from 5B0449, after the call it will return to 5B044F.
CallStack in x64dbg is missing 5ABF2E and 4DC0D6 which are showed in Olly.

Stack frame of x64dbg has these information, but callstack is not showing them.

![callstack4](https://cloud.githubusercontent.com/assets/22109528/18409524/546aaf50-7773-11e6-99f9-74bdd5035c7a.png)

**Comment by wk-952** [comment]
@mrexodia i loaded the application and entered fake serial/info so that the error message would show up.

This is what the debugger showed at first:
![1](https://cloud.githubusercontent.com/assets/11916365/18409512/289e0356-7749-11e6-8f70-bfda660f7435.png)
![2](https://cloud.githubusercontent.com/assets/11916365/18409515/35c74a10-7749-11e6-92c6-0baa05c51249.png)


After doing the steps i mentioned above:
![3](https://cloud.githubusercontent.com/assets/11916365/18409518/4c07d8da-7749-11e6-8ac5-73149dcace6b.png)
![4](https://cloud.githubusercontent.com/assets/11916365/18409520/51a1b7d4-7749-11e6-942c-ad7a66acd962.png)

**Comment by Mark-Joy** [comment]
@wk-952 Don't enter fake serial. Just run the program, wait for the nag showing up, then pause. You will see my screen shot.
Do the same with Olly.

**Comment by mrexodia** [comment]
@Mark-Joy the pause button in x64dbg works differently from Olly and pauses in a different place, the callstacks are not comparable at that state.

**Comment by Mark-Joy** [comment]
Stack frame (CPU tab) of x64dbg showed the information of 5ABF2E and 4DC0D6 (which is same as Olly), but callstack is not showing them..
Please check again the below picture 
![callstack4](https://cloud.githubusercontent.com/assets/22109528/18409655/0ff3a9cc-7777-11e6-94b0-d6845b31ef3f.png)

**Comment by mrexodia** [comment]
In Olly they are not part of the call stack either, olly just gives information on addresses that are around the callstack area. Look in the stack if you want these. See this screenshot for the mapping between Olly and x64dbg:

![s](https://i.imgur.com/N9g6F36.png)

**Comment by Mark-Joy** [comment]
I don't agree. Olly clearly showed that 5ABE4D is called from 4DC0D1; 5AEFC8 is called from 5ABF29, which is why they are in CallStack. Olly show the calls and the arguments to the calls only, not just pick some information around.

![callstack3](https://cloud.githubusercontent.com/assets/22109528/18410170/b1a9e3f0-7784-11e6-901d-98bef0475132.png)

**Comment by mrexodia** [comment]
Okay I'm closing this issue. If you have a fix send a pull request.

**Comment by torusrxxx** [comment]
There are more call stack frames in the new version.
