### ISSUE TITLE
Decode argumens of default WinAPI functions

### ISSUE THREAD

**Issue by kkthx** [x64dbg/x64dbg#1076]
Like olly does;
Olly:
![olly](https://cloud.githubusercontent.com/assets/4583553/18409616/95b0ba5e-774b-11e6-823e-b8706bf6e4ec.png)

x64dbg:
![x64dbg](https://cloud.githubusercontent.com/assets/4583553/18409614/91c207b8-774b-11e6-9437-11f18e636b02.png)

Maybe create some kind of "api" to create such decoding rules for other functions/frameworks e.g. for Qt functions

**Comment by mrexodia** [comment]
duplicate
