### ISSUE TITLE
If instruction with breakpoint gets changed, wrong instructions are displayed

### ISSUE THREAD

**Issue by whosdatdev** [x64dbg/x64dbg#1080]
Example: Set breakpoint on user32.MessageBoxW. Write a program that modifies the first instruction, for example change the first byte to "push rax" (0x50). x64bdg will now display wrong instructions. The problem solves itself if you delete the breakpoint.
Build from Aug 26

**Comment by mrexodia** [comment]
This is true, but there is no way to solve this. There is a memory filter with the original bytes over breakpoints so you don't have to look at loads of `int3` instructions, but I don't plan to try to support self-modifying code because it breaks too many assumptions.

**Comment by blaquee** [comment]
This is a job for a plugin that registers the breakpoint callback perhaps.
