### ISSUE TITLE
Address navigation from memory map

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#1082]
Navigating to an address from the memory map is not the same as previous builds.

For example in previous builds, double clicking on a section in the memory map would switch to that address in the cpu view. Now it will switch to cpu view but shows previous contents, doesnt update with correct address. Only addresses from sections that have .text and .code are auto synced with main cpu view when double clicked in memory map.

**Comment by mrexodia** [comment]
It will now automatically follow them in the dump view if they are not executable. See http://x64dbg.com/blog/2016/09/11/weekly-digest-3.html#intelligent-following-of-addresses for more information

**Comment by mrfearless** [comment]
ok

**Comment by blaquee** [comment]
Alternatively, if you want to force it to show in CPU, change that memory pages protection to executable and it should work that way

**Comment by mrexodia** [comment]
Or just right click and follow in disassembler
