### ISSUE TITLE
Follow in memory map doesn't auto switch to the corresponding tab

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1083]
The right click menu item `Follow in memory map` works as intended and highlights the region containing the address, but doesn't automatically switch to the `Memory Map` tab.
Is this the intended behavior ?

**Comment by wk-952** [comment]
Thanks!

**Comment by mrexodia** [comment]
Just a side note, have you considered joining [telegram](http://telegram.x64dbg.com), [gitter](http://gitter.x64dbg.com) or [irc](http://irc.x64dbg) would be nice to have you there!
