### ISSUE TITLE
Can't delete breakpoint if module is not loaded

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1086]
Say I am analyzing a program which loads a DLL dynamically. If I breakpoint a function in that dynamically loaded DLL and the DLL gets unloaded, the breakpoint cannot be removed until I load the module again. Upon pressing the button x64dbg says "Breakpoint [address] not found."

**Comment by ViRb3** [comment]
Here's an example with Notepad.
1. Break on EP.
2. Enable "break on DLL load" and continue execution. You should break on the loading of "uxtheme.dll".
3. Set breakpoints in the "uxtheme.dll" module, like so:
https://i.imgur.com/4qPOciQ.png
4. Restart the program and try to delete the breakpoints. Mind the message bottom-left.
https://i.imgur.com/RkEPwZX.png

**Comment by Nukem9** [comment]
This fails because BpGet is using the address of the breakpoint only. The name is blank so it doesn't search for it. Module isn't loaded -> `ModHashFromAddr` fails.

@ViRb3 if you really need to delete them, you can set a name for the breakpoints (then remove em). Otherwise you'll need to wait.

**Comment by ViRb3** [comment]
@Nukem9 Thanks for the nice workaround! I wasn't really bothered by it, just wanted to put it up here. Probably a BP index system should be sufficient to fix this issue.

**Comment by bkbiradar** [comment]
Just
