### ISSUE TITLE
Setting a Hardware BP with commands and `er` doesnt hit breakpoint

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#1093]
While debugging an application I noticed that if I set a hardware Breakpoint with the UI and continue execution, the breakpoint triggers. However if this same thing is done via the command bar, the breakpoint is not triggered.

`bph esp,,4` 
`er` 

Will let the program execute but never trigger the breakpoint, even though the breakpoint resolves to the same address as when I do via the context menu.

**Comment by mrexodia** [comment]
Try the command "bplist" it should show the exact type of hardware
breakpoint created, I think now you create a breakpoint on execute. Also I
never saw the command "er" ever but probably it's the same as "erun".

**Comment by mrexodia** [comment]
The correct command is `bph csp, r`
