### ISSUE TITLE
Hardcoded constant

### ISSUE THREAD

**Issue by AlexWMF** [x64dbg/x64dbg#1099]
What the const is here https://github.com/x64dbg/x64dbg/blob/development/src/bridge/bridgemain.h#L638
```
typedef struct
{
    DWORD code;
    char name[128]; // << here
} LASTERROR;
```

Could you define it explicitly?

**Comment by mrexodia** [comment]
It's completely arbitrary, but you could use sizeof(int)*32 😀

**Comment by AlexWMF** [comment]
Could you define it somehow? :)

**Comment by mrexodia** [comment]
I really don't see the point. You only use query operations on this structure and sizeof(s.name) will work fine...
