### ISSUE TITLE
freeze stack is broken

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1103]
Freeze stack breaks the selection of addresses.

**Comment by shamanas** [comment]
I'm gonna take a shot at this one.

**Comment by shamanas** [comment]
@mrexodia What exactly is the intended behavior?  
The fact that you cannot reselect is because of this code:
```c++
// CPUStack.cpp:425
    // This sets the first visible row to be selected when stack is frozen, so that we can scroll the stack without it being reset to first selection
    if(bStackFrozen && rowOffset == 0)
        setSingleSelection(wRva);
```
(Which is right at the beginning of CPUStack::paintContent)  
Removing these lines fixes the selection but I'm not sure if it should do something else in addition?

**Comment by mrexodia** [comment]
This is a feature from OllyDbg:

> Lock stack - disables automatical stack scrolling to the actual contents of ESP each time the execution is paused. Alternatively, press button "Address" in the bar. When scrolling is disabled, button changes to "Locked".

So basically it should not automatically scroll to ESP/RSP when for example stepping over `push eax`

**Comment by shamanas** [comment]
@mrexodia Ok, I'll test it out and get back to you, thanks for the quick answer :)

**Comment by mrexodia** [comment]
@shamanas we also have various chat rooms (http://x64dbg.com/#contact)
