### ISSUE TITLE
Not all Uppercase in Disasm

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1107]
![hoyo](https://cloud.githubusercontent.com/assets/17880848/18698309/b7bd9272-7fe6-11e6-8fd4-dba6c5e403f5.gif)

**Comment by mrexodia** [comment]
Yeah, module names and assembly are not affected by the option, mainly
because labels are case sensitive.

**Comment by gmastergreatee** [comment]
Thanks :+1:

**Comment by mrexodia** [comment]
Okay, I removed the uppercasing of module names.
