### ISSUE TITLE
Copy Selection in Dump copies whole line(s)

### ISSUE THREAD

**Issue by 10miles** [x64dbg/x64dbg#1109]
snapshot_2016-09-20_05-53

Whatever selection in dump, Copy > Selection (Ctrl+C) copies whole line(s) which may be better than nothing but it's not what it says it is.

The problem is probably with interpretation of bytes/symbols in lines.

Addresses should be line addresses.
Selected bytes/symbols should be at their proper addresses.
Unselected bytes/symbols should be intervals.

00000000286BBB50  .. .. 31 32 33 34 .. .. .. .. .. .. .. .. .. ..  1234

Thanks. :(

**Comment by mrexodia** [comment]
The dump converts data to text line by line and simply outputs the lines
that have a selection in them. I can rename the option to "Copy selected
lines" but that's just as confusing.
