### ISSUE TITLE
Break on DLL load causes x32dbg to freeze

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1111]
Steps to reproduce:
1. Enable 'break on DLL load'
2. Start debugging. You will break on the first DLL load.
3. Click 'Run' to break on a few consequent DLLs.
4. Try to Revert or Stop. x32dbg freezes.

Closing x64dbg looks like it opens a second x32dbg window and runs the debugged program, avoiding all BPs.

**Comment by ViRb3** [comment]
@mrexodia Here's a GIF targeting IDA 6.8 x32. Because a video always says more :)
![bug1](blob:http://imgur.com/443c7258-153c-47b1-a8e4-bacc991ec26b)

**Comment by ViRb3** [comment]
This continues happening if I leave x64dbg to close after 10 minutes:

![bug1-2](http://gifyu.com/images/bug1-2.gif)

**Comment by ViRb3** [comment]
@mrexodia Only x32dbg is affected. Can be reproduced by debugging x32dbg.exe itself for an example.

**Comment by wk-952** [comment]
@ViRb3 Do you have any antivirus ?
If yes, try completely disabling it (and also disable it's startup with the system), reboot the OS and see if it's still persists.
I had the exact same issue and it was because of Kaspersky, see issue #516

**Comment by ViRb3** [comment]
@wk-952 ![lol](https://i.imgur.com/FczxpHZ.png)
And I thought that only Bitdefender installed highly destructive hooks... Thank you a bunch!

**Comment by blaquee** [comment]
Did you confirm that it was the AV?

**Comment by ViRb3** [comment]
@blaquee Yes, it was Kaspersky. I followed @wk-952's instructions to disable it on startup and x64dbg is even considerably faster now. Lol.
