### ISSUE TITLE
Break on specified DLL causes x64dbg to freeze

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1112]
I think this has something to do with my previous issue: https://github.com/x64dbg/x64dbg/issues/1111
I apologize for having to mask the debugged module. x64dbg stop responding once I click the X.

GIF:

![bug2](http://gifyu.com/images/bug2.gif)

**Comment by mrexodia** [comment]
Yeah it's probably a duplicate of #1111 because break on DLL breaks only on the DLL you requested instead of all.
