### ISSUE TITLE
This crackme cannot run

### ISSUE THREAD

**Issue by bukuxiaoheshang** [x64dbg/x64dbg#1114]
This crackme cannot run,alway breakat 77C9C0A6 ,Ingore nvalid

77C9C0A3 | 8D 41 04                 | lea eax, dword ptr ds:[ecx+4]         |
## 77C9C0A6 | F0 0F BA 30 00           | lock btr dword ptr ds:[eax], 0        |
77C9C0AB | 0F 83 99 0B 00 00        | jae ntdll.77C9CC4A                    |
77C9C0B1 | 8B 42 24                 | mov eax, dword ptr ds:[edx+24]        | edx+24:"@,"
77C9C0B4 | 89 41 0C                 | mov dword ptr ds:[ecx+C], eax         |
77C9C0B7 | C7 41 08 01 00 00 00     | mov dword ptr ds:[ecx+8], 1           |
77C9C0BE | FF 87 00 02 00 00        | inc dword ptr ds:[edi+200]            |

download:  http://pan.baidu.com/s/1o8EnL0m

I don't know whether it is a  bug,please help me.Thanks

**Comment by mrexodia** [comment]
It's called system breakpoint, you can see it in the log. Disable it in the options.
