### ISSUE TITLE
x32dbg crashes on loading if a dump window is detached

### ISSUE THREAD

**Issue by extremecoders-re** [x64dbg/x64dbg#1115]
**Steps to reproduce:**

1. Open a blank instance of x32 dbg with/without any executable loaded
2. Detach any dump window
3. Load any executable or restart if already loaded
4. x32dbg crashes

**x32dbg version:** snapshot_2016-09-24_02-25
**OS version:** Windows 7 x86 SP1

Additional Info:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	57e66f8a
  Fault Module Name:	x32gui.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	57e67082
  Exception Code:	c0000005
  Exception Offset:	000391b3
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
```

**Comment by mrexodia** [comment]
The bug has been reproduced, but it cannot be solved quickly. Detaching has been disabled for now.

**Comment by extremecoders-re** [comment]
Thanks for checking that out. 

There were also other issues with detached dump tabs. 
Follow in Dump <1,2....> does not work for detached dump tabs,

**Comment by mrexodia** [comment]
> There were also other issues with detached dump tabs. 

Yes, this is the reason I disabled dump tab detaching until it has been fixed.
