### ISSUE TITLE
Save current workspace layout to a file

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#1122]
Just like IDA and Olly save the user workspace layout after the user ends the debuggin session, so she or he doesn't have to configure it all over again (columns/windows layout, tabs opened/closed, etc). Can this be done?...I mean, like saving all these settings on any type of config file?

**Comment by mrexodia** [comment]
Most things are saved, enable save tab order, column widths are saved, related issues are #812 #368 only the QSplitter layouts are current not saved.

**Comment by ThunderCls** [comment]
The QSplitters are the ones I'm mostly referring to here. Also, once the tabs management stuff (closing/adding) is working, it would be great to save/recall them as well.

**Comment by mrexodia** [comment]
Some progress was made in #1125
