### ISSUE TITLE
Memory Breakpoints

### ISSUE THREAD

**Issue by malexkiy** [x64dbg/x64dbg#1123]
Memory Break points don't work in x32 version of program. Tried with the latest version

**Comment by mrexodia** [comment]
Please give more details it works fine for me

![membp](https://i.imgur.com/Xgfi76h.png)

**Comment by malexkiy** [comment]
Here the screenshots:
Program continues execute, membp doesn't interrupt it.
![1](https://cloud.githubusercontent.com/assets/12190704/18934045/53c84712-85e0-11e6-80b4-36532bd441fa.png)
![2](https://cloud.githubusercontent.com/assets/12190704/18934046/53c8cc0a-85e0-11e6-8923-3c452e4480b5.png)

**Comment by mrexodia** [comment]
What are the page protections and what type of memory breakpoint did you
set?

**Comment by malexkiy** [comment]
Well, the page protection is "-R---" , I've set Access breakpoint. Set with commands "bpm, 'addr', 0, r" and "membp 'addr', 0, r". x64dbg works with x64 program without any problems, but x32dbg...

**Comment by mrexodia** [comment]
After you set the memory breakpoint, what protection does it show in the
memorial for the page?

**Comment by malexkiy** [comment]
It shows "-R--G"

**Comment by mrexodia** [comment]
Memory breakpoint on access appears to not break on execute probably the wrong enum set somewhere.

**Comment by mrexodia** [comment]
Okay, the command `bpm addr, 0, r` would only break on *read* of the page addr is in. You can now use `bpm addr, 0, a` and it will break on read+write+execute. The menus now also work this way.

**Comment by malexkiy** [comment]
Hmm... But in x64 version the same is working, in x32 problems. I can set memory breakpoint at required address and it'll interrupt the program, when memory at this address will be read.

**Comment by malexkiy** [comment]
I can't use such command, as I need to know, when the memory will be read, not written or executed

**Comment by mrexodia** [comment]
I tested `bpm addr, 0, r` on both x32 and x64 and they work as expected (break when an address in the page of addr is read).

**Comment by malexkiy** [comment]
Tested with commit 174b845?

**Comment by malexkiy** [comment]
Yeah, now it works correctly.
Thanks!

**Comment by mrexodia** [comment]
Glad to help 👍🏻
