### ISSUE TITLE
Something wrong with checkboxes (GUI only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1126]
Very minor glitch/bug
![a](https://cloud.githubusercontent.com/assets/11916365/18970592/1cc03fc4-8692-11e6-87e5-0591880a11a9.png)
Single click on any check box and it'll jam/hang like this,
click again and it'll be ticked correctly.

**Comment by mrexodia** [comment]
Kinda weird, but should be fixed now...
