### ISSUE TITLE
Feature request:Graph with support of string and in the cpu tab for viewing characters on cmp  

### ISSUE THREAD

**Issue by clshack** [x64dbg/x64dbg#1128]
Good morning, 
I was trying this debugger on a very easy crackme. 
[http://challenge01.root-me.org/cracking/ch15/ch15.exe](http://challenge01.root-me.org/cracking/ch15/ch15.exe)
I think that could be great having in the graph, the strings found during the analysis.
Another feature could be decoding and print on the right the characters compared on the **cmp** instruction.
On the image you can see better:
![Image of x64dbg](http://i.imgur.com/x1KKWhD.png)

Have a nice day and my compliment for your work !

**Comment by mrexodia** [comment]
You can use the info box for displaying character values

![ch](https://i.imgur.com/vIlNvZ6.png)

**Comment by mrexodia** [comment]
https://mega.nz/#!3k4njTIC!sKn2aWlbcb69njZARqmbwzLJEyb_lAw_OdRBi8Tks6A

**Comment by clshack** [comment]
@mrexodia I know that I can use the box, the goal was having all on the bar without looking the box for every instruction while debugging :)

**Comment by mrexodia** [comment]
okay I opened #1131 and #1132 to separate both feature requests
