### ISSUE TITLE
Some module handles show as ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1140]
Not sure if this is an issue, but x64dbg is unable to display the names of some handles. Running with Debug Privilige + Administrator. Process Hacker, on the contrary, always succeeds.

Example with Explorer:
![](https://i.imgur.com/ENFWtJG.png)

**Comment by mrexodia** [comment]
Yes x64dbg cannot get handles for certain types because they block infinitely. Process hacker has a driver and can do more things.
