### ISSUE TITLE
plugload - minor issue

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#1141]
Noticed an issue with plugload, if you type `plugload` and press enter (without specifying a plugin name) it shows that it cant find `x.dp32`, where `x` can be a random letter or non-printable character each time the command is entered on the command bar:
![](https://s20.postimg.org/cxueskkkd/plugloaderror.png)

**Comment by torusrxxx** [comment]
Seems like a invalid pointer dereference

**Comment by mrexodia** [comment]
Yes genuine forgot to check the number of arguments.

**Comment by blaquee** [comment]
:)
