### ISSUE TITLE
Add Powershell scripting support

### ISSUE THREAD

**Issue by Delapro** [x64dbg/x64dbg#1149]
Please add Powershell scripting to x64dbg. 

Scripting is already possible with Python #87, but I think for people used to work with Powershell it is more powerful. Powershell 2.0 is available on every Windows since Win7, without extra installation efforts.

Powershell provides many ways to integrate it via automation runspaces. Powershell allows remoting, so you can automate the debug script from another computer. This is very handy if you try to debug timing critical input focus changes. To start: https://msdn.microsoft.com/en-us/library/ee706563(v=vs.110).aspx

Especially if I think about this blog article: http://x64dbg.com/blog/2016/07/09/introducing-contemporary-reverse-engineering-technique-to-real-world-use.html. Stepping is dead, automation is key and Powershell is one of the best automation engines!

**Comment by mrexodia** [comment]
I don't plan to implement this. If you have any progress feel free to post here.
