### ISSUE TITLE
new feature need implement.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1151]
currently the jump line is too weak in x64dbg, in OD if more address jump to the same destination, then click in destination will show on jump line with all address, but in x64dbg only one jump line per one address. and no matter scroll up or down, the jump line is always there in the OD, not disappear, click in destination will know where it jump come from, other is if jump line is disappear then click destination will display again or click any jump address, hope implement.

Please see picture for more description:

http://oi68.tinypic.com/2n9yec6.jpg

**Comment by wk-952** [comment]
If i'm not mistaken, what you're asking for is called `cross references analysis`,
which basically displays all sources targeting a certain branch (all jmp/call/jnz/jae/etc... targeting a certain address).
If this is true, then luckily this has been implemented a long time ago, type `analx` in the command bar to invoke it.

This is the normal analysis done by x64dbg:
![normal_anal](https://cloud.githubusercontent.com/assets/11916365/19181589/6f007f88-8c6e-11e6-9082-dabec792d901.png)
3 lines for 3 jmps, each targeting the same destination, but as you said if we scroll up/down those lines will disappear, also clicking on the destination won't tell you who is jmp-ing to here.

This is the cross references analysis (after typing `analx`):
![x_anal](https://cloud.githubusercontent.com/assets/11916365/19181658/dc6eef1e-8c6e-11e6-8340-8af54df7baa9.png)
1 line connecting all sources together, selecting the target will tell you all the sources, also if you scroll up/down it won't disappear.
Notice how the red line points to each source (each jmp) by a small dash.

Another thing that's very useful in the cross references analysis is that you could select a certain destination then press `x` to see all the sources targeting it:
![x_anal2](https://cloud.githubusercontent.com/assets/11916365/19181957/8df1c2d8-8c70-11e6-99c8-38e067b61f63.png)
you could then double-click on any source to follow it in the `CPU` tab

There are other analysis types if you're interested, this is the official documentation for them:
http://x64dbg.readthedocs.io/en/latest/commands/analysis/

Very sorry if none of that is what you were asking for :smile:

**Comment by cxj98** [comment]
OK, I just discovery it. but why not set it to default without type analx in commandbox? and why not set to default analysis without press Ctrl + A?

**Comment by mrexodia** [comment]
Yeah I just said this two times in a reply to another issue, you should
really read better @cxj98
