### ISSUE TITLE
Closing Debugger

### ISSUE THREAD

**Issue by ner0x652** [x64dbg/x64dbg#1157]
After hitting the close button the 'closing debugger' action freezes. A forced close is needed to finish closing the debugger.

Details:
x64dbg v25 - compiled on Oct 10 2016
Windows OS 10 x64 Enterprise

**Comment by mrexodia** [comment]
That button should be disabled. You can disable the close dialog in the options if you want the debugger to close in the background.

**Comment by mrexodia** [comment]
Is this issue still relevant @ner0x652 ?

**Comment by ner0x652** [comment]
@mrexodia no, I haven't encountered this issue for a long time. Thanks for asking!
