### ISSUE TITLE
Failed to save settings

### ISSUE THREAD

**Issue by ner0x652** [x64dbg/x64dbg#1163]
Exiting debugger results in this error:
![capture](https://cloud.githubusercontent.com/assets/2598963/19411167/19cbe6ea-9305-11e6-866a-b072fc3d6ca8.PNG)

OS: Windows 10 x64 Professional
x64dbg: Oct 13 2016

**Comment by mrexodia** [comment]
Place it in a folder where it has write rights.

**Comment by ner0x652** [comment]
Yeap... ran it with admin rights, no error.

**Comment by mrexodia** [comment]
You can give write rights to "User" or "Everyone" in the directory to not
have to use administrator rights every time.

**Comment by 002Zer0Tw0** [comment]
so i changed access folder for non administration user mode changed it to allow permissions like "Full control" & "modify", it worked for me without running run-administrator without error popup at closing the program "x64Dbg/x86Dbg" ^O^

**Comment by mrexodia** [comment]
There is also a new (undocumented) option that will save the database and settings in %AppData%. Simply create a file `userdir` (empty or you can put a path in there) and it should work without having to make the x64dbg directory writable.

**Comment by Manas-salian** [comment]
Thanks
