### ISSUE TITLE
Allow F4 in graph view

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#1169]

**Comment by cengizIO** [comment]
Hello there!

I'd like to work on this, if nobody else is already working.

**Comment by mrexodia** [comment]
Thanks for your interest! You should probably modify the `runSelection()` function in MainWindow.cpp to use the graph selection instead of the disassembly selection if the graph is currently in focus.

**Comment by cengizIO** [comment]
Thanks for pointers! (pun intended) 

It took me a while to fire a windows dev environment, now I'm finally working on this.

**Comment by mrexodia** [comment]
Alright sounds good!

**Comment by cengizIO** [comment]
Well, there goes my motivation to work on your project.. 

Yes, I didn't expect any recognition for what I was doing. 

And yes, it's a piece-of-cake task for experienced Qt developers.

But closing an assigned issue without any notification to the assignee is a red flag for me.

Thanks anyway.

**Comment by mrexodia** [comment]
@cengizIO I'm sorry to hear that, but what was I supposed to do? @kkthx sent a pull request that does the job first and probably didn't see/care that someone was already working on the issue.

Any work is greatly appreciated and if you already set up the environment there are still around [40 open issues](https://github.com/x64dbg/x64dbg/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aeasy%20label%3Agui) left.

As for recognition, everybody contributing any code (however insignificant it might seem) gets listed in the [Contributers](https://github.com/x64dbg/x64dbg#contributors) section and (usually) outlined on the [blog](http://blog.x64dbg.com). If you see anyone missing, please notify me and it will be corrected.
