### ISSUE TITLE
x64dbg crash

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1176]
![hoyohoyo](https://cloud.githubusercontent.com/assets/17880848/19516347/2f6bd0ca-9619-11e6-8692-f9717fbc0b74.gif)

[dump-19102016_1628200541.dmp.txt](https://github.com/x64dbg/x64dbg/files/538708/dump-19102016_1628200541.dmp.txt)

**Comment by mrexodia** [comment]
A fix for this is underway right now.
