### ISSUE TITLE
Fatal GUI Exception when saving CPU window content to file.

### ISSUE THREAD

**Issue by 0x900x90** [x64dbg/x64dbg#1182]
OK. We have this option now. But i get "Fatal GUI Exception: bad allocation!" when i try to save big piece of data.

Can somebody check this?

Looks like this requires to much memory. But i asked about this option to avoid excessive memory usage.

**Comment by shamanas** [comment]
@0x900x90  
Huh, weird, I used it to copy a whole program (~300K instructions) without problems, I'll try to reproduce it.

**Comment by 0x900x90** [comment]
I copied 1.5M instructions into ~150Mb file. But look like xdbg collects all data in memory and only then saves data to disk. In OllyDbg i saved much more. And olly never used too much memory for this.

**Comment by mrexodia** [comment]
How much memory do you have?

**Comment by shamanas** [comment]
@0x900x90  
I'm flushing the data after every instruction in my code, that's why I'm surprised (I suppose QTextStream doesn't release the write buffer memory after a flush for some reason?)

**Comment by mrexodia** [comment]
I'm currently working on a better implementation. It will first disassemble every instruction in a buffer but I'm replacing it with a lambda so it shouldn't take so much memory.

**Comment by 0x900x90** [comment]
On my x86 system i can't use more than 2Gb for single process, i think.
