### ISSUE TITLE
0x prefix

### ISSUE THREAD

**Issue by nickwdev** [x64dbg/x64dbg#1187]
^title.
When I copy large functions into C++ (using inline asm) it's very exhausting to add 0x in front of every number. Maybe you can add a feature that auto-converts them if you use the copy functions.

**Comment by mrexodia** [comment]
Duplicate

**Comment by nickwdev** [comment]
yeah march 23 and still no implementation

**Comment by mrexodia** [comment]
Do you have any time because I don't. Creating more issues with work
counter productive I just removed this from my list of things to look at.
