### ISSUE TITLE
could be a big bug, can't refresh or maybe remembered last time result.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1188]
one day, i was try a KeygenMe, F8, F8 all the time, you know when I step a place,
CMP EAX, 0x20
JLZ xxxxxx
this should compare a serial number Length, more then 32 digit or less then 32 digit, it condition should decide jump or not jump, but however how could I try, It jump all the time, I asked a friend he confirmed this is a length compare, that day I was not really pay attention on it.

OK, but after other day,  I try other KeygenMe, when I go into algorithmic, usually F8, then EAX, EBX, ECX, EDX, ESI result must change every time, but it never change, always the keep the same, 

so, I'm surmise this is maybe debuger itself remembered first time debugging result, or maybe it after kick analyse module can't refresh immediately, i don't know this is bug or not, maybe you know the best.

**Comment by clshack** [comment]
Please post the hash and the file so the guys will be able to replicate the bug with the same file..

**Comment by mrexodia** [comment]
Thanks! Should be fixed now.
