### ISSUE TITLE
why debug note not begin save and load?

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1192]
I just try to put somethine in note, close debugger, go into directory a there is saved a note.txt file there, this is good, but when i relauch debugger again, then go note tab to see, there is blank, nothing there. I try to load same exe ready debugging, but the same blank note tab there? why? i close the debugger and it save blank content into note.txt, and will not load it in next time relauch debugger, hope fix it ASAP.

**Comment by mrexodia** [comment]
Last time I tried the note loaded fine.

**Comment by cxj98** [comment]
may i assume this bug is run as administrator with debugger and not load it? at least happen on my pc.

**Comment by cxj98** [comment]
OK, lauch debugger not load any exe, in note tab, type something in global, then close debugger, it save a note.txt in the same directory, now lauch debugger again, going note tab -> global, it loads blank content, now close debugger, it delete note.txt in directory, repeat the same procedure, the same result. maybe that is the bug in global? one more thing, after test, the saved note.txt not support None-English character, it become unreadable code, i type english also not load and save, after many test, it works fine on note->Debuggee, save and load, BTW where debuggee note saved? and one more suggestion, does note tab support word format feature will be implement? thanks.

**Comment by mrexodia** [comment]
The notes fully support non-English characters in UTF8 but I will try to reproduce the bug. Thanks for these reproduction steps!

**Comment by cxj98** [comment]
Hi, i'm using notepad2 instead of windows notepad, I don't know is this cased of encoding problem, but I'm thinking save as txt is not the best ideal, maybe *.rft or *.doc is good solution.

**Comment by shamanas** [comment]
I don't think .txt is an issue, I will try to reproduce this myself if @mrexodia has no time.
(Probably tomorrow morning but I could take a shot in a couple of hours too)

**Comment by mrexodia** [comment]
shoudl be fixed

**Comment by cxj98** [comment]
yes, just quick test, fixed now. thanks.

**Comment by mrexodia** [comment]
If your x64dbg directory is not writable it will not save the notes for
obvious reasons. It will not save settings either.
