### ISSUE TITLE
Could not get module file name for process

### ISSUE THREAD

**Issue by lab313ru** [x64dbg/x64dbg#1193]
Process was created with CreateProcessW/A. winver.exe.
Now it suspended and next call to NtResumeThread will resume winver. I want to attach to that process, but it gives me an error and ARG_GET_ERROR string in command line arguments.

Sample is 8489c1f79eab35c8764b4441ebcf6c10cc8af14e440b1c575d48929ad4a0d357.

**Comment by blaquee** [comment]
Hi, could you explain the steps you took to reproduce the issue?

**Comment by lab313ru** [comment]
1. Set breakpoint at NtResumeThread;
2. Execute sample;
3. Wait until breakpoint will hit;
4. Now try to connect to winver.exe.

**Comment by Nukem9** [comment]
potentially related
https://github.com/x64dbg/x64dbg/issues/755
https://github.com/x64dbg/x64dbg/issues/514

**Comment by mrexodia** [comment]
I was under the impression that `GetMappedFileName` is already being called when `GetFinalPathNameByHandle` fails.
