### ISSUE TITLE
Not-ASCII Symbols in Hex Dump

### ISSUE THREAD

**Issue by 10miles** [x64dbg/x64dbg#1196]
Last few releases use not-ASCII symbols in hex dump.
If this is bug, please fix it.
If this is by-design, it's wrong.
Please use only ASCII symbols in ASCII hex dump.
When Copy/Pase hex code in notepad, to be saved as ASCII text file.

ASCII Table, snapshot_2016-10-28_00-21 (latest release)
<img src="http://s21.postimg.org/5extqsx6v/004.jpg">

ASCII Table, snapshot_2016-10-24_00-47 (previous release)
<img src="http://s4.postimg.org/899nvz799/003.jpg">

Thanks. :(

**Comment by mrexodia** [comment]
You can change this behavior in the settings file.

```c++
duint setting;
if(BridgeSettingGetUint("GUI", "NonprintReplaceCharacter", &setting))
    mNonprintReplace = QChar(uint(setting));
if(BridgeSettingGetUint("GUI", "NullReplaceCharacter", &setting))
    mNullReplace = QChar(uint(setting));
```

Change both to `2e` to have dots back. Notice that dots are not the actual representation of the character, they are only shown in place of non-printable characters and these non-ascii characters are inserted so it is easier to see the difference between dots.

**Comment by 10miles** [comment]
Thanks for reply.
Open to discussion is good, but using non-ascii characters
in ASCII hex Table is wrong. Here's a solution from Olly Debugger

ASCII Table, Olly Debugger
<img src="http://s14.postimg.org/uek5xsdr5/005.jpg">

Non-printable characters 00-1F are represented by other
non-printable ASCII characters, thus becoming "printable"
by Copy/Paste. You can Copy/Paste representative characters
in notepad, save as ASCII text file and then see
in Hex Editor proper ASCII hex codes of proper non-printable
ASCII characters.

Thanks.:(

**Comment by mrexodia** [comment]
For copying I think you are right and the direct ASCII characters should be copied. For displaying I think it works fine as it is but if more people think it should be changed I will.

**Comment by merces** [comment]
Hi!

The default behavior for hexa dumps is to print a dot for non-ASCII characters. I think people are used to it and used to look for a 2E byte in order to distinguish a real dot from this condition. If you keep it as default, the hexa/ASCII dump output will be compatible with others. For example:

```
$ hd -n32 /bin/ls
00000000  7f 45 4c 46 01 01 01 00  00 00 00 00 00 00 00 00  |.ELF............|
00000010  02 00 03 00 01 00 00 00  b4 c1 04 08 34 00 00 00  |............4...|
00000020

$ xxd -l 32 /bin/ls
0000000: 7f45 4c46 0101 0100 0000 0000 0000 0000  .ELF............
0000010: 0200 0300 0100 0000 b4c1 0408 3400 0000  ............4...
```

On Windows, XVI32, wxHexEditor, Hex Workshop and many others follow the same pattern.

Apart from that, if you output a non-ASCII character in a ASCII dump (the column title says "ASCII"), it is not correct as @10miles pointed out. So, I suggest you keep "the dots" solution as default. 😉

**Comment by mrexodia** [comment]
@merces there is a unicode column with all possible codepages.
