### ISSUE TITLE
OllyMigrate plugin doesnt work after some update in debugger

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#1202]
x64dbg from "5 Mar 2016" is working fine with ollymigrate 0.91.
But latest snapshot doesnt work fine with migration plugin, migration aborted or process crashed. For example see logs:

SendDebuggee: Start Trigger
SendDebuggeePhase1: Process stopped, Next phase
SendDebuggeePhase2: Target process type 32bit
SendDebuggeePhase2: Save view, Thread=DE9153F5, Disassemble=07A91D8D, Dump=77A11000, Stack=07A8FB10
SaveThread: SaveInfo Thread=000017F0, EIP=77A4C27C, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=01D23250, Priority=00000000
SaveThread: SaveInfo Thread=FFEA3000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=DE9153F5, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SaveThread: SaveInfo Thread=00000000, EIP=00000000, Priority=00000000
SendDebuggeePhase2: Saved Thread Count=17
SaveBreakPoint: Clear All Memory Breakpoint
SaveBreakPoint: Clear All Hardware Breakpoint
SendDebuggeePhase2: Saved BP Count=0
SendDebuggeePhase2: Memory Allocated, Pid=000002F4 Address=03B00000 Size=00003000
SendDebuggeePhase2: Writememory Address=03B01000, RequestSize=00000164, WrittenSize=00000164
LoopThread: Setup Thread=000017F0, NewEIP=03B01050, Priority=FFFFFFF1
Thread switched!
Invalid thread DE9153F5
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=FFEA3000
LoopThread: OpenThread Failed, Thread=DE9153F5
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
LoopThread: OpenThread Failed, Thread=00000000
SendDebuggeePhase3: Process not running, Run
Thread 10DC exit
SendDebuggeePhase3: Process running, Next phase
SendDebuggeePhase4: Migration prepare finished, Request detach debuggee
Thread 136C created, Entry: 77AC1170
Thread 136C exit
Detached!
SendDebuggeePhase5: Detach debuggee POST process
StartNewDebugger: "C:\ida61\idaq.exe" -rwin32+756
SendDebuggeePhase5: Sender exit disabled for troubleshooting, debug mode enabled
SendDebuggeePhase5: Migration Finished
Debuggee migration finished, Op=Send, Pid=756, Thread=17, BreakPoint=0
SendDebuggeeDispatch: Finished, Release All

**Comment by mrexodia** [comment]
There is no source code available for OllyMigrate so there isn't much I can do about it...

**Comment by mrexodia** [comment]
Just tried on Windows 8.1 x64 with the latest x64dbg and Ollydbg 1.10, everything works fine:

```
INT3 breakpoint "entry breakpoint" at <x32dbg.WinMainCRTStartup> (00272244)!
Log will be redirected to C:/CodeBlocks/x64dbg/bin/x32/ollymid.txt.
SendDebuggee: Start Trigger
SendDebuggeePhase1: Process stopped, Next phase
SendDebuggeePhase2: Target process type 32bit
SendDebuggeePhase2: Save view, Thread=00002280, Disassemble=00272244, Dump=77891000, Stack=00B4F7C8
SaveThread: SaveInfo Thread=00002280, EIP=00272244, Priority=00000000
SendDebuggeePhase2: Saved Thread Count=1
SaveBreakPoint: Clear All Memory Breakpoint
SaveBreakPoint: Clear All Hardware Breakpoint
SendDebuggeePhase2: Saved BP Count=0
SendDebuggeePhase2: Memory Allocated, Pid=000001F4 Address=00B90000 Size=00003000
SendDebuggeePhase2: Writememory Address=00B91000, RequestSize=00000064, WrittenSize=00000064
LoopThread: Setup Thread=00002280, NewEIP=00B91050, Priority=FFFFFFF1
SendDebuggeePhase3: Process not running, Run
SendDebuggeePhase3: Process running, Next phase
SendDebuggeePhase4: Migration prepare finished, Request detach debuggee
Detached!
SendDebuggeePhase5: Detach debuggee POST process
StartNewDebugger: "C:\Users\Admin\Downloads\odbg110\OLLYDBG.EXE" -p 500
SendDebuggeePhase5: Sender exit disabled for troubleshooting, debug mode enabled
SendDebuggeePhase5: Migration Finished
Debuggee migration finished, Op=Send, Pid=500, Thread=1, BreakPoint=0
SendDebuggeeDispatch: Finished, Release All
Saving database to C:\CodeBlocks\x64dbg\bin\x32\db\x32dbg.exe.dd32 16ms
Debugging stopped!
```

**Comment by mrexodia** [comment]
Okay I think I found the issue and I will fix it soon.

**Comment by lupier** [comment]
Example log of old build where all are ok
SendDebuggee: Start Trigger
SendDebuggeePhase1: Process stopped, Next phase
SendDebuggeePhase2: Target process type 32bit
SendDebuggeePhase2: Save view, Thread=00001194, Disassemble=06EA1A6D, Dump=77A11000, Stack=082CFB28
SaveThread: SaveInfo Thread=000016F8, EIP=77A4C7EC, Priority=00000000
SaveThread: SaveInfo Thread=00001608, EIP=77A4DD2C, Priority=00000000
SaveThread: SaveInfo Thread=000016E8, EIP=755D18F6, Priority=00000000
SaveThread: SaveInfo Thread=00001218, EIP=77A4DD2C, Priority=00000000
SaveThread: SaveInfo Thread=000016F4, EIP=77A4C7EC, Priority=00000000
SaveThread: SaveInfo Thread=000016FC, EIP=77A4C7EC, Priority=00000000
SaveThread: SaveInfo Thread=00000300, EIP=77A4DD2C, Priority=00000000
SaveThread: SaveInfo Thread=000003E0, EIP=77A4DD2C, Priority=00000000
SaveThread: SaveInfo Thread=000011B8, EIP=77A4C7EC, Priority=FFFFFFFF
SaveThread: SaveInfo Thread=00001194, EIP=06EA1A6D, Priority=FFFFFFFF
SaveThread: SaveInfo Thread=000015F8, EIP=77A4C7EC, Priority=FFFFFFFF
SaveThread: SaveInfo Thread=00000CBC, EIP=77A4C27C, Priority=00000000
SaveThread: SaveInfo Thread=00000AC0, EIP=77A4C27C, Priority=00000000
SaveThread: SaveInfo Thread=00000DF8, EIP=77A4C7EC, Priority=0000000F
SaveThread: SaveInfo Thread=000015D8, EIP=77A4DD2C, Priority=00000000
SaveThread: SaveInfo Thread=00000A50, EIP=77A4C2AC, Priority=00000000
SaveThread: SaveInfo Thread=00000F3C, EIP=77A4DD2C, Priority=00000000
SendDebuggeePhase2: Saved Thread Count=17
SaveBreakPoint: Clear All Memory Breakpoint
SaveBreakPoint: Clear All Hardware Breakpoint
SendDebuggeePhase2: Saved BP Count=0
SendDebuggeePhase2: Memory Allocated, Pid=00001710 Address=03A40000 Size=00003000
SendDebuggeePhase2: Writememory Address=03A41000, RequestSize=00000164, WrittenSize=00000164
LoopThread: Setup Thread=000016F8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00001608, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000016E8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00001218, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000016F4, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000016FC, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000300, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000003E0, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000011B8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00001194, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000015F8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000CBC, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000AC0, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000DF8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=000015D8, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000A50, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
LoopThread: Setup Thread=00000F3C, NewEIP=03A41050, Priority=FFFFFFF1
Thread switched!
Thread switched!
SendDebuggeePhase3: Process not running, Run
SendDebuggeePhase3: Process running, Next phase
SendDebuggeePhase4: Migration prepare finished, Request detach debuggee
Detached!
SendDebuggeePhase5: Detach debuggee POST process
StartNewDebugger: "C:\ida61\idaq.exe" -rwin32+5904
SendDebuggeePhase5: Sender exit disabled for troubleshooting, debug mode enabled
SendDebuggeePhase5: Migration Finished
Debuggee migration finished, Op=Send, Pid=5904, Thread=17, BreakPoint=0
SendDebuggeeDispatch: Finished, Release All

As you can see there are no "thread id = 0" present

**Comment by mrexodia** [comment]
Here is the fix https://mega.nz/#!60AxlS7Y!p0J495MSrk8L64fEHjGya7bLDRVCIQpFsSPLu0LlBoY
