### ISSUE TITLE
x64dbg loads x32 DLL

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1206]
UPDATED:
The issue is that x64dbg unconditionally loads any x32 DLL. I don't know if this was intended, but I came across a lot of issues when I was mistakenly debugging like this.

**Comment by Nukem9** [comment]
![image](https://cloud.githubusercontent.com/assets/4228359/19839985/b9021374-9ec2-11e6-99ed-bf79335eff2f.png)
![image](https://cloud.githubusercontent.com/assets/4228359/19839987/bd56bf60-9ec2-11e6-9b42-93a6efc19685.png)

**Comment by ViRb3** [comment]
@Nukem9 Apparently the issue is more specific than I thought: **x64dbg loads x32 DLLs** but not executables.

**Comment by Nukem9** [comment]
I see what you mean. DllLoader64.exe runs and the 32-bit dll is never loaded. The process just exits, but there should be an error instead.

```
This file is a dotNET application.
Database file: C:\Users\Administrator\Desktop\snapshot_2016-10-24_23-38\release\x64\db\symsrv_test_noext32.dd64
Process Started: 00007FF634C80000 C:\Users\Administrator\Desktop\snapshot_2016-10-24_23-38\release\x32\DLLLoader64_253C.exe
DLL Loaded: 00007FFCA84B0000 C:\Windows\System32\ntdll.dll
DLL Loaded: 00007FFCA8370000 C:\Windows\System32\kernel32.dll
DLL Loaded: 00007FFCA57A0000 C:\Windows\System32\KernelBase.dll
DLL Loaded: 00007FFCA62B0000 C:\Windows\System32\user32.dll
DLL Loaded: 00007FFCA7B90000 C:\Windows\System32\gdi32.dll
System breakpoint reached!
Breakpoint at 00007FFCA8111040 set!
DLL Loaded: 00007FFCA8110000 C:\Windows\System32\imm32.dll
Breakpoint at 00007FFCA6501160 set!
DLL Loaded: 00007FFCA6500000 C:\Windows\System32\msctf.dll
Breakpoint at 00007FFCA5CF2790 set!
DLL Loaded: 00007FFCA5CF0000 C:\Windows\System32\msvcrt.dll
INT3 breakpoint "DllMain (msvcrt.dll)" at <msvcrt.EntryPoint> (00007FFCA5CF2790)!
INT3 breakpoint "DllMain (msctf.dll)" at <msctf.EntryPoint> (00007FFCA6501160)!
INT3 breakpoint "DllMain (imm32.dll)" at <imm32.EntryPoint> (00007FFCA8111040)!
Process stopped with exit code 0x0
Saving database to C:\Users\Administrator\Desktop\snapshot_2016-10-24_23-38\release\x64\db\symsrv_test_noext32.dd64 0ms
Debugging stopped!
```
![image](https://cloud.githubusercontent.com/assets/4228359/19840101/1b7ea650-9ec5-11e6-8810-ba526149169a.png)

**Comment by torusrxxx** [comment]
I know what's the problem. You're debugging a .NET DLL. x64dbg will pass
validation if the .NET header data section is not NULL. It doesn't check
for actual architecture for the .NET file. If you try a non-dotNET DLL it
should work fine.

**Comment by ViRb3** [comment]
@torusrxxx It is not a .NET DLL, rather a C++ compiled one.

**Comment by torusrxxx** [comment]
x64dbg thinks it to be a dotNET file. It says "This file is a dotNET
application." That might be the problem.

**Comment by torusrxxx** [comment]
This problem is fixed by not checking .NET for DLL files.
