### ISSUE TITLE
Adding the "Content" of the section in "Memory Map"

### ISSUE THREAD

**Issue by clshack** [x64dbg/x64dbg#1212]
Good evening,
I think that it will be useful to add the content of a section into the memory tab like in immunity. 

![memory](https://cloud.githubusercontent.com/assets/842138/19936344/6c4c0442-a11d-11e6-9442-d95a0489dc96.png)

**Comment by mrexodia** [comment]
Feel free to send a pull request. Generally this is a completely arbitrary label based on section protection and section names.
