### ISSUE TITLE
Debugger loses control after modification of the kernel32 IAT by target process

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#1213]
When target exe wipe with 0x0 kernel32.dll IAT in their own memory, debugger cant be closed in normal way.
KERNEL32.DLL->ntdll.dll:DbgPrintEx
and many other API used by kernel32.dll
current value > 00 00 00 00
original value > E0 F7 A7 77
So, when you try to close target exe - no problem. But debugger cant handle such weird IAT wipe-out and can not stop. When you try to close debugger in status bar I see next text:
.. stopping running debugger
.. cleaning up wait objects - infinite processing.

**Comment by lupier** [comment]
for example: screenshot after debugger loses target. In same situation Ollydbg can be closed without any infinite waiting
![2](https://cloud.githubusercontent.com/assets/1623540/19992615/97f8876c-a269-11e6-91de-78f2da4fbfc9.png)

**Comment by mrexodia** [comment]
Without checking this is most likely related to the horrendous code that #580 should fix.
