### ISSUE TITLE
problem with scrollbar.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1217]
i want to scroll up and down fast,  so I drag the scroll bar to up and down, but seems it not work. all ui scroll bar is not work, unless your scroll up and down mouse wheel to scroll up or down, do this, so slow, just tested.

**Comment by mrexodia** [comment]
Could you send a gif/video I just tried and everything appears to work fine.

**Comment by cxj98** [comment]
https://i.imgsafe.org/e54df0c199.gif

**Comment by cxj98** [comment]
download gif pic here.

http://s000.tinyupload.com/index.php?file_id=71873525873707768929

**Comment by cxj98** [comment]
it seems my pc problem, it works fine now.
