### ISSUE TITLE
Wildcard support for command search

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1218]
**Example commands:**
cmp dword ptr ss:[eax+10], 0xE
cmp dword ptr ds:[eax+50], 0xE
cmp dword ptr ss:[edx], 0xE

**Find via wildcard:**
cmp dword ptr ss:[?], 0xE

Because the instruction bytes change significantly it's hard to search for them by hand. Please consider implementing this functionality when you have time. Thank you!

**Comment by mrexodia** [comment]
#779
