### ISSUE TITLE
Toggling registers will only work once

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1220]
1. Toggle for example `EAX`
2. Try to toggle it again, it won't work

**Comment by wk-952** [comment]
It seems that toggling doesn't work if current value is negative.

**Comment by mrexodia** [comment]
That option wasn't supposed to exist for general purpose registers... I removed it

**Comment by wk-952** [comment]
Fun fact: The toggle option for registers (and this bug) existed since snapshots form 2014 
I guess this option was really unused a lot :smile: .

**Comment by mrexodia** [comment]
Yeah it was a really weird construction
