### ISSUE TITLE
File offset calculate bug?

### ISSUE THREAD

**Issue by mireado** [x64dbg/x64dbg#1221]
Whenever I using "Goto File Offset",
It seems doesn't calculate well.

small offset address is works well.
but, bigger offset calculate differently.
=========
Example::

Base=6BB00000
Module=kagparser.dll
offset CA0B

My calcuation,
0x6BB00000+0x0000CA0B=
0x6BB0CA0B

but x64dbg say,
0x6BB0D60B

[Imgur](http://i.imgur.com/OHOL4zI.png)

????? why this happen?
Did I have mistake something?

**Comment by mrexodia** [comment]
That's not the file offset that's the RVA.
