### ISSUE TITLE
Force update CPU tab after pressing +/- (goto next/previous)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1226]
1. Step over (for example) 4 consecutive instructions
2. Press `Numpad +` or `Numpad -`, you'll see that the info box below the disassembly gets updates while the disassembly view is not.

**Comment by wk-952** [comment]
It will only be updated if the next instruction caused the current page to be scrolled.

**Comment by mrexodia** [comment]
This should be partially fixed now, the reason for the window title is that the disassembly (and thus the history) is updated before the window title so that's why you are behind. I will look into fixing this without impacting performance but I'm not sure it's possible...
