### ISSUE TITLE
Wrong parsing in dynamic comments

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1227]
The following expression won't work:
`{4:[esp] + 48}`
but if a space is added at the beginning it'll work
`{ 4:[esp] + 48}`
also it'll work if you eliminated the number of bytes to read
`{[esp] + 48}`

I guess the precedence of the this form `n:[addr]` should have higher priority, because this works
`{(4:[esp]) + 1}`
(manually forcing the precedence of calculation using brackets)

**Comment by mrexodia** [comment]
try `{p:4:[esp]+48}` the issue is that '4' is recognized as a print type should be easy enough to fix

**Comment by mrexodia** [comment]
Should be fixed, thanks!

**Comment by wk-952** [comment]
Alright, thanks.
I haven't been getting all notifications lately.

**Comment by mrexodia** [comment]
Contact github about that there were issues with notifications they might
be able to assist.

**Comment by wk-952** [comment]
Yeah this is getting really annoying to me, i'll contact them today.
