### ISSUE TITLE
Saving layout state not working

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#1230]
![error](https://cloud.githubusercontent.com/assets/13303069/20077483/a2b257ac-a50a-11e6-8087-efb30d51eaaa.PNG)

None of those two options are properly working

**Comment by mrexodia** [comment]
Could you describe the issues in more detail?

**Comment by ThunderCls** [comment]
When you have those two options selected x64dbg is supposed to save the width of the columns and the positions of the tabs...well...it doesn't do it. Right after you close the debugger and open it again it is all as default again

**Comment by ThunderCls** [comment]
To be even more specific, if you close/open or arrange your top tabs and then you close x64dbg, when you execute it once again, all the tabs are gonna appear misplaced and even those previously closed are still there. Also there are some frames layouts like the stack, that are not saved.

**Comment by mrexodia** [comment]
Just tested, column widths and order is saved and the tab order is also saved...

**Comment by ThunderCls** [comment]
![x64dbg_bug](https://cloud.githubusercontent.com/assets/13303069/20116988/865c7a84-a5cc-11e6-9649-cded1c3e014a.gif)

**Comment by torusrxxx** [comment]
It is because the feature to save the layout is not fully implemented yet.

**Comment by ThunderCls** [comment]
I know, but this specific option is supposed to Load/Save the Tabs order, or at least that's what it says it does, but what I'm pointing out is that it doesn't do it at all.

**Comment by mrexodia** [comment]
I know I tried exactly the same thing and it worked fine. I will try some
more though.

**Comment by ThunderCls** [comment]
Ok, I did some other tests and apparently the tabs order saving does work, the thing is with closed tabs, when you close some tabs and change some places then when the debugger is restarted all the tabs are gonna be there again, and that's why is so confusing....anyways...I know the whole "layout backup" thing is not fully implemented yet, so if you will this can be closed
