### ISSUE TITLE
Functions "breakpoint on all commands" not showing bp's in Breakpoints window

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#1231]
When using "set breakpoint on all commands" menu in the Functions windows, once the bp's are setted, they won't appear in the "Breakpoints Manager Window". Also the Bp's highlighting don't get updated when using the same menu in the Functions windows until you force it by clicking inside the frame

![error2](https://cloud.githubusercontent.com/assets/13303069/20077780/ca91cdf6-a50b-11e6-8227-86dc8c6796e3.PNG)

**Comment by mrexodia** [comment]
This issue should have been fixed quite recently.

**Comment by ThunderCls** [comment]
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/13303069/20078646/73195996-a50f-11e6-9c1c-0ce3e2eb3859.gif)

**Comment by mrexodia** [comment]
Okay this should be fixed now. Thanks!
