### ISSUE TITLE
in od infobox it can show all CALL

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1235]
in OD, infobox can show all calls, does x32dbg can implement it? thanks.

**Comment by mrexodia** [comment]
Press x

**Comment by torusrxxx** [comment]
use https://github.com/torusrxxx/ExtraInfo

**Comment by cxj98** [comment]
looks good, thanks.

**Comment by cxj98** [comment]
but one thing, in od, those calls can chose which is going to set breakpint, does this will implement, thanks.

**Comment by mrexodia** [comment]
Use the "x" button to browse to the references.
