### ISSUE TITLE
Cannot pause at the point where an exception raises

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1239]
When the debugger is started in case of a JIT event(a program throws a fatal exception, but not access violation), and "Attach breakpoint" is unset. The debugger cannot pause at where the exception raises, but simply let the debuggee exits.

sample: x32dbg and [patchexporter](https://github.com/torusrxxx/x64dbgpatchexporter/issues/1)

**Comment by mrexodia** [comment]
Just tried, it appears to work fine now.
