### ISSUE TITLE
nibbles swapped when editing x87 registers

### ISSUE THREAD

**Issue by mtomek55** [x64dbg/x64dbg#1242]
In x32_dbg, editing a x87 register value, e.g. entering 3FFF8CCCCCCCCCCCCD00 and pressing OK, results in F3FFC8CCCCCCCCCCDC00 being stored, all nibbles swapped.
A simple workaround to open the register again and just press OK, which swaps the nibbles back to the correct order.

**Comment by mrexodia** [comment]
Try updating to a version that was already renamed to "x32dbg"

**Comment by mtomek55** [comment]
sorry, I forgot, I'm on the Nov 9 2016 22:53 build

**Comment by mtomek55** [comment]
I tracked this to 
RegistersView.cpp:2521
QByteArray pArray =  mLineEdit.editText.toLocal8Bit();

this returns the string from the LineEditDialog reversed.

**Comment by mrexodia** [comment]
this should be fixed now, thanks!
