### ISSUE TITLE
If a conditional breakpoint is reached for extremely many times, it may report as a breakpoint exception

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1245]
I set a logging breakpoint at HeapFree() with condition "0" when debugging an application, for example x32dbg. Log is redirected to disk file. After about 200000 hits it begins to report First-chance exceptions EXCEPTION_BREAKPOINT on the breakpoint.

**Comment by mrexodia** [comment]
closed in favor of #1764
