### ISSUE TITLE
Favorites Menu Improvements

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#1267]
- [x] Grab the selected application icon to display it on the menu entries
- [x] Use the current debugged application as parameter when launching the selected tool
- [x] Create an optional toolbar to display the favorites list

**Comment by torusrxxx** [comment]
It is possible to use "%PID%" as an argument in the command line. Refer to
the documentation.

**Comment by mrexodia** [comment]
I think it would be a good idea to add some other directives like
%debuggee% %curmodule%

**Comment by mrexodia** [comment]
I have no intention of adding icons/toolbars.

**Comment by torusrxxx** [comment]
#2466
