### ISSUE TITLE
Can't load dll file

### ISSUE THREAD

**Issue by VegaLay** [x64dbg/x64dbg#1269]
When I open .exe file it show on memorymap window.

but .dll file doen't show.

**Comment by mrexodia** [comment]
Run to the entry point of the DLL. It will show you the system breakpoint first.

**Comment by VegaLay** [comment]
After few times of run. It close itself.

**Comment by mrexodia** [comment]
That's possible. If your dll has no DllMain. Set the option to break on DLL
load.

**Comment by VegaLay** [comment]
Thanks a lot. The x64dbg is great.
