### ISSUE TITLE
Strange behaviour of search commands

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1270]
When I use "findall a.exe:EntryPoint, 50, 100" command, it can find 5000 matches!(The selected range only has 256 bytes)
Most of the search commands don't use the start and size arguments properly. And the supposed behaviour is not documented correctly for every search command either.

**Comment by mrexodia** [comment]
The command appears to work fine here.

**Comment by mrexodia** [comment]
Nevermind that, for `findall` it's definitely broken.
