### ISSUE TITLE
x64dbg Cannot get module filename D4

### ISSUE THREAD

**Issue by Pavlex4** [x64dbg/x64dbg#1273]
When I open winrar in x64dbg and then click attach inside file menu and select winrar I get error Cannot get module filename D4.How to fix this ?

**Comment by mrexodia** [comment]
Could you make a video of the exact reproduction steps and also mention your OS?

**Comment by Pavlex4** [comment]
I have windows 7

**Comment by Pavlex4** [comment]
First I selected open than select winrar,after that I went to file menu selected attach and clicked winarar from menu https://postimg.org/image/c0495xtdv/

**Comment by Pavlex4** [comment]
?

**Comment by mrexodia** [comment]
What "?"?

**Comment by Pavlex4** [comment]
How to fix error?

**Comment by mrexodia** [comment]
I don't know I will check in two weeks.

**Comment by Nukem9** [comment]
https://github.com/x64dbg/x64dbg/issues/1193#issuecomment-260149003

**Comment by Pavlex4** [comment]
When I attach module winrar I get :
Terminated: Debugging stopped!

**Comment by mrexodia** [comment]
I tried and it works fine on my PC.

**Comment by Pavlex4** [comment]
When I open WinRAR,to open winRAR module should it go to attach option from menu ?

**Comment by mrexodia** [comment]
What version of winrar? If you want to attach to a running process you can
use the attach dialog.

**Comment by Pavlex4** [comment]
Version of winRAR is 5.40.

**Comment by Pavlex4** [comment]
How to change module from ntdll.dll to winRAR.exe module ?
