### ISSUE TITLE
Expression parsing won't work if first char is bracket followed by any sign

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1276]
Grouping `(using brackets like those)` won't work if the first token - after the opening bracket - is a any sign.
Example, this won't work:
`(-1)`
`(+1)`

EDIT: An obvious workaround is prefixing the expression with zero
`(0-1)`
`(0+1)`

**Comment by wk-952** [comment]
Thank you.

**Comment by mrexodia** [comment]
Thanks for the report!
