### ISSUE TITLE
Calculator error

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1278]
When entering space or single-quote in ASCII text box, expression isn't calculated properly

**Comment by mrexodia** [comment]
Which text box exactly?

**Comment by gmastergreatee** [comment]
The text box to the right of ASCII in the calculator(Help menu)

**Comment by mrexodia** [comment]
Ah yes I see.

**Comment by gmastergreatee** [comment]
The same can be observed for Unicode text box.
