### ISSUE TITLE
Status bar update on copy

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1280]
It is displayed that a "Breakpoint at 0xXXXXXX set" whenever a breakpoint is added(somewhat same for deletion) but nothing is displayed on the status bar in case of copying from the disassembler.

Feel free to close it.

**Comment by mrexodia** [comment]
What should it display?

**Comment by gmastergreatee** [comment]
For instance, lets say we copied the address, then it would display "Copied address 0xXXXXXX to clipboard" on the status bar so that we would know that "Something really happened".

**Comment by mrexodia** [comment]
Yeah sure that would be a possibly enhancement.

**Comment by gmastergreatee** [comment]
Seems issue resolved.
