### ISSUE TITLE
Inter-Converter

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1281]
It would be really handy if there would be an inbuilt type converter tool. Like binary, octal, decimal, hexadecimal, ascii, and unicode inter-converter. Well I know that parts of the above can already be done in the calculator but say if its required to convert octal to ascii(as is required for the tuts4you secret question for registration), this can't be done in the calculator without sparing a lot of time.

**Comment by mrexodia** [comment]
What extra should the calculator do? I don't plan to add array conversions
(apart from the ones already available in the data copy dialog). I could
add octal number support in the calculator.

For doing bulk conversion, use something like the x64dbgpy command line or
write a small python script.

**Comment by gmastergreatee** [comment]
Seems I need to learn python. OK :-)

**Comment by mrexodia** [comment]
With c or c++ you can also easily write a conversion plugin that suits your needs. I don't mind adding extra conversions for single numbers though I just think it should be part of a plugin.

**Comment by gmastergreatee** [comment]
I'm a C# programmer, never put my hands into c/c++ so I would try to develop a plugin first.

**Comment by mrexodia** [comment]
There is a C# plugin template available on http://plugins.x64dbg.com It can
use some work but it's something to go off.

**Comment by gmastergreatee** [comment]
Yeah, it was me who added the first dummy issue and then closed it there in the C# section. :-D

**Comment by gmastergreatee** [comment]
I have developed an inter-converter. https://github.com/gmastergreatee/DOHAB_Inter_Converter<br>Will also create a related plugin for x64dbg later.
