### ISSUE TITLE
Display Unicode strings in "String References" search

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1286]

**Comment by ThunderCls** [comment]
+1

**Comment by mrexodia** [comment]
The file to get this working is https://github.com/x64dbg/x64dbg/blob/development/src/dbg/disasm_helper.cpp#L310 feel free to send a pull request with **decent** support for unicode strings. Anything is a unicode string if you disable that extended ascii check.

**Comment by cxj98** [comment]
there is a chinese pkugin support unicode string search.

**Comment by mrexodia** [comment]
[IsTextUnicode](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318672(v=vs.85).aspx) might be used as suggested by @torusrxxx

**Comment by torusrxxx** [comment]
#2406
