### ISSUE TITLE
Irregular behaviour in Unicode textbox

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1287]
Maybe this is some bug or I'm doing it the wrong way.
![asdasd](https://cloud.githubusercontent.com/assets/17880848/20535132/bcfc798e-b109-11e6-8346-a23f2546b641.gif)

**Comment by mrexodia** [comment]
You select the second byte of the previous character so your characters
will become 0x5200 = Chinese

**Comment by gmastergreatee** [comment]
Ahh! Okay
