### ISSUE TITLE
Do we have any plugin to handle Anti-Debug based on SetUnhandledExceptionFilter

### ISSUE THREAD

**Issue by naijim** [x64dbg/x64dbg#1294]
like that feature from OllyAdvanced.  I did some search but couldn't find relevant info. Does TitanHide handle this feature?

**Comment by mrexodia** [comment]
ScyllaHide has this feature. Notice that  SetUnhandledExceptionFilter is not the anti debug it is NtQueryInformationProcess(Debug port).

**Comment by mrexodia** [comment]
Also this is not an issue really to open here, it would be a better candidate to ask in the IRC or telegram channel...
