### ISSUE TITLE
Copy/Paste memory data not working properly

### ISSUE THREAD

**Issue by brupelo** [x64dbg/x64dbg#1297]
For some reason when trying to copy a big data chunk from memory following the next steps:

 - Select memory chunk in the ASCII column
 - Right click / Binary edit
 - Select all + Copy

Isn't copying the whole selected chunk. To see what I mean take a look to the next [video](https://dl.dropboxusercontent.com/u/21334722/ShareX/2016/11/2016-11-27_20-30-35.gif).

`x64dbg version compiled on nov20, 2016`

**Comment by mrexodia** [comment]
Use the data copy dialog to copy text. The buffer might be null terminated and it will only copy until that character. In your video there is no relation whatsoever between the text you want to copy and what finally shows up on the right...

**Comment by brupelo** [comment]
Where can i find that data copy dialog?

Anyway, you're right, my previous video wasn't showing very useful data, here's another [better one](https://dl.dropboxusercontent.com/u/21334722/ShareX/2016/11/2016-11-27_21-16-36.gif)

**Comment by mrexodia** [comment]
![data copy](https://i.imgur.com/m6ZkvEX.png)

**Comment by mrexodia** [comment]
Yeah it is as I suspected. Your string contains `\0` characters so the buffer will be terminated after that.

![null](https://i.imgur.com/IJm4LL3.png)

**Comment by brupelo** [comment]
I understand, in any case, i've tried the data copy dialog and it works like a charm, thanks a lot ;-)
