### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by srgloureiro** [x64dbg/x64dbg#1299]
It crashed when clicking on an arrow at the left column of the CPU tab.

[dump-27112016_2353130395.zip](https://github.com/x64dbg/x64dbg/files/615151/dump-27112016_2353130395.zip)

---------------------------
About x64dbg v25
---------------------------

Compiled on:<br>Nov 18 2016, 18:16:18

**Comment by mrexodia** [comment]
Could you give more specific details on how to reproduce?

**Comment by srgloureiro** [comment]
I can not exactly remember the whole picture, but I was analyzing an .exe file and I think I clicked on a red jump arrow

**Comment by mrexodia** [comment]
This arrow?

![image](https://i.imgur.com/BlQpsv1.png)

**Comment by srgloureiro** [comment]
Yes. But it was red and IIRC in the other sense (pointing up). And mine is way more longer than yours.

**Comment by srgloureiro** [comment]
And I think it was a on an unconditional jump, as the arrow was not dashed, but a continuous line.

**Comment by mrexodia** [comment]
There is no logic or anything that does anything when you click there but I
will check out the crash dump...

**Comment by srgloureiro** [comment]
How do you check the crash dump? does x64dbg support analyzing dmp files?

**Comment by mrexodia** [comment]
No. You posted it in the original issue right?

**Comment by srgloureiro** [comment]
yes; it is on 1st post.

**Comment by mrexodia** [comment]
I just use http://www.osronline.com/dump and x64dbg to see more contextual information for the dump you provided.

**Comment by mrexodia** [comment]
Okay it should be fix now, thanks!
