### ISSUE TITLE
Losing the instructions while scrolling 

### ISSUE THREAD

**Issue by clshack** [x64dbg/x64dbg#1303]
Good morning,
I have this part of code:
```
mov dword ptr ss:[ebp-0x84],0x8B64DB31		
mov dword ptr ss:[ebp-0x80],0x7F8B307B		
mov dword ptr ss:[ebp-0x7C],0x1C7F8B0C		
....		
mov dword ptr ss:[ebp-0x14],0x90909090
```

I do right click, Follow in Disassembler -> ebp-0x84.
`31 DB 64 8B... `
![start](https://cloud.githubusercontent.com/assets/842138/20674513/8fa41dd2-b589-11e6-87f6-821f76490fe5.png)
In this case, without scrolling the page the result it's correct, after the scrolling, the instruction **31 DB** become **DB** and it's not recognized anymore. 

![after](https://cloud.githubusercontent.com/assets/842138/20674574/c6b60dbc-b589-11e6-932c-8605749d0c7e.png)
  
Let me know if you need more info.

**Comment by mrexodia** [comment]
There is no way to correctly tell the difference between code and data. Disassembling backwards is also something that cannot be done with 100% accuracy and the best you can do is mark the bytes as data so the disassembly aligns correctly.
