### ISSUE TITLE
Wrong behavior of `dbclear` command (regarding breakpoints)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1310]
The `dbclear` command clears the entire database as expected, but that's not reflected on the breakpoints of the current debugging session, you have to restart the dubugee to see the effect,
i.e. they're not deleted until you restart the degugee.

Steps to reproduce:

1. Debug anything and place some random software/hardware BPs.
2. Type `dbclear` in the command bar.
3. Press run and the debugger will still pause at those BPs (despite them being deleted).
Also the log says `Breakpoint reached not in list!` when you reach any of them.

It's not a big deal or anything, but rather confusing, because the debugger will pause/break at non-existent BPs.

**Comment by mrexodia** [comment]
Yeah, currently there are no triggers on importing/exporting/clearing of databases. It shouldn't be too hard to add them.
