### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by kakao2933** [x64dbg/x64dbg#1311]
x64dbg is my FIRST reversing debugger and i just ran example .exe file, it CRASHED!

![2](https://cloud.githubusercontent.com/assets/23355585/20795063/a07ea8d0-b812-11e6-917f-a1d115af5da2.PNG)

↑ Just Clicked 'RUN' - CRASHED

![3](https://cloud.githubusercontent.com/assets/23355585/20795086/b2a0c1f6-b812-11e6-8639-46391e8f4741.PNG)
![4](https://cloud.githubusercontent.com/assets/23355585/20795099/c05aa082-b812-11e6-9a5c-f8dff8fbeeaf.PNG)

↑ Debuged with F8 - CRASHED

I tried 'Setting - Debug Permission' , 'Administrator permissions run'

how can i debug it? :(

**Comment by mrexodia** [comment]
Hi, please give more details on how to reproduce the issue. What did you debug and could you send the crash dump?

**Comment by kakao2933** [comment]
how can i view CRASH DUMP?

**Comment by kakao2933** [comment]
dump File - 
http://www.mediafire.com/file/kaj9542lnmsngxt/x32dbg.exe.4900.dmp

debugged File - 
http://www.mediafire.com/file/xb873aliodzoiwr/01.exe

**Comment by mrexodia** [comment]
@kakao2933 could you reupload the file?

**Comment by mrexodia** [comment]
I will reopen the issue if it still happens.
