### ISSUE TITLE
Downgraded performance in latest snapshots due to issues with Kaspersky

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1337]
Recently, there have been a noticeable performance downgrade when performing debugging actions.
For example, press and hold `F8` (Step over) you'll notice a consistent latency after 4-6 instructions,
i.e. 4-6 instructions are stepped over, then a delay will occur

Another example in which this latency is noticeable, select the instruction below the one you're currently at, then press `F4` (Run until selection) and notice the small delay despite the fact that both instructions are just below each other

I don't know when has this started to happen, but you can compare the performance of the latest snapshot vs. this one `snapshot_2016-10-31_23-29` and you'll definitely notice the difference.

**Comment by mrexodia** [comment]
Hm the commits you mention don't seem to correlate with any changes related to GUI performance. I will check it some more though. What kind of numbers do you get for events/s? Mine is between 24 and 30 consistently.

**Comment by wk-952** [comment]
I didn't actually mean that those specifically are the faulty commits, just stating what's inside `commithash.txt` in case that helps to determine which commits (between both) could be the cause.

Anyway it's the same reason as #516 :disappointed: , the difference here is that kaspersky doesn't have to be disabled during OS startup to solve the issue.
When it's turned off: events/s = 20-30 (both snapshots).
When it's turned on: events/s = 19-28 on `snapshot_2016-11-18_18-21`,
and 9-12 on `snapshot_2016-11-20_22-01` (and the new ones).

I never noticed this before because i was using builds from October most of the time, which (as every other builds before them) don't have this problem, it only became obvious when i started using the latest snapshots consistently a couple of days ago.

Very sorry about this misleading/useless issue.

**Comment by mrexodia** [comment]
@wk-952 yeah the commit has is definitely very useful! I checked the commits in between briefly but I will check again. As for Kaspersky, I have no idea what I can do about it. If I find the time I will profile but it's rather mystical. Could you also try with GleeBug? Perhaps the speed improvement in that engine would make this stuttering less noticeable.

I will try to find what could have caused the issue since there appears to be something in the code that triggers the issue, so I reopen the issue. If you find any other information that's very helpful. Thanks!

**Comment by Nukem9** [comment]
Sorry, I have to say this:

This issue is 1337.

**Comment by wk-952** [comment]
With GleeBug (stepping-over `x32dbg.exe`):

- kaspersky off;
events/s = 22-30 on both snapshots (and latest ones).

- kaspresky on:
events/s = 19-25 on both snapshots

**Comment by mrexodia** [comment]
Well I guess GleeBug will be the next goal then 😄

**Comment by mrexodia** [comment]
@wk-952 Do you still feel x64dbg is slow stepping with Kaspersky?

**Comment by wk-952** [comment]
@mrexodia 10 months ago when this issue occurred i had a `Core i3` processor (2 cores, 4 threads), the issue was definitely reproduce-able with the above-mentioned `snapshot_2016-11-20_22-01`,
now i have a `Core i7` processor (4 cores, 8 threads) and the issue is no longer reproduce-able even with `snapshot_2016-11-20_22-01`.
The events/second (when debugging `x32dbg.exe` )is now consistent at 30-31 with all snapshots.

The processor might have been the problem, or may be one of `Kaspersky`'s updates had solved the problem, but i guess it's worth mentioning that i haven't changed it's version `17.0.0.611` since that time.

Feel completely free to close this issue, it's no longer relevant/reproduce-able, if i found a way to trigger it again i'll leave a comment here. Thanks for the continued support.
