### ISSUE TITLE
The scroll button of memory tabs

### ISSUE THREAD

**Issue by hulucc** [x64dbg/x64dbg#1339]
The scroll button of memory tabs keep showing even if there is enough space for all the tabs.

![image](https://cloud.githubusercontent.com/assets/4343900/20826207/40584b9a-b8a4-11e6-8007-3f724fc8bb49.png)

**Comment by mrexodia** [comment]
Yeah I have seen this a few times. Perhaps @Nukem9 knows what's going on here?

**Comment by hulucc** [comment]
I find out that the bug won't happen when you select english as language.
Please select chinese to reproduce it.
