### ISSUE TITLE
Debugger hang problem

### ISSUE THREAD

**Issue by hulucc** [x64dbg/x64dbg#1341]
Windows10 10586 enterprise 64bit
x64dbg v25 compiled on: Dec 1 2016, 22:29:29
ScyllaHide(profile:Themida x86)
Reproduce the problem:
1. Load the unpackme.exe
2. Press shift+F9 to run it
3. Close the unpackme window
4. Hang

Target:
[unpackme.zip](https://github.com/x64dbg/x64dbg/files/626697/unpackme.zip)
Crashdump:
[dump-02122016_1654220665.zip](https://github.com/x64dbg/x64dbg/files/626699/dump-02122016_1654220665.zip)

**Comment by d3v1l401** [comment]
Same situation, loading a x32 executable with ScyllaHide (updated Nt*.ini) simply throws me a loop of ACCESS_DENIED into the log and if you try to close it just crashes.

Simply, seems there're some problems with Win 10.

**Comment by d3v1l401** [comment]
Adding information:
If you rename the plugins folder (therefore disabling plugins) you'll be able to debug without any problem.
There's a plugin who's giving problems, not sure but **MAY** be Scylla.

**Comment by mrexodia** [comment]
should no longer hang now.

**Comment by hulucc** [comment]
It still hang. How could i reopen this issue?@mrexodia

**Comment by wk-952** [comment]
@hulucc I tried your unpackme with the `VMProtect` profile and it ran fine.
Although, it couldn't be dumped with `Scylla`.
![1](https://cloud.githubusercontent.com/assets/11916365/22826991/296067ca-ef9e-11e6-84a9-c011127d6820.png)

OEP seems to be at RVA `0x1253`
