### ISSUE TITLE
Script execution aborted after script reload

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#1344]
When you start execution script and after first command (for example "var N") reload script via Ctrl-R
any next execution fails with errors
In screenshot you can see "invalid variable name "ADDR" state
![1](https://cloud.githubusercontent.com/assets/1623540/20863442/94c7a0a8-b9f4-11e6-8092-5718c7eafe6c.png)
p.s. dont see to wrong spelling of bphwcall

**Comment by mrexodia** [comment]
In this case the variable name is already taken. You can implicitly create
variables by using "ADDR=0"
