### ISSUE TITLE
x64dbg falsely shows addresses as they exist

### ISSUE THREAD

**Issue by shiftre** [x64dbg/x64dbg#1345]
If you hit "Ctrl+G" and add a non-existence address,(s.a 0xCCCCCCCC) x64dbg would
refer to it as a real address and try to jump to it.

![image](https://cloud.githubusercontent.com/assets/303679/20867462/6ffe91d8-ba4d-11e6-8ac1-f5d9abdcadea.png)

![image](https://cloud.githubusercontent.com/assets/303679/20867463/7a1fde60-ba4d-11e6-9e7f-19acfe0aa82c.png)

**Comment by mrexodia** [comment]
Perhaps the wrong kind of check is enabled in the goto dialog. It doesn't
say that it's a valid address though so that's fine 😀

**Comment by shiftre** [comment]
: /

If I reference to an API which does not exist, I can't go to it, but I can to an invalid address, this should be fixed.

**Comment by mrexodia** [comment]
It should be fixed but it's not really an important issue, only a minor
thing at least from your description.
