### ISSUE TITLE
Opcode list-some OpCode do'nt display

### ISSUE THREAD

**Issue by dalerkd** [x64dbg/x64dbg#1349]
like image:
![bug-1](https://cloud.githubusercontent.com/assets/10300911/20917202/0ac0d856-bbcb-11e6-9e9e-1b085184b4d9.png)

BUG from x64dbg
[dump-06122016_1548200190.zip](https://github.com/x64dbg/x64dbg/files/633207/dump-06122016_1548200190.zip)

Previously, I had tried to edit OpCode and compilation.
I try to restart the software, BUG disappeared.

**Comment by mrexodia** [comment]
It looks like you're just scrolled to the right.
