### ISSUE TITLE
CreateFileA failes on an existing file

### ISSUE THREAD

**Issue by ner0x652** [x64dbg/x64dbg#1364]
x64dbg failes to open an existing file using CreateFileA
![failed1](https://cloud.githubusercontent.com/assets/2598963/21094754/10096ff4-c061-11e6-908d-c3db70ec655e.png)

The system error code is 0x20(ERROR_SHARING_VIOLATION), the file isn't opened by any other program.
![failed2](https://cloud.githubusercontent.com/assets/2598963/21094783/2f487b58-c061-11e6-8c55-9e9a4ccd8bd5.png)

The annoying thing is that OllyDbg succeeds opening it.
![olly](https://cloud.githubusercontent.com/assets/2598963/21094808/51b6f1ce-c061-11e6-868c-0e7e1ae641e4.png)

Tried opening with x64dbg running as ADMIN and as normal user.

Any ideas what is the problem?

**Comment by mrexodia** [comment]
No and it is unlikely to be related to x64dbg unless there is some anti-debug at play or the application is opening a file that is exclusively opened by x64dbg...

**Comment by ner0x652** [comment]
There is no anti-debugging in the file. If it's not related to x64dbg, why OllyDbg succeeds?

**Comment by mrexodia** [comment]
Who knows... You could check the handles tab before CreateFile and see if
it's already opened.

**Comment by ner0x652** [comment]
In x64dbg there are no handles, but it should, at least a mutex was opened, while OllyDbg identifies opened handles. So I'm not totally convinced there is no problem in x64dbg.

**Comment by mrexodia** [comment]
Okay but you are the one who should convince me that it's a bug, not the
other way around 😀

Also check with other tools like ProcessHacker to see if a handle is
already open to the file.

**Comment by ner0x652** [comment]
I didn't say that this is a bug in x64dbg. This issue was opened because another debugger succeeds in doing the same operation, on the same system. So, I thought it is helpful to question this situation, also question why x64dbg doesn't show the (other) opened handles.

**Comment by mrexodia** [comment]
It is hard for me to do anything with exact reproduction steps including
the file and os configuration etc. It is possible that x64dbg has a handle
open to the file in question but there is no way for me to verify that
without more details.

**Comment by Gbps** [comment]
I experienced this same trick. It involves opening the currently executing file in x32dbg with CreateFile. In this case it's an anti-debug/packer trick, which fails for x32dbg due with ERROR_SHARING_VIOLATION. OllyDbg does not appear to have this issue.
