### ISSUE TITLE
border too much

### ISSUE THREAD

**Issue by czghzc** [x64dbg/x64dbg#1373]
bottom of the hex editor have border too much

**Comment by mrexodia** [comment]
Could you attach a screenshot indicating what you mean exactly?

**Comment by czghzc** [comment]
i want to insert a picture ,but, i don't know how to do it

**Comment by mrexodia** [comment]
Just drag it in the comment box or if you have a link use: ![](
http://mypicture)

**Comment by czghzc** [comment]
![2016-12-15_081833](https://cloud.githubusercontent.com/assets/23645596/21207891/cb0b23c4-c2a5-11e6-9f3e-e0463e223a08.png)

**Comment by czghzc** [comment]
Very good, Thank you very much
