### ISSUE TITLE
Error in Test Instruction

### ISSUE THREAD

**Issue by Pigrecos** [x64dbg/x64dbg#1378]
Capstone decoding error Test Instruction(all size), inverted operands(Src<->
Dst) 
Eg. Binary: 84c8 -> test al, cl       capstone decoding ---> test cl,al.
I believe that other instructions may have this problem.

If you have to parse the asm code is really a serious mistake.

Sorry for my bad English

**Comment by mrexodia** [comment]
An issue has already been opened in capstone quite some time ago: https://github.com/aquynh/capstone/issues/702

**Comment by Pigrecos** [comment]
Thanks, but because in 6 months they have not solved? But they read intel manuals? or they just copied? Very bad capstone.
Why do not you change engine disasm.

;)

**Comment by mrexodia** [comment]
Change it to what?

**Comment by mrexodia** [comment]
A workaround has been added to x64dbg.
