### ISSUE TITLE
GUI : Color palette overflowing out of the "Appearance" window

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1379]
![asdasd](https://cloud.githubusercontent.com/assets/17880848/21285789/5643daa8-c468-11e6-9f91-8fd48b7479bd.gif)

I don't know if it's designed this way. But it seems odd. Feel free to close

**Comment by mrexodia** [comment]
Try removing your `style.css` and settings.

![working colors](https://i.imgur.com/5tFxW9m.png)

**Comment by techbliss** [comment]
correct the style.css will always overwrite your appearance setting.
