### ISSUE TITLE
GUI : Appearance > Font display problem

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1381]
Font name, type and size are not displayed on the combo-boxes.
![asdasd](https://cloud.githubusercontent.com/assets/17880848/21285979/cafde3ca-c46d-11e6-8a8a-073d017183b4.gif)

**Comment by mrexodia** [comment]
Try removing your `style.css` and your settings.

![notheme](https://i.imgur.com/lQR0pnM.png)
