### ISSUE TITLE
GUI : Changing font size doesn't do anything

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1382]
![asdasd](https://cloud.githubusercontent.com/assets/17880848/21286027/dc15f020-c46e-11e6-9b9b-c5185af58b7e.gif)

**Comment by mrexodia** [comment]
Try removing your `style.css` and settings.

![font works](https://i.imgur.com/nBE7QAR.gif)

**Comment by Kakarottoui** [comment]
hello how i can add ms yahei to coding i try all and all not work in w32dasm i see good but i need use dbg  ;/  and cant read text;/ any can help  ?

![dbg problem](https://user-images.githubusercontent.com/98717828/151722580-8676a7af-f7d6-45cc-bfdd-db9cb4f99d48.png)

**Comment by mrexodia** [comment]
Only monospace fonts are shown

**Comment by Kakarottoui** [comment]
i try find but i dont find... have any link?? if i understand need to have monospace font css?

**Comment by mrexodia** [comment]
Each letter needs to be the same width, otherwise the GUI won’t draw properly
