### ISSUE TITLE
Improve "Autocomments only on CIP"

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#1383]
I want to have autocomments for things which are not likely to change, such as references to the memory section. Example:

    lea r8,qword ptr ds:[7FF77BE6B560] ; [7FF77BE6B560] = "hello"

On the other hand, I don't want to have autocomments for things which are temporary, such as registers. Example:

    mov rcx,rsi ; rsi = "world"

The reason is that by having a register hold a pointer to a string, the whole disassembly changes without a good reason.

**Comment by mrexodia** [comment]
While I do agree with your point about this behavior being weird (it has annoyed me a few times as well), the only actual reason for the 'Autocomments on CIP' option is to speed up disassembly. I will see how to change this, probably it's easy enough to make it both performant and behave in an intuitive way...
