### ISSUE TITLE
Disssasembled instructions change on scrolling

### ISSUE THREAD

**Issue by Doom8890** [x64dbg/x64dbg#1384]
For some reason, disassembled instruction changes on scrolling. 

Take a look at the 1st image:
![capture](https://cloud.githubusercontent.com/assets/17911579/21287386/b2330b48-c46a-11e6-8f62-e157303028e5.PNG)

Here `MOV ECX, 9` is shown correctly, however as soon as I scroll the instruction changes because for some reason the bytes are grouped differently.

![capture2](https://cloud.githubusercontent.com/assets/17911579/21287396/e137e4d6-c46a-11e6-8fc2-95f80cf54900.PNG)

In the first image, EIP points to `004015F9`, in the second image however, it points to the same address, but the address is now contained in a group of bytes from previous instruction( If you count 4 bytes starting from `004015F6`, you'll end up on `004015F9`)

This has been bugging me for a while now, and since it is still present in the latest build, I decided to open the issue here.

There should be a way to keep the bytes aligned correctly. Any ideas?

**Comment by mrexodia** [comment]
Disassembling backwards cannot be done perfectly that's just how it is.
