### ISSUE TITLE
Minor bugs and missing translate x64dbg

### ISSUE THREAD

**Issue by lugery** [x64dbg/x64dbg#1390]
![sshot-1](https://cloud.githubusercontent.com/assets/17271734/21366138/310c4f54-c701-11e6-9bf0-6e70d98dee2c.png)
![sshot-2](https://cloud.githubusercontent.com/assets/17271734/21368457/5de600b0-c70b-11e6-895e-3eafe618295d.png)
![sshot-3](https://cloud.githubusercontent.com/assets/17271734/21371531/9298bc30-c71a-11e6-9785-33239a6ecefc.png)
![sshot-4](https://cloud.githubusercontent.com/assets/17271734/21371723/93905fe8-c71b-11e6-8aa4-7acf90dbaba4.png)
![sshot-5](https://cloud.githubusercontent.com/assets/17271734/21372049/a8afcf4c-c71d-11e6-9d74-4ab7c329d00e.png)
![sshot-6](https://cloud.githubusercontent.com/assets/17271734/21372464/e50adfd4-c71f-11e6-9a72-0bb0c152ff61.png)
![sshot-7](https://cloud.githubusercontent.com/assets/17271734/21373056/5cd9ef60-c724-11e6-811a-690ab6f60ecd.png)
![sshot-8](https://cloud.githubusercontent.com/assets/17271734/21398168/0b514590-c7af-11e6-9ba4-f74c426b54f6.png)
![sshot-9](https://cloud.githubusercontent.com/assets/17271734/21398069/b5cbb38a-c7ae-11e6-8e93-996c0b50afc5.png)

**Comment by lugery** [comment]
![sshot-5](https://cloud.githubusercontent.com/assets/17271734/21372049/a8afcf4c-c71d-11e6-9d74-4ab7c329d00e.png)

**Comment by mrexodia** [comment]
For translations of the dialogs, extract these files in the `translations` folder: https://mega.nz/#!K4JHFTSY!tI45DnAj9JZR2zV99YE6eV_OTI1n-zOU4f8jLeC7lZw

1. As desired
2. This has been fixed
3. Use the qt translations
4. Should be fixed
5. Use the qt translations
6. Use the qt translations
7. Cannot change those messages they come from Windows
8. Use the qt translations

**Comment by lugery** [comment]
Thanks for help :) I am writing in English wrong. :(
There are 9 pictures above :)

1. Correct spelling "LoadLibrary". Is not it?
2. Thank you. It is nice :) I saw..

3, 4, 5, 6, 8 , 9 -> crowdin.com --> .xliff download --> <source> not found. :(
Sample:
![sshot-10](https://cloud.githubusercontent.com/assets/17271734/21435114/942342a2-c880-11e6-8c3c-4c67563d9578.png)

7. I did misrepresent :(

**Comment by lugery** [comment]
Thank you. I'm wait.. :)
