### ISSUE TITLE
Error starting process (CreateProcess, ERROR_CHILD_NOT_COMPLETE)

### ISSUE THREAD

**Issue by Danny911110** [x64dbg/x64dbg#1391]
Here is the log file.

Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing capstone...
Initializing Yara...
Getting directory information...
Start file read thread...
Symbol Path: C:\Tool\snapshot_2016-12-07_22-49\release\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering Script DLL command handler...
Starting command loop...
Loading plugins...
Handling command line...
Initialization successful!
Mnemonic help database loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Reading notes file...
File read thread finished!
Debugging: C:\Users\wangdann\Desktop\IDA data\ntoskrnl.exe
Database file: C:\Tool\snapshot_2016-12-07_22-49\release\x64\db\ntoskrnl.exe.dd64
Error starting process (CreateProcess, ERROR_CHILD_NOT_COMPLETE)!

**Comment by Danny911110** [comment]
Thanks for your answer.

**Comment by mrexodia** [comment]
x64dbg will only debug executables that can be started by Windows using `CreateProcess`
