### ISSUE TITLE
Debug error for LenaTute19(ReverseMeB.exe)

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1392]
![asdasd2](https://cloud.githubusercontent.com/assets/17880848/21418361/ba806f22-c846-11e6-8372-252f0652df52.gif)

**Comment by mrexodia** [comment]
What's the bug?

**Comment by gmastergreatee** [comment]
Ahh my bad! The exception at the end was caused due to a malware that I was reversing previously, some of whose related files were still left in the system and were interfering with the program's(x64dbg) working.
