### ISSUE TITLE
missing strings in GUI menu

### ISSUE THREAD

**Issue by TakahiroHaruyama** [x64dbg/x64dbg#1393]
Hi,

I downloaded the latest snapshot (snapshot_2016-12-17_17-11.zip) then run it, but there is a problem on Windows 7 x86 machine.
Specifically, I can't see any string in GUI menu like the following image.

<img width="1920" alt="screen shot 2016-12-22 at 7 37 55 pm 2" src="https://cloud.githubusercontent.com/assets/6092487/21423055/4a06c5ce-c87e-11e6-8078-ea68b82d90ff.png">

The same binary works fine on Windows 8.1 x64 machine.

<img width="1275" alt="screen shot 2016-12-22 at 7 41 39 pm" src="https://cloud.githubusercontent.com/assets/6092487/21423165/d6da80bc-c87e-11e6-96dc-0856957fcb2f.png">

Any thought?

**Comment by mrexodia** [comment]
What happens if you switch tabs?

**Comment by TakahiroHaruyama** [comment]
the same issue. 
<img width="1920" alt="screen shot 2016-12-22 at 10 49 28 pm 2" src="https://cloud.githubusercontent.com/assets/6092487/21427630/031c7512-c899-11e6-8a2e-d4bcfd2dc4b1.png">

**Comment by mrexodia** [comment]
Your theme appears custom, it looks like this on a clean-ish Windows 7 x64 install with Windows classic enabled:

![](https://i.imgur.com/lrWRHjZ.png)

**Comment by TakahiroHaruyama** [comment]
I do not modify the appearance at all. I'll use the old version instead of the latest one.

**Comment by mrexodia** [comment]
Sorry but I cannot provide backwards compatibility with old service packs because Qt probably doesn't support them. You can compile x64dbg with older versions of Qt to try to get it to work.

**Comment by TakahiroHaruyama** [comment]
Got it. Thanks.
