### ISSUE TITLE
BUG:Parse instruction error

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1395]
- repne scas**d** eax,dword ptr ds:[rdi]
- ->
- repne scas**w** eax,dword ptr ds:[rdi]

x64dbg：
![x64dbg](https://cloud.githubusercontent.com/assets/16742566/21448976/3f3810bc-c923-11e6-92ed-68e2a0d39492.png)

ida：
![ida](https://cloud.githubusercontent.com/assets/16742566/21448829/ce53156e-c921-11e6-981f-24a505a9cce5.png)

video:
[video link](https://github.com/stonedreamforest/x64dbg_theme_RelaxYourEyes/releases/tag/video)

c code:

long long rcx=-1,rax=0;
short *rdi;
for ( int offset = 0; rax != rdi[offset] || !rcx; rcx-- , offset++ );
rcx~=rcx;

ida is right~

**Comment by mrexodia** [comment]
The screenshots are the same and your video is a .exe and password protected.

**Comment by stonedreamforest** [comment]
password: 123

**Comment by stonedreamforest** [comment]
vs:
![vs](https://cloud.githubusercontent.com/assets/16742566/21449015/b2da2bf4-c923-11e6-8264-9f2119617f4e.png)

**Comment by mrexodia** [comment]
https://github.com/aquynh/capstone/issues/356
