### ISSUE TITLE
module name on CALL destination

### ISSUE THREAD

**Issue by winkerbie** [x64dbg/x64dbg#1396]
I notice that on every CALL _function_ instruction, the function is listed as _\<module name\>.sub_xxxxxxxx_ 

This gets really untidy on modules with long file names. Is there anyway to toggle it on/off so it just says CALL _sub_xxxxxxx_

I realise for the windows and external APIs that it may be helpful, but for calls within the same module it is not necessary

**Comment by mrexodia** [comment]
You can limit the maximum size of the module shown in disassembly.

**Comment by winkerbie** [comment]
can you explain how? I have look in every menu and settings

**Comment by mrexodia** [comment]
It's an undocumented setting because it's never used. Search for MaxModule
in the source code

**Comment by winkerbie** [comment]
Ah okay thanks, found it in the .ini

[Disassembly]
MaxModuleSize = 0 (instead of FFFFFFFFFFFF)

**Comment by mrexodia** [comment]
This issue can be closed if a spin box is added for this setting, should be easy.

**Comment by winkerbie** [comment]
I would if I knew how, sorry I do realise it is open source

**Comment by mrexodia** [comment]
No worries, it's just for future documentation on the 'easy' label.

**Comment by torusrxxx** [comment]
Ollydbg has the feature not to show the module name if it is within the same module.
