### ISSUE TITLE
change log link color not realtime Refresh

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1399]

**Comment by stonedreamforest** [comment]
and if alt+f2 symbols window not clear

**Comment by stonedreamforest** [comment]
memory map windows information not clear

**Comment by stonedreamforest** [comment]
log windows  not clear

**Comment by mrexodia** [comment]
The log cannot be fixed, see http://doc.qt.io/qt-5/qtextdocument.html#defaultStyleSheet-prop

> Changing the default style sheet does not have any effect to the existing content of the document.

Clearing logs is not preferred because you may want to see what causes an exit.
