### ISSUE TITLE
Breakpoint which doesn't break

### ISSUE THREAD

**Issue by michaelpittino** [x64dbg/x64dbg#1400]
Hello, is there any way to create a breakpoint which does not break but instead execute a script?
I found in the docs

> If fast resume is set and break condition evaluated to false:
> Resume execution of the debuggee (skip the next steps). This will also skip executing plugin callbacks and GUI updates.

I tried that but the breakpoint still breaks.
This is my bp setting: https://i.imgur.com/fS4NC9m.png

But even if that would work it would mean that the `command text` wouldn't be executed, right?

Thanks for any help!

**Comment by mrexodia** [comment]
Ah yes, "false" is not a valid keyword, try using "0" instead. I will
update the documentation to represent this.

**Comment by mrexodia** [comment]
Please comment if this is still an issue.
