### ISSUE TITLE
suggestion：Highlight Selected Register Like IDA

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1401]
if Select Register （or rax\rcx\rdx\al\cl\xmm0\xmm1）In the current picture：
![1](https://cloud.githubusercontent.com/assets/16742566/21515466/f6c7348e-cd0a-11e6-9d0b-a746560cca90.png)

the picture will Highlight Selected Register：
![2](https://cloud.githubusercontent.com/assets/16742566/21515475/165a365c-cd0b-11e6-8c5d-3f5549a725ac.png)

like ida：
![3](https://cloud.githubusercontent.com/assets/16742566/21515480/22c5c01e-cd0b-11e6-9fc4-daa539680f1f.png)

**Comment by stonedreamforest** [comment]
If it is also support Function(or Immediate /Address)  it Will be perfect

**Comment by mrexodia** [comment]
Already supported. Right click on the register and choose "highlight" or you mean that clicking on the register text will trigger that option?

**Comment by stonedreamforest** [comment]
Highlighting the initiative to the selected item
if i selected  rax ,the rax Highlighting  .
not selected  rax ,not Highlighting  .
for example：
![gif](https://cloud.githubusercontent.com/assets/16742566/21521477/421ea2f0-cd38-11e6-972c-c6d163dc2997.gif)

**Comment by mrexodia** [comment]
First enable the setting (otherwise you have to press `H` every time):

![permanent highlighting mode](https://i.imgur.com/5bDkEB7.png)

![highlight fest](https://i.imgur.com/Mei1zzm.gif)
