### ISSUE TITLE
Search for string does not find all results

### ISSUE THREAD

**Issue by affelwafro** [x64dbg/x64dbg#1405]
Dear x64dbg team,
dear mrexodia,

I've got some really strange problems with the 'search for string' function.

When using the snapshot from 7th of december and do a 'Search for -> Current Module -> Strings' x64dbg will give me 4958 results.

When using the latest snapshot (30th of december) I will get 1257 results.

After executing the application there are some more results, but the one I'm looking for is still missing.
OllyDBG got ~28.000 results on the same executable, including the string I'm looking for.

Even a 'Search for -> All Modules -> Strings' won't give me the results I needed.

I also tested it with another application but x64dbg won't give me all strings.

I'm running Win7 on 32bit. Tried it with and without any plugins. Tried in and out of a sandbox. Tried with and without admin privileges.
It's a really old machine I'm using here (2x 1.06 GHz, 2GB RAM). x64dbg was not usable with WinXP on my machine. On Win7 everything is working fine. :-)
I can't tell you if the same problem occurs on my desktop machine but am able to test this next week.

If you need any further information feel free to ask for it.
Maybe it's not a bug and I'm doing something wrong?

Finally, thanks for this nice application. I really love x64dbg and looking forward to completely switch from olly to x64dbg in near future. :-)

With best regards

**Comment by torusrxxx** [comment]
Thanks for your report. In fact x64dbg is weak at string searching,
especially for non-English applications. It is assumed that a hypothethical
plugin for each language will resolve the problem.

**Comment by mrexodia** [comment]
Well that does mean that the latest update did not improve the situation...

**Comment by mrexodia** [comment]
@affelwafro could you provide the/an executable that reproduces this behaviour?

**Comment by affelwafro** [comment]
Thanks for your fast replies. Never thought to get an answer today. :-)
Yup I can provide an executable, should I attach it?
Alt. http://softany.com/download.htm (WinCHM Pro)

When looking for the string 'Unregistered' you will get some results, but not all, with the snapshot from the 7th of december.
When trying to search for this string with the snapshot as of 30th of december, x64dbg can't find any string.

As far as I'm able to, I try to test every snapshot and noticed that it got more worse with the snapshot as of 23th of december. (but I missed some snapshots before).

With best regards

**Comment by mrexodia** [comment]
With OllyDbg v1.10 if I search for strings in `winchm.exe` (md5 `AB53BDC9AEF61C6B431F816A39C30B26`) it will find 3841 strings. When searching with the reverted (pre-23 december) string search it will find 4407 results (although admittedly some of them are false positives).

**Comment by affelwafro** [comment]
Kinda curious,
I searched with OllyDbg v2.01 (can't see where OllyDbg v1.10 shows the number of found strings)
![olly](https://cloud.githubusercontent.com/assets/8084390/21581786/672d055e-d040-11e6-83bb-f46dde436dc0.PNG)

On the bottom left corner it shows me the number of found strings. As far as I understood it shows strings and references to strings. I'm not sure if Olly is searching All Modules or just the Current Module when searching for strings.

**Comment by mrexodia** [comment]
Oh Olly 2 also seems to include the strings that are included directly in
the code. The first string for example isn't a reference but rather the
string data itself.

**Comment by affelwafro** [comment]
Ah, thanks for this information.

I just did a little bit of research, hopefully it's some kind of useful for you.

In WinCHM, take a look at the address, 0x57177c
This is the string I'm searching for, normally it should be '[Unregistered]'.

I now tried the earliest snapshot I've got on my desktop PC, it's snapshot_2016-05-26_01-13.7z.
This version is able to find the above string, but is missing some others.

Or maybe another example, I was doing some CrackMe's and noticed something. It's a crackme from crackmes.de, since the site is down at the moment, I've uploaded the file to zippyshare, https://anonym.to/?http://www74.zippyshare.com/v/gTdVI9we/file.html
I tried to attach the file here but github don't want to attach a zip file.
Alt. you can download the file from Tuts4You (https://anonym.to/?https://forum.tuts4you.com/topic/26285-crackme-crackmesde-collection-2011/). The file in the archive is called 500-crackme.zip.

When reaching the instruction at 0x4021A2, eax is pushed to the stack. The stack now shows
0x00306494 - &L":0000046d"
When you take a look to the dump at address 0x00306494, there is the string "DEMO VERSION".

**Comment by mrexodia** [comment]
Alright, so the issue appears to be that x64dbg will try to match string pointers before the actual strings. With extended ASCII UTF-16 lots of text is in the pointer range so I will try to find a workaround for that...

**Comment by affelwafro** [comment]
Thanks for your fast support, made my donation on bountysource.
It seems to work fine with the latest snapshot as of 2nd of january 2017.

I will try to keep an eye on this.
Just as a question, some posts above you wrote the following,

> Oh Olly 2 also seems to include the strings that are included directly in the code

Would it be possible to make an option to search for those strings, too?
Like OllyDbg 1.10,
![olly_strings1](https://cloud.githubusercontent.com/assets/8084390/21597802/efae4bfc-d150-11e6-9ab5-529346b03a25.PNG)

or like OllyDbg 2.01,
![olly_strings2](https://cloud.githubusercontent.com/assets/8084390/21597808/0de3b508-d151-11e6-8dbc-07ef0cefca07.PNG)

I would prefer an option because some people may don't want to mess up their results.

Thanks again for your nice and fast support. Keep up the good work. I wish all of you a happy new year.

**Comment by mrexodia** [comment]
I don't have any plans to directly search for strings in the string
references option, perhaps this is something for a plugin.

Also, thanks a lot for your donation!

**Comment by mrexodia** [comment]
Okay, I did some final verifications and x64dbg finds almost all strings OllyDbg does (and much more ones that OllyDbg doesn't find). The only ones it does not find are:

```
0055C4D8
005606A0
00595CFA
00595D3A
005A3866
005AB2A4
005C492E
005C6472
005C66BE
005C8006
005C8356
005D0CB2
```

For which the only interesting one is `005A3866`

![switch table](https://i.imgur.com/dsZsu4k.png)

The reason for this is that x64dbg linearly disassembles the executable to find string references and this part of code is mixed with data which means that `005A3866` is not disassembled. As you can see, the actual reference to the string is correctly detected when viewing the code.

The other undetected strings are some kind of Delphi string format (size,data) that I don't plan to support.
