### ISSUE TITLE
Bugged focus for patches window

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1407]
The focus of the patches window seems to be broken (reset on every action).

1. Debug anything, then patch multiple modules.
![1](https://cloud.githubusercontent.com/assets/11916365/21583951/671f8d4e-d09e-11e6-9364-e98e3bf59aec.png)
2. In the patches window, you won't be able to select any module other than the first one.
Also notice how the first module is highlighted in gray, despite it being selected.

- You can't select separate patched bytes (selection disappears).
- `Pick Groups` button will only appear for a second before the patches window steals its focus.
- Sometimes selecting buttons as `Restore Selected` or `Import` will require 2-3 clicks.

**Comment by wk-952** [comment]
Can i nag you a little bit more about this ?
The focus will still be reset (to the first item in the modules list) on the following actions:
1. Select any module other than the 1st one, then (de)select a patch group.
Now the 1st module will be selected.
2. Pressing `(De)Select All` or `Restore Selected` will also reset the selected module.
3. `Pick Groups` now works, but after clicking `Toggle` once, the patches window will steal the focus.
Also after that, the selected module will be reset.

**Comment by mrexodia** [comment]
Thanks a lot for the easy reproduction steps @wk-952!

It should be fixed now, but a refresh issue with the patches might pop up at some point. I will check more to make sure that's not the case.
