### ISSUE TITLE
Arguments Window Incorrect on x64bit Dbg

### ISSUE THREAD

**Issue by winkerbie** [x64dbg/x64dbg#1408]
This is only an issue for the x64bit version of the debugger.

The arguments window on the middle right of the dbg window shows the first 4 arguments correctly, but any extra arguments are listed as [rsp], [rsp+8], [rsp+10]...

This is incorrect. The microsoft x64 fastcall convention requires the caller of a function to leave at least 4 qwords or 'shadow space'/'home space' on the stack before pushing extra arguments. 

For ARG 5 onwards it should start from [rsp+28]... etc

**Comment by mrexodia** [comment]
Update it has already been fixed.

**Comment by ThunderCls** [comment]
Actually ARG 5 should start at [rsp+0x20]

1st arg -> RCX -> [RSP+0] / [RBP+16]
2nd arg -> RDX -> [RSP+0x8] / [RBP+24]
3rd arg -> R8 -> [RSP+0x10] / [RBP+32]
4th arg -> R9 -> [RSP+0x18] / [RBP+40]
5th arg -> [RSP+0x20] / [RBP+48]
6th arg -> [RSP+0x28] / [RBP+56]
.....

**Comment by winkerbie** [comment]
Thats a good point, though after the call it becomes [rsp+28]
How did you determine the rbp+XX values?

**Comment by mrexodia** [comment]
Rbp is ignored and not considered at all in x64dbg.

**Comment by stonedreamforest** [comment]
- void fun(rcx,rdx,r8,r9,rsp+0x20,rsp+0x28,rsp+0x30.......);
![1](https://cloud.githubusercontent.com/assets/16742566/21634434/3e8871de-d292-11e6-870d-368bfa0fce7a.png)

so should chang it like this :+1: 
rcx:xxxxxxx
rdx:xxxxxxx
r8:xxxxxxx
rc9:xxxxxxx
[rsp+0x20]:xxxxxxx
[rsp+0x28]:xxxxxxx
[rsp+0x30]:xxxxxxx
[rsp+0x38]:xxxxxxx
and more....

**Comment by mrexodia** [comment]
No, the arguments widget is based on when you're inside the call so the
arguments should start at rsp+0x28...

**Comment by stonedreamforest** [comment]
you should believe me  
i reverse  x64 software everyday 

I found an example：
![2](https://cloud.githubusercontent.com/assets/16742566/21643188/f1c61164-d2c1-11e6-8302-500ff38af160.png)

**Comment by mrexodia** [comment]
Can't you understand that inside a call there is an extra address on the
stack (it's called return address) so the arguments all shift one qword
up... I mentioned this a few times now.

**Comment by stonedreamforest** [comment]
I know what you mean...

**Comment by mrexodia** [comment]
So then what's the problem? The arguments have already been adjusted days
ago.

**Comment by stonedreamforest** [comment]
void fun(rcx,edx,r8,r9,rsp+0x20,rsp+0x28);

I mean if call fun now:
the arg:

rcx
rdx
r8
r9
[rsp+0x20]
[rsp+0x28]


you mean  into the function will be push return_address:
so 
the arg:

rcx
rdx
r8
r9
[rsp+0x28]
[rsp+0x30]


**but i think the stack will be change**

like:
push rdi     
sub rsp,160  
mov rdi,rsp

**Comment by mrexodia** [comment]
Yes the stack will change but the arguments widget is only valid on the
function call (similar to olly or if you hook a function)

**Comment by mrexodia** [comment]
Sorry about that, the fixed I pushed was inadequate. It has now been updated and the stack position will be `[rsp+20]` when the disassembly is on the `call` instruction. You can use this in conjunction with the checkbox mode on 'Calls' to only update the arguments widgets when on calls.

![only calls](https://i.imgur.com/IBK1Knn.png)

**Comment by winkerbie** [comment]
just to clarify now...

The arguments widget is only valid (and displays the correct information) **BEFORE** stepping into the CALL (i.e. when RIP is on the CALL xxxxxxx instruction)

Can you explain the difference between the checkbox - calls, locked and unlocked? This isn't documented anywhere

**Comment by mrexodia** [comment]
Unlocked means the widget updates when the disassembly updates (eg on stepping)

Locked means the widget will not update (contents will stay the same even if you step)

Calls means the widget will only update if the disassembly is on a call instruction.

**Comment by mrexodia** [comment]
Also it shows as valid information as it can. If not on a call it will take the return address in account for stack space, but registers are volatile so obviously it cannot keep those valid.
