### ISSUE TITLE
View Names [Ctrl + N]

### ISSUE THREAD

**Issue by dEig65** [x64dbg/x64dbg#1410]
How can I see imported names used by my executable?
I can see it Immunity Dbg via 'Executable modules' and [Ctrl + N]

**Comment by mrexodia** [comment]
Use the symbol tab to view imports/exports for modules and you can use the find intermodular calls option to find called functions with a name.

**Comment by qartveli34** [comment]
From the symbol tab I can get symbols but can not find references

**Comment by mrexodia** [comment]
Indeed you can use the search for intermodular calls for that as I
mentioned.

**Comment by qartveli34** [comment]
https://s28.postimg.org/bikgdyt31/Untitled.png

**Comment by mrexodia** [comment]
Follow the relevant section of the module in the disassembler, right click
there, search for, intermodular calls.

**Comment by qartveli34** [comment]
Wow. I get it. Thanks ^^

**Comment by mrexodia** [comment]
Feel free to close the issue if it is resolved.
