### ISSUE TITLE
GUI BUG: The instruction is not fixed

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1413]
![g222if](https://cloud.githubusercontent.com/assets/16742566/21793359/7750672c-d72b-11e6-9255-8d6c0657fe12.gif)

**Comment by mrexodia** [comment]
This is the expected behavior. You can do data analysis to deal with mixed code and data.

**Comment by stonedreamforest** [comment]
IT'S fun address.

ida show:
![1](https://cloud.githubusercontent.com/assets/16742566/21793516/15268642-d72d-11e6-8f1f-6371c2a5c7a8.png)

**Comment by mrexodia** [comment]
Can you scroll up in ida?

**Comment by stonedreamforest** [comment]
yes  It seems to be the default

**Comment by mrexodia** [comment]
And what is actually there in ida?

**Comment by stonedreamforest** [comment]
vs2013 the same as x64dbg.
ida may be wrong

**Comment by mrexodia** [comment]
Can you show a screenshot of what ida shows if you scroll above the
function?

**Comment by stonedreamforest** [comment]
![ida](https://cloud.githubusercontent.com/assets/16742566/21798771/2b55c0e4-d751-11e6-88c4-dde071f563bd.gif)

**Comment by mrexodia** [comment]
yes, so it is as I expected. There is code mixed with data (a switch table in this case):

![switch table](https://i.imgur.com/IuFFOWB.png)

What you can do is go to `18000DC84` in the x64dbg disassembly, hit `D` and enter the size `1c` it should then disassemble everything correctly.
