### ISSUE TITLE
Option to run x64dbg in background or hidden mode, also cmd to detach and exit the x64 dbg.

### ISSUE THREAD

**Issue by MrIQZero** [x64dbg/x64dbg#1415]
I would like to know if there is any way to run x64dbg in background or hidden mode. 
also it would be great if someone can let me know if there is a command or a way to "detach & terminate" the debugger using script.

Example: I have set a debugge initialization script, as soon and i detach the debugger using script it would detach the program but also unload the script; hence i cannot tell the debugger to exit/terminate from the script.

Would be great if someone can help me figure it out thanks,

**Comment by mrexodia** [comment]
There are no plans to provide x64dbg without a GUI.

For detach+exit you could write a plugin that calls both commands. Or you could try appending the debug exit command (which doesn't exist as far as I know) with a `;` eg `detach;exitdebugger`
