### ISSUE TITLE
Searching a pattern in all modules

### ISSUE THREAD

**Issue by sarcarx** [x64dbg/x64dbg#1420]
It would be a nice feature to have if we could search a pattern through all modules, the option only appears when selecting search for the current region.

**Comment by duncanisgoed** [comment]
You can search all modules for patterns in the memory map. Just hit ctrl+b

**Comment by mrexodia** [comment]
This just needs that context menu entry to use the [findallmem](http://help.x64dbg.com/en/latest/commands/searching/findallmem.html) command.

**Comment by gmastergreatee** [comment]
Seems related to #1285
