### ISSUE TITLE
Debugger doesn't display PID in decimal.

### ISSUE THREAD

**Issue by Mefist0** [x64dbg/x64dbg#1424]
Hello!
I noticed this bug in a earlier versions of the debugger. And it's still in a newest version.
When I'm changing option in Preferences->GUI->Show PID in HEX there's no any effect. I restarted the program after changing options. The PID of the process is always displayed in HEX.

See the screenshot:

![pid-in-hex](https://cloud.githubusercontent.com/assets/17492628/22054551/3777b258-dd67-11e6-8ed9-acd6e13c6ed9.PNG)

Thank you!

**Comment by torusrxxx** [comment]
Yes, PID there is currently always in hex.

**Comment by Mefist0** [comment]
Hello all!

Unfortunately the bug is still in a new release.

**Comment by mrexodia** [comment]
A fix is in a pull request but it is not yet merged because of unrelated
issues.
