### ISSUE TITLE
cannot ignore "status_invalid_exception_handler" exception

### ISSUE THREAD

**Issue by waterdr0p** [x64dbg/x64dbg#1428]
x64dbg version: 2017.1.10
OS env: win10 x64
x86dbg dbg program: EdrLib.dll
          http://pan.baidu.com/s/1c9sW94
Load EdrLib.dll and then F9, you will enconter x64dbg exception of "status_invalid_exception_handler". The same exception will not show in ollydbg2.01. I tried to ignore this exception by <Shift + F9> or [option/exception -> set ignorance 0000-ffff] but it is not work. So I report this issue, wish that who can help me.

**Comment by mrexodia** [comment]
You have to manually swallow the exception in the debug menu.

**Comment by waterdr0p** [comment]
I have tried every item of "debug menu" but also can't settle it.

**Comment by mrexodia** [comment]
Notice that a second chance exception actually means that the program has
crashed. You have to change cip and the swallow the exception to continue
execution.
