### ISSUE TITLE
.dd32 database file from previous x64dbg version causes CMP to malfunction

### ISSUE THREAD

**Issue by Saduff** [x64dbg/x64dbg#1429]
Hi. I came across a very odd bug. OS: Windows 10 x64
Steps to reproduce:

1. Download this ZIP and extract it: https://www.mediafire.com/?7sjyfbtnb7olilv
1. Copy "TheSecretWorldDX11.exe.dd32" to x32/db folder.
1. Open "TheSecretWorldDX11.exe" with the debugger.
1. It should immediately break (before the EP of the exe) at
`5FFA8D94 | 8B 54 02 1C              | MOV EDX,DWORD PTR DS:[EDX + EAX + 1C]   |`
1. Press F9 to run to the next breakpoint.
1. It should break at
`5FFA2666 | 38 19                    | CMP BYTE PTR DS:[ECX],BL                |`
1. There should be 0x55 at byte ptr[ecx] and in BL.
1. Step over the CMP and notice how ZF is set to 1 like it should be.
1. Now, repeat steps 3-4, but this time at the breakpoint, change ECX to 0x00838430
1. Press F9 to run to the next breakpoint.
1. There should be 0x55 in memory and in BL like before.
1. Step over the CMP and notice how ZF is **not** set to 1 like it should be.

Removing the .dd32 and letting the debugger create a new one fixes this problem.

EDIT: Seems it's not just the database from an older version of x64dbg. Replacing the dbghelp.dll with a slightly modified recompiled version causes it too.

**Comment by mrexodia** [comment]
This is not a bug. The actual contents of the memory are 0xCC (since a breakpoint is placed on 0x00838430). The original bytes are shown because that's more useful from a user perspective...

**Comment by Saduff** [comment]
Ah, you're right. Oops.
