### ISSUE TITLE
step into slow with mouse

### ISSUE THREAD

**Issue by dhucul** [x64dbg/x64dbg#1430]
step into slow with mouse , ok from file menu.

**Comment by mrexodia** [comment]
could you give more information and exact reproduction steps?

**Comment by dhucul** [comment]
this occurs after a refresh of a window

**Comment by mrexodia** [comment]
That is still not really enough information to reproduce the issue. What exactly do I have to do to reproduce the issue?

**Comment by dhucul** [comment]
similar to "#1337 opened on Dec 1 2016 by wk-952" but with no Kapersky installed.
