### ISSUE TITLE
show name of the currently browsed function / friendly names in callstack

### ISSUE THREAD

**Issue by bloodth0rn** [x64dbg/x64dbg#1433]
example: I'm in the middle of some long function . Let's say it's an export, it has a name. I would like to know it just like in IDA.

![image](https://cloud.githubusercontent.com/assets/3116731/22179814/60aff8fc-e05e-11e6-9c5c-221c8fc3a364.png)

Or more friendly names in callstack like "Return to Module.address (Friendlyname) from Module.address (Friendly name)

**Comment by mrexodia** [comment]
Look in the info box.
