### ISSUE TITLE
Scylla dump error

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1434]
![GbbeFId](http://i.imgur.com/GbbeFId.gif)
<a href="https://expirebox.com/download/b1f8c86d7d694a455ec6a4cbb4565271.html" target="_blank">Download target file</a>
<a href="http://www.yourfilelink.com/get.php?fid=1302488" target="_blank">Download LenaTute27(contains target)</a>

I had this peculiar Scylla error. Reproduction steps :-

```
1>Load the file bootca.exe in x32dbg.
2>Run till EIP = Entrypoint(for cases when system breakpoint is enabled in settings)
3>Make sure there are no exceptions in the "Exceptions List" in Options
4>Now, hit F9 or click on Run button 20 times to land on the address 0068E7FA(the last exception instruction before the app starts running)
5>Go to "Memory View" & set breakpoint on bootca.exe as shown in the gif file(Try pressing F2 after selecting the memory region, for me it didn't work so I had to use the context menu -> happens sometimes).
6>Now, hit F9 or click on Run button once more to land on the OEP of the file.
7>Now, try to dump the process from memory & voila, Scylla hangs.
```

Maybe this is OS related. Please look into this.

I'm using:-
```
Windows 8 -> 64 bit
```
Thank you for your time
Feel free to close.

**Comment by gmastergreatee** [comment]
More info - ChimpREC does the job well(dumping)

<a href="https://file.town/download/8mnqgz0htcwlias33yvrmh812">Download Link</a>
<b>NOTE : Antivirus may detect false positives</b>
Supplementary(maybe helpful):-
<a href="https://file.town/download/sv1or3ifvo33tliagtg0n50gg">What is ChimpREC & how it works</a>

**Comment by skillax** [comment]
Probably related to https://github.com/x64dbg/x64dbg/issues/1425
You're using the 2017-01-19 release, which is about the last build affected by this; could you please retry with the latest 2017-02-05 version ? I'll bet that one works :)

**Comment by gmastergreatee** [comment]
Seems like an OS issue. Tried it with a clean install of Win7, no issues.
