### ISSUE TITLE
memory breakpoint err

### ISSUE THREAD

**Issue by yudi010** [x64dbg/x64dbg#1435]
GetVolumeInformationA (7C821BA1)下内存断点, 断点会显示在_wcsnicmp(7C801000)

win xp 32

195840531@qq.com

**Comment by mrexodia** [comment]
This is the expected behavior. See http://x64dbg.readthedocs.io/en/latest/commands/breakpoint-control/SetMemoryBPX.html

> Set a memory breakpoint (GUARD_PAGE) on the whole memory region the provided address is in.
