### ISSUE TITLE
does anyone can help to test this plugin pack why can't search for strings?

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#1442]
download this pack for test, thanks

http://www15.zippyshare.com/v/57K52fzk/file.html

**Comment by mrexodia** [comment]
I don't want to support any kind of plugin packs here. Ask the original plugin authors.

**Comment by cxj98** [comment]
all plugins download from http://plugins.x64dbg.com

**Comment by mrexodia** [comment]
That is a user-maintained list. Contact the original plugin authors
individually if you experience issues.
