### ISSUE TITLE
When I search the function CoCreateInstance I get the wrong address

### ISSUE THREAD

**Issue by lld4dll** [x64dbg/x64dbg#1445]
When I search the function CoCreateInstance I get the wrong address
below is the picture that show the wrong mem address

![image](https://cloud.githubusercontent.com/assets/10267760/22424358/fc344a2a-e6fe-11e6-918b-1ad5ca90e0e6.png)

When I take from the symbols the address I have the right address

for reproduce the bug
attach installagent.exe on x32dbg (windows 10 32 bit)
and try to bp on CoCreateInstance

**Comment by blaquee** [comment]
What is installagent.exe?

**Comment by lld4dll** [comment]
one of the processes in windows 10

**Comment by skillax** [comment]
That's due to the exe-file having 'install' (or 'setup' or even 'launch') in it's filename; rename the file to test.exe and please test again, I'll bet it works fine :)  This is Windows behaviour by design (inserting SHIMs), not a x64Dbg issue.  kernel32.GetProcAddress gets screwed up as well ....

**Comment by lld4dll** [comment]
In ollydbg it works fine
This issue happen on x64dbg.....

**Comment by mrexodia** [comment]
@lld4dll Did you check if apphelp.dll is loaded? Also, did you check in the symbols if CoCreateInstance exists?

**Comment by lld4dll** [comment]
I checked CoCreateInstance on symbols and got the right address, I didn't checked if apphelp.dll is loaded
