### ISSUE TITLE
End trimmed when dumping Windows-1251 codepage memory page

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1447]
I have a program which decrypts a file and stores it in pure text in memory. The text is in cyrilic -> Windows-1251. I find that page in the Memory Viewer tab and dump to file. The beginning of the file is perfect, but somewhere around the last 50-60 lines everything is filled with '00'. I assume this is some incorrect calculation of the size of the page. The dump shows the page properly, with those 50-60 lines in-tact.

Thanks!

**Comment by ViRb3** [comment]
I tried the same workflow with Cheat Engine and it returned that some of the memory is unreadable, with the exception that it couldn't write a single character unlike x64dbg, which wrote everything but the last lines. The page is marked RW.

**Comment by ViRb3** [comment]
Jan 6 snapshot - writes everything but last 50-60 lines.
Jan 30 snapshot - 'Failed to read memory...'.

**Comment by ViRb3** [comment]
Newest snapshot saves everything just fine!

**Comment by mrexodia** [comment]
😀
