### ISSUE TITLE
loadlib bug

### ISSUE THREAD

**Issue by 0ffffffffh** [x64dbg/x64dbg#1449]
Debugger causes an access violation randomly when the loadlib command called.

I think the origin of this bug is TitanEngine's SetBPX function. The **loadlib** command uses remote code injection technique to load library. It writes the loader payload and set a breakpoint at the end of payload. Ok. But sometimes SetBPX does not set breakpoint. And naturally it doesn't handle the [cbDebugLoadBPX](https://github.com/x64dbg/x64dbg/blob/8849c7629a653e51a22f4b3fe2e7c9442ed1950f/src/dbg/commands/cmd-misc.cpp#L57) And as a result, the debugger tries to continue the payload code and it crashes.  

![screenshot_50](https://cloud.githubusercontent.com/assets/437161/22560400/8826f57c-e985-11e6-8beb-56ad6d826596.png)

**Comment by mrexodia** [comment]
Please be sure to check if this happens without plugins also.

**Comment by 0ffffffffh** [comment]
Actually, this issue is not related with user perspective. Because, I used this command to get work a plugin's feature that I develop. Why I used that? I was looking for something to load a library in being debugged process. But I realized that the SDK does not provides a function directly. TitanEngine provides RemoteLoadLibrary but it does not work at all. 

So I said If I can use the DbgCmdExec, I can be able to send command to the debugger programmatically. So I did. Its runs without problem for less frequently calls. When this command called frequently it runs unstable. So I put some Sleep after DbgCmdExec call to clear suspicion. And its runs again without any problem. 
 
When the crashes, seems the main thread trying to free an invalid memory blocks. 
```x64dbg.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFDF494F6B0).```

![screenshot_52](https://cloud.githubusercontent.com/assets/437161/22576163/1e550602-e9cb-11e6-9cb8-fba9b28373df.png)

Meanwhile, When I take a look to my worker thread it seems to runs as expected. 

If the loadlib usage is invalid, it would be great some support API for that task.

**Comment by mrexodia** [comment]
I will check out the heap corruption. Would it be possible for you to
create a sample plugin that triggers the behavior?

As for using the command, you can try calling _plugin_waituntilpaused()
after DbgCmdExec. This will not work in a debug callback though (it will
deadlock in that case).

**Comment by 0ffffffffh** [comment]
I created a sample plugin which is generated bug that we discussed. I experienced same problems with fresh plugin. Here is my sample plugin repo

https://github.com/0ffffffffh/x64dbg_bug_maker_plugin

**Comment by mrexodia** [comment]
@0ffffffffh could you check if this issue has been resolved?

**Comment by 0ffffffffh** [comment]
@mrexodia sure. I did. and yeah the crash problem does not occurs anymore. keep works without crash. so yes, the issue has been resolved. 

But you may want to know this little info,

loadlib may still fail on the frequently calls. (I used my previously posted bug maker plugin on this issue thread. It was used loadlib to load some dll frequently and randomly) because of cant set BPX. if loadlib's implementation could not set bpx. it just prints a setbpx failure log line and returns false and keeps going on its workflow without crash. that's not a big or urgent problem for the plugin developers I think.

**Comment by mrexodia** [comment]
Okay this issue has been solved and I opened #1717 for your other problem.
