### ISSUE TITLE
breakpoint hits wrong or myself?

### ISSUE THREAD

**Issue by slavne** [x64dbg/x64dbg#1450]
I have a single breakpoint with:
Break condition: $breakpointcounter==29
.... all empty ......
Hit count: 0

When pressing Run, program stops at breakpoint but I get Hit count=41. Why is hit count not 29? Does the exceptions count (I have ignored exceptions 0-ff...ff in preferences) ? I am using x64dbg v25, Jan 30th.

**Comment by mrexodia** [comment]
Read http://help.x64dbg.com/en/latest/introduction/Input.html 0x29 = 41

**Comment by mrexodia** [comment]
Thanks, I updated the documentation and added this information in a bunch of places as well as in the breakpoint/trace dialog placeholders.
