### ISSUE TITLE
Exceptions are not ignored

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1452]
![gif](https://cloud.githubusercontent.com/assets/16742566/22580053/31de297a-ea10-11e6-8dab-b94ab28b1598.gif)

**Comment by mrexodia** [comment]
You use the option to swallow (not pass to the application) an exception once, it works as expected.

If you want to automatically pass exceptions to the application, use Shift+F9 or add exceptions in the settings dialog. **You cannot swallow consecutive exceptions with an option built-into x64dbg.** The reason for this is that this will not happen in normal application flow. If you want to do this anyway, write a plugin that automatically swallows the exceptions you want.
