### ISSUE TITLE
how to set memory breakpoint at address， not  whole memory page

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1453]
such as:
set memory breakpoint  (one byte)
set memory breakpoint  (two byte)
set memory breakpoint  (four byte)
set memory breakpoint  (eight byte)

**Comment by mrexodia** [comment]
You cannot. Try hardware breakpoints.

**Comment by mrexodia** [comment]
It will however be added once GleeBug is ready, but that might take some time...

**Comment by stonedreamforest** [comment]
You can refer to vs：
![default](https://cloud.githubusercontent.com/assets/16742566/22615397/0fcc8ccc-eacf-11e6-849a-ec99c027dd80.png)

**Comment by gmgunderground** [comment]
Are there news about a range memory breakpoint and not to full page? In the last release I can't put memory breakpoint for one byte for example.

**Comment by torusrxxx** [comment]
Although the feature is completed, there's no timetable to release it
because no one is working on it currently. You might need to wait for
another year or start contributing.

**Comment by vidalv** [comment]
I suggest to use Ollydbg instead !
