### ISSUE TITLE
bug by detach memory windows 

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1454]
fox example:
1. if detach memory window 1, after if use ctrl + g serach address in memory window 1 will  display in memory window 2( current window)  ,it should display mw1

2. if detach memory window 1(or 2 or 3 or others)  and close it , afrer Right-click Any memory window->
 follow qword in dump (should select memory address)-> it display error

**Comment by mrexodia** [comment]
Closed as a duplicate of #1540
