### ISSUE TITLE
Import symbols are not correctly loaded.

### ISSUE THREAD

**Issue by 0ffffffffh** [x64dbg/x64dbg#1455]
Debugger Version: Build Feb 2 2017
Operating System: Windows 10 (NT 10 Build 14393) (Anniversary Update)

Imports are treated as export for some executables. For example, one of these executables is Qemu's executable which is named "qemu-system-x86_64.exe" (QEMU emulator version 2.7.93)

As far I know that the x64dbg enumerates import symbols using the ```IMAGE_IMPORT_DIRECTORY``` data. 

**qemu executable view in symbols tab**
![screenshot_57](https://cloud.githubusercontent.com/assets/437161/22627496/3db7c492-ebd5-11e6-8e77-9d3f965bee94.png)

**Actually it has imports in the Import directory**
![screenshot_59](https://cloud.githubusercontent.com/assets/437161/22627515/650f3e4e-ebd5-11e6-8c6a-5fa2636dd9bd.png)

**Comment by mrexodia** [comment]
That is a pseudo-export for the entry point.

**Comment by mrexodia** [comment]
Ah nevermind, I see the problem with the imports. That's a duplicate of #580

**Comment by 0ffffffffh** [comment]
Thanks. The latest commit solved my all problems. Now it just work fine 

And I must apologize that I cause a confusion about my first post. my bad.
Cuz, I've forgotten to add another scenario screen to explain the ***imports treated as export*** in my post. I was going to show this

![screenshot_60](https://cloud.githubusercontent.com/assets/437161/22630168/b54ea7b6-ec05-11e6-8632-9f68a3626326.png)

The latest commit even solved this problem.
