### ISSUE TITLE
Crash when doing nothing

### ISSUE THREAD

**Issue by Yothri** [x64dbg/x64dbg#1459]
Hi,

i am not good at reversing yet, and I also guess there wont be any help depending my problem here but its a try worth it.

I am trying to debug a game called Guild Wars 2 with x64Dbg (32 Bit) compiled on 30th January 2017.
I am working on Windows 10 Pro x64. 

I know for sure that this game doesnt have any anti debug techniques as well as it doesnt use any anti cheat software. Its not packed, and shipped as a clean executable. I can however debug the game with cheat engine without problems but with x64Dbg the game crashes after some time...

x64Dbg throws an ACCESS_VIOLATION in bottom left corner with yellow background and if i try to continue the process it suddenly crashs. I have no idea why, and I also dont have any idea on how to provide more information.

I already tried those plugins with anti debug techniques but i experience the same problem and like I said this game is clean from anti debug techniques.

![image](https://cloud.githubusercontent.com/assets/5815215/22794370/48c9648c-eef3-11e6-99ce-27786b815320.png)

**Comment by mrexodia** [comment]
A first chance exception can be resumed by pressing run again. Probably the game has an exception handler...

**Comment by Yothri** [comment]
Resuming it instantly gets me to the next exception and finally after some of them it results the game to crash which doesnt happen if its not being debugged with x64dbg. (Also doesnt happen when debugging with cheat engine though).

**Comment by blaquee** [comment]
1. Are you using any plugins? Which ones.
2.When it crashes inside the debugger, can you see what the Call Stack looks like? (Call Stack Tab) Show us
3. Check the Logs window as well for possible more information
4. Any AV software running? Or any program that could be injecting code into the process.

Unfortunately I dont have the game so there is little I can do with the information provided.

**Comment by Yothri** [comment]
1. I am using only SwissArmyKnife Plugin mainly for finding addresses or functions with signatures.
2. 
![image](https://cloud.githubusercontent.com/assets/5815215/22796113/716fe194-eef9-11e6-8398-6a7c53626140.png) Stack, seems pretty empty tho. LOL
3. ![image](https://cloud.githubusercontent.com/assets/5815215/22796088/5c69d688-eef9-11e6-81a3-2b43fcf1fa85.png) Logs window.
4. I am not using any AV software, except microsofts windows defender. I noticed yesterday that when Team Viewer is running, it injects in any process a dll, but i made sure for now that this doesnt happen. So no, basically there should not be another process injecting any code into the games process.

Game is free to play xD
What i can do tho is, what i just noticed is, to install game on my laptop and try if it happens there too.

**Comment by mrexodia** [comment]
Your log only shows one exception.

**Comment by Yothri** [comment]
I can press so many times on continue and the log gets bigger:

> Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 013160D0 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 74D849AA (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Erste Ausnahme[First chance exception] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception [Ausnahme] bei 012D3710 (C0000005, EXCEPTION_ACCESS_VIOLATION)!

**Comment by skillax** [comment]
There's a mention of 'Thread created' in your log (TLS callback ?); it's likely the app is actually changing memory-page access-rights. Goto the 012D3710 address in Disassembly and check what memory address it's trying to access; if it's not 00000000 but a real address, look it up in the Memory Map tab and check it's access rights; it's probably missing R and/or X; try adding those permissions and then resume ...

**Comment by mrexodia** [comment]
Closed because no further comments/information were given.
