### ISSUE TITLE
breakkpoint error： STATUS_WX86_BREAKPOINT

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1462]
Process stopped with exit code 0x4000001F

**Comment by mrexodia** [comment]
This is not enough information. Please read the issue template.

**Comment by stonedreamforest** [comment]
i already know the reason   not x64dbg problem  
i will write a plugin or join the ScyllaHide project  to fix it
but i code style and code level  and english is not good   
so It is more likely to write a new plugin...

**Comment by mrexodia** [comment]
If you make your plugin open source maybe someone will copy it in
scyllahide. Just post the code here.

**Comment by stonedreamforest** [comment]
There is code  from [pediy](http://bbs.pediy.com/thread-215797.htm)

read start：
![1](https://cloud.githubusercontent.com/assets/16742566/23147061/13020a3e-f817-11e6-9758-7f7154d1ebc6.png)

**x64dbg should create Own debugging port** 

**If it can，  the best  make it random**

**Comment by torusrxxx** [comment]
He is trying to debug a game with a DRM solution in Ring 0. A driver dedicated to circumvent the DRM is a better solution.

**Comment by stonedreamforest** [comment]
Source code ： https://github.com/stonedreamforest/NaiHeQiao

**Comment by mrexodia** [comment]
Thanks! I close both issues because they are caused by ring0 so we cannot do much about them.
