### ISSUE TITLE
Broken patch export for languages other than English

### ISSUE THREAD

**Issue by GuyXY** [x64dbg/x64dbg#1464]
I'm using x64dbg v25 on Windows 7 Ultimate (64 bit).

When I try to export a patch file and the debugger's language isn't set to English, the patch file will not be created.

**Comment by mrexodia** [comment]
Everything appears to work fine. If your language was German, please refer to #1514. If the issue persists, please post a comment.

**Comment by GuyXY** [comment]
Well yes, it does work now. However I think it's still a bit odd that you have to specifically type the ".1337" ending for it to work for any language other than English.

**Comment by mrexodia** [comment]
Good that you don't have to...
