### ISSUE TITLE
Decompile - Function not passing RET xx to snowman

### ISSUE THREAD

**Issue by Rourke101** [x64dbg/x64dbg#1465]
x32dbg - Feb 5 2017
Windows 7 64bits

Description: When using snowman with a function, the final instructions is not passed to snowman sometimes.

I have a code like this:
PUSH ESI
....
POP ESI
RET 20

If I select the instructions manually and use Decompile - Selection, it works well.
However, now I use Analysis - Analyze single function. x64dbg marks the whole function correctly. Then I use Decompile - Function and the last instruction RET 20 is not sent to snowman. This has an impact because snowman acts differently without that instruction. I have tried with other functions and the problem replicates (I think once I even got the INT3 after a RET 1C)

I also think the problem is that the analysis function is not accounting the parameter of RET. I suspect this is the case because when I try to fold one function with RET 20, it doesn't work - meaning that I see an animation of folding and then unfolding all in milliseconds. And when I fold a function with RET 1C, it folds and I get as the following instruction:
XXXXXXX | 1C 00                   | SBB     AL, 0                        |
XXXXXXX | CC                       | INT3                                    |
...
So clear indicator.

--------------------
How to replicate:
--------------------
1. Select 1st instruction of a procedure.
2. Right click - Analysis - Analyze single function.
3. Right click - Decompile - Function
4. In snowman tab check instructions on the left

**Comment by Rourke101** [comment]
I have installed version 13 Feb. If this version includes the patch, the error is still present. I have uploaded a video (sorry for the quality) showing the issue: https://mega.nz/#!gBYAiK5Q!PGml-07lXdLsTCcPhfORchAiVeBIDHfWfFBW0i0Hws8 The function boundaries are correctly analysed by x64dbg, then when passing the function to snowman the RET instruction is not sent. Also, if clicking on the + sign, the function attempts to fold but unfolds immediately.

**Comment by mrexodia** [comment]
I tried exactly the same thing and it worked fine. As for the folding, you
cannot fold a range that has EIP/RIP in it.

**Comment by Rourke101** [comment]
Sorry, I deleted my comment almost as I posted it, when I realised I was using v 13th February, which does not include the change. I will check it again with the new version

**Comment by Rourke101** [comment]
It works, bug fixed! gj
