### ISSUE TITLE
Older release is invalid (snapshot_2017-02-05_20-52.zip)

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#1466]
https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2017-02-05_20-52.zip

Clicking on it shows:

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>releases/33791743/218a1bf2-ebe5-11e6-8ba7-104be7b75fa0.zip</Key><RequestId>6451FB115016DA52</RequestId><HostId>wBnIbyAHNiTu4aSQRi3I1bi673b+Mv+ApP9LPKaF5BfLRJ18qBGaQJ+nxJuAYYM5aLJG63GPcf0=</HostId></Error>`

Probably just needs to be deleted

**Comment by mrexodia** [comment]
Should be fixed now, thanks!
