### ISSUE TITLE
flag description translation issue

### ISSUE THREAD

**Issue by mireado** [x64dbg/x64dbg#1467]
Register AF, OF, SF, DF, CF, FS etc...
Doesn't translated on release version like screenshot.
![180](https://cloud.githubusercontent.com/assets/4026514/23093513/3d829bc4-f629-11e6-86f5-8addf8db117e.png)

Could I get Translated with release version?

**Comment by mrexodia** [comment]
The strings are marked as translatable in the source already. Translate them yourself at http://translate.x64dhg.com

**Comment by mireado** [comment]
? already translated but release version have not translated at all

as you know korean translation rate is 100%

**Comment by mireado** [comment]
reopen plz...

**Comment by mrexodia** [comment]
Translations can take some time to propagate in the release packages. Just be patient.

**Comment by mireado** [comment]
OK. thank you for answer.

**Comment by mrexodia** [comment]
Hm I tested again and there appears to be something weird going on here. Probably it has to do with the strings spanning multiple lines or something.
