### ISSUE TITLE
bug: "savedata C:\write1 400000 200" - "Not Enough Arguments! At Least 3 arguments must be specified"

### ISSUE THREAD

**Issue by Eterna1** [x64dbg/x64dbg#1469]
### description
after typing command: `savedata C:\write1 400000 200`
it shows a message: `Not Enough Arguments! At Least 3 arguments must be specified`.
The file `C:\write1` is not created. 
doc for this command is here http://x64dbg.readthedocs.io/en/latest/commands/memory-operations/savedata.html
the same happens for command : `savedata :memdump: 400000 200`
### x64dbg version
Feb 13 2017, 32bit
### my OS
Windows 7 Ultimate, SP1, 64bit

**Comment by mrexodia** [comment]
Try reading http://help.x64dbg.com and http://faq.x64dbg.com

**Comment by brandonros** [comment]
This really doesn't close the issue. Can you give a more helpful example on how to actually call `savedata` since what most people assume isn't what is expected?

**Comment by brandonros** [comment]
For anybody else, it is

`savedata "C:\Users\Brandon\Desktop\hash-input.bin", 0385D020, 00800000`

**Comment by mrexodia** [comment]
http://help.x64dbg.com/en/latest/introduction/Input.html#commands

> Commands have the following format:
> `command arg1, arg2, argN`

http://faq.x64dbg.com

> Q: How do the commands mentioned in the help work?
> A: Basically the commands work like assembler (with **comma separated** arguments). mov eax, 0x1234 is a valid command. You can enter them in the command bar (not in the command line of x64dbg):
