### ISSUE TITLE
Breakpoints doesn't work after export-import database

### ISSUE THREAD

**Issue by Mefist0** [x64dbg/x64dbg#1479]
Hello!

I encountered an error when I debug any program and put breakpoints, save database(File -> Export database). After that I close x64dbg, open it again, load my program to debug(without any changes/compiling/etc) and Import database, I see my breakpoints(Breakpoints tab) I putted earlier, but when I hit F9 the program starts and doesn't stop on the breakpoints.

To solve this problem after database importing I do disable-enable breakpoints on Breakpoints tab.

**Comment by mrexodia** [comment]
related to #1310
