### ISSUE TITLE
How to load and analysis of a binary file

### ISSUE THREAD

**Issue by wonderzdh** [x64dbg/x64dbg#1482]
hi all:
Ollydbg can load any binary file, including the we dump memory.We can analysis its static disassembly, combining some of the features of the debugger itself, this is very useful.My English is poor, please forgive me.

**Comment by mrexodia** [comment]
You cannot. The debugger will only load files that start with CreateProcess. You could write a plugin that uses MapViewOfFile and WriteProcessMemory to insert another binary in memory and analyze it, but x64dbg is not a tool for static analysis.

If you want to load binary data in memory, you can try https://github.com/mrexodia/PasteFile
