### ISSUE TITLE
Improve graph layout

### ISSUE THREAD

**Issue by karliss** [x64dbg/x64dbg#1484]
Current graph layout code leaves room for improvements.

- [x] Fix toposort
-  ~~center code following  `if {} else {}` block~~
- [x] prevent node from being moved sideways due to sibling's children
- ~~reduce edge stretching due to widest element in column~~

Work in progress can be found in [this](/karliss/x64dbg/tree/graph-improvements) branch .

Current code on the left, with sorting improvements on the right side.
![status](https://cloud.githubusercontent.com/assets/7101031/23647670/9eaf470a-031f-11e7-954b-a669471f3943.png)

**Comment by mrexodia** [comment]
That looks like a very good improvement already! Is the algorithm implemented from the binary ninja prototype called 'topsort'?

**Comment by karliss** [comment]
That was a typo, I meant toposort (topological sorting). Topological sorting is only small portion of the layout code.

**Comment by karliss** [comment]
![layouttype](https://cloud.githubusercontent.com/assets/7101031/23775356/ff058764-0530-11e7-93b5-8cee6b0406d4.png)

Added some more compact layout options in a504b8733f2e021d7205d57e24b55f36723eca1d. The compact versions can sometimes be cluttered and difficult to read so it makes sense to allow switching between them. No GUI implemented yet.  For simple functions difference can be small, but in some cases like picture above it can make it much more compact.
