### ISSUE TITLE
Conditional breakpoint equal to string always breaks

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1485]
I am trying to break on an instruction when the register "EAX" is equal to a certain string. Whatever I do, however, the breakpoint is always hit, despite the value of EAX. Here's what I tried:

[EAX] == "Test"
UNICODE [EAX] == "Test"   (Ollydbg syntax)

and all variations of these. What am I missing?

Thank you!

**Comment by mrexodia** [comment]
There is no support for comparing strings in the conditions at the moment (string support in expression function is planned eventually though). In the meantime take a look at this plugin: https://github.com/pastaCLS/cndsteroids

**Comment by ViRb3** [comment]
Should I also assume that Watchdog and Tracing don't support strings?

Thanks for the reference! :)

**Comment by mrexodia** [comment]
Tracing is a conditional expression so no that doesn't support strings. I
don't know about the watchdog to be honest. The AddWatch command has
support for strings (
http://help.x64dbg.com/en/latest/commands/watch-control/AddWatch.html) but
I don't think watch supports being equal to a certain value. See
http://help.x64dbg.com/en/latest/commands/watch-control/SetWatchdog.html for
the supported modes.

**Comment by kempy007** [comment]
I was hoping to do something with strings too, but only if it begins with X value, and then fire off a command/script to post the value somewhere else. eg CTF server lol.

**Comment by mrexodia** [comment]
@kempy007 You can check out https://github.com/pastaCLS/cndsteroids, this can help you set conditional breakpoints. With [plugins](https://github.com/x64dbg/PluginTemplate) you can execute your own code.
