### ISSUE TITLE
instruction info box hard to restore once collapsed

### ISSUE THREAD

**Issue by Cauterite** [x64dbg/x64dbg#1486]
version: 2017-02-28
Windows 7 x64 SP1

I am of course talking about this box under the disassembly: [http://i.imgur.com/LxkOAUO.png]( http://i.imgur.com/LxkOAUO.png )
When you drag the top border down it collapses into 0 height (like [this]( http://i.imgur.com/nD66V3f.png ) ), which is okay except that it's very hard to open it again — there's a 1px line you have to aim for.

A minor gripe, but it took me some time to work out how to re-open the box.

**Comment by mrexodia** [comment]
Yes I agree that it's hard to open again. Do you have a proposal on how to ease this? It used to be that you couldn't collapse anything, but people asked for that to change so I don't quite know how to handle this...

**Comment by Cauterite** [comment]
just make the line you need to grip to drag it open a lot thicker ?

**Comment by mrexodia** [comment]
Okay should be fixed. It now works like this:

![normal](https://i.imgur.com/92BgpTm.png)

![collapsed](https://i.imgur.com/y0n1y3f.png)

**Comment by cxj98** [comment]
man, good work.
