### ISSUE TITLE
bug: stack window

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1488]
if i attach .exe not set any breakpoints 

at this time i want  ctrl + g find stack pointer   it's not success

**Comment by mrexodia** [comment]
what version are you using? This should have been addressed quite recently in https://github.com/x64dbg/x64dbg/issues/1475

**Comment by stonedreamforest** [comment]
![qq 20170311001120](https://cloud.githubusercontent.com/assets/16742566/23802750/39fffec6-05ef-11e7-9f3e-3373d157cb03.png)

**Comment by stonedreamforest** [comment]
Memory window can find it

**Comment by mrexodia** [comment]
Do you have any special settings?

**Comment by stonedreamforest** [comment]
![2017-03-11_12-05-48](https://cloud.githubusercontent.com/assets/16742566/23820445/74007024-0653-11e7-9322-7edd1d2cfb40.gif)

**Comment by mrexodia** [comment]
Okay should be fixed. You cannot access the stack because the value is out
of range...

**Comment by stonedreamforest** [comment]
no no   this is example ; 
I writing a plugin use it anti-anti-debug   the [issue：](https://github.com/x64dbg/x64dbg/issues/1462)

plugin [link：](https://github.com/stonedreamforest/NaiHeQiao)

Wait a moment  i Record a video now

**Comment by stonedreamforest** [comment]
[video ](https://github.com/stonedreamforest/misc/releases/tag/issues%2F1488%EF%BC%9Avideo)
password ：123
