### ISSUE TITLE
Run the favourite script as the user clicks on the favourite menu item.

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1491]
Currently it will only load the script instead of run it. This is of limited usability. Adding an option to run the script is very useful.
But since script loading is asynchronized, it is not possible to try to run the script immediately after script loading function is called or x64dbg will crash at simplescript.cpp:389 where I recommend a try and catch clause for std::out_of_range exception.

**Comment by mrexodia** [comment]
Can't we just add a parameter to `DbgScriptLoad` that specified if the script should be executed as soon as it's loaded?

**Comment by mrexodia** [comment]
I made `DbgScriptLoad` synchronous but I'm not sure if running the script immediately is what you want...

**Comment by torusrxxx** [comment]
I mean, we can add an option to run the script when the script is loaded
from the favourite menu or script tab, but plugins should be able to
control their behaviour without affecting the user setting.

**Comment by mrexodia** [comment]
Okay, the DbgScriptLoad function now only returns if the script is loaded so the issue should be fixed.
