### ISSUE TITLE
DLL loader not being deleted after closing the debugee

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1496]
In the latest snapshot, the DLL loader is not being deleted after terminating the debugee.

**Comment by mrexodia** [comment]
I think this was also mentioned in #1495

**Comment by wk-952** [comment]
Oh, sorry for this duplicate, didn't read the mentioned issue before opening this one.

**Comment by mrexodia** [comment]
No worries, that issue was not a duplicate it just also mentioned this.
Regardless the issue should be fixed now...
