### ISSUE TITLE
how to edit return value of function

### ISSUE THREAD

**Issue by lukeon90** [x64dbg/x64dbg#1497]
Hello,

I get a function called  
public: virtual bool __thiscall TWinApp::IsLicense(void)

how i can change or edit the function that it returns TRUE always ?

any ideas?

im using the newsest version of x64dbg  (Mar 14 2017)
thx

luke

**Comment by mudlord** [comment]
Be mindful of call conventions when you edit the function. I can't remember what call convention Borland C++ uses, which seems to be used in your case. I think its something to do with EAX. What if you do it wrong though and miss a spot?
