### ISSUE TITLE
Run the debugged programs with arguments

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#151]
It would be nice, if we could pass arguments to the debugged program.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/151
- Originally reported by: Anonymous
- Originally created at: 2014-08-07T21:45:12.550

**Comment by Nukem9** [comment]
We can. see http://x64dbg.com/help/index.htm for more information. In the future there might be an option to change the command line when you are already inside the application, but I have to figure out how that would work.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Z-Rantom** [comment]
Is there a way to make it easier to pass an arg like in Olly: File ==> Open ==> Argument ?
