### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1510]
![2017-03-28_22-42-11](https://cloud.githubusercontent.com/assets/16742566/24411263/0a329d26-1408-11e7-9f0a-4376d22904ee.gif)

**Comment by mrexodia** [comment]
This doesn't look like a bug. You copy the disassembly with hex constants without prefix (see issue #614) and then paste it in an assembler that takes decimal input. If you want to assemble with hexadecimal as default you should use XEDParse instead.
