### ISSUE TITLE
Patchfile Im- and Export does not work in German Translation

### ISSUE THREAD

**Issue by just4fun78** [x64dbg/x64dbg#1514]
In the german translation it's not possible to export an patchfile. The exportfunction has no effect and no file will be written.

And the importfunction does not work, because there is an error in the filetypeselector, in selectiontab visible '*. 1337' and not '*.1337', and so no '1337' files are visible in the fileselect window.

In uk translation both things work as expected, so i think there are some errors in the german translation file.

Would be nice if that is corrected.

**Comment by mrexodia** [comment]
Should be fix soon, thanks for the report!

**Comment by just4fun78** [comment]
For german translation the patch import and export now works fine. I have solved the issue. There was an byte error (two bytes too much, in 1337 declaration) in translationfile.
