### ISSUE TITLE
The export graph as image function in jpg format does not work.

### ISSUE THREAD

**Issue by just4fun78** [x64dbg/x64dbg#1515]
It's not possible to export an graph as image in jpg format. Function does not work, no file will be written.

When trying it, the screen shrugs and no file will be written.

The PNG graph export works as expected.

Would be nice if that is corrected

**Comment by mrexodia** [comment]
Just tested and everything works fine (refrain from using this format though, it's really lossy and you cannot see anything).

![test](https://cloud.githubusercontent.com/assets/2458265/24583665/e77a5696-1751-11e7-9d74-b0cd4b82dabc.jpg)

**Comment by just4fun78** [comment]
Sorry, it didn't work for me. I have 2 systems, latest xdbg build, and on my booth systems the export graph as image, in jpg format does not work and write no file to destinationfolder, when i try. PNG export works. But when change the format to jpg no file will be written.

![01_win](https://cloud.githubusercontent.com/assets/26845898/24586868/387a3904-17ab-11e7-8dde-1a83fe932c69.jpg)
![02_graph](https://cloud.githubusercontent.com/assets/26845898/24586871/3d18b206-17ab-11e7-9615-a4013480bac6.jpg)
![03_testpng](https://cloud.githubusercontent.com/assets/26845898/24586874/40e8b566-17ab-11e7-899e-49a126496f13.jpg)
![04_testjpg](https://cloud.githubusercontent.com/assets/26845898/24586878/46ff919a-17ab-11e7-8f9c-29b53424bcff.jpg)
![05_result](https://cloud.githubusercontent.com/assets/26845898/24586880/49fd41a8-17ab-11e7-97d0-b89697d672bb.jpg)

On my second system Windows 7 x64 SP1 with latest xdbg build, the issue is exactly the same, and no file will be written when i try to export the graph in jpg format.
