### ISSUE TITLE
Wrong disassembly of `rep movs` family instructions

### ISSUE THREAD

**Issue by lhmouse** [x64dbg/x64dbg#1520]
The problem is shown in the picture (line 1 and 3 are wrong while line 2 and 4 are right):

![rep movs](https://cloud.githubusercontent.com/assets/5071344/24620428/41943ee2-18d0-11e7-922f-f66f09df6484.png)

The machine code `F3 A5` is `rep movsd`. However, an additional prefix `48` (modifies the instruction to `movsq`) or `66` (modifies the instruction to `movsw`) can be placed either **in front of** it or **in the middle of** it. x64dbg disassembles the former correctly, but not the latter.

**Comment by mrexodia** [comment]
This is probably a capstone issue. See [here](https://github.com/aquynh/capstone/blob/master/suite/regress.py#L43) for the regressions. Please check if your samples are already there and if not, open an issue/pull request.

**Comment by lhmouse** [comment]
Oh it has been fixed today. :clinking_glasses:
