### ISSUE TITLE
Calling convention (EBP base) is not correct.

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1524]
When a routine begins with "push ebp;mov ebp,esp", EBP will point to the stored value of previous EBP. The first argument in stack is pointed to by [EBP+8], instead of [EBP+4] currently. [EBP+4] is the return address.

**Comment by mrexodia** [comment]
Shouldn't be too difficult to fix. Probably this has to be slightly changed: https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/CPUArgumentWidget.cpp#L209

**Comment by mrexodia** [comment]
This was fixed by #1526 right?
