### ISSUE TITLE
Wrapping Data Copy

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#1527]
Data Copy when handling huge arrays of bytes doest work well
with for example Delphi, yes i know its old.
So wrapping it would solve some copying issues 👍

**Comment by mrexodia** [comment]
Could you provide a template for Delphi?

**Comment by Chandlr** [comment]
Array [0..7175] of Byte = (
$90, $90, $90, $90, $26, $4E, $90, $90, $40, $40, $56, $90, $75, $25, $71, $90, $71, $90, $9D, $90, $9D, $13, $A1, $90, $A1, $3A, $C7, $90, $C7, $1E, $C2, $90, $C2, $2A, $DD, $90, $DD, $1C, $F5, $90, $F5, $0E, $F3, $90, $F3, $2B, $0B, $90, $0B, $0B, $41, $90, $41, $02, $33, $90, $33, $90, $44, $90, $44, $22, $3A, $90, $3A, $12, $5B, $90, $5B, $07, $5C, $90, $5C, $02, $EA, $90, $EA, $90, $F5, $90, $F5, $90, $90, $90, 
$90, $90, $91, $90, $91, $08, $C0, $90, $C0, $06, $32, $90, $32, $24, $40, $90, $40, $0A, $54, $90, $54, $03, $53, $90, $53, $0F, $55, $90, $55, $10, $6E, $90, $6E, $51, $72, $90, $72, $2A, $60, $90, $60, $29, $6B, $90, $6B, $0D, $B9, $90, $B9, $04, $CA, $90, $CA, $01, $99, $90, $99, $90, $E1, $90, $E1, $90, $F5, $90, $F5, $90, $41, $90, $41, $90, $F8, $90, $F8, $90, $83, $90, $83, $90, $87, $90, $87, $90, $55, $90, 
$55, $90, $5B, $90, $5B, $01, $BB, $90, $BB, $02, $B7, $90, $B7, $06, $88, $90, $88, $04, $8F, $90, $8F, $13, $5B, $90, $5B, $1A, $97, $90, $97, $0C, $6C, $90, $6C, $04, $73, $90, $73, $12, $7C, $90, $7C, $04, $78, $90, $78, $01, $79, $90, $79, $90, $85, $90, $85, $90, $93, $90, $93, $90, $93, $90, $93, $0C, $B0, $90, $B0, $18, $F4, $90, $F4, $0F, $9F, $90, $9F, $07, $C8, $90, $C8, $35, $D4, $90, $D4, $0D, $99, $90,
i cut just a few but you get the width length here :)

**Comment by mrexodia** [comment]
So what are the limits exactly? 210 characters per line or 42 bytes per line?

**Comment by Chandlr** [comment]
Seems to be 998 chars ( , $ included)

**Comment by mrexodia** [comment]
and what is the preferred amount of bytes per line?

**Comment by Chandlr** [comment]
42 bytes per line would be sexy :)
