### ISSUE TITLE
support disassembly history in graph

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1528]
Support +/- in the graph.

**Comment by torusrxxx** [comment]
already supported

**Comment by RaMMicHaeL** [comment]
@torusrxxx thanks! Please [claim your bounty](https://www.bountysource.com/issues/43951381-support-disassembly-history-in-graph) :)

**Comment by RaMMicHaeL** [comment]
@torusrxxx actually, there's one little thing that's missing: if you follow a jump or a call, and click on '-', you don't go back to the jump or the call (as in the regular CPU view), but to a previous, unrelevant command in the graph. I can create a video if my description is not clear.
