### ISSUE TITLE
Need features like Ollydbg in symbols view

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1530]
I know symbols view in x64dbg which is similar to Executable Modules(shortcut:Alt+E) in ollydbg, but lack these features which I think is very useful:
1. show full path of modules. I usually using sorting of path to care about those dlls in the same directory as the exe file.
2. the right side table in symbols view is similar to CTRL+N in ollydbg, but when press 'ENTER', x64dbg turn to disassembler window and show the address of the symbol address. But in ollydbg, it's working like CTRL+R which is also implemented in x64dbg. --OH, i just found bug about this, 'ENTER' only work when symbol's type is 'export', when 'import' it's just turn to disassembler window but address is not changed. But the rigth-mouse click menu 'Follow in Disassembler ' is working correctly. 

Further more, the 'ENTER' in CTRL+N in ollydbg do more work, it's not just CTRL+R, if symbol is:
 Address=0045D3A0 Type=Import  (Known) Name=msvcrt.fputc
and it's used like this:(maybe another bug: CTRL+R to 0045D3A0 in x64dbg can't found the below line)
00431600   $-FF25 A0D34500  JMP DWORD PTR DS:[<&msvcrt.fputc>]       ;  msvcrt.putc
then it will also search 00431600

**Comment by mrexodia** [comment]
All the 'bugs' you found are not bugs but expected behavior. For the imports I changed the behavior to make sense more, for the references it will only find references in the current disasm section. If you want to find references to an import address in a specific section, follow import in dump (this will go to the IAT address), follow the section in disasm and then use Ctrl+R from the dump.

Alternatively, copy the IAT address (from symbols), right click in cpu -> search for -> all modules -> constant -> enter address -> it will find all references in all modules.

**Comment by lynnux** [comment]
@mrexodia thank you very much! 
I finally know how x64dbg work if press 'ENTER' in import table, it just only dump in memory view but not change the address in disassembler view. 
And CTRL+R only search  for the current region in disassembler view, that cause I thaught is a bug is because I goto IAT address  in disassembler view and then press CTRL+R,  of course it can not get any result because the address is in '.idata' section which only have import table data.
So, very sorry for the misunderstanding!
Could you rollback the change for 'ENTER' press action in import table, because after compiled the latest code, when press 'ENTER' will cause disassembler view turn to the import address. Previously, if I want the 'ENTER' action in CTRL+N like ollydbg, I can just press ENTER in x64dbg, then CTRL+R, bug now need more step.

two little more suggestion:
1. the tittle in References like 'Constant:004546477 (Region global.exe)'  can have more detail, we can take the section name from memory map, for example:'Constant:004546477 in global.exe(.text)', or 'Constant:004546477 in global.exe(.idata)'
2. the focused window in CPU view can have more thicker border like in ollydbg, if possible, can have a config color for border. If I press 'ENTER' in import table, I can know which window I focused in.

**Comment by mrexodia** [comment]
Currently you can do the same by right clicking on the import and selecting
the "follow in dump" option. I will use it for a while and see the best
usage... I can also add a menu to scan for usages in all modules directly.

The border cannot be bigger because of something weird in qt. If you find
something that works with the user style.css tell me.

**Comment by mrexodia** [comment]
Also this improvement to the reference title is a good idea, maybe you can
try to add it and send a pull request?

**Comment by mrexodia** [comment]
I made a poll here http://www.strawpoll.me/12729588

**Comment by lynnux** [comment]
I figure out how CTRL+R works in ollydbg
There are two kind of address:
1. address belong to a section, whose type is IMG, it's in a module
2. address belong to a section, whose type is PRV or MAP, it's in a heap or map.

if press CTRL+R on the 1st address, ollydbg will only search in region of module '.text', which it's think is the code region, no matter where located in disassembler view
if press CTRL+R on the 2nd address, it will search in the region showed in disassembler view

I think this is reasonable, I feel comfortable about this, and never thought how it implemented until this post. I think, normally, there may not have many references cross modules on a address. A address usually only mean something to the module which it's belong to.

However, on 1st address, ollydbg seem only search the first '.text' section, I don't know if there would have more section like '.text', an easy decision is to search all section belong to the same module.

**Comment by mrexodia** [comment]
This behavior is almost never what I want, but olly has an option for this
in options. X64dbg has different search modes explicitly.

I won't change the default ctrl+r behavior. You can use different search
options if you want different behavior.
