### ISSUE TITLE
data copy formatting

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1534]
![2017-04-12_19-11-22](https://cloud.githubusercontent.com/assets/16742566/24955024/544a87c2-1fb4-11e7-845e-201bdde62915.gif)

The best way：

![qq 20170412191741](https://cloud.githubusercontent.com/assets/16742566/24955150/d82e1f22-1fb4-11e7-9322-b126f9a07e9d.png)

**Comment by mrexodia** [comment]
well I don't think indentation should be added here by default, perhaps a checkbox?

**Comment by Chandlr** [comment]
and update x64dbg to 12 april 👍

**Comment by mrexodia** [comment]
I only added this for Delphi @Chandlr

**Comment by stonedreamforest** [comment]
x32：
byte 、word、dword：**row  * 8**


x64：
byte 、word、dword：**row  * 8**

qword： **row * 4**

**Comment by shadoww0** [comment]
where did you get this dark theme?

**Comment by stonedreamforest** [comment]
@shadoww0  [theme ](https://github.com/stonedreamforest/x64dbg_theme_RelaxYourEyes)

**Comment by Chandlr** [comment]
It looks very similar to "Dark Theme" 
https://github.com/x64dbg/x64dbg/wiki/Color-Schemes
a cool idea would be a combobox with diffrent themes .. too much work ? :x

**Comment by mrexodia** [comment]
@Chandlr the problem is that if I add the themes directly to x64dbg that I have to maintain them for new features...

**Comment by Chandlr** [comment]
@mrexodia No just allow others to add a .ini with the theme color and the combobox would see the .ini if thats possible.. cant think of how myself :x

**Comment by stonedreamforest** [comment]
this feature isn't available right now?

**Comment by mrexodia** [comment]
Ah, probably the refactor from @torusrxxx removed this functionality...

**Comment by torusrxxx** [comment]
in Binary Edit dialog
