### ISSUE TITLE
Configure Shortcuts for eg "Search for->Current Module->Pattern"

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#1539]
As title says to be able to configure shortcuts for Current module pattern search

**Comment by balintf** [comment]
I've added PR #1790 to implement this, but I'm not entirely sure if we should also add default values for them, or if they should be just empty.
The defaults Search for->Current Region->Command and Pattern are Ctrl+F, and Ctrl+B. For searching in the Current Module I've added Ctrl+Shift+F and Ctrl+Shift+B, but in most IDEs Ctrl+Shift+F is find in files, which in x64dbg might correspond to either find in current module or find in all modules.
