### ISSUE TITLE
Cosmetic Gui Bug. With following Ptr in Dump in another Dump window

### ISSUE THREAD

**Issue by BellCrow** [x64dbg/x64dbg#1540]
Cosmetic Error: If you detach a Dump window and then try to follow a pointer in an unattached window, you can choose the watchdog as a traget for the following, but not the detached window(s).

![bug](https://cloud.githubusercontent.com/assets/5954939/25074790/f9914952-2304-11e7-851a-4b86006a690b.jpg)

**Comment by BellCrow** [comment]
Note: Follow menu stays corrupted, even if you reattach the dump windows
![bug](https://cloud.githubusercontent.com/assets/5954939/25074849/d983e84e-2305-11e7-9fb2-3ec5454cb81d.jpg)

**Comment by mrexodia** [comment]
I kinda forgot why but I know this was disabled on purpose. I think it was
related to the fact that signals get disconnected if you detach.

**Comment by BellCrow** [comment]
I see. thanks for the fast response

**Comment by mrexodia** [comment]
This has been fixed somewhere.
