### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1541]
1. Find command(shortcut CTRL+F) seems only search the range below the selected line, could there have a  'Entire Block'  option?
2. in ollydbg, there have two shortcut ALT+F7, ALT+F8(in disassembly window) relate to reference result, AlT+F7 go to previous reference, Alt+F8 go to next reference. In x64dbg, there could have several references, it can be implemented just for current focused references.  And even better if it support fitlered view of references.
3. Find command also lack a shortcut CTRL+L, which goto next search.

**Comment by mrexodia** [comment]
1. Yes this was commented out by accident I believe. I restored this functionality for `Search for -> Current Region -> Find command`
2. This feature has now been added, it will only work on the 'current' reference view (the last one created) and the hotkeys are Ctrl+K (previous) and Ctrl+L (next).
3. The find command will find all occurrences and show them in the reference view so you can use the new feature from 3 to do this now.

**Comment by lynnux** [comment]
@mrexodia, really appreciate your work! I found a code bug relate to the shortcut, please have a check ^_^
