### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AbedKarmi** [x64dbg/x64dbg#1544]
X32DBG APR 14 2017
Windows 10 x64 1703

When loading any executable the debugger paused on EXCEPTION_ACCESS_VIOLATION!. When remove plugin SCYLLAHIDE v1.2, it loads with no problem. This issue was not in the earlier windows 10 x64 build 1607

**Comment by mrexodia** [comment]
Then it's an issue with the plugin not with x64dbg. Anyway you should update ScyllaHide to the version from github.com/x64dbg/ScyllaHide perhaps that works.

**Comment by CrcakOnDemand** [comment]
to solve the problem
untick NTQueryInformationprocess in scyllahide settings

**Comment by marqueswhite** [comment]
please take me off of this thread ad campaign.  I don't know how I got on it

*Mark White*
*Sales & Insurance Claims*


*toll free 1.855.255.1349* | *m*obile 303.731.5011 | *f*ax 1.888.799.9981




*Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy. *
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by DragonQuestHero** [comment]
same problem:joy:
