### ISSUE TITLE
Windows XP 64-bit hangs x32dbg

### ISSUE THREAD

**Issue by fenderluvr** [x64dbg/x64dbg#1546]
This is an old CTF (crackme).  I was using x64DBG to try and see if I could get as much info from this debugger as I could IDA Pro (v6.8).  Unfortunately, loading the EXE from within the debugger causes it to hang.  The only thing I can see is at the very bottom of the debugger UI which states, "System breakpoint reached!".  Only option is the force-close the debugger.

https://ctftime.org/task/834

**Comment by fenderluvr** [comment]
This is an old CTF (crackme).  I was using x64DBG to try and see if I could get as much info from this debugger as I could IDA Pro (v6.8).  Unfortunately, loading the EXE from within the debugger causes it to hang.  The only thing I can see is at the very bottom of the debugger UI which states, "System breakpoint reached!".  Only option is the force-close the debugger.

https://ctftime.org/task/834

**Comment by mrfearless** [comment]
I get a SEC_ERROR_EXPIRED_CERTIFICATE when trying to download the sample

**Comment by fenderluvr** [comment]
Try here:

https://mega.nz/#!C45l3YJA!rM5rBaK1-xNOJBoUVBtUvW9SmJJy3gtKcJyQPsHoJEQ

**Comment by mrfearless** [comment]
Press F9 to run from system breakpoint. Of if that doesnt work, uncheck the system breakpoint checkbox in Options->Preferences->Events. Check the Entry breakpoint at least.

Probably worth checking the TLS Callbacks checkbox for this exe as it uses them - as evidenced with viewing it in CFF Explorer and x32dbg will break on the TLS callback as well if this option is checked.

I can get to entry break point ok (if break on system breakpoint isnt checked) and/or the TLS function (if TLS Callbacks is checked)

**Comment by mrexodia** [comment]
@mrfearless so could you reproduce the issue?

**Comment by fenderluvr** [comment]
Just all suggestions, but it doesn't have an positive effect.  If I LOAD the app via the debugger it will hang indefinitely.  At the bottom, I see "initialized" and "loading commandline" - wasted debugging time timer is at 1 second.  Worth noting that the EXE is not hung (I can move the window around) but is not fully loaded (not text is displayed).  No issues with OllyDBG or IDA..

**Comment by fenderluvr** [comment]
Actually, the debugger window isn't hung either; only the UI (locked thread?).  I can force-close using the x in the upper-right corner.  Attaching to the EXE seems to work okay, regardless of BP options enabled/disabled.

**Comment by mrfearless** [comment]
I'm using windows 7 64bit and it didn't appear to be hung and the ui wasn't locked for me.

**Comment by fenderluvr** [comment]
Hmmm...  OK.  Let me try Windows 10 and see what I get.  My current test is on WinXP 64bit (easiest OK for, well, you know).

**Comment by fenderluvr** [comment]
Ok, not able to repro on Windows 10 x64.  Still, it's interesting that there is a hang on Windows XP x64.  Thanks for looking...

**Comment by mrexodia** [comment]
I just tried on Windows 8.1 x64 (Parallels VM), @fenderluvr you experience the issue on XP 64 only?

**Comment by fenderluvr** [comment]
That is correct.

**Comment by mrexodia** [comment]
Just tried this and it happens with any executable you debug on Windows XP 64. It does not hang immediately however, you have to step first. Can you confirm this also happens when doing `init x32dbg.exe` and then stepping @fenderluvr ?

**Comment by fenderluvr** [comment]
All INIT commands tried, same failure (with any EXE - you are right, mrexodia).  Hitting F9 or F7 causes the UI to hang.  Any stepping causes the behavior (shift-F7, for example).

**Comment by mrexodia** [comment]
I believe I have found and fixed the issue (learning for exams is really
boring apparently), I will test some more and push a fix. I'm afraid
however that there will be another issue after this so you might want to
check some older versions of x64dbg to see if those work in the meantime.

**Comment by fenderluvr** [comment]
Ok.  Will this go into tomorrow's daily build?  Can I view the check in?  Just curious.

**Comment by mrexodia** [comment]
It should already be in http://releases.x64dbg.com

**Comment by fenderluvr** [comment]
Ok, cool.  I'll test it.  Is there is a check-in for the fix I can look at?

**Comment by mrexodia** [comment]
I don't know what check-in means. You can see the commit that fixed this in the references (it's 4c1fd6c).

**Comment by fenderluvr** [comment]
Haha, sorry man.  Back in my day (yes, I'm older than you), we would "check out" a section of code, make the needed changes and then "Check it back in".  So your "commit" is the code change that I'm asking about.  -Cheers

**Comment by fenderluvr** [comment]
Ok, it look like you made the lock exclusive.  I have dug into this debugger's code so it's a bit of an assumption based on the code change.  :)

**Comment by mrexodia** [comment]
No, making the lock exclusive was fixing another problem (which would actually never manifest on XP since there is no distinction between shared and exclusive locks there). The thing that actually fixed it was releasing the lock before the `wait` function was called :)

**Comment by fenderluvr** [comment]
Ah, ok.  I will go back and take a closer look.  Thx!

**Comment by fenderluvr** [comment]
Ok, yes, I see it.  I'm going to test in a few...

**Comment by fenderluvr** [comment]
Uhm...  This change AVs all over the place (c0000005) at every step.  This happens using an 32bit exe.  :|

**Comment by fenderluvr** [comment]
So this is very strange.  Using something simple like HxD.exe (hex editor) has no issues.  However, using Roboauth.exe or Produkey.exe (sysinternals) AVs.  The debugger doesn't crash, but weird behavior persists.

**Comment by fenderluvr** [comment]
Going to build a quick win32 app and retest.

**Comment by fenderluvr** [comment]
Alright, well not so simple.  Building a quick Windows app with VC2017 isn't recognized on Windows XP as a valid windows app (of course, I guess - stupid MS).  Anway, I only see this problem on WinXPx64 (where I do my RE stuff), sooo I guess I'll use a different debugger when I run into this issue (losing interest, sry).  Nice work on this debugger though.  I'll keep watching/using.

**Comment by mrexodia** [comment]
After fixing this deadlock I did encounter a different issue probably
related to Windows xp 64 being crappy with wow64. Any newer os works
perfectly fine. To build with vs2017 for xp you have to change to the xp
platform toolset in project properties, but I'll look into this some more
later...

**Comment by mrexodia** [comment]
Also remember that xp is not actually supported. Compatibility is held together with undocumented apis and duct tape and it's never checked so I'd advice updating to at least windows Vista

**Comment by mrexodia** [comment]
In the meantime you could try the new debug engine, for me everything works 'fine' with that: https://ci.appveyor.com/api/buildjobs/fggq40iss5ov0i03/artifacts/bin.zip

**Comment by fenderluvr** [comment]
Yea, XP is old as dirt (but less OS hassles, as I'm sure you know).  Changing the build properties causes more head aches.  Maybe I'll just find an old SDK with EXEs that have less dependencies (ugh).  Anyway, thanks for looking looking at this and I'll check out your link.

**Comment by fenderluvr** [comment]
Indeed, everything does work 'fine' with that - nice.

**Comment by fenderluvr** [comment]
Hmmm...  Well, maybe I was lazy.  I copy over the x32 bin dir into the debugger DIR, thinking this will just updated files.  Yes, so it works - sort of.  The titanengine.dll is very small compared to the DLL that comes with the x64DBG download.  I get past the UI hang, but then any real debugging starts, the debugger crashes.  Maybe I'm doing it wrong.  :(

**Comment by fenderluvr** [comment]
Looks like string search on module was causing the crash.  Happened twice, but seems to be working better now.

**Comment by mrexodia** [comment]
That library is rather experimental but if you find anything a report is
greatly appreciated. I would still not recommend using Windows xp, but
everyone their poison 😃

**Comment by fenderluvr** [comment]
Will do.  :)

**Comment by mrexodia** [comment]
Okay @fenderluvr I have looked into the issue and everything should be working fine in the next snapshot (20 minutes or so).

**Comment by fenderluvr** [comment]
Awesome, thx!!!

I'll update and verify.

**Comment by fenderluvr** [comment]
Looks like your fix works.
