### ISSUE TITLE
exception problem

### ISSUE THREAD

**Issue by mefcdj** [x64dbg/x64dbg#1547]
The specified filter exception, conditional breakpoint or aborts be filtered exception, There is no picture here，if you need me to send pictures to your mailbox, tell me your email

设置了指定过虑异常，条件断点还是会中断被过虑的异常，如果你需要我发图片到你的邮箱，告诉我你的邮件

**Comment by mrexodia** [comment]
Unhandled exception filter is a well known anti debug trick. You can send the pictures to x64dbg@googlegroups.com
