### ISSUE TITLE
sometimes I can't go to the reference's address by double click

### ISSUE THREAD

**Issue by Hypophrenia** [x64dbg/x64dbg#1549]
It's a crackme  which contains some self-modify code 
here it is:
http://reversing.kr/download.php

name is **Twist1**

I've unpacked it and find some valuable string-references
but I found I can't go to the address directly by double click .
well , right-click and choose follow in ..... is okay..

**Comment by mrexodia** [comment]
Hm?

**Comment by Hypophrenia** [comment]
@mrexodia  I'm a fool. it's just follow in dump default.  maybe in that situation x64dbg treated that codes as datas? is I need reanalysis that module? sorry for I puted the stupid issues.

**Comment by mrexodia** [comment]
No problem for the issues. What x64dbg will do is if the memory page of the
address is executable it will follow in disassembler and if it's not
executable it will follow in dump.

**Comment by Hypophrenia** [comment]
@mrexodia  yeah ,I've fixed it 

![capture3](https://cloud.githubusercontent.com/assets/13413791/25170637/deb4e632-251d-11e7-8e35-f9a30915d5fc.PNG)

thanks.

can you introduced some  books or web sites to learned the reverse engineer.?
I just don't know how to continue.

**Comment by gmastergreatee** [comment]
Lots of tutes -> https://tuts4you.com/download.php

**Comment by Hypophrenia** [comment]
@mrexodia  thanks

**Comment by Hypophrenia** [comment]
@gmastergreatee  thanks. ;)
