### ISSUE TITLE
float value editor

### ISSUE THREAD

**Issue by flarejune** [x64dbg/x64dbg#1550]
Can you add a float value (input) editor to Dump View?Thank you

**Comment by gmastergreatee** [comment]
Also for double?

**Comment by flarejune** [comment]
That's even better,float is more commonly used,3D games have more float values

**Comment by mrexodia** [comment]
The format the registers use is long double guys 😃

**Comment by torusrxxx** [comment]
He only wants to modify floating-point values in the memory.

**Comment by mrexodia** [comment]
Ah okay, I'm not sure if we should add that before doing the long double editor.

**Comment by flarejune** [comment]
In the dump view, if the current view mode is a floating point value mode,when double clicking to edit, switch to floating point editor,Is a simple floating point value to the Hex converter,without manual conversion.the best can be like XMM register editor

**Comment by mrexodia** [comment]
Try to implement it @flarejune, you can get started in CPUDump.cpp:370 and add a special case for floating point there...

**Comment by flarejune** [comment]
no problem,most of the floating point values that need to be edited manually are approximate integers

**Comment by torusrxxx** [comment]
Already supported via 1350756ef3816c2a55cb682cc8004e7bde6add53

**Comment by torusrxxx** [comment]
It's better to design a separate floating point calculator. Almost all fields in the integer calculator do not apply to floating point.
