### ISSUE TITLE
how to close moudle name

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1559]
![1](https://cloud.githubusercontent.com/assets/16742566/25259999/017503c8-267c-11e7-8c5c-be4172a265ed.png)

I use it invalid

example:
add ecx,wininet.76E592AA
->
add ecx, 0x76e592aa

**Comment by torusrxxx** [comment]
这个设置只能隐藏当前模块的模块名，因为我当时考虑隐藏所有模块的模块名用处不大。

**Comment by stonedreamforest** [comment]
@torusrxxx  
i want copy Disassembly  and use  nasm Compile it， so  don't need it,

**it is best to support nasm  grammar.**

**Comment by mrexodia** [comment]
There are absolutely no plans to support this kind of stuff. The
disassembly is for reading not for assembling. You can use something like
multimate assembler or write a plugin

**Comment by stonedreamforest** [comment]
multimate assembler  looks good,  If I have spare time , I will try to write a plugin

**Comment by torusrxxx** [comment]
我现在就做一个这种插件

**Comment by torusrxxx** [comment]
现在使用升级了的https://github.com/torusrxxx/x64dbgpatchexporter

**Comment by stonedreamforest** [comment]
I've used it, looks great :+1: ,But,if i using nasm, he still has some small errors,That's good enough for me
