### ISSUE TITLE
Debug symbols don't get loaded

### ISSUE THREAD

**Issue by Timmmm** [x64dbg/x64dbg#1564]
I build a fairly simple C++ program with MSVC 2017 in debug mode. It produces a folder with a `.exe` and `.pdb` file. However if I debug this program with x64dbg (20th April 2017) then it only shows me the disassembly. The Source tab is blank. This is on Windows 10.

Here is the log output:

```
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing capstone...
Initializing Yara...
Getting directory information...
Start file read thread...
Symbol Path: C:\Users\Tim\Documents\Local\x64dbg\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Loading plugins...
Handling command line...
Initialization successful!
Mnemonic help database loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Reading notes file...
File read thread finished!
Debugging: C:\Users\Tim\Google Drive\Programs\UsbIsoTest_Host_MSVC\x64\Debug\UsbIsoTest_Host_MSVC.exe
Database file: C:\Users\Tim\Documents\Local\x64dbg\x64\db\UsbIsoTest_Host_MSVC.exe.dd64
Process Started: 00007FF6794A0000 C:\Users\Tim\Google Drive\Programs\UsbIsoTest_Host_MSVC\x64\Debug\UsbIsoTest_Host_MSVC.exe
Breakpoint at 00007FF6794EE49B set!
DLL Loaded: 00007FF8D4F90000 C:\Windows\System32\ntdll.dll
DLL Loaded: 00007FF8D4EE0000 C:\Windows\System32\kernel32.dll
DLL Loaded: 00007FF8D22B0000 C:\Windows\System32\KernelBase.dll
Thread 788 created, Entry: ntdll.00007FF8D4FC2DC0
DLL Loaded: 00007FF8D47A0000 C:\Windows\System32\setupapi.dll
DLL Loaded: 00007FF8C87C0000 C:\Windows\System32\winusb.dll
DLL Loaded: 00007FF8D26C0000 C:\Windows\System32\msvcrt.dll
DLL Loaded: 00007FF8D24D0000 C:\Windows\System32\cfgmgr32.dll
Thread 1CE8 created, Entry: ntdll.00007FF8D4FC2DC0
DLL Loaded: 00007FF8D2590000 C:\Windows\System32\rpcrt4.dll
Thread 30C created, Entry: ntdll.00007FF8D4FC2DC0
DLL Loaded: 00007FF8C3850000 C:\Windows\System32\vcruntime140d.dll
DLL Loaded: 00007FF89D6E0000 C:\Windows\System32\ucrtbased.dll
DLL Loaded: 00007FF8A7270000 C:\Windows\System32\msvcp140d.dll
System breakpoint reached!
```

The PDB file is at `C:\Users\Tim\Google Drive\Programs\UsbIsoTest_Host_MSVC\x64\Debug\UsbIsoTest_Host_MSVC.pdb`

**Comment by mrexodia** [comment]
You have to manually load the symbol file. Right click on the module in the symbols tab and clikc 'Download symbol;

**Comment by Timmmm** [comment]
I did that and it seemed to find the pdb file:

```
SYMSRV:  C:\Users\Tim\Documents\Local\x64dbg\x64\symbols\UsbIsoTest_Host_MSVC.pdb\123549EFC748407C8572E07EF0E53D2Aa\UsbIsoTest_Host_MSVC.pdb not found
DBGHELP: UsbIsoTest_Host_MSVC - public symbols & lines 
        C:\Users\Tim\Google Drive\Programs\UsbIsoTest_Host_MSVC\x64\Debug\UsbIsoTest_Host_MSVC.pdb
```

But nothing else changed - the source tab is still blank.

**Comment by mrexodia** [comment]
That is the expected behavior. The source tab will only contain something
if you click the "open source file" context menu item from the disassembler.

Word of warning: x64dbg is not made with source level debugging in mind.
There are some options to step in/over source lines but that's about where
it stops.

**Comment by Timmmm** [comment]
Maybe I'm being an idiot but I don't see that option anywhere in the
context menu. You mean on the CPU tab right?

**Comment by mrexodia** [comment]
If the disassembler shows `XXXXX.cpp:341` as a comment and the source file exists verbatim on disk you have this option.

**Comment by Timmmm** [comment]
Ah ok. It doesn't show that anywhere in the comments. I managed to fix my
bug without x64dbg anyway so I'll leave it for now. Seems like a great
program but I guess more designed for reverse engineering where you never
have the source code...

Thanks for the help anyway!

**Comment by stonedreamforest** [comment]
@Timmmm 
![2017-04-24_23-00-36](https://cloud.githubusercontent.com/assets/16742566/25343554/fd6e965e-2941-11e7-9ad9-8d37fa89c871.gif)

**Comment by mrexodia** [comment]
Alright. Notice that you have to reload the symbols manually every time
before it can show line numbers. Perhaps in the future x64dbg will be
improved to work better on a source level, but this is definitely not the
current focus.
