### ISSUE TITLE
scripting

### ISSUE THREAD

**Issue by reverser69** [x64dbg/x64dbg#1568]
hi
i wanna place bp on all intermodular call then run script to remove bp from unwanted ones by this script of obgscript but it cannot be runned in 64dbg

pause 
//////////////////////// 
LOOP: 
bc eip 
run 
jmp LOOP
whats its equivalent in 64dbg?

**Comment by mrexodia** [comment]
what is the problem?

**Comment by ThunderCls** [comment]
@mrexodia I think he wants to translate those odbgscript commands to a x64dbg's script engine equivalent

**Comment by mrexodia** [comment]
It's a valid script from what I can tell.

**Comment by reverser69** [comment]
@mrexodia the debugger shows error on bc eip command.

**Comment by reverser69** [comment]
@ThunderCls exactly

**Comment by mrexodia** [comment]
What exactly is the error?

**Comment by reverser69** [comment]
error on lin 004

error executing command!

on 64bit target.
let me check it on 32bit

**Comment by mrexodia** [comment]
What's the log say? The bc command will only fail if the address you land
on after running is not a breakpoint. Most likely you land on a first
chance exception.

**Comment by reverser69** [comment]
even when not receiving "error executing command!"
debugger doesnt respond anymore.eip or rip
log says break point at "target" but doesn't stop the target just hangs. 
now says break point deleted but not responding any more .

**Comment by reverser69** [comment]
i dont know i assume im doing something wrong

**Comment by mrexodia** [comment]
> What's the log say?

You can find out by opening the log.
