### ISSUE TITLE
Change Command line bug

### ISSUE THREAD

**Issue by Vityacv** [x64dbg/x64dbg#1576]
try set cmd:
"C:\zzz\A.B.C.D. test\test.exe" -d xxx
ctrl+f2, check:
"C:\zzz\A.B.C.D. test\test.exe" test\test.exe" -d xxx

**Comment by mrexodia** [comment]
Read the manual.

**Comment by Vityacv** [comment]
???
After restarting process(Ctrl+F2) there is bug which changes original line:
"C:\zzz\A.B.C.D. test\test.exe" -d xxx
to:
"C:\zzz\A.B.C.D. test\test.exe" test\test.exe" -d xxx
As you see the string:
test\test.exe"
is added.

**Comment by mrexodia** [comment]
The command you tried to use to change the command line is in the wrong
format.

**Comment by Vityacv** [comment]
i believe the string:
"C:\zzz\A.B.C.D. test\test.exe" -d xxx
is a correct format for command line
Without dots it works without bug.

**Comment by mrexodia** [comment]
Sorry I misinterpreted the issue.
