### ISSUE TITLE
x64DBG - TraceInto-TraceOver expressions broken on GUI (build apr14,2017)

### ISSUE THREAD

**Issue by JChersko** [x64dbg/x64dbg#1578]
Build from Apr14, 2017.
Windows 10 64-bit , up-to-date
Brief description: Attempting to use the traceinto or traceover commands while in x64DBG results in invalid expression even when using the supplied examples for any field. (Not tested in x32DBG).

Reproduction of steps:
Try to do a simple TraceOver using the Debug -> TraceOver field. 
Set TraceCount to any lower number for testing (default 50000).
Set expression to part of the example expression "eax == 0" with or without quotes.
Trace will not start and says Invalid expression eax == 0.

Plugins currently using:
XDBG v0.01 by Brock
Scylla (example plugin)

**Comment by mrexodia** [comment]
Try the latest version.
