### ISSUE TITLE
Obsidium crashes the debugger with exception.

### ISSUE THREAD

**Issue by forkoz** [x64dbg/x64dbg#1579]
![obsidium](https://cloud.githubusercontent.com/assets/12354546/25706819/28ef1dbe-30a7-11e7-992f-baa4c8e96538.png)

Debugger shouldn't let a process crash it with BS memory reads. Funny thing is sometimes it will open, sometimes not. I thought it could be plugins but removing all of them didn't make things any more consistent.

**Comment by mrexodia** [comment]
Without unpackme or reproduction steps this is completely useless information.

**Comment by forkoz** [comment]
download NTlite and open it with the debugger. you didn't even try :(

**Comment by mrexodia** [comment]
I tried to open obsidium itself, but I didn't find any problems.

**Comment by forkoz** [comment]
I don't believe obsidium is protected with itself. Ntlite is the only product that comes to mind actually protected by it. 1.5 crackme opens with it just fine, 1.6 protected crashes most times. The only thing I could do was attach by scylla (which only lets me dump/try to reconstruct imports). Should I screen record?

**Comment by mrexodia** [comment]
Yeah please send more details and also send the plugins you are using
please. I got debugger detected

**Comment by mrexodia** [comment]
No response was given, comment if you have consistent reproduction steps from a clean environment with the latest version @forkoz .
