### ISSUE TITLE
Assembling instruction with a label and an offset is error.

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1582]
`mybuffer` is a label. Assemble `mov dword ptr [mybuffer+10],0` will be assembled as `mov dword ptr [10],0` for XEDParse. The instruction cannot be assembled by other assemble engines.

**Comment by mrexodia** [comment]
I think asmjit and keystone can also support this, but I didn't implement the callback. What happens if you assemble `call mybuffer`?

**Comment by torusrxxx** [comment]
`call mybuffer` cannot assemble with "keystone". It is assembled as expected with other engines. `call mybuffer+10` can only be assembled with `XEDParse` and it assembles it correctly. `mov dword ptr [mybuffer],0` assembles correctly.

**Comment by mrexodia** [comment]
Keystone was deactivated so the issue is no longer relevant I believe...
