### ISSUE TITLE
Version of each library in the `About` box

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#159]
Something like this:
```
TitanEngine 2.0.3
x32_dbg 1.1.3
x32_gui 1.3.5
...
```

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/159
- Originally reported by: [Dither](http://bitbucket.org/Dither)
- Originally created at: 2014-08-09T12:24:49.922

**Comment by Nukem9** [comment]
Honestly I don't see the value of this, this is only an issue when you start building your own versions or when you start mixing versions. The latest release always has the latest versions of the libraries available. I could make some static text though, but that's useless.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Well there are plugins also. And there is no way currently for a plugin to demonstrate its version to user unless it implements some kind of dialog for it. And it can be important to know that you use some outdated module/plugin.

----------------------------------------
Original comment by: [Dither](http://bitbucket.org/Dither)

**Comment by Nukem9** [comment]
see the log window for plugin versions.
![plugin_version.png](https://bitbucket.org/repo/gxGRnk/images/2128803471-plugin_version.png)

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
I don't know. Some modules show versions, some not and have only static info about them (system), integer version numbers, no single place to look at all the information like authors/versions/etc. It's very confusing. Though it's not that critical but psychologically it is a good thing to have single organized About box instead of several places with the needed info.

----------------------------------------
Original comment by: [Dither](http://bitbucket.org/Dither)

**Comment by Nukem9** [comment]
Plugins report their version to the debugger through a structure, so you really want I can create some plugin info dialog or something... And indeed versioning is confusing, because there is no standard. TitanEngine has no actual version (the one embedded in the resources is old), BeaEngine has a GetVersion API, but this doesn't really report the correct version, because it's updated. lz4 has no version, jansson has no version, XEDParse has no version.

Only Scylla has an actual version. I will keep the issue open though, maybe I will implement this some time.

Greetings

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by mrexodia** [comment]
don't think this is very useful anymore
