### ISSUE TITLE
Need pluging

### ISSUE THREAD

**Issue by josechuky** [x64dbg/x64dbg#1590]
Will some make a plugin, like IDA debugger have, or W32DsmPatch?
These plugins allow to change bits and try is the changes works, before patching. 
This is very useful when trying to crack the cracMe
My coding skills are not good, and this take 
an experienced programmer abilities.

Sample Pics
![ida4](https://cloud.githubusercontent.com/assets/27946556/26020323/33d58a9c-374b-11e7-9901-9eef458c484b.jpg)
![ida5](https://cloud.githubusercontent.com/assets/27946556/26020324/33d86f6e-374b-11e7-8754-898935bde5ea.jpg)
![wdsn](https://cloud.githubusercontent.com/assets/27946556/26020325/33da151c-374b-11e7-88b0-af13163d230f.jpg)
![ida1](https://cloud.githubusercontent.com/assets/27946556/26020327/33dc67fe-374b-11e7-9ad1-0d1b93a203dc.jpg)
![ida3](https://cloud.githubusercontent.com/assets/27946556/26020326/33db1d7c-374b-11e7-821f-c5350a7dee75.jpg)

thanks in advance
Jose

**Comment by ThunderCls** [comment]
Sorry, I'm not sure of understanding what you mean, do you want to be able to make patches on memory? Before committing on the physical file?, if so, you can do that in x64dbg since....always I believe.

**Comment by josechuky** [comment]
I can't really explain myself better. Maybe you know someone with Ida. You
can see it, for yourself.

**Comment by gmastergreatee** [comment]
@josechuky I think you are asking for this feature which is available in the "Patches" window. Also there is an "Export" option to export the patches for later import for re-debugging
![huahua](https://cloud.githubusercontent.com/assets/17880848/26024486/b9490ae2-37ef-11e7-82a2-82af129aa14b.gif)

**Comment by mrfearless** [comment]
No plugins needed, you can change bytes directly to try out commands, either by directly editing the raw bytes or by using assembler commands. Here is an example with editing directly binary, changing a JLE (x075) instruction to a JMP (0xEB) one :

![](https://s20.postimg.org/kiarix3h9/x64dbgbinaryedit1.gif)

**Comment by josechuky** [comment]
Thanks 
You are correct, the binary edit tool does the job,
thanks again
jose
