### ISSUE TITLE
update the launcher to be more intuitive

### ISSUE THREAD

**Issue by amn** [x64dbg/x64dbg#1591]
x64dbg presents a cryptic error message telling me "RegCreateKey failed" and presumably aborts process after that.

I have no intention to run the tool with Administrator privileges, is it essential or critical to its functionality, or just an artefact of some operation(s) that it assumes upon start?

I am going to be debugging my own processes, not even that -- actually I just want to open a .DBG dump file.

I understand that it may be a Windows limitation that requires the program to run with Administrator privileges in order to do some/everything that it is doing, but is there any chance to compartmentalize functionality so it at least starts when run with user privileges?

Am I welcome to submit a patch? Thank you.

**Comment by ThunderCls** [comment]
I'm assuming you're executing the launcher, if so, it will just try to create a couple entries in the Windows registry for shortcuts and icons and that stuff, but it's not required for proper use of the debugger, just run x32dbg.exe or x64dbg.exe directly depending on the platform you want to debug and you're good to go

**Comment by mrexodia** [comment]
Yeah I have to fix the launcher to make it more clear how to start x64dbg
itself...

**Comment by amn** [comment]
Appreciate your swift and constructive response, guys. Thank you for the tool. For now, I figure I will be loading from the `x64dbg.exe` that is in the `./release/x64` folder, as opposed to the "launcher" that's `./release/x96dbg.exe` (not sure why it has "96" in the name?)

**Comment by mrexodia** [comment]
32+64

**Comment by mrexodia** [comment]
The launcher has now been improved:

![](https://i.imgur.com/dnamSyU.png)
