### ISSUE TITLE
Exception Box

### ISSUE THREAD

**Issue by josechuky** [x64dbg/x64dbg#1594]
Hello to all,

Will you please.add the "CheckBoxes"
 Ignore memory access violation in Kernel32
Ignore pass to program allowing exception
INT3 break
Single step break
Memory access violation
Integer division by 0
Invalid or privileged instruction
All FPU exceptions
Ignore also custom exceptions ...
Thanks in advance
jose

**Comment by mrexodia** [comment]
No. Those settings are not safe. You can ignore them separately by pressing the button to add the last exception.
