### ISSUE TITLE
Weird non-existent bytes in code view for specific database

### ISSUE THREAD

**Issue by MulleDK19** [x64dbg/x64dbg#1595]
I took notepad.exe and emptied it, so I could use it to mess around with assembly.
After a while, trying to assemble some code, it became something else than I expected.

Assembling MOV RBP,RSP at certain addresses became:
```
00000001400012A5 | 48 89 E5                 | MOV RBP,RSP                                         |
00000001400012A6 | 89 E5                    | MOV EBP,ESP                                         |
00000001400012A7 | E5 90                    | IN EAX,90                                           |
```

Even more weird does it get after looking at the dump view, which correctly shows `48 89 E5 90`.
Somehow the code view shows duplicate bytes `89 E5 E5` that don't actually exist.

Then I tried changing the bytes in the dump, from `48 89 E5 90` to `12 34 56 90`, and the code view again shows duplicates of those bytes:
```
00000001400012A4 | 55                       | PUSH RBP                                            |
00000001400012A5 | 12 34 56                 | ADC DH,BYTE PTR DS:[RSI+RDX*2]                      |
00000001400012A6 | 34 56                    | XOR AL,56                                           |
00000001400012A7 | 56                       | PUSH RSI                                            |
```

Removing the database fixes the issue, but that won't be viable in a big project with hours put into it.

Looking at the addresses, somehow the code view fails to consume the bytes it disassembles, as you can see, the first byte in each of the disassembled instructions show the correct byte at that address, but then shows the next ones as well. So somehow, the disassembler correctly disassembles 48 89 E5 as MOV RBP,RSP but only advances 1 byte instead of 3, so the next disassembly occurs at 12A6 instead of 12A8, which also only advances 1 byte and so on.

**Comment by MulleDK19** [comment]
.exe and DB: [db.zip](https://github.com/x64dbg/x64dbg/files/1005180/db.zip)
Nop the instructions at 1400012A4 then try to assembly MOV RBP,RSP at 1400012A5

**Comment by mrexodia** [comment]
It appears to be related to type analysis. The database says:

```json
{
"encodemaps": [
  {
   "module": "empty.exe",
   "address": "0x1000",
   "manual": false,
   "data": "00{2A4}1113131100{D58}"
  }
 ]
}
```

Removing this (or doing right click -> analysis -> remove analysis type analysis from module) will fix the issue. You can also select the range where this goes wrong and press 'U' to remove the problem on a small scale so you can continue with your project.

Did you manually add byte/dword/etc type analysis here?

**Comment by mrexodia** [comment]
Okay, should be fixed now. Thanks for your concise report!

**Comment by MulleDK19** [comment]
I only tried analyzing, which did not help.
In either case, I don't see why type analysis would mess up the disassembler. Or rather, why it should.

Also, another issue I'm having, which I'm not sure if is because I'm doing something wrong or is a bug, but the Structs tab doesn't work at all. Neither Parse Header nor the AddStruct command. Nothing ever shows up in the tab despite it saying "Types parsed".

**Comment by mrexodia** [comment]
> In either case, I don't see why type analysis would mess up the disassembler. Or rather, why it should.

You don't have to see it, but it was related and I fixed it. The type analysis allows you to display bytes in the disassembler in a different way (`db E8` for example) and there was a logical mistake which made certain types of code behave incorrectly.

> Also, another issue I'm having

You're right, It is another issue.

However both commands work as expected just parsing the structs won't show them in the struct tab. You have to use the `visit struct` option and enter the struct type name (the one you give to `AddStruct`). It will then lay the struct over the memory and allow you to view members. See http://blog.x64dbg.com (somewhere in the weekly digests) for more information.
