### ISSUE TITLE
Enable/disable window (Handle tab)

### ISSUE THREAD

**Issue by MapleLeaf-X** [x64dbg/x64dbg#1597]
There is a bug which causes x64dbg (applies to both x86 and x64 versions) UI not to update the context menu aand the window table to 'enabled' or 'disabled'.

Steps to reproduce:
1. load up x64dbg and notepad. (order doesn't matter)
2. attach x64dbg to notepad.
3. run the target. (notepad)
4. go to handle tab and refresh it.
5. disable target's (notepad) window.

This will call EnableWindow for the target and disable the window while still showing 'enabled' in the window table as well as the context menu showing 'disable window'.
In order to be able to enable the window you have to disable it again and then UI goes back to normal.

This bug has been reproduced on windows 7 x64 sp1 with today's snapshot (05/17/2017).

**Comment by ThunderCls** [comment]
Ok, there was a syncing issue when calling the windows listing function and updating the GUI, a fix will be pushed soon enough 👍
