### ISSUE TITLE
Binary Strings Searcher

### ISSUE THREAD

**Issue by josechuky** [x64dbg/x64dbg#1598]
Hello all,
 Will you please add a Binary String Searcher.
Thanks in advance
jose

**Comment by mrexodia** [comment]
It's already supported.

**Comment by josechuky** [comment]
Hello Mrexodia
Can you explain where the binary string searcher?
thanks in advance 
jose

**Comment by gmastergreatee** [comment]
@josechuky While debugging go to "Memory Map" & then press "Ctrl + B", the rest is self-explanatory. This is my way, maybe there are more ways I don't know of.

**Comment by josechuky** [comment]
Many Thanks
jose
