### ISSUE TITLE
Script log instruction bytes

### ISSUE THREAD

**Issue by fvrmatteo** [x64dbg/x64dbg#1601]
- x64dbg version: May 17 2017
- OS: Windows 7 SP1 x64

Using the following log command: log "{mem;dis.len(cip)@cip}" in a script won't work, the output is "???".

I tried with the following formats and none worked:
- log "{mem;dis.len(cip)@cip}"
- log "{mem;10@cip}"

I also tested the previous commands with the trace functionality and with the command bar and they worked properly.

The attached script can be used to test the problem.
[loginstruction.txt](https://github.com/x64dbg/x64dbg/files/1012652/loginstruction.txt)

**Comment by mrexodia** [comment]
This is most likely related to script parsing. I think `;` might be used to indicate a comment as well...
