### ISSUE TITLE
Registers in alphabetical order... why

### ISSUE THREAD

**Issue by chvrn** [x64dbg/x64dbg#1607]
What is the use in this?
Why not use the values they are encoded by in instructions?

**Comment by mrexodia** [comment]
Because I want to.

**Comment by chvrn** [comment]
Okay. Just seems like a not so thoughtful decision. 

Having them in the proper order (like other debuggers) has the upside that you can use it for reference when switching single bits using the Binary Edit feature, looking at what's what on the stack after a PUSHA etc.

**Comment by mrexodia** [comment]
It was indeed decided about 4 years ago, before x64dbg went public. There is no real good reasoning for it (the order isn't even alphabetical) and you are welcome to send a pull request to change the order 👍

**Comment by torusrxxx** [comment]
eax,ecx,edx,ebx,esp,ebp,esi,edi
