### ISSUE TITLE
window titles in attach dialog is awful

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1608]
![x64dbg-attach-window](https://cloud.githubusercontent.com/assets/15761310/26525195/e9b7b5a2-433e-11e7-8dba-d5af7d9f6d05.png)

**Comment by mrexodia** [comment]
@ThunderCls you might wanna take a look at this

**Comment by ThunderCls** [comment]
Sure @mrexodia, I just don't understand the nature of the bug, or even what´s the unexpected behavior here.

**Comment by mrexodia** [comment]
From what I can tell the titles of the windows in the taskbar are somehow not shown in the attach dialog...

**Comment by ThunderCls** [comment]
Well that's what GetWindowText gives out, if you guys have any other idea, I'm all ears and willing to change it

**Comment by ThunderCls** [comment]
Ok, I think I found a workaround for this, it's just a matter of using GetWindow(..., GW_OWNER)/IsWindowVisible(...) to access explicitly to the correct "main window" of the given process and not just the foreground window. I'll push a fix as soon as I can
