### ISSUE TITLE
Detached + Closed Dump tab causes "Follow in Dump" to fail.

### ISSUE THREAD

**Issue by rotateLeft** [x64dbg/x64dbg#1609]
Version: 25 May 2017
O/S: Win7 x86 SP1

Issue: If you detach "Dump 1", then close it, it will automatically reappear on the end of the tab list (OK). If I then select a register value and "Follow in Dump -> Dump 1", nothing happens.

Steps: Load a PE file. Find a valid value in a register. Right-click register value and select "Follow in Dump" -> "Dump 1". Detach and close "Dump 1" tab. Again, right-click same register and "Follow in Dump" -> "Dump 1". Notice how the contents of "Dump 1" is not updated or given focus.

**Comment by blaquee** [comment]
This also occurs if you just detach the tab and try to follow in dump 1 as well. I'll take a look at this, I think I know why.
