### ISSUE TITLE
Dump tab names should be consistent in "Follow in Dump" submenu

### ISSUE THREAD

**Issue by rotateLeft** [x64dbg/x64dbg#1610]
Version: 25 May 2017
O/S: Win7 x86 SP1

Issue: If you double-click to rename a Dump tab, that new name should be used in the "Follow in Dump ->" sub menu.

Steps: Load a PE. Double-click a Dump tab to rename, ie "TestTab". Right-click a valid register value and select "Follow in Dump ->". The submenu list contains the old tab name.

**Comment by blaquee** [comment]
Wasnt this fixed recently by @torusrxxx ?

**Comment by mrexodia** [comment]
It indeed appears to have been fixed!

![fixed](https://i.imgur.com/qZ3HAYP.png)
