### ISSUE TITLE
Displaying Labels and Comments side-by-side

### ISSUE THREAD

**Issue by winkerbie** [x64dbg/x64dbg#1611]
How come I x64dbg doesn't display comments and labels side-by-side?

As in for a line of code:
**MOV RDI, RSI**    |     My Label       // my comment

Instead if the instruction has a label, but then I insert a comment, it just hides the label so looks like:
**MOV RDI, RSI**      |  // my comment

Its quite useful to have both, can it be added

**Comment by mrexodia** [comment]
you can, just drag the address column.

**Comment by winkerbie** [comment]
What do you mean?

**Comment by winkerbie** [comment]
oh found it

Is there a way to display the label instead of the address?

**Comment by mrexodia** [comment]
there is no way to display a label instead of the address.

**Comment by mrexodia** [comment]
note that the label is also displayed in the infobox under the disassembly.
