### ISSUE TITLE
Search reference of constant missed out result

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1617]
On win7 x64, load user32.dll and download the symbols for this module, then you can get the NtUserSetWindowsHookEx, this has been called by SetWindowsHookExW. But when CTRL+R on this, or search the constant of the NtUserSetWindowsHookEx address in current user32 module, it can't find any thing.
Check the assembly:

> 76AC75D5 | E8 09 00 00 00          | call NtUserSetWindowsHookEx          |
> 76AC75DA | C9                      | leave                                  |
> 76AC75DB | C2 18 00                | ret 0x18                               |
> 76AC75DE | 90                      | nop                                    |
> 76AC75DF | 90                      | nop                                    |
> 76AC75E0 | 90                      | nop                                    |
> 76AC75E1 | 90                      | nop                                    |
> 76AC75E2 | 90                      | nop                                    |
> 76AC75E3 | B8 8C 10 00 00          | mov eax,0x108C                         |NtUserSetWindowsHookEx
> 76AC75E8 | B9 00 00 00 00          | mov ecx,0x0                            |

It's like E8 09 is something short call, which cause the constant searching not find the result. Ollydbg behave OK.

**Comment by Mattiwatti** [comment]
The call chain is different for me, it goes `SetWindowsHookExW` -> `SetWindowsHookExAW` -> `_SetWindowsHookEx` -> `NtUserSetWindowsHookEx`. But CTRL+R does give me `_SetWindowsHookEx` when I stand on `NtUserSetWindowsHookEx`, all the way back to `SetWindowsHookExA`/`SetWindowsHookExW`.

**Comment by lynnux** [comment]
@Mattiwatti yes, actually, it's called directly by _SetWindowsHookEx. I downloaded the lastest  x64dbg release, it now can find the correct result, may be fixed by some recent commit. 
Very sorry for the trouble!

**Comment by mrexodia** [comment]
@lynnux could you send me the source code for x64dbg_tol again? It appears to have been removed from Github. I wanted to try implement the UAC trick for drag and drop.
