### ISSUE TITLE
Step over doesn't appear to step over

### ISSUE THREAD

**Issue by DigiAngel** [x64dbg/x64dbg#1621]
Using the June 8th release on Windows 7 32 bit.  Why is the jump taken if I've selected step over?  Thank you.
![peek 2017-06-15 05-51](https://user-images.githubusercontent.com/947191/27180081-dab21684-518e-11e7-906b-ec061285a204.gif)

**Comment by mrexodia** [comment]
That's just how it works. If you want to put a breakpoint on the instruction after the jump and run you can highlight it and press F4.

Basically step over is equivalent to step into, except for `call` and `rep` instructions.

**Comment by DigiAngel** [comment]
Awesome...thanks for setting me straight.
