### ISSUE TITLE
FPU Improvements

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1628]
- `403DFFFFFFFFFFFFFFFF` is not converted correctly (this requires fixes in [ldconvert](https://github.com/x64dbg/ldconvert))
- Add a GUI to parse floating point numbers (the `str2ld` function can be used for this), see #1624 
- Sort of FPU registers by ST(x) instead of x87rX (like in OllyDbg). FPU instructions operates with ST(x) as a rule but not with x87rX. It's not easy to debug FPU programs with current sort (#1624)

**Comment by jin-x** [comment]
Yes this is still very actual !!!!!!!! :)))

**Comment by jin-x** [comment]
**ldconvert** is a temporary solution... it's not so easy-to-use...

**Comment by torusrxxx** [comment]
since #1661 (July 27) you can enter a decimal number with decimal point in the edit floating point number register dialog.

**Comment by torusrxxx** [comment]
These issues are either fixed or in a separate issue #1841.
