### ISSUE TITLE
Error starting process (CreateProcess, ERROR_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by n0way0ut** [x64dbg/x64dbg#1635]
x64dbg version: build version 21 jun 2017

windows 7 sp1 x64

![launcher exe](https://user-images.githubusercontent.com/5345101/27772590-e75853aa-5f65-11e7-8ecd-a43d77a4b911.jpg)

**Comment by AraHaan** [comment]
wait wot I use Windows 7 sp1 ultimate here and normally CreateProcess should work just fine. I might have to take a look at it later.

**Comment by mrexodia** [comment]
It's related to the architecture of your operating system. Windows 32 bit works fine

**Comment by n0way0ut** [comment]
it works fine also if I open it with x64dbg instead of x32dbg.

**Comment by AraHaan** [comment]
it seems to work fine on my 64 bit install of windows 7 ultimate.

**Comment by stonedreamforest** [comment]
May be the reason for the plugin

**Comment by wk-952** [comment]
@n0way0ut This looks like a valid .Net app, use something like [dnSpy](https://github.com/0xd4d/dnSpy) to debug it.
![untitled](https://user-images.githubusercontent.com/11916365/27869680-f570abda-61a0-11e7-97a0-e5e63526c964.png)

**Comment by AraHaan** [comment]
ILSpy works too for it as well (well if you want to decompile it back to .net code from IL) @wk-952.

**Comment by blaquee** [comment]
Im working on a fix for this. Should be done in a day or so after some testing. I'll need someone to test on 32bit OS if I dont install a VM by then
