### ISSUE TITLE
Additional actions in Shortcuts dialog

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#164]
Specifically, I'd like to be able to set `Actions -> Copy Address` to `Ctrl+X`.

It might be a good idea to set the hotkey by default for all views (CPU, dump, stack, etc.).

In general, not all actions can be found in the Shortcuts dialog. Other examples: copy disassembly, search for constant.

---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/164
- Originally reported by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)
- Originally created at: 2014-08-14T11:03:05.874

**Comment by mrexodia** [comment]
should be easy to do, check AppearanceDialog.cpp and Configuration.cpp
