### ISSUE TITLE
How can I debug the whole project?

### ISSUE THREAD

**Issue by aikuimail** [x64dbg/x64dbg#1658]
I have tried the project for one day then I get it, and I found that I can't run the gui's dll with the debug build mode, I think the reason is that I have use the release dependency files, and how can I get the debug dependency? Sorry for my English.

**Comment by stonedreamforest** [comment]
[https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project](https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project)
