### ISSUE TITLE
Undo modified

### ISSUE THREAD

**Issue by freesoft0000** [x64dbg/x64dbg#1659]
Does the x64dbg assembly window have Undo function when it is modified? Fallback operation. 

Doesn't x64dbg have a program flow diagram like IDA? At the moment, it seems like only a flow chart of code snippets 

I'm a beginner and I don't seem to mention these in the help documentation, so I won't. 

In addition, the default font for the CHM help document is too small. 

Is it necessary to improve the documentation so that the instructions are more detailed?. 

X64dbg themes and colors can be integrated into the distribution package, again download more troublesome, some areas can not be downloaded. 

In the breakpoint window, the breakpoint can not be ctrl+, the mouse multiple choice, also cannot press the shift+ mouse to choose. 
You can't select symbols by Ctrl and shift, including the symbol window 

The default font for x64dbg is also small and can be changed larger. Large monitors are now widely used, so small fonts can blind people. Joke. 

Is a history file with user information stored separately in a INI file?. Instead of mixing them in the x32dbg.ini file. If the program is packaged for use by others. It is easy to delete useless information without losing configuration. 

I wonder if x64dbg's support for high DPI is perfect? 
Chinese language interface, some of the buttons of text display incomplete 

Whether the search filter can support & | ! (And or not)

One more question. 
The x64dbg menu sometimes hits very quickly and doesn't work. Need to click again.
For example, click file - open, or the shortcut menu in the right

**Comment by stonedreamforest** [comment]
`ctrl+backspace`

**Comment by freesoft0000** [comment]
thanks

**Comment by mrexodia** [comment]
@freesoft0000 open separate issues for separate questions/bugs.
