### ISSUE TITLE
multiple selection in breakpoint window

### ISSUE THREAD

**Issue by freesoft0000** [x64dbg/x64dbg#1666]
In the breakpoint window, the breakpoint can not be ctrl + mouse multiple choice, also cannot press the shift + mouse to choose.
 You can't select symbols by Ctrl and shift, including the symbol window

**Comment by mrexodia** [comment]
I have no intention of supporting multiple selections. There is no use for it.

**Comment by blaquee** [comment]
Maybe for breakpoints a command such as "bc *" can be supported to clear all BP's or a range of BPs using  bc [x-x] or (x-x).
