### ISSUE TITLE
doubleclick and ESC

### ISSUE THREAD

**Issue by peterius** [x64dbg/x64dbg#1672]
x64dbg snapshot_2017-07-09_20-21

x64dbg is great!  It seems like you guys are the best 64 bit debugger available, that's a real niche.  If I have some cash in the future I'll definitely send you some.

About the interface, I very much like being able to double click on the address in the memory Dump and get the offsets, that's very convenient.  However two things I miss from i d a are being able to double click addresses and look at the disassembly.  Currently double clicking opens a dialog to patch code, and I got to say that's not the first thing I would imagine wanting to do.  Gee, what's this, I don't know, I'll replace it.  I feel like patching is more of a contextual menu thing?

The other thing I really miss is using the escape key to move the sort of instruction cursor back, and then back out of a function  It would be nice even if there's no cursor to do something like have a kind of cursor function stack and maybe draw a thin box around the jmp or call or whatever that was actually executed so you can find your way back to the current rip/eip.  But being able to just hit escape a few times and get one's bearings, or label or break something, and then step back in is really useful.

**Comment by mrexodia** [comment]
Press enter if you want to follow branches

Use (Numpad) minus `-` and `+` to navigate.

**Comment by peterius** [comment]
Oh okay, thanks, that's decent.  I should have read some documentation.
