### ISSUE TITLE
x32dbg find pattern improvement suggestion

### ISSUE THREAD

**Issue by MerovingianByte** [x64dbg/x64dbg#1675]
It would be great if one could search for numbers writing in the decimal format rather than hexadecimal for convenience. For example, searching for 10 rather than 0A. You can do this on cheat engine by [typing in the value in decimal or hexadecimal format and selecting the value type](https://imgur.com/a/9QVHX)(binary, byte, 2 bytes, 4 bytes, 8 bytes, float, double, string, array of byte, all and grouped).

**Comment by mrexodia** [comment]
I won't change the way patterns are searched, you can however write your own conversion tools (plugin).

**Comment by MerovingianByte** [comment]
Omg you're quick. Ok then, thank you.

**Comment by mrexodia** [comment]
You can find some more related discussion here: https://github.com/x64dbg/x64dbg/issues/1281

**Comment by mrexodia** [comment]
As for some more explanation, the feature is searching for bytes. Obviously a different feature could be added to search for words/dwords but changing the existing feature isn't a good idea in my opinion.

**Comment by mrexodia** [comment]
There is also this pluin: https://github.com/codecat/ClawSearch

**Comment by MerovingianByte** [comment]
Awesome man! I think the last plugin is just what I wanted! Now when Skyrim stops crashing using x32dbg I won't have to use CE anymore(not that cheat engine is bad, it's an awesome tool as well, but I just prefer x32dbg)
