### ISSUE TITLE
Funcap alternative for x64dbg

### ISSUE THREAD

**Issue by fmj02** [x64dbg/x64dbg#1677]
Hi, is there anything like funcap - IDA Pro plugin for x64dbg? Some kind of utility that adds labels like deobfuscated strings, return values and passed function parameters. Please see https://github.com/deresz/funcap for screenshots for more understanding. I have found this: https://github.com/ThunderCls/xAnalyzer but I think it's only for WinAPI calls. Funcap is great but IDA Pro debugger just crashes for some targets like games using "local win32 debugger".

**Comment by mrexodia** [comment]
Ehm?

**Comment by mrexodia** [comment]
Well, it should be possible to make such a thing...

As for IDA integration, you can use labeless to sync. Adding TitanEngine to IDA would be pointless.
