### ISSUE TITLE
"cannot allocate memory" then terminate

### ISSUE THREAD

**Issue by reverser69** [x64dbg/x64dbg#1681]
hi
with a target 64dbg shows this error and terminates itself
i dont know if its a bug or its a trick by targets antidbg

**Comment by mrexodia** [comment]
please be more specific on how to reproduce the issue.

**Comment by Mattiwatti** [comment]
Wow, that's a kinder response than I would have given to this report @mrexodia.

**Comment by mrexodia** [comment]
I was in a good mood that day 😄

**Comment by reverser69** [comment]
yeah 
ive seen your other moods 
trying to present a description but its quite random
i hoped there was a dump\bug report feature so i could upload the crash file

**Comment by mrexodia** [comment]
1. update x64dbg (the error should be `Could not allocate memory (minidump will be created)`)
2. send me the file created in the `minidump` folder 👍

**Comment by reverser69** [comment]
ok
 debugging the target and waiting for error to show up

**Comment by mrexodia** [comment]
The issue appears to have disappeared. If you manage to reproduce it again @reverser69 please give consistent reproduction steps and comment here. I will reopen the issue.

**Comment by reverser69** [comment]
hi
much thanks for your attention
since aug 13 i am debugging the very same target but haven't received even a single allocation error
i think the issue was solved by using the last version of 64dbg
sorry for any inconvenience i caused and being late.was just testing in order not to submit any incorrect report.

regards

**Comment by mrexodia** [comment]
No problem and thanks for your quick response!
