### ISSUE TITLE
Issues while assembling `enter` instruction

### ISSUE THREAD

**Issue by AlexAltea** [x64dbg/x64dbg#1682]
Trying to assemble `enter 0, 9` (`C8 00 00 09`), but *asmjit* generates `enter 9, 0` (`C8 09 00 00`).
XEDParse doesn't even recognize the mnemonics at all. Keystone works fine though.

Tested on Latest x64dbg snapshot (snapshot_2017-08-08_01-47.zip).

**Comment by kobalicek** [comment]
oops, why not keeping it open until I solve it in asmjit?

**Comment by AlexAltea** [comment]
> oops, why not keeping it open until I solve it in asmjit?

Probably because this does not depend on x64dbg but it's exclusively an asmjit issue. Otherwise, every single project that depends on asmjit should open the same issue which defeats the purpose of project issues.

It was my fault for not reporting this issue directly to asmjit myself.
