### ISSUE TITLE
History (+ and - keys) in dump view

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#169]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/169
- Originally reported by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)
- Originally created at: 2014-08-15T00:50:38.080

**Comment by Nukem9** [comment]
I think this is better for runtrace stuff :-).

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by mrexodia** [comment]
implemented by @Herz3h
