### ISSUE TITLE
Entry point not found when starting x64dbg

### ISSUE THREAD

**Issue by jnowe** [x64dbg/x64dbg#1693]
Hello,

I have a strange error when I launch x64dbg (64 bits) on my Win7-x64-SP1.

I get this:
"The procedure entre point ?toLower@QString@@QEGBA?AV1@XZ could not be located in the dynamic link library Qt5Core.dll."

I'm using the latest snapshot of x64dbg. It's the first time I see this error.

Thanks

**Comment by mrexodia** [comment]
I recently updated some dependencies, perhaps I messed that up (although everything worked fine when I tested it)

**Comment by mrexodia** [comment]
Just tested, `snapshot_2017-08-22_13-37.zip` works fine...

**Comment by jnowe** [comment]
I've downloaded the snapshot you mentioned; again, the error still remains. How can I trace the error to fix it on my computer? can it be linked to another dll?

**Comment by jnowe** [comment]
With x32dbg, there's no error btw.

**Comment by mrexodia** [comment]
I checked both x32dbg.exe and x64dbg.exe when freshly extracting this snapshot from the download. You could check with Procmon if it tries to load Qt from a different location

**Comment by jnowe** [comment]
It works well if installed in another folder. If I update my current folder where previous x64dbg is installed, I get the error. Strange, no?

**Comment by mrexodia** [comment]
No, probably you didn't properly overwrite the Qt DLLs. Try deleting the `platform` and `Qt5*.dll` files.

**Comment by jnowe** [comment]
Thanks, I will follow that trick next time.

**Comment by jnowe** [comment]
ahh damn, the error came back. Very random.

**Comment by mrexodia** [comment]
I don't think there were any changes to the codebase though?

**Comment by jnowe** [comment]
Ok, it's the plugin quickaccess.dp64 that creates this error at starting the debugger

**Comment by mrexodia** [comment]
Ah that very possible. You can easily fix it by recompiling this plugin for
Qt 5.6.2 as shown on the wiki.
