### ISSUE TITLE
CreateThread Thread Entry or manual breakpoint not working

### ISSUE THREAD

**Issue by gmourton** [x64dbg/x64dbg#1694]
[Lab2_patch.zip](https://github.com/x64dbg/x64dbg/files/1246846/Lab2_patch.zip)
Debugger version: x32dbg v25 compiled on: Jan 10 2017, 20:36:51
Operating system: Windows 7 Home Premium Service Pack 1 running in VMware on Ubuntu.

The start address of CreateThread does not break when the program is ran. Even if I manually put a breakpoint on the address or hardware breakpoints, it does not break and terminates. Doing the same steps, it will break in ollydbg.
![image1](https://user-images.githubusercontent.com/5059815/29635858-503869c4-8846-11e7-9f0d-8272ba02137b.jpg)
![image2](https://user-images.githubusercontent.com/5059815/29635862-53fa07a2-8846-11e7-81e9-a6c5b98bfe7c.jpg)

Set a breakpoint on address 1000D0FD with the relevent debug settings (thread entry) or manually set a breakpoint on the address to be ran (10001656). Then stepping or running the program will run and terminate without breaking. These steps in ollydbg will cause olly to break in the thread start.

**Comment by blaquee** [comment]
Hmm not sure what youre going through but I just tested this and it broke just fine on CreateThread API. Try updating your x64dbg version to latest.

**Comment by mrexodia** [comment]
This file is not an executable, if you want to load this file and not return from EntryPoint after LoadLibraryW succeeded, write your own executable such as:

```c++
int main()
{
    LoadLibraryW(L"Lab2_patch.exe");
    Sleep(INFINITE);
    return 0;
}
```

And attach x64dbg to this.
