### ISSUE TITLE
A crash while clicking on 'X' (looking for xrefs) in the graph

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#1695]
The code crashed on this line:
https://github.com/x64dbg/x64dbg/blob/1d28f08fd3decdaaa43abf53a70698b624f2af86/src/gui/Src/Gui/XrefBrowseDialog.cpp#L42

Seems like the crash happens on code which is not attached to any module, e.g. code that resides on manually allocated memory.

JIT screenshot after the crash:
http://i.imgur.com/itjZxTU.png

**Comment by mrexodia** [comment]
Thanks! It appears to be an uninitialized field in the graph. I have a fix but I will push it later.

**Comment by RaMMicHaeL** [comment]
Great, thanks! It would be also great to have [support disassembly history in graph](https://github.com/x64dbg/x64dbg/issues/1528). I tried to put a small bounty on it on bountysource.com, but for some reason I couldn't find the issue.

**Comment by mrexodia** [comment]
@RaMMicHaeL I did manage to find it, but it appears the search feature is completely broken at Bountysource... https://www.bountysource.com/issues/43951381-support-disassembly-history-in-graph
