### ISSUE TITLE
Ten or more Watches causes weird behaviour when setting Watchdog Mode or Deleting

### ISSUE THREAD

**Issue by rotateLeft** [x64dbg/x64dbg#1701]
Build: Aug 22 2017
O/S: Win7 x86
Description: If you have 10 or more Watches in the Watch window, setting the Watchdog Mode for the 10th entry does nothing. If you increase the number of Watches to 18, setting the Mode for Watch 10 causes Watch 16 to be updated. The same applies to deleting - delete Watch 10 causes Watch 16 to be removed. The behaviour of Watches 1-9 seem OK.

Steps: In the Watch Window, add 10 Watches. I used increasing variations on "ds:[11E10]", "ds:[11E14]" etc. With 10 created, try and change the Watchdog Mode on the 10th entry to "Changed". Nothing happens. If you add another 10 Watches, changing the Watchdog Mode on the 10th entry causes the 16th entry to be updated. Similarly, deleting the 10th entry causes the 16th entry to be removed.

**Comment by blaquee** [comment]
Isnt this fixed by @torusrxxx PR?

**Comment by mrexodia** [comment]
Yes!
