### ISSUE TITLE
Unable to close debugger

### ISSUE THREAD

**Issue by aswerw** [x64dbg/x64dbg#1704]
Windows 8.1 x64
Aug 22 2017 (snapshot_2017-08-22_13-37.zip)
Aug 26 2017 (snapshot_2017-08-26_15-59.zip)

[Video](https://streamable.com/a3uz8)

- Load the executable. [Unpackme.zip](https://github.com/x64dbg/x64dbg/files/1266099/Unpackme.zip) (Enigma 5.6)
- Add ignored exception range: 00000000-FFFFFFFF.
- Run it, and close the programs window.

The debugger does not seem to detect that the debuggee has terminated. 
Close, Restart, Pause, File->Detach, and File->Exit will not work.

**Comment by aswerw** [comment]
ThreadHideFromDebugger

**Comment by mrexodia** [comment]
Okay, good to hear it's solved :)
