### ISSUE TITLE
Exported Symbols from DLL missing for Visual Studio 2017 debug builds

### ISSUE THREAD

**Issue by Dwedit** [x64dbg/x64dbg#1706]
Version: Aug 22 2017
OS: Windows 10 x64 15063.540

I have built an example DLL program in Visual Studio 2017 (15.3.2), it's a simple Hello World DLL program that exports a function named Hello.  It's a debug build.

```
#include <stdio.h>

extern "C"
{
	__declspec(dllexport)
	void Hello()
	{
		printf("Hello World!\n");
	}
}

```
When I load the DLL in x32dbg, I am unable to find the Hello symbol in the list of symbols.
The only exported symbol on the list is the module entry point.

![x32dbg_screenshot1](https://user-images.githubusercontent.com/1743498/29990575-7dd79c90-8f41-11e7-9970-ccd922106c3c.png)

When I look at the DLL function list in Ollydbg, it looks fine.

![ollydbg_screenshot](https://user-images.githubusercontent.com/1743498/29990579-8c2a9bee-8f41-11e7-8f7d-d4f622973401.png)

Here is the sample DLL file.  It's a visual c++ debug build of the hello world snippet.

[DllTest.zip](https://github.com/x64dbg/x64dbg/files/1271710/DllTest.zip)

**Comment by mrexodia** [comment]
works just fine

![](https://i.imgur.com/scrOi9H.png)

**Comment by Dwedit** [comment]
Okay, it seems to work if I delete the PDB file.  If the PDB file is in the same directory, I see the bug.

[DllTest_with_pdb.zip](https://github.com/x64dbg/x64dbg/files/1271721/DllTest_with_pdb.zip)

**Comment by blaquee** [comment]
Not sure if its a bug, but just go to the DLL and 'Download Symbols for this module' and it will resolve the Hello Export.

**Comment by Dwedit** [comment]
I tried saying "download symbols for this module", but that just made it try to download Hello World symbols from Microsoft, which obviously failed.  Still no Hello export appearing in there if the PDB is loaded.
