### ISSUE TITLE
Dump Feature Request

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1709]
Pressing __"Up"__ or __"Down"__ while on the __"Dump"__ view __decreases__ or __increases__ the address by 16 bytes. Why not also add an option to press __"Left"__ or __"Right"__ to __decrease__ or __increase__ the address by 1 byte.

**Comment by mrexodia** [comment]
You can use Ctrl+Up I believe.

**Comment by gmastergreatee** [comment]
Okay! I didn't knew that but now there's another problem. When moving by 1 byte, the selected address always changes to whatever is the top-left address irrespective of the previously selected address.

For example, let's say that the top left address is 401010 & I have selected address 401018. Now if I press Ctrl+Up or Ctrl+Down, then the selected address will change to 40100F or 401011 whereas it must remain the same(because while pressing Up or Down, the selected address doesn't change).
