### ISSUE TITLE
Dump autoupdate

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#171]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/171
- Originally reported by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)
- Originally created at: 2014-08-15T01:10:15.266

**Comment by Nukem9** [comment]
i think this should be done from a plugin using GuiUpdateDumpView(); the dump is updated automatically when x64_dbg performs memory changes.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
I think that the feature would fit nicely into x64_dbg itself. OllyDbg 2 has this feature, and I use it quite a lot.

![Untitled.png](https://bitbucket.org/repo/gxGRnk/images/836130228-Untitled.png)

----------------------------------------
Original comment by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)

**Comment by Nukem9** [comment]
hm, it is just going to take away CPU time... I will add it in the testplugin after I finished a custom context menu

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
> hm, it is just going to take away CPU time...

That's why it's off by default. It's very handy when working with GUI programs, e.g. when you need to check how a variable changes when the mouse hovers over a specific element.

----------------------------------------
Original comment by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)

**Comment by Nukem9** [comment]
alright, is 100 ms good enough? or 10?

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
OllyDbg uses one second, which is good enough most of the time, but sometimes a little bit too large.

I'd say that 100 or 200 ms will do. 10 ms is unnecessarily low.

----------------------------------------
Original comment by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)

**Comment by mrexodia** [comment]
create a new thread that calls `GuiUpdateDumpView()` once in a while

**Comment by mrexodia** [comment]
@RaMMicHaeL https://i.imgur.com/yU9ubOK.gifv

**Comment by RaMMicHaeL** [comment]
Nice, thanks!
