### ISSUE TITLE
The debugger does not respond after trying to close the debugging

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#1710]
**Commits on Sep 4, 2017**

The debugger does not respond after trying to close the debugging, on both versions, 64 bit and 32 bit, execution of plug-in unloading hangs during closing process ... the debugger no longer closes, a second attempt at debugging causes errors, opening a duplicate copy of the debugger leads to a synchronization error ... on the previous version everything was fine.

![](https://image.ibb.co/gLsPpF/Image_2.png)

![](https://image.ibb.co/krWTGv/Image_3.png)

```
Debugging stopped!
AutoCmdLine unloaded. 
Waiting for the debuggee to be stopped...
Aborting scripts...
Unloading plugins...
[PLUGIN] APISearch.dp64 unloaded
[PLUGIN] AutoCmdLine.dp64 unloaded
```

**Comment by mrexodia** [comment]
See #1704

**Comment by UnlimitedChild** [comment]
without debugging the same thing, it's enough to open the debugger, where the debugger no longer closes, the calls are not intercepted ...

**Comment by mrexodia** [comment]
Is there some kind of kernel mode driver running perhaps? And I don't know what "calls are not intercepted" means..

**Comment by mrexodia** [comment]
Also, please give a list of all your plugins. And try without plugins.

**Comment by UnlimitedChild** [comment]
I tried different versions, it does not depend on the plugins themselves, it depends on the number of plugins, then the unloading of plugins does not work anymore. Here I copied all the plugins and the debugger archive for the 64-bit system only, the last build. https://mega.co.nz/#!AkR3Haab!AAAAAAAAAAD2zK-gy8HA7AAAAAAAAAAA9syvoMvBwOw
I'll try to debug it ...

**Comment by freesoft0000** [comment]
Version of the test:
snapshot_2017-09-05_05-09
snapshot_2017-09-05_17-37
All plug-ins are no longer working.
and x64dbg software does not exit normally. Prompted
Closing Debugger ... Taskbar shows unloading plugins ...
X64dbg can exit if no plugins are used

**Comment by freesoft0000** [comment]
snapshot_2017-09-01_23-04
There's no problem with this version.
