### ISSUE TITLE
The debugger doesn't close at all.

### ISSUE THREAD

**Issue by KurapicaBS** [x64dbg/x64dbg#1711]
snapshot_2017-09-05_05-09.zip

If the "Don't show close dialog" is checked, then dialog won't close at all.

f it's not checked, the closing dialog will show but won't disappear.

![2017-09-06_014309](https://user-images.githubusercontent.com/13423107/30086717-15b2b2ca-9249-11e7-9023-4e76985a3867.jpg)

**Comment by mrexodia** [comment]
Duplicate of #1710 

Could you also try without plugins?

**Comment by mrexodia** [comment]
Should be fixed now!

**Comment by stonedreamforest** [comment]
me too
