### ISSUE TITLE
x32dbg freezes executing script

### ISSUE THREAD

**Issue by toffler** [x64dbg/x64dbg#1716]
Hi, I'm new to xdbg, I wrote my first script **log "start"**, when I attach to a process, paste this text into script window and press space, an empty window "script error" appears, xdbg freezes and becomes non-responsive. I use Win 8.1. I read about font issues, so I disabled windows font cache service - that didn't help.

**Comment by mrexodia** [comment]
I cannot reproduce this, both x64dbg and x32dbg print `start` in the log and then are fully responsive...

**Comment by blaquee** [comment]
What version of x64dbg are you using @toffler

**Comment by toffler** [comment]
I'm using x32dbg, this happens only if I attached x32dbg to a process, I tried a few different processes and x32dbg crashes badly as soon as I try to execute script by pressing space.  It works perfectly if x32dbg is not attached, also works if I just type **log "start"** in the command field and press enter.

**Comment by toffler** [comment]
The script window is detached btw if it helps. Also if I paste for example **qwerty** in the script window when x32dbg is not attached to process I get a pop up window saying **Error in line 001**. If I do the same with attached process, the same window says **Script Error** and it crashes, so I get different error windows.

**Comment by mrexodia** [comment]
Okay I reproduced the issue, a fix will be available shortly.

**Comment by toffler** [comment]
Thank you! This site is very confusing, how and where can I get a fixed x32dbg.exe?

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/releases

**Comment by mrexodia** [comment]
The sourceforge snapshots are daily (will probably be uploaded soon), github releases are always builds of the latest commit
