### ISSUE TITLE
x64dbgpy plugin error

### ISSUE THREAD

**Issue by nihuai** [x64dbg/x64dbg#1718]
click run，Print two times
![debug](https://user-images.githubusercontent.com/22935890/30361998-5ce86b64-988c-11e7-93f1-60f813bbd29b.png)

click run，Single step two times
![qq 20170913141734](https://user-images.githubusercontent.com/22935890/30362395-5caeee14-988e-11e7-9038-4e438f68ecd3.png)

**Comment by mrexodia** [comment]
Open in the x64dbgpy repository please.

**Comment by nihuai** [comment]
@mrexodia Do you have an example?

**Comment by nihuai** [comment]
@mrexodia I'm from x64dbgpy plugin Open Edit，Refer to the video

**Comment by mrexodia** [comment]
python.x64dbg.com
