### ISSUE TITLE
is it disassembling bug?

### ISSUE THREAD

**Issue by reverser69** [x64dbg/x64dbg#1719]
this is assembly by delphi reconstructor :
 HintProcessUnit::sub_006E93CC
 **006E93CC**    push       ebp
 006E93CD    mov        ebp,esp
 006E93CF    mov        ecx,4
 006E93D4    push       0
 006E93D6    push       0
 006E93D8    dec        ecx

and this by 32dbg : 
006E93C9 | 77 00             | ja hideallip.6E93CB                     | jmp $0
**006E93CB** | 00 55 8B          | add byte ptr ss:[ebp-75],dl             |
**006E93CE** | EC                | in al,dx                                |
006E93CF | B9 04 00 00 00    | mov ecx,4                               |
006E93D4 | 6A 00             | push 0                                  |
006E93D6 | 6A 00             | push 0                                  |
006E93D8 | 49                | dec ecx                                 |
006E93D9 | 75 F9             | jne hideallip.6E93D4                    |
006E93DB | 51                | push ecx                                |

**Comment by mrexodia** [comment]
It's not a bug. Delphi likes putting zero bytes between functions. Use "b" to set the correct type in disassembly.
