### ISSUE TITLE
Workaround for the SetWindowsHookEx things in debuggee?

### ISSUE THREAD

**Issue by Klanly** [x64dbg/x64dbg#1723]
When keyboard or mouse was hooked by the debuggee, it makes the debugger almost unable to step.
The LowLevelHooksTimeout regkey helps a bit, but it affects other processes.
So there should be a built-in function in the debugger to filter out these hook calls when debugging.

**Comment by mrexodia** [comment]
I disagree. This kind of functionality would be very brittle and easily cause all kinds of issues. There are various solutions, a plugin perhaps or adding another input device that is used for stepping?
