### ISSUE TITLE
Debugging posix executables 

### ISSUE THREAD

**Issue by techvoltage** [x64dbg/x64dbg#1724]
In a recent ctf there was a posix executable. However, I was not able to debug it properly because apparently when the executable is started, Windows passes control to posix.exe. In x64dbg, I was only able to see posix.exe and had trouble finding the code for the binary. Is there a proper support for posix subsystem?

**Comment by mrexodia** [comment]
There is no support and there probably won't be any either. If you want to debug a linux executable you can use a linux debugger (r2, gdb).
