### ISSUE TITLE
Some prefetchXX instructions

### ISSUE THREAD

**Issue by jin-x** [x64dbg/x64dbg#1725]
Version Jul 8 2017 doesn't know some of prefetchXX instructions:

• **prefetch** (e.g. 0F 0D 00 - prefetch [eax])
• **prefetchwt1** (e.g. 0F 0D 10 - prefetchwt1 [eax])

Please add :))

**Comment by flobernd** [comment]
This should be fixed. Zydis correctly recognizes these instructions as `prefetch_exclusive` (XED name; I'll probably remove the suffix) and `prefetchwt1`.
