### ISSUE TITLE
Can't skip C0000005 exception, But ollydbg can.

### ISSUE THREAD

**Issue by yumere** [x64dbg/x64dbg#1726]
My x64dbg version is snapshot_2017-09-12_00-45
Operating System: Windows 10

Brief:
I run pikachu volley ball game developed in 1997. This program is made by Visual C++ 4, MFC. Very old code.

When I debug the program with ollydbg, I didn't encounter any exceptions.
But when use x64dbg I encounter C0000005 exception.

I surely added that exception code to x64dbg setting.

In address 00402F82, asm is below

```asm
mov ecx, dword ptr [edi + edx*4 + 4]
```

In x64dbg:

```ASM
ecx=02337328
dword ptr [edi+edx*4+4]=[E678FB5C]=???
.text:00402F82 pika.exe:$2F82 #2382
```

In ollydbg:

```
DS:[005C5F4C]=005C6828
ECX=005C6998
```

Why these address calculated by `EDI` and `EDX` is different?
What can I do for this problem?

**Comment by mrexodia** [comment]
Good chance the contents of edi,edx are not the same in ollydbg and x64dbg at that crash?

Use a clean ollydbg as well (eg no anti-anti-debug plugins) to test.

**Comment by yumere** [comment]
Oh.. Sorry. When use clean ollydbg, I encountered same exception...

Um... Actually I don't work on program analysis and I'm just studying Reinforcement Learning AI.

What should I do? Just install anti-anti-debug plugins into x64dbg?

**Comment by mrexodia** [comment]
For me with a clean x32dbg.exe (no plugins) I do:

1. open [volleyball.exe](http://www.geocities.ws/psydralf/Pikachuvolleyball.htm)
2. use `dbh` command
3. the game runs fine in x32dbg

**Comment by yumere** [comment]
Very Very Thank you for your advise. I can debug program now and research. 👍
