### ISSUE TITLE
Ideas for Yara improvement

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#1729]
Currently there's a dialog able to select *.* files in a selected directory
iam wondering if it could be more like dila's YaraGUI so its able to scan with all previously
selected yara rules. Also currently it does not detect all yara signatures for example try: 
https://github.com/x64dbg/yarasigs/blob/master/packer_compiler_signatures.yara

other signatures:
https://github.com/x64dbg/yarasigs/
dila's YaraGUI:
http://sigint9.github.io/yaragui/

**Comment by mrexodia** [comment]
Yara has been removed from x64dbg.
