### ISSUE TITLE
Function analysis is wrong in every PE I disasm?

### ISSUE THREAD

**Issue by andresantacruz** [x64dbg/x64dbg#1731]
Hi, I was trying out the x32dbg in some PEs I have here to see how is it.

Unfortunately all the PEs I have loaded, the dbg can't properly analyse functions. I have to manually analyse (shortcut A) at the start of each function in order for the disasm to correctly reach the end of that function.

Is this a known issue? If so I'm sorry to post, I did a search but didnt find anything here at github.

I was thinking it could be due to the disasm algorithm? I couldnt find in google which disasm algorithm the x64dbg implements as well. Is it linear sweep?

Thanks.

**Comment by mrexodia** [comment]
It's intentional. Individually analyze functions you're interested in by pressing "A" on function start.

**Comment by andresantacruz** [comment]
Hum...
May you explain why it's intentional? I mean, every other dbg I used have the feature to analyse the entire module. Even the x64dbg have the feature (ctrl+A) but it doesn't seem to work as intended.
Thanks for the fast response @mrexodia

**Comment by blaquee** [comment]
You could also use the xanalyzer plugin that offers the ability to do a module wide analysis

**Comment by andresantacruz** [comment]
hummm I will check this plugin right now. Thanks @blaquee

**Comment by andresantacruz** [comment]
Although I'm curious about why this is the way it is ATM. Can't think about the motivations behind don't analyse the module entirely.

**Comment by mrexodia** [comment]
Ctrl+A uses an inferior algorithm. There is no reason to analyze all the functions so that's why it's disabled. You can read extensive reasons on the radare2 blog http://radare.today/posts/analysis-by-default/

The question is, why do you want analysis? And also if there is a bug with analysis, what is the bug exactly?

**Comment by andresantacruz** [comment]
Thanks @mrexodia for pointing the reasons :)

There is no bug with analysis AFAIK. I just found this way of disasm very strange because I never see it done this way. I come from a IDA background and one thing I always found very useful with IDA is the analysis capabilities it have but now I understand the motivation behind what you did in x64dbg.
