### ISSUE TITLE
Terminated (debugging stopped) when debugging a program

### ISSUE THREAD

**Issue by jnowe** [x64dbg/x64dbg#1733]
Hello all,

I dont know if I can say it's a bug or a problem in using x32dbg.
I have a setup.exe file. This setup launches Winzip to extract the program to be installed. But it requires a password. I use x32dbg to find it or to bypass it. When I fill the request with a password, the setup tells me the password is invalid with a popup. When I click OK, the debugger is stopped and the file analyzed is removed from x32dbg.
So is-it a bug? Or I'm using badly the debugger? so what can I do?

Thanks for feedback

PS: I use the latest build on Windows 7-x64 SP1

**Comment by mrexodia** [comment]
I think this is the expected behavior. If the process terminates, the debugee will close in x64dbg. You can try putting a breakpoint on `NtTerminateProcess` to see the state just before the program exits.

If you think your issue was not solved, just put a comment here and I will re-open it.

**Comment by juski1995** [comment]
Hi!, i am encountering an issue when trying to debug a program using x64, the program has an anti-debug method embedded into the program, i am extremely novice, just started trying to debug and code today, i would like to know, how can i bypass this error message so that i can continue to debug this program

**Comment by theguly** [comment]
sorry to reopen this issue, but as long as i debug, i'd like to see what happened before any TerminateProcess or whatever.
immunity, olly, both let me to explore the stack even after a process is killed/closed/whatever: this is a huge plus to trace the flow

**Comment by Inori** [comment]
Me too, both OllyDbg and windbg will stop on the last instruction when the process exit.

**Comment by mrexodia** [comment]
You can set a breakpoint on NtTerminateProcess

**Comment by Inori** [comment]
It will be better if we can see the last exception instruction which makes the program exit, together with it's register context and call stack.
`NtTerminateProcess` can stop the debugger from exiting, but we lost many information.
I have to see the log window for the last exception and sometimes it's not very clear especially in a big complex program with many threads and normal exceptions.

**Comment by mrexodia** [comment]
Last chance exceptions will always cause a break before NtTerminateProcess
so you should already have that information.

Breaking on NtTerminateProcess should also give you the callstack. It’s
also possible to break on the exit process debug event, but at that point
the context is already lost so I’m not sure how that could be helpful.

**Comment by fenderluvr** [comment]
How can you do this in x64DBG?  Maybe my syntax is wrong, but I cannot get this to work.  Can you pls provide and example of how to set a BP on NtTerminateProcess?  Thank you!

**Comment by alihamza687** [comment]
> I think this is the expected behavior. If the process terminates, the debugee will close in x64dbg. You can try putting a breakpoint on `NtTerminateProcess` to see the state just before the program exits.
> 
> If you think your issue was not solved, just put a comment here and I will re-open it.

bro help me i use x32dbg i run softwaer in x32dbg and x32dbg terminated debugging stopped option me The hide formula isn't working on it either.
