### ISSUE TITLE
Crash When Calling DbgGetProcessId

### ISSUE THREAD

**Issue by atom0s** [x64dbg/x64dbg#1734]
**Debugger Version:** Sep 12 2017, 00:43:44
**Operating System:** Windows 10 Pro x64 Build 10.0.14393
**Brief Description Of The Issue:**

When coding a plugin, if you call 'DbgGetProcessId' from within pluginInit, x64dbg will crash. (Using x32dbg.exe for testing a plugin idea.)

**Steps To Reproduce**

  * Create a basic plugin using the plugin example(s).
  * Inside of pluginInit, call DbgGetProcessId.
  * Place compiled plugin into the plugins folder and launch x32dbg.
  * It should crash immediately.

_New to x64dbg's plugin interface so this may be in the docs somewhere that I missed. Didn't see another report that even mentions DbgGetProcessId so figured it should be ok to report. I have a feeling this will crash on any of the Dbg functions though._

**Comment by mrfearless** [comment]
Yes it does appear to hang or crash if used in pluginit or plugsetup. If used in the CBINITDEBUG callback it works ok, which makes sense as DbgGetProcessId will return the process id of the target app being debugged, whereas with pluginit and plugsetup there isnt a target process initiated yet.

**Comment by mrexodia** [comment]
Impressive that nobody has found this so far!

Anyway what @mrfearless is saying is true, calling `DbgGetProcessId` doesn't make any sense before `CBINITDEBUG` is called, because there is no debuggee (it will also return 0 now).
