### ISSUE TITLE
Go to file offset (ctrl+shift+g) address calculation is broken

### ISSUE THREAD

**Issue by danilaml** [x64dbg/x64dbg#1737]
- Debugger version: Sep 12 2017
- Operating system version and Service Pack: Win7 SP1 x64
- Brief description of the issue: When trying to jump to offset bigger than `0x200` from the image base using `ctrl+shift+g` menu the calculated address is wrong.

Example: I open a file (simple hello world exe)/mem dump with base address equal to `0x00D60000`.
If then I press `ctrl+shift+g` and try to enter different offset values the shown jump address is as follows:
  * for `1` it's `00D60001`
  * for `123` it's `00D60123`
  * for `0` it's `01160000` *(!)*
  * for `200` it's `00D60000` *(!)*
  * for `1000` it's `00D61C00` *(!)*
  * and etc.

**Comment by mrexodia** [comment]
The dialog doesn't go to a relative offset. It goes to the file offset

![](https://i.imgur.com/vdggj8K.png)

For me to reproduce your issue I need the binary you are debugging. If you want to go to a relative offset in the current module just use `:$1234` will go to `mod.base(dis.sel())+0x1234`

**Comment by danilaml** [comment]
@mrexodia sorry, didn't look up proper English name. But I still don't see how this behavior is expected. I.e. why "for 123 it's 00D60123" but "for 200 it's 00D60000"

Anyway, here is the exe (it's just a simple "hello, world" application).
[1.zip](https://github.com/x64dbg/x64dbg/files/1346663/1.zip)

You can just run it and try my examples:

![image](https://user-images.githubusercontent.com/2046350/31048313-3dd84510-a623-11e7-9d3c-e6cc9ec9cd12.png)
![image](https://user-images.githubusercontent.com/2046350/31048315-469ffbac-a623-11e7-84d4-a15fce27b34b.png)
![image](https://user-images.githubusercontent.com/2046350/31048320-4e1abc96-a623-11e7-9e4d-d257a1265d57.png)
![image](https://user-images.githubusercontent.com/2046350/31048321-5357ef3a-a623-11e7-93a2-5aa375d79c18.png)

**Comment by mrexodia** [comment]
Yeah, the file offset -> rva conversion is tricky and is being rewritten. You are doing it in ntdll though and not the hello world

**Comment by danilaml** [comment]
@mrexodia I don't think it matters in this case, since I get the same results. Btw, what is so tricky about it exactly? FOr example in this case I thought I only wanted to do a simple sum of to hex values (base value + offset). Shouldn't be anything tricky with it, unless there is a bug in parsing. And it works for some small numbers, don't see why it shouldn't work for bigger ones.

Btw, tried to compile the x64dbg, but man this is tricky ;P (the fact that I'm using VS2017 doesn't help). Have you considered at least moving GUI part to VS solution, so you don't have to use 2 IDEs to compile it? There is a Qt plugin for all recent VS versions.

**Comment by mrexodia** [comment]
>  For example in this case I thought I only wanted to do a simple sum of to hex values (base value + offset).

You should definitely re-read my first comment.

> Btw, tried to compile the x64dbg, but man this is tricky ;P (the fact that I'm using VS2017 doesn't help). Have you considered at least moving GUI part to VS solution, so you don't have to use 2 IDEs to compile it? There is a Qt plugin for all recent VS versions.

VS2017 is not supported, just follow the steps [here](https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project#prerequisites). You can use the Qt plugin yourself because it just opens the `.pro` file in Visual Studio as far as I know...

**Comment by danilaml** [comment]
@mrexodia 
>You should definitely re-read my first comment.

Well, maybe I'm using it wrong, but `:$1234` doesn't really do what I want, since it doesn't "scroll" the selected memory dump. And I wanted to got the the address relative to that memory dump.

>VS2017 is not supported, just follow the steps here. You can use the Qt plugin yourself because it just opens the .pro file in Visual Studio as far as I know...

Yeah, I saw that. I'd rather not install VS2013 again (I think I still have a few traces of it left somewhere ;P), and I was hoping that upgrading solutions to the newer toolset/vs would work, but it looks like apart from small problems (like missing proper win sdk include/lib folders) there were also a lot of errors regarding c++ conformance, so I just abandoned the idea. 

Anyway, thanks for the help.

**Comment by mrexodia** [comment]
Yeah file offset definitely doesn't do what you want. You can simulate what
you want by doing "mem.base(dis.sel())+X" but it's probably better to write
a plugin that automatically does that.

I tested visual studio 2015 and 2017 and after upgrading they work quite
good (no conformance issues or anything). There is a branch with a vs2015
solution, but on my PC I have all visual studio versions since 2010
installed and I just use vs2017 with the vs2013 compiler.

**Comment by danilaml** [comment]
@mrexodia hm `mem.base(dis.sel())+X` doesn't seem to do what exactly I want.
I want to be able to move/scroll to/go to the address in the current dump (selected from memory map) at the offset relative to its beginning/base address.
`mem.base(dis.sel())` gives me the address of `ntdll`, while I have `1.exe` dump open.

Btw, in this particular case `1.exe:$1234` seems to calculate the dress that I want, but
  1) I'm not sure how would that translate for other memory map dumps (like `".text"` section)
  2) This doesn't scroll the dump view, so it's a bit useless for me (at least if there is no way to view the current address in the dump view).

> I just use vs2017 with the vs2013 compiler.

Hm. After a bit of struggling and installing some additional old windows SDKs+ MFC I've managed to build x64dbg.

But I had to fix some C++ conformance issues along the way. I'll submit the PR with them shortly.

**Comment by mrexodia** [comment]
`dis.sel()` is the current selection of the disassembler. If you want the current dump selection, use `dump.sel()`

Apart from that I have no clue what you are trying to do and what purpose it serves, perhaps you could explain with some kind of modified screenshot or whatever.

Thanks for the PR I will try to review it soon!

**Comment by danilaml** [comment]
@mrexodia well, I think that `1.exe:$1234` stuff worked fine for me, i.e. it calculated the desired address from offset, BUT - it didn't move/scroll the memory dump I was viewing. 
Basically, I want to be able to navigate memory dump view using something like Go To -> File Offset, but instead of the file offset it'd be RVA.
Because so far, none of the commands had any effect on dump widget. Or maybe I'm using them wrong.

**Comment by mrexodia** [comment]
Okay, so you want the disassembler view and the dump view to be synced with each other if I understand it correctly?

If you want to change the address of just the dump, click in the dump, press ctrl+g, enter an address and press enter. The ctrl+g action depends on the current view (highlighted with a small black border around it).

**Comment by danilaml** [comment]
@mrexodia welp. Now I feel like an idiot. For some reason it didn't appear that the same comands/expression I wrote in the command line would work in a `Ctrl+G` dialog. Well, it's much better now! Would be even nicer, if there was a shortcut to Go To `mod.base(dump.sel()):$x` (i.e. got to the offset of the currently examined module in the dump view), though not sure how helpful that would be for anyone else =)

**Comment by mrexodia** [comment]
For some reason I never responded to this, but as for a shortcut to `mod.base(dump.sel()) + x` you can use `:$x` ([relevant help section](http://help.x64dbg.com/en/latest/introduction/Input.html#rva-file-offset)).
