### ISSUE TITLE
data highlighting (originally by RaMMicHaeL)

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#175]
Also, I thought about the following idea: coloring aligned pointers to code/data in the dump window with pale, non-distracting colors. Example (red is code, green is data):

![Untitled-1.png](https://i.imgur.com/W2aLES0.png)

![img](http://rammichael.com/wp-content/uploads/2015/08/dump_address_color.png)

![http://www.disk-editor.org/images/screens/HexEditor11.gif](http://www.disk-editor.org/images/screens/HexEditor11.gif)

If you like the idea, feel free to create a new enhancement about it, or to implement it right away :)

---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/175
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-08-15T21:45:04.087

**Comment by RaMMicHaeL** [comment]
An OllyDbg 2 plugin implementation:
http://rammichael.com/dumpaddresscolor

I must say that it works pretty well.

I'm not sure that x64dbg has the API to implement it. Does it?

**Comment by mrexodia** [comment]
Nope.. However, these seem like nice options to implement. How did you do
the window handle thing?

**Comment by RaMMicHaeL** [comment]
Simply `IsWindow` + `GetWindowThreadProcessId` :)

**Comment by mrexodia** [comment]
Alright, thanks. I will try to look into it when I can.

**Comment by MoonDoggie42** [comment]
+1 I miss even underlining pointers to addresses in the code section.

On Fri, Aug 28, 2015 at 9:03 AM, Duncan Ogilvie <notifications@github.com>
wrote:

> Alright, thanks. I will try to look into it when I can.
>
> On Fri, 28 Aug 2015 12:49 RaMMicHaeL <notifications@github.com> wrote:
>
> > Simply IsWindow + GetWindowThreadProcessId :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/x64dbg/x64dbg/issues/175#issuecomment-135737340>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/175#issuecomment-135815396>.
>



-- 
-Colin

**Comment by Nukem9** [comment]
Seems like it would be nice to have a color for HANDLE along with the HWND idea.

**Comment by RaMMicHaeL** [comment]
I'm not sure that it's going to work well, because of false positives. For example, I opened a test process, and called `CreateMutexW(0, 0, 0)` multiple times. What I got was:
0x14C, 0x150, 0x154, 0x158, ...
The 0x14C value, for example, can easily be a size of a buffer, and not a Mutex.
It's different with window handles, which are global, [and designed to be more or less unique](http://blogs.msdn.com/b/oldnewthing/archive/2007/07/17/3903614.aspx).

**Comment by mrexodia** [comment]
True, but addresses in code sections can also be false positives.

**Comment by RaMMicHaeL** [comment]
Nice! How do I enable these?
I downloaded the new build, but I see the `7F`/`FF`/`IsPrint` colors instead (which are not so helpful, if you ask me, especially in disassembly).

**Comment by mrexodia** [comment]
I implemented the pointer highlighting as underlines instead of
background...
