### ISSUE TITLE
Crash on Intermodular call lookup from function

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#1752]
- Debugger version: Oct 8, 2017 Snapshot
- Operating system: Windows 10 x64

Brief: x64dbg Crashes when using the Search For-> Current Function -> Intermodular Calls.

Reproducable steps:
(1) Debug any software, use System breakpoint
(2) 'd LdrpInitializeProcess'
(3) analx
(4) Search For -> Current Function -> Intermodular Calls.
(5) crash.

I haven't looked yet at the minidump it generates so I'll upload it here and get to it when I can.
[dump-10102017_1100050823.zip](https://github.com/x64dbg/x64dbg/files/1372402/dump-10102017_1100050823.zip)

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/blob/c5c3358c529c37988991d998bbbe9b2147fa6af4/src/dbg/commands/cmd-searching.cpp#L548
