### ISSUE TITLE
Feat. Req.: Flash Taskbar Icon when Debugger Breaks

### ISSUE THREAD

**Issue by STaRDoGG** [x64dbg/x64dbg#1754]
I'm old school in a way; I used to use SoftICE way back in the day, and whenever a breakpoint would hit, the debugger took back over the screen, so it was easy to see when it hit.

In x64dbg you don't really know that the bpoint hit just by looking at the program. The program just kinda freezes (at least from my little bit of experience with it so far), you just have to know it's going to hit at that time. It'd be great to add in a quick flash of the x64dbg taskbar icon when it hit's a breakpoint. Then you'd immediately see that it broke.

Making it a toggle-able option for those that like it as it currently is, sounds like the best idea.

Any chance of adding this in?

**Comment by mrexodia** [comment]
Uncheck this option:

![](https://i.imgur.com/QWx53u9.png)

**Comment by STaRDoGG** [comment]
@mrexodia, aha! That might do the trick. I must've somehow glossed over that when looking through the options. ty.
