### ISSUE TITLE
race condition with conditional breakpoints

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1764]
1. Place a breakpoint on a function that is called from multiple different threads at the same time
2. Set the breakpoint condition to 0
3. Run, the program will throw an EXCEPTION_BREAKPOINT or EXCEPTION_SINGLE_STEP

**Comment by torusrxxx** [comment]
The problem can be greatly reduced by setting process affinity(use single core).

**Comment by mrexodia** [comment]
Example code (put conditional breakpoint on `increase()` call):

```
#include <Windows.h>

static volatile int gCounter = 0;

extern "C" __declspec(dllexport) void increase()
{
    gCounter++;
}

static DWORD WINAPI ThreadProc(void*)
{
    while(true)
        increase();
    return 0;
}

int main()
{
    CreateThread(0, 0, ThreadProc, 0, 0, 0);
    CreateThread(0, 0, ThreadProc, 0, 0, 0);
    CreateThread(0, 0, ThreadProc, 0, 0, 0);
    ThreadProc(0);
}
```

**Comment by LFriede** [comment]
I don't know if this information is useful for you, but in case it is you know it now ;)
I encountered the same behaviour while trying to log heap frees. Like described in #1245 while bpx is on RtlHeapFree and "Break Condition" = 0 (Log Text was "RtlFreeHeap: {p:esp+c}" at this moment, the other fields are empty) the debugger begins to show EXCEPTION_BREAKPOINT to me.

The thing i noticed additionally is that sometimes it breaks with EXCEPTION_ACCESS_VIOLATION on EIP = RtlFreeHeap+1. Looking with cheat engine at the memory location there is the 0xCC in the right place and the stuff after 0xCC disassembles to a call dword ptr[] to nowhere in my case which is the reason of the access violation.

Second thing is that sometimes it breaks with "Breakpoint not in list" at RtlFreeHeap-1.

Hope this helps =)

**Comment by mrexodia** [comment]
The only possible fix for this issue (that I can see) is to redirect EIP/RIP to a separately allocated section in the debuggee.

The requirement for this is to correctly relocate instructions, which requires quite a significant effort.

It would look like this:

- When writing the 0xCC on the original location, first rewrite the instruction to a code cave, followed by an absolute jump to the instruction after the original one. For many instructions this just means copying, but for example a `call` instruction (or any other instruction related to EIP/RIP for that matter) needs some sort of emulation to work. There is also the challenge of exceptions, because if the debugger observes an exception thrown in this code cave it needs to patch up the `CONTEXT` and do other things to be transparent to the debuggee.
- Once the breakpoint is hit and resumed, change EIP/RIP to the code cave without removing the 0xCC bytes.

This kind of functionality is difficult to implement completely transparently for the debuggee and is not dissimilar to what tools like PIN or DynamoRIO do.

Another attempted solution is to suspend all other threads once a breakpoint is hit, but this does not affect debug events that are already queued, so suspending a thread will (in theory) stop it, but in practice there could already be debug events for those threads in the queue, giving very confusing results.

**Comment by thatreguy** [comment]
I've seen [.bpsync](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-bpsync--synchronize-threads-at-breakpoint-) to work painlessly

**Comment by mrexodia** [comment]
Interesting... I will try to make a standalone example to reproduce the issues I found, because I'm fairly sure calling NtSuspendThread on all other threads didn't work.

**Comment by Mattiwatti** [comment]
Note that freezing a thread != suspending it. I'm very curious how `.bpsync` works because there is no public API (user or kernel) to freeze a thread.

**Comment by flarejune** [comment]
You can try this way,like InlineHook's Trampoline,Example:

005521CD         | A1 78563412                | mov eax,dword ptr [12345678] 
005521D2         | 40                                 | inc eax 
005521D3         | A3 78563412                | mov dword ptr [12345678],eax

Now set the breakpoint at 0x005521CD,the debugger calls the "VirtualAllocEx" API,Within 2GB of the module memory address,Allocate a temporary memory,
copy "A1 78563412| mov eax,dword ptr [12345678]" to temporary memory(need to fix relative address),write to temporary memory(call WriteProcessMemory API):

0600000          | A1 xxxxxxxx                        | mov eax,dword ptr [12345678] 
0600005          | E9 xxxxxxxx                         |  jmp 0x005521D2

When the trigger breakpoint at 0x005521CD, do not restore the "0xCC" command of 0x005521CD,When the thread wants to resume running, set RIP = 0066000 (call SetThreadContext API) and continue running.

This is the only way to resolve thread concurrency

**Comment by torusrxxx** [comment]
https://github.com/x64dbg/GleeBug/pull/63 can be used to implement a code cave to make your breakpoint thread-safe.

**Comment by tylermasci16** [comment]
I im affected

**Comment by mrexodia** [comment]
https://github.com/x64dbg/TitanEngine/pull/9 This fixes the issue (but gives you the wrong suspend count while paused).

**Comment by huyi51462** [comment]
Using the 'pause' can also cause similar problems. This is because the first callback that hits a 'pause' breakpoint will remove that breakpoint. Any later exceptions will then throw a '#bp' error because they can't find a matching breakpoint. Even if it doesn't throw a '#bp' error, it can still lead to unpredictable issues due to the rip not being adjusted correctly. For example, this could cause it to point to an 'int 2e' instruction right after the 'syscall ret' in a wait function.I thought about it and didn't know how to solve this problem.

**Comment by huyi51462** [comment]
Using the 'pause' can also cause similar problems. This is because the first callback that hits a 'pause' breakpoint will remove that breakpoint. Any later exceptions will then throw a '#bp' error because they can't find a matching breakpoint. Even if it doesn't throw a '#bp' error, it can still lead to unpredictable issues due to the rip not being adjusted correctly. For example, this could cause it to point to an 'int 2e' instruction right after the 'syscall ret' in a wait function.I thought about it and didn't know how to solve this problem.
