### ISSUE TITLE
Program crashes when clicking on CPU view (packed binary)

### ISSUE THREAD

**Issue by xarkes** [x64dbg/x64dbg#1768]
- x64dbg 14 Oct 2017
- Windows 7 SP1
- x64dbg crashes when clicking on the CPU view after the program reached some point.
- Open the linked binary in x32dbg, move to breakpoint view, continue the program until it reaches EP, then click on CPU view.
- Binary: [vkq.zip](https://github.com/x64dbg/x64dbg/files/1392023/vkq.zip) (Password: infected)
It should not be harmful to your computer, but we never know.

**Comment by mrexodia** [comment]
appears to work fine here... try https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2017-10-16_20-08.zip (we just switched disassembly engines and some bugs were fixed)

**Comment by xarkes** [comment]
Ah yes, no problem anymore! Thanks!
