### ISSUE TITLE
"Failed to write file" when dumping memory to file

### ISSUE THREAD

**Issue by qwerty245** [x64dbg/x64dbg#1778]
Hello, all.
I have recently started using x64dbg. I have a file named "sample.exe", written in C++. Here is the source code, if it helps.

```
#include <iostream>

using namespace std;

int main(){
	int input;
        cout << "Please enter key...\n" << endl;
	cin >> input;
	if (input == 55){
		cout << "Correct!" << endl;
	}
	else{
		cout << "Incorrect!" << endl;
	}
}
```

I am trying to dump the memory located in the .text section. For reasons which I am unaware of, whenever I try to dump memory through the memory map to a .bin file, the result always ends up being that nothing happens and I am given an error that simply states "failed to write file" located at the bottom of the window.
I am at a loss as to what causes this. I am using the latest version of x64dbg, I run it as an administrator, and it does not matter what executable I try this on or what section is dumped, it always results in the same error.
Any help would be appreciated, thanks.

**Comment by rmbreak** [comment]
I had this problem with snapshot_2017-10-30_01-05.zip but not when I compile from source at 9c639ddc5fb41973ea5f42fb4fea412aaf12acf1.

**Comment by qwerty245** [comment]
Unfortunately the newest snapshot, snapshot_2017-11-04_21-36.zip, which includes the change made at 9c639dd, doesn't fix the issue.

**Comment by mrfearless** [comment]
what folder is x64dbg being executed from? and where are you dumping the .bin file to? and what OS are you using? any AV products? could be OS or AV preventing writing. Also when you downloaded the snapshot was it unblocked (right click, properties, unblock file that was downloaded from internet)

**Comment by rmbreak** [comment]
@qwerty245 did your save path have a `\n` anywhere, such as `C:\Users\Desktop\Me\nogood.bin`? This was the issue for me. I mistakenly thought building from source fixed it because I tried saving a memory mapping to a valid file path.

**Comment by mrexodia** [comment]
Hmmm, super derp there 😕

**Comment by qwerty245** [comment]
@rmbreak There it is, that was the problem. Thank you so much!
