### ISSUE TITLE
cannot print the close parenthesis

### ISSUE THREAD

**Issue by IceAmber** [x64dbg/x64dbg#1791]
Examples of good issues:

the bug as follow, the close parenthesis cannot print in the register st(0)

fld st(0
sub esi,ecx
fld1 
sub edi,ecx
fld st(0
sub ebp,ecx
fsubrp st(2)
sub edx,ecx
fld dword ptr ss:[esp+48]
fld st(0
fsubp st(2)
fld st(1)
fmul st(3)
fld st(4)
fmulp st(3)
fld st(1)
fmulp st(4)
fxch st(4)
fmulp st(1)

**Comment by mrexodia** [comment]
Which x64dbg version?

**Comment by IceAmber** [comment]
so sorry that the version is a little bit old, the bug has fixed in the newest version
