### ISSUE TITLE
References tab not following the address on double-click

### ISSUE THREAD

**Issue by reliasn** [x64dbg/x64dbg#1794]
[Video showing the problem](https://sendvid.com/0dq4rmj8)

Steps to reproduce it:
1 - CTRL+B to search for a binary pattern. In the example of the video, ``F3 A4`` was used.
2 - Results are shown in the "References" tab.
3 - Double-click one of the results.
4 - x32dbg doesn't follow the address in the "CPU" tab. If you right-click and select "Follow disassembler", it works.

Unless I'm using the debugger incorrectly, I suppose this is not intended.

**Comment by mrexodia** [comment]
It probably follow the reference in the dump window.

**Comment by mrexodia** [comment]
Just watched the video and that is definitely what happened. This keeps popping up so I think it is a good idea to somehow attract the user's attention to the fact that the stuff was followed in dump instead of the disassembler...

**Comment by mrfearless** [comment]
Not sure if its possible with the qt widgets, but maybe flash the border of the dump, alternate colors red-black-red-black for 1 second if follow dump=true, or the background of the dump tab itself (red background, white text / normal background, normal text)

**Comment by mrexodia** [comment]
Currently the border of the dump is flashed 😄 flashing the background is a good idea though!

**Comment by torusrxxx** [comment]
Create a short scrolling animation

**Comment by torusrxxx** [comment]
Please open a separate issue
