### ISSUE TITLE
Fix enum symbol bug

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1795]
when import/export symbol have ordinal function, it will stop enum after ordinal function, this code fix this:
in ‪src\dbg\addrinfo.cpp:
in bool apienumimports(duint base, const IMPORTENUMCALLBACK & cbEnum):
```

        // Loop through all imported function in this dll
        while(imageFtThunkData.u1.AddressOfData)
        {
#ifdef _WIN64
            if (imageOftThunkData.u1.Ordinal & IMAGE_ORDINAL_FLAG64)
            {
                size_t ord = IMAGE_ORDINAL64(imageOftThunkData.u1.Ordinal);
#else
            if (imageOftThunkData.u1.Ordinal & IMAGE_ORDINAL_FLAG32)
            {
                size_t ord = IMAGE_ORDINAL32(imageOftThunkData.u1.Ordinal);
#endif
                sprintf_s(importName(), MAX_IMPORT_SIZE, "#%u", ord);
            }
            else
            {
                pImageImportByNameVa = (PIMAGE_IMPORT_BY_NAME)(base + imageOftThunkData.u1.AddressOfData);

                // Read every IMPORT_BY_NAME.name
                duint bytesRead = 0;
                if (!MemRead((duint)pImageImportByNameVa + sizeof(WORD), importName(), MAX_IMPORT_SIZE, &bytesRead) && !bytesRead)
                    return false;
            }

            // Callback
            cbEnum(base, (duint)imageIATVa, importName(), importModuleName);
```

**Comment by mrexodia** [comment]
Thanks! I will try to integrate it soon.

**Comment by lynnux** [comment]
@mrexodia , you may miss using IMAGE_ORDINAL to get the ordinal value:
current:
![1](https://user-images.githubusercontent.com/367894/32827311-ad636c76-ca26-11e7-866a-d18e774d4e64.png)
in IDA:
![2](https://user-images.githubusercontent.com/367894/32827327-ba5b1a5a-ca26-11e7-805a-5ff8bce0cddc.png)
by the way, it would be better if showing the name of the ordinal function when it has a name, you can display it at 'Symbol (undecorated)'  column.

**Comment by mrexodia** [comment]
Oh yeah you’re right I forgot to remove the flag 😅

**Comment by mrexodia** [comment]
Okay fixed that part, perhaps we should open a new issue for displaying the address label/symbol if one exists?

**Comment by lynnux** [comment]
@mrexodia , it's may not easy to handle this, right now is just fine. I tested IDA, if common.dll not exsit will show:
![2](https://user-images.githubusercontent.com/367894/32868958-7f11cc30-caaf-11e7-9b5b-10319c00d15d.png)
if there exsits common.dll:
![1](https://user-images.githubusercontent.com/367894/32868979-980e2fc6-caaf-11e7-941b-c6e1e0a9210b.png)
right now in x64dbg, the first column has a hint:
![3](https://user-images.githubusercontent.com/367894/32827311-ad636c76-ca26-11e7-866a-d18e774d4e64.png)
the only fault is that it can't be searched by filter

**Comment by mrexodia** [comment]
Hm, actually the first column not being searchable is an artifact from when
labels were not showm there yet... but I think a better solution is to
display the full dll + import name/demangled name in the undecorated column
instead of adding more hacks :)
