### ISSUE TITLE
[Debug]Breakpoint display type error

### ISSUE THREAD

**Issue by nihuai** [x64dbg/x64dbg#1800]
In memory layout：Sets the memory execution breakpoint.
Breakpoints window：Memory execution breakpoints are shown as access breakpoints.
Should display: execute.
I have changed the title and content.
The previous problem was my system went wrong.

**Comment by torusrxxx** [comment]
只支持读写、写入和执行内存断点，不支持仅读取断点

**Comment by mrexodia** [comment]
I think in GleeBug there is support for all the combinations but obviously not yet tested properly.
