### ISSUE TITLE
"Breakpoints reached not in the list!" if set Break Condition to "0"

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1801]
On win7 x64, take notepad.exe for example (both 32 and 64 bit vesion of notepad encountered the same problem), F2 set breakpoint on kernel32.HeapAlloc, then <Alt+B> in breakpoints view, <CTRL+E>edit the breakpoints, set Break Condition to "0", save and press F9 to run,  in the gui of notepad, press <CTRL+O> to select file, the debugger will stop and you will get "Breakpoints reached not in the list!" in the status bar. 
![qq 20171106114401](https://user-images.githubusercontent.com/367894/32424540-0fb4cf6e-c2e8-11e7-8bff-d19ac5ffb0f6.png)

After some code review, I think it would be a bug in TitanEngine.

**Comment by torusrxxx** [comment]
see also #1764

**Comment by lynnux** [comment]
ok, I close the issure due to dumplicate [#1764](https://github.com/x64dbg/x64dbg/issues/1764)

**Comment by mrexodia** [comment]
If you have more ideas on how to fix this they are welcome. I think I
handled everything correctly in GleeBug, but it still happens there.

**Comment by lynnux** [comment]
@mrexodia , that's strange. I tested Shift+F4 in ollydbg, it still got error, but the error is single step event at the line below the original condition breakpoint.
![qq 20171106163822](https://user-images.githubusercontent.com/367894/32432048-f4c10a28-c310-11e7-9bb4-0bc3b79f7980.png)
I don't know how conditon breakpoints are implemented, just reached the breakpoint then check condition and resume run(if result of condtion is false)?

**Comment by mrexodia** [comment]
Yes, OllyDbg has exactly the same bug I think it's because debug events are not always delivered in order.

**Comment by mrexodia** [comment]
Oh lynnux forgot to mention that the same that happens in olly can also
happen in x64dbg but with less likelihood.
