### ISSUE TITLE
Import from which hint in symbol view

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1804]
Currently, imported functions showed in symbol view lack the dll name:
![1](https://user-images.githubusercontent.com/367894/32528098-16a2cecc-c46c-11e7-9cb4-26d548910518.png)
If I want to know where it import from, I must double click the line and turn into CPU view, and finally know where it import from:
![2](https://user-images.githubusercontent.com/367894/32528139-427ede82-c46c-11e7-8503-26b1ce7da4de.png)
in ollydbg, it show this:
![3](https://user-images.githubusercontent.com/367894/32528182-94b63e7a-c46c-11e7-8421-91c6ec78e177.png)
At first, I think we can change to first column from "00B613FC <notepad.&VerQueryValueW>" to "00B613FC <version.VerQueryValueW>", but after some code review, I find out the implement is in SearchListViewTable::paintContent, it's may not easy to achieve this.
So my second plan is out, can we add dll name after "Import"? like this:
![4](https://user-images.githubusercontent.com/367894/32528451-12230b6c-c46e-11e7-959a-7f54b01c7e6c.png)
It's may better than add the dll name in front of fuction name.

**Comment by mrexodia** [comment]
We could use the “unmangled name” column... or simply name them “dll:api”
instead of “api”

**Comment by lynnux** [comment]
but if I want to sort by dll name, mean while not missing the function sorting by function name

**Comment by mrexodia** [comment]
I think if you have 'Symbol' to be the same as now, 'Symbol (undecorated)' can be 'DLL + symbol' perhaps? Right now the sorting on that is useless anyway...

Your idea could also work by adding the DLL to the 'Type' column but that doesn't feel very clean either. We can also change the behavior to be the same as olly and if people want to find all imports from a specific DLL they can just type 'kernel32' in the search to filter all the other things out.

**Comment by lynnux** [comment]
yes, you can have 'DLL + symbol' like in ollydbg, just implment as you wish :)
One more feature request: if 'Symbol (undecorated)'  can unmangle the symbols of gcc functions, that would be awesome.

**Comment by lynnux** [comment]
@mrexodia ,  a new demangler library from avast https://github.com/avast-tl/demangler

**Comment by mrexodia** [comment]
Hm, the demangler could be great. Thanks!

**Comment by torusrxxx** [comment]
Add the module name into symbol type, so it looks like "Import from kernel32.dll". It doesn't break current sorting functionality.

**Comment by twifty** [comment]
Any updates on this?

**Comment by torusrxxx** [comment]
#2634
