### ISSUE TITLE
Anyone want <CTRL+TAB> working like OD or Qt Creator or Visual Studio?

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1805]
I feel very comfirtable with the way that <CTRL+TAB>/<CTRL+SHIFT+TAB> working in ollydbg, and not get used the way in x64dbg, although there are enough shortcuts to quickly locate the view where I cared.
After some search, I decide to stole code from the source code from qt creator, and it's almost done:
![1](https://user-images.githubusercontent.com/367894/32537167-9233ad42-c49c-11e7-8e1e-dcbdfab46476.png)
althrough it's just a demo, but can be very quickly integrated in x64dbg, there is only one thing that should take care of is the MHDetachedWindow.

**Comment by mrexodia** [comment]
I don't see the difference between OllyDbg and x64dbg? For Olly it goes to the next window (whatever that means), in x64dbg it goes to the next tab (exactly like chrome).

Another idea is to maybe steal Ctrl+Shift+P from sublime text (something like this: https://github.com/TheCrazyT/x64dbg-plugin-quickaccess) and allow people to search the view they want by name.

**Comment by mrexodia** [comment]
Perhaps @Atvaark has an opinion on this since he implemented Ctrl+Tab in the first place 😄

**Comment by lynnux** [comment]
Yes, currently x64dbg goes the way like chrome, but in ollydbg Ctrl+Tab goto previous popuped window(like the detached window inx64dbg) in history stack. Consider the scenario: I press CTRL+R on a address in CPU, it turns into reference view, if I can't find any useful information, then I should go back, in olly it's just Ctrl+Tab, in x64dbg there has a shortcut for CPU view is Alt+C. But if the previous view is not CPU view, then I should recall where the view I come from, and trigger the corresponding shortcut?

**Comment by lynnux** [comment]
Should close now, implement at pull [1807](https://github.com/x64dbg/x64dbg/pull/1807)

**Comment by mrexodia** [comment]
Will be closed when #1807 is merged
