### ISSUE TITLE
Api Break for x64dbg

### ISSUE THREAD

**Issue by yolnud** [x64dbg/x64dbg#1821]
version
OS : windows 10 64bit
x32dbg : Nov 20 2017

I can't get the plugin, Api Break for x64dbg to show up under plugins menu?  All other plugins show up just fine.

Thanks.

**Comment by mrfearless** [comment]
Is it in the x32\plugins (x64\plugins for .dp64) folder?
Has it been unblocked from internet download (win7 shows an unblock button on right click->properties dialog with a msg "this file came from another computer and might be blocked to help protect this computer" - might be different settings for win10 or different way of handling this)

**Comment by amandinus** [comment]
Same matter with me.
OS: windows 10 64 bits family.
x32dbg or x64dbg do not show the plugin apibreak in the plugin menu.
I only see scyllahide (+scylla of course )that has been installed and work perfectly.
