### ISSUE TITLE
x64Dbg crashing

### ISSUE THREAD

**Issue by zashraf1337** [x64dbg/x64dbg#1828]
Hello,

When I take a snapshot during a debgging session in a windows 7 x86 VM using VMWARE Fusion for MAC, x64dbg usually crashes with following stack in windbg.

*** wait with pending attach
Symbol search path is: symsrv*symsrv.dll*Z:\downloads\Windows_dbg_symbols
Executable search path is: 
ModLoad: 00fd0000 00fe0000   Z:\MalwareAnalysisToolsOnlyRunInVMs\x64_debug_snapshot_2017-11-30_20-27\release\x32\x32dbg.exe
(d10.8bc): In-page I/O error ffffffffc000035c - code c0000006 (!!! second chance !!!)
eax=547490f0 ebx=0023d401 ecx=000003a9 edx=00000000 esi=00000753 edi=00000000
eip=77738b15 esp=002210e0 ebp=0022111c iopl=0         nv up ei pl nz na pe cy
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010207
ntdll!RtlIsValidHandler+0x54:
77738b15 8b3c88          mov     edi,dword ptr [eax+ecx*4] ds:0023:54749f94=????????

0:000> k
```
ChildEBP RetAddr  
0022111c 77738a74 ntdll!RtlIsValidHandler+0x54
0022119c 777560f7 ntdll!RtlDispatchException+0x10e
0022119c 77738b15 ntdll!KiUserExceptionDispatcher+0xf
002214f4 77738a74 ntdll!RtlIsValidHandler+0x54
00221574 777560f7 ntdll!RtlDispatchException+0x10e
00221574 77738b15 ntdll!KiUserExceptionDispatcher+0xf
002218cc 77738a74 ntdll!RtlIsValidHandler+0x54
0022194c 777560f7 ntdll!RtlDispatchException+0x10e
0022194c 77738b15 ntdll!KiUserExceptionDispatcher+0xf
00221ca4 77738a74 ntdll!RtlIsValidHandler+0x54
00221d24 777560f7 ntdll!RtlDispatchException+0x10e
```

Then, make sure the following points are included in your issue:

- Debugger version (can be found on right hand side of menu bar of debugger).
Nov 28 2017
- Operating system version and Service Pack 
   Win 7 - x86 - sp1

**Comment by mrexodia** [comment]
I suspect this is a bug in vmware, not x64dbg. Similarly to wine I don’t plan to support simulated environments...
