### ISSUE TITLE
Plugin Deinitialization Error

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#1830]
Hello everybody,

x64dbg always crashes if you try to exit the debugger, provided that a code was called from the plug-in, which was not completed before the x64dbg closing, for example a simple messagebox, the message is not closed, because it is hidden behind the debugger window, when you exit the debugger, at first sight debugger successfully closed, but the message from the plugin becomes visible, and when you press ok, the debugger crashes with an error.

Unhandled exception at 0x00007FFD140B1100 in x64dbg.exe: 0xC0000005: Access violation executing location 0x00007FFD140B1100.

The test was on the last build. This behavior can be repeated on any plug-in with messagebox. 

Thank you for your work.

**Comment by UnlimitedChild** [comment]
Did not notice a similar theme, but this topic applies to any plug-in in the pool. Crash Bug - Plugin handling related https://github.com/x64dbg/x64dbg/issues/1818

**Comment by mrexodia** [comment]
Plugins should handle this during plugstop, there is no way for me to tell that there is a return address to an unloaded module in a thread somewhere...
