### ISSUE TITLE
How to edit a hwd bp only if address is not in the list?

### ISSUE THREAD

**Issue by andresantacruz** [x64dbg/x64dbg#1832]
Hi,
As the title states is there a way to edit a hwd bp (or other type of bp) to only hit if the hit address don't is in a address list?

Thanks.

**Comment by mrexodia** [comment]
What kind of address list are you talking about? You can edit the [breakpoint condition](http://help.x64dbg.com/en/latest/introduction/ConditionalBreakpoint.html) to something like `eip != 0x12345678` to ignore the breakpoint on a specific address.

**Comment by andresantacruz** [comment]
@mrexodia I mean some kind of feature that prevents a bp from hitting at some addresses. I was looking for some plugin that could present some alternative to the conditional break box as it is not that practical in my case as I have a bp that hits in very much different addresses.

**Comment by torusrxxx** [comment]
https://github.com/torusrxxx/addressbook
