### ISSUE TITLE
evaluation of logical operations

### ISSUE THREAD

**Issue by zashraf1337** [x64dbg/x64dbg#1834]
Hello,

```
0 && dword:[0x4]
```
results in 

```
Failed to read memory
Unknown command/expression: "0 && dword:[0x4]"
```

I would expect it to not evaluate `dword:[0x4]`

Use case: e.g. it can be used in conditional breakpoints.

**Comment by mrexodia** [comment]
duplicate of https://github.com/x64dbg/x64dbg/issues/931

**Comment by yiivon** [comment]
I wanna implement this logical issue, think about that how x64dbg could filtering LVN_GETDISPINFO out of WM_NOTIFY like as `arg.get(1) == 0x4e && ([arg.get(3)+8]==0xFFFFFF6A || [arg.get(3)+8]==0xFFFFFF4F)`
