### ISSUE TITLE
FPU registers in x64

### ISSUE THREAD

**Issue by jin-x** [x64dbg/x64dbg#1837]
x64dbg snapshot_2017-12-08_03-24
Win 7 x64 Ult

x64 shows FPU registers very strange
Compare the following 2 videos with the same code on 32-bit and 64-bit mode.
32-bit mode: https://cloud.mail.ru/public/6t97/k4UBAUPZw (everything is OK)
64-bit mode: https://cloud.mail.ru/public/Hooy/J1YwektT9 (strange data)

The code is written on Delphi but I attach for you FASM examples too with no any runtime init code – the result the same, I've checked. You can try yourself...

[example.zip](https://github.com/x64dbg/x64dbg/files/1559067/example.zip)

**Comment by jin-x** [comment]
And one more wish: pleeeeeeeeease make the ability to sort FPU registers by logical names (ST0, ST1, ST2...) instead of physical (x87r0, x87r1, x87r2...).

**Comment by mrexodia** [comment]
Confirmed this bug and working on a fix now.

**Comment by mrexodia** [comment]
A fix is pending on my local branch, for now you can try replacing your x64 TitanEngine.dll with [this one](https://github.com/x64dbg/deps/raw/c233bad3accf9dd90fb7c068308258c9bf914c8c/x64/TitanEngine.dll).

**Comment by mrexodia** [comment]
Oh and thanks for your great reproduction steps!
