### ISSUE TITLE
Application crashes on breakpoint

### ISSUE THREAD

**Issue by rokups** [x64dbg/x64dbg#1840]
For some strange reason when breakpoint is hit this one application crashes. Application window shows that windows dialog saying "Application has been closed". Application is built probably 5 years ago or more and protected with winlicense.

- Debugger version: Nov 28 2017
- OS: Windows 10 x64 LTSB
- ScyllaHide options:
  - Hide from PEB (all checked)
  - OutputDebugStringA
  - NtClose
  - Normal injection
  - Unload after DllMain

In order to reproduce:
1. Download game client: http://download.l2shrine.com/LineageIIInstaller-Epilogue.zip (5GB download, sorry!)
2. Download game launcher and put into game dir: https://update.l2shrine.com/L2%20Shrine.exe
3. Run launcher and update
4. Run game
5. Attach x64dbg to l2.exe process. Sometimes process crashes on attaching and i have to retry few times.
6. Put breakpoint on recv()
7. Enter any credentials and try to log in.

Breakpoints work (at least at entry point) when application is started straight in x64dbg. It is unclear if starting application straight in the debugger fixes the issue as Winlicense terminates application before login can be attempted.

**Comment by mrexodia** [comment]
Does the debugger crash? If not there is nothing that can be done, probably their kernel mode anti cheat is doing something crazy.

**Comment by rokups** [comment]
Debugger does not crash. Application is debuggable under windows XP with 
ollydbg + some plugins too.

**Comment by cexer** [comment]
> For some strange reason when breakpoint is hit this one application crashes. Application window shows that windows dialog saying "Application has been closed". Application is built probably 5 years ago or more and protected with winlicense.
> 
> * Debugger version: Nov 28 2017
> * OS: Windows 10 x64 LTSB
> * ScyllaHide options:
>   
>   * Hide from PEB (all checked)
>   * OutputDebugStringA
>   * NtClose
>   * Normal injection
>   * Unload after DllMain
> 
> In order to reproduce:
> 
> 1. Download game client: http://download.l2shrine.com/LineageIIInstaller-Epilogue.zip (5GB download, sorry!)
> 2. Download game launcher and put into game dir: https://update.l2shrine.com/L2%20Shrine.exe
> 3. Run launcher and update
> 4. Run game
> 5. Attach x64dbg to l2.exe process. Sometimes process crashes on attaching and i have to retry few times.
> 6. Put breakpoint on recv()
> 7. Enter any credentials and try to log in.
> 
> Breakpoints work (at least at entry point) when application is started straight in x64dbg. It is unclear if starting application straight in the debugger fixes the issue as Winlicense terminates application before login can be attempted.

hi @rokups , i also encounterd the same issue.  did you figure it out , how to avoid this ?

**Comment by rokups** [comment]
I didnt. Moving on is a best way to avoid this :trollface:

**Comment by cexer** [comment]
> I didnt. Moving on is a best way to avoid this :trollface:

Sad story ……
