### ISSUE TITLE
How to load function analysis from IDA to x64dbg?

### ISSUE THREAD

**Issue by andresantacruz** [x64dbg/x64dbg#1842]
Hi,

Is there a way to load function analysis done in a binary from IDA to x64dbg?

I found the x64dbgida.py script but it don't export functions informations.

Thanks.

**Comment by stonedreamforest** [comment]
https://github.com/a1ext/labeless

**Comment by andresantacruz** [comment]
Hi @stonedreamforest I'll take a look at this plugin. However in the github page I didn't find nowhere saying it imports function analysis to x64dbg. It only says that it sync function names. Do you use this plugin? Thanks.

**Comment by stonedreamforest** [comment]
Seamless synchronization of **labels**, **function names**, **comments** and **global variables**

**Comment by andresantacruz** [comment]
Yes, but what I need is the function analysis data as function start/end, etc. You know if this plugins imports it?

**Comment by blaquee** [comment]
Are you seeing discrepancies in the function analysis of x64dbg vs IDA? You can define these through the debugger manually too. Also, the plugin https://github.com/ThunderCls/xAnalyzer provides additional analysis that might fit your needs.
