### ISSUE TITLE
semantic tracing and trace replayer

### ISSUE THREAD

**Issue by MerovingianByte** [x64dbg/x64dbg#1845]
It would be great if we could have something like [this](https://www.youtube.com/watch?v=JDybqYzNd8k), combined with [IDA's trace replayer](https://www.hex-rays.com/products/ida/support/tutorials/replayer/trace_replayer.pdf). I think it's more of an idea for a plugin, but it would be great if it shipped as a default plugin for x32dbg.

**Comment by mrexodia** [comment]
See the trace tab.

**Comment by MerovingianByte** [comment]
trace tab? I'm going to download the current version. I can't find any trace tab here.

**Comment by mrexodia** [comment]
no for that you go in 'trace -> trace into'

**Comment by mrexodia** [comment]
Not sure what's left to be done here. You can record a trace (albeit a little clunky at times) and see the executed instructions. You can also use trace record to highlight the graph/disassembly.

**Comment by brandonros** [comment]
What do you do if you execute the same program 2 different times 2 different ways and you want to compare subtle differences in trace?

**Comment by torusrxxx** [comment]
A dedicated trace diff program that reads 2 trace32 files would be nice, but that might better be a separate program that is only run when you need it, not bundled in x32dbg and hence gets loaded every time. Also anyone can already compare 2 trace32 files by copying them as text and then use a text diff program.
