### ISSUE TITLE
First chance exception on 00007FFA345D3FB8 (E06D7363, CPP_EH_EXCEPTION)

### ISSUE THREAD

**Issue by Jasi2169** [x64dbg/x64dbg#1846]
Before submitting an issue, make sure it has not already been reported.

Then, make sure the following points are included in your issue:

- Dec 20 2017
- Windows 10 Enterprise x64
- First chance exception on 00007FFA345D3FB8 (E06D7363, CPP_EH_EXCEPTION)
- when i run the target the app ,it keeps pausing and showing same error i reported,so there loading icon keeps loading on the target app,no way to debug it

PS after a more than 1 and half year i touched x64dbg today

**so i just want to know what this issue actually means and when this exception is raised ?**

**Comment by mrexodia** [comment]
It is not an issue, just the c++ app throwing exceptions and handling them (for example because it cannot connect to a website or any other error state). Just press shift+f9 to automatically continue on first chance exceptions.
