### ISSUE TITLE
Address in "Follow in ..." are wrong

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#1849]
![1](https://user-images.githubusercontent.com/367894/34356025-e635fcbc-ea74-11e7-891e-27a17b3bee15.png)

Seems relative jmp/call instructions are wrong.

**Comment by mrexodia** [comment]
ping @athre0z

**Comment by mrexodia** [comment]
Hm, it appears to correctly follow the address, just `arg.mnemonic` is not what you would expect it to be...

**Comment by athre0z** [comment]
It's for this case:
https://github.com/zyantific/zydis/blob/master/include/Zydis/Utils.h#L59
