### ISSUE TITLE
Reusing shortcuts  “ctrl + f2” and “alt + f2” causes the crash

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1852]
os：win7 64
x64dbg：snapshot_2017-12-26_13-39

1. Drag a exe to debug, Enable entry breakpoint
2. use alt+f2  and ctrl +f2(or Drag exe again )
3. Repeat step 2

**Comment by Mattiwatti** [comment]
Check out #1863, pretty sure you're having the same issue.

**Comment by karimzahriya** [comment]
What’s up fam

**Comment by marndt93** [comment]
hey guys, how's your day been?

**Comment by DeadPackets** [comment]
My day sucks Ive been screaming at XCode for the past few hours. Anyway,
does anyone have an explanation to why Im suddenly subbed to this repo?

**Comment by lsq126** [comment]
suck my dick

**Comment by lsq126** [comment]
suck my d1ck

**Comment by lotzewing** [comment]
Why am I subscribed to this these random Xcode threads?
  

  
  

  
  
>

**Comment by rsisto** [comment]
No idea, I'm trying to unsubscribe but it doesn't seem to be working

<http://kreitech.io>

**Comment by Carnicero** [comment]
i have already tried to unsub but i keep getting this emails

2018-01-22 11:42 GMT-02:00 Rafael Sisto <notifications@github.com>:

**Comment by milorules1012** [comment]
This is the 5th respiratory  that GitHub has claimed I am subscribed to,
when I am not.

I hate to be a bother and contribute to the current unwanted situation I
think everyone is in, but does anyone know what is going on and how to fix
this?
I am not seeing anything online about this...

**Comment by haikalganteng** [comment]
hi guys
I don't know what I'm doing here btw

**Comment by mrexodia** [comment]
Everybody who is still subscribed to this and doesn't know why: **change your password**. You will not see anything in your audit log, but your credentials were used in a Github API call to subscribe to this repo.

**Comment by wadeal** [comment]
How about GitHub fix their fucking shit?

Until then

Fuck off
