### ISSUE TITLE
BND RET

### ISSUE THREAD

**Issue by dhucul** [x64dbg/x64dbg#1856]
BND RET popping up in assemble code.  Invalid instruction?

**Comment by mrexodia** [comment]
Could you give the bytes of where this happens?

**Comment by mrexodia** [comment]
It is a valid instruction: https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol1/o_7281d5ea06a5b67a-398.html

**Comment by dhucul** [comment]
Thanks for the link.
