### ISSUE TITLE
Goto expression Rva

### ISSUE THREAD

**Issue by DwordXor** [x64dbg/x64dbg#1857]
Hello x64dbg Team

Is it possible to a function in Expressions dialog a option jump to rva like Olly advanced?

Greets,

**Comment by mrexodia** [comment]
Yes, read the introduction of the help.

**Comment by DwordXor** [comment]
Hello  mrexodia 

I have read the introduction of the help but i cannot found it

Can you explain me how i can jump with rva?

**Comment by mrexodia** [comment]
http://help.x64dbg.com/en/latest/introduction/Input.html

**Comment by DwordXor** [comment]
Thanks

CTRL+G Module:$rva works ,but better is in Expressions dialog a radio button like Olly Advanced or Scyllahide .

Regards,

**Comment by mrexodia** [comment]
Feel free to write a plugin with a goto dialog that works better for you...

**Comment by garbb** [comment]
for current module, ":$<RVA>" works for me
ex: ":$19AD0A"
