### ISSUE TITLE
How to save?

### ISSUE THREAD

**Issue by trollmad3** [x64dbg/x64dbg#1861]
I litterally looked in all of the menus and cant find a **SAVE** button. If you know please tell me.

**Comment by mrexodia** [comment]
What do you want to save?

**Comment by trollmad3** [comment]
A .exe I recently modified. (I added breakpoints to it)

**Comment by Nukem9** [comment]
`File` > `Patch files... (or Ctrl+P)` > `Select All` > `Patch File`

**Comment by mrexodia** [comment]
Your breakpoints, comments, labels, etc will be saved automatically when you close the debuggee. If you want to save your modifications to the program (patches) you can do as stated above.

**Comment by trollmad3** [comment]
I clicked patch file and nothing happed.  
![image](https://user-images.githubusercontent.com/7843719/34636398-e9a99522-f265-11e7-9502-baef9bf880ea.png)

**Comment by Wheel-Of-Fate** [comment]
> I clicked patch file and nothing happed.
> ![image](https://user-images.githubusercontent.com/7843719/34636398-e9a99522-f265-11e7-9502-baef9bf880ea.png)
sorry to bump this old issue but i have found the solution "Don't Modify the executable in the same place where all the its dependencies are located"
in other word "copy the executable to blank place like new folder" and the changes shall appear i don't know why that works but it does

**Comment by Inf0Junki3** [comment]
> `File` > `Patch file... (or Ctrl+P)` > `Select All` > `Patch File`

I have a strange issue with this, actually. I open up and patch my binary, no problem there. Run the above. When I save to a new .exe file, I get `11/519 patch(es) applied!`. I figured out that x64dbg views continuous patches as a single patch, so it's confusing but OK, workable... However, my "patched" binary is unchanged. Looking at the differences with a tool like winmerge, I should see some 500 odd bytes difference between the original and the patched binary; instead, the only difference I see is 5 spaces.

Any recommendations? Any advice appreciated!

**Comment by ldh0227** [comment]
I test patch HashMyFiles.exe's Window Text HashMyFiles to MaroMyFiles and it works.
![image](https://user-images.githubusercontent.com/946434/71393525-467c1e80-2650-11ea-8127-4c527c673b6a.png)
![image](https://user-images.githubusercontent.com/946434/71393556-67dd0a80-2650-11ea-9845-6ed47ca9a48d.png)

Following is my instruction.
1. x64dbg open hashmyfiles.exe and run until not break.
2. find "HashMyFiles" text on memory
3. on memory dump "Edit (Ctrl+E" to patch text.
4. File > Pathch file... (or Ctrl+P) > Select All > Patch File
5. on Dialog I make copy hashmyfiles.exe becuase keep original. and Select hashmyfile - copy.exe

![image](https://user-images.githubusercontent.com/946434/71393642-e043cb80-2650-11ea-9de8-a08e0bfeedbb.png)

I hope this helps.

**Comment by ravi9798** [comment]
![image](https://user-images.githubusercontent.com/55943437/80732099-7456ff80-8b29-11ea-9d67-e8212045af7e.png)

this is shown when i try to run the patch file of any software. please help me what should i do..???

**Comment by mrexodia** [comment]
Those counts are not combined. If not all of the patches (amount of bytes
patched) are done that means you are likely patching outside of the image.

If x64dbg is not elevated you cannot save to program files. If you enabled
smartscreen those settings will work, it’s unrelated to x64dbg.

**Comment by korewatori** [comment]
> I clicked patch file and nothing happed.
> ![image](https://user-images.githubusercontent.com/7843719/34636398-e9a99522-f265-11e7-9502-baef9bf880ea.png)

currently having this issue again. sorry to bump this almost-year old issue but I don't think a clear solution to this was ever posted

**Comment by Tzvisapp** [comment]
> > I clicked patch file and nothing happed.
> > ![image](https://user-images.githubusercontent.com/7843719/34636398-e9a99522-f265-11e7-9502-baef9bf880ea.png)
> 
> currently having this issue again. sorry to bump this almost-year old issue but I don't think a clear solution to this was ever posted

well you're not alone. same here

**Comment by zoigo** [comment]
i am working on a self-modifying crackme, and after finding this issue comments i was able to save the NOPs i introduced, but all the code that was modified not by me was returned to original in a patched file.

we still need a way to produce a basic image dump

windows taskmanager dump appears to contain the decrypted image in the middle of it, but it is bloated

**Comment by kshvsec** [comment]
> ![image](https://user-images.githubusercontent.com/55943437/80732099-7456ff80-8b29-11ea-9d67-e8212045af7e.png)
> 
> this is shown when i try to run the patch file of any software. please help me what should i do..???

found any solutions yet? been trying to find one for this
