### ISSUE TITLE
ASCII Field for the edit registers dialog

### ISSUE THREAD

**Issue by cw2k** [x64dbg/x64dbg#1881]
I know that feature from Ollydbg:
![screenshot - 27 01 2018 22_54_25](https://user-images.githubusercontent.com/3834079/35476736-1c66e536-03b5-11e8-990d-ac38d5ecfc70.png)
... and miss it in X64dbg.

So please implement this for **EAX, EBX, ECX, EDX**

**Comment by aymanmahmood** [comment]
, m, ,

**Comment by mrexodia** [comment]
@cw2k Could you test if this solves your issue? https://ci.appveyor.com/project/mrexodia/x64dbg/build/1.0.397/artifacts (pull request #1892)

**Comment by mrexodia** [comment]
ping @cw2k

**Comment by Djamana** [comment]
Wow yeah now its much better.
![image](https://user-images.githubusercontent.com/7028778/36549698-b1fa52e8-17f3-11e8-9eef-67079e6dbf61.png)

@mrexodia :+1:  Thanks. :^)

Well Olldbg set up a high standard. 
There'll be some more stuff to reach it.

Tiny Adjustment '#1:
Hmm well maybe EFLAGS EBP and EBP doesn't needs the ACCII field

Tiny Adjustment '#2 :
'Mask' not printable chars like \0 with \x00
not printable chars are 00-1F (except 09 Tab)

Tiny Adjustment '#3 :
Separate bytes with space 
41424343
41 42 43 43

Bigger Adjustment '#4:
Make the rest of the fields editable. So you may also enter ACCII and (un)signed  decimal values.

**Comment by mrexodia** [comment]
Merged with #1006
