### ISSUE TITLE
Add memory breakpoint/hardware breakpoint in disassembly window.

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#189]
In olly, you can add memory breakpoint from the dump as well as the disassembly window. x32/64dbg is missing this.

---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/189
- Originally reported by: Anonymous
- Originally created at: 2014-09-03T03:07:36.159

**Comment by mrexodia** [comment]
easy to do, quite useless though since memory breakpoints are page-wide and don't work locally
