### ISSUE TITLE
need Hide Debugger

### ISSUE THREAD

**Issue by tqangxl** [x64dbg/x64dbg#1894]
stop check Debugger
![image146](https://user-images.githubusercontent.com/9669944/36012436-0ef896b8-0d99-11e8-8728-2fec5192d22b.jpg)

**Comment by Atvaark** [comment]
[ScyllaHide](https://github.com/x64dbg/ScyllaHide) should suit your needs.

**Comment by mrexodia** [comment]
ScyllaHide is indeed a good idea, you can also use the `dbh` command to mask the PEB.
