### ISSUE TITLE
Database Loss/Erasure/Reset

### ISSUE THREAD

**Issue by AncientRepositoryOfKnowledge** [x64dbg/x64dbg#1899]
Ok so I've just lots days of work thanks to this issue.

Version: snapshot_2018-01-28_12-18

Issue: Basically when you try to attach x64dbg to a process which already has a debugger attached, it resets the database.

How to recreate the issue:

1) Work for days to map out a program and store it in the x64dbg database.
2) Load the program up, and attach another debugger to it.
3) Try to attach x64dbg to the program aswell (it fails).
4) Close the other debugger.
5) Attach x64dbg to program.
7) Congratulations, your database is empty. 

For some reason, my backup was empty too, so not sure what happened there. Probably because I loaded the program up and closed it again after seeing my database was empty.

**Comment by mrexodia** [comment]
I'm really sorry about that... The issue has been fixed now and I made a new plugin available ([DbGit](https://github.com/x64dbg/DbGit)) that you can use to automatically add the databases to a git repo created in the `db` folder. Obviously this doesn't help you in this case, but it can reassure you that no data will be lost in the future.

**Comment by AncientRepositoryOfKnowledge** [comment]
It's ok man, and thanks for the fix.

**Comment by Mattiwatti** [comment]
Sorry for the necro, and this isn't exactly a high priority issue anyway, but I read this and I thought it was funny (sorry), so I tried it and got the following error message in the log:
> Attach to process failed! GetLastError() = ERROR_IS_SUBSTED: An attempt was made to use a JOIN or SUBST command on a drive that has already been substituted.

That's literally worse than no error IMO :stuck_out_tongue: 
The `NTSTATUS` version is much better:
> Attach to process failed! GetLastStatusValue() = STATUS_PORT_ALREADY_SET: An attempt to set a process's DebugPort or ExceptionPort was made, but a port already exists in the process or an attempt to set a file's CompletionPort made, but a port was already set in the file or an attempt to set an ALPC port's associated completion port was made, but it is already set.

To 'really' fix this, it would also be possible to do `NtQIP` with `ProcessDebugPort` (returns `0xFFFFFFFF` if process is being debugged). However that requires a process handle and most of that initialization stuff is in TitanEngine. Eh...

**Comment by sakashittu** [comment]
eeeeem what are we talking about👑👑👑👖
