### ISSUE TITLE
Log condition string formatting fails when string contains only 1 character

### ISSUE THREAD

**Issue by MulleDK19** [x64dbg/x64dbg#1906]
Version: Feb 14 2018
I'm trying to log some strings in a conditional log breakpoint, which works fine, except when the strings are 1 character long.

If RAX contains the address of "Hello", `{s:RAX}` will print `"Hello"`.
If RAX contains the address of "H", `{s:RAX}` will print `???`.

**Comment by mrexodia** [comment]
Yes, the `s` format string function tries to heuristically determine whether the bytes at the address are part of a string and what encoding it is (utf16 vs ansi). You can use a plugin like [EasyDump](https://github.com/torusrxxx/EasyDump) to have a command for logging strings for which you know the encoding. You can also use the [_plugin_registerformatfunction](https://github.com/x64dbg/x64dbg/blob/development/src/dbg/_plugins.h#L320) to write your own type of formatting, feel free to ask if you have questions about how to do that.

**Comment by MulleDK19** [comment]
Surely a bug shouldn't be worked around with a plugin.

The s format specifier is next to useless because it won't list 30% of strings. Even some strings longer than 1 character are still shown as `???`.

It should at the very least assume ASCII if determination fails.

**Comment by mrexodia** [comment]
Could you give examples of the 30% it doesn't list?

The `s` format specifier uses the same heuristic as the disassembly view, you can find the code [here](https://github.com/x64dbg/x64dbg/blob/development/src/dbg/disasm_helper.cpp#L293). The point is to not list every one or two character byte sequence that by chance can also be interpreted as an ASCII string. In short: you are using the wrong tool for the job.

**Comment by MulleDK19** [comment]
But if I'm logging a value as a string, it's because I know it's a string, not because I have an idea that it's sometimes a string.

In my case I was logging operator names, of which quite a number of them are one character. A lot that were 20-30 characters of pure ASCII characters were logged as `???` as well.

**Comment by mrexodia** [comment]
> But if I'm logging a value as a string, it's because I know it's a string, not because I have an idea that it may sometimes be a string.

That's why I said you are using the wrong tool for the job :) The `s` format string might not do what you expect but the behavior is what it is...

> A lot that were 20-30 characters of pure ASCII characters

So if you find those again, post them here so the heuristics can be improved. In the meantime just write a simple plugin to format the data exactly the way you need it or wait for someone to do it for you :smile:

**Comment by MulleDK19** [comment]
So what is the point of `s` if not to log strings? It's quite useless for anything, except for figuring out how bad the heuristics are.

**Comment by MulleDK19** [comment]
Just ran the breakpoints again. My number was wrong. It fails on 61.9% of the strings. 1628 out of 2628 fails. Strings such as "min", "max" and "atan2". The longest string it fails on is 38 characters long, consisting purely of a-Z.

**Comment by mrexodia** [comment]
Thanks, I reproduced the errors with many strings under 11 characters long, could you post the exact string of 38 characters long that this failed on (and your memory map).

In the meantime you can use the plugin I whipped together https://github.com/mrexodia/LogString

Log syntax is "{ascii@address}"

**Comment by MulleDK19** [comment]
`leaderboardRequestRowsGlobalAroundUser`, at time of read address was 0x000000000286FFE8, in the main executable.

```0000000000401000  0000000001A7D000   ".text"                          Executable code               IMG    ER---        ERWC-
0000000001E7E000  0000000000792000   ".rdata"                         Read-only initialized data    IMG    -R---        ERWC-
0000000002610000  00000000003B6000   ".data"                          Initialized data              IMG    -RW--        ERWC-
00000000029C6000  0000000000168000   ".pdata"                         Exception information         IMG    -R---        ERWC-
0000000002B2E000  0000000000001000   ".tls"                           Thread-local storage          IMG    -RWC-        ERWC-
0000000002B2F000  000000000000A000   "_RDATA"                                                       IMG    -R---        ERWC-
0000000002B39000  0000000000202000   ".rsrc"                          Resources                     IMG    -R---        ERWC-
0000000002D3B000  0000000000065000   ".reloc"                         Base relocations              IMG    -R---        ERWC-
0000000002DA0000  0000000000025000   ".bind"                                                        IMG    ER---        ERWC-```

**Comment by mrexodia** [comment]
That bug with the long string is likely fix now. You can use the LogString plugin (also updated) to treat anything as ASCII and log it verbatim...

**Comment by mrexodia** [comment]
Implemented using `{utf8@rax}`
