### ISSUE TITLE
Memory map merging regions with different protections

### ISSUE THREAD

**Issue by reliasn** [x64dbg/x64dbg#1907]
On the left, you have the latest x64dbg snapshot. On the right, Cheat Engine's "Memory Regions".

![](https://i.imgur.com/EmH4OJt.png)

I don't know if this is by design or a bug, but x64dbg doesn't seem to show all protections in a certain memory region. In the example above, there was an allocation of size 0xC000 at 0x165E0000 with ``PAGE_READWRITE`` protection. After some code executed, the last 0x1000 bytes were released and other protections got changed, originating the regions shown by Cheat Engine.

Is there a way to show a more detailed memory map in x64dbg?

**Comment by mrexodia** [comment]
There are two different 'views' of the memory map in x64dbg:

1. Show memory pages as they were allocated (original allocation base + size), the only exception is for module sections which are also shown as they appear in the header (this is the default view)
2. Show memory pages as they are in memory (probably equivalent to Cheat Engine).

You can switch views by using the 'Switch View' menu option in the memory map. Note however that this has the side effect of changing how much data you can scroll through when you go to an address in the disassembly or dump. It also changes what 'current region' means in the various search functions.
