### ISSUE TITLE
Provide Project File

### ISSUE THREAD

**Issue by skl131313** [x64dbg/x64dbg#1909]
Provide some sort of project file system. So that targets and settings don't have to be constantly re-entered manually.

Also don't close/clear the debugger when the program has finished executing.

**Comment by adsontag** [comment]
I use my mobile

Sendt fra min -mobiltelefon

-------- Original Message --------
Subject: [x64dbg/x64dbg] Provide Project File (#1909)
From: skl131313
To: x64dbg/x64dbg
CC: Subscribed


Provide some sort of project file system. So that targets and settings don't have to be constantly re-entered manually.

Also don't close/clear the debugger when the program has finished executing.

**Comment by mrexodia** [comment]
There is a settings file and databases per debuggee.

**Comment by skl131313** [comment]
Any documentation on where to find and use it? I can't find anything about this feature. Nothing like for other programs File->open project.

Also:
> Also don't close/clear the debugger when the program has finished executing.

**Comment by mrexodia** [comment]
Databases are saved and loaded automatically, you don’t have to do anything.

**Comment by skl131313** [comment]
It doesn't keep the working directory and arguments I passed to an executable though, when I reopen it for debugging.

**Comment by mrexodia** [comment]
Your first issue is a duplicate of #1874 
The second thing you mention is a duplicate of #498

When you created this issue you should have seen:

> Before submitting an issue, make sure it has not already been reported.

**Comment by mrexodia** [comment]
As a solution in the meantime you can construct the command that launches your application with the desired command line and working directory and add it as a favourite:

```
InitDebug "C:\program.exe", "-argument -argument", "C:\workingdir"
```

**Comment by arco123** [comment]
Jesus Christ people. Get me out of this mailing list.

**Comment by skl131313** [comment]
That first issue only refers to command line arguments, that can be achieved by an implementation that doesn't use a project file. A project file can store a lot more information than just the command line arguments. It isn't exactly a duplicate.

I did search, I didn't find anything with the keywords I used.

**Comment by mrexodia** [comment]
So what would be stored in a project file? You mention command line, that is stored (minus that issue). Currently the databases store your labels comments breakpoints, what else do you want? The databases (similar to ida idb) are stored in the “db” folder

**Comment by skl131313** [comment]
The database file can be stored in/with the project file. Some people may want to use the same database for the same executable, like I do for a few projects. Program settings that are only applied for that specific project file. Sounds like database is basically what the project file is, just need to change it so it isn't hidden from the user in such a manner as it currently is.

**Comment by dikdidini** [comment]
UNSUBSCRIBER PLEASE!!!!!!


________________________________
De: skl131313 <notifications@github.com>
Enviado: sexta-feira, 2 de março de 2018 16:21
Para: x64dbg/x64dbg
Cc: Subscribed
Assunto: Re: [x64dbg/x64dbg] Provide Project File (#1909)


The database file can be stored in/with the project file. Some people may want to use the same database for the same executable, like I do for a few projects. Program settings that are only applied for that specific project file. Sounds like database is basically what the project file is, just need to change it so it isn't hidden from the user in such a manner as it currently is.

**Comment by mrexodia** [comment]
You can import/export the database from the file menu if you want to share it with your peers (or just copy the relevant file from the db folder).

As for program settings, I assume you mean the x64dbg options (x64dbg.ini)? This you can also share with your peers (in fact the whole x64dbg directory is portable, nothing is hidden).

The plugin system is more than rich enough to implement a more advanced system that suits your needs better...
