### ISSUE TITLE
x32dbg strips the quotes for arguments so special characters fails to be passed to program

### ISSUE THREAD

**Issue by saidelike** [x64dbg/x64dbg#1918]
Hi,

- Debugger version: 5bf0e7fb7b512f8fea62f808bd7079bb95b78849 (5 Mar 2018)
- Operating system: Windows 7 SP1 x64

So i have `prog.exe` and `prog.py` in `C:\Users\User\Desktop\`. I run `prog.py` which will call x32dbg attaching to `prog.exe`. So I run x32dbg from Python with the following:

```
# this is the content of prog.py
import os, struct
s = "A"*128
s += struct.pack('<I', 0x7C376FFE)     # pop ebx ; ret ;
s += "AAAA"

os.system('C:\\Tools\\x64dbg\\release\\x32\\x32dbg.exe C:\\Users\\User\\Desktop\\prog.exe "' + s + '"')
```

And I call it from:

```
C:\Users\User\Desktop\>python prog.py
```

The issue is that the command line x32dbg has in File > Change Command Line is `"C:\Users\User\Desktop\prog.exe" AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAþo7|AAAA` which means it got rid of the additional quotes I added when calling x32dbg.

It is problematic because there is a pipe (i.e. `|`) which is interpreted by the shell and so it does not do what I want.

One workaround is to patch the command line using File > Change Command Line to `"C:\Users\User\Desktop\prog.exe" "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAþo7|AAAA"` (note the additional quotes for the argument) but I would assume x32dbg does not strip the quotes I gave.

**Comment by saidelike** [comment]
Is there a reason why you would want to remove the quotes at all? If the user provides quote around an argument, it should be passed as is, and if he does not provides quote, same or am I missing something?

**Comment by saidelike** [comment]
Anyone understands the problem here? Do you have any question if not?

**Comment by mrexodia** [comment]
The issue is fully understood. I think you can use:

```
command "\"quoted string\""
```

**Comment by mrexodia** [comment]
oh nvm... I think you can use x96dbg.exe to do what you want

**Comment by mrexodia** [comment]
@saidelike please confirm if your issue was solved or not

**Comment by saidelike** [comment]
Hi, sorry for the delay, I had missed your messages.

Sorry to bring bad news but it does not look like it is fixed. 

* Debugger version: snapshot_2018-07-01_19-55.zip
* Operating system: Windows 7 SP1 x64

I've used this simple C code, compiled with Visual Studio, to replicate - and so you can replicate on your side too.

```cpp
int main(int argc, char* argv[])
{
	int i;
        // print every single argument
	for (i = 0; i < argc; i++) {
		printf("Arg %d = %s\n", i, argv[i]);
	}
        // never returns so we can check the output
	while (1)
		;
    return 0;
}
```

# Result without x32/x64dbg

If I run it without any debugger:

Expected: it prints every single argument separately.

```
C:\Users\exdev\Desktop>PrintArgs.exe "i" "am" "the" "args"
Arg 0 = PrintArgs.exe
Arg 1 = i
Arg 2 = am
Arg 3 = the
Arg 4 = args
```

Expected: it prints a single argument

```
C:\Users\exdev\Desktop>PrintArgs.exe "i am a single arg"
Arg 0 = PrintArgs.exe
Arg 1 = i am a single arg
```

# Result with x32dbg

Not expected: it prints the single argument as if it were multiple arguments wherewas it should print only Arg 0 and Arg1 as above without x32dbg attached.

```
C:\Users\exdev\Desktop>C:\Users\exdev\Desktop\snapshot_2018-07-01_19-55\release\
x32\x32dbg.exe C:\users\exdev\Desktop\PrintArgs.exe "i am a single arg"
```

```
Arg 0 = C:\Users\exdev\Desktop\PrintArgs.exe
Arg 1 = i
Arg 2 = am
Arg 3 = a
Arg 4 = single
Arg 5 = arg
```

# Result with x96dbg

Not expected: It does not seem to pass any argument using x96dbg so it may be that there is another bug.

```
C:\Users\exdev\Desktop>C:\Users\exdev\Desktop\snapshot_2018-07-01_19-55\release\
x96dbg.exe C:\users\exdev\Desktop\PrintArgs.exe "i am a single arg"
```

```
Arg 0 = C:\Users\exdev\Desktop\PrintArgs.exe
```

**Comment by mrexodia** [comment]
@saidelike please confirm it is also fixed for you now.

`x96dbg.exe "C:\program.exe" arg1 arg2 arg3` called from `c:\workingdir` should forward to x32dbg/x64dbg with:

`x32dbg.exe "C:\program.exe" "arg1 arg2 arg3" "c:\workingdir"`

Which should start `C:\program.exe` with `arg1 arg2 arg3` as command line with the working directory `c:\workingdir`.

I tested with GFlags on `vsjitdebugger.exe` and everything appears to be working.

**Comment by saidelike** [comment]
Debugger version: snapshot_2018-07-19_16-55.zip
Operating system: Windows 7 SP1 x64

# Result with x32dbg

Not expected: it does not take into account the arguments I pass. It is as if there was cached arguments in x32dbg for each time I restart x32dbg.

To replicate, unzip `snapshot_2018-07-19_16-55.zip` in a fresh folder. Then execute:

```
C:\Users\exdev\Desktop>C:\Users\exdev\Desktop\snapshot_2018-07-19_16-55\release\
x32\x32dbg.exe C:\Users\exdev\Desktop\PrintArgs.exe
Arg 0 = C:\Users\exdev\Desktop\PrintArgs.exe
```

Then close x32dbg and try the following. As you can see arg1, arg2, arg3 do not appear:

```
C:\Users\exdev\Desktop>C:\Users\exdev\Desktop\snapshot_2018-07-19_16-55\release\
x32\x32dbg.exe C:\Users\exdev\Desktop\PrintArgs.exe exe arg1 arg2 arg3
Arg 0 = C:\Users\exdev\Desktop\PrintArgs.exe
```

# Result with x96dbg

Not expected: Originally it seemed to pass argument from x96dbg to x32dbg. However trying again, it seems as if there was cached arguments as described with x32dbg.

Hope this helps.

**Comment by mrexodia** [comment]
# x32dbg/x64dbg

The command line for `x32dbg.exe` is not suitable for public use. The launcher uses it to communicate it's intention to the debugger. However, here is an overview of the options:

```
x32dbg.exe <filename>
x32dbg.exe -p <pid>
x32dbg.exe <filename> <command line>
x32dbg.exe <filename> <command line> <working directory>
x32dbg.exe -a <pid> -e <event>
x32dbg.exe -p <pid> -e <event>
x32dbg.exe -p <pid> -tid <tid>
```

The important part is that you have to escape your command line arguments if you want to use x32dbg directly, for example:

```
x32dbg.exe "C:\Program Files\Test\Test.exe" "arg1 ""arg2 with spaces""" "C:\Program Files\Test"
```

Will effectively run:

```
cd "C:\Program Files\Test"
"C:\Program Files\Test\Test.exe" arg1 "arg2 with spaces"
```

# x96dbg

The intention for x96dbg is to handle the escaping for you. To achieve the same as the previous example you can do:

```
cd "C:\Program Files\Test"
C:\x64dbg\x96dbg.exe "C:\Program Files\Test\Test.exe" arg1 "arg2 with spaces"
```

# Test

I wrote my own test program:

```
#include <windows.h>
#include <stdio.h>

int wmain(int argc, wchar_t* argv[])
{
    wprintf(L"GetCommandLineW():\n%s\n", GetCommandLineW());
    wchar_t dir[MAX_PATH];
    GetCurrentDirectoryW(MAX_PATH, dir);
    wprintf(L"GetCurrentDirectoryW():\n%s\n", dir);
    wprintf(L"argc: %d\n", argc);
    for(int i = 0; i < argc; i++)
        wprintf(L"argv[%d]:\n%s\n", i, argv[i]);
    system("pause");
}
```

I tested again to make sure and everything is working as expected. Your command line usage of x32dbg.exe is just wrong. The first happens to work, but the one with the arguments does nothing. Just use x96dbg.exe instead.
