### ISSUE TITLE
The tab bar icon has changed...

### ISSUE THREAD

**Issue by SnowI5Me** [x64dbg/x64dbg#1920]
As the title says, the tab bar icon has changed.
how to revert a tab bar icon ?

![tabbaricon](https://user-images.githubusercontent.com/19868462/38169345-e8be6626-35a2-11e8-8061-dbb34106ced7.PNG)

> I installed it again, but it is not restored to its original state.

Thanks in advance for your help.

**Comment by mrexodia** [comment]
Hi,

These few days it’s easter, you can disable it by adding this to your
config:

[Misc]
NoSeasons=1

Happy easter!

**Comment by SnowI5Me** [comment]
Thank You And Happy Easter !

**Comment by SnowI5Me** [comment]
Thank you

**Comment by zeffy** [comment]
This gave me a nice laugh once I realized why the icons suddenly changed. I also happened to discovered the "oep" easter egg, that made my day lol.

Happy easter!

**Comment by MehdiiPanahi** [comment]
not Working in 2022 version

**Comment by mrexodia** [comment]
You can disable the icons in the settings, but it’s only visible during the seasons
