### ISSUE TITLE
What your titanEngine version? Why I use the lastest titanEngine version v2.0.3 don't export TitanOpenThread which difference from yours.

### ISSUE THREAD

**Issue by Youlor** [x64dbg/x64dbg#1926]
I compile titanEngine from https://bitbucket.org/titanengineupdate/titanengine-update, but when I complied, I find the titanEngine  dll difference from x64dbg, can't find TitanOpenThread function in exports

**Comment by mrexodia** [comment]
We use the “x64dbg” branch.
