### ISSUE TITLE
Animate into/over speed

### ISSUE THREAD

**Issue by stevenwdv** [x64dbg/x64dbg#1927]
It would be really useful to be able to set the speed of the animate into/over function, so that we can choose to execute more instructions per time unit. This was apparently mentioned [here](https://botbot.me/freenode/x64dbg/2018-02-10/?page=1), but I can't find an issue for it here.

Also, sorry for asking this here, but is there an option to only animate/step into user code (and not, for example, `HeapAlloc`? (If, not, I guess I'll open a new issue for that as well. EDIT: or is this #1884?) (This would make a speed slider less relevant, but it still would be useful)

**Comment by mrexodia** [comment]
As for your second question, you can use the switch condition to only step in when the instruction doesn’t go to another module or memory region. See the tracing documentation for more information http://help.x64dbg.com/en/latest/introduction/ConditionalTracing.html

**Comment by mrexodia** [comment]
Does that actually work? Perhaps it would be a good idea to implement detection of button holding to improve the speed.

**Comment by torusrxxx** [comment]
You can set animate speed in settings dialog.

**Comment by Menalix** [comment]
> You can set animate speed in settings dialog.

Where I don't see such option

**Comment by jamespharvey20** [comment]
> > You can set animate speed in settings dialog.
> 
> Where I don't see such option

Engine->Animation per-step interval (ms) -- Defaults to 50ms.

Unfortunately, it has a maximum accepted value of 99, so you can only cut the speed in half.

**Comment by mrexodia** [comment]
Usually people want to change it to animate faster. But you can check the
ini file to set it to any value you want for now (I think)
