### ISSUE TITLE
[GUI]The check box has been checked, but there is no visual effect

### ISSUE THREAD

**Issue by flarejune** [x64dbg/x64dbg#1932]
"Assemble at xxxxx" dialog,"Keep Size" or "Fill with Nop's" ,has been checked, but there is no visual effect

**Comment by torusrxxx** [comment]
What visual effect do you expect?

**Comment by flarejune** [comment]
"Assemble at xxxxx" dialog,"Keep Size" or "Fill with Nop's" ,has been checked, but there is no visual effect(dot pattern)

**Comment by flarejune** [comment]
You try to check the checkbox,

**Comment by flarejune** [comment]
"Assemble at xxxxx" dialog,"Keep Size" or "Fill with Nop's" ,Has always been unchecked state
