### ISSUE TITLE
plugin hotkey doesn't work

### ISSUE THREAD

**Issue by flarejune** [x64dbg/x64dbg#1943]
work:
_plugin_menuaddentry(hMenu, MyMenuEntry, "MyMenuEntry");
_plugin_menuentrysethotkey(PluginHandle,MyMenuEntry,"Ctrl+H");

doesn't work:
_plugin_menuaddentry(hMenuDisasm, MyMenuEntry, "MyMenuEntry");
_plugin_menuentrysethotkey(PluginHandle,MyMenuEntry,"Ctrl+H");

if menuentry add to main menu, hotkey is work, but, doesn't work

**Comment by mrfearless** [comment]
I wouldn't expect it to work with popup menus, just the plugins main menu entries. You can add similar menu items to the popup disasm menu for appearance, but not for hotkey usage as far as im aware.

The registered hotkey will then push a call to the plugin menu item, as if the user clicked that menu option, and will call the plugins CBMENUENTRY for processing as normal.

Or optionally register some custom commands and allow user to specify the hotkey they wish with the favourites dialog (Favourites->Command tab-Add), specifying the command and the shortcut key to use - assuming it doesnt conflict with an existing key of course.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/snowman/blob/x64dbg-module/src/x64dbg-module/QtPlugin.cpp#L55
