### ISSUE TITLE
Can not debug certain 64-bit dotNET application

### ISSUE THREAD

**Issue by reyaz006** [x64dbg/x64dbg#1949]
This appears on status bar almost immediately after loading target:
`First chance exception on *** (04242420, CLRDBG_NOTIFICATION_EXCEPTION_CODE)!`
After running:
`Last chance expection on *** (E0434352, CLR_EXCEPTION)!`
After that the process gets terminated and `Debugging stopped!`

The target may have some anti-debug protection included, which, I think, may be a reason for this. I'd like to ask if this is a proper issue to report here?

x64dbg version: May 17 2018.
OS: Windows 8.1 x64.
The target is [here](https://www.syncdocs.com/downloads/SyncdocsPortableInstaller64.exe) (needs to be unpacked first, actual file is Syncdocs64.exe).

**Comment by mrexodia** [comment]
It doesn’t look like a bug in x64dbg to me. If you find a hello world-style executable to reproduce this on without anti debug it would be a different story.

**Comment by blaquee** [comment]
You need to add that exception to the exception list. When a NET program is loaded and the CLR environment is started, it invokes that Exception (its a harmless exception) and debuggers should ignore it.

**Comment by mrexodia** [comment]
Adding the exception to the list only automatically presses the run button for you, so it would still throw the last chance exception

**Comment by blaquee** [comment]
Yea, that last exception just seems like some other error occurred within the .NET runtime. But I didn't check the program he attached.
