### ISSUE TITLE
Feature Request : Add "All modules in same directory" option inside "search for"

### ISSUE THREAD

**Issue by nihillian** [x64dbg/x64dbg#1950]
The "all modules" option under "search for" button in context menu searches things inside every dependency, but sometimes, say when I am searching for some string, it's useless to search for them inside system dlls, like kernel32, user32 or so on. So if there could be an option to include only the modules in same folder/directory as the debuggee, it would be great.

In addition, under settings -> events -> break on : if there could be a similar option like, "break on dlls in same directory" it would be great too.

**Comment by gmastergreatee** [comment]
Do you mean this #1284 ?

**Comment by mrexodia** [comment]
duplicate
