### ISSUE TITLE
how to find multiple assembled instructions?

### ISSUE THREAD

**Issue by nt47** [x64dbg/x64dbg#1951]
Dear Master,
i have downloaded latest version,but i have a problem now.
i can only find one assembled instruction with find command (ctrl+shift+f)
i have read #297,but i still don't understand,can u tell how to use this function which find multiple assembled instructions?
thx

**Comment by mrexodia** [comment]
The short answer is that you cannot. It’s not implemented yet.

**Comment by nt47** [comment]
@mrexodia then future version will be added this function possiblely?

**Comment by mrexodia** [comment]
I don’t need this functionality so I won’t add it. You can add it if you
want though.
