### ISSUE TITLE
@import on style.css

### ISSUE THREAD

**Issue by borela** [x64dbg/x64dbg#1959]
- Debugger version: May 17 2018.
- Operating system: Windows 10 x64.

I tried to import external CSS files into the `style.css` using the syntaxes:

```
@import "./file.css";
@import url("./file.css");
```

But it didn't work, looking at QT help didn't give me an answer either. Is this a limitation in QT's system or is it something that can be fixed?

Being able to break themes into multiple files would help a lot during design.

**Comment by mrexodia** [comment]
In 2009 this was a limitation in Qt.

https://thesmithfam.org/blog/2009/09/10/qt-stylesheets-tutorial/

In 2013 there was still a problem

https://forum.qt.io/topic/23202/solved-qt-5-handling-of-css-imports-in-qthelp/2

If they didn't include this feature by now you probably cannot do it. Probably it's easiest to create a simple preprocessor that you run to generate the final file without imports.

**Comment by borela** [comment]
I'll use sass then, thank you @mrexodia :D
