### ISSUE TITLE
X64dbg crashes if exported .dll symbols have more than 255 Chars

### ISSUE THREAD

**Issue by willi-neu9** [x64dbg/x64dbg#1962]
[crash_long_dll_symbols.zip](https://github.com/x64dbg/x64dbg/files/2086228/crash_long_dll_symbols.zip)

Only tested under Win7 64 Bits with x64dbg Version May 17 2018

X64dbg crashes if .dll symbols are loaded that are longer than 255 Characters. Just run:
crash\crashdll\x64\Debug\Crash.exe.
This Testprogram has an embedded breakpoint. Just run it. After breakpoint has loaded x64dbg replace int3 with a nop and singestep thru the program. After second Symbol loads from crashdll.dll by single steppling using F8 the Debugger crashes.

Found by debugging thru a .dll load which longest exported Symbol is about 360 Chars long.

Best regards

/Willi/

**Comment by mrexodia** [comment]
I think I fixed this bug in the symcache branch. Could you try it? https://ci.appveyor.com/api/buildjobs/1hq2y855wkscfqec/artifacts/release.zip

**Comment by willi-neu9** [comment]
[June_dump_1.txt](https://github.com/x64dbg/x64dbg/files/2086868/June_dump_1.txt)
[June_dump_2.txt](https://github.com/x64dbg/x64dbg/files/2086869/June_dump_2.txt)
[may_dump_1.txt](https://github.com/x64dbg/x64dbg/files/2086870/may_dump_1.txt)
[may_dump_2.txt](https://github.com/x64dbg/x64dbg/files/2086871/may_dump_2.txt)

Hi mrexodia,

I've tested the above release a little bit and the crash is gone using my debugged program as test source. On the other Hand there is a new bug in displaying symbols. In this test release local symbols of a debugee are not longer displayed (see may_dump1.txt and june_dump1.txt). If return values of a GetProcAddress call are stored in local program variables the Symbol of the currently loaded library function is displayed as destination Name instead of the Name of the local variable (see may_dump2.txt and june_dump2.txt) for differences.

Best regards


/Willi/

**Comment by mrexodia** [comment]
@willi-neu9 can you confirm this issue is fixed in the latest snapshot now?

**Comment by willi-neu9** [comment]
[local_symbols_not_displayed_on_version_1_jul_2018.txt](https://github.com/x64dbg/x64dbg/files/2153228/local_symbols_not_displayed_on_version_1_jul_2018.txt)
[crash_long_dll_symbols.zip](https://github.com/x64dbg/x64dbg/files/2153230/crash_long_dll_symbols.zip)

High mrexodia,

If you load "crash_long_dll_symbols\crashdll\x64\Debug\crash.exe" from "crash_long_dll_symbols.zip" into x64dbg of Jun 11 2018 into Debugger and single step a little bit around you can see that many local symbols of Crash.exe are displayed in the disassembler listing.

If you load "crash_long_dll_symbols\crashdll\x64\Debug\crash.exe" from "crash_long_dll_symbols.zip" into x64dbg of Jul 1 2018 into Debugger and single step a little bit around you CANNOT LONGER see that many local symbols of Crash.exe are displayed in the disassembler listing.

Just try by yourself.

Best regards

/Willi/

**Comment by mrexodia** [comment]
![(https://i.imgur.com/OKjBYDe.png)

**Comment by mrexodia** [comment]
```
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\crash.exe
	AssemblyDirectory = C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\crash.exe.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.VC80.DebugCRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="8.0.50727.762"
	INFO: Reference: Microsoft.VC80.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="8.0.50727.762"
INFO: Resolving reference Microsoft.VC80.DebugCRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="8.0.50727.762".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Windows\assembly\GAC_64\Microsoft.VC80.DebugCRT\8.0.50727.762__1fc8b3b9a1e18e3b\Microsoft.VC80.DebugCRT.DLL.
				INFO: Attempt to probe manifest at C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\Microsoft.VC80.DebugCRT.DLL.
				INFO: Attempt to probe manifest at C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\Microsoft.VC80.DebugCRT.MANIFEST.
				INFO: Attempt to probe manifest at C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\Microsoft.VC80.DebugCRT\Microsoft.VC80.DebugCRT.DLL.
				INFO: Attempt to probe manifest at C:\!exclude\crash_long_dll_symbols\crashdll\x64\Debug\Microsoft.VC80.DebugCRT\Microsoft.VC80.DebugCRT.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference Microsoft.VC80.DebugCRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="8.0.50727.762".
ERROR: Activation Context generation failed.
End Activation Context Generation.
```

**Comment by mrexodia** [comment]
I don't have a visual studio installed ancient enough to run this, but with the release version symbols appear to be fine. If you send me msvcrt80d.dll for win64 I can try to reproduce it on the debug version.

**Comment by mrexodia** [comment]
Try installing visual studio 2017 to get a recent version of msdia registered (putting msdiaxxx.dll next to x64dbg should work). Check the symbol log to see if there are errors while loading.

**Comment by willi-neu9** [comment]
[crash_long_dll_symbols.zip](https://github.com/x64dbg/x64dbg/files/2155972/crash_long_dll_symbols.zip)

Hi mrexodia,

Sorry that was my fault. I've accidently used the wrong Compiler Settings to compile Crash.exe. Now Crash.exe should run on any Windows 7 Computer without installing any msvc .dlls. I've tried it on such a Computer and it loads without problems. If you still have trouble to get "Crash.exe" run, please let me know.

Best regards

/Willi/

**Comment by mrexodia** [comment]
appears to work fine here. https://paste.ee/p/bbsUo

what do you see in the symbol log?

**Comment by willi-neu9** [comment]
Hi Ducan,

I don't know how to create this symbol log. Is this a x64dbg function?
If yes how do call it?

/Willi/
  ----- Original Message -----

**Comment by mrexodia** [comment]
Go to the symbols tab, the log is in the bottom.

**Comment by willi-neu9** [comment]
Hi Ducan,

I just see the following error messages in symbol tab when loading crash.exe

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\crash.pdb\BB52C6FF46784303AD1851F1C030DDD32\crash.pdb
[DIA] Failed to load PDB: p:\msvc\crash\crashdll\x64\Debug\crash.pdb

[DIA] Failed to load PDB: C:\t\crashdll\x64\Debug\crash.pdb

[DIA] Failed to load PDB: C:\t\crashdll\x64\Debug\crash.pdb

No symbols loaded for: crash.exe

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\ntdll.pdb\F47155555C654CCCAECFD23B66F59D7D1\ntdll.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\ntdll.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\ntdll.pdb

No symbols loaded for: ntdll.dll

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\kernel32.pdb\CC40188259BF403B915ABB6F5B331BCE2\kernel32.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernel32.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernel32.pdb

No symbols loaded for: kernel32.dll

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\kernelbase.pdb\C357DF0380104CEDA9C5CAE4FFB2D32A2\kernelbase.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernelbase.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernelbase.pdb

No symbols loaded for: kernelbase.dll




The file:



[DIA] Failed to load PDB: C:\t\crashdll\x64\Debug\crash.pdb



is there but cannot be loaded. You can find "crash.pdb" in my example

"crash_long_dll_symbols.zip"

Maybe a x64dbg setup at my side is still wrong?

/Willi/

  ----- Original Message -----

**Comment by willi-neu9** [comment]
Hi Ducan,

when loading crash.exe in Version x64dbg Jun 11 2018 crash.pdb can be loaded:

See here:

SYMSRV: K:\x64dbg4\release\x64\symbols\crash.pdb\BB52C6FF46784303AD1851F1C030DDD32\crash.pdb not found
DBGHELP: crash - private symbols & lines 

C:\t\crashdll\x64\Debug\crash.pdb

SYMSRV: K:\x64dbg4\release\x64\symbols\ntdll.pdb\F47155555C654CCCAECFD23B66F59D7D1\ntdll.pdb not found

DBGHELP: C:\Windows\System32\ntdll.pdb - file not found

DBGHELP: ntdll - export symbols

SYMSRV: K:\x64dbg4\release\x64\symbols\kernel32.pdb\CC40188259BF403B915ABB6F5B331BCE2\kernel32.pdb not found

DBGHELP: C:\Windows\System32\kernel32.pdb - file not found

DBGHELP: kernel32 - export symbols

SYMSRV: K:\x64dbg4\release\x64\symbols\kernelbase.pdb\C357DF0380104CEDA9C5CAE4FFB2D32A2\kernelbase.pdb not found

DBGHELP: C:\Windows\System32\kernelbase.pdb - file not found

DBGHELP: KernelBase - export symbols




when loading crash.exe in Version x64dbg Jul 01 2018 crash.pdb cannot longer be loaded:

See here:

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\crash.pdb\BB52C6FF46784303AD1851F1C030DDD32\crash.pdb
[DIA] Failed to load PDB: p:\msvc\crash\crashdll\x64\Debug\crash.pdb

[DIA] Failed to load PDB: C:\t\crashdll\x64\Debug\crash.pdb

[DIA] Failed to load PDB: C:\t\crashdll\x64\Debug\crash.pdb

No symbols loaded for: crash.exe

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\ntdll.pdb\F47155555C654CCCAECFD23B66F59D7D1\ntdll.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\ntdll.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\ntdll.pdb

No symbols loaded for: ntdll.dll

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\kernel32.pdb\CC40188259BF403B915ABB6F5B331BCE2\kernel32.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernel32.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernel32.pdb

No symbols loaded for: kernel32.dll

[DIA] Skipping non-existent PDB: K:\x64dbg7\release\x64\symbols\kernelbase.pdb\C357DF0380104CEDA9C5CAE4FFB2D32A2\kernelbase.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernelbase.pdb

[DIA] Skipping non-existent PDB: C:\Windows\System32\kernelbase.pdb

No symbols loaded for: kernelbase.dll




/Willi/

  ----- Original Message -----

**Comment by mrexodia** [comment]
New snapshot should be out soon, hopefully that fixes it...

**Comment by willi-neu9** [comment]
Hi Ducan,

I just tried X64dbg Jul 5 2018 and there was a successful FIX for the unsuccessful load of local .pdb files.

GREAT!

But there is still this bug open.

If you load "crash.exe" into x64dbg and set some HW breakpoints and then close the debugger this HW breakpoints
are stored in the Data Base correctly.
If you start crash.exe outside of x64dbg it will activate x64dbg due the INT3 breakpoint insite as JIT debugger.
As you can see in the attached images the HW breapoints are set correctly but are not set in the DRx registers.

Maybe you can fix that too?


Best regards


/Willi/
  ----- Original Message -----

**Comment by mrexodia** [comment]
Good to know it works :)

The other issue you mention is #1942. I have no use case for this so I don’t have much interest in fixing that at the moment. This issue appears to be solved.
