### ISSUE TITLE
Breakpoint not in list

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#1964]
Sometimes I get the following message:
![screenshot](https://i.imgur.com/AtjfARN.png)

Right now it stopped on `ntdll.NtQueryInformationProcess` without an apparent reason. I just attached to the system process `audiodg.exe` and started a media player, perhaps you can reproduce it too.

If that's not easy fixable, can we at least have an option to not stop on those invalid breakpoints?

**Comment by mrexodia** [comment]
What version are you using? Check if the process cookie option is enabled and disable it.

**Comment by justanotheranonymoususer** [comment]
I didn't have the cookie option. Updated to the latest version, seems like the bug is gone.
