### ISSUE TITLE
[Plugin] Callback CBLOADDB

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#1971]
x32dbg - Version June 19, 2018
Windows 10 (64-bits) - Version 10.0.17134 Build 17134

**Brief description:**
When using the callbacks in a custom plugin, the CBLOADDB callback isn't called.

**Reproduce:**
Create a callback as illustrated, and witness no log printing as a database is being loaded.

```
PLUG_EXPORT void CBLOADDB(CBTYPE, PLUG_CB_LOADSAVEDB* info)
{
	dprintf("LoadDB called type: %d", info->loadSaveType);
}

PLUG_EXPORT void CBSAVEDB(CBTYPE, PLUG_CB_LOADSAVEDB* info)
{
	dprintf("SaveDB called type: %d", info->loadSaveType);
}
```

**Minor printing annoyance**
The CBSAVEDB is being called, but prints like so:

`Saving database to D:\RE\Debuggers\x64dbg\release\x32\db\TestExe_x86.exe.dd32 [dbremap] SaveDB called type: 20ms`

![plugin_cbloaddb](https://user-images.githubusercontent.com/13701799/41894742-cac95e9e-78d4-11e8-935a-5ab3ef8efb69.jpg)

**Comment by mrexodia** [comment]
If the database does not exist this function is not called. I think it’s
also not called if savedb didn’t create any json keys.

**Comment by MoonDoggie42** [comment]
**Additional testing:**
registered the callbacks in pluginInit()
disabled all plugins except this offending one  

Compiled against windows sdk: 10.0.16299.0
Platform toolset v141

**Comment by mrfearless** [comment]
I remember mentioning this issue as well in telegram when i was looking at doing stuff with hashes, its a catch22, as the CBLOADDB and CBSAVEDB are only called if there is data already in the user database, but with no data in it, there is no way to get the json object to then later add data to it, or to read data - to compare for example.

**Comment by mrexodia** [comment]
@MoonDoggie42 if CBSAVEDB didn’t previously save information it means CBLOADDB won’t be called.

**Comment by MoonDoggie42** [comment]
@mrfearless @mrexodia Thanks for the clarification from both of you.  I was under the impression the message in the log "Loading Database ..." was meaning the callback should have been called but just wasn't.

I do have a .dd32 file with database information in it (labels/comments) etc.  I was hoping to extend the capabilities of x64dbg via a plugin that could remap them to an updated PE of the file with slightly different offsets.  

I'll look into extending this functionality via an entirely separate db file instead of adding it to the current one.  Thanks a ton.

**Comment by mrexodia** [comment]
Probably the easiest is to decompress the database with lz4 and then directly manipulate the json.

The current database is not exposed because that would limit the possibility of a different database implementation (jansson has pretty bad performance characteristics and expositing the database would lock us to jansson).

**Comment by torusrxxx** [comment]
If there is no data in database, CBLOADDB won't be called (src/dbg/database.cpp:260) because there is no data to read. This is also the case when you debug a new executable. CBSAVEDB will be called all the times to save plugin data, but if no plugin stores any data, next time CBLOADDB won't be called either.
