### ISSUE TITLE
Edit With Float And Show

### ISSUE THREAD

**Issue by nt47** [x64dbg/x64dbg#1974]
Dear Master,
when i edit a value in memory window or stack window,i can't input a float type .
can u add this support and even can show what float i input?
it is possible? and hard work ?

**Comment by torusrxxx** [comment]
It would take developers 5 minutes to add it, but no one has yet come up with an idea how and where this float editor will apear.

**Comment by nt47** [comment]
@torusrxxx 
u can understand me ? i just want to use it like use ollydbg so ez

**Comment by torusrxxx** [comment]
In Ollydbg the user can only edit a float value when dump is in float mode, and edit a double value when dump is in double mode. The user cannot edit edit a double value in stack but can edit a float value.

**Comment by torusrxxx** [comment]
The method used in Ollydbg doesn't work directly in x64dbg because the stack size is 32-bit or 64-bit, and the user might want to edit double value in x86 or edit float value in x64.

**Comment by torusrxxx** [comment]
duplicate of #1550
