### ISSUE TITLE
DLL loading log message should not be more verbose than before

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1978]
In latest version of x64dbg it begins to log number of imports and exports of each DLL loaded. Most users don't care about number of imports and exports so this can be seen as debug output to be removed.

**Comment by mrexodia** [comment]
Agreed! The branch was not 100% polished, but I wanted to get the functionality out the door so people can use it and report any issues they find.

**Comment by mrexodia** [comment]
Should be fixed.
