### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by michaelpittino** [x64dbg/x64dbg#1982]
First of all I want to say thanks again for this great debugger, still using it almost daily.

I was wondering if there is a changelog somewhere which sums up all the more important changes.
I'm not actively following the development/reading through commits, so it'd be really great if there was a way to know what's new.

Thanks and Best Regards,
Michael.

**Comment by mrexodia** [comment]
Currently there is no such thing. There are also no releases, so it’s a difficult thing to do in a meaningful way.

Reading the commits is not too bad. There should be links to the closed issues there...

**Comment by mrexodia** [comment]
One idea was to do something like https://x64dbg.com/blog/beamer to highlight important new changes as they happen, but I didn't have time to do much with that so far...

**Comment by torusrxxx** [comment]
Nobody's writing them
