### ISSUE TITLE
synchronization of event processing with QtGUI

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#1983]
Hi, when processing a lot of information through the plugin, there is no access to the interface not, even with GuiUpdateDisable ().
with DoEvents () better, but more time lost. 
What code should I write to avoid friezes with gui?

**Comment by mrexodia** [comment]
You can run your code in a separate thread, and use the following structure:

```c++
DWORD WINAPI MyThread(PVOID data)
{
//do long work
}

cbMenuSomething //plugin callback for menu/command
{
    auto hThread = CreateThread(..., MyThread, data, ...);
    bool finished = false;
    while(!finished)
    {
        auto res = WaitForSingleObject(hThread, 100);
        switch(res) {
        case WAIT_OBJECT_0: finished = true; break;
        case WAIT_TIMEOUT: GuiProcessEvents(); break;
        default: //weird state, probably best to bail
        finished = true; break;
    }
}
```

**Comment by Paliha** [comment]
Excellent! Very grateful for the answer. even with BRIDGE API GuiProcessEvents () much better, and in a separate thread is very good.
