### ISSUE TITLE
Hardware breakpoint step into not running

### ISSUE THREAD

**Issue by maskelihileci** [x64dbg/x64dbg#1984]
The last version of the application does not step into hardware assignments

**Comment by maskelihileci** [comment]
snapshot_2018-07-05_02-53.zip
snapshot_2018-07-01_19-55.zip

these two versions can not skip the step !

**Comment by mrexodia** [comment]
Yes this behavior was changed. There will be only one callback on a step.

**Comment by maskelihileci** [comment]
Why ?

**Comment by maskelihileci** [comment]
Could you add this feature to the settings as changeable?

**Comment by mrexodia** [comment]
Why?
