### ISSUE TITLE
ApiBreak plugin doesnot work both x32dbg and x64dbg

### ISSUE THREAD

**Issue by bukuxiaoheshang** [x64dbg/x64dbg#1985]
ApiBreak plugin doesnot work both x32dbg and x64dbg  in 2018.07.05 version,but it can using in 2017.10.18 version, compare with the import table, 2018.07.05 version increase two modual，it's  msctf.dll and imm32.dll，Is it because this reason？

**Comment by mrexodia** [comment]
Ask for support at https://github.com/0ffffffffh/Api-Break-for-x64dbg/issues
