### ISSUE TITLE
How to keep the breakpoints at any time

### ISSUE THREAD

**Issue by oldn123** [x64dbg/x64dbg#1986]
Hi, master
sometimes x64dbg is terminated or stopped functioning unexpectedly.  then the breakpoints maked by this time will losed. if I can save the breakpoints by menu/toolbar at any time will help to reduce the damage .

**Comment by mrexodia** [comment]
You should report when x64dbg crashes or freezes so those issues can be addressed. If you want to save the database you can use the `dbsave` command. You can add this as a favorite command if you want access to this quickly.

**Comment by oldn123** [comment]
thanks.
