### ISSUE TITLE
about bpm commad

### ISSUE THREAD

**Issue by oldn123** [x64dbg/x64dbg#1990]
hi, master
my bpm command set like this,
![image](https://user-images.githubusercontent.com/16172679/42828375-0db75a2e-8a1b-11e8-88a1-4c67599e7dfd.png)

the log was output as
![image](https://camo.githubusercontent.com/9e0050bee6d962e96a6cb22bac13214f91f2f0e6/687474703a2f2f636875616e74752e62697a2f74362f3334342f31353331383432343534782d313536363638383731382e706e67)

then , why the bpm address is not equal to the log record ?

**Comment by torusrxxx** [comment]
bpm不要加方括号，加方括号代表先以其作为指针从里面读取一个地址，再在这个地址进行操作。
