### ISSUE TITLE
little trouble

### ISSUE THREAD

**Issue by jie-xiao** [x64dbg/x64dbg#1993]
First,thanks for your work,Give us a good tool.I know x64dbg can debug a dll entry immediately.Then how can I debug a dll-export function?

**Comment by blaquee** [comment]
Write a small program that loads the dll and calls the export you intend to debug, place a breakpoint on that export and then debug it, The program would essentially call LoadLibrary and GetProcAdress() for the export you intend to use.

**Comment by jie-xiao** [comment]
ok,thanks..
