### ISSUE TITLE
Application Font

### ISSUE THREAD

**Issue by twifty** [x64dbg/x64dbg#1999]
Latest version as of this post, on Windows 10 (64bit like anybody uses 32).

I adjusted the font sizes for each of the panes without a problem. They all resized right away. However, when I tried resizing the 'Application Font', nothing happened. until I restarted the application that is. I must have set an overly large value, so when I stated up the app again it was a mess. A larger problem was navigating back to the font window. The window has a static size but the inner controls were too large to fit, causing an overflow, which prevented me from seeing/clicking the "defaults" button. I fixed the issue by shift tabbing.

I now notice an asterix/star after the "Application Font" title. Usually this would mean an accompanying message, however there is none (there is enough space under the buttons to contain one but it's empty). I'm guessing something like "Requires a relaunch" should be written there.

Also, would it be possible to resize the button bar according to the font size. Currently they are just too small. One must be very careful not to click the wrong one.

**Comment by mrexodia** [comment]
Yes, the star means you have to relaunch the app. Feel free to send a pull request to add the label you want.
