### ISSUE TITLE
Add option to display 16/8 bit registers

### ISSUE THREAD

**Issue by twifty** [x64dbg/x64dbg#2000]
Currently only the full 32 bit registers are displayed, would it be possible to add extra columns to view the 16 and 8 bits (EAX - AX - AH - AL)?

This would be handy to view things like "cmp al,1", especially after you have stepped passed the instruction.

**Comment by mrexodia** [comment]
If you have an instruction you can always click on it and look in the info box under the disassembly to see the register value.

**Comment by sebastian-heinz** [comment]
I think this would be handy too, if there is no instruction is there a way to see them?

**Comment by tnnursery** [comment]
https://www.tnnursery.net/planting-instructions/
