### ISSUE TITLE
Disable all breakpoints for x seconds.

### ISSUE THREAD

**Issue by techvoltage** [x64dbg/x64dbg#2012]
Would be good to have instead of having to manually disable them for a while. Facing this issue for a challenge I'm solving so thought would be good to have

**Comment by M-o-o** [comment]
Yes... Or a temporary "bypass breakpoints" toggle that lets the program run without breaking, while leaving the enabled/disabled state of breakpoints unchanged. Maybe even an alternative "run to here", like a "run to here without breaking", which stops at the relevant line and not any breakpoints.

**Comment by mrexodia** [comment]
I don't think this is a commonly-used feature. Feel free to implement it as a plugin and share on plugins.x64dbg.com
