### ISSUE TITLE
Confused disassembler

### ISSUE THREAD

**Issue by tathanhdinh** [x64dbg/x64dbg#2013]
I'm playing with the code base of x64dbg, there are many things that make me surprise, e.g. [get Capstone but return Zydis](https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Disassembler/capstone_gui.cpp#L205):

```
const Zydis & CapstoneTokenizer::GetCapstone() const
{
    return _cp;
}
```

I believe that is because of some previous decision about using Capstone, then [changed](https://x64dbg.com/blog/2017/10/18/goodbye-capstone-hello-zydis.html) to use Zydis. Should we refactor these codes?

**Comment by mrexodia** [comment]
Yes, I think it is a good idea to refactor this.
