### ISSUE TITLE
Debugger crashed on command 'yara'

### ISSUE THREAD

**Issue by cozil** [x64dbg/x64dbg#2015]
Debugger crashed while running command 'yara' with only one argument.

I looked into the source code, and found an issue:

```
    if(IsArgumentsLessThan(argc, 2))
        return false;
    duint addr = 0;
    SELECTIONDATA sel;
    GuiSelectionGet(GUI_DISASSEMBLY, &sel);
    addr = sel.start;

    duint base = 0;
    duint size = 0;
    duint mod = ModBaseFromName(argv[2]);
```

argv[2] is not available while running command 'yara' with only one argument.
Should check if argc > 2 before use it.

**Comment by mrexodia** [comment]
To solve this issue: remove yara from x64dbg.

**Comment by torusrxxx** [comment]
To make it clear: `if(IsArgumentsLessThan(argc, 2))` already checks the number of arguments. The real cause is Yara.

**Comment by balintf** [comment]
> To make it clear: `if(IsArgumentsLessThan(argc, 2))` already checks the number of arguments. The real cause is Yara.

This only checks that the `yara` command was given at least one argument, but the cause of the crash is that x64dbg uses the second argument at argv[2], which is only valid if argc > 2. By adding checks before argv[2] usages and some default values for the argc == 2 case, I was able to get the yara command working with only one argument.

> To solve this issue: remove yara from x64dbg.
Do you mean remove it from the 64 bit version, or remove it entirely from x64dbg? Could you elaborate on why do you think yara should be removed? (I don't use it personally, but some might find it useful)
