### ISSUE TITLE
Logging/non-break breakpoints interfere with single-stepping

### ISSUE THREAD

**Issue by M-o-o** [x64dbg/x64dbg#2017]
Aug 28 2018 version, x64.
When using step into or step over, and the next line is a no-break breakpoint (with break condition 0, e.g. for logging or command only), the program will start _running_ from that line, instead of stepping into that line. 

Possibly related to #2011, which seems a bit different.

**Comment by mrexodia** [comment]
This might also have been fixed, I didn't try yet. Feel free to try with the latest release if I don't get to it in time.

**Comment by mrexodia** [comment]
Just tried and I couldn't reproduce the problem anymore.

**Comment by M-o-o** [comment]
Yes, steps properly now and doesn't start running :+1:
