### ISSUE TITLE
EIP has wrong value after call

### ISSUE THREAD

**Issue by twifty** [x64dbg/x64dbg#2020]
A windows 10 update was forced upon me this morning. Ever since, I am not able to step through a service's `main` method.

Now, this is not necessarily a bug within x64dbg, but the people here have a deeper understanding of how debuggers interact with the system.

Here is the problem, I have a windows service, `LightingService.exe`. I copy this binary to the desktop and place a breakpoint on the very first instruction at the entry point. This instruction is a call to `__crt_init_cookie`:

`E8 6A 04 00 00 : call 47DA0B ; call to initialize EH cookie`

Stepping into the call, the EIP is `48A20B` and not the expected `47DA0B`. With the EIP being at the wrong offset, it eventually leads to an ACCESS_VIOLATION.

However, if I rename the copied binary to something like `test.exe`, everything works as it should.

Does the debugger calculate its own EIP or is it fetched from the system? If the latter then this could very well be a (new?) anti debugger feature.

Note, this problem only applies to the main method. Attaching to a running service and breaking on normal operations works just fine.

**Comment by MulleDK19** [comment]
Seeing as it works if you rename the file, perhaps the database is corrupted. Try deleting the database in the db folder.

**Comment by twifty** [comment]
I'll close this since it does appear to be a corrupt database. However, I should mention the problem is repeatable. It seems related to changing the instruction on the main entry point. If I instead patch the second instruction, it works as intended.

**Comment by mrexodia** [comment]
when loading the database x64dbg will try to restore any breakpoints you previously set. perhaps this is causing some weird behavior for you?

**Comment by twifty** [comment]
I haven't tried to reproduce the problem since. It was a combination of changing the entry point instruction, having a breakpoint set on that line and having a label set on the line. I don't know how or why windows update broke things, but it was working perfectly fine for weeks before.
