### ISSUE TITLE
"Fill with NOPs" doesn't work in x32dbg.

### ISSUE THREAD

**Issue by MulleDK19** [x64dbg/x64dbg#2022]
Works fine in x64dbg, but in x32dbg, replacing an instruction with a smaller instruction with "Fill with NOPs" ticked does not NOP the left over bytes. Sep 2 2018 build.

```asm
Before replace
00212274 | B8 00000000           | MOV     EAX, 0                                   ```

After replace
00212274 | 90                    | NOP                                              |
00212275 | 0000                  | ADD     BYTE PTR DS:[EAX], AL                    |
00212277 | 0000                  | ADD     BYTE PTR DS:[EAX], AL                    ```

**Comment by CrabstickOMalley** [comment]
Same deal. 

before:

`FF15 F0124000            | call dword ptr ds:[xxxxxx]       | 83F8 01                        | cmp eax,0x1                            |`

**Comment by mrexodia** [comment]
The bug no longer reproduces. Notice that the `Keep size` option only makes sure never more than 3 bytes will be written (for cmp eax,0x1).

**Comment by KeyC0de** [comment]
Same problem persists. It doesn't fill with nops (same size selected or not).

**Comment by mrexodia** [comment]
Can you show a screencast of the issue you’re having @KeyC0de ? As far as I can tell everything is working as intended, but that might not be what you expect.

**Comment by KeyC0de** [comment]
It's the simplest thing you can expect. I tick "Fill with nops" on x32dbg and it doesn't fill the selected assembly instruction with nops. That will be all. Would you still rather have a screenshot?

**Comment by mrexodia** [comment]
Yes that's why I asked for it.

When I said it works as expected I actually meant it.

x64dbg:
![x64dbg](https://i.imgur.com/IcZOJuL.gif)

x32dbg:
![x32dbg](https://i.imgur.com/eyUb2WY.gif)

**Comment by KeyC0de** [comment]
I have a 2-year old version. That is likely the problem then. Sorry I didn't notice it was that old.
