### ISSUE TITLE
API as a RESTFull service

### ISSUE THREAD

**Issue by KINGSABRI** [x64dbg/x64dbg#2025]
Hello guys, 
First, thank you all for your great efforts here. I'd like to ask if it's possible to make the APIs as service like RESTful (JSON) service?

The point is, writing a plugin or automating things is a little bit hard. There're some API wrappers but I'm using Ruby, and I can't find a wrapper for the API. It would be great if there is a service that allows connecting and automate things from x64dbg itself.  

- Debugger version: Snapshot Sep 2, 2018
- Operating system version and Service Pack: Windows 10 os build 17134: 32-bit

Thank you

**Comment by mrexodia** [comment]
I would definitely say this is out of scope. A plugin could definitely implement this though.
