### ISSUE TITLE
Mouse Cursor issue

### ISSUE THREAD

**Issue by KINGSABRI** [x64dbg/x64dbg#2026]
Hello guys,
There's a weird issue with mouse cursor move over the CPU, stack area and the tabs. Please check the gif.
The issue happens with older version too. 

![x64dbg_mouse-issue](https://user-images.githubusercontent.com/1071827/45382598-6af5e800-b611-11e8-9526-40d17e122905.gif)

Debugger version: Snapshot Sep 2, 2018
Operating system version and Service Pack: Windows 10 os build 17134: 32-bit

Thank you.

**Comment by mrexodia** [comment]
Remove all skins and plugins and try again.

**Comment by KINGSABRI** [comment]
Downloaded the snapshot and extracted it then use it as is. I've got the same issue

**Comment by KINGSABRI** [comment]
update: I got back to the old setup then **Options >> Reload style.css** , problem solved

HTH
