### ISSUE TITLE
the GuiMenuSetEntryVisible,GuiMenuSetName,GuiMenuSetEntryName interfaces didn't send correct message to ui 

### ISSUE THREAD

**Issue by Persimelon** [x64dbg/x64dbg#2027]
I found the GuiMenuSetEntryVisible,GuiMenuSetName,GuiMenuSetEntryName in bridgemain.cpp are not correct,they should send their own message enum rather than GUI_MENU_SET_VISIBLE

**Comment by mrexodia** [comment]
Thanks for your report.
