### ISSUE TITLE
Register read/write hints are wrong?

### ISSUE THREAD

**Issue by carlreinke** [x64dbg/x64dbg#2047]
It seems like the register read/write hints aren't quite right.  Flags seem to work properly.  A few examples below.  I'm using the default color scheme: red is write, green is read, gray is read+write.

`push esi` -- I expect that this doesn't write `esi`.
![image](https://user-images.githubusercontent.com/11667451/47134104-cc405500-d268-11e8-8e6d-2fcc92a445db.png)

`mov esi,dword ptr ss:[ebp+C]` -- I expect that this doesn't read `esi`.
![image](https://user-images.githubusercontent.com/11667451/47134441-ee86a280-d269-11e8-8923-8ae40dc4466a.png)

`div esi` -- I expect that this doesn't write `esi`.
![image](https://user-images.githubusercontent.com/11667451/47134073-aa46d280-d268-11e8-81ec-201aa50ad296.png)

`test esi,esi` -- I expect that this doesn't write `esi`.
![image](https://user-images.githubusercontent.com/11667451/47134378-b4b59c00-d269-11e8-8d96-4a8110aa0199.png) ![image](https://user-images.githubusercontent.com/11667451/47134390-c434e500-d269-11e8-8588-da311bf710cb.png)

`je` -- As expected.
![image](https://user-images.githubusercontent.com/11667451/47134361-994a9100-d269-11e8-8b3c-27417c90a124.png)

- Debugger version: x32dbg Oct 17 2018
- Operating system version: Windows 10 Home 1809 17763.55

**Comment by balintf** [comment]
I've checked it and it's a bug that was introduced with the Capstone->Zydis transition.
The code in Zydis::RegInfo treats ZydisOperandAction as a flag, however it's an enum with continuous values from 0 to 7. The code in question:
https://github.com/x64dbg/x64dbg/blob/fba7af6bcd28381c4edd68f709a134f40befc9a4/src/zydis_wrapper/zydis_wrapper.cpp#L876-L879

I'm working on a fix for this.

**Comment by mrexodia** [comment]
Hmm, I vaguely remember finding and fixing this in some other context,
totally forgot about it. Thanks!

**Comment by carlreinke** [comment]
Looks good in 2018-11-04_23-45 snapshot.
