### ISSUE TITLE
the disassembly window  is blank ,not show any disassembly

### ISSUE THREAD

**Issue by suiwang** [x64dbg/x64dbg#2048]
- Debugger version :Sep 2 2018
- Operating system version : windows7 64bit 
- Brief description of the issue.
when I attach a game to debugger,the debugger is not show any disassembly.
![bmpn1a 60xk2gq20abcxxl](https://user-images.githubusercontent.com/10204099/47159510-9f4f7900-d320-11e8-97e5-d306c5484fb6.png)

**Comment by mrexodia** [comment]
The game uses anti-attach.
