### ISSUE TITLE
dll debug

### ISSUE THREAD

**Issue by leon198686** [x64dbg/x64dbg#2050]
Hello guys has anyone put a detailed manual on the debug dll, we looked everywhere, but nowhere detailed instructions from beginning to end in x96dbg or x32dbg???Here is here description of but not full https://github.com/x64dbg/x64dbg/issues/516  after the break dll how to proceed???

**Comment by mrexodia** [comment]
You can contribute at team.x64dbg.com/docs

**Comment by leon198686** [comment]
I need help,I have nothing to contribute!Need full instructions?

**Comment by mrexodia** [comment]
Just drag the dll in the x64dbg window and you can debug the entry point.

**Comment by leon198686** [comment]
mrexodia Thank you.But I am interested in the question, and if I have a ready EXE and I need it, but rather in dll change for example je to jmp, how to do it?or just make a hook on the dll?
