### ISSUE TITLE
为什么没有debug hook 的脚本输出，和直接完全支持python？

### ISSUE THREAD

**Issue by zbx91** [x64dbg/x64dbg#2052]
想做个调试单步显示功能的小插件，搞了一天，居然不行，需要 hook _dbg_dbgcmdexec，_dbg_dbgcmddirectexec，都无从下手。唉。。。。。。。。。。。。。。
ida直接就能以python为基础脚本，非常舒服。

**Comment by torusrxxx** [comment]
x64dbg不直接支持python，因为用户可能没有安装python。

**Comment by zbx91** [comment]
x64dbg，我改了一天加了几个py插件，发现还是不足，想做个hook，使用frida还涉及通讯问题。
如果直接跟ida pro 有dbg_hook回调，就好弄很多。
x64dbg在进行分析、查找引用过程中，如果使用ctrl+g，直接卡死，然后就无法使用ctrl+g功能。
x64dbg+python可以无限遐想的。

**Comment by torusrxxx** [comment]
x64dbg有很多C++回调可供使用，你可以使用它们。

**Comment by zbx91** [comment]
单步回调没看到,cmdexec回调也没找到，这几个很关键的。

**Comment by torusrxxx** [comment]
可以用暂停回调。

**Comment by zbx91** [comment]
说下名称，我好看看。

**Comment by zbx91** [comment]
breakpoint这个回调，我在x64dbgpy中使用了，的确很迅速，好用。

**Comment by zbx91** [comment]
CB_PAUSEDEBUG, //暂停调试
CB_RESUMEDEBUG, //继续调试
CB_RESUMEDEBUG, //继续调试
CB_STEPPED, //调试步进
CB_DEBUGEVENT, //调试事件
在x64dbgpy中无法用，你可以试试

**Comment by zbx91** [comment]
CB_DEBUGEVENT, //调试事件
这个x64dbgpy中有，不过进行脚本调用后，才会使用，没什么大用。

**Comment by torusrxxx** [comment]
你可以在x64dbgpy中改进一下，不用在x64dbg提出这个问题，这个问题不是x64dbg的问题。

**Comment by zbx91** [comment]
我只觉得，要是能一起搞出来就不会出现这种问题。
我觉得我有点懒惰。不过你提醒了我。

**Comment by zbx91** [comment]
我想问，你的这个汉化，哪里来的

**Comment by torusrxxx** [comment]
我做的，我做x64dbg三年了。

**Comment by zbx91** [comment]
哦。。。加个q，一起玩玩x64dbg？
我的q是 2955254435

**Comment by zbx91** [comment]
ollydbg的dump窗口数据备份功能，这个要是有就更好了！

**Comment by torusrxxx** [comment]
去https://gitter.im/x64dbg/x64dbg聊天，不要用qq聊天。

**Comment by zbx91** [comment]
//enums
typedef enum
{
    CB_INITDEBUG, //初始化   加入反调试
    CB_STOPDEBUG, //停止 
    CB_CREATEPROCESS, //进程创建  做个log
    CB_EXITPROCESS, //进程退出
    CB_CREATETHREAD, //线程创建  做log
    CB_EXITTHREAD, //线程退出
    CB_SYSTEMBREAKPOINT, //系统断点
    CB_LOADDLL, //载入模块   做各种奇葩的事情
    CB_UNLOADDLL, //卸载模块
    CB_OUTPUTDEBUGSTRING, //调试字符串  做log
    CB_EXCEPTION, //发生异常    shot
    CB_BREAKPOINT, //进入断点   没啥大用
    CB_PAUSEDEBUG, //暂停调试     待定的东西
    CB_RESUMEDEBUG, //继续调试
    CB_STEPPED, //调试步进     关键的东西
    CB_ATTACH, //准备附加     好东西
    CB_DETACH, //准备脱离
    CB_DEBUGEVENT, //调试事件   事件后，没啥太大用
    CB_MENUENTRY, //菜单项
    CB_WINEVENT, //窗口事件
    CB_WINEVENTGLOBAL, //所有窗口事件
    CB_LOADDB, //载入数据库
    CB_SAVEDB, //卸载数据库
    CB_FILTERSYMBOL, //过滤符号
    CB_TRACEEXECUTE, //追踪步进
    CB_SELCHANGED, //选区改变
    CB_ANALYZE, //准备分析
    CB_ADDRINFO, //获取地址数据    这个很可以搞下
    CB_VALFROMSTRING, //解析表达式   [[x]+y]运算结构处理，可以试试这个 
    CB_VALTOSTRING, //执行表达式
    CB_MENUPREPARE, //准备菜单
    CB_LAST
} CBTYPE;
