### ISSUE TITLE
Create a command line parameter to attach to process

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#206]
Attaching to a process by command line with a -p <pid> parameter (example) would be cool for automating some debugging

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/206
- Originally reported by: Anonymous
- Originally created at: 2014-09-24T15:12:22.946

**Comment by Nukem9** [comment]
this is already done, take a look at JIT debugging.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by mrexodia** [comment]
this was implemented
