### ISSUE TITLE
Chocolatey package download URL is broken in 20181029.1349

### ISSUE THREAD

**Issue by laurin1** [x64dbg/x64dbg#2060]
x64dbg.portable v20181029.1349 [Approved]
x64dbg.portable package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2018-10-29_13-49.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2018-10-29_13-49.zip'.
  The remote server returned an error: (404) Not Found.
Downloading x64dbg 64 bit
  from 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2018-10-29_13-49.zip'
**ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2018-10-29_13-49.zip'.
  The remote server returned an error: (404) Not Found.**
The upgrade of x64dbg.portable was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\x64dbg.portable\tools\ChocolateyInstall.ps1'.
 See log for details.

That snapshot, snapshot_2018-10-29_13-49.zip, does not exist.

**Comment by mrexodia** [comment]
We are not maintaining this package, please contact the package author instead.

**Comment by gep13** [comment]
Just to provide some clarity around this, and hopefully to prevent any future confusion...

The Package Page on chocolatey.org for the x64dgb.portable package contains the following:

![image](https://user-images.githubusercontent.com/1271146/47901353-a5446e80-de77-11e8-87e7-9c49ffa67f88.png)

Software Site links to https://x64dbg.com/#start
Software Source links to https://github.com/x64dbg/x64dbg
Software Mailing List links to https://gitter.im/x64dbg/x64dbg
Software Issues links to https://github.com/x64dbg/x64dbg/issues

These are links that are intended to provide information about the underlying software that the Chocolatey Package contains.

For any problems with the Chocolatey Package itself, which was the case here, there are additional links in the **Package Specific** section, i.e. 

Package Source links to https://github.com/echizenryoma/Chocolatey-Package/tree/master/x64dbg.portable
Package outdated links to https://chocolatey.org/docs/package-triage-process which provides further information about reaching out about an outdated package.

**Comment by mrexodia** [comment]
I can request to take over maintenance of the package and host it under the
x64dbg team if you like. Perhaps we can set up some CI to automatically
update the package too?
