### ISSUE TITLE
Wrong Memory protection for DS

### ISSUE THREAD

**Issue by dor-alt** [x64dbg/x64dbg#2078]
Hi
I was looking for an already answered question for this but closest thing found was https://github.com/x64dbg/x64dbg/issues/1907 which didn't help.

I wrote a program which query a certain memory page for a string with VirtualQueryEx(). What I received in AllocationProtect field in _MEMORY_BASIC_INFORMATION  struct is 0x04 - PAGE_READWRITE.
When I look at the exact same string in x32dbg, on the memory map, it appears in the read only memory segment of my program , which has only Read in its protection.
I know for sure, the protection is PAGE_READWRITE becuase I was able to rewrite this string (from another exe) without changing the memory protection.

Maybe there's something I don't understand with how to read the memory map protection and would be happy for an answer. Thanks

version : x32dbg Nov 13 2018
windows: 10-64 bit

![read](https://user-images.githubusercontent.com/39267196/48580354-a5d50e80-e927-11e8-84b1-e3d6ad40d016.JPG)
![stack](https://user-images.githubusercontent.com/39267196/48580355-a66da500-e927-11e8-9c5f-511413a76679.JPG)

**Comment by mrexodia** [comment]
What did you use to rewrite the string from another exe?

**Comment by dor-alt** [comment]
I was getting the string address and just used WriteProcessMemory() to rewrite its location with some other string with the same length as the old one.
Didn't use VirtualProtect() or anything. And even without rewriting this memory address, do you know why VirtualQueryEx() did return the right protection for the memory and on x32dbg it was Read Only?

**Comment by mrexodia** [comment]
WriteProcessMemory will call VirtualProtect for you

**Comment by dor-alt** [comment]
I called VirtualProtect before the call to the WritePRocessMemory ... x32dbg still didn't change, does it supposed to change after a call like that or it stays static once the debugging process started?

**Comment by mrexodia** [comment]
In general x64dbg cannot smell you are doing something. There some heuristics (like time passing, or certain debug events) that cause the memory map to re-populate. This is a costly operation, so it cannot be done every millisecond...

**Comment by dor-alt** [comment]
Got it, so can you please just explain (or refer to some docs) what's the differnce between the protection and initial columns?

**Comment by mrexodia** [comment]
You can find the source code here: https://github.com/x64dbg/x64dbg/blob/development/src/dbg/memory.cpp#L27

Protection is the 'current' protection (depending on your memory map view this can be wrong, see source code for details). Initial is the protection that was passed to VirtualAlloc.
