### ISSUE TITLE
xed

### ISSUE THREAD

**Issue by DiskGetor** [x64dbg/x64dbg#2081]
hello,can you post one test for win32 project with xed? i used your lib not work so,thank you.

	//FFFFF80003EE77F1 [15] 0x66,0x66,0x66,0x66,0x66,0x66,0x66,0x0F,0x1F,0x84,0x00,0x00,0x00,0x00,0x00,     nop [rax+rax*1], ax 
	//XEDPARSE_EXPORT XEDPARSE_STATUS XEDPARSE_CALL XEDParseAssemble(XEDPARSE* XEDParse);
	XEDPARSE a;
	a.x64=TRUE;
	PCHAR t=nullptr;
	XEDParseAssemble(&a);

**Comment by mrexodia** [comment]
I don’t want to support xedparse anymore, but you can open an issue on the repo
