### ISSUE TITLE
Invalid KiFastSystemCall hook in ScyllaHide

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#2082]
x86dbg build (latest 18.11.2018)
scyllahide - 2018-08-27_08-49
Windows 7 x86 SP1

Invalid disassembly or something else leads to invalid hook placement for KiFastSystemCall
1) before hooks
![valid](https://user-images.githubusercontent.com/1623540/48715216-50a24100-ec36-11e8-8b55-c1c87e83cea1.png)
2) after DRx protection is on
![invalid](https://user-images.githubusercontent.com/1623540/48715277-72032d00-ec36-11e8-89e5-0b16862a01eb.png)
Hook placed at wrong addr.
3) new invalid KiFastSystemCall 
![invalid2](https://user-images.githubusercontent.com/1623540/48715489-f190fc00-ec36-11e8-91a6-18ff40532eec.png)

**Comment by mrexodia** [comment]
github.com/x64dbg/ScyllaHide
