### ISSUE TITLE
DbgCmdExec remove spaces

### ISSUE THREAD

**Issue by Ahmadmansoor** [x64dbg/x64dbg#2085]
-  Debugger version (18-Nov 2018).
- Operating system: Windows 7 SP1 x64.

DbgCmdExec("log This is test"); >> thisistest
it removes spaces and it changes the status of the words

DbgCmdExecDirect("log 'a b'"); >>'ab'

**Comment by mrexodia** [comment]
Yes, this is expected and documented behavior. You can use quotes to prevent this.
