### ISSUE TITLE
Helper window for current line shows wrong value

### ISSUE THREAD

**Issue by kumpuu** [x64dbg/x64dbg#2090]
Here is a screenshot of what I mean.

![bug](https://user-images.githubusercontent.com/24507920/49965664-1fa7ea00-ff1e-11e8-9e5b-fe0e59e8681d.png)

As you can see it shows the correct value in the dump, and watchdog also works.
I'm not sure how others could reproduce it as I doubt it's a very common issue and my test setup is nontrivial.

Version Nov 27 2018 (x32dbg.exe)
Win 10 Home 1803 x64

**Comment by torusrxxx** [comment]
Reproduce it by:①follow its operand in dump②modify its operand and see the infobox is updated③press "Ctrl+Backspace" to undo the change and see the infobox is not updated.
The dump has a periodic update event but the infobox doesn't, but it is expected that you can manually update it by clicking on the instruction.

**Comment by kumpuu** [comment]
I think you mean something else, I did not manually edit anything and clicking on the instruction does not update it to the correct value either.

**Comment by mrexodia** [comment]
The reason is that qword sized operands are not supported in 32 bit mode.

**Comment by kumpuu** [comment]
Ah I see. Maybe they should be? It was a very confusing moment and I wasted a lot of time before checking manually.

**Comment by mrexodia** [comment]
I made a fix, but forgot to push it 🤦‍♂️ New snapshot should be up soon...

**Comment by kumpuu** [comment]
Awesome, thanks.
