### ISSUE TITLE
Can't find datacopy dialog

### ISSUE THREAD

**Issue by brayanfernandes** [x64dbg/x64dbg#2091]
was this feature removed?

![sem titulo](https://user-images.githubusercontent.com/16024973/50055093-25c1e480-0131-11e9-9c57-66e10a5e4eab.png)

my current version

![capturar](https://user-images.githubusercontent.com/16024973/50055113-6f123400-0131-11e9-85dc-cb9c33ea101d.PNG)

**Comment by mrexodia** [comment]
It has been moved to the binary edit as a tab, but I’d like to move it
back...

**Comment by brayanfernandes** [comment]
I found, Thank you mrexodia.
