### ISSUE TITLE
Problem with patches

### ISSUE THREAD

**Issue by alexxx6** [x64dbg/x64dbg#2092]
https://drive.google.com/file/d/16mJ_2t8kLfIlf4xQ1jDPyNf966nxNCCJ/view?usp=sharing

**Comment by mrexodia** [comment]
you cannot patch outside a module

**Comment by alexxx6** [comment]
what should I do to make it possible?

**Comment by mrexodia** [comment]
You cannot patch something that is not loaded from a file on disk (eg a
module). Is is not possible to do what you want.
