### ISSUE TITLE
Add official themes (including a dark theme, or maybe a few)

### ISSUE THREAD

**Issue by fredddii** [x64dbg/x64dbg#2096]
This would be a very nice feature. I know there are many themes out there but I would like to have this functionality built-in, in the same fashion that Notepad++ does.

**Comment by mrexodia** [comment]
I am not against this per-se, but I don’t want to maintain themes. Perhaps some sort of theme selector could be done though, and a location that aggregates all community themes.

**Comment by torusrxxx** [comment]
There is dark theme
