### ISSUE TITLE
[Feature request] Make "Topmost" option permanent after closing x32dbg

### ISSUE THREAD

**Issue by bartlomiejduda** [x64dbg/x64dbg#2097]
- Debugger version: **Nov 4 2018**
- Operating system version: **Windows 7 64bit**
- Brief description of the issue
**Hello. I have one small feature request. Could you please make "Topmost" option to be set permanent after closing x32dbg? Because I have to enable it each time debugger starts. It would be very helpful to save this setting.**
- Elaborate reproduction steps for the bug/issue being reported: **None**

- A short clip or a screenshot clearly showing the issue.
https://i.ibb.co/cDKG8Sn/screenshot000904.png 

- The translation you are using. Make sure to also test without translation: **English**
- Plugins you have installed. Make sure to also test without plugins: **None**

**Comment by torusrxxx** [comment]
An application that automatically puts itself "Topmost" is always annoying, as it can hide your window, and even worse when it opens a modal dialog and makes the main window topmost, you can't input and finish your dialog and the application is essentially deadlocked. Therefore it might not be a good choice to always make "topmost" option permanent. Though we can add a setting in the settings dialog (x64dbg doesn't put itself back topmost when settings dialog is open now).
