### ISSUE TITLE
Cannot specify command-line parameter!

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#210]
x64_dbg does not accept any parameters when invoked from the command line.  The parameters can be entered manually, but the debugger should allow any and all parameters to be specified.  (Note: the Windows call GetCommandLine lists all the parameters, but they are separated by spaces, not nulls; it seems that x64_dbg does not first separate the parameters from the name of the file to be debugged, and so it thinks the file name is invalid.)

Please fix, thank you!

ejamesr

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/210
- Originally reported by: [ejamesr](http://bitbucket.org/ejamesr)
- Originally created at: 2014-10-25T21:12:24.233

**Comment by Nukem9** [comment]
This issue is regarding x64_dbg v22.

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
There is no such thing as 'command line parameters'. The actual fields that allows 'command line parameters' include the full executable path, that's just how windows works.

If you want to specify the commandline parameters manually before starting the debuggee you should read the help, it was there since V1

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Sorry, there is no help file in release_022.rar.

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
Oh, sorry about that. I think I forgot to compile it before compressing the release. The latest version of the help can be found at http://help.x64dbg.com

Greetings

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
If I write on the command line: "x64_dbg MyProgram.exe parm1 parm2", everything after "x64_dbg" is a command-line parameter.  The Windows call returns the full path for the executable, inserts spaces between each one and adds a terminating null.  I'll try to find a prior version to read the help file, thank you.

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
Ah, the commandline for x64_dbg is undocumented (you should use the launcher `x96_dbg.exe` for that.

It actually is `x64_dbg.exe "C:\FullPathTo\File.exe"`

You can specify a commandline with the `InitDebug` command (http://x64dbg.com/help/scr/InitDebug_initdbg_init.htm).

The alternative is to just load the target and set the commandline after that manually.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Manually works.  But I would like the computer to make my life easier!

So, I would like to type 
```
x64_dgb "C:\FullPathTo\File.exe" parm1 parm2 -3 -4 -debug
```
in my batch file or command script in Notepad++.  This is what I've been able to do, for just about every program I've used for the last 35 years, so please excuse my habits and expectations.

Could you keep this request on a suggestions list?

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
Hi,

Okay, I will keep the issue open. Please make clear what you want in the first post so everyone can work on this.

Greetings

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Good point, I'll do better in my next posts.

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by meepdarknessmeep** [comment]
Not to bug anyone, but can this get added?

**Comment by mrexodia** [comment]
@meepdarknessmeep are you looking for using x64dbg from the commandline or changing the commandline of the debuggee? Because the latter was done a long time ago. See the [FAQ](http://faq.x64dbg.com)

**Comment by meepdarknessmeep** [comment]
Was hoping for running x64dbg from command-line with command-line arguments
for the other program!  :)

**Comment by mrexodia** [comment]
Feel free to implement it yourself. I don't plan to at the moment.

**Comment by mrexodia** [comment]
If you really want to use the command line you can also use x96dbg.exe by
the way

**Comment by mrexodia** [comment]
Okay, currently undocumented but it's implemented.

Executing: `x96dbg.exe c:\test32.exe arg1 arg2 arg3`

Will open `x32dbg.exe "c:\test32.exe" ""arg1" "arg2" "arg3""`

Which runs `x32dbg.exe` and executes the command `init "c:\test32.exe", "arg1 arg2 arg3"` effectively forwarding your command line arguments.
