### ISSUE TITLE
int3 (debug interrupt 'CC') not easily skipped

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#211]
**Problem**: After int3 (debug interrupt 'CC') is encountered during debugging, execution stops (this is good), but no simple keystrokes allow execution to continue. To continue, I have found that if I press 'DownArrow' and then Ctrl-*, that will sometimes make the next instruction the current (Set New Origin Here).  More than half the time, this does not work, and the RIP goes back to the int3.  Then, debugging can continue.  Also, clicking on the next line, then right-clicking and selecting Set New Origin Here does the same, and most of the time I have to repeat the process.

**What is wanted**: Immediately after execution stops due to 'int3', be able to press F7 or F8 and continue (as in Ollydbg, similar in other debuggers) by skipping over the 'int3' instruction and setting RIP at the next instruction.

**Background**:  I debug my own code by inserting 'int3' statements wherever I want the debugger to stop so I can debug at that point.  But x64_dbg behaves differently from the other debuggers I also use (Visual Studio, Windbg, and Ollydbg).  With the others, pressing F7/F8 (or F10/F11) causes the program to immediately skip over the 'int3' instruction and resume with the next line.  x64_dbg feels awkward compared to the others.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/211
- Originally reported by: [ejamesr](http://bitbucket.org/ejamesr)
- Originally created at: 2014-10-25T22:13:56.221

**Comment by Nukem9** [comment]
DBG: resolved issue #211 (added a 'skip' command to skip the next instruction)


-> <<cset 3b755c927914>>

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
You are right about that it "feels awkward", but in my opinion x64_dbg is one of the few debuggers handling this thing correctly. Various debuggers handle INT3 commands as if they are breakpoints, meaning they swallow the exception, leaving the debugger open for detection mechanisms like:


```
#!c++

BOOL TestDebuggerSwallowsException()
{
    __try
    {
        RaiseException(STATUS_BREAKPOINT, 0, 0, 0);
    }
    __except(1)
    {
        return FALSE; //all good, debugger did not swallow the exception
    }
    return TRUE; //debugger detected
}
```

Above code inspired from: http://www.autosectools.com/anti-debugging-with-exceptions.pdf

Simply ignoring exceptions is not supposed to happen, but to fix the awkwardness I added a command `skip` that simply sets the IP one instruction forward (in addition to swallowing the exception, so be careful using this).

The reason you had to repeat the process is first and second chance exceptions. First chance is before the exception is thrown at the debuggee. Second chance is after all possible handlers are called (could be none) and the application would normally crash. The `skip` command takes care of this for you.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Thank you, having the 'skip' command is certainly an improvement.

I insert 'int3' commands at the points where I want my assembly-language
code to stop (this is in addition to any breakpoints I might set once the
debugger runs; in fact, this is the best way to set breakpoints at
strategic points in the code I'm debugging).  So, I prefer this be handled
exactly as a breakpoint, because each int3 I insert actually is a
breakpoint.  It is not an error (as is almost every exception), it is by
design.  I just want the program to stop at that point so I can inspect
memory, CPU flags, variables, etc.  Olydbg and Windbg handle this in the
way that makes debugging flow smoothly, exactly as a manually-place
breakpoint would do.

I have no experience with the detection methods you write about, so I can't
speak to that.  In any case, I look forward to testing the new version, thx!

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
I assigned the `skip` command to the keyboard shortcut `Ctrl+F8`. You can download the latest snapshots from http://snapshots.x64dbg.com

This will be all I can possibly do to ease your manual debugging habit.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by sdcode** [comment]
Sorry to reopen this, but having used x64dbg for a few weeks now, I must say this is the biggest nuisance in an otherwise marvelous software. When the debugger hits an int 3, and the USER hits F7 or F8, this is IMHO an absolutely clear expression of interest to skip the int 3 and continue with the next instruction. What else would induce the user to hit F7? And having to use the other hand to press Ctrl is not user-friendly. Really, it's torture. This software is so crammed full of features and options, why not insert one "skip int 3 on F7/F8"?

**Comment by mrexodia** [comment]
There is, just use ctrl+f8 the reason has been discussed several times and
the current behavior will stay.

**Comment by sdcode** [comment]
Congrats, there are still people with principles!

**Comment by mrexodia** [comment]
I don't quite get the fuzz over this.. If you dislike the behaviour of the
step function, remove the hotkey, write a plugin command that has your
desired behavior and bind it to a hotkey.

The reason (even though I'm repeating myself) is for exception handling. If
you are holding f7 and this behavior were default it would swallow the
exception exposing the debugger for detection.

Also I'm not against people sending a pull request that doesn't change the
default behavior but adds an option to enable your desired behavior, I just
don't want to change the current behavior.

**Comment by sdcode** [comment]
> I don't quite get the fuzz over this
Yes indeed, you don't get it. You will never get it.

**Comment by mrexodia** [comment]
Excuse me? Is there something wrong with you?

**Comment by sdcode** [comment]
No, I'm fine, thanks.

**Comment by mrexodia** [comment]
I have added an option especially for cocksuckers, see http://imgur.com/gallery/GVgNn for the full gallery.

![cocksucker1](http://i.imgur.com/4UR93UO.png)

![cocksucker2](http://i.imgur.com/peCgU5e.png)

![cocksucker3](http://i.imgur.com/uvRkDfY.png)

Take as much offence as you like, but try to keep it nice. Comments like yours are destructive for the open source community and they are not welcome here. I'm usually polite to everybody but I do see this as a problem. Nice, hardworking people keep open source projects like this going and being polite is the least you can do to pay them back.

**Comment by mrfearless** [comment]
I created two plugins for stepping over int3 exception_breakpoint's (one for x32dbg.exe, the other for x64dbg.exe) to place in their respective plugins folders.

I'm including them here in case the option is reverted as some stage. Hopefully they work as intended.

[StepInt3.dp32](https://dl.dropboxusercontent.com/u/17077376/x64dbg%20Plugins/StepInt3.dp32)
[StepInt3.dp64](https://dl.dropboxusercontent.com/u/17077376/x64dbg%20Plugins/StepInt3.dp64)

**Comment by sdcode** [comment]
Duncan, in over 30 years of programming I've never ever encountered such an arrogant asshole as you are. In all honesty: You need professional advice.

**Comment by codygray** [comment]
I just grabbed the latest version of x64dbg, saw this strange option in settings, and clicked on the link. (I know, I know, what was I thinking?) Language like this has absolutely no place in a quality piece of software.

> Take as much offence as you like, but try to keep it nice. Comments like yours are destructive for the open source community and they are not welcome here.

Duncan, I honestly don't understand your attitude here. You are accusing others of being not "nice" and "destructive [to] the open source community," but then you go and put verbiage like "cocksucker" in a prominent place in your software's user interface. It is not a cultural misunderstanding where you don't realize the term is offensive; you grant as much where you say that sdcode can take as much offence as (s)he likes. Please understand that *other people* are likely to take offense just looking at your software, and that inserting these kinds of slurs is far more toxic for the open source community (or, indeed, *any* community) than some bickering on a bug-tracker forum.

If you want to state your case, and even argue for it vehemently with strong language, be my guest. It worked well for Linus; your mileage may vary. But please reconsider where you are drawing the line. If you are going to put the option into the UI, use neutral language. If you feel so strongly that it should not go there, then just exercise your discretion not to put it in.

**Comment by mrexodia** [comment]
@sdcode @codygray and everyone involved, my apologies for the strong language. I just had a bad day. I just removed the strong language and changed the option name to `Skip INT3 Stepping`.

**Comment by sdcode** [comment]
Thanks, Duncan. Keep up the good work, it's really a very good debugger.

**Comment by ethernidee** [comment]
@mrfearless , could you reupload your plugins? Both CTRL + F8 and down + ctrl + * do not work properly. Even old OllyDebugger handles those int 3 in a friendly way.
