### ISSUE TITLE
Memory Map displays incorrect/old Protection

### ISSUE THREAD

**Issue by dauthleikr** [x64dbg/x64dbg#2111]
- Debugger version: Jan 20, 2019
- Operating system version: 10, v1803

Short description: The Memory Map is not accurate / does not refresh its protection

Steps to reproduce:
1. Run this:
`	std::cout << "Press enter to reprotect" << std::endl;
	std::cin.get();

	DWORD oldProtect;
	const auto addr = reinterpret_cast<void*>(MessageBoxW);
	std::cout << "Reprotecting " << std::hex << reinterpret_cast<uintptr_t>(addr) << std::endl;
	VirtualProtect(addr, 0x1000, 0x4, &oldProtect); // reprotect the page to ReadWrite (no execute)
	
	std::cout << "Check protection" << std::endl;
	std::cin.get();

	MessageBoxW(nullptr, L"Howdy", L"Test", 0);
`
2. Attach at the first promt, check the mem section of MessageBoxW, it's ER---
3. Press enter, get to "Reprotecting ...."
4. Check the mem section in x64dbg, the protection still claims to be ER---
5. Press enter again, program crashes because of accessviolation (it's -RW-- after all)

if this is intended, a "refresh" context menu or something alike would be appreciated.

**Comment by mrexodia** [comment]
If you want a more accurate (but in my opinion often useless)
representation of the memory map you can switch the view with the “switch
view” context menu option.

**Comment by kleberfh** [comment]
Please remove me from this,  i,ve muted already but I’m receiving this anyway.
Em 27 de jan de 2019 23:34 -0200, Duncan Ogilvie <notifications@github.com> escreveu:
> If you want a more accurate (but in my opinion often useless)
> representation of the memory map you can switch the view with the “switch
> view” context menu option.

**Comment by dauthleikr** [comment]
> 
> If you want a more accurate (but in my opinion often useless) representation of the memory map you can switch the view with the “switch view” context menu option.

Yes that works nicely. What's the difference between the two? One refreshes and one doesn't?

**Comment by mrexodia** [comment]
Both refresh periodically and when certain debug events happen. The
difference is that the default view combines pages with the same
AllocationBase, whereas the alternative view doesn’t.

**Comment by dauthleikr** [comment]
> Both refresh periodically and when certain debug events happen. The difference is that the default view combines pages with the same AllocationBase, whereas the alternative view doesn’t.

Ok thanks for explaining. I'm going to close this since it's no bug
