### ISSUE TITLE
Can't save database. Permission issue. Required elevation poses security risk.

### ISSUE THREAD

**Issue by AntonVonDelta** [x64dbg/x64dbg#2118]
Some time ago I had some crashes while debugging an exe. The database was not saved and I was very frustrated "Failed to write database file !(GetLastError() = ERROR_ACCESS_DENIED: Access is denied.)". I noticed it was by default saved in the Program Files directory and the debugger did not have writing access to that folder. To overcome this I enabled Run as admin option for the x96dbg.exe file. The database is successfully saved but the program I was debugging now seems to be dropping some files in temp folder. I looked at its permission and it is elevated. If by mistake I let the code to run it is a very important security risk. How can I save the database to a custom place? And why is the debugger opening files with its permissions?

**Comment by mrexodia** [comment]
The requirement when running x64dbg is that you do so from a writable
directory (Documents, AppData, whatever). Per default databases are written
to the db subfolder and not to the directory of the program you are
debugging.

**Comment by AntonVonDelta** [comment]
Very important: I have the x64dbg file in Progrma Files. Is it portable? Can I just move it to D:/ ?

**Comment by mrfearless** [comment]
Yes just copy the folder to another place. Run the x96dbg.exe and choose setup

**Comment by mrexodia** [comment]
@AntonVonDelta Where did you get x64dbg from? We have no installer, if you got an installer it's third party and probably littered with malware.

**Comment by AntonVonDelta** [comment]
Well it is in my Program Files folder so there should have been an installer of some kind. I don't quite remember it was some time ago. I think I took the exe from github..it was a snapshot.

**Comment by mrexodia** [comment]
The release on GitHub is up to date with the latest commit on develop,
compiling it yourself doesn’t give any benefits...
