### ISSUE TITLE
x64dbg.pro build error

### ISSUE THREAD

**Issue by hazedic** [x64dbg/x64dbg#2126]
The following error occurs when trying to build. 
I'd like to know how to solve it.

Qt version: qt-5.6.2-x64-msvc2013, qt-5.6.2-x86-msvc2013
QtCreator version: qtcreator-4.3.1

![image](https://user-images.githubusercontent.com/13882826/53301513-18467a80-3897-11e9-99f9-99b3e1f73cb8.png)

**Comment by mrexodia** [comment]
In theory this shouldn’t happen. Did you follow all steps on the wiki correctly? build.bat is what is used to build on the CI and everything is green...

**Comment by hazedic** [comment]
I recorded the process of setting up dev environment and building x64dbg.

https://drive.google.com/open?id=1BfdAyQ37fQm0vmVaPoyDbUXrCm4tIpiq
