### ISSUE TITLE
Russian string?

### ISSUE THREAD

**Issue by antosha22rus** [x64dbg/x64dbg#2130]
Hi, mrexodia. I noticed that x64dbg does not display Russian string (search in > current module > string references). How to enable the display of Russian string?
![image](https://user-images.githubusercontent.com/37859984/53681821-73f28700-3d21-11e9-8833-7a958977e60b.png)

**Comment by mrexodia** [comment]
Currently there is no string search for non-English characters because I don’t use that feature.

**Comment by antosha22rus** [comment]
_I hope that in the future you will add a Russian string :)
Thanks for x64dbg_

**Comment by mrexodia** [comment]
There are no plans for this feature. Over time I have realized that it
often makes no sense to develop a feature like this that I will never use
myself and will thus go completely untested. This is the reason x64dbg is
open source. You can try adding this feature to suit your needs and if you
want (see GPL license) you can share it with us too :)

**Comment by mrexodia** [comment]
Perhaps try https://github.com/horsicq/stringsx64dbg in the meantime.

**Comment by Symbai** [comment]
@mrexodia Can you tell me where in the source is the check if a string is valid or not regarding the string references?

**Comment by mrexodia** [comment]
@Symbai https://github.com/x64dbg/x64dbg/blob/development/src/dbg/disasm_helper.cpp#L259

**Comment by torusrxxx** [comment]
#2406
