### ISSUE TITLE
Patches not saving 0/x

### ISSUE THREAD

**Issue by SniperHero007** [x64dbg/x64dbg#2135]
So, I've been searching around and didn't find any working solution for my problem. The problem I have is pretty self explanatory (title). Is there any way to fix this problem? Anything else I could attach to understand my problem?

**Comment by mrexodia** [comment]
This should be in the FAQ. You cannot patch something that does not exist
on disk.

**Comment by SniperHero007** [comment]
Here, I made a screenshot... It exists because when I change it right before the exe want to go there, it works, but the patch doesn't...

![image](https://user-images.githubusercontent.com/46090897/53840232-47996d80-3fa2-11e9-9b08-d5db0d84345e.png)

**Comment by mrexodia** [comment]
My guess, the code is put there at runtime. Check the section table in a pe editor and see if that section has a raw address + size. If it does there is a bug in x64dbg. Otherwise it’s just the same story: you cannot patch something that does not exist on disk.

**Comment by SniperHero007** [comment]
I'm sorry, I'm new to this, what program should I use and how should I do this?

**Comment by mrexodia** [comment]
Cff explorer works. I recommend watching some malware analysis videos about
pe unmapping to get up to speed.

**Comment by SniperHero007** [comment]
Does this mean it has?

![image](https://user-images.githubusercontent.com/46090897/53899914-f477f700-4043-11e9-80d7-eca1dd59a06e.png)

**Comment by mrexodia** [comment]
http://faq.x64dbg.com

**Comment by MahdiJamal** [comment]
I had the same problem, then I realized that the program was compressed with upx

After I unzipped and tested again, the problem was solved
