### ISSUE TITLE
Black background color in Trace tab when not in debugging mode

### ISSUE THREAD

**Issue by WallyCZ** [x64dbg/x64dbg#2138]
1. Record and stop some trace and you will see something like that in Trace tab (that is expected):
![obrazek](https://user-images.githubusercontent.com/13380548/53945439-ecf73300-40c1-11e9-9702-d52af1b33015.png)

2. But after stopping debugging via Close button on toolbar black backround color behind opcodes appears (if not, switch to another tab and back):
![obrazek](https://user-images.githubusercontent.com/13380548/53944578-faabb900-40bf-11e9-9ccf-70f30e0b446d.png)

Debugger version: x32dbg Jan 20, 2019
OS: Windows 10 x64 1809

**Comment by torusrxxx** [comment]
Thank you for your report and it is fixed now.
