### ISSUE TITLE
Wrong .DLL Symbols displayed during debugging

### ISSUE THREAD

**Issue by willi-neu9** [x64dbg/x64dbg#2139]
Hi,

In newer releases of X64DBG 64 Bits (In Version of July 2018 this bug is not displayed) using the attached .DLL the wrong Symbol names are displayed during debugging. See attached .JPEG files. 

If you look into attached "Before_GetProcessAddress_Call.jpeg" you see that EDX points to the symbol Name "ERR_load_crypto_strings"

If you look into attached file: "After_GetProcessAddress_Call.jpeg" you see that address for "ERR_load_crypto_strings" is loaded into RAX register but "libeay321.ERR.get_error" is wrongly displayed.

You can try youself by unpacking attached archive in any directory

Just run "x64_wrong_symbol.exe". It has an embedded breakpoint to load x64dbg on demmand. See name of symbol which address should be loaded and the displayed name of symbol loaded in RAX after you have debuged over GetProcAddress.

Used Windows Version Windows 7 64 Bits.

Best regards

/Willi/

PS. If you need more information, just let me know!

[x64wrong_symbols.zip](https://github.com/x64dbg/x64dbg/files/2942885/x64wrong_symbols.zip)

**Comment by mrexodia** [comment]
Yeah confirmed, something appears to be wrong with the export table parsing here...
