### ISSUE TITLE
Patch file dialogue box not working on Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by MechDR** [x64dbg/x64dbg#2140]
Pretty self explanatory... the dialogue box shows up, but it doesn't contain any patches.

![SHOT7008](https://user-images.githubusercontent.com/45944962/54875385-6c913b80-4dfe-11e9-8c75-cdddc4e6ad90.png)

- Debugger version:  Mar 22 2019 x86 **(have to add that this only happens in the x86 version, the dialogue on the x64 version works fine).**
- Operating system: Windows Server 2008 R2 Enterprise (6.1, build 7601, last updated March 15th 2019).
 - Reproduction steps: Open an x86 exe (any, tried it with a few, doesn't seem to matter) in x86dbg, change something (anything really) and try to save the patches. Also tried with an older version (Jan 20 2019), has the same bug.

Of course, this doesn't happen in Windows 7 Ultimate x64 (only tried it in a VM and the VM is really out of date, haven't updated it in forever... 2 or 3 years out of date for sure), but, what I can confirm is that the dialogue box **does work** on Windows Server 2008 Datacenter R2 SP1 in a VM (also out of date, but not 2 or 3 years out of date... perhaps a year or so).

And thanks for the great work you're doing :+1: . Means a lot :).

**Comment by MechDR** [comment]
Just an update. The issue might be resolved. I just found out that one of my DIMMs was malfunctioning so this was probably the beginning of a series of weird behaviors. The patch dialogue seems to be working fine now ;).

**Comment by mrexodia** [comment]
Pretty strange, feel free to close the issue if it really disappeared... I couldn't reproduce any of it myself...

**Comment by MechDR** [comment]
Yeah, I'm closing it. If the issue does reappear, I'll probably open it again (or open a new one ???... I'm kinda new to GitHub :P :D).
