### ISSUE TITLE
Documentation: How or where to get the references for setting up a trace log? e.g. comment 

### ISSUE THREAD

**Issue by BlenderViza** [x64dbg/x64dbg#2141]
I want to create a trace log with all instructions. I have already found out that I need to do something like the following:

![image](https://user-images.githubusercontent.com/48265422/55041711-95981300-502e-11e9-913c-9670d395fd1d.png)

I would also like to output my comments and labels. 
How to do this?

Where can I look up the reference names for the format string? Not only for comments and labels but also for every outputable property.

**Comment by BlenderViza** [comment]
How do get a line break in the log file?

I tried: 

command 
```
mov CR, d
mov LF, d

```
Log Text 
```
|{modname@cip}|0x{p:cip}|{i:cip}|{ascii[;length]@address}|{CR}{LF}
or
|{modname@cip}|0x{p:cip}|{i:cip}|{ascii[;length]@address}|{x:CR}{x:LF}

```
with error:

`|ntdll.dll|0x00007FFEA15DC93F|add rsp, 0x38|[Formatting Error]|DA`
|

**Comment by BlenderViza** [comment]
I can't find a function to determine the memory address of comments from the user database.

Is it ever possible to output comments or am I missing something?

**Comment by mrexodia** [comment]
If you want to use the trace log feature, see the documentation: http://help.x64dbg.com/en/latest/introduction/ConditionalTracing.html

If you just want to log all instructions and their context, see the documentation: http://help.x64dbg.com/en/latest/gui/views/Trace.html

In short, read the documentation.
