### ISSUE TITLE
Rubbish files in latest snapshots? (after 2019-04-06)

### ISSUE THREAD

**Issue by Tim-Sobolev** [x64dbg/x64dbg#2143]
Are such files rubbish and should be excluded from snapshot archive?

x32/x32_bridge.dll
x32/x32_dbg.dll
x32/yara.dll
x64/x64_bridge.dll
x64/x64_dbg.dll
x64/yara.dll

**Comment by mrexodia** [comment]
What files?

**Comment by Tim-Sobolev** [comment]
Added missed file list in first message.

**Comment by mrexodia** [comment]
Hm, I thought I excluded yara... the other dlls are there for backwards compatibility.

**Comment by Tim-Sobolev** [comment]
OK, thanks for quick response.
