### ISSUE TITLE
Consider removing (broken) BreakModule plugin from Wiki Plugins page

### ISSUE THREAD

**Issue by rmi1974** [x64dbg/x64dbg#2148]
Hello folks,

I would like to request the removal of **BreakModule** plugin from Wiki -> Plugins page.

> BreakModule by ThunderCls: This plugin is intended to give the user the option to pause the execution of the debugged application when the specified modules are loaded.

The plugin is simply broken on modern Windows OS and Linux/Wine where I found/analysed the issue. See my comment here for analysis: 

https://github.com/ThunderCls/BreakModule/issues/1#issuecomment-485349790

According to https://github.com/ThunderCls/BreakModule/issues/1#issuecomment-262250002 the the plugin is obsoleted/superseded anyway by x64dbg functionality. So what's the point of listing a broken (abandoned) plugin then?

Regards

**Comment by ThunderCls** [comment]
The Plugins Wiki has been updated.

**Comment by mrexodia** [comment]
Sup @ThunderCls how are things?

**Comment by ThunderCls** [comment]
> Sup @ThunderCls how are things?

Hey pal @mrexodia ...everything's ok, I've been "off" for some time now, kinda busy actually with work/study and whatnot...but doing good tho, always try to keep up on telegram even tho I rarely write. Glad to read you and see you're ok...c ya around mate!

**Comment by mrexodia** [comment]
Good to know you’re okay 😊
