### ISSUE TITLE
Weird tab and context menu icon problem

### ISSUE THREAD

**Issue by MechDR** [x64dbg/x64dbg#2151]
Has anybody had this issue?

![SHOT7033](https://user-images.githubusercontent.com/45944962/56541515-387b7880-656c-11e9-88fe-996b92b6122f.png)

The weird thing is that... it started by itself, out of nowhere. The problem even reflected in all my VMs. Weird.

And then, everything was back to normal after I restarted the rig...

On the other hand, the drop down menus were not affected by this at all (all of the menu icons were as they should be).

- Debugger version: Latest build, Apr 17 2019, but this weird icon problem was also visible on older versions.
- Operating system: Windows Server 2008 R2 SP1, but was also visible in every single VM I have running (Windows 7 x86/x64, 8.1 x86/x64, 10 LTSC 2019 x86/x64)
- Reproduction steps: Have no idea... everything was back to normal after I restarted the rig.

PS: I wrote in another bug report that the issue I was having at that time was probably related to a malfunctioning DIMM and currently, that DIMM is removed and all of the other DIMMs have been tested individually and all together with Memtest. So, I don't think this is hardware related.

**Comment by mrexodia** [comment]
Ever hear of easter? 😉

**Comment by MechDR** [comment]
Oh, it's an Easter egg :D. Sorry, I'm orthodox, completely forgot that it's catholic easter ;).

Good joke though ;) :).
