### ISSUE TITLE
Symbols -> Copy -> Whole Table

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#216]
When using Copy->Whole Table from Symbols not all data transfered after Paste. Data lost depend on the width of the columns: Address, Symbol, Symbol(undecorated).

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/216
- Originally reported by: [Bailar](http://bitbucket.org/Bailar)
- Originally created at: 2014-11-14T01:29:45.575

**Comment by Nukem9** [comment]
Hi,

It is programmed like this on purpose. You copy the table as you see it, because in tutorials or quick snippets this looks best. What is the reason you need the whole table?

Greetings

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Hi Mr. eXoDia,

When analyze program with a lot of custom dlls copy tables is very handy feature.
In x64dbg You have to click on some dll on the right than type text in search field. Than select another dll
and search again etc...  

With "copy table" You can copy functions from all dlls to notepad++ for example and search something in parallel.
The problem is that before copy I always have to change width of the columns in order to not lose some characters. But if it's a feature than ok. 
Just a slight inconvenience for me.


----------------------------------------
Original comment by: [Bailar](http://bitbucket.org/Bailar)

**Comment by mrexodia** [comment]
create another option that doesn't trim/expand and just gets the data directly (this will look ugly)
