### ISSUE TITLE
Save information window in trace

### ISSUE THREAD

**Issue by Elinpf** [x64dbg/x64dbg#2160]
I want to see the register information and the corresponding memory information at the time of tracking. What should I do?
X64dbg seems to have not saved the information in the information window in the trace window. Is there any plugin that can achieve this?

thanks.

**Comment by mrexodia** [comment]
No, this is not possible right now unfortunately. Is there any information you want to save specifically?

**Comment by Elinpf** [comment]
I found that if the text in the information window is saved in the trace, then the state of the register and its corresponding memory state can be seen at the time of backtracking.
Autocomments doesn't help with backtracking at now.
If added, the number of repeated traces can be greatly reduced.

**Comment by Elinpf** [comment]
Can this function be implemented as a plugin?

**Comment by mrexodia** [comment]
There is a callback for every step where you could save whatever you need, yes :)

**Comment by torusrxxx** [comment]
Info box is now in trace tab
