### ISSUE TITLE
Do not query process cookie when attaching

### ISSUE THREAD

**Issue by Mattiwatti** [x64dbg/x64dbg#2164]
Steps to reproduce:
- Enable process cookie querying.
- Attach to a running process (e.g. another instance of x64dbg) and do some stuff in the debuggee.
- Whenever `NtQueryInformationProcess` is called, a "breakpoint reached not in list!" message is generated.

IMO it would be fine to only call `HandleNtdllLoad` (which is responsible for setting the initial bp on `NtQueryInformationProcess`) if the process was created and not attached to. The cookie is only guaranteed to be queried in `LdrpInitializeProcess` -> `RtlSetUnhandledExceptionFilter` -> `RtlEncodePointer`. All other ways of reaching `RtlEncodePointer`/`RtlDcodePointer` happen only under specific circumstances, like the debuggee adding a VEH, or when ntdll calls the exception handlers, so they are not reliable anyway.

Another thing about `HandleNtdllLoad` is that it could be changed to return without setting a breakpoint if the OS is >= Windows 8, because in that case the cookie can just be queried by the debugger. Both of these changes would reduce conflicts with other code that reads `NtQueryInformationProcess` and finds an unexpected breakpoint byte (e.g. ScyllaHide).

Related: #1747

Edit: I see that this was already mentioned in #1964, but no fix was given other than to disable the cookie setting.

**Comment by balintf** [comment]
I already have a simple patch for this, but I want to explore the possibilities of improving it by querying the process cookie and optionally using hardware breakpoints as suggested in #1747 .

> Another thing about HandleNtdllLoad is that it could be changed to return without setting a breakpoint if the OS is >= Windows 8, because in that case the cookie can just be queried by the debugger.
Do you mean to query it simply by using  `NtQueryInformationProcess` with the debuggee's Process Handle? (I've tested it under Windows 10, and it seems to work well, but I don't have a Windows 7 to verify that it fails and if `NtQueryInformationProcess` returns an error code in this case).

**Comment by Mattiwatti** [comment]
> Do you mean to query it simply by using NtQueryInformationProcess with the debuggee's Process Handle? (I've tested it under Windows 10, and it seems to work well, but I don't have a Windows 7 to verify that it fails and if NtQueryInformationProcess returns an error code in this case).

Yes, exactly. This will fail with `STATUS_INVALID_PARAMETER` on any Windows versions <= 7 if the process handle being queried is not `NtCurrentProcess` (`0xFFFFFFFF`). Even querying your own process cookie will fail if you use a real handle instead of the hardcoded pseudo handle.

On Windows 8 and later a process can query another process's cookie so long as it has `PROCESS_VM_WRITE` access to the handle.

**Comment by Mattiwatti** [comment]
This is fixed now thanks to the PR, closing this.
