### ISSUE TITLE
No GetVariable,SetVariable,GetVariableList plugin support

### ISSUE THREAD

**Issue by avigi** [x64dbg/x64dbg#2165]
There is now possibility to get variables from plugin.
for example if i create variable using Cmd("Avi=1"), there is no option to get this variable.
Script:: has the many option for example-
Script::Argument
Script::Assembler
Script::Label
but non of them gives the option to GetVariable,SetVariable,GetVariableList......

**Comment by mrexodia** [comment]
Good question. There is no api, because you can just use `Eval("Avi")` which will evaluate the expression `Avi` which will return the contents of your variable :)
