### ISSUE TITLE
IF Else option

### ISSUE THREAD

**Issue by avigi** [x64dbg/x64dbg#2166]
I see we have the option "ternary(condition, var1, var2)" as an If Else option,
but what if i want to run some command in case some variable are set with some value??

for example if ($var1==1){run} else {pause} ?????

**Comment by mrexodia** [comment]
There is no way to execute other commands under some condition (I'm assuming you mean in a single command). It would be best if you just write a plugin with your own command that does what you want.

If you are writing some script you can use `je`:

```
cmp $var1, 1
jne pause
run
jmp end
pause:
pause
end:
```

**Comment by torusrxxx** [comment]
just put $var==1 in break condition and done.
