### ISSUE TITLE
Ui optimization

### ISSUE THREAD

**Issue by fyc132** [x64dbg/x64dbg#2167]
![%)0Q%J~Z}XO{Y2%3MPB)D4O](https://user-images.githubusercontent.com/16433238/57425751-19106b00-724f-11e9-8ab6-600c25af398a.png)

How can I display the loop enclosing line and automatic commenting of function parameters in the disassembly window? 3q

**Comment by mrfearless** [comment]
https://github.com/ThunderCls/xAnalyzer

**Comment by fyc132** [comment]
> https://github.com/ThunderCls/xAnalyzer

![1](https://user-images.githubusercontent.com/16433238/57444601-1891c780-7283-11e9-94b7-3bd709ef91f7.png)

Looks good. 3k you
