### ISSUE TITLE
Can I change default terminal(cmd) to something else?

### ISSUE THREAD

**Issue by newbieh4cker** [x64dbg/x64dbg#2182]
Before submitting an issue, make sure it has not already been reported.

Then, make sure the following points are included in your issue:

- Debugger version | | |  May 9 2019, 21:10:03
- Operating system version and Service Pack (including 32 or 64 bits).  | | |  Win XP SP3

As issue subject, Can I change default terminal cmd.exe to something else?
Currently, os default setting for terminal is ConEmu.exe

**Comment by mrexodia** [comment]
This feature is out of scope for x64dbg. You can try to inject ConEmu.exe into x64dbg and try to make it work, but this is not something x64dbg will ever support in itself (since the OS controls what console window is created, not the debugger).
