### ISSUE TITLE
x64dbg will be delete already download symbols and redwonload it when i load symbols

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#2185]
i want to load symbols :
![Vn1mRGvf36](https://user-images.githubusercontent.com/16742566/58746786-e09e2e80-8494-11e9-8506-6117d04defd0.gif)

**Comment by stonedreamforest** [comment]
Does it seem necessary to compare existing hash values before downloading?

**Comment by gitlsl** [comment]
I got same issue

**Comment by mrexodia** [comment]
@stonedreamforest Generally if the symbol is already downloaded it will be loaded automatically, so why are you clicking 'Download symbol' an expecting it to not download something?

Anyway I added the (currently) undocumented command `symload` which you can use like this:

```
symload app.exe, "C:\path\to\app.pdb"
symload app.exe, "C:\path\to\app.pdb", 1
```

The first command will load the PDB as normal from the disk (always manual now, it won't remember anything). The second command will load the PDB forced (if you know the PDB is right, but the validation data is missing or doesn't match).

**Comment by stonedreamforest** [comment]
> @stonedreamforest Generally if the symbol is already downloaded it will be loaded automatically, so why are you clicking 'Download symbol' and expecting it to not download something?
> 
> Anyway I added the (currently) undocumented command `symload` which you can use like this:
> 
> ```
> symload app.exe, "C:\path\to\app.pdb"
> symload app.exe, "C:\path\to\app.pdb", 1
> ```
> 
> The first command will load the PDB as normal from the disk (always manual now, it won't remember anything). The second command will load the PDB forced (if you know the PDB is right, but the validation data is missing or doesn't match).

-----
sometimes i don't known the symbols already loaded . so  i will try  manually load.

**Comment by mrexodia** [comment]
Hm okay, do you have any suggestion how to solve this problem of knowing if symbols are loaded or not? The problem is that the symbols view is quite crowded, so adding more columns etc would be unwanted. It would be possible to add a tooltip for example, but I'm not sure this is very useful... Or perhaps the color of the module could be red/green for symbols loaded or not loaded?

**Comment by stonedreamforest** [comment]
Add a status box(or icons) in the first column, like this
- [x] （loaded） 
- [ ] （unload）


Using default color display will be confusing：
![image](https://user-images.githubusercontent.com/16742566/59554755-a5dedf00-8fda-11e9-8d26-62637ea71139.png)

**Comment by mrexodia** [comment]
It would be too difficult to implement a checkbox there, but I implemented doing different colors (can be customized of course):

![](https://i.imgur.com/bzI2SFg.png)

**Comment by stonedreamforest** [comment]
and should add normal loaded/unload column like moudle(base/path)，

**Comment by mrexodia** [comment]
In my opinion this isn’t very useful. This column will not be visible, but
it’s easy to do of course...

**Comment by stonedreamforest** [comment]
we can move it to first column, x64dbg just remeber it  in the configuration file

**Comment by mrexodia** [comment]
Alright, will do then!
