### ISSUE TITLE
Version Jun 12 2019 , language setting  take No effect

### ISSUE THREAD

**Issue by charygao** [x64dbg/x64dbg#2186]
Version Jun 12 2019 ,
I set a new Language,Then it shows New language setting will take effect upon restart.
but it's still the old Language after restarted。
sorry for that english is not my native。

**Comment by mrfearless** [comment]
check if the ini setting files are writable: `x64dbg\x32\x32dbg.ini` and `x64dbg\x64\x64dbg.ini` and that x64dbg is not installed in a protected folder (`\Program Files`, `\Program Files (x86)`, etc)

**Comment by charygao** [comment]
I find it's caused by a plugin - "EasyLabelView"[https://github.com/phiDelPark/x64DbgPlugins]. @mrfearless 
the plugin "EasyLabelView" will causing a system error while closing the x64dbg,after "zh_CN" to "en-US" language setting. So Could you integrate the "EasyLabelView" function into x64dbg？

**Comment by mrexodia** [comment]
@charygao this is an open issue in https://github.com/x64dbg/x64dbg/issues/2114, hopefully you will find some way to improve EasyLabelView to fix your issue.

It would help if you could explain your use case of this plugin in #2114 so this can be taken into account if someone wants to work on it.
