### ISSUE TITLE
What does the prefix "c" mean in stack view?

### ISSUE THREAD

**Issue by gp-wang** [x64dbg/x64dbg#2187]
Appreciate the tips

**Comment by mrexodia** [comment]
A screenshot would help.

**Comment by gp-wang** [comment]
![image](https://user-images.githubusercontent.com/10679417/59539181-21447180-8eb1-11e9-8bbb-bc86d9c2e0cf.png)

**Comment by mrexodia** [comment]
This is not a prefix, it is supposed to be the stack frame for the function, but something is clearly broken about it.

**Comment by gp-wang** [comment]
Thanks

> This is not a prefix, it is supposed to be the stack frame for the function, but something is clearly broken about it.
