### ISSUE TITLE
Stack buffer overrun after enter long module name

### ISSUE THREAD

**Issue by partoftheworlD** [x64dbg/x64dbg#2190]
Debugger version:  Jun 16 2019
Windows 10 19H1
Debugger crash after enter very long module name(257+ chars)
Elaborate reproduction steps for the bug/issue being reported:
1. Ctrl+G
2. Enter `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.`  (Dot at the end of line is required)
3. Crash

![123](https://user-images.githubusercontent.com/6013494/59650359-5e00b900-918e-11e9-9c54-86c2d94ae72a.gif)

Minidump:
https://mega.nz/#!NokzSCjZ!AF26dn3Zj8HR12em0wnxuDYXd4gbcn_roU-zVdZiASg

**Comment by flarejune** [comment]
https://github.com/x64dbg/x64dbg/blob/32c8e33c645393e1c08ee965e75ede0657504432/src/dbg/value.cpp#L1456
