### ISSUE TITLE
Is there a expression to get the module base address given the module name?

### ISSUE THREAD

**Issue by gp-wang** [x64dbg/x64dbg#2192]
Is there a expression to get the module base address given the module name?

E.g. in the "symbols" tab, I have below module:
Base=00007FF79ED60000
Module=witcher3.exe
Party=User
Path=F:\programs\steam\steamapps\common\The Witcher 3\bin\x64\witcher3.exe

Is there a function that given "witcher3.exe" it will return 00007FF79ED60000 to me?

Thanks in advance.

--
Btw, is there a x64dbg forum or slack channel for discussions?

**Comment by mrexodia** [comment]
Try reading at least the introduction of the manual. Everything related to expressions is documented there. It is “witcher3:0” or “witcher3:base”

See the github readme for all the possible channels we have for chatting. All are synchronized with each other so you can use the platform of your choice.

**Comment by gp-wang** [comment]
> Try reading at least the introduction of the manual. Everything related to expressions is documented there. It is “witcher3:0” or “witcher3:base”
> 
> See the github readme for all the possible channels we have for chatting. All are synchronized with each other so you can use the platform of your choice.

Thanks. 

From the manual, I first tried "mod.base(addr) : Get the base address of the module addr." so I was confused a bit: mod.base(witcher3.exe) didn't return a result. I will try "witcher3:0" instead.

**Comment by mrexodia** [comment]
Yeah all expressions take integers as input. So mod.base() expects an address. mod.base(witcher3.exe:0) would work though:)

**Comment by loongee** [comment]
use mod.fromname("xxx.dll")

> Is there a expression to get the module base address given the module name?
> 
> E.g. in the "symbols" tab, I have below module: Base=00007FF79ED60000 Module=witcher3.exe Party=User Path=F:\programs\steam\steamapps\common\The Witcher 3\bin\x64\witcher3.exe
> 
> Is there a function that given "witcher3.exe" it will return 00007FF79ED60000 to me?
> 
> Thanks in advance.
> 
> -- Btw, is there a x64dbg forum or slack channel for discussions?
