### ISSUE TITLE
Validation error: PDB guid is not matching

### ISSUE THREAD

**Issue by itsmattkc** [x64dbg/x64dbg#2193]
**Debugger version:** Jun 22 2019
**Operating system version:** Windows 10 1809 x64

A particular DLL's PDB file appears to be causing the following error:

```
Downloading symbol d3drm.pdb
  Signature: 3B7D82D31
  Destination: C:\Users\Matt\Desktop\snapshot_2019-06-22_17-19\release\x32\symbols\d3drm.pdb\3B7D82D31\d3drm.pdb
  URL: https://msdl.microsoft.com/download/symbols/d3drm.pdb/3B7D82D31/d3drm.pdb
Validation error: PDB guid is not matching (expected: 00000000-0000-0000-0000-000000000000, actual: 3b7d82d3-0000-0000-0000-000000000000).
[DIA] Failed to load PDB: C:\Users\Matt\Desktop\snapshot_2019-06-22_17-19\release\x32\symbols\d3drm.pdb\3B7D82D31\d3drm.pdb
```

Most PDBs work correctly, just this one seems to be causing an issue.

I used ChkMatch to compare the PDB and DLL in question and got the following output, which seems to imply x64dbg is detecting the signature incorrectly:
```
ChkMatch - version 1.0
Copyright (C) 2004 Oleg Starodumov
http://www.debuginfo.com/


Executable: C:\Program Files (x86)\LEGO Island\d3drm.dll
Debug info file: C:\Users\Matt\Desktop\snapshot_2019-06-22_17-19\release\x32\symbols\d3drm.pdb\3B7D82D31\d3drm.pdb

Executable:
TimeDateStamp: 3bd086fc
Debug info: 2 ( CodeView )
TimeStamp: 3b7d82d3  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 26  RVA: 000029bc  FileOffset: 00001dbc
CodeView format: NB10
Signature: 3b7d82d3  Age: 1
PDB File: d3drm.pdb

Debug information file:
Format: PDB 2.00
Signature: 3b7d82d3  Age: 1

Result: Matched
```

This is the problematic DLL in question: [d3drm.zip](https://github.com/x64dbg/x64dbg/files/3317315/d3drm.zip)

No plugins installed, default English translation.

**Comment by mrexodia** [comment]
The legend @Mattiwatti strikes again:

https://github.com/x64dbg/x64dbg/blob/1e075142a5983b05496ef0f2b7fe8648c957e8d0/src/dbg/pdbdiafile.cpp#L297

Anyway this format is not supported right now, in the meantime you can use the `symload` command to skip the signature validation and I will update the validation logic to support it.

**Comment by mrexodia** [comment]
Fixed version should be out soon.
