### ISSUE TITLE
About save the CPUInfoBox information to TraceBrowser

### ISSUE THREAD

**Issue by Elinpf** [x64dbg/x64dbg#2196]
which callback or api could help me if i want to write a plugin that save the CPUInfoBox informations to the TracerBrowser?

Thanks a lot.

**Comment by torusrxxx** [comment]
There is no such API yet, but the information is already saved in trace
files and can be viewed with "Information" menu.

**Comment by Elinpf** [comment]
How to view "information" and put "information" in a new column in TraceBrowser？
Thanks

**Comment by torusrxxx** [comment]
#2295
