### ISSUE TITLE
find

### ISSUE THREAD

**Issue by nihuai** [x64dbg/x64dbg#2197]
False search results：
![X3%KUUR`N76C7}T82V@ATFL](https://user-images.githubusercontent.com/22935890/60425263-bde26f80-9c24-11e9-858a-54d2391262cb.png)
![image](https://user-images.githubusercontent.com/22935890/60425951-33027480-9c26-11e9-9ace-3d189622cf49.png)

mov eax,bswap(FunAddr) //It's no use.
find IAT,eax

Correct search results：
![W~{A87V1VI6WN379JLYB2KU](https://user-images.githubusercontent.com/22935890/60425333-e0748880-9c24-11e9-87f2-26b4e17a7097.png)
![3VP%}5WQDRGW)0 MZV02W57](https://user-images.githubusercontent.com/22935890/60425500-3a754e00-9c25-11e9-900c-2bd416c2fd40.png)

find 123,90E8  //This is the only way to search，Variables and register searches are problematic

**Comment by mrexodia** [comment]
I think this needs some clarification in the documentation and additionally the command should fail if the argument is not a valid byte pattern, to avoid confusion.

**Comment by mrexodia** [comment]
There are now various new ways to achieve what you want:

```
find IAT, ptr:eax
find IAT, dword:eax
find IAT, "{bswap;4@eax}"
find IAT, "{bswap@eax}"
```

**Comment by hp9831g** [comment]
Hi, friends,

I fill noob to ask

How I find asm command just like ollydbg
In ollydbg
Ctr + F -> type like "mov r32,r32"

Which finds all command which has mov instruction to any 32bit reg to another 32bit register

Like 
Mov eax,ecx
Mov ecx,edi
Mov ebx,edx


I wasted whole day to find this functionality.

Thanks in advance.
Hemant
