### ISSUE TITLE
How to remove Hex Dump highlights

### ISSUE THREAD

**Issue by Kei0725** [x64dbg/x64dbg#2200]
- Debugger version:  Jul 2 2019(2019-07-02_16-06)
- Operating system version:   Windows 10 x64

![tmp](https://user-images.githubusercontent.com/42237467/61200690-e3877280-a714-11e9-89e8-d1c248528e2a.PNG)

**Comment by mrexodia** [comment]
Change the color to transparent. These indicate information to you though, so I don’t really see why you’d wanna remove them...

**Comment by Kei0725** [comment]
Thanks  , It's comfortable to look like that.  😄 




![tmp2](https://user-images.githubusercontent.com/42237467/61203152-2b5dc800-a71c-11e9-815b-092bfc8496c7.PNG)
