### ISSUE TITLE
Removing release snapshots too quickly affects downstream chocolatey users

### ISSUE THREAD

**Issue by obilodeau** [x64dbg/x64dbg#2207]
I know you don't maintain the chocolatey package (I read #2060) but if you would hold on to previous snapshots just a little longer it would help consumers of the package.

For example, right now, the latest version of the package refers to a snapshot that has been deleted:
```
2019/08/22 16:55:24 ui:     virtualbox-iso: x64dbg.portable v20190817.1748 [Approved]
    virtualbox-iso: x64dbg.portable v20190817.1748 [Approved]
2019/08/22 16:55:24 ui:     virtualbox-iso: x64dbg.portable package files install completed. Performing other installation steps.
    virtualbox-iso: x64dbg.portable package files install completed. Performing other installation steps.
2019/08/22 16:55:28 ui:     virtualbox-iso: Attempt to get headers for https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip failed.
    virtualbox-iso: Attempt to get headers for https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip failed.
2019/08/22 16:55:28 ui:     virtualbox-iso: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
2019/08/22 16:55:28 ui:     virtualbox-iso: Downloading x64dbg
    virtualbox-iso: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```

I want to bundle the `x64dbg` package to [malboxes](https://github.com/GoSecure/malboxes/) (in https://github.com/GoSecure/malboxes/pull/125), a tool to get people into malware analysis and this hinders our user experience.

I don't know how your release system is setup but if you could hold on to a few releases (like lets say `n-3`) it would make it simpler for chocolatey users.

**Comment by mrexodia** [comment]
Github didn't like it in the past if you uploaded gigabytes of releases.

There are archives with all releases as long as I can maintain at:

- https://sourceforge.net/projects/x64dbg/files/snapshots/
- https://osdn.net/projects/x64dbg/storage/snapshots/

**Comment by obilodeau** [comment]
I didn't know about these archives. That's perfect! Thank you!
