### ISSUE TITLE
why x64dbg lost its developer?

### ISSUE THREAD

**Issue by yiivon** [x64dbg/x64dbg#2208]
Cause it's document, the compile instructions is so old to take a newer so much time to jump into the KENG!

**Comment by mrexodia** [comment]
I don't know what you are doing, but if you follow the compilation instructions everything works fine. Could you detail what steps specifically you have trouble with?

Generally I don't think x64dbg is losing developers, most people simply do not want to contribute, even if we would make a utility to automatically install all (2) required dependencies and compile x64dbg for them.
