### ISSUE TITLE
CPU/Callstack/Graph view has method to disable breakpoint?

### ISSUE THREAD

**Issue by yiivon** [x64dbg/x64dbg#2210]
Mostly times we just need to disable a cond-breakpoint in CPU/Callstack/Graph view instead of remove it, is there any Hotkey or menu item?
Thanks so much!

**Comment by mrexodia** [comment]
Check the hotkey menu. In the cpu you can click on the red dot on the left. Otherwise I’m not sure from the top of my head...

**Comment by yiivon** [comment]
Thank you! 
and there is a `DisableBreakpoint` interface in SDK, but no `EnableBreakpoint` to turn it on again? and need to invoke `DbgIsBpDisabled(av)` to check it state?
maybe i can do these as **cmd**, yes?

I want to add that interface, also want to enhance the graph view and stack view to debug for VMP3, i found that CFG graph view is the flash feature of x64dbg, it can capturing mostly handler of VMP and stack if could be displaying at coloring can tracking every small change of vRegisters/vStack.
I wanna build x64dbg, I try to build x64dbg strictly as the instructions on wiki, but msvc 2013 compiler can not handle the C++11 codes in sources within parts of QT, and then i turn to vs 2017 and the latest QT but finally got failure by vc runtime libraries matching problem..., so i don't know why C++11 features appear in sources should be compiled with vs2013? please checkout the latest branch development to verify that.

**Comment by mrexodia** [comment]
I am using vs2013 at home and on CI, so there is something wrong with your
configuration. Do you have the latest update installed?

**Comment by yiivon** [comment]
I am in Parallels VM, a new Windows 7 x64, okay, thanks, maybe talk later, thanks for your time.

**Comment by mrexodia** [comment]
I meant the Visual Studio 2013 Update 5. I'm developing on Windows 8.1 x64 and Windows 10 x64 successfully with this. I'm making an image of Windows 7 x64 to try but it will take me a while...

**Comment by yiivon** [comment]
Thank you very much, I done it successful at last i turn vs2013 solution to vs2015, runtime libraries version match, it work good. 
And in fact maybe it should be added `DEFINES += Q_COMPILER_INITIALIZER_LISTS` to the .pro file to solve a bit of problem while compiling in my or some people environment possible.
**Proposal** :  firstly export all/whole/mostly api, including unimplemented/empty function, so that some other developers like me more easy to take their time on.
Thanks again.

**Comment by mrexodia** [comment]
So to be clear, you didn’t try vs2013?

Anyway feel free to open a PR with this additional define. As long as it
still compiles on CI with 2013 it’s fine for me :)

**Comment by yiivon** [comment]
I have tried vs2013, but not so lucky haha, no matter what, vs2013 is the preferred choice because of a lower layout debugger's 👍

**Comment by mrexodia** [comment]
Anyway, looking forward to your work! If you have any questions, feel free to ask them here or come to Telegram/XMPP/Slack/Discord to chat, see https://x64dbg.com/#contact

**Comment by yiivon** [comment]
Thank you so much! I am working hardly and mainly focus on VMP3 now, x64dbg is so great and so useful toolset for these job, i would shared my found/ideas later in time. thanks for your nice work, all the developers.
