### ISSUE TITLE
Issues with new find-patterntransform - reject invalid pattern code

### ISSUE THREAD

**Issue by VladlenaVashchenko** [x64dbg/x64dbg#2212]
Hi mrexodia,

I think the reason invalid patters are still accepted in find cause your reject invalid pattern is not working. Would you please check the type of string passed. I think you need a cast from System::string to std::string.

I could be wrong. Please check. You are so talented you will solve it soon.

Thanks,
VV

**Comment by mrexodia** [comment]
Please provide an example of an invalid pattern that is still accepted.

**Comment by VladlenaVashchenko** [comment]
find 401000, "{s:eax}"
Try this and check result, result will be 401000.
to see what really happens debug in visual studio.

New code makes problem in ref.add too. it fails almost every time. this happens every time with every pc i try it fresh

**Comment by VladlenaVashchenko** [comment]
I have tried this branch: https://github.com/x64dbg/x64dbg/tree/d50675ca025e3494de683d8510a681551e92c8ab

the error is not there. also ref.addr works better. issues are from new patterntransform()

**Comment by rchorlog** [comment]
I don't know why I am on this discussion thread but is there a way I can be
removed?  I don't even know what this project is
