### ISSUE TITLE
x64dbg follow [xxxx] in dump problem!

### ISSUE THREAD

**Issue by strivexjun** [x64dbg/x64dbg#2216]
debugger: Aug 11 2019
os:  windows 7 7601

see gif
![x64dbgbug](https://user-images.githubusercontent.com/17829802/65479125-dc23d880-debe-11e9-8cfc-6bc39c12cbdf.gif)

**Comment by mrexodia** [comment]
What is the problem? If you follow `12EFE0` in dump it goes there, if you follow `[12EFE0]` in dump it goes to `*(void**)12EFE0`. See the manual for how expressions work.
