### ISSUE TITLE
I uninstalled it, but it keeps showing whenever I right click.

### ISSUE THREAD

**Issue by DrJvet** [x64dbg/x64dbg#2217]
I downloaded the latest available. When I wanted to uninstall the software after clicking in the setup option I just moved the folder to the recycle bin and deleted it. I did it because I wasn't able to find the program in the list of installed programs. So I did it that way, and now every time I right click other software it still shows up as "debug with x64dbg" but without the icon and I can't use it because I deleted it.

I just want the "debug with x64dbg" option gone.

Thank you.

**Comment by mrexodia** [comment]
See faq.x64dbg.com
