### ISSUE TITLE
DbgValFromString&DbgEval

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#2223]
Hi!
What method can I get data from a variable in a script?
Example from the script:
FindPointer mytable, pattern, 4
The method that I use:
bool cbFunctionFindPointer(int argc, char* argv[3])
{
	char buffer[MAX_MNEMONIC_SIZE];
	bool success;
	duint index = DbgEval(argv[1], &success);
	duint Size = Memory::GetSize(DbgValFromString(argv[1]), false, true);
.....
}
Unfortunately, there are no data in the variables. As a result, the functions (DbgValFromString&DbgEval) simply convert the variable name to unsigned __int64:
0x0000020db33b9720 {0x0000020db33b72f0 "FindPointer mytable, pattern, 4"}
index	= 5557833728	//unsigned __int64
Size	       = 1077248	        //unsigned __int64

**Comment by mrexodia** [comment]
Hi, can't you just use `findallmem` from your script? `findallmem 0, "{bswap@mytable}"` should work. Otherwise could you paste the full code because right now it does not make any sense to me.

**Comment by Paliha** [comment]
if my memory serves me, this command displays the search result in the ref window. This is not convenient. To search for va / rva pointers, I wrote my command and everything was in order. With the transition to a fresh OS (vin10.1809) in place of the arguments, I get a line with the command and variables.

**Comment by mrexodia** [comment]
Can you post your whole code so I can take a look?

**Comment by mrexodia** [comment]
It might help to try

```
bool cbListArguments(int argc, char* argv[])
{
    for(int i = 0; i < argc; i++) dprintf("%d:%s\n", i, argv[i]);
    return true;
}
```

And see what is the output.

**Comment by Paliha** [comment]
ок.
Script:
alloc 0x9D000, 0x130000000
addrcode = $result
LoadDataMem  addrcode, C:\130000000.bin 
ret
--------------
Code:
bool cbLoadDataMem(int argc, char* argv[3])
{
	for (int i = 0; i < argc; i++) _plugin_logprintf("%d:%s\n", i, argv[i]);
	if (argc == 3)
	{
		char pathtofile[MAX_STRING_SIZE];
		sprintf(pathtofile, "%s", argv[2]);//получили путь к файлу
		HANDLE hFile = CreateFileA(pathtofile, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
		if (hFile == INVALID_HANDLE_VALUE)
		{
			MessageBoxIcon(hwndDlg, "\tFaile It is not a directory.\n\n\teXeLab.Copyright \xA9 2018", PLUGIN_NAME, MB_OK);
		}
		else
		{
			HANDLE hMapping = CreateFileMapping(hFile, nullptr, PAGE_READONLY, 0, 0, nullptr);
			DWORD dwSize = GetFileSize(hFile, NULL);
			unsigned char* dataPtr = (unsigned char*)MapViewOfFile(hMapping, FILE_MAP_READ, 0, 0, dwSize);
			duint address_mem = DbgValFromString(argv[1]);//получили адрес памяти
			DbgMemWrite(address_mem, (void*)dataPtr, dwSize);
			UnmapViewOfFile(dataPtr);
			CloseHandle(hMapping);
		}
		CloseHandle((HANDLE)hFile);
	}
	return true;
}
---------
Log:
0:LoadDataMem  addrcode, C:\130000000.bin
1:addrcode
2:C:\130000000.bin

**Comment by Paliha** [comment]
>>for(int i = 0; i < argc; i++) dprintf("%d:%s\n", i, argv[i]);
the output is the same variables.
---
updated sdk, added to method:
sprintf(buffer, "%p", DbgValFromString(argv[2]));
strncpy_s(buffer, buffer, len);
now everything is great..))

**Comment by mrexodia** [comment]
I have no idea what the issue was. The code you sent earlier looked fine 🤷‍♂ but glad you fixed it :) Feel free to close the issue if it’s solved.
