### ISSUE TITLE
Playing things down with ErrorNotReproduced is not fair

### ISSUE THREAD

**Issue by VladlenaVashchenko** [x64dbg/x64dbg#2224]
Mr exodia,

I have raised a genuine issue earlier which is about your new find pattern code. This time I got some time to look into your code. And referring to line: [https://github.com/x64dbg/x64dbg/blob/31443c2c78f8dc6d39955b53d7ce8a3e9c1109e6/src/dbg/stringformat.cpp#L26](url) and line: [https://github.com/x64dbg/x64dbg/blob/31443c2c78f8dc6d39955b53d7ce8a3e9c1109e6/src/dbg/stringformat.cpp#L92](url) you are returning "???" if your code fails to get any value. This "???" is the reason why your code fails for pattern find "find 0x400000, "{s:eax}". Its a shame to see once great mr exodia become so disrespectful. If your intention is to sabotage this project then atleast do it gracefully.

**Comment by mrexodia** [comment]
You are free to work on your own issue in your own time. I will decide what I spend my own time on and opening more issues isn’t motivating me to look at yours.

**Comment by mrexodia** [comment]
Also the label means the issue was not reproduced by me or someone else than the reporter. All new bug reports get this label.

**Comment by mrexodia** [comment]
You can now find a description of issue labels here: https://github.com/x64dbg/x64dbg/labels
