### ISSUE TITLE
Crash when saving graph image

### ISSUE THREAD

**Issue by vid512** [x64dbg/x64dbg#2230]
x64dbg from 14. Oct. 2019 crashes when graph / save image dialog is closed. To reproduce, just start any executable and press keys G, I, ESC. This seems to happen with any executable, for example with "x96dbg.exe x96dbg.exe".

**Comment by not6** [comment]
Still happens on Apr 11 2024 build on fresh install
Sometimes the image is actually written before crashing (graph size might have something to do with this but I didn't do much testing) but lines of disasm look a bit cropped (see output image at bottom of comment)

OS: Windows 10 x64 22H2 19045.4355
Screen res (if this even matters): 3840x2160 (just regular 4k 16:9)

Output when it "works" (still crashes afterwards, but it doesn't always output an image):
![Output](https://github.com/x64dbg/x64dbg/assets/94708210/735ee67c-c7c4-47b1-b9c7-d2cedde73832)
