### ISSUE TITLE
symbols error

### ISSUE THREAD

**Issue by xlfj5211** [x64dbg/x64dbg#2236]
正在下载符号 mscoree.pdb
  签名：5EB01A03276E4F6BB974E19A522150E12
  目标：K:\net工具\snapshot_2019-10-23_12-30\release\x32\symbols\mscoree.pdb\5EB01A03276E4F6BB974E19A522150E12\mscoree.pdb
  网址：https://msdl.microsoft.com/download/symbols/mscoree.pdb/5EB01A03276E4F6BB974E19A522150E12/mscoree.pdb
InternetOpenUrl失败（）……

why    all file download   is error  , resaon ?  i'dont know

**Comment by xlfj5211** [comment]
正在下载符号 wkernel32.pdb
  签名：FAE4F96B89C9437DB941FB0E4E43787D2
  目标：K:\net工具\snapshot_2019-10-23_12-30\release\x32\symbols\wkernel32.pdb\FAE4F96B89C9437DB941FB0E4E43787D2\wkernel32.pdb
  网址：https://msdl.microsoft.com/download/symbols/wkernel32.pdb/FAE4F96B89C9437DB941FB0E4E43787D2/wkernel32.pdb
连接成功，但下载失败（状态码：404）……

**Comment by mrexodia** [comment]
Microsoft is maintaining the service.
