### ISSUE TITLE
Last chanceexception on 00007FF6AD1EB1B0 (C00000005, EXCEPTION_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by JafferWilson** [x64dbg/x64dbg#2242]
- Debugger version (can be found on right hand side of menu bar of debugger).
- Operating system version and Service Pack (including 32 or 64 bits).
![image](https://user-images.githubusercontent.com/13446197/68125672-12318f00-ff38-11e9-9d4f-efdd84b93903.png)

I am using Window 10 64 bit version HOME.
- Brief description of the issue.
I was trying to debug the `terminal64test.exe` I have tried everything to avoid this exception but I am not able to do anything.
I am also attaching the exe file along with the thread. Please check it out.
[terminal64test.zip](https://github.com/x64dbg/x64dbg/files/3804273/terminal64test.zip)
- Elaborate reproduction steps for the bug/issue being reported.
1) Started the exe file.
2) Attached the process.
3) Run the process one by one. And the exception occurred.

I am using the ScyllaHide_2019-06-03_01-14-45 plugin. Without it the process will never allow you to get attached. Neither by process attach nor via file open.

[Exception video.zip](https://github.com/x64dbg/x64dbg/files/3804325/Exception.video.zip)

I hope to hear from you soon.

**Comment by lupier** [comment]
This is scyllahide related issue.

**Comment by JafferWilson** [comment]
@lupier I did not use Scyllahide.

**Comment by DigiAngel** [comment]
Confirming that updating to latest x64dbg and ScyllaHide plugins (and putting the files in the right places) fixed this for me.

**Comment by JafferWilson** [comment]
@DigiAngel Please let me know how to do that. I am quite naive for that.

**Comment by DigiAngel** [comment]
For scyllahide It's pretty easy...from the pdf in the package:
~~~
32-bit: Copy scylla_hide.ini, HookLibraryx86.dll and ScyllaHideX64DBGPlu-
gin.dp32 to your \x32\plugins\ directory.
64-bit: Copy scylla_hide.ini, HookLibraryx64.dll and ScyllaHideX64DBGPlu-
gin.dp64 to your \x64\plugins\ directory.
~~~
Hope that helps.

**Comment by skjerrywtf** [comment]
bež už do piče

ut 31. 12. 2019 o 12:16 DigiAngel <notifications@github.com> napísal(a):

**Comment by alnagar** [comment]
i tried it with the attached binary but it still gives me EXCEPTION_ACCESS_VIOLATION and i cant step through it.
so I tried with latest scyllahide and latest x64dbg. any advice from anyone ?
