### ISSUE TITLE
Symbols miss ordinal functions

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#2245]
This is a bug exsit long time ago, and I remember I point out this in one issue, but this is not fixed even now. My fixed code in my private fork:
https://github.com/lynnux/x64dbg/commit/0c0863e0bde197caa17e7d4ca7dc87c343161a92#diff-4c7f7321a834d2865ae8e5aacb680bcaR266
you can reproduced this in exe which import WS2_32.dll, you will see there can't show any ordinal functions in symbol view.

**Comment by mrexodia** [comment]
I'm a bit confused, why don't you just open a pull request to fix the issue? Anyway I'll cherry pick the commit to get it fixed here as well...

**Comment by mrexodia** [comment]
Oh I see, we discussed your changes in https://github.com/x64dbg/x64dbg/pull/1843. I rebased your branch and put it as `lynnux-clean`. I think the pull request was actually close to merged, so I'm sure we can work something out.
