### ISSUE TITLE
GetTickCount in program inconsistent with that in expression function

### ISSUE THREAD

**Issue by xujintao** [x64dbg/x64dbg#2246]
My debug program is simple, a loop call GetTickCount per second:
```
#include <Windows.h>
#include <stdio.h>
int main() {
	while (true) {
		DWORD dwTime = GetTickCount();
		printf("tick: (x)%04xms, (u)%ums, (u)%us\r\n", dwTime, dwTime, dwTime/1000);
		Sleep(1 * 1000);
	}
	getchar();
}
```
I want to compare the GetTickCount return value in my program with GetTickCount x64dbg supply in expression functions. So i prepare log text below:
```
[x64dbg_tick: (x){GetTickCount()}ms, (u){u:GetTickCount()}ms, (u){u:GetTickCount()/3E8}s] vs [tick: (x){eax}ms, (u){u:eax}ms, (u){u:eax/3E8}s]
```
logs:
![image](https://user-images.githubusercontent.com/5418373/68540266-e8f68000-03c9-11ea-97ac-17f784ce8e18.png)
Obviously, x64dbg's GetTickCount is correct and program's GetTickCount is wrong for it runs a time per milisecond. However, if i run program alone without a debugger, it will run per second.

- Debugger version (Sep 1 2019, 17:35:46).
- Operating system version and Service Pack (windows 7 64bit, sp1).

**Comment by Mattiwatti** [comment]
You didn't happen to leave any plugins enabled perhaps? Just asking because this behaviour is a lot like what ScyllaHide (and probably other anti-anti-debug plugins) would do to a debuggee, but not the debugger, if the `GetTickCount` hook was enabled :stuck_out_tongue:

**Comment by xujintao** [comment]
@Mattiwatti 
Many thanks. It turns out to be that i leave the ScyllaHide.options.TimingHooks.GetTickCount enabled.
