### ISSUE TITLE
DbgGetRegDumpEx() return success but get nothing.

### ISSUE THREAD

**Issue by StarsunYzL** [x64dbg/x64dbg#2248]
I am developing a plugin using pluginsdk from snapshot_2019-11-10_23-25, I found that sometimes DbgGetRegDumpEx() return true but all registers get zero, here is the code:
```c++
#include <mutex>
#include <windows.h>

#include "_plugins.h"
#include "bridgemain.h"

std::mutex g_step_mutex;

extern "C" __declspec(dllexport) bool pluginit(PLUG_INITSTRUCT * init) {
  init->sdkVersion = PLUG_SDKVERSION;
  init->pluginVersion = 1;
  strcpy_s(init->pluginName, "Test");
  return true;
}

extern "C" __declspec(dllexport) void CBSTEPPED(CBTYPE type, PLUG_CB_STEPPED * info) {
  std::lock_guard lock(g_step_mutex);
  REGDUMP regs;
  if (!DbgGetRegDumpEx(&regs, sizeof(regs))) {
    _plugin_logprintf("Read registers failed!");
    return;
  }

  // !!! Sometimes all registers get zero.
  if (!regs.regcontext.cip)
    _plugin_debugpause();
}

extern "C" __declspec(dllexport) void CBTRACEEXECUTE(CBTYPE type, PLUG_CB_TRACEEXECUTE * info) {
  std::lock_guard lock(g_step_mutex);
  REGDUMP regs;
  if (!DbgGetRegDumpEx(&regs, sizeof(regs))) {
    _plugin_logprintf("Read registers failed!");
    return;
  }

  // !!! Sometimes all registers get zero.
  if (!regs.regcontext.cip)
    _plugin_debugpause();
}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID reserved) {
  return TRUE;
}
```

Load any exe to x32dbg such as calc.exe, do a "Animate into" or "Trace into", _plugin_debugpause() will be called sooner or later. See attachment:

![2019-11-12_095849](https://user-images.githubusercontent.com/1513136/68636762-9044f580-0537-11ea-93fa-0dd7fc4105f0.jpg)

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/blob/development/src/dbg/_exports.cpp#L647-L692

This appears to happen if x64dbg (for some reason) thinks `DbgIsDebugging()` returns `false`, which should not be the case. Thanks for the reproduction case, I'll look into it!
