### ISSUE TITLE
x32dbg doesn't break at TLS Callback when Event setting is enabled (default)

### ISSUE THREAD

**Issue by jarmovanlenthe** [x64dbg/x64dbg#2250]
I'm running the March 4, 2018 version (REM workstation 64-bit). However, I couldn't find this issue in the tracker, though #1960 might be related.

I was looking into a malware sample with a TLS callback. I had to enable breaking on System breakpoints (in Options, Preferences, Events) in order to break on the environment initialization process and then set a breakpoint on the TLS callback.

**Comment by mrexodia** [comment]
Could you share the sample (with a password please to avoid any accidents)?

**Comment by jarmovanlenthe** [comment]
I've retested with the 2020-02-11 version and now it breaks perfectly on the TLS callback when only "TLS Callbacks" is enabled in Events. Already patched!
