### ISSUE TITLE
[QUESTION] X64DBG See All Memory Addresses in the CPU Pane

### ISSUE THREAD

**Issue by Gillver21** [x64dbg/x64dbg#2257]
X64DBG Version November 13, 2019
Windows 7 SP1
Trying to see every Memory Address in the CPU pane in X64dbg

First of all,may I suggest that a "Questions" section be added to this GitHub Page. Thank you.

Being a total noob, I'm trying to get a better understanding of reversing. Having done a recent GOTO for an address whose contents are being placed into a DS PTR, I could only find the address when putting it into the GOTO but as soon as I scrolled it would disappear. As a result I wanted to know if it was possible for X64DBG to show all of the memory addresses in the  CPU pane instead of skipping like in the pictured example.

![x64dbg_prob1](https://user-images.githubusercontent.com/32806396/69744851-fbcdbc00-110e-11ea-9277-f162167fe6ac.PNG)

Thank You

**Comment by mrexodia** [comment]
This is not possible and also would defeat the whole purpose of the CPU
view. If you want to look at the contents of memory you can use the dump
view instead.

**Comment by Gillver21** [comment]
Alrighty. Really, thank you so much for the prompt response. Alrighty, I'd been a bit scared of the Dump so far but I'll get right to it.

Thanks so much. 

-Gill

**Comment by Gillver21** [comment]
Butadditionally, what if the Dump doesn't show everything if I might ask?

**Comment by mrexodia** [comment]
Memory-wise the disassembly and dump show the same contents. The
disassembly simply disassembles the bytes on top of that. Does that answer
your question?

**Comment by Gillver21** [comment]
It sort. Of does. Sorry for the late response. Waiting at a doctor's office.

I'll need to gain a better understanding of what Dissassembly shows so I will continue to read.

Thanks for all if the help and responsiveness. I truly appreciate it.

**Comment by mrexodia** [comment]
Closing this for now.
