### ISSUE TITLE
Highlighting in hex dump

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#226]
instruction code, string and others in different colors:
[http://www.disk-editor.org/images/screens/HexEditor11.gif](http://www.disk-editor.org/images/screens/HexEditor11.gif)

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/226
- Originally reported by: [codedeep](http://bitbucket.org/codedeep)
- Originally created at: 2014-12-22T17:06:23.453

**Comment by Nukem9** [comment]
there is no difference between instructions or strings or others in x64_dbg. All data is interpreted however you want to. I will keep the issue open, in case these binary templates are going to make it.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment]
Should we close this and 'move' it to https://github.com/x64dbg/x64dbg/issues/175?

**Comment by mrexodia** [comment]
Yea, sounds like a good idea :)

**Comment by RaTcHeT302** [comment]
How can I get an .exe file to show like this? I'm assuming that it's really simple but I can't find any help at all.
![hex](https://user-images.githubusercontent.com/10897523/27257036-137bcbba-53d1-11e7-9ac5-ada056d0bdd5.gif)

**Comment by RaTcHeT302** [comment]
Apparently this was just a suggestion, that's from some program called Active@ Disk Editor?
