### ISSUE TITLE
A little confuse about command callback argument `argc` and `argv`

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#2263]
I register a command in plugin, it's like
```
bool bpcontent(int argc, char* argv[])
```
the usage command is `"[x64dbg_tol] USAGE: bpcontent [start] [end]\n"`
when execute `bpcontent 000123 000456`, I think the `argc` should be 3, but I got 2, and the  argv[1] is 000123000456, only `bpcontent 000123,000456` can get argc ==3.
This is a little strange, it's not behave like the `main` in normal console program.

**Comment by mrfearless** [comment]
Thats correct, the parsing of arguments uses a `,` to separate any arguments

**Comment by lynnux** [comment]
ok, get used to this pattern, if there has space char, it's still need to quto using ".

**Comment by mrexodia** [comment]
If you are interested, here is the parser state machine for commands: https://github.com/x64dbg/x64dbg/blob/development/src/dbg/commandparser.cpp

**Comment by lynnux** [comment]
@mrexodia, I'v check the code before post this issue, it's easy to patch to support using space to seperate arguments, but it may cause break change, so remain it as before.

**Comment by mrexodia** [comment]
Yes. It would be quite easy to use `CommandLineToArgvW` to parse the arguments exactly the same as the command line. One potential idea is to create a plugin based on `GuiRegisterScriptLanguage`, which parses the command and then uses `DbgCmdExecDirect` to forward the arguments to the original command.

See [x64dbgpy](https://github.com/x64dbg/x64dbgpy/blob/feff90c65aac40f0fa008a667538daab12d8791e/py.cpp#L708) for an example.
