### ISSUE TITLE
Does x32dbg support source level debugging？

### ISSUE THREAD

**Issue by wangyue0101** [x64dbg/x64dbg#2264]
I want to view the source code of the program in x32, and the page is blank after clicking the source code bar. Is it because x32 does not support source code viewing, or does it need another way to display source code?

**Comment by mrfearless** [comment]
You can use source level debugging, if you have the source code, compile your project to use the appropriate debug flags and options for assembler/compiler and for the linker to output a pdb file.
Once debugging in x64dbg with this special debug build of exe you can then switch to source level debugging to step through code, set breakpoints etc instead of via the normal cpu view.

![](https://i.postimg.cc/j26xfLKj/x64dbg-source-view-debugging.png)

**Comment by wangyue0101** [comment]
> You can use source level debugging, if you have the source code, compile your project to use the appropriate debug flags and options for assembler/compiler and for the linker to output a pdb file.
> Once debugging in x64dbg with this special debug build of exe you can then switch to source level debugging to step through code, set breakpoints etc instead of via the normal cpu view.
> 
> ![](https://camo.githubusercontent.com/a1a85c82b919fdcd16fe76612f7b404a0a3037d9/68747470733a2f2f692e706f7374696d672e63632f6a323678664c4b6a2f7836346462672d736f757263652d766965772d646562756767696e672e706e67)

“Once debugging in x64dbg with this special debug build of exe you can then switch to source level debugging to step through code”？
Is this version not official?

**Comment by wangyue0101** [comment]
@mrfearless 
    thank you for your reply. I am trying to learn this
“Once debugging in x64dbg with this special debug build of exe you can then switch to source level debugging to step through code”？
Is this version not official?

**Comment by mrfearless** [comment]
The special build of exe - comes from your own compiled source, which uses the correct debug flags and options to create the debug build of your exe along with the full pdb file for your exe. For me to build a properly debug source exe requires that i include the following switches for assembler (ml.exe):

```ML.EXE /c /coff /Cp /Zi /Zd /nologo /I:"\Masm32\Include" MyApp.asm```

And for the linker i require the following:

```LINK.EXE /SUBSYSTEM:WINDOWS /DEBUG /DEBUGTYPE:CV /PDB:"MyApp.pdb" /VERSION:4.0 /LIBPATH:"\Masm32\Lib" /OUT:"MyApp.exe" MyApp.obj, MyApp.res```

Once i debug MyApp.exe in x64dbg, i can view the source as the pdb and source are to be found alongside my special MyApp.exe debug build.

For C/C++ source level debugging, it will require specific options set when compiling, may have to ask someone who knows C/C++ to indicate the proper flags and switches required.

**Comment by mrexodia** [comment]
Generally any build with a pdb will have source lines. Debug builds have
better line-by-line stepping, but release builds work too.

The linker flag is generally /DEBUG(:FULL) (Linker -> Debug in VS)

**Comment by wangyue0101** [comment]
Thanks for your reply. I will try it now

**Comment by mrexodia** [comment]
Closing this for now. Let me know if you have further questions.

**Comment by ZsoltKantor** [comment]
I have a 64-bit console code compiled with cl.exe and linked with /DEBUG, but in x64dbg the source is not displayed.
I'm using the latest (Nov 18 2023) x64dbg version.
I also loaded the pdb file manually but nu source is visible, the "Source" tab is empty.
