### ISSUE TITLE
Symbol undecorate check for pdb

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#2268]
https://github.com/x64dbg/x64dbg/blob/development/src/dbg/pdbdiafile.cpp#L1029-L1032
```
    if(context.collectUndecoratedNames && !symbolInfo.name.empty() && symbolInfo.name.at(0) == '?')
    {
        undecorateName(symbolInfo.name, symbolInfo.undecoratedName);
    }
```
this check stop further `undecorateName` call if symbol name not start with '?'
I wrote a plugin which hook `__unDNameEx` to get more undecorated symbol in binary built by gcc or rust, their symbols are like `__ZN3std9panicking11begin_panic17h0ae8f48c0cd25b16E`. So could you consider remove the check or add more check start with '_' ?

**Comment by lynnux** [comment]
code from https://github.com/getsentry/symbolic/blob/master/demangle/src/lib.rs#L85-L91
```
fn is_maybe_cpp(ident: &str) -> bool {
    ident.starts_with("_Z") || ident.starts_with("__Z")
}

fn is_maybe_msvc(ident: &str) -> bool {
    ident.starts_with('?') || ident.starts_with("@?")
}
```
maybe we can use this idea to filter symbols?

**Comment by mrexodia** [comment]
I think something like: `if(first == '?' || first == '_' || first == '@')` should work for all cases right?

**Comment by lynnux** [comment]
thanks for the commit!

**Comment by mrexodia** [comment]
np :)
