### ISSUE TITLE
x32dbg Failed to start trace

### ISSUE THREAD

**Issue by donPab** [x64dbg/x64dbg#2269]
x32dbg version Jan 8, 2020  
Log Text:  tried  0x{p:cip}, tried {cip}, tried {eip}, tried  eip
Log Condition  eip >= 01361000 && eip < 01C7E000, and tried cip rather than eip, tried rip... with 8 more leading zeros

Always getting Failed to start trace

x64dbg folder is C:\H_Paul\x64dbg\release\x64
not using any plugins, just virgin

**Comment by mrexodia** [comment]
What is the error?

**Comment by donPab** [comment]
Always getting Failed to start trace, just like I said in the above description and problem title

**Comment by donPab** [comment]
Duncan,

Please see my response on github

Tkx, Paul

**Comment by mrexodia** [comment]
Could you paste the contents of the log (especially the last few lines)? And could you also show a screenshot of the trace dialog just to confirm? This error should not really happen under normal circumstances, but if it does there should be information in the log.

**Comment by donPab** [comment]
Hi Duncan,

First failure happened with 2019 May19 version.

Since then I have downloaded 2020 Jan8 version, but put it in same system folder C:\Program Files\x64dbg

And I believe I got failures there

 

Then I moved it all to my everyday working folders  C:\H_Paul\x64dbg

And it does not give me Failed to start trace.

But trace tab is empty, and there is no trace file created.

So I need to know that to put in LogText for X32 to get the eip as hex value

Also, did not notice LOG tab until you asked about it.

 

I need to go to chorus rehearsal (Hayden and Mozart)

And would like to work on recreating failure that I thought happened in 2020 Jan 8 version.

Back to you later… probably sorry for the alarm and the github entry.

Tkx, Paul

**Comment by mrexodia** [comment]
@donPab could you provide the logs and/or perhaps record your screen to see what's going on. On my side everything appears to work fine.

**Comment by donPab** [comment]
Hi Duncan,

 

I know I owe this research to you.  Been busy.

We did three performances last Fri/Sat/Sun

and then I had a previously scheduled hernia surgery Tue.

Now I am "back on the job".

 

I have identified two aspects of this problem--  A and B

 

Failed to start trace (#2269-A) 

Start Trace, look at LogFile popup but change nothing, set LogText&Condition, reduce max, press OK,  but get message with no clue what caused it.

 

 

Failed to start trace (#2269-B)

Install in Systems Folder, Start Trace w/FN.FT, and get message

Probably because cannot open output file to write new folder nor file(s)

Bad idea to install in Systems folder?  But no startup messageBox (and no Log warning)

 

See attachments for each.

TraceInto (etc) data entry not recorded into the log tab.  What did I type? Can it UnDo?

 

Current Documentation is “complete”, and sterile.

Like—how to I add a text note to the log tab? What do I type? Into the command box?

Usability nits.  Requires prior experience in Olly or IDA.

 

2017-18 Blogs are rich with examples, advice, and when to use, and for what…

src code put together much better than Olly. Architected. And just in a few years. Great YouTube.

 

tkx, Paul

**Comment by CherryDT** [comment]
Same issue here. It shows `Invalid expression ""` and changes log text from `0x{p:cip} {i:cip}` to an empty field. I also tried `eip` instead of `cip`.

**Comment by mrexodia** [comment]
@CherryDT If I remember correctly the invalid expression “” is because the break condition is empty

**Comment by CherryDT** [comment]
Hm, you are right. But why does this field need a value when the other "condition" fields don't?

**Comment by mrexodia** [comment]
It’s because of implementation details, but you’re probably right it’s
sensible to assume indefinite tracing if the condition is empty.

**Comment by mrexodia** [comment]
For anyone seeing this in the future: the reason is that you cannot start a trace when the program is running.

**Comment by CherryDT** [comment]
Also, in case it's still relevant, I think the OP forgot the 0x prefix in the hex address literal.

**Comment by thethiny** [comment]
2025 update:


> For anyone seeing this in the future: the reason is that you cannot start a trace when the program is running.

I did not understood what you meant until I figured it out on your own. I thought you meant you need to trace BEFORE you launch the app.
Anyway,
In order for the trace to work you need to be AT A BREAKPOINT, not the app us running.

Thanks for the team for their hard work btw 🙏🏻
