### ISSUE TITLE
[BUG] Adding same user label as current in disasembly causes label deletion

### ISSUE THREAD

**Issue by alex-shr** [x64dbg/x64dbg#2270]
Windows 10.0.18363.535 64-bit, x32dbg (Jan 8 2020)

Addition of user label "foo" to function with user label "foo"
![Буфер обмена-1](https://user-images.githubusercontent.com/59136505/72059986-d099d780-331e-11ea-987c-ef97cc836d45.jpg)

changes user label "foo" to default stub label "sub_6FF4C0" instead of doing nothing
![Буфер обмена-2](https://user-images.githubusercontent.com/59136505/72060033-ead3b580-331e-11ea-8237-ffefe3ac0792.jpg)

**Comment by mrexodia** [comment]
Should be fixed by the same fix as #2273
