### ISSUE TITLE
Clicking OK in "Add comment" window with no changes made deletes the comment.

### ISSUE THREAD

**Issue by andrelo1** [x64dbg/x64dbg#2273]
- Debugger version: Jan 8 2020.
- Operating system version and Service Pack: Window 10 Pro 64 bit.
- Brief description of the issue: clicking OK in "Add comment" window with no changes made deletes the comment.
- Elaborate reproduction steps for the bug/issue being reported:

1. Double click on comment or press hotkey to open comment for editing.
2. Click OK with no changes.
3. Comment was deleted.

**Comment by alex-shr** [comment]
I have this bug too. Also i have same bug for labels.

**Comment by andrelo1** [comment]
I don't have any plugins, just clean x64dbg.

**Comment by mrexodia** [comment]
I reproduced the bug, thank you for reporting!
