### ISSUE TITLE
Add run to section

### ISSUE THREAD

**Issue by lurumdare** [x64dbg/x64dbg#2280]
Example "Code Virtualizer by Oreans"

Protector add code to .reloc and create instructions pushfq (x64)

Algorithm:
Set all breakpoints on pushfq and debug to .text section (unprotected code)

This needed for fast cracking or for creating good protection (in dev)

**Comment by mrexodia** [comment]
I’m pretty sure you can already accomplish this with memory breakpoints and/or conditional tracing. Did you try it?

**Comment by lurumdare** [comment]
Nope. Can you show me example? I think need `!pushfq` and breakpoint

**Comment by lurumdare** [comment]
`!pushfq` in `.text` section

**Comment by lurumdare** [comment]
Alogirith for task

1. Find pushqd
2. Breakpoint to pushqd, Reset 
3. Breakpoint to .text section, Reset

**Comment by lurumdare** [comment]
SDK supporting trace to `pushqd` ? 
Maybe `RFLAGS == [RSP]` is good. 

And need functions for breakpoint section with name..

**Comment by mrexodia** [comment]
Pushfq is emulated already to not push the trap flag, so the rflags==[rsp]
doesn’t work. You can just use 2:[rip]==xx and “rip >= sectionStart && rip
< sectionEnd”. If you want more advanced functionality you can also use lua
or python or a simple plugin.

**Comment by lurumdare** [comment]
Can you explain detailed?

**Comment by mrexodia** [comment]
The manual can help you further, see the conditional tracing section and
introduction for how to use expressions.
