### ISSUE TITLE
Searching for string and calls takes forever

### ISSUE THREAD

**Issue by L3G4CYOne** [x64dbg/x64dbg#2281]
Searching for strings or calls take a lot of time.

All this builds have the same issue:
snapshot_2020-01-21_20-41.zip 
snapshot_2020-01-16_15-58.zip
snapshot_2020-01-15_21-53.zip
snapshot_2020-01-08_01-50.zip
snapshot_2019-11-26_13-35.zip

With this one snapshot_2019-11-13_01-33.zip it works fine.

**Comment by mrexodia** [comment]
Likely caused by/related to https://github.com/x64dbg/x64dbg/commit/b4a03a8009d94df67367ea4f72dd2581da299247

**Comment by iArtorias** [comment]
> Likely caused by/related to [b4a03a8](https://github.com/x64dbg/x64dbg/commit/b4a03a8009d94df67367ea4f72dd2581da299247)

I can actually confirm that reverting the changes back introduced in that commit, has fixed an issue. Please fix it ASAP. Thanks in advance !

**Comment by Christsnatcher** [comment]
I had the same issue as @L3G4CYOne, with the last working snapshot being snapshot_2019-11-13_01-33. @iArtorias has been so kind to let me test his fix and it is working perfectly for both x86 and x64. Please implement his fix as soon as possible for that we're able to actually use your latest snapshots again (talking about a reasonable search time obviously here)! Thank you!

**Comment by Christsnatcher** [comment]
I had the same issue as @L3G4CYOne, with the last working snapshot being snapshot_2019-11-13_01-33 and can confirm that @iArtorias is correct, reverting these particular changes resolves the issue on the latest snapshot both for x86 and x64, de facto giving me chance to use the latest snapshot without having to wait around 5 minutes for a string search to complete in a 50 MB binary. So, I would be very grateful if you'd revert that particular commit and fix this crucial bug for everyone. Thank you very much!

**Comment by mrexodia** [comment]
The issue is that perhaps it's fast, but it is incorrect and causes bugs when using the `GuiReference*` API. I'm currently thinking about how this issue can be solved without the bugs, but it doesn't seem to be very straightforward.

**Comment by mrexodia** [comment]
On my machine the performance increase drastically (from too long to wait for it to finish to 8.5 seconds on a 50mb exectutable)

**Comment by Christsnatcher** [comment]
I can confirm that the "bug" is no longer present in the latest snapshot, moreover, searching for strings, calls, etc now performs even faster than in the aforementioned "working" November build.

Thank you very much @mrexodia for finally resolving this issue!

**Comment by mrexodia** [comment]
👍🏻
