### ISSUE TITLE
Debug plugins

### ISSUE THREAD

**Issue by lurumdare** [x64dbg/x64dbg#2282]
How to debug plugins for x64dbg? Via source code.

**Comment by mrexodia** [comment]
Set x64dbg as the executable to launch in the plugin project settings.

**Comment by lurumdare** [comment]
@mrexodia SDK allow to set section breakpoint?

**Comment by mrexodia** [comment]
No?

**Comment by lurumdare** [comment]
@mrexodia link pls in SDK if function available.

**Comment by mrexodia** [comment]
There is no “function”. In your previous issue I outlined multiple
potential approaches you can take to automate your debugging process, but
it will require some effort from your end to automate things in a way
suitable to your problem.

**Comment by lurumdare** [comment]
@mrexodia I ask you whether it is possible to make it in practice not to waste time? you do not answer

**Comment by lurumdare** [comment]
@mrexodia 
https://i.imgur.com/rL7DUZ1.png

Where set as the executable ?

**Comment by mrexodia** [comment]
In the “Debugging” section, not in the post build step

**Comment by lurumdare** [comment]
@mrexodia https://i.imgur.com/MKuT0fF.png ?

How to correct?

**Comment by mrexodia** [comment]
Switch command and command arguments and also add a post build step to copy
the plugin to the plugins folder.

**Comment by lurumdare** [comment]
@mrexodia can you show example?

**Comment by mrexodia** [comment]
![](https://i.imgur.com/wOOF5Vo.png)

**Comment by lurumdare** [comment]
@mrexodia 
Well 
The plug-in was copied in the folder
But how to debug it now? exe is not started

**Comment by mrexodia** [comment]
Hm, now when you start debugging it should work.

**Comment by lurumdare** [comment]
https://i.imgur.com/i7dUva3.png
error 
https://i.imgur.com/VugWl0m.png

**Comment by mrexodia** [comment]
For debugging options you set the executable to x64dbg in the `Debugging` section, command line for x64dbg empty

**Comment by lurumdare** [comment]
Thanks. Worked.

Solution

https://i.imgur.com/AOhB1F8.png

**Comment by mrexodia** [comment]
Also another trick is to use `mklink` and create a symbolic link from your VS output to the x64dbg plugin directory. This way you do not need to have the additional copy post-build step.

`mklink c:\x64dbg\x64\plugins\Plugin.dp64 c:\source\bin\x64\Plugin.dp64`
