### ISSUE TITLE
x32dbg instructions don't visualize correctly sometimes

### ISSUE THREAD

**Issue by t4rmo** [x64dbg/x64dbg#2285]
Debugger version: x32dbg Jan 21 2020 straight from the repo, no plugins or mods

Operating system version:
VM:Windows 7 32bits SP1 and
Windows 10 Version 1909 Build 18363.628

The visualization of the instructions fails when i scroll up after of some kind of breakpoint.

https://www.youtube.com/watch?v=NYhBxxF-Pr0

**Comment by mrexodia** [comment]
See #1303, #1384, #1719
