### ISSUE TITLE
Feature: Keep the settings and db intact on update

### ISSUE THREAD

**Issue by thatcashcow** [x64dbg/x64dbg#2288]
I would like the new updates to keep the various settings (especially themes) the same. Please make it happen!

**Comment by mrexodia** [comment]
Your existing settings are not modified when updating x64dbg. Just copy over the ini files.

**Comment by thatcashcow** [comment]
Can we keep those settings and db in a more permanent location like %APPDATA% so as to avoid this manual work every time there is an update?

**Comment by mrexodia** [comment]
No, the idea of x64dbg is that it’s 100% portable. You can use one of the
many automatic updater plugins if you don’t feel like copying a single
folder when you update.

**Comment by thatcashcow** [comment]
Just adding this here : I found https://github.com/LFriede/x64dbg-updater to be working smoothly
