### ISSUE TITLE
Conditional Breakpoint on Write in an address

### ISSUE THREAD

**Issue by Rexkh** [x64dbg/x64dbg#2293]
Hello

I would like to know the right syntax for conditional breakpoint. I use other Debugger program but the syntax does not work in x64dbg. 

I set Break Condition to readInteger(0x0019FE00)==0x004C9DAC but it doesn't work. What is the correct syntax for x64dbg?

On the other hand, Where is x64dbg forum where we discuss about x64dbg and ask question?

**Comment by mrexodia** [comment]
There is a detailed document at https://help.x64dbg.com/en/latest/introduction/ConditionalBreakpoint.html.
