### ISSUE TITLE
Process execution pauses for too long while loading a comment database

### ISSUE THREAD

**Issue by alex-shr** [x64dbg/x64dbg#2296]
x32dbg Feb 11 2020.
Microsoft Windows [Version 10.0.18363.657]
I cann't attach x32dbg to time critical network client app (RF Online MMORPG client protected by Enigma). Comment database loading takes 6sec+ when x32dbg tries to attach to the process. During this time, the execution of the debugged application is completly suspended, which is enough to lose connection. "Attach breakpoint" option is OFF, but it does not help at all. 

Is it possible to move this database loading stuff into a separate thread?

**Comment by mrexodia** [comment]
It’s not really possible, because breakpoints are also loaded at this stage and you don’t want your breakpoints to not load.

In theory it isn’t necessary for the app to be suspended though, perhaps it’s possible to move database loading to before cbCreateProcess, but I doubt this use case is common enough. Generally you can just start the program under the debugger and things should work fine.

**Comment by alex-shr** [comment]
Starting the program under the debugger is not an option. There is another app - the launcher. This application logs on to the game server, launches the main client application and transfers encrypted data to it. This procedure is time critical, and cannot be done manually

**Comment by mrexodia** [comment]
Did you try gflags?

**Comment by blaquee** [comment]
Floating the idea here of “early attach” plugin execution. Then perhaps you could run something before all the necessary initialization. Just a thought

**Comment by mrexodia** [comment]
@blaquee Yeah you can already do that with`CB_INITDEBUG` and `CB_ATTACH`, which are called before the debug loop starts, but you cannot change the behavior of what happens in `cbCreateProcess`, which will hang the executable as long as it doesn't return.

See here for relevant code: https://github.com/x64dbg/x64dbg/blob/6407b2b063bdc3d54dd8a58ee549ff65942c1728/src/dbg/debugger.cpp#L2694-L2705

@alex-shr From where I'm sitting this looks like an impossible scenario to cover even in theory. There is never a guarantee that events in the debug loop are processed under a certain time threshold, so even if the database loading is optimized there might be lots of reasons why `cbCreateProcess` takes a very long time (disk i/o for instance, or other plugins)

**Comment by alex-shr** [comment]
This code is the problem.
https://github.com/x64dbg/x64dbg/blob/6407b2b063bdc3d54dd8a58ee549ff65942c1728/src/dbg/debugger.cpp#L1371-L1373
It takes 12 seconds under MSVC 2019 debugger. All other code of `cbCreateProcess` takes less than 0.5 second. Can you move it into `debugLoopFunction` before this part?
https://github.com/x64dbg/x64dbg/blob/6407b2b063bdc3d54dd8a58ee549ff65942c1728/src/dbg/debugger.cpp#L2707-L2723

**Comment by mrexodia** [comment]
It might be possible, but it's very tricky because it will no longer call `CB_LOADDB` from the debug thread like before which is something plugins might depend on. I will investigate if something is possible.

**Comment by mrexodia** [comment]
On further investigation I think it will be possible, will push a change
soon.

**Comment by alex-shr** [comment]
Many thanks!
