### ISSUE TITLE
arguments in call stack

### ISSUE THREAD

**Issue by MahdiMds-Lorx** [x64dbg/x64dbg#2302]
x64dbg dont show arguments in call stack but ollydbg show that
![Untitled](https://user-images.githubusercontent.com/59086060/75607131-257cf180-5b09-11ea-989e-3c8f27f22350.png)

**Comment by dauthleikr** [comment]
Look below the registers:
![image](https://user-images.githubusercontent.com/5332935/75609372-46911280-5b08-11ea-97ce-512a2a0d6c22.png)

**Comment by MahdiMds-Lorx** [comment]
that like olly?

**Comment by MahdiMds-Lorx** [comment]
???

**Comment by Boberttt** [comment]
Honestly it would be a cool feature
