### ISSUE TITLE
Shortcut for command

### ISSUE THREAD

**Issue by lurumdare** [x64dbg/x64dbg#2303]
How to setup with SDK?

**Comment by lurumdare** [comment]
GuiAddFavouriteCommand

**Comment by mrexodia** [comment]
Generally you shouldn’t connect shortcuts to commands directly. Instead create a menu item and use the _plugin_menuXXX API to assign a hotkey (it will also be configurable by the user from settings). Then in your CBMENUENTRY simply use DbgCmdExecDirect to execute your command (or DbgCmdExec to execute it async on the command queue)
