### ISSUE TITLE
Enable/Disable all breakpoints

### ISSUE THREAD

**Issue by F474M0R64N4** [x64dbg/x64dbg#2304]
add please to sdk

**Comment by mrexodia** [comment]
For now you can run `DbgCmdExecDirect("be");`

**Comment by F474M0R64N4** [comment]
How to check if all breakpoints are enabled?

**Comment by F474M0R64N4** [comment]
@mrexodia

**Comment by mrexodia** [comment]
`BRIDGE_IMPEXP int DbgGetBpList(BPXTYPE type, BPMAP* list);`

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/blob/54f399f5b106746513fe262c13ece20263f692ea/src/gui/Src/Utils/Breakpoints.cpp#L97
