### ISSUE TITLE
Bug multiple DbgCmdExecDirect

### ISSUE THREAD

**Issue by lurumdare** [x64dbg/x64dbg#2307]
Tested this code and not work correctly. 

 ```
  if(!DbgCmdExecDirect("run"))
    {
        return false;
    }
    if(!DbgCmdExecDirect("bd"))
    {
        return false;
    }
    if(!DbgCmdExecDirect("ts")) // ts command custom plugin with make .text section breakpointed
    {
        return false;
    }
    if(!DbgCmdExecDirect("run"))
    {
        return false;
    }
   if(!DbgCmdExecDirect("be"))
      {
          return false;
      }
```

if commented last `DbgCmdExecDirect("be")` = works.

What's problem?

**Comment by mrexodia** [comment]
https://x64dbg.com/blog/2016/10/20/threading-model.html

**Comment by lurumdare** [comment]
@mrexodia how to fix?

**Comment by mrexodia** [comment]
https://github.com/x64dbg/Scripts/blob/master/UpxUnpacker.cpp

https://github.com/x64dbg/docs/blob/master/commands/script/scriptdll.md

**Comment by lurumdare** [comment]
@mrexodia scriptdll allow key binding?

**Comment by mrexodia** [comment]
You can also just create a new thread in your plugin and use the script
api, doesn’t have to be a scriptdll

**Comment by lurumdare** [comment]
Okay. How to? https://i.imgur.com/nDUa686.png this code doesn't work.

**Comment by mrexodia** [comment]
Read the blog post I linked. The run/step command only tells the debug
thread to resume, it does not wait for it to pause again.

Pseudocode:

myThread:
  DbgCmdExecDirect(“step”)
  _plugin_waitforpause();


cbMyCommand:
  CreateThread(myThread)

See the ScriptAPI::Debug source code, all the commands execute
ScriptApi::Debug::Wait after running the command.

**Comment by lurumdare** [comment]
Thanks, problem solved.
