### ISSUE TITLE
AutoExportPatches plugin 

### ISSUE THREAD

**Issue by 16Darkhorse16** [x64dbg/x64dbg#2312]
Hello,
on X64DBG_snapshot_2020-02-23_16-38 run in Win 10 LTSC the plugin in subject doesn't show in the plugin menu.
I have installed copying AutoExportPatches.dp64 in \release\x64\plugins
Can you help me please?
Thanks

I

**Comment by mrexodia** [comment]
There is no menu, check the logs to see if the plugin has been loaded
