### ISSUE TITLE
Could not open process error

### ISSUE THREAD

**Issue by noobes1337** [x64dbg/x64dbg#2313]
https://i.imgur.com/WowycQF.png
I'm using x64dbg on a a 64 process and when i'm trying to attach the debugger to it, it gives me the error. Also that application is not visible in the attach list, i need to Find Window it

**Comment by mrexodia** [comment]
Check the FAQ. Anti cheat drivers are known to restrict handles from being opened so if that’s the case you will have to get rid of that first.
