### ISSUE TITLE
Locking window filter and refreshing view: Filter is removed

### ISSUE THREAD

**Issue by AntonVonDelta** [x64dbg/x64dbg#2317]
I can't lock the filter in the Handles>Windows filter and refresh the view because the filter will be removed.

**Before:**
![image](https://user-images.githubusercontent.com/25268629/78144726-a6951480-7438-11ea-99d1-961e26500701.png)

**After:**
![image](https://user-images.githubusercontent.com/25268629/78144765-b3196d00-7438-11ea-9b06-e6dbb9314d06.png)

- Version:  Feb 23 2020 on x32dbg
- Windows 10 x64 1909

Is there a quick fix I could implement myself? I need this feature.

**Comment by mrexodia** [comment]
Probably this won’t be so difficult to fix. Check the code responsible for filling the table (iirc HandlesView.cpp).
