### ISSUE TITLE
The display icon is wrong, it's too ugly, it's better than the previous 2015 version

### ISSUE THREAD

**Issue by NameS0me0ne** [x64dbg/x64dbg#2320]
For example, the CPU icon is a bell, or the 2015 version is comfortable

**Comment by MulleDK19** [comment]
Someone hasn't noticed that all icons have been replaced with random Easter related icons 😂

**Comment by DIH-965** [comment]
i want to use the original icons，what should i do?

**Comment by mrexodia** [comment]
You’re a reverse engineer, figure it out or wait until easter is over :)
