### ISSUE TITLE
Feature request: do not unload patch file on program restart

### ISSUE THREAD

**Issue by user202729** [x64dbg/x64dbg#2323]
- Debugger version: Apr 12 2020.
- Operating system version and Service Pack: Windows 10, 64 bit
- Brief description of the issue: When the "Restart" button (also control+f2) is pressed, the Patches list is deleted.
- Elaborate reproduction steps for the bug/issue being reported:

* Load any executable.
* Apply some patches.
* Press "Restart".
* Observe that the patches list is deleted.

Although it's possible to export the patches and then import it later, I'd rather it was automatic.

**Comment by mrexodia** [comment]
You can use the AutoExportPatches plugin

**Comment by simakovroman23** [comment]
```
```
```

```
```
```
