### ISSUE TITLE
"An error occurred when reading trace file"  if restart program while tracing

### ISSUE THREAD

**Issue by user202729** [x64dbg/x64dbg#2326]
- Debugger version: Apr 12 2020.
- Operating system version and Service Pack: Windows 10, 64 bit
- Brief description of the issue: (title)
- Elaborate reproduction steps for the bug/issue being reported:

* Right click in the "trace" tab -> "start run trace" -> choose any file.
* F7 a few times to fill the trace window.
* control+F2 (restart the program)
* Go to the trace window.
* Press F7.

In the status bar, the error message "An error occurred when reading trace file" is displayed.

**Comment by torusrxxx** [comment]
Thank you for your feedback. This issue has been fixed. If you still experience this issue in latest version please tell us.
