### ISSUE TITLE
After closing all References tabs, no way to return them

### ISSUE THREAD

**Issue by OfekShilon** [x64dbg/x64dbg#2331]
I accidentally closed the last References tab:
![image](https://user-images.githubusercontent.com/73080/81279018-33964380-905f-11ea-8274-5815f8297f4d.png)

I followed your advice [here](https://reverseengineering.stackexchange.com/a/18533/14073) and tried many other things - but can't find a way to bring it back.

**Comment by mrexodia** [comment]
If you close a tab in references the data is gone. Search for references again to bring it back.
