### ISSUE TITLE
[FEATURE REQUEST] Jump to address/jump into function with middle mouse click

### ISSUE THREAD

**Issue by enkeyz** [x64dbg/x64dbg#2332]
This is a feature request, for adding functionality for the middle mouse button. 

If you click on a command with middle mouse button, and that command contains a jump or a function call, then x64dbg jumps to that address/or jumps into the function.

Yeah, I know you can do it with the Enter button on the keyboard, but you always use the mouse, and the middle mouse button isn't used for anything.

**Comment by enkeyz** [comment]
And what about CTRL/SHIFT/ALT + middle mouse?

**Comment by mrexodia** [comment]
I honestly think it would be better to allow changing the behavior of double click, because I don't think anyone ever needs to assemble when doing double click...

**Comment by enkeyz** [comment]
Ty!
