### ISSUE TITLE
[Feature Request] add new settings

### ISSUE THREAD

**Issue by rezaf28** [x64dbg/x64dbg#2339]
Hi!
Please add:
1- "always on top" checkbox 
2- "always clear database" on exit program OR add detabase clear button.
3- "always hidden debugger" ( not use in plugins) command: hide
4- "always Run As Admin"
thanks.

**Comment by mrexodia** [comment]
1. Options -> Topmost
2. Use debuggee initialization script (command `dbclear`)
3. Use debuggee initialization script (command `hide`)
4. Use windows explorer properties -> compatibility -> run as administrator
