### ISSUE TITLE
[Feature Request] Show all Calls

### ISSUE THREAD

**Issue by rezaf28** [x64dbg/x64dbg#2341]
Hi!
Plesae show all threads calls in one tab of call stack.
some programs use many thread and user most get all call stacks one one.
for better show you can splite with line. example: software and hardware breakpoint spliter line.
Thanks.
info:
windows 10 latest stable build Build 18363
x64dbg apr-28-2020

**Comment by mrexodia** [comment]
This should be pretty easy to implement for anyone who would like to try.
