### ISSUE TITLE
[Feature Request] Create new Icon 

### ISSUE THREAD

**Issue by rezaf28** [x64dbg/x64dbg#2342]
Hi!

most users for fast use x64dbg pin it in taskbar, but your icons 32 and 64 text in 4k and 1080 resolutions not detectable.
Please Change old icons with new icons.
you can change color of icons. exp: for 32 red for 64 blue.
OR you can write on bug-fly (i dont know what say in english)
thanks.
svg files to create with custom config:
[icons.zip](https://github.com/x64dbg/x64dbg/files/4619203/icons.zip)

temp:
![x64dbg_32](https://user-images.githubusercontent.com/25824853/81759739-c3624480-94da-11ea-9f86-c3494b027756.png)
![x64dbg_64](https://user-images.githubusercontent.com/25824853/81759743-c52c0800-94da-11ea-8d7c-aea2313a94ec.png)

info:
windows 10 latest stable build Build 18363
x64dbg apr-28-2020

**Comment by mrexodia** [comment]
There are no plans to change the icon. Perhaps a recoloring will be considered though
