### ISSUE TITLE
"Find Refrences to" bad module use for search

### ISSUE THREAD

**Issue by rezaf28** [x64dbg/x64dbg#2343]
Hi!
if use want to search refrences to current address , x64dbg just search in current module (write on window top title).
exp:
i am in pcdbasic.dll and want to search refrences from main module (main module ==> text.exe)
![x64dbg_001](https://user-images.githubusercontent.com/25824853/81761051-230e1f00-94de-11ea-9ce0-9019880ea02f.png)

but when click 
![x64dbg_002](https://user-images.githubusercontent.com/25824853/81761055-25707900-94de-11ea-9eac-7fc056dc25bd.png)

i can't search from module , only search from current region.
please add search from main module and user module.
thanks.
info:
windows 10 latest stable build Build 18363
x64dbg apr-28-2020

**Comment by mrexodia** [comment]
Yep that is how it works. References are in the current page your view in the disassembly
