### ISSUE TITLE
Exceptions all the time???

### ISSUE THREAD

**Issue by petkovic** [x64dbg/x64dbg#2344]
mate im getting exception almost all the time, im dbg some stuff in maya and no matter what i do im getting the exceptions

win 10 x64
x64dbg - May 9 2020

EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000409 (STATUS_STACK_BUFFER_OVERRUN)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FFA2FC0DB9E ucrtbase.00007FFA2FC0DB9E
        NumberParameters: 1
ExceptionInformation[00]: 0000000000000007
Last chance exception on 00007FFA2FC0DB9E (C0000409, STATUS_STACK_BUFFER_OVERRUN)!

**Comment by petkovic** [comment]
here is one more

EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: 0000000000000000
        NumberParameters: 2
ExceptionInformation[00]: 0000000000000008 DEP Violation
ExceptionInformation[01]: 0000000000000000 Inaccessible Address
Last chance exception on 0000000000000000 (C0000005, EXCEPTION_ACCESS_VIOLATION)!

**Comment by blaquee** [comment]
You can always choose to add them to the ignored exception list

**Comment by petkovic** [comment]
I did, but still getting exception, i can show you a tons of ignores in the exception list

**Comment by mrexodia** [comment]
If a program crashes it will raise exceptions. This could be caused by anti-debug (NtQueryInformationProcess), try a plugin to hide the debugger.
