### ISSUE TITLE
[feature request] count successful and failed jumps

### ISSUE THREAD

**Issue by malis2007** [x64dbg/x64dbg#2345]
Hello there :)
could there be a feature to count all jumps from a breakpoint to another and add them to the comment column? with two options to choose from, either step into or step over
example (image taken from ollydbg, i did the count manually):
https://images2.imgbox.com/63/90/WyhcrCHX_o.png
X = didn't jump
V = did jump
from the image we see: it didn't jump for 7 times, then jumped once, then didn't jump for 53 times [X7 V1 X53]
i think that this feature will be helpful to compare re-runs (each re-run is separated by something like > in the comments column)
https://images2.imgbox.com/6e/c9/9URWVvUl_o.png

what do you think?

**Comment by dovezp** [comment]
You can do this already, in theory with the breakpoints manager in x64dbg. 

Alternatively, you can use the capstone library and find conditional jump locations, create a breakpoint manager in x64dbgpy for each conditional jump found, and on handling each breakpoint save all registers and store into each result into "execution" arrays for the address.

**Comment by mrexodia** [comment]
This is a feature for a plugin because it is too specialized.
