### ISSUE TITLE
when having set a breakpoint and you try to re-set it and after run, it runs without breaking at breakpoint

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#235]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/235
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2015-01-02T15:44:36.533

**Comment by mrexodia** [comment]
assuming this was fixed.
