### ISSUE TITLE
Variable names cannot start with [a-fA-F]

### ISSUE THREAD

**Issue by mappzor** [x64dbg/x64dbg#2360]
Didn't look at code but it seems rather obvious that this happens because first argument to `var` command is interpreted as hex digit, so `Invalid variable name` error is returned.

Example:
```
> var a
Invalid variable name "a"
> var f
Invalid variable name "f"
> var g
g=0 // OK
```
Also when variable already exists it would be nice to get information about that instead of "invalid variable name".

EDIT: I misnamed this bug a bit because problem occurrs only when whole name can be interpreted as hex number.
By the way it seems that command `varlist` is a nop.

**Comment by mrexodia** [comment]
`varlist` outputs to the reference view (it's in view -> variables) but I agree this is not entirely obvious. The variable names `a,b,c,d,e,f` are indeed not valid because there is no `0x` prefix and nothing can be done to change this without completely changing the way expressions work

**Comment by mappzor** [comment]
Oh, I expected varlist would use log window.

I expected that changing this could be hard to get things like `var a` working but what about second possible syntax `var $a`?

**Comment by mrexodia** [comment]
Hm generally in x64dbg you do not actually have to declare variables, I just checked and `$a=6` works fine :)
