### ISSUE TITLE
How to turn off this 'mouse hover preview tooltip window'

### ISSUE THREAD

**Issue by Symbai** [x64dbg/x64dbg#2361]
How do I turn off this tooltip window which appears when I mouse hover a call instruction? I'm using the latest version but cannot find an option in the preferences for this.

**Comment by mrexodia** [comment]
Previously code existed to disable this feature, it was supposed to be moved to the settings dialog but it never was. Fix would be to call `setDisassemblyPopupEnabled(false)` in the `Disassembly` class.

**Comment by jackreez** [comment]
Fixed in #2371 
Issue can be closed.
