### ISSUE TITLE
Stack and memory dump in trace browser

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2378]
Add call stack and memory dump in trace browser, based on information available in trace file. This requires the trace file be scanned from current selected instruction up to the first one.

(I'm working on this, let me create an issue first, currently there is no dump or stack window in trace view, references and log view will be used first)

**Comment by requizm** [comment]
Why hasn't anyone written anything? I was guessing this is a highly requested feature but there is no interaction.

**Comment by requizm** [comment]
> Crazy right? Almost like this is an open source project where nobody gets paid to implement anything...

@mrexodia  You're right. I'm sorry if I'm being rude. I'm just surprised there has been no comment on this issue in 2-3 years.

**Comment by mrexodia** [comment]
You are welcome to contribute! If you have any questions feel free to drop them here or you can start a discussion/connect in one of the chats.

**Comment by torusrxxx** [comment]
I don't have any code written for this since 2020... It's very complicated. Every memory accesses in the trace would be indexed by a tree with key {address, traceindex} in order to find the current content at any address at any instruction execution very fast. The index may need to be stored in the trace at the end of tracing or when closing the trace file.

**Comment by torusrxxx** [comment]
I'm still planning to start on this in 2023. If anybody is interested, leave a message here.

**Comment by torusrxxx** [comment]
My TODO list
- [ ] Create dump reconstruction object
- [ ] Feed data into dump reconstruction object
- [ ] Add find references dialog similar to xrefs
- [ ] Add call stack view
- [ ] Add dump view
- [ ] Add unpack/dump support
- [ ] Add find strings support
- [ ] Add find pattern support
- [ ] Write memory map into trace file
- [ ] Add memory map view
- [ ] Add modules view
- [ ] Fix randomised module base in trace file
- [ ] Replace tree implementation with custom one and add storage support
