### ISSUE TITLE
无法载入style.css 皮肤文件,咋回事

### ISSUE THREAD

**Issue by 327065266** [x64dbg/x64dbg#2390]
无法载入style.css 皮肤文件,咋回事

**Comment by torusrxxx** [comment]
我全新下载snapshot_2020-07-11_21-00.zip并检查了没发现问题。

**Comment by mrexodia** [comment]
theme are now in `x64dbg\bin\themes\<My theme name>\style.css`, can be loaded from `Options -> Theme`
