### ISSUE TITLE
最新版的DBG皮肤设置成黑色就无法看到设置选项了

### ISSUE THREAD

**Issue by 327065266** [x64dbg/x64dbg#2391]
最新版的DBG皮肤设置成黑色就无法看到设置选项了

**Comment by torusrxxx** [comment]
我全新下载snapshot_2020-07-11_21-00.zip并检查了没发现问题。

**Comment by wwh1004** [comment]
@torusrxxx
确实看不清是不是选了选项
![image](https://user-images.githubusercontent.com/27536652/89100630-379deb80-d42b-11ea-897f-08e9b392b786.png)

**Comment by mrexodia** [comment]
Fixed in https://github.com/x64dbg/x64dbg/commit/d0eaef34e39b7c939b8ecbc27e24cf3c4647577f
