### ISSUE TITLE
(Feature request) Replay run trace

### ISSUE THREAD

**Issue by astandarduser** [x64dbg/x64dbg#2393]
So I am trying out run trace and notice there is no ability to replay (or maybe I just can't find it), would be a nice feature

**Comment by torusrxxx** [comment]
I don't understand how replay will work with x64dbg. For example, you recorded a run trace when you entered the correct serial for a crackme. Next time, you entered an invalid serial and breaks at the same breakpoint where the run trace started. Will simply replaying the previous run trace bring you the login success page?
