### ISSUE TITLE
(Feature request) Export trace to csv

### ISSUE THREAD

**Issue by astandarduser** [x64dbg/x64dbg#2394]
Would be a nice feature to have, here is an example usage https://www.youtube.com/watch?v=DJP-dFRoA6Q   
Even just export as a plain text format would be nice to have

**Comment by torusrxxx** [comment]
For now you can select all, right click, copy anything you want and paste in a document.

**Comment by torusrxxx** [comment]
We need to provide the user an option to export something, but the question is what to export and in what format (at the time of writing the run trace I was actually looking for an existing format but found none). Perhaps we should enable the user to reproduce a log file from the trace file as if they were rerun with trace logging enabled, but that creates a problem that the expression evaluation only works with current state, not with state recorded in a trace. And a fixed function CSV export is no better than simply copying.

**Comment by torusrxxx** [comment]
For tracing difference you can use trace record. First re-enable trace record, and then enter the correct serial while tracing. Next time enter an incorrect serial and use "trace into beyond trace record" you'll instantly land at where the program executes "password incorrect" code!

**Comment by astandarduser** [comment]
> For now you can select all, right click, copy anything you want and paste in a document.

You are right, you can copy and paste, although things might get a bit iffy with a large trace file, an export to txt, csv would be good, just as long as the different columns are separated by something

**Comment by torusrxxx** [comment]
added in #2436
