### ISSUE TITLE
Regression: highlighting underline

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#2402]
Here's highlighting ecx:

![image](https://user-images.githubusercontent.com/5781692/88464945-66661000-cec7-11ea-8017-5cf4b68da04b.png)

See how it difficult to notice and the color is similar to "rbp". Before it was a red underline, much more visible. Please revert. Thanks.

**Comment by mrexodia** [comment]
Generally I would like to keep this way of highlighting because of the dark
theme, but I agree with you it might be better to have an option.

**Comment by justanotheranonymoususer** [comment]
It's much less useful this way, before I could spot highlights at a glance, now there's no chance, much much worse :(

**Comment by torusrxxx** [comment]
Yeah, I like the style before.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/88479595-99a0b180-cf50-11ea-95c2-cbf99b7a978c.png)

How about this? I think the change is necessary to support a proper dark theme so I don't want to revert it. It looks like this on the default dark theme:

![image](https://user-images.githubusercontent.com/2458265/88479612-b2a96280-cf50-11ea-91e4-3253e079a64c.png)

**Comment by torusrxxx** [comment]
Well, it doesn't work because the highlight background color is the same as selection background color.

**Comment by justanotheranonymoususer** [comment]
What's wrong with a red underline in a dark theme?

**Comment by mrexodia** [comment]
The bottom of the word is cut off and you can no longer read the text. I don't want to change this back, please try on your configuration what foreground+background works for you and we can change the default 🙂

**Comment by justanotheranonymoususer** [comment]
What about underlines in dump? Is it not the same?

**Comment by mrexodia** [comment]
Yes, those indeed cause reading problems and I think have been removed from
the dark theme to make things look nice.

**Comment by justanotheranonymoususer** [comment]
Really, so you just removed the underline from the dump as well? :(
These were handy.
Can't the underline be fixed to play nice with a dark theme? What's the difference anyway? It's just a line.
Sounds wrong to throw a bunch of powerful visual hints for a minority that prefers dark theme, instead of fixing it or at least making it optional (preferably on by default).

**Comment by mrexodia** [comment]
I checked and for the dump everything is looking fine, no visual hints have
been thrown away.

Again, please provide me with highlighting colors that work for you because
I don’t plan to revert this change.

**Comment by torusrxxx** [comment]
What about using the current coloring scheme for unusual instructions
(black text in dark red background), or white text in dark red background?

**Comment by mrexodia** [comment]
Yeah I thought about that but then it’s the same as those ^^

**Comment by torusrxxx** [comment]
Then black/white text on bright red background(#FF0000) ? Also the segment "fs/gs" color needs a separate setting from unusual instructions.

**Comment by justanotheranonymoususer** [comment]
> What about using the current coloring scheme for unusual instructions

That's clearly better than the current highlighting. But as @mrexodia said not ideal. Perhaps the unusual instructions can be made less visible in highlighted mode.

e.g. without:
![image](https://user-images.githubusercontent.com/5781692/88663823-d7364380-d0e4-11ea-9356-c597ce12727f.png)

with:
![image](https://user-images.githubusercontent.com/5781692/88663829-da313400-d0e4-11ea-8871-a3f9867da070.png)

**Comment by mrexodia** [comment]
It's unfortunately not possible to determine whether something is highlighted, at least not in a different instruction. For now I've settled with foreground `#000000`, background `#CC0000` and it's working nicely for me (not very many unusual instructions and I didn't find things confusing when they were both visible as highlighting is something you have to do consciously).

**Comment by justanotheranonymoususer** [comment]
That's not too bad, thanks, but how about changing the text color to white?

Otherwise it's hardly readable, and yes, I'm supposed to know what I chose to highlight, but e.g. I need to see ecx vs rcx.
A bonus is that it'll be also different from the ud highlighting.

![image](https://user-images.githubusercontent.com/5781692/89121667-6ff40700-d4c9-11ea-900d-eb688a8bb753.png)

**Comment by mrexodia** [comment]
I personally cannot read the text when it’s any shade of white, but that’s
why there are settings.

**Comment by justanotheranonymoususer** [comment]
Good defaults are important, too :)

**Comment by mrexodia** [comment]
🤷🏻‍♂️
