### ISSUE TITLE
Unable to delete comment

### ISSUE THREAD

**Issue by caomfan** [x64dbg/x64dbg#2409]
- Debugger version: Jun 22 2020, 14:18:43.
- Operating system version: Windows 10 1903

**Comment by mrexodia** [comment]
I cannot reproduce this, can you give reproduction steps?

**Comment by caomfan** [comment]
Ctrl+Alt+C,In this window, the comment cannot be refreshed immediately after deleting it, in fact it has been deleted

**Comment by torusrxxx** [comment]
Duplicate of #999
