### ISSUE TITLE
Cannot import patch file, does not appear - snapshot_2020-08-04_21-21.zip

### ISSUE THREAD

**Issue by Maxzor** [x64dbg/x64dbg#2417]
This must be a stupid Qt filesystem filtering-box issue.
I want to apply a patch to a program : cannot find the .1337 file in the explorer with the filter set.
Option to select all file types too maybe?

**Comment by StackerDEV** [comment]
Sams issue in snapshot_2020-08-16_04-47

Also will FileDialog will not find *.1337 extensions while in  Patches window and by pressing import.

Solution/workaround; 
Make sure to type full file name and extension then save will succeed (when saving patches)
Make sure to type full name and extension in Import/Export function for it to properly work.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/93711162-64799f80-fb4c-11ea-9412-178176df6652.png)

Working fine over here 🤷‍♂️
