### ISSUE TITLE
How to change bottom status bar text color

### ISSUE THREAD

**Issue by wwh1004** [x64dbg/x64dbg#2427]
I want to change bottom status bar text color.  I have tried almost all color settings, but I still can't change it.
![image](https://user-images.githubusercontent.com/27536652/90026226-9d228f80-dce9-11ea-8d33-fe962a1e2e9b.png)
I almost can't see anything.

**Comment by mrexodia** [comment]
Strange, I’m pretty sure this is working fine with the default dark theme.

**Comment by wwh1004** [comment]
it is my style.css, i have used it for a long time. so i want to use it in new x64dbg, but i found i can't change bottom status bar text color.

**Comment by mrexodia** [comment]
Check the documentation for Qt or base your theme on https://github.com/x64dbg/x64dbg/blob/development/bin/themes/Dark/style.css there is nothing special for this text, it's just a `QLabel` and you can modify it with the css

**Comment by ScyllaHide** [comment]
Okay you can fix this very easy by setting color of the QStatusBar QLabel from black to white in the style sheet file.

`QStatusBar QLabel {
    color: white;
}`
