### ISSUE TITLE
[Feature] Binary select

### ISSUE THREAD

**Issue by morsisko** [x64dbg/x64dbg#2428]
What do you think about "Binary -> Select" feature that can select a block of bytes in range X to Y? This is a common option in many hex editors, and it might be useful in some cases, for example when you need to extract a non standard amount of bytes like 0x567. At the moment you have the option to select it manually using mouse or by holding the shift key, however it is a bit tedious process, especially when the amount of bytes to select is quite high. The feature could be added to the `Dump` context menu, "Right click dump -> Binary -> Select"

There is a screenshot from one popular program, just for reference, of course the widget could be adapted to x64dbg style:
![https://i.imgur.com/oyCCydx.png](https://i.imgur.com/oyCCydx.png)

This is not super useful feature, however in my opinion it would be nice to have, as it would make life easier in some situations.

**Comment by mrexodia** [comment]
https://github.com/mrexodia/ExtendDumpSel

**Comment by morsisko** [comment]
Thanks, I wasn't aware about that plugin. Although it is sufficient for me it still could be nice idea to add it to main release, maybe with some sort of frontend.

Anyway it's only my opinion.

**Comment by morsisko** [comment]
If someone is interested in this feature, I've created simple plugin: https://github.com/morsisko/xSelectBlock

![2020-10-25_15-04-41](https://user-images.githubusercontent.com/11231925/97112015-4ae6ed00-16e2-11eb-9e7a-6e681cc96436.gif)
