### ISSUE TITLE
Follow in Dump Not Working

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#243]
This bug is not easy to explain in words so I made a video to make it clear:
https://www.youtube.com/watch?v=WlVvrgNBGJc&feature=youtu.be

This bug happens every time I try to open that software in the debugger so any extra information needed I can get.

Edit: In the video it shows that the Stack Window is working when I try to "Follow in Dump", but the truth is sometimes it does not work as well.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/243
- Originally reported by: Demonic Sword
- Originally created at: 2015-01-09T05:57:07.933

**Comment by mrexodia** [comment]
this is an issue that still exists. it has to do with trying to dump near the end of the page. somehow this doesn't work.

**Comment by Zer0-One** [comment]
I'm having this same issue

**Comment by mrexodia** [comment]
Do you have a reliable way to reproduce the issue?
