### ISSUE TITLE
Load Executable/PE into x64dbg without the required DLLs

### ISSUE THREAD

**Issue by MegaBor** [x64dbg/x64dbg#2437]
Unfortunately using x64dbg cannot load a PE into the debugger without the required DLLs.

If I drag PE into x64dbg, whilst the DLLs are not in the same directory, I get the error:
`The code execution cannot proceed because DLLNAME was not found. Reinstalling the program may fix this problem`

I created this issue, because in OllyDbg it is allowed to load a PE without the required DLLs.

It can be useful if I just want to quickly analyze some of the instructions without debugging the process or if I want to apply a quick patch.

I have been googling this and couldn't find any information in regards, therefore I create this issue and wanted to ask if there is any configuration that makes this possible?

Thank you for your time!

**Comment by mrexodia** [comment]
This is by design. Personally I use: https://github.com/mrexodia/IATFaker
