### ISSUE TITLE
Goto Address Not Working

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#244]
A video that explains the issue: https://www.youtube.com/watch?v=V1-6aYC8egQ&feature=youtu.be

It happens every time I try to goto an address not located in any section of the Memory Map. Other debuggers show the address correctly (Other debuggers = OllyDbg 1.10).

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/244
- Originally reported by: Demonic Sword
- Originally created at: 2015-01-09T06:22:58.613

**Comment by mrexodia** [comment]
assuming this is fixed.
