### ISSUE TITLE
Can 't edit instructions

### ISSUE THREAD

**Issue by arg2das** [x64dbg/x64dbg#2444]
Hello,

I have been unable to use the lastest build of **x64dbg** on **Windows 10**, as it it does anything when double-clicking the instructions to edit them, though it actually follows _calls_ and _jumps_...

I have tried with some older versions, with no luck. Even if I run it with admin privileges and also the debug ones.
It happens both with **x32dbg** and **x64dbg**, at first I thought it could have something to do with read only memory, but I don 't think that is the case, as it worked before reinstalling Windows.
I can 't get it to work in any program.

Any help is appreciated.

Thanks

**Comment by mrexodia** [comment]
The behavior has been changed to allow a more intuitive navigation for most people. You can still achieve the same by first selecting the instruction and then pressing space (you can customize this hotkey).
