### ISSUE TITLE
 How to switch the debugging engine?

### ISSUE THREAD

**Issue by CNLouisLiu** [x64dbg/x64dbg#2447]
Version sep 14 2020
How to switch to Titan engine, the new engine makes xAnalyzer unable to work.

**Comment by 0xCCh** [comment]
In x64dbg.ini replace the line
DebugEngine = 1 
to 
DebugEngine = 0

**Comment by CNLouisLiu** [comment]
thanks

**Comment by mrexodia** [comment]
> In x64dbg.ini\x32dbg.ini replace the line
> DebugEngine = 1
> to
> DebugEngine = 0

Thanks for helping out!
