### ISSUE TITLE
Problem with "String references" search.

### ISSUE THREAD

**Issue by dhanzek** [x64dbg/x64dbg#2449]
On newer snapshots I encounter problem with string search (Search for -> Current module -> String references),
which manifest as not finding all strings in module.

Example:
As of "snapshot_2020-07-29_04-15" the X32dbg yield no result for searching string "This feature"
in "VB Decompiler.exe" (VB Decompiler Lite v11.5, https://www.vb-decompiler.org/download.htm).
Last good snapshot which can find string was "2020-07-25_13-18".

**Comment by torusrxxx** [comment]
The string that is not found is longer than current max value (60 bytes) and therefore not found. I'll try to fix it.
