### ISSUE TITLE
new snapshot seems to have broken some plugins

### ISSUE THREAD

**Issue by grog169** [x64dbg/x64dbg#2450]
both x32 & x64 versions
---------------------------
x32dbg [Elevated]: x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library C:\x64dbg\x32\plugins\CodeShot.dp32. 

The procedure entry point GetContextData could not be located in the dynamic link library C:\x64dbg\x32\plugins\CopyToAsm.dp32. 

The procedure entry point GetContextData could not be located in the dynamic link library C:\x64dbg\x32\plugins\Ktracer.dp32

The procedure entry point ImporterGetRemoteAPIAddressEx could not be located in the dynamic link library C:\x64dbg\x32\plugins\x64dbgApiBreak.dp32. 

The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library C:\x64dbg\x32\plugins\xAnalyzer.dp32.

**Comment by blaquee** [comment]
This looks like its due to the new Debug Engine. In your .ini file look for the entry `DebugEngine` and change the value back to 0. Do not switch to the GleeBug as this is the cause. 

@mrexodia any chance we can add a gleebug tag for issues directly related to GleeBug?

**Comment by mrexodia** [comment]
Added a tag!

**Comment by mrexodia** [comment]
Try this https://ci.appveyor.com/api/buildjobs/s5k708v0k50thpjt/artifacts/bin.zip (put `TitanEngine.dll` in `GleeBug\TitanEngine.dll`)

**Comment by grog169** [comment]
Thanks. previous issues fixed. Now getting these issues.

---------------------------
x32dbg [Elevated]: x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point ConvertVAtoFileOffset could not be located in the dynamic link library C:\!rev\x64dbg\x32\plugins\Ktracer.dp32. 
The procedure entry point GetDebuggedDLLBaseAddress could not be located in the dynamic link library C:\!rev\x64dbg\x32\plugins\x64dbgApiBreak.dp32.

**Comment by mrexodia** [comment]
Thanks, I will check those plugins later!

**Comment by UnlimitedChild** [comment]
Hi,

snapshot_2020-10-29_00-29.zip

---------------------------
x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetContextData could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\CopyToAsm.dp64. 
---------------------------
OK   
---------------------------


---------------------------
x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point ConvertVAtoFileOffset could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\idaldr.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\testplugin.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point ImporterGetRemoteAPIAddressEx could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\x64dbgApiBreak.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\x64dbg_sync.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetContextData could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\xAnalyzer.dp64. 
---------------------------
OK   
---------------------------

**Comment by UnlimitedChild** [comment]
This plugin, as I understand it, can be removed ..
---------------------------
Exception! Please report it! OS: 47BB000A
---------------------------
ExceptionCode C0000005

ExceptionFlags 00000000

NumberParameters 00000002

ExceptionAddress VA 00007FFE6F35157B - Base 00007FFE6F350000

ExceptionAddress module GetCharABCWidthsI_cache.dp64

**Comment by UnlimitedChild** [comment]
x64dbg - 32bit (snapshot_2020-10-29_00-29.zip)

`---------------------------
x32dbg: x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\APIInfo.dp32. 
---------------------------
OK   
---------------------------
---------------------------
x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetContextData could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\CopyToAsm.dp32. 
---------------------------
OK   
---------------------------
---------------------------
x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point ConvertVAtoFileOffset could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\idaldr.dp32. 
---------------------------
OK   
---------------------------
---------------------------
x64dbg - 31st October: National Candy Apple Day (US): x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDebuggedFileBaseAddress could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\x64dbgApiBreak.dp32. 
---------------------------
OK   
---------------------------
---------------------------
x64dbg - 31st October: National Candy Apple Day (US): x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\x64dbg_sync.dp32. 
---------------------------
OK   
---------------------------
---------------------------
x64dbg - 31st October: National Candy Apple Day (US): x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetContextData could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\xAnalyzer.dp32. 
---------------------------
OK   
---------------------------

`

**Comment by mrexodia** [comment]
Please try the new version (not yet in the x64dbg repo) from https://ci.appveyor.com/project/mrexodia/gleebug/builds/36066789

**Comment by UnlimitedChild** [comment]
Now looks like this>
```
---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point DumpProcess could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\testplugin.dp64. 
---------------------------
OK   
---------------------------
---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDebuggedFileBaseAddress could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\x64dbgApiBreak.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDebuggedFileBaseAddress could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\x64dbgApiBreak.dp32. 
---------------------------
OK   
---------------------------

```

**Comment by UnlimitedChild** [comment]
snapshot_2020-11-12_05-12.zip

one api left to fix ... 
```
---------------------------
x64dbg: x64dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDebuggedDLLBaseAddress could not be located in the dynamic link library N:\x64dbgWithoutStyle\x64\plugins\x64dbgApiBreak.dp64. 
---------------------------
OK   
---------------------------

---------------------------
x32dbg.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDebuggedDLLBaseAddress could not be located in the dynamic link library N:\x64dbgWithoutStyle\x32\plugins\x64dbgApiBreak.dp32. 
---------------------------
OK   
---------------------------

```

Thanks for your work!

**Comment by mrexodia** [comment]
Hm that API is actually no longer supported at all (it currently returns 0), but easy enough to implement I guess 😄

**Comment by UnlimitedChild** [comment]
Does the author know about this? =)
https://github.com/0ffffffffh/Api-Break-for-x64dbg/releases/tag/BETA
