### ISSUE TITLE
Patch File Crashing

### ISSUE THREAD

**Issue by niwow** [x64dbg/x64dbg#2452]
I'm using the latest version 2020/9/14  On Windows  . When i try to  patch a file ,it will stop and become non clickable.And it will crash automatically. I tried serval times, but it can't become better. Thanks for help !

**Comment by mdrb97** [comment]
Having the exact same problem. I can save patches in the form of .1337 files but I cannot "export" a .exe file.

**Comment by niwow** [comment]
I‘m fine with export and import function,but i just can't patch it .

**Comment by ly021012** [comment]
Having the exact same problem

**Comment by thecocce** [comment]
The problem occurs when using "GleeBug" engine.

**Comment by lhsazevedo** [comment]
Same here, let me know if theres some log I can share to help narrow it down

**Comment by torusrxxx** [comment]
This is a bug of GleeBug and you can turn off GleeBug by command `config Engine,DebugEngine,0` and restart.

**Comment by pedroflor** [comment]
> This is a bug of GleeBug and you can turn off GleeBug by command `config Engine,DebugEngine,0` and restart.

Confirm that this workaround (disabling GleeBug) allows to patch .exe files.

**Comment by KITT3000** [comment]
On the version 2020-11-05_15-25 this problem still occurs, manually changing the engine in the options does not help, only using the command in the console.

**Comment by mrexodia** [comment]
Changing the engine works fine for me, did you restart the debugger after?

**Comment by NguyenCongVN** [comment]
Changing the debugger by command but not by changing in preferences that works fine for me
