### ISSUE TITLE
can you give an example to "Trace over"

### ISSUE THREAD

**Issue by zezezez** [x64dbg/x64dbg#2454]
I have use the function "**Trace over**" in Trace window .but I failed.Can you give me an example of using "Trace over".thank you.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/93716466-4e7dd600-fb70-11ea-9df2-0a4e4a05bec2.png)

![image](https://user-images.githubusercontent.com/2458265/93716470-5473b700-fb70-11ea-95db-52b538d5d9fd.png)

![image](https://user-images.githubusercontent.com/2458265/93716476-5dfd1f00-fb70-11ea-9386-aed74c600e6b.png)

![image](https://user-images.githubusercontent.com/2458265/93716480-66555a00-fb70-11ea-9247-0905296937ad.png)

![image](https://user-images.githubusercontent.com/2458265/93716488-6e14fe80-fb70-11ea-9341-60f3e5d4a70d.png)

**Comment by zezezez** [comment]
thanks
