### ISSUE TITLE
x64dbg patch file crash

### ISSUE THREAD

**Issue by ly021012** [x64dbg/x64dbg#2461]
x64dbg patch file crash how to solve.

**Comment by ly021012** [comment]
I can save patches in the form of .1337 files but I cannot "export" a .exe file

**Comment by thecocce** [comment]
The problem occurs when using "GleeBug" engine.

**Comment by thecocce** [comment]
Duplicate to this ?

https://github.com/x64dbg/x64dbg/issues/2452

**Comment by mrexodia** [comment]
Yes, thanks for the help @thecocce
