### ISSUE TITLE
No setting in GUI to change engine

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#2463]
The message says:

> GleeBug is now available for beta testing, would you like to enable it? Some bugs can be expected, but generally things are looking stable!
> 
> You can change this setting in the Settings dialog.

But looks like there's no setting. I found from the source that I have to change manually in the ini file.
For reference for others and future me:

```
[Engine]
DebugEngine=0
```

Values:

- TitanEngine - 0
- GleeBug - 1
- StaticEngine - 2

**Comment by mrexodia** [comment]
Yeah it’s on my list of stuff to work on :)
