### ISSUE TITLE
Hide Debugger (PEB) detected by VMP

### ISSUE THREAD

**Issue by KVPV** [x64dbg/x64dbg#2467]
- Debugger version: Sep 21 2020 (GleeBug)
- Operating system: Windows 10 (1909)

I try debug programm with hidden debug (PEB), 
but this is detected. I remember the function was 
working earlier and hiding the debugger. 
But now it is being detected by VMProtect why?

**Comment by CXVUSER** [comment]
> 
> 
>     * Debugger version: Sep 21 2020 (GleeBug)
> 
>     * Operating system: Windows 10 (1909)
> 
> 
> I try debug programm with hidden debug (PEB),
> but this is detected. I remember the function was
> working earlier and hiding the debugger.
> But now it is being detected by VMProtect why?

Try ScyllaHide plugin
