### ISSUE TITLE
Debugging process with ObRegisterCallbacks and limited rights

### ISSUE THREAD

**Issue by KVPV** [x64dbg/x64dbg#2470]
- Debugger version: Sep 21 2020 (GleeBug)
- Operating system: Windows 10 (1909)

Process A: starts the service and driver to install ObRegisterCallbacks on the spawned new another process B. 

When installing ObRegisterCallbacks on process B, it strips it of all privileges. I cannot attach to process B because I have no privileges to do so.

The only thing I managed to do: execute DLL Injection into process B.

How can I debug it? Two processes have VMProtect. 
Attempts to use ScyllaHide failed and the debugger was found.

**Comment by mrexodia** [comment]
This question is out of scope for the debug engine, because you have to unregister the callbacks or patch the handle checks in another way.
