### ISSUE TITLE
Assembly code is not recognized correctly

### ISSUE THREAD

**Issue by czghzc** [x64dbg/x64dbg#2471]
The assembly code is not correctly recognized, as shown in the following figure:
OS: Win7-64bit
App: x32dbg Oct 2 2020 (TitanEngine)

![2020-10-06_095315-2](https://user-images.githubusercontent.com/23645596/95150599-1d7de200-07bb-11eb-99c0-677b9fbeb9ac.png)

**Comment by mrexodia** [comment]
Use b to mark the code as bytes.
