### ISSUE TITLE
question about assembler 

### ISSUE THREAD

**Issue by jellyr** [x64dbg/x64dbg#2491]
When I want to assemble an instruction. like 
`call qword ptr ds:[<&GetModuleFileNameW>]`
It says invalid address.
If I write call qword ptr ds:[0x00007FF788F22018], then it successes.

But I want to assemble lots of api, and I do not want to write the address directly. 
How can I directly assemble instruction like 
`call qword ptr ds:[<&GetModuleFileNameW>]`

BTW:  
I do not want to use `call GetModuleFileNameW`, because if the offset is greate than 32bit integer ,  `call GetModuleFileNameW` would not work!

**Comment by torusrxxx** [comment]
First you know that <&GetModuleFileNameW> is itself a pointer stored in application memory, and there is no way to automatically find out the address of this pointer in application memory given the name of API. You may add a label to this pointer and refer to this label instead.

**Comment by jellyr** [comment]
I think what you said makes sense.  I'll close this issue。 
Thank you for your time!
