### ISSUE TITLE
Suggestion: Remove option 'show ASCII in address dump mode'

### ISSUE THREAD

**Issue by cw2k** [x64dbg/x64dbg#2498]
... you find this in
Settings/[GUI].
[x] show ASCII in address dump mode.
(I discovered that option while updated the German translation for x86dbg.)
When enabled it'll show that extras ASCII column in CPU/Dump (within view mode 'Address' ) as showed in this example:
```
Address            Value             ASCII
0000000021B9A030  6C746E65204C4C44  DLL entl
0000000021B9A038  3030203A6E656461  aden: 00
0000000021B9A040  3436303030303030  00000064

```
Well that's a great thing. (In Ollydbg I near have the dump view all the time in that mode.)
I don't see any reason why you should disable that. 
Beside you may also accomplish the same in the 'Edit Columns' Dialog. 
(You can open that by right click at the column header in dump view)  
So my suggestion is to 
1. Enable this by default / refractor out/delete the flag to toggle it on/off
2. Remove the option "show ASCII/Unicode in address dump mode" from Settings/[GUI] as well as in the ini file
(Which seem to be redundant and so just adds useless clutter.)

**Comment by mrexodia** [comment]
Yep I agree, will change today 🙂
