### ISSUE TITLE
Wrong translation string can easily crash X64dbg

### ISSUE THREAD

**Issue by cw2k** [x64dbg/x64dbg#2499]
Here I just wanna bring up some actual crash:
That is the original string:
"Could not delete breakpoint **%p**! (DeleteBPX)\n"
And that the wrongly translated String:
"Haltepunkt **%s** konnte nicht gelöscht werden! (DeleteBPX)\n"
When this meets the vsnprintf_s function it'll produced an C0000005 (EXCEPTION_ACCESS_VIOLATION).
Notice that **%p** that somehow turned into **%s**. I'll make a value to be read as string. 
And since that value is probably pointing at some memory location that is not meant be be read it'll trigger this Access Violation.

Well I correct this specific problem now.
However that error show that two things are need:
1. Some Try-Catch-block around that tr() function (that does the translation) 
   so a problem like this would crash the whole program. 
2. some kind of validations script  when compiling language resources that will 'look for' this know problem

**Comment by mrexodia** [comment]
Yeah I think when generating the strings it should check if the order of the format strings is preserved somehow. It could also be done at startup probably, but since I don't use the translation I didn't particularly care...

**Comment by cw2k** [comment]
>... It could also be done at startup probably,..
Hmm validating all resource string on each startup? I don't think that's such a good idea.
Beside how to collect all the resource strings that are scattered all around code to validate each against the planed localisation resource file?

But what about suggestion #1. 
Put an exception handler into tr() 
in the catch part just slam out an error into the log. Maybe like this:
Log ( "Error [%x] while translating resource string.\n '%s' can't be turned into '%s',\n A known error were is that format strings where messed up during translation.") % (ExceptionCode, StringOriginal, StringTranslated) 
and we're done.

Now running X64Dbg with translation is kind da safe again.

**Comment by mrexodia** [comment]
I don't really think this is a great idea. I worked with exceptions
handlers before but in my experience it's better to let it crash in
production than introduce these kinds of hacks that hide errors in the
code :)

One idea I think might be worthwhile is to try and save the database
if x64dbg crashes for some reason. This could be done as long as the
code that handles the database isn't the issue and the data isn't
corrupted.

Unfortunately this is quite a task and fairly difficult to implement
correctly so I didn't do it for now...

**Comment by cw2k** [comment]
>I worked with exceptions handlers before but in my experience it's better to let it crash in production than introduce these kinds of hacks that hide errors in the code :) 
Catch-N-Log so the errors are not hidden.  But keep it running!
I don't see the point in it letting a minor known flaw crash the whole program just to see that beautiful windows crash screen again.

Expect the unexpected. There is no really 100% perfect code.
Adding some tactical exception handler for error containment.improves code quality.

About 
>Save the database if x64dbg crashes for some reason.
I can image that should be easily done by add a try catch in the main function. In case of a crash the exception handler just invokes 'saveDatabase'.
In case you slam in some worker threads for various tasks they  will need their own try-catch -save-the-database. However all-in-all it'll be not a big thing.

In mean in practice there are sometimes these tiny little details that make things more exciting and challenging, However that life - expect the unexpected.

**Comment by torusrxxx** [comment]
I support this idea.

**Comment by mrexodia** [comment]
I really don't think exceptions are the way to go. In the past TitanEngine had this and it was hiding problems. Instead the issue should be addressed by a processing step on the translations.

**Comment by SuperGoldHouse** [comment]
啥时候能修好C0000005断点的问题呀

**Comment by mrexodia** [comment]
This was made impossible by checking the translations before they are generated for a release: https://github.com/x64dbg/Translations/blob/master/TranslationChecker/TranslationChecker/Program.cs
