### ISSUE TITLE
X64 DBG Doesn´t open for me

### ISSUE THREAD

**Issue by Init1337** [x64dbg/x64dbg#2501]
Hello , when i open the x96dbg i tell yes to everything ,  i have admin permissions on my computer , but then nothing works , neither x32 dbg or x64 , i hope someone can help me , thx

**Comment by mrexodia** [comment]
Make sure you are not extracting x64dbg to program files and you can check
x96dbg.ini to see if the paths are set correctly.

**Comment by stefanounick** [comment]
Same problem here, latest snapshot doesn't do anything but older versions work fine

**Comment by mrexodia** [comment]
What are your system specs? Is there a minidump created?

**Comment by mrexodia** [comment]
Thanks for the report, I fixed the issue.

**Comment by stefanounick** [comment]
Can confirm, new release fixed it for me
