### ISSUE TITLE
x64dbg not loading any application on Wine 5.19

### ISSUE THREAD

**Issue by SmallJoker** [x64dbg/x64dbg#2507]
Debugger version: Nov 3 2020 (156fe7cd2) -- same result with Oct 12 2019 (random choice)
OS: Ubuntu 20.04 / Wine 5.19 (no staging)

None of the following loads an application:
 - Dragging exe into the window
 - Attaching to a process
 - Opening exe file using the file browser
 - `init "explorer.exe", ""`

I tried those variants using the x64dbg application itself, and a few other executables.

<details>
<summary>Log when dragging an executable</summary>

```
$ wine x64dbg.exe 
01f0:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
021c:fixme:msvcrt:Concurrency_wait (100) stub!
01f0:fixme:msvcrt:_Trace_agents (0 35c2960)
01f0:fixme:shell:IDropTargetHelper_fnDragEnter (0x2b25960)->(0x40022 0x7fd403f73ae8 0x21be88 0x00000001)
01f0:fixme:shell:IDropTargetHelper_fnDragOver (0x2b25960)->(0x21bea0 0x00000001)
(line repeats)
01f0:fixme:shell:IDropTargetHelper_fnDrop (0x2b25960)->(0x7fd403f73ae8 0x21c088 0x00000001)
01f0:fixme:msvcrt:_Trace_agents (4 35c29a0)
01f0:fixme:msvcrt:ThreadScheduler_ScheduleTask (0x35f5ef0 0x1d474c0 0x35c29a0) stub
```
</details>

<details>
<summary>Log when using the file browser</summary>

```
$ wine x64dbg.exe 
0168:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
017c:fixme:msvcrt:Concurrency_wait (100) stub!
0168:fixme:msvcrt:_Trace_agents (0 35c2b10)
0168:fixme:commdlg:IServiceProvider_fnQueryService Interface {e07010ec-bc17-44c0-97b0-46c7c95b9edc} requested from unknown service {e07010ec-bc17-44c0-97b0-46c7c95b9edc}
0168:fixme:shell:ViewModeToListStyle ViewMode 0 not implemented
0168:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x2b42dc0 (2, 1026, a003, 0, 0x2192b8)
0168:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x2b42dc0 (2, 1026, a004, 0, 0x2192b8)
0168:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x2b42dc0 (2, 1025, a003, 1, 0x2192b8)
0168:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x2b42dc0 (2, 1025, a004, 1, 0x2192b8)
0168:fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
0168:fixme:win:FlashWindowEx 00000000002192A0 - semi-stub
0168:fixme:win:FlashWindowEx 0000000000219640 - semi-stub
0168:fixme:msvcrt:_Trace_agents (4 35c2b50)
0168:fixme:msvcrt:ThreadScheduler_ScheduleTask (0x8bc7a0 0x1d474c0 0x35c2b50) stub
```
</details>

<details>
<summary>Log when attaching to a process</summary>

```
$ wine x64dbg.exe 
00fc:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
0034:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
0034:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
0110:fixme:msvcrt:Concurrency_wait (100) stub!
00fc:fixme:msvcrt:_Trace_agents (0 35c3240)
00fc:fixme:msvcrt:_Trace_agents (4 35c3280)
00fc:fixme:msvcrt:ThreadScheduler_ScheduleTask (0x35f6790 0x1d474c0 0x35c3280) stub
```
</details>

Processes cannot be run as Administrator in Wine, but the title mentions `x64dbg[Elevated]`

**Comment by mrexodia** [comment]
Wine is not supported.

**Comment by SmallJoker** [comment]
Too bad. I hoped there was someone familiar with this project who could have a look into a workaround - like it has been done earlier to avoid calling a stub function.

**Comment by mrexodia** [comment]
I was busy so my response was a bit short. You can rebase the wine branch
on the latest development and it will probably work. It might be possible
to integrate this into x64dbg by detecting Wine at runtime and I’ll accept
a pull request for it if you can show there won’t be any impact on Windows
users (the current code there has been working for a long time without
issues and I’d like to keep it that way).

**Comment by SmallJoker** [comment]
So far the only difference seems to be 6c3d1f2be. If it works on Wine, it's unlikely to affect Windows builds. I can give it a try, but it's been a long time since I last developed software on Windows.

**Comment by mrexodia** [comment]
Yeah but it is some concurrent queue and the Visual Studio one is working
very well. Unless there is a pressing reason to change I’d like to keep it
this way.

**Comment by mrexodia** [comment]
I’ve looked at implementing the missing API for Wine and likely it’s not
that hard to do, but I don’t use Wine so it’s not really worth doing for me
right now.
