### ISSUE TITLE
the symload / loadsym command does nothing

### ISSUE THREAD

**Issue by joseph-giron** [x64dbg/x64dbg#2508]
I see this command (symload)  in the documentation https://help.x64dbg.com/en/latest/commands/analysis/symload.html however running the command at the bottom does jack crap. It always says the same thing - at least 2 arguments must be specified. I could supply a thousand arguments and it still wouldn't be happy. 
![image](https://user-images.githubusercontent.com/1933739/98177461-ec76f700-1eb7-11eb-8cf2-a3113afb62ea.png)
What gives?

**Comment by mrexodia** [comment]
As specified in the manual, commands are comma separated. I am working on
allowing you to switch to the same structure as windbg but some help there
would be appreciated.

**Comment by joseph-giron** [comment]
Crap. Well next time I'll RTFM. Sorry.
