### ISSUE TITLE
How can I print the comment from specific address using command line?

### ISSUE THREAD

**Issue by jyoonab** [x64dbg/x64dbg#2510]
By using command line, I wish to print the comment(I assume this is correct term) from a specific address,
but I have had no chance find the correct command for doing this.

![tempsnip](https://user-images.githubusercontent.com/37427419/98810285-5700d780-2462-11eb-8052-f402ee6388ef.png)

I have tried to use some commands(such as commentlist etc...) but not able to find the solution.

May I ask if there is any correct command line which will show the comment?

Thanks

**Comment by mrexodia** [comment]
These are so-called autocomments which are based on the registers and
memory. If you want to find the strings you can just use the search strings
button.

**Comment by jyoonab** [comment]
Thanks for prompt reply and letting me know the term = ] 
I am trying to print the autocomments by using the log function like (log "{autocomments@address}").
Is there any way I can do this?
I know I can print the disassembly info by using disasm@dis.sel().

**Comment by tamersaeed** [comment]
Write echo

**Comment by mrfearless** [comment]
There is also a manual process - you can also press ";" (semi-colon) to edit the comment - then select it and copy to clipboard

**Comment by mrexodia** [comment]
You can write a plugin that does this for you. Here is an example of `{timestamp@0}`: https://github.com/mrexodia/TimeStampFormat/blob/master/TimeStampFormat/plugin.cpp

**Comment by takhyun12** [comment]
The purpose of the question is to ask if he can get value through String Formating Method (e.g. {mem;size@address}).

**Comment by mrexodia** [comment]
Im well aware, that’s why I gave an example plugin that allows you to
create your own format functions. There you can call DbgGetCommentAt to get
the comment you want (or return any value).

**Comment by jyoonab** [comment]
@mrexodia Thanks for letting me know. It seems I need to dig into the DbgGetCommentAt function first, and do what you suggested. Let me close this thread = ]

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/blob/d422af7dd49074094bce6b92d1590bd9cb14793f/src/gui/Src/Gui/CPUDisassembly.cpp#L796-L803
