### ISSUE TITLE
 when I save the .exe file it doesn't save and the program closes

### ISSUE THREAD

**Issue by Dojassola** [x64dbg/x64dbg#2511]
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes
when I save the .exe file it doesn't save and the program closes

**Comment by mrexodia** [comment]
Check the issues before you open a new one.

**Comment by Dojassola** [comment]
I already solved it and even then I'll put the patches in the .exe file and
it doesn't work

Em qua, 11 de nov de 2020 19:28, Duncan Ogilvie <notifications@github.com>
escreveu:
