### ISSUE TITLE
Hi there, does x64dbg support instruction replacement already?

### ISSUE THREAD

**Issue by DK-DARKmatter** [x64dbg/x64dbg#2512]
Sorry if this question has been asked by anyone, but I cannot find anything about this.
I mean, 
can we just replace instruction directly like:
 "mov eax ,xxx" ----before
to
"mov al, 0h" ---- after

I know we have hex edit now. But it gonna be very hard for someone to transfer the command to the corresponding hex code directly without any help. I mean, I just cannot transfer "mov al, 0h" to the corresponding hex code without any help.
So I'm wondering if we could have a easier way to replace the instructions. Like we give it "mov al , 0h" as a string, x64dbg could change this string into the corresponding hex code and replace the original hex.

Thanks in advance.

**Comment by mrexodia** [comment]
Check the manual, there is an assemble command.
