### ISSUE TITLE
Copy/paste binary data in Base64 format

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2516]

**Comment by mudlord** [comment]
Could be done as a plugin?

**Comment by thundercoder123** [comment]
@mrexodia 
Can I take up this issue?
Also this is my first open source contribution.I will be needing a bit of guidance.
Please guide me through the process and the requirements for this issue.
Thank you in advance!

**Comment by ZehMatt** [comment]
This is better off with a plugin tbh

**Comment by thundercoder123** [comment]
> @mrexodia 
> Can I take up this issue?
> Also this is my first open source contribution.I will be needing a bit of guidance.
> Please guide me through the process and the requirements for this issue.
> Thank you in advance!

\attempt

**Comment by mrexodia** [comment]
Unfortunately I don’t have a lot of time for guiding. This feature is probably more something for a plugin to implement as mentioned twice before.
