### ISSUE TITLE
x64Dbg not recognizing code in new section

### ISSUE THREAD

**Issue by JulianGlez** [x64dbg/x64dbg#2522]
I'm using Windows 10 64bits and x64Dbg in the Nov 12 2020 TitanEngine version.

I'm trying to create a simple trojan manually, first of all I created a new executable section at calc.exe (this is the .exe I'm using to hide the trojan) called "troyano". Then I edited its content with a payload created with metasploit (shell_reverse_tcp).

To call the new section from the original code I opened the edited calc.exe with x64Dbg but this is the only thing I see in my new section: 

![image](https://user-images.githubusercontent.com/74913560/99967582-5e947a80-2d98-11eb-952c-21bfbf787eb9.png)

Neither of the inserted code to the new section is shown and I don't know exactly why.

Thank you.

**Comment by mrexodia** [comment]
It’s because the code doesn’t exist in the memory. The debugger just shows what Windows reports being in the memory.

**Comment by JulianGlez** [comment]
So how can I access and modify that section?

If this is a very stupid question just tell me, if you can, where can I learn more.

**Comment by mrexodia** [comment]
This is an issue tracker for x64dbg, not a forum to ask for help.
