### ISSUE TITLE
对话框里面的字体太小

### ISSUE THREAD

**Issue by jiangwenfan** [x64dbg/x64dbg#2524]
默认每个窗口的字体都太小了，我设置了每个窗口显示的字体大小，但是当我在反汇编窗口中修改汇编指令时，发现弹出的这个对话框太小了，以至于输入的汇编指令都小的难以辨认，不知道该如何解决。

**Comment by b917893200** [comment]
换大点的屏幕，你打中文他也不一定看得懂啊

**Comment by mrexodia** [comment]
You can change the font in the settings.

**Comment by torusrxxx** [comment]
When the assemble dialog is opened the height of input box is not adjusted to the font size (BUG).

**Comment by jiangwenfan** [comment]
> When the assemble dialog is opened the height of input box is not adjusted to the font size (BUG).

非常感谢你的解答，这个修复版的程序已经完美解决了这个问题。
