### ISSUE TITLE
Hello there, does x64dbg support to getting stack value in bridgemain.cpp?

### ISSUE THREAD

**Issue by takhyun12** [x64dbg/x64dbg#2529]
First of all, thank you for making such a nice project.

I have code(in bridgemain.cpp) to get address value and disAsssembly value based on "cip". 

and I'm trying to get the stack values (shown in the picture) in the "bridgemain.cpp" code.

Does x64dbg support getting that value from Bridgemain.cpp?

Please give me some advice.

![1](https://user-images.githubusercontent.com/41291493/100574939-6d41db00-331e-11eb-9621-d329ac3ef13f.PNG)

**Comment by morsisko** [comment]
Can't you just read it using the esp register? For example `DbgEval("[esp+4]");` or directly from the debugee memory

**Comment by torusrxxx** [comment]
You can use `DbgEval("arg.get(0)");`. In general you should look at commands, expressions and string formatting as well as exported functions, many features are exported via commands, expressions and string formatting only, but no exported functions (This is due to interface stability).
