### ISSUE TITLE
what is the difference between bookmarks, label, and comment

### ISSUE THREAD

**Issue by wkingnet** [x64dbg/x64dbg#2534]
sorry, I am a newcomer. I read the help manual but there is no answer for me. So what is the difference between bookmarks, label, and comment ? I feel that their functions are very similar, especially label and comment. Thanks!

**Comment by mrexodia** [comment]
Yes, their implementation is also 99% shared. The main difference is in
where they are displayed:

1. Label: displayed when you call or jmp somewhere (or when a register
contains a label it’s also shown)
2. Comment: only displayed next to an instruction in the disassembly
3. Bookmark: just a quick way to remember a location, also only displayed
as a highlight on an address.
