### ISSUE TITLE
Debugging not loaded when running with Wine under Ubuntu

### ISSUE THREAD

**Issue by namviet3210** [x64dbg/x64dbg#2535]
Hi there,

I have just downloaded the latest release (snapshot_2020-12-01_16-29.zip) and try it with wine under Ubuntu 20 (64 bit).
However, debugging was not loading, the main tab (CPU) shows blank. It seems nothing happens when I try to open any .exe file.
In the Log tab, the message after application initiated is shown as below, there is no update on this tab when I try to open any .exe file.
Please advice how to resolve the problem.

Thank you,
nv
************Log tab************
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing Zydis...
Getting directory information...
Start file read thread...
Retrieving syscall indices...
Symbol Path: C:\Program Files (x86)\x64dbg\release\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Invalid relocation block for module ntdll.dll!
Syscall indices loaded!
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
Handling command line...
  "C:\Program Files (x86)\x64dbg\release\x64\x64dbg.exe"
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!

![x64dbg_ubuntu](https://user-images.githubusercontent.com/9313006/101104800-41e41800-35cc-11eb-8341-38cdd58ed91e.JPG)

**Comment by rmi1974** [comment]
Hello!

That's a known issue:

https://bugs.winehq.org/show_bug.cgi?id=45916 ("x64dbg fails to load debuggee, needs ThreadScheduler_ScheduleTask")

You have to add native overrides for the VC++ runtime.
Here is a registry snippet I use for every WINEPREFIX I want to debug apps/games with x64dbg:

`x64dbg.reg`

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Wine\AppDefaults]

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\x32dbg.exe]

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\x32dbg.exe\DllOverrides]
"dbghelp"="native,builtin"
"msvcp120"="native,builtin"
"msvcr120"="native,builtin"

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\x64dbg.exe]

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\x64dbg.exe\DllOverrides]
"dbghelp"="native,builtin"
"msvcp120"="native,builtin"
"msvcr120"="native,builtin"
``` 

Run it once in each WINEPREFIX before starting debugging

```
wine regedit x64dbg.reg
```

It uses per-application overrides so the `debuggee` (app/game) can still use Wine's builtin VC++ runtime implementation.
Additionally `dbghelp` is set to native as well for better debugging experience (Wine's builtin has several symbol processing deficiencies) 

In general please search WineHQ Bugzilla first.
Few issues have been documented by me or others.

https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=STAGED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=RESOLVED&list_id=718242&product=Wine&query_format=advanced&short_desc=x64dbg&short_desc_type=allwordssubstr

Regards

**Comment by namviet3210** [comment]
Hi @rmi1974 ,

Thank you for the detail instruction.
Follow your guidance, I have been able to run the program correctly.

This issue is now closed!
Regards,
nv

**Comment by janisozaur** [comment]
The bug filed with wine got closed with most recent release of wine, version 7.7 and loading a PE works fine without any additional setup.

**Comment by mrexodia** [comment]
Great news, thanks for the info!

**Comment by ZehMatt** [comment]
> The bug filed with wine got closed with most recent release of wine, version 7.7 and loading a PE works fine without any additional setup.

Fancy seeing you here :)
