### ISSUE TITLE
remember changed command line

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#254]
Instead of using Change command line every single run, would be nice to remember the modified command line for automatic reuse next times...

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/254
- Originally reported by: Anonymous
- Originally created at: 2015-02-12T14:52:37.832

**Comment by mrfearless** [comment]
I wrote a little plugin that remembers the command line, and auto sets it when loading the same module: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-masm/downloads/AutoCmdLine-Plugin.zip - its a work in progress, so might have a few bugs or other issues ive not anticipated.

**Comment by mrfearless** [comment]
Updated plugin - now found in my bitbucket repository along with another api search: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-masm/downloads

**Comment by mrexodia** [comment]
didn't Herz3h's fixed solve this issue?
