### ISSUE TITLE
ucrtbase.pdb missing and not downloadable from Microsoft

### ISSUE THREAD

**Issue by adamsstephen** [x64dbg/x64dbg#2542]
I have downloaded the latest version of x64dbg and using the x32 version as a newbie. to look at a driver file I want to update to x64 working. But the symbols database is not available in the package or from Microsoft, who now state it must be download from within the application!
Where is there an initial version to work with this debugger?
Do I need it, what advantages does it give me?

**Comment by mrexodia** [comment]
I don’t really understand the question. If you want to download a PDB from Microsoft you can go to the symbols tab, right click on the module, download symbols for this module.

**Comment by adamsstephen** [comment]
I could not find this in the documentation and I still get this error fro ucrtbase.pdb
"Downloading symbol ucrtbase.pdb
  Signature: B6AC828B65092A857EB84274407C36A81
  Destination: C:\Users\stephen\Downloads\snapshot_2020-12-01_16-29\release\x32\symbols\ucrtbase.pdb\B6AC828B65092A857EB84274407C36A81\ucrtbase.pdb
  URL: https://msdl.microsoft.com/download/symbols/ucrtbase.pdb/B6AC828B65092A857EB84274407C36A81/ucrtbase.pdb
Failed to create destination file (ERROR_PATH_NOT_FOUND)..."

**Comment by mrexodia** [comment]
That means there is no PDB available publicly for (that version of) that
DLL.

**Comment by fahadashiq12** [comment]
I have same issue in my project as well.

**Comment by mrexodia** [comment]
> I have same issue in my project as well.

Report it to Microsoft.
