### ISSUE TITLE
snapshot 2020-12-15_20-57 and later broke x32dbg for Windows versions < Windows 7 (PSAPI_VERSION 1 vs. 2)

### ISSUE THREAD

**Issue by rmi1974** [x64dbg/x64dbg#2545]
Hello folks,

I didn't see an announcement that x64dbg project dropped support for Windows versions < Windows 7 (XP, Vista) hence this bug report.

Starting x32dbg from snapshot 2020-12-15_20-57 and later on Windows XP, Vista immediately aborts with dreaded message box (and crash afterwards):

```
The procedure entry point K32GetProcessImageFileNameW could not be located in the dynamic link library KERNEL32.dll
```

https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getprocessimagefilenamea

```
Starting with Windows 7 and Windows Server 2008 R2, Psapi.h establishes version numbers for the PSAPI functions.
The PSAPI version number affects the name used to call the function and the library that a program must load.

If PSAPI_VERSION is 2 or greater, this function is defined as K32GetProcessImageFileName in Psapi.h and exported
in Kernel32.lib and Kernel32.dll. If PSAPI_VERSION is 1, this function is defined as GetProcessImageFileName
in Psapi.h and exported in Psapi.lib and Psapi.dll as a wrapper that calls K32GetProcessImageFileName.

Programs that must run on earlier versions of Windows as well as Windows 7 and later versions should always
call this function as GetProcessImageFileName. To ensure correct resolution of symbols, add Psapi.lib to the
TARGETLIBS macro and compile the program with -DPSAPI_VERSION=1.
To use run-time dynamic linking, load Psapi.dll.
```

From my investigation I deduced that starting with 2020-12-15_20-57 snapshot (contains TitanEngine dll update) the project including subprojects (TitanEngine) was built with a newer MS Visual Studio 2013 which uses *PSAPI_VERSION=2* by default.

I found a hint in one of the commits which suggests this:

https://github.com/x64dbg/x64dbg/commit/24a3d2af27cbb0c2ff6de2502b2d93a66f9cf2a0 -> "Fix compilation on VS2013"

----

Additionally I performed an executable analysis (detect compiler versions via magics/heuristics) using virustotal:

*Older working snapshot_2020-12-14_15-31.zip*

https://www.virustotal.com/gui/file/967c1dcc4cc25632c35b02916f49e953d88847b4e211cd8c75c5744b5b34b128/details

```
Creation Time 2020-11-12 03:54:39
Signature Date 2020-11-12 03:55:00
First Seen In The Wild 2020-12-01 12:28:14
First Submission 2020-11-23 15:06:08
Last Submission 2020-11-23 15:06:08
Last Analysis 2020-11-24 01:51:56

[ASM] VS2010 build 30319 count=22
[ C ] VS2010 build 30319 count=113
[---] Unmarked objects (old) count=3
[C++] VS2010 build 30319 count=49
[IMP] VS2008 SP1 build 30729 count=14
[ C ] VS2010 SP1 build 40219 count=9
id: 257, version: 25019 count=3
[---] Unmarked objects count=211
id: 175, version: 30319 count=74
[EXP] VS2010 build 30319 count=1
[RES] VS2010 build 30319 count=1
[LNK] VS2010 build 30319 count=1
```

Ok, VS2010.

*Non-working snapshot_2020-12-15_20-57.zip*

https://www.virustotal.com/gui/file/8e02263f7461d770af1207dc2aa8b707775e2982c5f9c6ed8b84024439dfe315/detection

```
Creation Time 2020-12-15 17:35:23
Signature Date 2020-12-15 17:36:00
First Submission 2020-12-16 20:39:24
Last Submission 2020-12-16 20:39:24
Last Analysis 2020-12-16 20:39:24

id: 259, version: 27412 count=10
id: 261, version: 27412 count=146
id: 260, version: 27412 count=18
id: 260, version: 29118 count=17
id: 259, version: 29118 count=21
id: 261, version: 29118 count=34
id: 257, version: 27412 count=14
[ C ] VS2010 SP1 build 40219 count=9
id: 257, version: 25019 count=3
[---] Unmarked objects count=220
id: 265, version: 29335 count=74
id: 256, version: 29335 count=1
id: 255, version: 29335 count=1
id: 151, version: 0 count=1
id: 258, version: 29335 count=1
```

These unnamed IDs most likely refer to VS 2013.

----

Additionally I did a trace log with Wine to show loader/imports resolver:

```
...
0194:trace:module:load_dll looking for L"PSAPI.DLL" in L"Z:\\home\\focht\\wine-apps\\x64dbg\\release\\x32;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0"
0194:trace:module:load_dll Found L"C:\\windows\\system32\\PSAPI.DLL" for L"PSAPI.DLL" at 02000000, count=2
0194:trace:imports:import_dll --- GetModuleFileNameExA PSAPI.DLL.15 = 02001494
0194:trace:imports:import_dll --- GetProcessImageFileNameW PSAPI.DLL.20 = 020014F8
0194:trace:imports:import_dll --- GetModuleFileNameExW PSAPI.DLL.16 = 020014A8
0194:trace:imports:import_dll --- EnumProcesses PSAPI.DLL.6 = 020013E0
0194:trace:imports:import_dll --- GetMappedFileNameW PSAPI.DLL.12 = 02001458
0194:trace:imports:import_dll --- GetModuleBaseNameA PSAPI.DLL.13 = 0200146C
0194:trace:imports:import_dll --- GetModuleInformation PSAPI.DLL.17 = 020014BC
0194:trace:imports:import_dll --- EnumProcessModules PSAPI.DLL.4 = 020013B8 
...
0194:trace:module:load_dll looking for L"KERNEL32.dll" in L"Z:\\home\\focht\\wine-apps\\x64dbg\\release\\x32;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0"
0194:trace:module:load_dll Found L"C:\\windows\\system32\\kernel32.dll" for L"KERNEL32.dll" at 7B600000, count=-1
0194:trace:imports:import_dll --- SetConsoleCtrlHandler KERNEL32.dll.1258 = 7B60D37C 
...
0194:trace:imports:import_dll --- K32GetProcessImageFileNameW KERNEL32.dll.938 = 7B60C738
0194:trace:imports:import_dll --- K32GetModuleFileNameExW KERNEL32.dll.934 = 7B60C6E8
```

`TitanEngine.dll` does actually both: importing "old" PSAPI v1 style with `PSAPI.DLL.GetProcessImageFileNameW` and "new" PSAPI v2 style with `KERNEL32.DLL.K32GetProcessImageFileName` which seems weird.

----

If this breakage was unintentional I propose to set `PSAPI_VERSION` to `1` in `PreprocessorDefinitions` section for all projects or at least the projects that use PSAPI (TitanEngine):

https://github.com/x64dbg/TitanEngine/blob/x64dbg/TitanEngine/TitanEngine.vcxproj#L90

Alternatively you could define it in top-level include file:

https://github.com/x64dbg/TitanEngine/blob/x64dbg/TitanEngine/stdafx.h#L9

```
#define PSAPI_VERSION 1
```

and rebuild everything.

Regards

**Comment by mrexodia** [comment]
I compiled TitanEngine locally on my machine with Visual Studio 2019, thanks for the report!

**Comment by rmi1974** [comment]
```
To fix this you can compile it with VS2010 and replace TitanEngine.dll.
```

Well, i don't need an immediate fix. I'm using older snapshots anyway due to https://github.com/x64dbg/x64dbg/issues/2525 (Linux/Wine is my main debug environment).

With the proper PSAPI_VERSION=1 setting and rebuilding everything with VS 2019 the issue should be gone. I guess you will do that for one of the next snapshots anyway ;-)

**Comment by LordGarfio** [comment]
Hello Mr exodia,

Have you officially dropped support for Windows XP and Windows 7 support ?

**Comment by mrexodia** [comment]
See my answer above. I will fix this eventually, but it requires a
TitanEngine update.

**Comment by rmi1974** [comment]
Hello folks,

since this is now a **WONTFIX**, here are the download links to the last working snapshot via Internet Archive (archive.org):

https://web.archive.org/web/20220920065431/https://master.dl.sourceforge.net/project/x64dbg/snapshots/snapshot_2020-12-14_15-31.zip?viasf=1

https://web.archive.org/web/20220920065353/https://master.dl.sourceforge.net/project/x64dbg/snapshots/snapshot_2020-12-14_15-31-pdb.zip?viasf=1

```console 
$ sha1sum snapshot_2020-12-14_15-31*

ec9a9a9cc7bc15a86a068463c3938bfa2d5cc33c  snapshot_2020-12-14_15-31-pdb.zip
00565b738d3064e07c106cd84ed15a7d394b5075  snapshot_2020-12-14_15-31.zip
``` 

The old working version is useful for people who need/want to reproduce / research / analyze software behavior with old Windows versions.

Regards

**Comment by mrexodia** [comment]
It can be fixed, just put in some effort. Regardless, all versions ever released are at https://osdn.net/projects/x64dbg/ and https://sourceforge.net/projects/x64dbg/
