### ISSUE TITLE
patches for dll cannot be saved

### ISSUE THREAD

**Issue by wxmeng04** [x64dbg/x64dbg#2546]
The patches for dll file is not successfully saved. see below picture.
![11](https://user-images.githubusercontent.com/26078750/102715382-83740300-42ee-11eb-91d9-a20747453b6c.jpg)

**Comment by morsisko** [comment]
This might be the case: https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions (Q: Why are not all my patches being applied)

**Comment by wxmeng04** [comment]
> This might be the case: https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions (Q: Why are not all my patches being applied)

How can I solve the problem?

**Comment by mrexodia** [comment]
Don't patch in locations that are not in the file.
