### ISSUE TITLE
What is wrong for breakpoint flow?

### ISSUE THREAD

**Issue by spobit** [x64dbg/x64dbg#2547]
- Debugger version (can be found on right hand side of menu bar of debugger).
  12/16/2020
- Operating system version and Service Pack (including 32 or 64 bits).
  win10 x64
- Brief description of the issue.
I just maked two breakpoint is x64dbg, see img1 img2. But the breakpoint is breaked two times, what happen.

![image](https://user-images.githubusercontent.com/25954976/102716341-428fe480-4316-11eb-8b8a-32563fe2b5a6.png)
![image](https://user-images.githubusercontent.com/25954976/102716373-7b2fbe00-4316-11eb-801d-dd9e8f0facf4.png)
![image](https://user-images.githubusercontent.com/25954976/102716376-808d0880-4316-11eb-8b28-808d806f2dae.png)

**Comment by mrexodia** [comment]
This is not related to x64dbg, but to your application.
