### ISSUE TITLE
Crash when refreshing handles

### ISSUE THREAD

**Issue by win9z** [x64dbg/x64dbg#2549]
- Debugger version: Dec 16 2020
- Operating system: Windows 10 x64 version 1607
- Description:
x32dbg crashes after pressing "refresh" in handles tab while execution is running. Tested without plugins.
Steps to reproduce:
Open x32dbg, attach to any application, open "Handles" tab and press F5 or RMB->Refresh

![изображение](https://user-images.githubusercontent.com/43905618/102720067-01daa000-4303-11eb-92cc-e7a23270fd78.png)
![изображение](https://user-images.githubusercontent.com/43905618/102720097-40705a80-4303-11eb-8bf6-5f1253df1e12.png)

**Comment by secretpwner** [comment]
same problem

**Comment by mrexodia** [comment]
Can you give more details? Which application did you debug or does it
happen with all?

Also try changing to English to rule out any possible translation errors.

**Comment by torusrxxx** [comment]
This has been fixed in 9fe6a9c164a15a0f2ded0915c0d9ddf024bcfe83. Can you confirm that?

**Comment by win9z** [comment]
yes, the issue is solved
