### ISSUE TITLE
Feature Request: Allow patches to be applied even to dlls that haven't been loaded

### ISSUE THREAD

**Issue by fearedbliss** [x64dbg/x64dbg#2550]
Hello, I've been using X32DBG specifically for many years and it's great. I used to use OllyDBG back in the day so I'm happy there has been advancements in modern reverse engineering utilities. Keep up the good work.

My request primarily (After researching I haven't found this feature to be available), is to allow patch files that apply after I had export them, to re-apply those same patches even if those dlls haven't been loading in memory. Or at least, allow those patch entries to be listed in the patches window as well.

My use case for this is that there are game modifications I've made primarily to the rendering engine that the game uses. The game allows for different rendering engines such as Glide (3dfx) or DirectDraw, thus there would only be either the "Glide.dll" loaded or the "DirectDraw.dll" loaded at any given time, however my modifications are applied across both. This leads me to having to be careful about when I export the patches, and manually stitch together the missing pieces into a single file (for ease of loading). I suppose the workaround for this would be for me to manually unselect each of the changes for each file, and export them into separate files themselves, and then manually load each patch file one by one. However, since I have my own separate documentation, and this same set of patches are also being retroactively applied to many different versions of this game, this list of patches would quickly become unmaintainable.

If there could either be a default behavior for this or a checkbox in the configuration that allows this type of behavior, it would be greatly appreciated.

Thank you!

**Comment by mrexodia** [comment]
Try the AutoExportPatches plugin. If that’s not enough for your use case
you can see if you can customize the plugin to suit your needs.

**Comment by fearedbliss** [comment]
Hey @mrexodia, thank you for the recommendation. I’ll look into it. Closing this issue.
