### ISSUE TITLE
Execute till user code

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#256]
It would be great to have "Execute till user code" (like "Olly"). Is it possible?
Thank you!

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/256
- Originally reported by: Anonymous
- Originally created at: 2015-02-22T10:52:30.685

**Comment by shinmai** [comment]
Is this a duplicate of #80 or did I misunderstand the title?
