### ISSUE TITLE
Regression: No keyboard hotkey to return from graph to disasm

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#2561]
It was possible with Shift+Enter. Not sure if the hotkey was removed (why?) or became broken.
Ideally, it would be just 'G' to both enter and leave graph view.
See also discussion here:
https://github.com/x64dbg/x64dbg/pull/2403

**Comment by gmastergreatee** [comment]
__Alt+C__ still works but that doesn't go to the selected line in graph

**Comment by gmastergreatee** [comment]
__G__ works in the current snapshot __snapshot_2020-12-29_21-30__

**Comment by justanotheranonymoususer** [comment]
Indeed, seems to be working now, thanks.
