### ISSUE TITLE
MMX,XMM,YMM show as little endian

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#257]
MMX, XMM and YMM show as little endian.
Or allow schwitch so.
x86 is little endian cpu!

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/257
- Originally reported by: [nairam_sk](http://bitbucket.org/nairam_sk)
- Originally created at: 2015-03-05T23:07:38.140

**Comment by lupier** [comment]
FPU show data in non useful scientific notation format.
For example: ollydbg show st0 as valid value 7587892.0
http://gyazo.com/2d7082b3ffe5e36731d7f3f026bd8442
But x64dbg show same as 
http://gyazo.com/0f4d19fe3b203f9c6ebeaff0397ba4a2
Sometimes I do some calculation in mind and such scientific notation wasn't useful.

**Comment by mrexodia** [comment]
right, might be possible to add an option for that.

**Comment by lupier** [comment]
Any progress?
There are still exists bug in float\double view for latest snapshot. For example let's place value 998782.7467170957 in memory. (03 B4 51 7E FD 7A 2E 41 in hex)
In double view I've just see int part 998782 (truncation? round? anyway, this is big error)

**Comment by mrexodia** [comment]
The precision error should be fixed now. However with more precision you
get stuff like -2 showing as 6.375869374756050483e-256 so there are still
things to solve
