### ISSUE TITLE
x32dbg unable to load a PDB 2.0 file

### ISSUE THREAD

**Issue by sunbeam906** [x64dbg/x64dbg#2574]
When loading TRAOD.exe in x32dbg it's as if it doesn't even see the adjacent TRAOD.pdb file:

![alt text](https://i.imgur.com/jLmsW5m.png)

Loaded the same exe file in both x32dbg and OllyDbg 1.10, showing the same location in both:

![alt text](https://i.imgur.com/j9Cvcy6.png)

You can see there are no symbols shown in x32dbg, while OllyDbg does show them.

I've checked that the .exe and .pdb match with ChkMatch tool:

![alt text](https://i.imgur.com/gXq2AcA.png.)

Tried as well with the latest snapshot (snapshot_2021-01-08_02-43.zip) and the same result. So this is something that probably hasn't been reported yet.

Link to files for testing: https://download1077.mediafire.com/1s7h7tcek2ng/i8ltb9wqnujoo61/TRAOD.zip.

BR,
Sun

**Comment by mrfearless** [comment]
Tried the files and can confirm that it doesnt even show in the symbol log that it tried to load or corresponding pdb file. Just appears to skip it/ignore it. CFF Explorer does show `codeview` for `Type` in debug directory, but `Invalid` for `AddressOfRawData`

**Comment by Mattiwatti** [comment]
This is due to the file having a 0 `AddressOfRawData` RVA in its debug directory, but a valid offset in `PointerToRawData`. This should be pretty easy to fix, I'll make a PR for this soon.
