### ISSUE TITLE
[feature request] Improvements to 'exceptions' tab

### ISSUE THREAD

**Issue by Mattiwatti** [x64dbg/x64dbg#2582]
The current 'exceptions' tab in x64dbg is pretty bare. An exception is either ignored (if it's on the list), or it is not. Exceptions on this list are always passed to the debuggee, i.e. the same as if you pressed F9 or Shift+F9. What I'd like to see in x64dbg is more control over what happens when certain exceptions happen.

Using WinDdbg as an example:
![image](https://user-images.githubusercontent.com/3313892/105696790-0dbe1100-5f04-11eb-8c57-591ef9a730d2.png)
I think the options under 'execution' for WinDbg are confusingly named, so I wouldn't want an exact replica of this, but other than that this window gives much more control over what happens:
- We can choose between break on first chance ('enabled'), break on second chance ('disabled'), only log ('output') or do nothing at all ('ignored').
- We can choose between `gh` ('continue handled', same as x64dbg's 'run, swallow exception'/Ctrl+Alt+Shift+F9) or `gn` ('continue not handled', same as x64dbg's 'run'/F9 or 'run, pass exception'/Shift+F9).
- There is a predefined 'unknown exceptions' catch-all which allows us to control what happens when WinDbg encounters _any_ exception (other than the ones already in the list).

I feel like the 'output' radio button in WinDbg should be made a checkbox instead, because this is orthogonal to the other options under 'execution'. This would also fix #2121 by making it possible to have totally silent exceptions.

This is a quick mockup based on WinDbg of more or less what I'd like to see in x64dbg:
![image](https://user-images.githubusercontent.com/3313892/105700342-077e6380-5f09-11eb-9259-cbe64c4d5071.png)

Because we already have `exceptiondb.txt` containing the names of known exceptions, adding human readable names similar to this would be a nice bonus. Currently I have quite a few exceptions on my x64dbg ignore list of which I can't remember what they are or why I added them.

**Comment by mrexodia** [comment]
I think this is a really good idea! Implementation-wise it would have to be
some kind of global exception breakpoints probably.
