### ISSUE TITLE
Cannot Debug library .dp64

### ISSUE THREAD

**Issue by AbedKarmi** [x64dbg/x64dbg#2583]
Before submitting an issue, make sure it has not already been reported.

Then, make sure the following points are included in your issue:

- Debugger version (can be found on right hand side of menu bar of debugger).
- Jan 14,2021

- Operating system version and Service Pack (including 32 or 64 bits).
- Windows 10  19042.746 x64

- Brief description of the issue.
- Cannot load library (x6dbg plugin) for debugging, it immediately quits.

- Elaborate reproduction steps for the bug/issue being reported.
just try to load it in the debugger

[http://www.mediafire.com/file/5bqipzgizi3121l/MyLibrary.dp64/file](url)

..
Worked after I moved it to the root directory (F:\) , and deleted the related database file !

It does not work inside any folder .

**Comment by mrexodia** [comment]
Not enough information to reproduce.
