### ISSUE TITLE
[feature request] Alternative algorithm for disassembly

### ISSUE THREAD

**Issue by ituy** [x64dbg/x64dbg#2585]
Issue:
- Unable to read obfuscated bytecode (when opcodes are placed between junk bytes).

Suggestion:
- Keep existing disassembly algorithm for reading large files.
- Implement a seperate algorithm, designed for reading obfuscated code.
- Let user be able to manually switch between algorithms.

If disapproved:
- Are there any other debuggers for handling obfuscated code? Such that do not require manual editing of the code.

Related posts:
- #2581

**Comment by mrexodia** [comment]
Duplicate
