### ISSUE TITLE
Automating a simple task

### ISSUE THREAD

**Issue by Antiever** [x64dbg/x64dbg#2591]
There is a common task - find the file decryption procedure.
The process is quite obvious

1. **Conditional Breakpoint** on `CreateFile`:
   - filter `lpFileName` by substring `".ext"` _(we need it because there is a huge number of files)_
   - when triggered, remember the handle (`hFile`)

2. **Conditional Breakpoint** on `ReadFile`
   - filter by handle
   - when triggered, remember the buffer address (`lpBuffer`)

3. **Breakpoint** for reading memory at `lpBuffer`

The problem is in the first step (**Conditional Breakpoint** when finding a substring).
Debugger does not know how to do it "out of the box"
It seems like there are plugins, (not all of them will work with the latest x64dbg btw) but how to use them correctly to solve such a problem is not clear.

Is it possible to completely automate all steps with x64dbg?
If not, then at least give an example of how to implement a substring match conditional breakpoint.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/148145830-78b4f69b-64b3-43ec-9233-f2338ed3866d.png)

This has been implemented in #2430
