### ISSUE TITLE
A part of conditional expression is always true

### ISSUE THREAD

**Issue by thehlopster** [x64dbg/x64dbg#2593]
https://github.com/x64dbg/x64dbg/blob/b7e50aa3a2fc6017139fc61ce47b56bc1c4e860b/src/dbg/TraceRecord.cpp#L203-L205
https://github.com/x64dbg/x64dbg/blob/b7e50aa3a2fc6017139fc61ce47b56bc1c4e860b/src/dbg/TraceRecord.cpp#L236

Since `*memorySize` is `unsigned char` value range of [0, 255] is always lower than 512, so this check is unnecessary and can be removed

**Comment by mrexodia** [comment]
Perhaps with the current disassembler this is the case, but if I recall correctly some instructions (fxsave and similar) could have big memory sizes so it's safer to keep in my opinion.
