### ISSUE TITLE
Settings revert to defaults after saving

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [x64dbg/x64dbg#2600]
Version:  Feb 15 2021
OS:  Windows 10 Pro 64-bit
Description:  Upon saving settings and closing the Preferences menu, settings automatically revert back to their defaults.
Steps to reproduce:
- Open x64dbg
- Open Preferences
- Click on Exceptions tab
- Set any settings you like
- Click Save
- Open Preferences again
- Click on Exceptions tab again
- The settings will revert to their default settings

A short video clip of the issue:

https://user-images.githubusercontent.com/58268914/108569426-ddd31500-72d9-11eb-8e4e-3b39071f249e.mp4

**Comment by htala** [comment]
I have the same issue!

**Comment by ArmanScience** [comment]
same here!

**Comment by arybin-cn** [comment]
Same here

**Comment by mrexodia** [comment]
Works fine now.
