### ISSUE TITLE
Wrong ASCII strings are detected

### ISSUE THREAD

**Issue by helperman** [x64dbg/x64dbg#2602]
x32dbg can't detect ASCII strings correctly.
OllyDebug can do that easily.

![00000564](https://user-images.githubusercontent.com/8351863/108698432-2f1b1880-7515-11eb-85ac-1b89348029e2.png)

- Debugger version: snapshot_2021-02-15-22-35

[HxD.zip](https://github.com/x64dbg/x64dbg/files/6021421/HxD.zip)

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/148144004-3150654e-7c0c-4ed9-b42f-e3eeac50238b.png)

Looks fine to me with the latest version.
