### ISSUE TITLE
List certain NVIDIA DLLs as system DLL

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2608]
Every process I debug have these DLLs. Even though I unticked breaking on system DLLs, I still have to run through these every time I restart the debuggee. Can we develop a way to auto mark them as system, or remember the user's settings in the modules view?

C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\nvdxgiwrap.dll
C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\nvd3d9wrap.dll
C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\detoured.dll

**Comment by mrexodia** [comment]
I guess the way to implement it would be to either allow adding more system directories or to persist marked DLLs.

**Comment by mirh** [comment]
A slightly more comprehensive solution would be to take into account any `AppInit_DLLs` setting
https://dblohm7.ca/blog/2016/01/11/bugs-from-hell-injected-third-party-code-plus-detours-equals-a-bad-time/

**Comment by torusrxxx** [comment]
AppInit_DLLs is disabled since Windows 8, so NVIDIA has stopped doing it. This feature is still useful nevertheless. I think the best way to do it is to persist marked DLLs.

**Comment by mirh** [comment]
I mean, Nvidia also stopped to ship those dlls too then.
Nowadays they are just using the official hybrid graphics infrastructure.
