### ISSUE TITLE
Add load recent patches in "Patches" window

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#261]
in the "Patches" window it would be helpful having a quick way to load the last recent patches

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/261
- Originally reported by: [cypherpunk](http://bitbucket.org/cypherpunk)
- Originally created at: 2015-03-23T20:20:58.269

**Comment by mrexodia** [comment]
implemented as 'Import' to import patches.
