### ISSUE TITLE
Error in any conditional expression should break

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2630]
Change the conditional breakpoint and tracing logic so that if there is an error in any conditional expression, the debugger breaks so that the user can fix it.

**Comment by mrexodia** [comment]
I believe this is currently already the case (at least for breakpoints),
but there is no error message so it’s quite confusing

**Comment by torusrxxx** [comment]
This is true only for break condition, but if there is an error in log condition or command condition it won't break.

**Comment by mrexodia** [comment]
Good point!
