### ISSUE TITLE
C++ try catch in plugin

### ISSUE THREAD

**Issue by aaron-dadum** [x64dbg/x64dbg#2633]
Hi guys, 

It's not really an bug issue, but I noticed, that try catch exception handling in C++ developed plugin doesn't work. 

Would you be able to state if it's expected behavior? 
Is there anything else I could catch my code's exceptions?

Thank you!

**Comment by mrexodia** [comment]
Can you give a reproduction? There’s nothing that should prevent it from
working to my knowledge...
