### ISSUE TITLE
Call StackFunction module data display is abnormal 

### ISSUE THREAD

**Issue by cn-fairy** [x64dbg/x64dbg#2637]
Test version ：snapshot_2021-04-13_22-19(Windows server2019 17763 x64)
![image](https://user-images.githubusercontent.com/74580422/114676280-b9287600-9d3b-11eb-810e-0a2eb7bcaa07.png)
Exception demonstration ：
![2](https://user-images.githubusercontent.com/74580422/114675672-17088e00-9d3b-11eb-8736-cf5f6c1e6e7a.gif)
As shown in the figure above, when you click on the list name, the data will be displayed abnormally 
Steps to reproduce ：
1. Use x64dbg to load a program 
2. Click the "call stack" function module (the function module needs to have data at this time) 
3. Click on a list name (such as "Thread" in the dynamic picture demonstration)

**Comment by mrexodia** [comment]
CC @morsisko

**Comment by morsisko** [comment]
Hmm, I thought I disabled sorting for this "Call stack" tab. 
Anyway, should it be disabled like in "Breakpoint" tab, or other action is desired?

**Comment by mrexodia** [comment]
For me disabling it is fine, at least better than a broken view.
