### ISSUE TITLE
Olly vs x64

### ISSUE THREAD

**Issue by Serqati** [x64dbg/x64dbg#2657]
is x64dbg better  than or equals to ollydbg ?
if not will x64dbg be stronger as ollydbg ?

**Comment by mrexodia** [comment]
Just try it.

**Comment by Serqati** [comment]
I try it before 
I just want know is it better than The Fuc**ng Olly ?

**Comment by mrexodia** [comment]
Yes it is

**Comment by mrexodia** [comment]
And please refrain from using strong language in the future. No need to be hostile.
