### ISSUE TITLE
Compile with gcc or clang

### ISSUE THREAD

**Issue by Serqati** [x64dbg/x64dbg#2660]
Can I build x64dbg from source with Gcc or Clang ?

**Comment by mrexodia** [comment]
No, msvc only at the moment.

**Comment by Serqati** [comment]
Will It be possible in future ?
Is it in your plan ?

**Comment by mrexodia** [comment]
Why do you want it?

**Comment by Serqati** [comment]
Because msvc isn't open source!
Is Calng and Gcc in ur plan?

**Comment by mrexodia** [comment]
No
