### ISSUE TITLE
Is there a way to use this over CLI to output Assembly?

### ISSUE THREAD

**Issue by jt0dd** [x64dbg/x64dbg#2664]
I found the CLI docs for this https://help.x64dbg.com/en/latest/introduction/Commandline.html and noticed there's no mention of a way to export Assembly for a program, so I just want to double check: x64Dbg cannot act as a CLI disassembler, right?

**Comment by mrexodia** [comment]
Nope, you can use radare2/rizin for that. The command line for x64dbg is meant to be used by launcher-type applications to start a GUI debugging session. There is no stdout or anything of that sort.
