### ISSUE TITLE
Commands don't work in 32-bit (in 64-bit work OK)

### ISSUE THREAD

**Issue by MarianD** [x64dbg/x64dbg#2668]
Status of the debugger:
- just after launching it (`x32dbg.exe`)
- no debuggee attached, no action performed
 
Example (command):
`2+3`

Status line:
>    `[Script DLL] LoadLIbrary failed (00000126)!`

Log:

    Handling command line...
      "C:\Program Files\x64dbg\x32\x32dbg.exe" 
    [Script DLL] Loading Script DLL "C:\Program Files\x64dbg\x32\scripts\2+3"...
    [Script DLL] LoadLibary failed (00000126)!

Version: 
- May 8, 2021, 14:14:31  (Help → About)
- May 8 2021 (TitanEngine) (in the right-hand side of the menu bar)

OS version:
- Windows 7 Ultimate 64-bit Sevice Pack 1

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/121826037-f8c8fb00-ccb5-11eb-89d8-fc0c68fbe308.png)

Switch it back to 'Default'
