### ISSUE TITLE
Can't undo changes in Memory Dump, is this function supported?

### ISSUE THREAD

**Issue by CaledoniaProject** [x64dbg/x64dbg#2669]
I'm running the latest snapshot, trying to undo changes in memory dump, but CTRL-Z does not work:

![screenshot 2021-06-09 at 11 15 25 PM](https://user-images.githubusercontent.com/1357701/121381866-9f6b6f80-c935-11eb-92c8-c95f07406608.jpg)

Is this feature supported?

**Comment by mrexodia** [comment]
There is no generic undo, but you can select the range you want to undo and
use Ctrl+Backspace (or the context menu)
