### ISSUE TITLE
x64dbg does not honor _NT_SYMBOL_PATH environment variable

### ISSUE THREAD

**Issue by CaledoniaProject** [x64dbg/x64dbg#2677]
I've created a system-level _NT_SYMBOL_PATH environment variable then rebooted, but x64dbg is still downloading symbols from https://msdl.microsoft.com

Was it implemented?

**Comment by mrexodia** [comment]
It’s not implemented on purpose. You can change the symbol path and server in the settings.

**Comment by CaledoniaProject** [comment]
Thanks, I found it in the preferences dialog.

**Comment by CaledoniaProject** [comment]
BTW: In the Options menu it's called "Preferences", but the dialog popped up is "Settings", I think you should use the same window title.

**Comment by mrexodia** [comment]
Feel free to open a pull request with a change.

**Comment by CaledoniaProject** [comment]
https://github.com/x64dbg/x64dbg/pull/2678
