### ISSUE TITLE
Some processes cannot be attached, but windbg can be attached

### ISSUE THREAD

**Issue by cn-fairy** [x64dbg/x64dbg#2680]
Version:snapshot_2021-07-01_23-17
System:Window 7  7601
Test object: sqlserver.exe (SQL Server 2008)
![image](https://user-images.githubusercontent.com/74580422/125060542-10da4180-e0df-11eb-8151-37c971e2ecfe.png)

The picture shows the problem described
x64dbg:
![image](https://user-images.githubusercontent.com/74580422/125060643-26e80200-e0df-11eb-93f2-1190efa4f9bc.png)

windbg:
![image](https://user-images.githubusercontent.com/74580422/125059780-46caf600-e0de-11eb-9acc-c8f17b55ff67.png)

**Comment by mrexodia** [comment]
Did you enable the debug privilege in the settings?

**Comment by cn-fairy** [comment]
I have run x64dng as an administrator, and just found the related added options in the settings. Can you take a screenshot to explain? I'll be under test later (I expect to reply in an hour and a half and get off work)

**Comment by mrexodia** [comment]
It’s in the Engine tab -> Debug privilege

**Comment by cn-fairy** [comment]
Thankfully, when running as administrator and with Debug privilege turned on in the engine, it can be attached.
