### ISSUE TITLE
Linux: "It’s not supported and there are no plans."

### ISSUE THREAD

**Issue by xero-lib** [x64dbg/x64dbg#2691]
It’s not supported and there are no plans.

_Originally posted by @mrexodia in https://github.com/x64dbg/x64dbg/issues/2632#issuecomment-815574373_

Why no Linux support? Dotnet works just fine, and you should be able to cross compile for Linux without too many issues.

**Comment by mrexodia** [comment]
You can do the work if you want 😄

**Comment by plefebvre91** [comment]
Hi :) 

@mrexodia I have read all the issues concerning the Linux (non-)support and I'm not asking for this, but just some information to save time.

I did not still went deep into the code, and I think you are better placed than me to know this:
- this debugger has been developed for Windows, but is there any technical constraints which would make impossible to port this  (or at least some parts) on Linux ?
- do you think it's a crazy idea to try this without rewriting this entirely ? 
- as far as you know, is there an existing project which plan to port x64dbg on Linux ?

**Comment by mrexodia** [comment]
It’s definitely possible to port. The main part that can be reused is the
GUI, but there are definitely other parts as well. It might be more
worthwhile to work on edb though…
