### ISSUE TITLE
How to measure execution time?

### ISSUE THREAD

**Issue by Yoshimaster96** [x64dbg/x64dbg#2692]
How do I measure how long it takes for a piece of code to execute? Or at least how long until a breakpoint is hit?

I'm trying to debug a program which I don't have the code for so I can't just modify and recompile it. I'd also like to have at least 1us accuracy if possible.

**Comment by mrexodia** [comment]
This is not a feature of x64dbg. You can use the expression function `GetTickCount()` https://help.x64dbg.com/en/latest/introduction/Expression-functions.html#general-purpose but this is 1ms accuracy and you will have to do the calculations yourself (you can use a breakpoint command for this purpose).

**Comment by Yoshimaster96** [comment]
Ah okay. Well this would be a nice feature to have.

**Comment by mrexodia** [comment]
I see it more as a feature for a plugin, it’s not a common operation when debugging binaries I think. It’s definitely possible though, let me know if you need some help with the plugin api.
