### ISSUE TITLE
pdb ignored?

### ISSUE THREAD

**Issue by gituser5555** [x64dbg/x64dbg#2699]
I created a x64 debug build in visual studio and tried to debug it with x64dbg. The created pdb seems to be ignored, since I can not view a source. Is there some kind of trick?
I already set the symbols path to `.\` (VS creates pdb and exe in the same directory)

**Comment by mrexodia** [comment]
What does it show in the symbol log? If the source code is not on the exact
same location as it was compiled at you cannot open the source (eg on
another machine with different paths)

**Comment by mrfearless** [comment]
You might also need to change some flags and switches to make a pdb compatible with non-visual studio tools. The /FAST and/or /FASTDEBUG switch in the Linker settings should be removed, and the debug optimizations settings in the C/C++ Compiler settings should be set to none (this adds a c1.dll dependency used for visual studio debugging from what i recall). That should help produce a pdb that can be read by other tools including x64dbg.

**Comment by mrexodia** [comment]
Feel free to comment if you have any new information and it can be reopened.
