### ISSUE TITLE
x32dbg not loading pdb file

### ISSUE THREAD

**Issue by sunbeam906** [x64dbg/x64dbg#2704]
First and foremost, please know the following:

- the Debug Directory in the PE file is manufactured (@offset 0xA61E0)
- I've manually created it and adjusted it so it contains VALID information (@offset: 0xA6200)
- the pdb file is manufactured as well with the help of this tool: https://github.com/Mixaill/FakePDB in IDA 7.5 SP3
-- as in: loaded the PE file in IDA, waited for the analysis to finish (it's fast), exported the PDB file with the tool
- the GUID and Age matching the exe to the pdb have been adjusted accordingly
- the PDB information was obtained from this site: https://llvm.org/docs/PDB/index.html
- you can check the files match with ChkMatch (http://beefchunk.com/documentation/sys-programming/os-win32/debug/www.debuginfo.com/tools/chkmatch.html)

![explorer_6CWbzG5CRT](https://user-images.githubusercontent.com/148178/128192213-f1398f34-8b53-4566-a6fe-4f280f62a063.png)

Attached below are the target and x32dbg.exe with the problem:

- target: [target.zip](https://github.com/x64dbg/x64dbg/files/6931733/target.zip)
- x32dbg (build 30 Jan 2021): [x32dbg.zip](https://github.com/x64dbg/x64dbg/files/6931749/x32dbg.zip)

Upon opening the executable in x32dbg and checking the Symbols tab, you can clearly see the PDB information is not loading:

![x32dbg_xfdyPO7L4c](https://user-images.githubusercontent.com/148178/128193276-52600d9d-44f0-49f8-8b9c-6178f08482f8.png)

Which is strange, because Cheat Engine, for example, does read it:

![cheatengine-x86_64_Sfz24H1gol](https://user-images.githubusercontent.com/148178/128193770-6ddde7a9-4f2d-404a-93e7-e2e2cc094654.png)

Please investigate.

Best regards,
SunBeam

P.S.: If a fix can't be produced, can I at least learn WHY the pdb isn't loading and whether or not I should adjust the pdb even further so it does get loaded? Thanks!

**Comment by sunbeam906** [comment]
I have also tried the latest x32dbg build (1 Jul 2021) and getting the same:

![x32dbg_bCXN5LWUpd](https://user-images.githubusercontent.com/148178/128194611-70cd1023-0c35-4e47-b30b-e73bf02e5426.png)

BR,
Sun

**Comment by sunbeam906** [comment]
UPDATE: I've went ahead and attempted to figure out the issue. In short, I've debugged x32dbg with x32dbg with target file loaded:

![1](https://user-images.githubusercontent.com/148178/128199295-6ddc3896-a3ed-4383-b0c2-c58907309932.png)

Skipping the indicated jump leads to this result:

![2](https://user-images.githubusercontent.com/148178/128199350-b8d7faa2-df43-4520-85bf-107109df67a9.png)

SUGGESTION: Please add an override for GUID and Age of exe/pdb so we can load 'fake' pdbs. In short, please add an option to disable PDB validation (like in WinDbg, depicted here: https://web.archive.org/web/20200130221144/http://ntcoder.com/bab/2012/03/06/how-to-force-symbol-loading-in-windbg/)

![3](https://user-images.githubusercontent.com/148178/128200539-cb504c0b-6697-4124-bcc9-e8c34f6682a3.png)

Thank you,
SunBeam

**Comment by mrexodia** [comment]
You can use the symload command:

Symload my.exe, my.pdb, 1

Or you can use the undocumented Misc option. You shouldn’t use it though,
because if the PDB doesn’t match the executable that means your symbols are
wrong.

**Comment by sunbeam906** [comment]
> You can use the symload command: Symload my.exe, my.pdb, 1 Or you can use the undocumented Misc option. You shouldn’t use it though, because if the PDB doesn’t match the executable that means your symbols are wrong.

My executable/pdb are in a certain folder (C:\Users\SunBeam\Desktop\debug). Running **symload lithtech.exe, lithtech.pdb, 1** yells _File does not exist!_. Using the path, with or without "": **symload "C:\Users\SunBeam\Desktop\debug\lithtech.exe", "C:\Users\SunBeam\Desktop\debug\lithtech.pdb", 1** throws _Invalid module "C:\Users\SunBeam\Desktop\debug\lithtech.exe"!_ error. So which is it?

"Or you can use the undocumented Misc option" -- There is a Misc tab in x32dbg, but not an option. Maybe I fail seeing it?

![x32dbg_lNs3THDvU1](https://user-images.githubusercontent.com/148178/128311560-2096b91a-1422-4fb3-a9e4-855031045ef1.png)

And of course "because if the PDB doesn’t match the executable that means your symbols are wrong". That is self-implied, coming from someone who knows what they're doing in there :) But to be fair and square, I suggested an option in the last picture of my previous post. That way anyone would toggle it active only when we'd use a manufactured PDB. I doubt anyone would want to force non-matching PDBs, as we know what the effect of that is: some functions, up to a point, might be correctly aligned with the symbols. But then, later on in the code, since exe mapping has changed, the symbols will point to wrong stuff.

**Comment by mrexodia** [comment]
In my experience if you provide this option someone will enable it and then
forget about it and waste hours and hours debugging with the wrong PDB
(I’ve seen this happen multiple times).

The command takes modulename, path to pdb as described in the
documentation:
https://help.x64dbg.com/en/latest/commands/analysis/symload.html?highlight=Symload

If you don’t want to do this manually every time I suggest using a debuggee
startup script.

**Comment by sunbeam906** [comment]
> In my experience if you provide this option someone will enable it and then forget about it and waste hours and hours debugging with the wrong PDB (I’ve seen this happen multiple times). The command takes modulename, path to pdb as described in the documentation: https://help.x64dbg.com/en/latest/commands/analysis/symload.html?highlight=Symload If you don’t want to do this manually every time I suggest using a debuggee startup script.

While I appreciate your feedback, several things remain overlooked. Here's an example to understand how and where this feature would be used with.

I have game 1, _Wolfenstein New Order_. Engine is idTech 5. Developers left in the .pdb. I then have game 2, _Wolfenstein Old Blood_. Same engine, no .pdb this time around. I can use the first pair from game 1 to map - by array of byte scanning or other means - the same core functions in game 2. In IDA. Then export the mapping as a fake .pdb. Then this .pdb would get loaded into x64dbg and the symbols would point to correct functions in game 2. How do I know? I created it and it's linked to that specific executable.

"if you provide this option someone will enable it and then forget about it and waste hours and hours debugging with the wrong PDB (I’ve seen this happen multiple times)"

Then.. in my experience.. that person isn't very good at what they're doing. As a reverse engineer, I thoroughly make sure everything is in the right space. As suggested, that option can be a check-box and left unchecked by default. Whenever needed, in examples like the above, it can be toggled active. Trust me, you wouldn't forget it's on, considering you're working with a manufactured .pdb. Also.. can you explain a bit how a human being would work with 1 exe version and the .pdb from 2-3 versions ago? I'm talking game-hacking here, not coding and debugging your own made exe with the matching pdb pair. In the game space you wouldn't be able to mix-up .exes and .pdbs, simply because they are rare to come by. Mostly due to developer mistakes when configuring Steam depots.

Lastly, **you still haven't explained why msdia140.dll fails to find the Age in the pdb I uploaded here**. Before quick-replying that the pdb's structure might be off vs. what MSVS produces, I encourage you to: a) check the data -OR- b) say you're not interested in checking this. It would save us both a lot of time.

Much appreciated,
Sun

P.S.: To be clear - I'm not arguing, not trying to artificially create a dispute, etc. Am calm, no need to go into psychology 101 from just reading plain text. There's no tone to it here, so let's leave it as flat-line reading :) Thanks!

**Comment by mrexodia** [comment]
I would need the executables and pdbs to figure out why Microsoft’s code might fail to extract the correct age. You can try using different msdia140.dll versions, but I’ll check the x64dbg code to see if there might be a mistake somewhere.

With regards to the option, it already exists but there is no GUI for it (you can set it in the INI or use the other method I described with symload). You can find it in the source code (currently on mobile so I cannot check it). There won’t be a GUI option added for it because of the concerns I highlighted previously.

**Comment by sunbeam906** [comment]
> I would need the executables and pdbs to figure out why Microsoft’s code might fail to extract the correct age. You can try using different msdia140.dll versions, but I’ll check the x64dbg code to see if there might be a mistake somewhere.

They have been attached to the first post. Available from moment 1 :) Please see post #1:

![chrome_8tPnGV4Y62](https://user-images.githubusercontent.com/148178/128346107-7d3211ba-6a33-4a51-974b-76c34016a481.png)

> With regards to the option, it already exists but there is no GUI for it (you can set it in the INI or use the other method I described with symload). You can find it in the source code (currently on mobile so I cannot check it). There won’t be a GUI option added for it because of the concerns I highlighted previously.

Will check the source code, sure.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/128352202-0bab8090-1e4c-4276-89e6-e84fcb1052ee.png)

I tried various msdia140.dll versions and all of them report age of zero. There is no error going on (there is a path that sets the age to zero if a certain bit isn't set in the global symbol) and a struct field that is close to the GUID is being dereferenced. I think this is because for some reason MS DIA doesn't correctly recognize this frankenstein PDB, but likely you could figure out more if you trace the creation of this structure and see where the data of this+0x204 field comes from (I tried searching for 0x204 but the only function I found was `public: bool __thiscall CSymRow::computeAddrs(class SymCache &)` which is probably unrelated.

**Comment by sunbeam906** [comment]
I just discovered something :) I don't think there's need to pursue this any further. Explaining why.

When I first created the fake PDB, my executable wasn't "adjusted" with a Debug Directory and valid information. As such, when I exported the PDB from IDA, this happened:

```
FakePDB/generate pdb (with function labels):
    * generating JSON: F:\Games\NOLF\lithtech.exe.json
    * generating PDB: F:\Games\NOLF\lithtech.pdb
    * symserv EXE id: b'3AE746D9C7000'
    * symserv PDB id: b'00000000000000000000000'
    * done
```

Notice how the symserv PDB id is 0.

I've re-run now the IDA export of a PDB, but used the adjusted executable this time around. So the tool now reads the PDB information "planted" in the Debug Directory and outputs this when exporting the .pdb file:

```
FakePDB/generate pdb (with function labels):
    * generating JSON: C:\Users\SunBeam\Desktop\debug\lithtech.exe.json
    * generating PDB: C:\Users\SunBeam\Desktop\debug\lithtech.pdb
    * symserv EXE id: b'3AE746D9C7000'
    * symserv PDB id: b'3810F85E542A40B394ABED5EDF1399C31'
    * done
```

A valid 16-bytes ID read from the executable :)

And guess what.. without forcing the flag in the .ini..

![x32dbg_UHXBKMR6R6](https://user-images.githubusercontent.com/148178/128358519-3f6d2ee5-bd42-4c16-b0b0-a9c4bc1f2ca4.png)

So.. rule number 1: fix the executable first, adding the Debug Directory and adjusting GUID, Age, etc. -- all the PE stuff. ONLY THEN use IDA to produce a fake .pdb :)

You may close this issue.

**Comment by mrexodia** [comment]
Glad it’s resolved :)

I was doing most things from my email so I totally missed your initial post with all the attachments, my bad on that one.

**Comment by wqj66** [comment]
Hello Why can the old OD type db to get the interval memory address but the new one can't.

**Comment by mrexodia** [comment]
Can you clarify @wqj66 ? I don’t understand your question and how it relates to this issue. Please add screenshots or something to illustrate the problem.
