### ISSUE TITLE
HEX calculate BUG

### ISSUE THREAD

**Issue by h8suga** [x64dbg/x64dbg#2705]
Debbuger Version: Jul 1 2021.
Calculate HEX not working.
![image](https://user-images.githubusercontent.com/88285797/128396912-75d9952f-0d20-42d6-8855-22e50cad6433.png)

**Comment by mrexodia** [comment]
The default base is hex, see https://help.x64dbg.com/en/latest/introduction/Input.html#numbers

For decimal 10, use `.10`
