### ISSUE TITLE
Searching for string references is giving less results than before

### ISSUE THREAD

**Issue by tracid1987** [x64dbg/x64dbg#2733]
### Operating System

Windows 10 Pro 64bit, 20H2, OS build 19042.1165

### x64dbg Version

jul 1 2021

### Describe the issue

Today i have downloaded "snapshot_2021-07-01_23-17.zip" I did not install it yet, i was always launching x64dbg/release/x32/x32dbg.exe from the windows explorer folder. I have opened a file and clicked on the CPU field "search for-all modules-string references". i cant remember how many results it has found together but when i have further searched the results for a specific string it has found at least 5 lines with my desired string. i was trying a few times and the results were the same.

then i made a nap and when i have returned i did not launch x64dbg/release/x32/x32dbg.exe from the windows explorer folder itself but i ran x64dbg/release/x96dbg and clicked install and accepted everything - to place icons, integrate into shell. then i have launched x32dbg from the desktop. in references i have unticked TLS callbacs. then i have loaded the same file and searched for all the string references in all modules the same way as before and i still dont know how many results it has found altogether but when i further searched for my desired string it has found only 1 line as opposed to the results found earlier.

I did not set anything else, i did not do anything else but now it is finding only that 1 result. i have tried to launch x32dbg from different path locations but still less results found.
I have unpacked the downloaded snapshot_2021-07-01_23-17.zip and run a freshly unpacked version of it but it still finds less string

I have attached one screenshot where you can see strings like it cant encode them- its a random result (not my desired) and i dont now if it was like this before, i have noticed it only now, i am attaching just in case if it helps to solve the issue.

I cant understand what happened, is it possible that by installing something was modified? 
Is it possible to change encoding or to extend string search results?
Is it possible to reset x64dbg in the system? 

Thank you

### Steps to reproduce

1. unfortunately i cannot reproduce it
2. 2.
3. 3.

### Attachments

![dbg](https://user-images.githubusercontent.com/90793716/133487883-986d3e58-2a3e-4d8b-850e-644fa2233102.jpg)

**Comment by tracid1987** [comment]
Looks like "Open" or "Attach" makes the difference, because now i have attached the alredy running exe and now it has found all strings. when i open the exe it find less. what is the difference?

**Comment by ZehMatt** [comment]
Maybe the process loaded things from a file into the data section? I don't think this is a bug

**Comment by tracid1987** [comment]
Yes i have alredy realised that its not a bug. After getting answer from somebody why did it happen, how can i delete this issue from here? Because if its not a bug then it has no place here. Thanks

**Comment by ZehMatt** [comment]
I'll take care of it, dont worry.
