### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by vadimszzz** [x64dbg/x64dbg#2736]
Can you support remote debugging of ARMv7 & ARMv8 for just in case Apple M1 software or iOS kernel? (llvm debugserver protocol)

I don't know any existing good ARM graphical debugger, if there's one please tell me. I tried hopper and IDA, both are unusable. They're much harder than x64dbg.

**Comment by mrexodia** [comment]
The most architecture-independent part would be the GUI. My goal is to eventually provide this as a library, but this is a work-in-progress. If you want to do Windows on ARM it should be much easier.

**Comment by UnlimitedChild** [comment]
https://gitee.com/geekneo/A64Dbg

An arm/arm64/x86/x64 assembly level debugger for macOS/iOS/Linux/Android.

<html>
<body>
<p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An arm/arm64/x86/x64 assembly level debugger for macOS/iOS/Linux/Android like OllyDbg &amp; X64Dbg.</p><p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An arm/arm64 virtualization debugger(uvmdbg) based on UraniumVM for macOS/iOS/Android.</p><p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Running desktop platform supports Windows/Linux/macOS.</p><p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The debugee platform supports macOS/Linux/iOS/Android.</p>

  | Local | Remote Android | Remote iOS
-- | -- | -- | --
Windows | No | Yes | No
Intel Linux | Yes | Yes | No
ARM Linux | Yes | Yes | No
Intel macOS | Yes | Yes | Yes
ARM macOS | Yes | Yes | Yes

<ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; padding-bottom: 1px; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: initial;">GUI Runtime is based on<span> </span><a href="https://www.qt.io/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">Qt</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">GUI Controls is based on<span> </span><a href="https://gitee.com/geekneo/X64Dbg/" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">X64Dbg</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">DebugEngine is based on<span> </span><a href="http://lldb.llvm.org/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">LLDB</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">Assembler/Disassembler is based on<span> </span><a href="http://llvm.org/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">LLVM</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">Decompiler is based on<span> </span><a href="https://retdec.com/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">RetDec</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">Script is based on<span> </span><a href="https://www.python.org/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">Python</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">AnalyzeEngine is developed by<span> </span><a href="http://yunyoo.cn/" rel="nofollow" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">YunYoo</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">UVMEngine is developed by<span> </span><a href="https://gitee.com/yunyoo/UraniumVCPU/" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">YunYoo</a>;</li></ul><p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://gitee.com/geekneo/A64Dbg/blob/master/Version.md" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">Debugger Version</a>:</p><ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; padding-bottom: 1px; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: initial;">Windows user: download from<span> </span><a href="https://gitee.com/geekneo/A64Dbg-Win" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">A64Dbg-Win</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">Linux user: download from<span> </span><a href="https://gitee.com/geekneo/A64Dbg-Linux" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">A64Dbg-Linux</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">ARM Linux user: download from<span> </span><a href="https://gitee.com/geekneo/A64Dbg-LinuxARM" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">A64Dbg-LinuxARM</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">Intel macOS user: download from<span> </span><a href="https://gitee.com/geekneo/A64Dbg-Mac" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">A64Dbg-Mac</a>;</li><li style="box-sizing: border-box; list-style: initial; margin-top: 0.25em;">ARM macOS user: download from<span> </span><a href="https://gitee.com/geekneo/A64Dbg-iOS" style="box-sizing: border-box; background: transparent; color: rgb(9, 94, 171); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">A64Dbg-iOS</a>;</li></ul>
</body>
</html>

**Comment by mrexodia** [comment]
Unfortunately A64Dbg is not open source (it violates the GPL) and you cannot be sure what you are executing. Be careful!

**Comment by vadimszzz** [comment]
Found https://github.com/snare/voltron

**Comment by vadimszzz** [comment]
@UnlimitedChild thank you, that's what I need

**Comment by vadimszzz** [comment]
> Unfortunately A64Dbg is not open source (it violates the GPL) and you cannot be sure what you are executing. Be careful!
> 
> Additionally the author is not cooperating in good faith to open source the parts I requested.

Nobody cares about opensource 😂😂😂. This chinese dude made ultra cool tool based on yours and he don't want to share his hard work.

**Comment by giteeisdumb** [comment]
Yeah you can't even download lmao because China ? smh
