### ISSUE TITLE
Search in the log

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2752]

**Comment by dalerkd** [comment]
This is a good idea, because I often encounter the need to copy it to software like notepad, and then search for it.

**Comment by rajkumarananthu** [comment]
I would like to work on this, can I? Any pointers to start on this issue?

**Comment by mrexodia** [comment]
Certainly! There should be a find function in QTextEdit. See
https://stackoverflow.com/questions/37598807/qplaintextedit-searches-the-document-to-the-end-and-again-from-the-beginning

**Comment by rajkumarananthu** [comment]
Thank you, please assign the issue to me, in case of any questions will approach you, I'll start working on this.

**Comment by mrexodia** [comment]
Thanks for taking it on! I assigned the issue to you.

**Comment by rajkumarananthu** [comment]
Adding the email conversation here as suggested:

Good Day,

I went through the code base and found that the changes are around "class LogView".

Following is my plan:
1. Add an action "find" in logview(with a shortcut Ctrl+F, if possible).
2. Add a new Dialog box "class FindDialog '' extending from QDialog.
3. Connect the action of find in logview to FindDialog and action of find button on DialogBox to search/find function in LogView.
4. Search the user input text in the log data(which is QString logBuffer; in LogView, as I understand).
5. Highlight all the matching words in the LogView if found.
6. If not, create an error dialog.

Please correct me if I am wrong anywhere and provide your review/suggestions/improvements I can do?

Duncan:
Hi,

It would probably be better to post this in the issue, that ways others can learn from it too. There is already a function QTextEdit::find that implements the finding and selecting of the text. There is also already a helper dialog called LineEditDialog so you won’t have to create your own.

**Comment by mrexodia** [comment]
Any update on this? If you’re stuck I’m happy to help out :)

**Comment by rajkumarananthu** [comment]
@mrexodia Hi, thanks for waiting, I was on vacation for the past ~15 days, so I couldn't work on this, I'll start working on this, will reach out to you in case if I am stuck somewhere.

**Comment by rajkumarananthu** [comment]
Hi @mrexodia , I am trying to compile the project in Windows 11 with Visual Studio Community 2022. Windows is a guest OS on Ubuntu(as Virtual Machine). I am able to successfully build from Visual Studio. But while building with Qt, I am facing the following error:

`Project ERROR: Unknown module(s) in QT: winextras`

Any idea how to fix this issue?

**Comment by mrexodia** [comment]
What version of Qt are you using?

**Comment by rajkumarananthu** [comment]
Sorry for the delayed reply, I was using Qt 6.2.2, which I found has a major change in QtCore package, so I want to check it with Qt 5.15.2.
After changing the Qt library to 5.15.2, I am able to successfully compile the application through QtCreator, but while launching the application I faced an error saying that:
`The application failed to start because it could not find or load the Qt platform plugin 'windows'`

Then I ran:
`windeployqt --force x64gui.dll`

And then everything worked fine. I also made the changes respective to add this feature, now I am checking its functionality.
If any questions, I'll reach out to you.

Thanks

**Comment by mrexodia** [comment]
I guess you found the guide?

https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project#compiling-with-different-visual-studioqt-versions

**Comment by rajkumarananthu** [comment]
Yeah, that's the one that helped me get through this.

**Comment by rajkumarananthu** [comment]
Hi @mrexodia I created a pull request: https://github.com/x64dbg/x64dbg/pull/2817 with my changes, please review them and let me know if anything to change, below are the snapshots after adding the feature, and showing the version of the tool:

![Window_menu](https://user-images.githubusercontent.com/10969471/148347716-ba2bf0e6-fc4d-4286-a699-7a919da285af.png)

![Search_for_Dialog](https://user-images.githubusercontent.com/10969471/148347766-77ad8e99-1c53-4ef7-9a1e-7611a20e86cb.png)

![Highlighted_strings_after_clicking_ok](https://user-images.githubusercontent.com/10969471/148347783-414ac88c-e364-406b-9e37-56f283c7ad38.png)

![About](https://user-images.githubusercontent.com/10969471/148348240-fdabc4a1-8615-4f7b-8e3e-2e356158c156.png)

Let me know if this doesn't match what you would like or any more improvements needed or anything else.
I am new to open-source contributions, please let me know if I am missing anything or anything I can improve(from coding or design perspective).

Thanks
Rajkumar Ananthu.

**Comment by rajkumarananthu** [comment]
Hi @mrexodia thank you for accepting my changes, I think now we can close this issue, I think I can't close the issue.
Thanks,
Rajkumar Ananthu

**Comment by mrexodia** [comment]
Yep, agreed. Next time you can write “Closes #1234” in your description and GitHub will do it automatically for you :)
