### ISSUE TITLE
Set codepage as default string view?

### ISSUE THREAD

**Issue by myocytebd** [x64dbg/x64dbg#2757]
### Feature type

Quality of life

### Describe the feature

It is great that in in Dump, codepage based string view is supported.    
But could it be extended to other UI components? Auto hinting in CPU/Register/Stack assumes ascii string.

**Comment by mrexodia** [comment]
Unfortunately the code page feature has really bad support, so I don’t know if it will be a good idea to extend it to other places as-is.

Perhaps with some work it could be done…
