### ISSUE TITLE
Update Visual C++ Redistributable Requirements for running x64_dbg to VS2013

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#276]
Had a user on the masm32 forum post about an issue with running latest snapshot x32_dbg.exe requiring MSVCR120.dll (which is part of the Visual C++ Redistributable Packages for Visual Studio 2013)

Now that the project has been upgraded to use VSCE, the requirements to run x64_dbg should be updated to reflect this (on the sourceforge page and elsewhere?)

Visual C++ Redistributable Packages for Visual Studio 2013
http://www.microsoft.com/en-US/download/details.aspx?id=40784 

(contains both x86 and x64 parts)

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/276
- Originally reported by: Mr. fearless
- Originally created at: 2015-04-07T12:51:06.676

**Comment by mrgreywater** [comment]
I propose that it should be compiled with the /MT flag which statically links the necessary msvc libraries. This way the requirement to install any Visual C++ Redistributable is gone. (This will result in a larger binary, but I don't really think anyone cares)

**Comment by mrexodia** [comment]
This would work if Qt also used the /MT flag. I don't feel like shipping a custom Qt version. What could be done is ship the redistributable DLL files directly with the release.

**Comment by mrgreywater** [comment]
I always thought it was forbidden to distribute those individual microsoft dll's, but [I guess I am wrong in this case](https://msdn.microsoft.com/en-US/vstudio/dn501987#VS2013UltPremPro). Adding the dlls would be a good idea.

**Comment by Nukem9** [comment]
Site links have been updated for a while now. Closed.
