### ISSUE TITLE
[Help] Breakpoint command: how to single-step after data read breakpoint?

### ISSUE THREAD

**Issue by myocytebd** [x64dbg/x64dbg#2761]
### Operating System

Windows 10 x64 Pro, 21H1, Build 19043.1165 (VMWare Guest, host=Linux)

### x64dbg Version

July 1 2021

### Describe the issue

What I want:  
On data read/write break-point (Hardware Access - Read/Write):  step-over/out a few times, log, and run.  

I could not figure out how to do it in commands.  
In GUI, on data breakpoint X, single-step will break on already-hit X again once, and then continue without problems.  

My question: How to get it work in breakpoint commands?  
`log "pre"; StepOver; log "post"; run;` Hits again on already-hit X and stopped, with log:  
```
pre
post
Hardware breakpoint (dword, read/write) at 039550E8!
```
 (why post got printed?)
(I tried to add enable/disable etc., and things went weirder and anyway still stopped on X.)

### Steps to reproduce

1. Add a data read breakpoint or Hardware Access - Read in x32dbg.  
2. Set command to `log "pre"; StepOver; log "post"; run;`.
3. It stopped on the already-hit Hardware Access/Read breakpoint again. How to make it step without hit the already-hit breakpoint?

**Comment by myocytebd** [comment]
It seems that commands does not execute in order?  
`eip: sete dl (edx=0)`
command: `sto; mov edx, -1;` (run in GUI command input)
Resulting in edx=ffffff00

**Comment by mrexodia** [comment]
Check the manual. It is not supported to execute a step in the breakpoint command.
