### ISSUE TITLE
comment view text display incorrect

### ISSUE THREAD

**Issue by xtayaitak** [x64dbg/x64dbg#2769]
### Operating System

Win10 64bit 

### x64dbg Version

newest develop branch, commit id bae7211

### Describe the issue

**I think the reason is  Memory<COMMENTSINFO*>  only allocate memory.but have not call construct of std::string.
so copy COMMENTSINFO struct means copy std::string but src std::string is not a object.it is only zero filled memory**

![image](https://user-images.githubusercontent.com/4498459/138239327-d222297a-609b-4f8a-8de3-0abf4b84420c.png)
![image](https://user-images.githubusercontent.com/4498459/138239355-aa8fb40b-9d3e-4f82-b452-796488bd7c2b.png)

### Steps to reproduce

1. git clone newest code
2. complie with vs2017,Qt5.14.2
3. run and type a comment
4. ctrl+alt+c  show comment tab

**Comment by mrexodia** [comment]
I totally agree, this looks like UB that simply happens to not do anything
bad on VS2013

**Comment by xtayaitak** [comment]
@mrexodia I think this struct should be declare as pod type.like this.
![image](https://user-images.githubusercontent.com/4498459/138383914-97d2700e-f2b1-40de-9f76-740aab2742c0.png)

**Comment by xtayaitak** [comment]
I added new CommentEnum to fix this.I don't know if it cause other problem.
![image](https://user-images.githubusercontent.com/4498459/138387345-d938d665-7c14-4ab8-b618-b93e63894918.png)
![image](https://user-images.githubusercontent.com/4498459/138387469-794b14b7-077b-4e8e-987e-b9bc69ee9e51.png)
