### ISSUE TITLE
goes to document and does not open at all

### ISSUE THREAD

**Issue by joemamasbed** [x64dbg/x64dbg#2785]
### Operating System

Windows 10 home 21h1

### x64dbg Version

nov 13 2021

### Describe the issue

i try to open it it open explorers documents then i close out then it opens again i close out of that it gives the normal menu and if i pick 32 or 64 bit they both would crash and do nothing

### Steps to reproduce

1. ^
2. ^^
3. ^^^

**Comment by mrexodia** [comment]
Could you make a video? I don’t understand what you are doing and what’s the issue. Could you provide any minidumps?

**Comment by joemamasbed** [comment]
> Could you make a video? I don’t understand what you are doing and what’s the issue. Could you provide any minidumps?

ive figured out you cannot move the file where ever its extraacted has to be its final location or else it does as described

**Comment by mrexodia** [comment]
Okay, let me know if the issue is not closed for you...
