### ISSUE TITLE
Plugins can not be installed

### ISSUE THREAD

**Issue by Formingus** [x64dbg/x64dbg#2788]
### Operating System

Win10 x64 21H1

### x64dbg Version

Nov 3 2021

### Describe the issue

Plugins can not be installed!! I cant instal any plugin !! ? ny Idea

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Copy them to the `plugins` folder.

**Comment by user18x** [comment]
Same problem here!

After download of xanalyzer and extracted to the plugins folder i can't find the plugin!

I did exactly whats written here:

    Download the latest version of x64dbg

    Extract apis_def.zip

    Copy xAnalyzer.dp32/xAnalyzer.dp64 and the apis_def folder to the respective plugin directories in x64dbg

    Look under the "Plugins" menu in the main x64dbg window or in the secondary menu in the Disasm window as well for an "xAnalyzer" entry[/quote]
There is no plugin named xanalyzer in the plugins menu, only Scylla!

I'm on Win 10 64-Bit
x64dbg latest release
