### ISSUE TITLE
(snapshot_2015-04-10_12-56) crash on detaching/stopping the process after adding a BP

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#279]
Hi, i would like to report a bug with the new snapshot (2015-04-10_12-56),

as the title says, the debugger crashes on detaching / stopping a process when a BP
is already set.

This is the information thrown after crash:

------------
Problem signature:

  Problem Event Name:	APPCRASH

  Application Name:	x64_dbg.exe

  Application Version:	0.0.2.5

  Application Timestamp:	552701ec

  Fault Module Name:	ntdll.dll

  Fault Module Version:	6.3.9600.17114

  Fault Module Timestamp:	53649e73

  Exception Code:	c0000005

  Exception Offset:	000000000006361a

  OS Version:	6.3.9600.2.0.0.256.4

  Additional Information 1:	a7a9

  Additional Information 2:	a7a995a44779e2312cdd48619ceb0a5c

  Additional Information 3:	9229

  Additional Information 4:	9229bd6f028184c87c7fece30835270b

------------

To reproduce the problem:

1) Simply load any application

2) Place a breakpoint anywhere in the code

3) Press the "stop debugging" button or detach the process

this happens with the x32 and the x64 versions,
i didn't test what would happen if i attached a process instead of opening it from the debugger

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/279
- Originally reported by: [w k](https://github.com/wk-952)
- Originally created at: 2015-04-10T02:59:35.819

**Comment by Nukem9** [comment]
This happens because of jansson.dll using msvcr100.dll and x64dbg itself using msvcr120.dll.
`FILE*` is incompatible:  https://bitbucket.org/mrexodia/x64_dbg/src/b0f06aeeb5eff1a4f41257ab8b6691fd0d2ab9c5/x64_dbg_dbg/addrinfo.cpp?at=master#cl-46


I can't fix this (don't have access to snapshots to update Jansson)

----------------------------------------
Original comment by: [Nukem9](http://bitbucket.org/Nukem9)

**Comment by Nukem9** [comment]
Thanks for your reply Nukem9,

I tried something trivial which is simply compiling jansson.dll in VS 2013 so it would depend on msvcr120.dll,
and it worked so the problem is partially solved (no more crashes) but another one came up,
after setting the required BPs and comments then restarting the process, both BPs and the comments are gone from the Disassembly window *only* .

The debugger still broke on the address and i can see all the BPs and the comments in their corresponding tabs,
so the BPs are still there and effective.
Another thing is that at the bottom-left status bar (exactly after breaking) i got the error message: "breakpoint reached not in list!"

i guess this is all because of the in-compatibility right?


----------------------------------------
Original comment by: w k

**Comment by Nukem9** [comment]
It's probably the incompatibility with more dlls. I don't know which ones mrexodia recompiled with VS2013.

----------------------------------------
Original comment by: [Nukem9](http://bitbucket.org/Nukem9)

**Comment by mrexodia** [comment]
I didn't recompile anything, it's still on my bucket list :lollipop:

**Comment by wk-952** [comment]
I think i found the faulty modules,
it is "x32_dbg.dll" and "x64_dbg.dll"
after replacing both with the ones included in "snapshot_96" at sourceforge
everything magically worked without problems,
no need to recompile jansson.dll in VS2013 (no crashes occur),
BPs and comments are reserved after restarting / detaching the process and the
error message "breakpoint reached not in list!" is no longer displayed.

I don't have experience in programming so i don't know exactly which part in the source
code that has changed since "snapshot_96" and caused this issue,
also the "snapshot_2015-04-06_11-57" which is the one exactly before the last snapshot has this issue too.

I hope this helps

**Comment by mrexodia** [comment]
the transition to VS2013 happened between `snapshot_96` and the current one. the reason it works with the older `_dbg` files is that they are VS2010 :smiley: 

I'll try recompiling jansson somewhere this weekend. You could also bother Nukem to share his new compiled version for VS13 :+1:

**Comment by mrexodia** [comment]
breakpoint restoring from the database is broken, has not much to do with jansson...

**Comment by wk-952** [comment]
Thank you so much mrexodia,

I've cloned and recompiled everything from the beginning (x64dbg and all its dependencies) in VS2013,
and all the issues stated here are gone, i'm also now able to use my old database again.

So thank you again mrexodia and Nukem9.

One last thing i want to point out to, i couldn't compile TitanEngine in VS2013,
-when compiling as "Release|Win32" i get the error message:
" error C2039: 'Cr0NpxState' : is not a member of '_FLOATING_SAVE_AREA' "
in the file: Global.Engine.Context.cpp
at lines: 96 and 194

and the warning: "warning C4996: 'GetVersionExW': was declared deprecated"
in the file: Global.Engine.Hider.cpp
at line: 17

-and when compiling as "Release|x64" i get the error message:
" error C1047: The object or library file 'scylla_wrapper_x64.lib' was created with an older compiler than other objects; rebuild old objects and libraries "

and the 2 warnings:
1) " warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc "
   in the file: \include\xlocale
   at line: 337

2) the same warning about 'GetVersionExW' when compiling as win32

**Comment by wk-952** [comment]
Oh i guess there is another problem...
all plug-ins are no longer working (StaticAnalysis, ScyllaHide, OllyDumpEx_X64Dbg)
except Scylla that comes pre-installed with the debugger

**Comment by mrexodia** [comment]
Use the latest snapshot (will be online in a few hours) I recompiled
everything with static runtimes except Qt, so now you only need the vs13
runtimes.

**Comment by wk-952** [comment]
No words can describe my appreciation for all your work, thank you.
I guess this issue can be closed now since everything is solved.
