### ISSUE TITLE
Target process is not present in "Attach" list

### ISSUE THREAD

**Issue by YVEF** [x64dbg/x64dbg#2795]
### Operating System

Windows 10 Version 20H2 64-bit build 19042.1288

### x64dbg Version

Nov 3 2021

### Describe the issue

Hi, I unable to attach to the process of Zscaler client. 
I have Zscaler, installed on my pc, and I want to be able to debug it, but the target process (ZSATray.exe) is missing in the "Attach" list. ("Enable source debugging" is enabled in the settings).
Actually, I don't know is this is bug or not, but want to know the reason, if it's possible.
Thanks you :)

### Steps to reproduce

1. Install Zscaler on a PC
2. Check if ZSATray.exe is running.
3. Open Attach tab in the x64dbg and check that the process is not present.

**Comment by ZehMatt** [comment]
Is the process elevated by any chance? You can not attach to elevated processes unless x64dbg is elevated as well.

**Comment by YVEF** [comment]
@ZehMatt 
thanks for the feedback.
what does elevated mean? which privileges should be included? or do you mean, just using admin rights?

**Comment by mrexodia** [comment]
See the FAQ: https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions

**Comment by YVEF** [comment]
@mrexodia 
thanks, I saw the FAQ.
x64dbg run using admin rights, Enable Debug Privilege - checked, target process (ZSATray.exe) is not kernel protected. So, unfortunately, the FAQ is not answering on my question.

**Comment by mrexodia** [comment]
Maybe it’s the wrong architecture? If you do `attach .pid` you might get an error message. If the process doesn’t show in the attach list that means x64dbg cannot open a handle to it (usually indicating either missing privileges or some kind of protection).

**Comment by YVEF** [comment]
@mrexodia yes, you are right. my mistake.
thank you!
