### ISSUE TITLE
Help I need to crack the program

### ISSUE THREAD

**Issue by lsh7161** [x64dbg/x64dbg#2797]
### Operating System

window10

### x64dbg Version

x64

### Describe the issue

hello i live in korea
when i look at this site
https://www.optitrack.com/support/downloads/motive.html

I need the motive.3.0.0 crack file
Anyone possible
do you have?
I am X64DBG
I dID know how to patch

We will pay in Bitcoin.

lsh7161@naver.com

### Steps to reproduce

1. 
2. 
3.

**Comment by ZehMatt** [comment]
Wrong place for this
