### ISSUE TITLE
How do I fix the scaling issue in x64dbg?

### ISSUE THREAD

**Issue by c0d3f0rc3** [x64dbg/x64dbg#2801]
### Operating System

Windows 10 64 bit Build 19043.1348

### x64dbg Version

Dec 5 2021

### Describe the issue

All the buttons and icons are big and blurry. 
Even the scrollbars are abnormally huge too. 
My windows scaling settings is 150% (Recommended). 
If I change it to 125%, both fonts and icons will become way too small. 
How do I fix it?
Is this related to high DPI settings?

### Steps to reproduce

1. Just open x64dbg and see that all of the icons/buttons are too big and blurry

### Attachments

Huge and blurry icons (and scrollbars) (150%)
<img width="960" alt="1" src="https://user-images.githubusercontent.com/71599154/146235295-cce7f9f8-5102-4cf0-9891-d0af4be288f4.png">
small icons (125%)
![2](https://user-images.githubusercontent.com/71599154/146236291-23fb915b-c0c2-4a9b-8272-fabac9bcefba.png)

**Comment by mrexodia** [comment]
I don’t have a device that has this high dpi/scaling thing, but I have seen it before and tried some blind DPI-related fixes…

**Comment by codecompliant** [comment]
I am seeing the same issue even on a 1920x1080 display (laptop).
The application gui is scaled so small it is barely readable. It looks much better when I change Windows scaling to 150% but then all of my other apps/icons are much larger which is not ideal.

**Comment by mrexodia** [comment]
I’m not seeing any issues on my laptop, I think it’s related to high DPI
screens but I don’t have it so no way to reproduce.

**Comment by codecompliant** [comment]
I just changed all the fonts to 10 and system to 12 seems better now.

**Comment by pka4916** [comment]
i have the same problem.    high DPI on my laptop.
