### ISSUE TITLE
Add "detach and exit" to the exit confirm dialog

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2802]
I find I need "detach and exit" more often than restart debugging or stop debugging. Are there too many choices?

**Comment by mrexodia** [comment]
Can’t you make a favorite command to do it? I thought of doing things the same way as visual studio and detach if you attached when exiting. Would that work for your workflow?

**Comment by torusrxxx** [comment]
The problem is that there is no command to do that, no "shutdown", "terminate" or "exit" command to exit x64dbg. There is also no way to execute "shutdown" after "detach" completed.

**Comment by torusrxxx** [comment]
Whether the user wants to terminate or detach depends on whether the debuggee is a game or virus.

**Comment by mrexodia** [comment]
Perhaps the detach command can get a parameter to do that? Or you can add it to the exit dialog (which I have disabled)? I’m not a fan of the idea to add a menu for it, but with the command you can do a favorite.

**Comment by torusrxxx** [comment]
I'd like to get it into the exit dialog. There are already 4 options, if 5 are too many, then remove some useless options like "stop debugging".

**Comment by mrexodia** [comment]
Yes, stop debugging is a useless option indeed ^^
