### ISSUE TITLE
Add a command to run a debuggee without debugging then auto-attach after 5 seconds

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#2804]
### Feature type

Quality of life

### Describe the feature

I believe some users may find it handy.

**Comment by ZehMatt** [comment]
Isn't this something you could probably do with a plugin just as easily?

**Comment by torusrxxx** [comment]
I don't need this feature myself. Wait for somebody else to do it in their plugin.

**Comment by torusrxxx** [comment]
Looks like nobody needs this.
