### ISSUE TITLE
你好中文乱码

### ISSUE THREAD

**Issue by wasd345** [x64dbg/x64dbg#2811]
### Operating System

中文乱码

### x64dbg Version

dec 28 2021

### Describe the issue

![image](https://user-images.githubusercontent.com/5779660/147624901-40e865d6-ec75-42af-997b-a158ef680344.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5779660/147624993-61c624bb-2dc3-4da5-b266-6c1fe00bc212.png)

### Attachments

![image](https://user-images.githubusercontent.com/5779660/147624933-0168fe4e-b1c6-425f-b92d-92fcab56f81b.png)

**Comment by torusrxxx** [comment]
这是什么
