### ISSUE TITLE
New table rendering buggy at scaling resolutions

### ISSUE THREAD

**Issue by eliphatfs** [x64dbg/x64dbg#2819]
### Operating System

Windows 10 64 bit 19043.1415

### x64dbg Version

snapshot_2022-01-05_13-06.zip

### Describe the issue

I have just upgraded x64dbg from an older version (but unfortunately I cannot recover what was the previous version). x32dbg CPU view starts to render at a strange resolution, texts aliasing heavily. Other parts are clearly visible. I suggest viewing this screenshot in full-screen. I am sure you can find the difference between the CPU view and the others.
![image](https://user-images.githubusercontent.com/23738781/149049861-5bd4b6a2-1767-4476-8b65-fbe26dd9c51f.png)

### Steps to reproduce

(Not available)

**Comment by torusrxxx** [comment]
fixed in  fddef53

**Comment by mrexodia** [comment]
Do you have scaling set up in Windows @eliphatfs ?

**Comment by eliphatfs** [comment]
Yes, I think.

**Comment by torusrxxx** [comment]
Likely because that code doesn't support ClearType.
![Enabling and Disabling ClearType](https://user-images.githubusercontent.com/15761310/149603149-1ffcb042-fac3-490f-98a9-bd4a4ef949f8.png)

**Comment by mrexodia** [comment]
But that's strange, why would it look normal with drawText and not with the QTextLayout I'm using? When I was reading the code they are also using this internally.
