### ISSUE TITLE
Search constant not found

### ISSUE THREAD

**Issue by idigger** [x64dbg/x64dbg#2824]
### Operating System

Windows 10 64bit

### x64dbg Version

Jan 19 2022

### Describe the issue

 Search constant 8762 not found 

### Steps to reproduce

004032E1 | 66:817D A2 6287          | cmp word ptr ss:[ebp-5E],8762  <<-- Search constant 8762 not found 
004032E7 | 75 08                            | jne xxx.4032F1

**Comment by SirHerpDerp** [comment]
Please write in english next time so everybody can understand you without using a translator.

When using asmjit it seems like you have to declare if a number is hex or dec.
Try `cmp word ptr ss:[ebp-0x5E], 8762` or `cmp word ptr ss:[ebp-0x5E], 0x8762` if both numbers should be interpreted as hex.

**Comment by mrexodia** [comment]
Chinese is also fine for me ^^

I tested locally, will have to look into why the constant isn't found. Likely some conversion issue.

**Comment by mrexodia** [comment]
When looking for `0xffffffffffff8762`
