### ISSUE TITLE
How to set a breakpoint after another breakpoint triggered?

### ISSUE THREAD

**Issue by Champollion9012** [x64dbg/x64dbg#2825]
### Operating System

Windows 10

### x64dbg Version

Jul 29 2021

### Describe the issue

I debug multi-thread IM program that will receive and send many messages.
If I'd like to capture some event after typing some words,  than setting up a breakpoint at send function. But doing this, we would got a lot of other messages.
Thus, I try to set up a breakpoint when typing, then enable the breakpoint at send function.
Then, I could get the message what I typed more accurately. Right?

So, I want to know how to set a breakpoint after another breakpoint triggered automatically?
Maybe some features like conditional breakpoint could help me?
I don't want always manually it .

### Steps to reproduce

1. setting up a bp at typing related function and enable it.
2. setting up a bp at send function (network function) but disable it.
3. When first bp was triggered, I need enable manually the second bp to capture the data what I typed.

**Comment by torusrxxx** [comment]
You can specify a breakpoint command that does whatever you want in the edit conditional breakpoint dialog.

**Comment by torusrxxx** [comment]
For example, set breakpoint command to "bpe LabelOfAnotherBreakpoint" and breakpoint command condition to "1" will enable another breakpoint once this breakpoint is triggered.
