### ISSUE TITLE
Clarify if XMM / YMM registers are available for logging

### ISSUE THREAD

**Issue by clarkewd** [x64dbg/x64dbg#2826]
### Feature type

Other

### Describe the feature

I see in December 2018 that x64dbg [did not support xmm and fpu registers](https://forum.tuts4you.com/topic/40998-how-to-log-xmm0-register-when-tracing/) because "in x64dbg all values are 32/64 bit integers"...

But on the [String Formatting documentation page](https://help.x64dbg.com/en/latest/introduction/Formatting.html) I see information about printing XMM and YMM with examples:

> `f` - single precision floating-point pointer or register: ... It can also accept XMM and YMM registers: {f:XMM0} prints the single precision floating-point number at XMM0 bit 31:0, {f:YMM7[7]} prints the single precision floating-point number at YMM7 bit 255:224.

When I try this format, either on the command input area in x64dbg or in a conditional breakpoint logging condition, it does not work. It's OK if this feature is not available but it might be good to clarify this in the documentation.

**Comment by mrexodia** [comment]
The XMM feature was added by @torusrxxx recently. Are you using the latest version?

**Comment by clarkewd** [comment]
Ah, ok. I just had luck getting it to work. Here's what I was unclear about: Running `rax` in the command box works, but running `xmm0` gives an error.

So basically #2807 allows for using `log {f:XMM0}` in the command box, using `{f:XMM0}` for the breakpoint log. But anything else, for example {x:XMM0} (or even just XMM0 as an expression) will not work.

The new "support for XMM and YMM registers" is sort of a special case for allowing to print out their floating point values without having to rewrite x64dbg to handle > 64-bits variables etc.

This is great. Thanks @torusrxxx.  I just didn't understand that at first.

**Comment by mrexodia** [comment]
If you have some suggestion to clarify the documentation an edit would be appreciated! You can click the “Edit on Github” and you should send a PR automatically
