### ISSUE TITLE
Stack Window not showing ASCII characters

### ISSUE THREAD

**Issue by jinhaochan** [x64dbg/x64dbg#2835]
### Operating System

Windows 10 64 bit OS build 19042.1526

### x64dbg Version

Jan 21 2022

### Describe the issue

In the stack view, it only shows unicode strings, but does not show ASCII strings

Unicode strings being shown

![image](https://user-images.githubusercontent.com/7328587/153796044-c1e9e57c-5fd7-453b-a93d-e1bf0b6051bf.png)

ASCII strings not being shown

![image](https://user-images.githubusercontent.com/7328587/153796102-c4aaf813-2a6f-429b-8dc4-6b955d4e70e1.png)

### Steps to reproduce

1. https://github.com/jinhaochan/eCRE/blob/main/issue.exe (Will be removed once bug is fixed or addressed)
2. Load the binary into x32dbg 
3. Pause execution when the dialog box appears 

![image](https://user-images.githubusercontent.com/7328587/153797096-a3f40547-ef87-4d0d-9c3c-74113b96ccb0.png)

4. Switch to the main thread (Threads -> Double click "Main")
4. On the 5th Stack frame is where the Unicode strings appears

![image](https://user-images.githubusercontent.com/7328587/153797202-a3ed3331-4f33-4ae6-93f0-d32f697452d0.png)

5. On the 6th stack frame is where the ASCII strings are supposed to appear

![image](https://user-images.githubusercontent.com/7328587/153797234-344bccc3-bbdc-498d-b278-48edf3d043c9.png)

**Comment by user18x** [comment]
**Operating System**
Windows 10 64 bit 21H2

**x64dbg Version**
snapshot_2022-02-14_23-40.zip

Same by me!

I've seen a video from 2020 and the crackme is from 2020 too.

In the video it looks like:
![original](https://user-images.githubusercontent.com/37771000/155108145-4840d3f6-7c79-4dce-8c0d-ccc2e87c5d0f.png)

If i try with x64dbg it looks like this:
![mine](https://user-images.githubusercontent.com/37771000/155108449-87edb09c-0526-47e1-bbc6-197c71794c46.jpg)

So the problem doesn't exist in a earlier  version!
In a earlier video (from this season) it is showing to download snapshot_2020_01_21_20-41.zip.

**Comment by mrexodia** [comment]
Users from Russia and China have a different string detection algorithm. Perhaps this is why it doesn’t work…

**Comment by jinhaochan** [comment]
I’m neither from Russia nor China, but from South East Asia. Have you tried running this program on your non-Russian, non-China machine to see if it’s reproducible?

**Comment by user18x** [comment]
@mrexodia
I'm from germany!
The video is from a guy of asia.
But why is the algorithm detection different?
Can it be fixed?

**Comment by user18x** [comment]
> I’m sure it can be fixed. I’ll get to it when I have time/motivation to do so. If you want to give it a try yourself the function is called `isasciistring`

With this statement you shoot yourself an own goal!
With this motivation this tool will not become # 1.

PS: Will test x64dbg again when it's fixed. **Thanks for help!**
PPS: Back to Topic!

**Comment by user18x** [comment]
Hmm, tried with version snapshot_2022-03-02_15-55.zip and last one snapshot_2022-03-26_14-14.zip, the issue is the same, not fixed.
My result is the same like my screenshot above is showing.
