### ISSUE TITLE
Relative Paths for x96dbg.ini

### ISSUE THREAD

**Issue by MrMendelli** [x64dbg/x64dbg#2838]
### Feature type

Quality of life

### Describe the feature

I would like to be able to use relative paths in the launcher settings file to point to `x32dbg.exe` and `x64dbg.exe` respectively. I've already tried editing the file manually and assuming my implementation _(`.\`/`\`/`/`)_ isn't wrong, the launcher seemingly refuses the use of relative paths.

**Comment by mrexodia** [comment]
This should be _relatively_ (heh) easy to implement. The relevant code is in: https://github.com/x64dbg/x64dbg/blob/development/src/launcher/x64dbg_launcher.cpp#L454

**Comment by SwapnilKumbhar** [comment]
Is there any ongoing work on this issue? I would be happy to contribute if not!

**Comment by mrexodia** [comment]
Yeah you’re welcome to! Be sure to check out the guide on how to build x64dbg. It’s a bit involved unfortunately… https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project

**Comment by SwapnilKumbhar** [comment]
Thanks for the link. I'll give it a shot!
