### ISSUE TITLE
Script waits too long or freezes while running.

### ISSUE THREAD

**Issue by qwertyu131** [x64dbg/x64dbg#2843]
### Operating System

Windows 10  21H2 19044.1526

### x64dbg Version

snapshot_2022-03-02_15-55

### Describe the issue

It's part of the script I'm running, it contains about 1000 parts like this.

findasm "call 0x3E40000", 0x981000, 0x217000
mov $size, $result
mov $count, 0
find_continued_360:
cmp $count, $size
je find_ended_360
cmp 1:[ref.addr($count) + 5], 0x90
je continued1_360
mov eip, ref.addr($count) - 1
asm eip, "call [0xAF4898]"
jmp continued2_360
continued1_360:
mov eip, ref.addr($count)
asm eip, "call [0xAF4898]"
continued2_360:
inc $count
jmp find_continued_360
find_ended_360:

### Steps to reproduce

1. When you run the script step by step, it does not freeze. However, when I run the script it freezes.
2. 
3.

**Comment by qwertyu131** [comment]
I solved it.

**Comment by mrexodia** [comment]
And how did you solve it?

**Comment by qwertyu131** [comment]
I shared it here my friend.
https://github.com/qwertyu131/x64dbg/commit/94a459151559ca0cd9b96a835cbbfc07aa27e967

**Comment by mrexodia** [comment]
Thanks! Maybe you could open a pull request?

**Comment by qwertyu131** [comment]
https://github.com/x64dbg/x64dbg/pull/2844
I opened the pull request.
