### ISSUE TITLE
Can "keep size" in the lower left corner of binary editing dialog box be selected by default?

### ISSUE THREAD

**Issue by KJBYG** [x64dbg/x64dbg#2847]
### Feature type

Quality of life

### Describe the feature

Can "keep size" in the lower left corner of binary editing dialog box be selected by default?
![2022-03-14_180645](https://user-images.githubusercontent.com/43238453/158150897-db5ecad8-0912-473d-9c4b-93fbcf52c874.jpg)

**Comment by mrexodia** [comment]
It should remember your selection.

**Comment by KJBYG** [comment]
您好！您的邮件我已收到，祝您每一天都开开心心，快快乐乐！

**Comment by KJBYG** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x64dbg/x64dbg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x64dbg/x64dbg] Can "keep size" in the lower left corner of binary editing dialog box be selected by default? (Issue #2847)





 
It should remember your selection.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KJBYG** [comment]
If I select it, the next time I open the dialog box, it is still unchecked, that is, the user's choice here cannot be saved.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x64dbg/x64dbg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x64dbg/x64dbg] Can "keep size" in the lower left corner of binary editing dialog box be selected by default? (Issue #2847)





 
It should remember your selection.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by torusrxxx** [comment]
fixed in #2850

**Comment by KJBYG** [comment]
Remember my choice? I chose it in the dump and went into binary editing, and I think the length should be the same by default at this time.




---Original---
From: "Duncan ***@***.***&gt;
Date: Mon, Mar 14, 2022 19:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [x64dbg/x64dbg] Can "keep size" in the lower left corner ofbinary editing dialog box be selected by default? (Issue #2847)




 
It should remember your selection.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
