### ISSUE TITLE
Can't patch in *.exe

### ISSUE THREAD

**Issue by kivancxxx** [x64dbg/x64dbg#2854]
### Feature type

Debugging

### Describe the feature

I open the *.exe file in x64dbg. If I try to patch the file, it forces me to save in *.dll file. How can I patch it in *.exe extention?

Thank you...

**Comment by mrexodia** [comment]
Can you show a video of what happens? There is nothing forcing the extension

**Comment by kivancxxx** [comment]
I open system mechanic *.exe file in x64dbg. I right click x64dbg's CPU editor: Search for --> All Modules --> String references. Then in the Search field I type WpadExpirationDays. I double click on it, scroll up a little and change JNE instruction to JE (on the title it writes "winhttp.dll"). When I save it as *.exe, the file doesn't open.

**Comment by mrexodia** [comment]
I guess you are patching winhttp.dll and that should be a windows component so you can’t patch that on disk.
