### ISSUE TITLE
Some applications don't open in x64dbg

### ISSUE THREAD

**Issue by kivancxxx** [x64dbg/x64dbg#2855]
### Feature type

Debugging

### Describe the feature

I can't get to open Auslogics BoostSpeed and Auslogics Registry Cleaner. Should I wait for the new version of x64dbg?

Thank you.

**Comment by mrfearless** [comment]
Did you check to see if they are .net applications? For example you can use CFF Explorer to open the exe and verify if its an PE/PE64 or .net executable. If it is none of them then perhaps its a Microsoft store app or something else. x64dbg will only support PE/PE64 exe and dll's. Also you may need to check there is no anti-debug capabilities of the target your trying to open, or intervention by third parties: Anti-virus, self protecting services etc
