### ISSUE TITLE
GitHub Releases Missing Compiled Binary Package

### ISSUE THREAD

**Issue by utkonos** [x64dbg/x64dbg#2856]
### Operating System

N/A

### x64dbg Version

N/A

### Describe the issue

The package with compiled binaries which use to appear on the GitHub releases page has been missing for a couple of releases. I am not sure if this is intentional or if there is a problem in the automated build and release system. The packages are still appearing on the Sourceforge distribution page, however.

### Steps to reproduce

1. Open this page: https://github.com/x64dbg/x64dbg/releases
2. The zip package with compiled binaries is missing.

**Comment by mrexodia** [comment]
Thanks. I’m aware of the issue and it seems to be a change in GitHub’s API that breaks the release tool I’m using. When I find some time I’ll use GitHub’s official tool to upload releases

**Comment by mrexodia** [comment]
Should be fixed now!
