### ISSUE TITLE
Make triggered memory breakpoint address available in expressions

### ISSUE THREAD

**Issue by VelocityRa** [x64dbg/x64dbg#2861]
### Description

It's not already available is it? I couldn't find anything in docs.

My use case is that there's a large area of function pointers that I have put a read bp on and I want to log which ones are hit.

Could be exposed as a complex type here: https://help.x64dbg.com/en/latest/introduction/Formatting.html#complex-type

### Feature type

Debugging

**Comment by mrexodia** [comment]
It might be available in the exception expression functions. https://help.x64dbg.com/en/latest/introduction/Expression-functions.html#exceptions

**Comment by VelocityRa** [comment]
Unrelated bug, I selected a range ie. 0x04592DA0-0x04592FAC, right clicked Breakpoint -> Memory, Read -> Restore on Hit and it put a breakpoint at 0x04480000 of size (0x6C0000) which is about 1MB before the one I selected.
What am I doing wrong?
I know these probably use page access violation exceptions to work but why go 1MB before? And I would expect that implementation detail (only being able to break on page boundaries)) to be transparent from the user anyway.
It's a 32-bit executable if that matters.

**Comment by VelocityRa** [comment]
Also regarding what you said, I tested `ex.addr()` and I don't think it returns the access addr, at least not all the time.
Anyway I should first figure out the above issue.

**Comment by VelocityRa** [comment]
Bump?

**Comment by mrexodia** [comment]
I updated the documentation for you a while ago:

> Last exception information, zero if index is out of bounds. For access violations or memory breakpoints `ex.info(1)` contains the address of the accessed memory (see [EXCEPTION_RECORD.ExceptionInformation](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-exception_record) for details).

**Comment by mrexodia** [comment]
Also the variable `$breakpointexceptionaddress` is exactly what you're looking for. It's set to the address that triggered the exception.
