### ISSUE TITLE
Wrong branch was compiled

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [x64dbg/x64dbg#2862]
### Operating System

all

### x64dbg Version

snapshot

### Describe the issue

![1](https://user-images.githubusercontent.com/15037766/162614678-a8ae7e60-39cc-4c09-b8c2-46204044094d.png)

### Steps to reproduce

1. nothing

**Comment by mrexodia** [comment]
There is no issue. I just use the release from a snapshot a few years ago. The files built are from “development”
