### ISSUE TITLE
Requesting Disassembly capability for MSDOS file types: .sys .com and .exe

### ISSUE THREAD

**Issue by Programmer96** [x64dbg/x64dbg#2864]
### Feature type

Debugging

### Describe the feature

Why? I'm glad you ask; well, I want to have fun on boring weekends, I like to disassemble old games and apps, to check how they were made, and learn about programing techniques and program structure on low RAM environments, XMS handling and so on.

Sincerely, me.

**Comment by mrexodia** [comment]
This is out of scope for x64dbg. You can use Ghidra/Cutter/IDA and try to debug DOSBox or similar.
