### ISSUE TITLE
 "bp  mod.fromname("user32") + 90B0"  doesn't work

### ISSUE THREAD

**Issue by barluc** [x64dbg/x64dbg#2867]
### Operating System

windows 10 x64

### x64dbg Version

Mar 26 2022

### Describe the issue

 mod.fromname("user32") 
75CA0000 (1976172544d) user32.75CA0000

bp  mod.fromname("user32") + 90B0
invalid address :  "mod.fromname(user32)+90B0"

i know there other way to achiever the same effect(bp  user32:0+ 90B0).
but i wan't to known why "bp  mod.fromname("user32") + 90B0" doesn't work,it's bug?

### Steps to reproduce

bp  mod.fromname("user32") + 90B0
invalid address :  "mod.fromname(user32)+90B0"

**Comment by mrexodia** [comment]
This is because of escaping (which is not properly documented, just explaining how it works):

```
bp "mod.fromname(\"user32\") + 90B0"
bp mod.fromname(\"user32\") + 90B0
```

Those two forms should work.

**Comment by barluc** [comment]
i see,thanks
