### ISSUE TITLE
x64 debug not breaking at dll Entry Point - Windows ARM.

### ISSUE THREAD

**Issue by saptarshi-laha** [x64dbg/x64dbg#2869]
When using the custom DLL Loader by x64dbg/rundll32.exe the entrypoint of the DLL is never hit.

When using rundll32.exe, we can’t change the commandline before it hits the entrypoint of rundll32.exe and thus adding parameters is impossible.

is this expected? Since there is no issues in x86/x64 versions of Windows.

**Comment by mrexodia** [comment]
This is a bug in the syscall emulation implementation. Microsoft is aware, but it hasn't been fixed yet I think. You can use this workaround: https://github.com/x64dbg/TitanEngine/commit/7a102faf0b0203d78f698935c3315da427e9a318
