### ISSUE TITLE
Error for any file

### ISSUE THREAD

**Issue by 3xp0rt** [x64dbg/x64dbg#2873]
### Operating System

Windows 7 64bit, Build 7601

### x64dbg Version

May 14 2022

### Describe the issue

I am getting an error for any file, both for x32dbg and x64dbg

### Attachments

![VirtualBoxVM](https://user-images.githubusercontent.com/61662492/168430309-22e7a749-61b3-4aa5-8112-4fd6ce55c4eb.png)

**Comment by mrexodia** [comment]
Works fine for me, what file did you open exactly?
