### ISSUE TITLE
Can't open an exe file in x32dbg

### ISSUE THREAD

**Issue by shoham-z** [x64dbg/x64dbg#2874]
### Operating System

windows 10 64 bit, build 21h2

### x64dbg Version

Apr 11 2022

### Describe the issue

Hello guys, I can't open an exe file in x32dbg, it's probably a 32 bit file, all i know is that x32dbg tries to load everything but fails.
Btw i have tried to do it in a virtual machine.
![Screenshot from 2022-05-17 20-02-49](https://user-images.githubusercontent.com/58585812/168870270-e3351ef0-5039-40d5-8025-afc005ff52e1.png)

### Steps to reproduce

1. Open a virtual machine
2. Launch x32dbg
3. Try to open exe file

**Comment by mrexodia** [comment]
Can you share the executable? Everything works fine for me.

**Comment by shoham-z** [comment]
I uploaded the executable compress, because github won't let me.
I had a similar issue with windbg, where the solution was to install missing DLLs like VCRUNTIME140.dll from microsoft.
I should also mention that I am using the vm specifically for reversing. 

[HelloWorld.zip](https://github.com/x64dbg/x64dbg/files/8710483/HelloWorld.zip)

**Comment by mrexodia** [comment]
Initially I missed it, but it says `Process stopped with exit code 0xC0000135` which is indeed `STATUS_DLL_NOT_FOUND` so nothing x64dbg can do about it.
