### ISSUE TITLE
Memory breakpoint bug?

### ISSUE THREAD

**Issue by ziv6** [x64dbg/x64dbg#2875]
**Memory breakpoint: 
why set  at 019C80D8 
(read / wite ) at 01980000 ??**

Hardware breakpoint:  is right

Memory breakpoint at 019C80D8 set!

Memory breakpoint (write) at 01980000 (019C1430)!

Memory breakpoint at 019C80D8 set!

Memory breakpoint disabled!

Delete memory breakpoint failed: 01980000 (RemoveMemoryBPX)

No memory breakpoints to delete!

Memory breakpoint at 019C80D8 set!

Memory breakpoint (read) at 01980000 (01A330C4)!

Memory breakpoint at 019C80D8 set!

Memory breakpoint (read/write/execute) at 01980000 (01A330C4)!

Hardware breakpoint at 019C80D8 set!

Hardware breakpoint (dword, read/write) at 019C80D8!

Hardware breakpoint (dword, read/write) at 019C80D8!

Hardware breakpoint disabled!

**Comment by torusrxxx** [comment]
Memory breakpoint only supports 4KB memory page, not memory address range anywhere and any size. Use a hardware breakpoint instead.
