### ISSUE TITLE
Hi-DPI scaling issue

### ISSUE THREAD

**Issue by shatyuka** [x64dbg/x64dbg#2876]
### Operating System

Windows 11 64bit, build 22000

### x64dbg Version

May 14 2022

### Describe the issue

Toolbars and many other controls are not scaled correctly.
Also, tweaking the program's compatibility configuration doesn't help.

Commit a031e03.

### Steps to reproduce

Simply run x64dbg

### Attachments

What it looks like for version 2022.05.14 at 200% scale.
![20220514](https://user-images.githubusercontent.com/31368738/170587794-0046c232-1a82-46ec-ac8d-2c8f381792bc.png)

And for old version
![20220411](https://user-images.githubusercontent.com/31368738/170587812-012efac8-930c-41ba-8758-1063ee5437a4.png)

**Comment by eladkarako** [comment]
@shatyuka, can you check if the patched exe  
in https://github.com/x64dbg/x64dbg/issues/2877  
makes any difference?

**Comment by shatyuka** [comment]
> @shatyuka, can you check if the patched exe in #2877 makes any difference?

Definitely not. As I mentioned before, tweaking the program's compatibility configuration doesn't help.
It's because the author removed the code related to hi-dpi scaling. Have a look at commit a031e03.

The program claims that it will handle UI scaling instead of the OS, but doesn't do it well. For icons or some custom controls, the sizes are not scaled.
For the blurry launcher, it's another issue.

**Comment by eladkarako** [comment]
> launcher

ooppps.. yep, I've only patched the launcher.  

> tweaking the program's compatibility configuration doesn't help.

..you might be right there.


<details><summary>anyway,</summary>

after I've patched it all,  
there is no apparent change, as far as I can tell,  
it seems that the programs already handles DPI awareness properly  
(might need to adjust the UI itself to scale correctly though).


https://github.com/x64dbg/x64dbg/issues/2877#issuecomment-1140466026 (under notes),  
has two variation of the patched program.  
if you wish, you can check to see if there is any visual difference on your end,  
but my guess is you won't see any difference.  

the GDI variation there might help though,  
it is meant for old programs, and the result would be a bit blurry,  
but fix-point anchored controls (such as toolbars) <strong>would look slightly larger</strong>.

</details>

**Comment by fyozt** [comment]
![image](https://user-images.githubusercontent.com/33294277/171020219-26cdd2a9-4302-4b0f-a372-4ab7bad4ad17.png)
There are indeed DPI issues; previous versions didn't have such issues.

**Comment by mrexodia** [comment]
Just set the environment variable as a workaround

**Comment by gmh5225** [comment]
you can use `SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_SYSTEM_AWARE);` on Win10 above 1703
Minimum supported client | Windows 10, version 1703 [desktop apps only]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext

**Comment by shatyuka** [comment]
> you can use `SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_SYSTEM_AWARE);` on Win10 above 1703 Minimum supported client | Windows 10, version 1703 [desktop apps only] https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext

https://github.com/x64dbg/x64dbg/commit/a031e037a4a57e3efd19f7784ef6580a871da76d#diff-d47c61b3cf0457a765cc4cf7d908d6e5457babe427cfd311d6b485bd1aca4ecfL79

**Comment by gmh5225** [comment]
`QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling)` does not have the same effect as `SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_SYSTEM_AWARE)`.
on my machine, QT's API causes lagging, but WINAPI's do not.

**Comment by mrexodia** [comment]
I was reading about it a while back and supposedly the Qt fix isn’t proper 🤷‍♂️

**Comment by gmh5225** [comment]
PR https://github.com/x64dbg/x64dbg/pull/2881

**Comment by shatyuka** [comment]
> PR #2881

Have you tested it in-person? I don't think it's useful because x64dbg is already dpi awareness. Have a look at discussion above.

**Comment by mrexodia** [comment]
I cannot test in person, for me everything works fine in every scaling mode without this flag last time I tested. It only reproduces on certain laptop screens

**Comment by shatyuka** [comment]
> I cannot test in person, for me everything works fine in every scaling mode without this flag last time I tested. It only reproduces on certain laptop screens

Sorry, but it's a reply to @gmh5225.
However, I just tested it on Windows 10 20H2 on vmware, this problem still exists (200% scaling).

**Comment by gmh5225** [comment]
yes. It works for me.
you can download this [version](https://ci.appveyor.com/api/buildjobs/w3ycdh29vhiq59sd/artifacts/x64dbg-Branch_fix_dpi-43781518.zip) to test.

**Comment by fyozt** [comment]
> yes. It works for me. you can download this [version](https://ci.appveyor.com/api/buildjobs/w3ycdh29vhiq59sd/artifacts/x64dbg-Branch_fix_dpi-43781518.zip) to test.

still ineffective；It is recommended to test DPI 175%

**Comment by gmh5225** [comment]
mine is 150% (3840 x 2160)

**Comment by gmh5225** [comment]
> > yes. It works for me. you can download this [version](https://ci.appveyor.com/api/buildjobs/w3ycdh29vhiq59sd/artifacts/x64dbg-Branch_fix_dpi-43781518.zip) to test.
> 
> still ineffective；It is recommended to test DPI 175%

175% is also ok for me

**Comment by fyozt** [comment]
The main problem is the icon column; everything else is fine.

**Comment by gmh5225** [comment]
> The main problem is the icon column; everything else is fine.

It doesn't look like you and @shatyuka have the same problem.

**Comment by shatyuka** [comment]
> > The main problem is the icon column; everything else is fine.
> 
> It doesn't look like you and @shatyuka have the same problem.

Definately the save problem.

**Comment by fyozt** [comment]
> > The main problem is the icon column; everything else is fine.
> 
> It doesn't look like you and @shatyuka have the same problem.

Should be the same problem; there was no such problem in previous versions.

**Comment by mrexodia** [comment]
So could someone do before/after screenshots with the build from the pull request? https://github.com/x64dbg/x64dbg/pull/2881

Thanks @gmh5225 for putting in the work! I’m happy to merge it, but I didn’t reproduce it yet.

**Comment by shatyuka** [comment]
> So could someone do before/after screenshots with the build from the pull request? https://github.com/x64dbg/x64dbg/pull/2881
> 
> Thanks @gmh5225 for putting in the work! I’m happy to merge it, but I didn’t reproduce it yet.

@mrexodia I have tested, it doesn't work.
I think you should just simply add the lines deleted before.

**Comment by mrexodia** [comment]
I did some tests, for me either options looks horrible (1080p, 175% scaling which is the max Windows offers me):

This is with `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` (how it was previously):

![image](https://user-images.githubusercontent.com/2458265/173232196-048db850-b0c8-4283-bb75-6f6ce1259d54.png)

The latest release:

![image](https://user-images.githubusercontent.com/2458265/173232219-d8e7e1cb-820d-4369-9d4f-a20ab2e5a026.png)

For me they both look horrible. The main thing I noticed is that the native controls aren't scaling super nicely (toolbar and status bar) but the tables are looking much better now (there is glitching with scaling enabled).

**Comment by mrexodia** [comment]
I think that #2881 is almost the best of both worlds. The only problem is the toolbar icons being very small, I have to do some more testing though...
