### ISSUE TITLE
DPI awareness (just embedded manifest edit, no code change needed!)

### ISSUE THREAD

**Issue by eladkarako** [x64dbg/x64dbg#2877]
### Feature type

Quality of life

### Describe the feature

there are few dialogs that can be crystal clear in larger screens (currently slightly blurry due to rendering in a compatible mode).
<img src="https://user-images.githubusercontent.com/415238/170834052-b58af9da-3af4-4181-862d-447995f5b387.png" title="can right click, open in new tab for full resolution." />

<details><summary>main program (I can not notice any visible change)</summary>

note: I havn't noticed any change in the main program,  
text and such looks the same,  
since you probably render it yourself.  

it mostly just fixes dialogs, pop-ups and windows assigned by the OS.
although, technically everything might benefit from it.

<hr/>

w/o (normal)  

<img width="972" title="main w/o" src="https://user-images.githubusercontent.com/415238/170834126-453e75e8-25ce-4c8a-b7dd-370700cf0159.png" />  

with DPI awareness

<img width="972" alt="main w/" src="https://user-images.githubusercontent.com/415238/170834149-90d1dd31-c6e3-409f-887d-786da15f4e7e.png" />

</details>

<hr/>

I've patched the exe with https://github.com/eladkarako/manifest/
https://github.com/eladkarako/manifest/blob/master/example_manifests/generic.manifest#L11-L12

<hr/>

it might help with other issues such as  

- https://github.com/x64dbg/x64dbg/issues/2876 . edit: apparently <a href="https://github.com/x64dbg/x64dbg/issues/2876#issuecomment-1140377018">not</a>.
- https://github.com/x64dbg/x64dbg/issues/2432
- https://github.com/x64dbg/x64dbg/issues/1664

<hr/>

here is a pre-patched exe (https://github.com/x64dbg/x64dbg/releases/tag/snapshot `snapshot_2022-05-25_18-42.zip`:  

- <a href="https://github.com/x64dbg/x64dbg/files/8791487/x96dbg.manifest_patched.exe.zip">x96dbg.manifest_patched.exe.zip</a>. <sub><a href="https://www.virustotal.com/gui/file/02f002a2a35a091e41a6fd5f3fc90e5ac235161c9f716ceff3701dcb687befd2?nocache=1">virustotal</a></sub>

- <a href="https://github.com/x64dbg/x64dbg/files/8791488/x96dbg.original.exe.zip">x96dbg.original.exe.zip</a> (for reference).

<hr/>

manifest:

<details><summary>existing (missing DPI awareness)</summary>

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel
          level="asInvoker"
          uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <!--The ID below indicates application support for Windows Vista --> 
        <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
      <!--The ID below indicates application support for Windows 7 --> 
        <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/> 
      <!--The ID below indicates application support for Windows 8 --> 
        <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/> 
      <!--The ID below indicates application support for Windows 8.1 --> 
        <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/> 
      <!--The ID below indicates application support for Windows 10 --> 
        <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/> 
    </application> 
  </compatibility>
</assembly>
```

</details>

<details><summary>modified <sub>(w/ DPI awareness, along with long path awareness and new segmented heap (allows you to load about ~1GB file with almost no lags)</sub></summary>

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <dependency optional="yes"> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*" /> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings> <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                     </windowsSettings> 
     <windowsSettings> <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness> </windowsSettings> 
     <windowsSettings> <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                   </windowsSettings> 
     <windowsSettings> <heapType      xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                 </windowsSettings> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" /> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" /> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" /> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" /> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" /> 
    </application> 
  </compatibility> 
</assembly> 
 
```

</details>

**Comment by mrexodia** [comment]
Thanks, I’ll take a look at the manifest. It should be very easy to modify the embedded manifest, but I don’t have such a display so it’s impossible for me to test properly…

**Comment by eladkarako** [comment]
> I don’t have such a display

works on standard screens,  
with larger than 100% DPI.  

values such as 175% works best for blurry-tests,  
due to "non-even pixel-scale" multiplication.

<img width="584" alt="2022-05-29_000839" src="https://user-images.githubusercontent.com/415238/170842916-8cc75ff0-95f1-49f1-8dd8-17887425e055.png">

**Comment by eladkarako** [comment]
sorry,  
I've just realized I've only tested a modified `x96dbg.exe` (the launcher),  
which makes sense that I didn't noticed any change in the main program.. 🤦‍♂️

yet,  
even after I've modified `x64dbg.exe`, `x64dbg.dll`, `x64gui.dll`,  
and `x32dbg.exe`, `x32dbg.dll`, and `x32gui.dll`,  
I saw no change.  

which means <strong>the program already handles DPI awareness properly!</strong>  
I assume the QT engine <a href="https://doc.qt.io/qt-5/highdpi.html">handles it somehow</a>,  
so no manifest change is needed (..maybe just for the launcher),  
anyway I'm closing this... :|

<hr/>

<details><summary>notes</summary>

since I've already manifest-patch the program for testing,  
I'll attached it here for reference.


```txt
/
|   x96dbg.exe
|   
+---x32
|       x32dbg.dll
|       x32dbg.exe
|       x32gui.dll
|       
\---x64
        x64dbg.dll
        x64dbg.exe
        x64gui.dll
```


- <a href="https://github.com/x64dbg/x64dbg/files/8793506/snapshot_2022-05-25_18-42__original.zip">snapshot_2022-05-25_18-42__original.zip</a>

- <a href="https://github.com/x64dbg/x64dbg/files/8793500/snapshot_2022-05-25_18-42__manifest_patched_permonitorv2.zip">snapshot_2022-05-25_18-42__manifest_patched_permonitorv2.zip</a>

- <a href="https://github.com/x64dbg/x64dbg/files/8793505/snapshot_2022-05-25_18-42__manifest_patched_permonitorv2%2Bgdiscaling.zip">snapshot_2022-05-25_18-42__manifest_patched_permonitorv2+gdiscaling.zip</a>

<hr/>

I see no difference between the original or the one patched with 
https://github.com/eladkarako/manifest/blob/master/example_manifests/generic.manifest#L11-L12  
which should means the highest level of DPI awareness (per-screen, v2) is already effective.

<img width="972" alt="original" src="https://user-images.githubusercontent.com/415238/170875553-7d04ab1f-c860-4ac0-a236-29e44270f8d8.png">

<img width="972" alt="permonitorv2" src="https://user-images.githubusercontent.com/415238/170875582-01b93b18-5006-44f6-a0ab-a0422ebb2243.png">

<hr/>

the GDI-scaling addition  
https://github.com/eladkarako/manifest/blob/master/example_manifests/generic_with_info.manifest#L28  
is meant for old programs,  
it helps them scale correctly without the controls glitching around,  
it also makes fixed-point anchored controlled such as toolbars scale correctly to look larger,  
it does however not as sharp as you'll want your program to be,  
mostly "free" text is fine, but labels within controls are a bit blurry.

if you're wondering,  
this is how it would look:  

<img width="972" alt="permonitorv2+gdiscale" src="https://user-images.githubusercontent.com/415238/170875781-efc46210-57e3-4f44-88a3-cc1601d47d21.png">


</details>
