### ISSUE TITLE
auto DBH at inject

### ISSUE THREAD

**Issue by uragan1987** [x64dbg/x64dbg#2879]
### Feature type

Debugging

### Describe the feature

At starting process with x32dbg, hide from debugging works fine
But at inject to a running process, i have always to call "dbh" to hide it

Maybe put a checkbox at settings, to get it auto hide?
or is there a plugin for this?

**Comment by mrexodia** [comment]
You can use an init script.

**Comment by uragan1987** [comment]
what you mean with "init script"?
cant find any options about automatic load script at attach process.
"System BP Script" dont call it on attach
A Simple Script has to be called manualy on every attach

did i forgot an other method?

**Comment by mrexodia** [comment]
There is no more callbacks on attach because there is no pause thread anymore so there is no way to call the command before the program can notice.
