### ISSUE TITLE
utf8's bug

### ISSUE THREAD

**Issue by onesbug** [x64dbg/x64dbg#288]
hi,i am x64dbg's chinese user,my operate system's version and my character set are chinese.
i found x64dbg can't load all plugin(*.dp32,*dp64).
in x64_dbg.cpp:
    strcpy_s(plugindir, dir);
    PathAppendA(plugindir, "plugins");
    CreateDirectoryW(StringUtils::Utf8ToUtf16(plugindir).c_str(), 0);
    pluginload(plugindir);

plugindir is a ansi character set because "x64_dbg.cpp"'s save format is ansi.
and the variable "plugindir" doesn't change to utf8,so my all plugin can't be loaded.
hope can fix this bug.
									bughoho

**Comment by mrexodia** [comment]
working without problems here, I extracted x64dbg to `c:\z电脑坏了。电脑坏了。\x64\` (sorry if the chinese text is offensive, I just picked something random from the net). Both testplugin and multimate assembler are working without problems.

I will however change `PathAppendA` to a function that works properly with UTF-8 encoded strings.

Try extracting x64dbg to `C:\x64dbg`. Maybe the plugin you are trying to load is bad.

**Comment by onesbug** [comment]
i try it again,it's no problem indeed.the x64dbg's newer version filename 
from "x32_*.*" to "x32*.*" and the plugin can't import sdk's exe and dll.

Thank you for your reply.
btw.Is there any news about the x64dbg's StaticAnalysis?
that is greate and important features.i think that will be more useful than ollydbg.

**Comment by mrexodia** [comment]
`x32_dbg.exe` has no exports, so that shouldn't matter. `x32_dbg.dll` is still provided and has all exports forwarded to `x32dbg.dll`. See [this repository](https://github.com/x64dbg/x64dbg_forwarder).

Some analysis was done already, take a look at 112f70de (still in the `capstone` branch so there are no snapshots yet).
