### ISSUE TITLE
dis.mnemonic

### ISSUE THREAD

**Issue by leibso** [x64dbg/x64dbg#2882]
### Operating System

windows 10 1809

### x64dbg Version

May 25 2022

### Describe the issue

when i input command like  “dis.mnemonic ”  （or run as a script ）
i always got "Unknown command/expression: "dis.mnemonic("

why has this happen?  

### Steps to reproduce

1. input some command, like "dis.mnemonic("
2. got wrong, like "Unknown command/expression: "dis.mnemonic("

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/174460402-30df109d-5712-4eea-90f9-d547d49e0596.png)

**Comment by leibso** [comment]
thanks a lot
