### ISSUE TITLE
Folder/file path of the target to debug in the Window title?

### ISSUE THREAD

**Issue by ScyllaHide** [x64dbg/x64dbg#2885]
### Feature type

Quality of life

### Describe the feature

When debugging different versions of a program, it could be you lose track of which version you looking at. Showing the file path in the window title like IDA does could quickly help there.

**Comment by mrexodia** [comment]
There is not enough room in the Window title in my opinion.

**Comment by ScyllaHide** [comment]
on 1080p display:
IDA
https://postimg.cc/YvR3DVx7][img]https://i.postimg.cc/YvR3DVx7/ida.png
x64dbg
https://postimg.cc/9DCbpVZ1][img]https://i.postimg.cc/9DCbpVZ1/x64.png

not sure if the file path could be limited to only show the last 100 chars?! This would immensly help.

**Comment by mrexodia** [comment]
Yeah I guess it could be an option to show the full path.
