### ISSUE TITLE
Documentation contradicts about string functions

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#2888]
### Operating System

Chrome

### x64dbg Version

-

### Describe the issue

See below. I believe that the correct one is that registers are allowed, right? It worked for me in a conditional breakpoint.
https://help.x64dbg.com/en/latest/introduction/ConditionalBreakpoint.html
https://help.x64dbg.com/en/latest/introduction/Expression-functions.html

![image](https://user-images.githubusercontent.com/5781692/174649001-b24a58f9-8028-44ba-9f3e-183205d32782.png)

### Steps to reproduce

1. RTFM

**Comment by mrexodia** [comment]
There is no contradiction. It’s just that “utf8(…)” returns a string and not a number, so it’s not a valid expression.

The function strstr has the signature “strstr(string, string) -> number” so it’s a valid expression.

**Comment by justanotheranonymoususer** [comment]
OK, I think it's a bit confusing. Maybe it's clearer to say that utf8(…) is a valid expression but not a valid statement? Or, if you insist on calling the whole thing an expression, to say that it's a valid sub-expression? Otherwise it implies that utf8(rax) is just invalid.

**Comment by mrexodia** [comment]
What about “utf8(…) does not return a number so it cannot be used as a trace condition for example”?

**Comment by justanotheranonymoususer** [comment]
That sounds better. And also adding a couple of basic options will help. Something like `strstr(utf16(ECX), "foo")` is what I wanted to see but I had to find it on another page. Thanks.

**Comment by mrexodia** [comment]
Done. The example you asked for was already there (except it's utf8 instead of utf16)
