### ISSUE TITLE
x64dbg cannot pause debugger

### ISSUE THREAD

**Issue by NtQuery** [x64dbg/x64dbg#289]
snapshot_2015-04-17_03-42 with ScyllaHide

In ScyllaHide tick PEB->BeingDebugged and PEB->HeapFlags

x64dbg cannot be paused

**Comment by mrexodia** [comment]
Ah, great! I think that's the reason

**Comment by NtQuery** [comment]
? OllyDbg works fine... can still be paused....

**Comment by mrexodia** [comment]
X64dbg uses debugbreakex

**Comment by mrexodia** [comment]
Should be fixed now. I simply create a thread that does:
```
int3
ret
```

This doesn't use these weird UiDebugBreakin calls.

**Comment by NtQuery** [comment]
Ah ok... DebugBreakProcess creates a thread and calls DbgUiRemoteBreakin and this checks the PEB for debugging.
