### ISSUE TITLE
Text Size Error

### ISSUE THREAD

**Issue by Hao17** [x64dbg/x64dbg#2896]
### Operating System

Windows 10 64bit, build 19042

### x64dbg Version

Feb 14 2022

### Describe the issue

My laptop and monitor's resolution are 3840x2160 ("size of text" is 250%). When I set display mode to monitor only, x64dbg's text size is to big. However, x32dbg's text size is normal.

![image](https://user-images.githubusercontent.com/8477471/176406027-ed3e2129-e607-4adc-a9fe-317e7ecc8cbb.png)

### Steps to reproduce

Press win + P and set display mode to monitor only, then open x64dbg

**Comment by mrexodia** [comment]
#2876
