### ISSUE TITLE
Illegal Instruction 64bit x64dbg on lea rbx,qword ptr ds

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#290]
As mentioned the other night, I thought id best post it up:

64bit x64dbg debugging:

`000000013F261512 | 48 8D 1D 66 3C 00 00     | lea rbx,qword ptr ds:[<chartab>]        | ;Test64.Asm:308`
First chance exception on 000000013F261512 (C000001D, EXCEPTION_ILLEGAL_INSTRUCTION)!
![illegalinstruction lea rbx](https://cloud.githubusercontent.com/assets/1768766/7337242/041f49fa-ec1b-11e4-847a-181d32dcf56c.png)

**Comment by Nukem9** [comment]
*As a note, this happens because an INT3 is inserted in the middle of the command. (This isn't visible in the debugger, must be checked with an external memory viewer)

**Comment by mrexodia** [comment]
appears to be fixed
