### ISSUE TITLE
Terminated: debugging stopped x64dbg

### ISSUE THREAD

**Issue by dioutan** [x64dbg/x64dbg#2906]
Hello,

I am trying to run a file. Exe with x64dbg but as soon as I click on the "run" button the program terminates. Here below, are images of what happens,
I am a beginner, can you help me please?

version of x64dbg: 2022-06-22_00-12
Windows10

![Captureexe](https://user-images.githubusercontent.com/70212955/177500776-a10bb2b6-ac8f-474f-bf70-ff51fd6a6a07.JPG)

                                                                             ====>>>>

![capture_exe2](https://user-images.githubusercontent.com/70212955/177500774-e148a117-e45e-4f9c-9425-11966f1baf21.jpg)

**Comment by mrexodia** [comment]
Please show the full log

**Comment by dioutan** [comment]
Here is


![capture_exe3](https://user-images.githubusercontent.com/70212955/177551841-b8f3fbcf-7e44-49a1-91c4-f18b6a05ed31.jpg)


after run i get

![capture_exe2](https://user-images.githubusercontent.com/70212955/177552180-9fe7d7db-e8b6-4f8b-822c-fb86d3115616.jpg)

**Comment by mrexodia** [comment]
This is not the _Log_ tab

**Comment by dioutan** [comment]
sorry my log is here
![capture5_exe_jpg](https://user-images.githubusercontent.com/70212955/177563196-cc69ce58-f81b-4b41-99cc-df1b0e988375.png)

**Comment by mrexodia** [comment]
Perhaps the application has some anti-debug. I don’t think this is a bug in x64dbg.
