### ISSUE TITLE
For dark theme, white Icons to replace black icons

### ISSUE THREAD

**Issue by ScyllaHide** [x64dbg/x64dbg#2909]
### Operating System

Windows 10 Build 19041.1

### x64dbg Version

Jul 04 2022

### Describe the issue

When using the dark theme, 5 icons are to black to recognize them.

functions, strings, variables, trace and source.

### Steps to reproduce

I made them white.

### Attachments

![source_white](https://user-images.githubusercontent.com/12070561/178115222-795fd575-8ccf-4e91-9e6a-dd4ee260f432.png)
![trace_white](https://user-images.githubusercontent.com/12070561/178115223-ec3d1dee-f6d3-4d07-8d6c-56a6031c48bf.png)
![strings_white](https://user-images.githubusercontent.com/12070561/178115224-1afcf572-6a58-440b-8cf5-c588c08ce96b.png)
![variables_white](https://user-images.githubusercontent.com/12070561/178115225-b3703c7b-324a-4a98-8000-f455ba1c263d.png)
![functions_white](https://user-images.githubusercontent.com/12070561/178115226-49dbdf9e-7add-4047-b386-64ab89eebbf3.png)

**Comment by ScyllaHide** [comment]
Here you can download them: https://mega.nz/file/APowmCjT#dUPyckRGCwVmnjCphs2SEaokgMj_G1YMb0lNWiuT6mo

**Comment by mrexodia** [comment]
Thanks for the PNGs!

**Comment by mrexodia** [comment]
You can now replace every icon from your theme.

See https://github.com/x64dbg/x64dbg/commit/fdf8052d67e0c99a72d849db4a3a32f6e4ec0793

You need `index.theme`:

```ini
[Icon Theme]
Name=Dark
Comment=Dark icon theme
Directories=icons
Inherits=Default

[icons]
Size=16
Type=Scalable
```

And then you can make `icons/source.png` which will override the default.

**Comment by ScyllaHide** [comment]
This is awsome! i will add it to the theme: https://github.com/ScyllaHide/X64dbg_Acid_Lime_Theme_Remixed
