### ISSUE TITLE
Show length of functions?

### ISSUE THREAD

**Issue by ScyllaHide** [x64dbg/x64dbg#2915]
### Feature type

Quality of life, Debugging

### Describe the feature

When IDA finished walking through the binary/code, it shows the lenght of the functions. Is it possible to provide the same feature in x64dbg after Module Analysis?
Something like this?
![len fct](https://user-images.githubusercontent.com/12070561/180775564-b2c8e7ee-0326-4c91-9487-503fe361eaae.png)

That it will be possible to sort functions after their length (to select way less for breakpointing)?

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/180881919-5ae89b82-7ccf-418c-9067-6bbc4fe9b630.png)

**Comment by ScyllaHide** [comment]
How could i not see this. This is great!
