### ISSUE TITLE
Minor issue with comments that contain CR LF

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#292]
If pasting some text into a comment that contains carriage return line feed, then the display of the comment is shown as in the attached image - slightly askew.

Comment showing in screenshot is:

This is a test
so is this

Very minor visual bug.

Strip CR LF from comments.
![comments with cr lf](https://cloud.githubusercontent.com/assets/1768766/7347813/13d8f6ec-ece4-11e4-9ed5-802e661bb51c.png)

**Comment by mrexodia** [comment]
Just don't do it :P I'll fix it later today I think
