### ISSUE TITLE
Jump branch highlight 

### ISSUE THREAD

**Issue by mrcnpp** [x64dbg/x64dbg#2922]
### Feature type

Quality of life

### Describe the feature

Hello,

First of all thanks for this fantastic tool.

My idea is pretty simple , i dunno how hard is to apply this request.

Could you add an option to make thicker the line that shows the branch that will be taken ? 

This function is already implemented in disassembly view but not in graph view.

Thanks

**Comment by mrexodia** [comment]
It was implemented yesterday https://github.com/x64dbg/x64dbg/commit/eb2f4776e3dedbb84fb6860a3b939dc2f28276de
