### ISSUE TITLE
Context wrong when debugging in Windows on arm

### ISSUE THREAD

**Issue by moeray** [x64dbg/x64dbg#2923]
### Operating System

Win11 on ARM

### x64dbg Version

aug 5 2022

### Describe the issue

When debugging an x64 program in Windows on arm, the value of register RBP cannot be read correctly, resulting in failure to continue normal execution after breakpoints other than the entry breakpoint are hit

### Steps to reproduce

1. Run x64dbg in Windows11 on ARM
2. Load a 64bit program, set breakpoints on arbitrary code
3. F9 to run the program

**Comment by mrexodia** [comment]
It's a known bug in Windows that was reported 2 years ago and not fixed yet.

See https://github.com/x64dbg/x64dbg/issues/2869

**Comment by mrexodia** [comment]
You can replace `TitanEngine.dll` with the latest release from [here](https://github.com/x64dbg/TitanEngine/releases/latest). Let me know if it fixes the issue because I do not have access to an ARM64 device with Windows 10 to test right now.

**Comment by moeray** [comment]
> You can replace `TitanEngine.dll` with the latest release from [here](https://github.com/x64dbg/TitanEngine/releases/latest) (V0010 or later). Let me know if it fixes the issue because I do not have access to an ARM64 device with Windows 10 to test right now.

I tried it, no effect, still rbp is cleared after the breakpoint is triggered

**Comment by moeray** [comment]
Isn't the changed content of the code you sent on “arm-on-windows” branch? Has the master branch also fixed this problem?

**Comment by moeray** [comment]
Oh sorry, I didn't see the latest package just now, I tried again, and now it can successfully read rbp and no any exception, very cool!
