### ISSUE TITLE
COM object debug ++

### ISSUE THREAD

**Issue by ELF-EXELABRU** [x64dbg/x64dbg#2924]
### Feature type

Quality of life, Debugging, Other

### Describe the feature

Hi, mrexodia
Minimal COM debug:
binary chain **00000000-0000-0000-C000-000000000046** as _iUnknown_
and detection always structure:
> IUnknown::AddRef
> IUnknown::QueryInterface
> IUnknown::Release

this is ASM 
call [rax + struct_ref] //+0x8, +0x10 (x64)
>call [rax + 0x8]
>call [rax + 0x10]

and others based CLSIDs in _HKEY_ROOT_ detection

 ### also, add all **NT ERROR CODES** (FOR EAX/RAX register dectection during singlestep):
- 	case INET_E_INVALID_URL: {err_string = "INET_E_INVALID_URL";  break; }
- 	case INET_E_NO_SESSION: {err_string = "INET_E_NO_SESSION";  break; }
- 	case INET_E_CANNOT_CONNECT: {err_string = "INET_E_CANNOT_CONNECT";  break; }
- 	case INET_E_RESOURCE_NOT_FOUND: {err_string = "INET_E_RESOURCE_NOT_FOUND";  break; }
- 	case INET_E_OBJECT_NOT_FOUND: {err_string = "INET_E_OBJECT_NOT_FOUND";  break; }
- 	case INET_E_DATA_NOT_AVAILABLE: {err_string = "INET_E_DATA_NOT_AVAILABLE";  break; }
-       case MK_E_CONNECTMANUALLY: {err_string = "MK_E_CONNECTMANUALLY";  break; }
- 	case MK_E_EXCEEDEDDEADLINE: {err_string = "MK_E_EXCEEDEDDEADLINE";  break; }
- 	case MK_E_NEEDGENERIC: {err_string = "MK_E_NEEDGENERIC";  break; }
- 	case MK_E_UNAVAILABLE: {err_string = "MK_E_UNAVAILABLE";  break; }
- case E_NOTIMPL: {err_string = "E_NOTIMPL";  break; }
- case E_OUTOFMEMORY: {err_string = "E_OUTOFMEMORY";  break; }
- 	case E_INVALIDARG: {err_string = "E_INVALIDARG";  break; }
- 	case E_NOINTERFACE: {err_string = "E_NOINTERFACE";  break; }
- 	case E_POINTER: {err_string = "E_POINTER";  break; }
- 	case E_HANDLE: {err_string = "E_HANDLE";  break; }
- case WBEM_S_FALSE: {err_string = "WBEM_S_FALSE";  break; }
- case WBEM_S_TIMEDOUT: {err_string = "WBEM_S_TIMEDOUT";  break; }
- case WBEM_S_NEW_STYLE: {err_string = "WBEM_S_NEW_STYLE";  break; }
- case WBEM_S_PARTIAL_RESULTS: {err_string = "WBEM_S_PARTIAL_RESULTS";  break; }
- and ALL etc.
thx!

**Comment by mrexodia** [comment]
I feel this is more suited as a plugin feature. Let me know if you need any help with the API
