### ISSUE TITLE
Make X64dbg Display Comments as Ollydbg by define functions and parameters

### ISSUE THREAD

**Issue by MaxBayne** [x64dbg/x64dbg#2926]
### Feature type

Quality of life

### Describe the feature

hii how can i display  comments section inside x64dbg to be like ollydbg as describe functions call and its parameters with pretty style like this image inside ollydbg

![image](https://user-images.githubusercontent.com/8224490/184509333-cbdcad64-d9a0-4835-a16a-dfff09e584ff.png)

**Comment by mrfearless** [comment]
See https://github.com/ThunderCls/xAnalyzer

**Comment by MaxBayne** [comment]
Thanks so much ...

**Comment by mrexodia** [comment]
The issue has been reported before (5+ times) so that’s why it’s closed. The API is there for plugins to implement this feature and xAnalyzer is an example of it.
