### ISSUE TITLE
terminal crash when  i run executable in debugger

### ISSUE THREAD

**Issue by oaek127** [x64dbg/x64dbg#2928]
### Operating System

windows 10

### x64dbg Version

x32dbg

### Describe the issue

when i run the program through debugger the terminal window is closed and all windows in the debugger becomes blank .. i use x32dbg on windows 10.

### Steps to reproduce

1. open executable in the debugger
2. hit  run from the toolbar 
3. terminal closes and all debugger windows become blank

**Comment by mrexodia** [comment]
This is not enough information to reproduce the problem. What is the application you ran and what is in the x64dbg log window?

**Comment by oaek127** [comment]
> This is not enough information to reproduce the problem. What is the application you ran and what is in the x64dbg log window?

when it crashes  i find " process exited with error code 0xff(255) .. 
i'm learning reverse engineering by following a book , the application comes with the textbook source code ..

**Comment by mrexodia** [comment]
There is no crash, as you can read in the log the application just exited (called ExitProcess or NtTerminateProcess) with that exit code.

**Comment by oaek127** [comment]
> There is no crash, as you can read in the log the application just exited (called ExitProcess or NtTerminateProcess) with that exit code.

ok but  why i get blank windows and the terminal is closed?

**Comment by mrexodia** [comment]
When the application exits the terminal is closed. You can set an exit breakpoint in the settings to investigate why it exits.

**Comment by oaek127** [comment]
> When the application exits the terminal is closed. You can set an exit breakpoint in the settings to investigate why it exits.

yes i did that .. i set a breakpoint next the first call for printf function but it also exit with blank windows for the debugger itself

**Comment by mrexodia** [comment]
Can you share the executable file?

**Comment by oaek127** [comment]
> 



> Can you share the executable file?
yes sure... its a small program to test pointers.

[Pointers.zip](https://github.com/x64dbg/x64dbg/files/9479802/Pointers.zip)

**Comment by oaek127** [comment]
> Can you share the executable file?

alright, i got it working .. when i use the exe file comes with the textbook which is compiled by elder visual studio , it crashes , but when i generate my own exe file it works .. i don't know why, but thanks anyway.

**Comment by mrexodia** [comment]
It works fine for me with these options:

![image](https://user-images.githubusercontent.com/2458265/188261959-de63f1f6-c498-4985-ae7e-a6ded623765a.png)

![image](https://user-images.githubusercontent.com/2458265/188261962-55499ef6-1aa7-40bf-aed2-d40c508e5fc1.png)

**Comment by oaek127** [comment]
> It works fine for me with these options:
> 
> ![image](https://user-images.githubusercontent.com/2458265/188261959-de63f1f6-c498-4985-ae7e-a6ded623765a.png)
> 
> ![image](https://user-images.githubusercontent.com/2458265/188261962-55499ef6-1aa7-40bf-aed2-d40c508e5fc1.png)

yes indeed , thank you
