### ISSUE TITLE
format code

### ISSUE THREAD

**Issue by gwotang** [x64dbg/x64dbg#293]
Hello,

Is there a way to format code?

like OllDbg - [Debugging options] - [Disasm]

[v] Tab between mnemonics and arguments

**Comment by mrfearless** [comment]
There is some options in Options->Preferences->Disasm that might be what your looking for:
- Argument spaces
- Memory spaces

They expand the instruction out, by placing spaces, depending on those checkbox settings.

Hope that helps

**Comment by mrexodia** [comment]
Added the option, it looks like this:

![image](http://i.imgur.com/DZbOHHD.png)
