### ISSUE TITLE
Function parsing problem when commas are present

### ISSUE THREAD

**Issue by mateussilva92** [x64dbg/x64dbg#2930]
### Operating System

Windows 10 64bit, Build 19043

### x64dbg Version

Jun 22 2022

### Describe the issue

So I was building a script where I was trying to log a custom function that receives 3 inputs. And the results of the log always displayed `???`. It ends up being that log function looks for the commas blindly instead of running the function passed as a parameter.

E.g.:
`log "Result of match: {0}", dis.match(addr, str)`

The example above will not display `Result of match: 1` nor `Result of match: 0` instead it will display `Result of match: ???` because it's not running `dis.match(addr, str)` before running the log. It's looking at the commas and spliting the command into `dis.match(addr` and `str)` and for the parameter `{0}` it will try to run `dis.match(addr` which is not valid that's why it ends up displaying the `???`.

### Steps to reproduce

1. Create a script
2. Add the following command to the script `log "Result: {0}", ternary(1, 10, 20)`
3. Run the script and observe the result in the logs tab (the result of the script will be `Result: ???` instead of `Result: 10`)

**Comment by mrexodia** [comment]
Yeah you need to quote the arguments. But in general this is solved by using the inline formatting instead: “Result: {ternary(1, 10, 20)}”

**Comment by mateussilva92** [comment]
@mrexodia what about in case the function as a parameter that as already quotes in it?
E.g. `log "Result: {streq(dis.mnemonic(cip), "call")}"`

**Comment by mrexodia** [comment]
Yeah this is tricky, you would have to use `\"`. The addition of string parameters to expression functions is quite new so I will think about a solution for this.

**Comment by mrexodia** [comment]
The following command works as "expected" now:

```
log "is jmp: {streq(dis.mnemonic(dis.sel()), "jmp")}"
```

I'm not entirely convinced about this approach, but we'll see if it has any negative side effects.

Technically the following command would no longer work as expected:

```
cmd "arg1{", arg2, arg3
```

You would now need to write:

```
cmd "arg1\{", arg2, arg3
```

**Comment by mateussilva92** [comment]
This fixes the issue with the `log` command, but there are still commands that parse the args incorrectly, splitting on the commas instead of checking if that comma is part of other command.
I saw the parser and it seems to be missing a check for parentheses.

E.g.
```
mov $variable, streq(dis.mnemonic(dis.sel()), "ret")
```

---

I did some extra tests and it seems that there are other problems.
```
asm $address, dis.text($address), 1

```
This will not run the `dis.text($address)` before trying to run the `asm` command. Not sure if it's intended or not.

**Comment by mrexodia** [comment]
This will not be fixed, there is no way to handle that correctly.

**Comment by mrexodia** [comment]
The reason is that the commands themselves are not a language. It's a loosely defined mechanism and there is no concept of expressions or parentheses. The command is parsed and then the arguments are passed as strings to the command callback. The callback can then use the `DbgEval` function to evaluate expressions.

Perhaps a solution like this could work. All commands are also made available as expression functions with the prefix `cmd.`, which would put the command invocation and the arguments in the same domain. Your example would then become:

```
cmd.asm($address, dis.text($address), 1)
```

Would that work for you?

**Comment by mateussilva92** [comment]
That seems like a good idea and for sure would fix this kind of problems.
