### ISSUE TITLE
入口断点失效  状态栏显示 Please report an issue!

### ISSUE THREAD

**Issue by hbhouse** [x64dbg/x64dbg#2931]
### Operating System

Microsoft Windows [ver 10.0.18363.1443] x64

### x64dbg Version

Sep 4 2022(TitabEngine)

### Describe the issue

入口断点失效  状态栏显示 Please report an issue!

### Steps to reproduce

1.入口断点失效  状态栏显示 Please report an issue!
2.无法增加断点 

### Attachments

[dump-07092022_1558250898.zip](https://github.com/x64dbg/x64dbg/files/9503982/dump-07092022_1558250898.zip)
![360截图18720122727960](https://user-images.githubusercontent.com/10690930/188823994-77c12ce5-f9b9-4b6d-a633-ac19650fe65d.png)

**Comment by mrexodia** [comment]
Could you share `1pro.exe` and the log?

**Comment by hbhouse** [comment]
我找到问题原因的了 是因为杀毒软件的影响  造成断点无法工作

**Comment by mrexodia** [comment]
I found a bug and I think it has been fixed.
