### ISSUE TITLE
Can not open some C# programs by snapshot_2022-09-04_22-34

### ISSUE THREAD

**Issue by cjchome** [x64dbg/x64dbg#2932]
### Operating System

Windows 11 x64

### x64dbg Version

snapshot_2022-09-04_22-34

### Describe the issue

Can not open some C# programs by snapshot_2022-09-04_22-34
Such as PrintConductor.exe
Previous versions can do.

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
It should work properly again now
