### ISSUE TITLE
"Error replacing page: [...] Please report an issue!"

### ISSUE THREAD

**Issue by not6** [x64dbg/x64dbg#2933]
### Operating System

Windows 10 Professional 21H2, Build 19044.1949

### x64dbg Version

Sep 11 2022, latest as of writing this issue

### Describe the issue

This has been reported before but I could not fix it by disabling my anti-virus like the other person and no breakpoints are needed to reproduce this problem
Following message being repeatedly printed in logs, although application seems to be running fine

```
Error replacing page: 6F810000[00210000]
Sections:
  ".text": 6BE01000[00072000]
  ".data": 6BE73000[00003000]
  ".idata": 6BE76000[00003000]
  ".rsrc": 6BE79000[0000F000]
  ".reloc": 6BE88000[00005000]
New pages:
Please report an issue!
```

### Steps to reproduce

Run this (safe) application in x32dbg, no plugins or breakpoints are required
[Download link](https://www.gtagarage.com/mods/download.php?f=90)
[Mirror](https://www.upload.ee/files/14501799/IMGTool.exe.html)
It is packed with UPX but that has nothing to do with this issue as it occurs even after unpacking.
The application is _very_ old (2005) so that might be a clue to what's going on

**Comment by mrexodia** [comment]
Thanks, I can reproduce the issue!

**Comment by not6** [comment]
Thank you as well!
