### ISSUE TITLE
Are there plans to support windows arm64?

### ISSUE THREAD

**Issue by fenginsc** [x64dbg/x64dbg#2934]
### Feature type

Debugging

### Describe the feature

Debugging of Windows programs that support arm64 will be good.
But considering that arm is different from x86, the work of instruction set adaptation may be difficult.

**Comment by mrexodia** [comment]
There are no plans right now.

**Comment by Max-RM** [comment]
@fenginsc have you find some other debuggers for Windows ARM64?

Because Cheat Engine and x64dbg doesn't work.

Maybe you find some anolog after 2 years, if yes can you send it to me?

**Comment by Max-RM** [comment]
> @fenginsc have you find some other debuggers for Windows ARM64?
> 
> Because Cheat Engine and x64dbg doesn't work.
> 
> Maybe you find some anolog after 2 years, if yes can you send it to me?
(Don't recommend Visual Studio debugger because it doesn't have some needed functions)

**Comment by mrexodia** [comment]
You can use WinDbg, it works fine!

**Comment by fenginsc** [comment]
@Max-RM
Unfortunately, there are no better debuggers for windows on arm64 at the moment, so maybe you could try WinDbg.

**Comment by Max-RM** [comment]
> @Max-RM Unfortunately, there are no better debuggers for windows on arm64 at the moment, so maybe you could try WinDbg.

Thx. Will try later.
