### ISSUE TITLE
09-11 version update can not run on xp

### ISSUE THREAD

**Issue by inaryart** [x64dbg/x64dbg#2937]
### Operating System

widnows xp

### x64dbg Version

snapshot_2022-09-11_15-59

### Describe the issue

- commit
https://github.com/x64dbg/x64dbg/commit/3c22b64cd8352c1cfc182d11171a0c11bc6843b1

https://github.com/x64dbg/x64dbg/issues/2545

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Feel free to fix it. XP has been _out of support_ for almost 10 years now.

**Comment by CrankDatSouljaBoy** [comment]
True

**Comment by mrexodia** [comment]
https://github.com/x64dbg/TitanEngine/actions/runs/3204003430 Did you use this dll? This version of TitanEngine is not yet in x64dbg snapshots.
