### ISSUE TITLE
Minor language bug in latest release

### ISSUE THREAD

**Issue by not6** [x64dbg/x64dbg#2938]
### Operating System

Windows 10 Professional 21H2, Build 19044.1949

### x64dbg Version

Sep 18 2022

### Describe the issue

The release version of x64dbg has a strange minor issue in preferences that has not been there before in earlier releases
The 'Cancel' button in the preferences window is now in Ukrainian for some reason.

![image](https://user-images.githubusercontent.com/94708210/191095582-e14512cf-c4d7-4bdf-80a5-721dd787592d.png)

Copying translation files from last release to current seems to fix the issue

### Steps to reproduce

Go to Options->Preferences

**Comment by mrexodia** [comment]
What is the language you have selected in the menu? Perhaps someone started translating Ukrainian and you’re just getting the partial translation…

**Comment by not6** [comment]
I checked earlier and it's en-US @mrexodia
Probably doesn't matter but my Windows language is also English only

**Comment by mrexodia** [comment]
Thanks, someone translated the English language on crowdin. I removed the language and it should be fixed in the next build. Meanwhile you can delete the translation files to fix it.
