### ISSUE TITLE
Load from binary file into the memory

### ISSUE THREAD

**Issue by AbedKarmi** [x64dbg/x64dbg#2943]
### Feature type

Debugging

### Describe the feature

Debugger allows saving a block of binary data from dump window to a file, but does not allow loading that data back into the dump window. we need to have that feature, so we can load binary data from a file into the dump memory.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/DotX64Dbg

Take a look at the examples, this will be quite easy to implement as a quick C# script.

**Comment by AbedKarmi** [comment]
Thanks,

I was able to activate it, but with no documention, I could not figure out how find the address of the dump-1 memory?

**Comment by ZehMatt** [comment]
> Thanks,
> 
> I was able to activate it, but with no documention, I could not figure out how to find the address of the dump-1 memory, or other memory sections like (.text) ?

To get the selection from the memory dump that would be something like 
```csharp
var range = UI.MemoryMap.GetSelection();
Console.Write("Selection from dump: {0} - {1}", range.Start, range.End);
```

**Comment by AbedKarmi** [comment]
Thanks for the code, was helpfull. Could you clarify if the plugin supports Windows.Forms in c# code?

**Comment by ZehMatt** [comment]
Yes it does support WinForms

**Comment by AbedKarmi** [comment]
I add this to the project file manually to enable windows forms "<UseWindowsForms>true</UseWindowsForms>"
But, when the debugger starts, the project file is overwritten, and the winforms support is removed!
So only .NetCore framework is shown in the project dependencies

**Comment by AbedKarmi** [comment]
I was able to make the plugin work, but I have several issues and notes:
1. If the project is openned with visual studio, it will cause an error, the plugin will not load

x64dbg\release\dotplugins\MyPlugin\obj\x64\Debug\net6.0-windows\MyPluginEx.GlobalUsings.g.cs(2,1): error CS0116: A namespace cannot directly contain members such as fields or methods

So, I have to exit visual studio, and DELETE both folders bin & obj, then start debugger again

2. The code I have written did not work as required, I have openned an issue about this BUG

https://github.com/x64dbg/x64dbg/issues/2944#issue-1393749089

Here is the code:

    [Command("LoadFile")]
    void LoadFile(string[] args)
    {
        OpenFileDialog openFile = new()
        {
            //set up the open file dialog
            Multiselect = false,
            Filter = "All Files (*.*)|*.*",
            FilterIndex = 0,
            InitialDirectory = Application.StartupPath
        };
        if (openFile.ShowDialog() == DialogResult.OK)
        {
            // var range = UI.MemoryMap.GetSelection();
            var range = UI.Dump.GetSelection();
            byte[] bytes = File.ReadAllBytes(openFile.FileName);
            
            if ((int)range.Size != bytes.Length)
                Console.WriteLine("File size does not match selection range {0:X}   {1:X}", (int)range.Size, bytes.Length);
            else
            {
                Console.Write("Loading binary data into Dump: {0:X} - {1:X}", range.Start, range.End - 1);
                Memory.Write(range.Start, bytes);
            }
        }
    }


3. I wonder how can I do a "Select ALL" for the UI.Dump?

Thanks , you are doing so great job :)

**Comment by ZehMatt** [comment]
1. Is known, see https://github.com/x64dbg/DotX64Dbg/issues/64
2. Not sure what which part is not working; do you get any errors?
3. You can set the selection via Dump.SetSelection() but there is currently no way to tell the length.
4. The selection is always inclusive, so when an instruction or byte is selected range.End will be always Start + Size which points to the next element which is the correct way.

**Comment by AbedKarmi** [comment]
Nothing is written!

**Comment by ZehMatt** [comment]
I'll look into it.

**Comment by albertlab0** [comment]
+1 for this feature request.

**Comment by torusrxxx** [comment]
Has somebody written anything? I didn't do that at first because Odbgscript doesn't seem to support it, Need a name for the command first, could be "loaddata" to keep consistency with existing "savedata".
