### ISSUE TITLE
Rename asmjit.dll dependency to asmjit_xedparse.dll

### ISSUE THREAD

**Issue by pmeerw** [x64dbg/x64dbg#2948]
### Operating System

Windows 11

### x64dbg Version

Oct 3 2022

### Describe the issue

asmjit_xedparse.dll would be a better name, it points to the repo where this DLL comes from

### Steps to reproduce

N/A

**Comment by mrexodia** [comment]
Yeah unfortunately renaming this wouldn't be possible since plugins might be using the name...
