### ISSUE TITLE
Implement ability to pin x64dbg to taskbar

### ISSUE THREAD

**Issue by ax1ne** [x64dbg/x64dbg#2949]
### Feature type

Quality of life

### Describe the feature

x64 Does not seem to have the ability to be pinned to the taskbar, only "Pin to Start". This would make it so much easier to start instead of having to switch from somewhere else to open it.

**Comment by mrexodia** [comment]
![image](https://user-images.githubusercontent.com/2458265/194702854-afb2fd69-3bd7-48d7-aa29-65975179d5d2.png)
 
Works fine for me.

**Comment by ax1ne** [comment]
I was unable to get it to do so with both versions, administrator privileges on / off.

E.g:
https://i.imgur.com/ei45l3H.png

**Comment by ax1ne** [comment]
Edit: Updated to the latest version and it fixed it.
