### ISSUE TITLE
When can there be memory scanning function, like cheat engine

### ISSUE THREAD

**Issue by i2a35oy0x6** [x64dbg/x64dbg#2950]
### Feature type

Plug-ins

### Describe the feature

I've looked everywhere and there is only one ClawSearch plugin that implements memory scanning, but that plugin is no longer updated and using it will crash x64dbg

**Comment by mrexodia** [comment]
I tested and the plugin seems to work fine. How exactly do you crash it?

**Comment by i2a35oy0x6** [comment]
> I tested and the plugin seems to work fine. How exactly do you crash it?

try open ClawSearch's dialog, and close x64dbg, dbg will crash.

**Comment by i2a35oy0x6** [comment]
> I tested and the plugin seems to work fine. How exactly do you crash it?

https://github.com/codecat/ClawSearch/issues/5

https://github.com/codecat/ClawSearch/issues/12

**Comment by mrexodia** [comment]
Fixed it, wait for https://github.com/codecat/ClawSearch/pull/13 to be merged. You can get the release for now at https://github.com/mrexodia/ClawSearch/releases/tag/2022-10-07

**Comment by i2a35oy0x6** [comment]
thanks!
