### ISSUE TITLE
0/1 Patch(es) applied

### ISSUE THREAD

**Issue by jazzchng** [x64dbg/x64dbg#2951]
### Operating System

Windows 10 64bit, 21H2, Build 19044.2075

### x64dbg Version

5.6.3

### Describe the issue

Hello!
I am unable to patch the file, I edited the jump to a specific address but it doesn't patch.
What am I doing wrong here? I have attached an image below for reference.
Thank you!
![image](https://user-images.githubusercontent.com/21230745/195037312-fa979a90-55ed-4103-b092-adb1dbc29179.png)

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions

**Comment by jazzchng** [comment]
> https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions

Thank you mrexodia! I'll read through the faq for more info :)
