### ISSUE TITLE
How can I use shortcutkey Cttl+G like ollydbg?

### ISSUE THREAD

**Issue by Oxygen1a1** [x64dbg/x64dbg#2953]
### Feature type

Debugging

### Describe the feature

when I use ctrl+G,xDbg change sel address which I input,But when I use Ctrl+G again, the default address is the one I selected.

**Comment by mrexodia** [comment]
And? What do you expect to happen?

**Comment by Oxygen1a1** [comment]
> 

what I want to is when I use ctrl+g shortcut keys,the window will remeber what I input last time,but not I selected
if any settings can change it or plugin code can change it?
please tell me,thanks

**Comment by mrexodia** [comment]
You can use the arrow up to get the input you last selected.

**Comment by Oxygen1a1** [comment]
> You can use the arrow up to get the input you last selected.

Oh!Thanks，
