### ISSUE TITLE
hope to have command to save log, not only GUI 

### ISSUE THREAD

**Issue by RachelWealth** [x64dbg/x64dbg#2961]
### Feature type

Other

### Describe the feature

As command can help for third-party programme transfer

**Comment by utkonos** [comment]
Yes, this would be a very helpful feature! Log control commands:

`logsave [arg1]`
this would save the log to a text file with a timestamp filename like the GUI does. If the optional `arg1` is provided, that string is used as the filename or path to save to.

`logredir [arg1]`
this would enable log redirection to a timestamp filename like the above. if the optional `arg1` is provided, that string would be used as the filename or path for the redirected log data.

`logredirstop`
stops log redirection

**Comment by ElvisBlue** [comment]
Well this cound be implement by writing a plugin. x64dbg provide `_plugin_registercommand` API to add your custom command.

**Comment by mrexodia** [comment]
I could swear there is some kind of API for this, but I don’t remember… why
do you need this functionality? It might be easier to have a command that
appends to a custom log file…

**Comment by utkonos** [comment]
> why do you need this functionality?

The use case here is in a script. At the end of the script, it would be very useful to be able to run `logsave` right before `ret`. Another location would be in error handling also just before a `ret` and after a `msg`.

The two nice to haves: `logredir` and `logredirstop` would have a similar purpose: in scripts. One could start and stop logging during certain parts of the script where logging to a file would be useful such as during a trace or when gathering network indicators or other other specific parts of a script.

> It might be easier to have a command that appends to a custom log file…

Yes, having `logsave` and/or the other two is just an idea for how to solve the use case. I would be happy with any feature that could solve the use case.

**Comment by torusrxxx** [comment]
The log redirection and saving doesn't have an external API yet, mostly because it is handled by GUI, not DBG.

**Comment by utkonos** [comment]
I asked ChatGPT to write this plugin. Does this look correct?

```
#include <cstdio>
#include <cstring>

#include "x64dbg.h"

// Plugin information
const char* plugin_name = "Log to File";
const char* plugin_version = "1.0.0";

// Console command to enable logging to a file
void cmd_logtofile(int argc, char* argv[])
{
    // Check if the correct number of arguments was provided
    if (argc != 2)
    {
        dputs("Usage: logtofile [filename]");
        return;
    }

    // Get the filename from the command arguments
    const char* filename = argv[1];

    // Open the file for writing
    FILE* file = fopen(filename, "w");
    if (!file)
    {
        dprintf("Failed to open file %s for writing\n", filename);
        return;
    }

    // Enable logging to the file
    GuiSetLogFile(file);
    dprintf("Logging enabled to file %s\n", filename);
}

// Initialize the plugin
extern "C" __declspec(dllexport) bool pluginit(PLUG_INITSTRUCT* initStruct)
{
    // Register the console command
    plugin_registercommand(plugin_name, "logtofile", cmd_logtofile);

    // Return success
    return true;
}

// Plugin cleanup
extern "C" __declspec(dllexport) bool plugstop()
{
    // Return success
    return true;
}

// Plugin information
extern "C" __declspec(dllexport) char* plugin_info()
{
    // Format the plugin information string
    static char info[256];
    sprintf_s(info, "%s v%s by %s", plugin_name, plugin_version, "Assistant");

    // Return the plugin information
    return info;
}
```

**Comment by Bluefissure** [comment]
> I asked ChatGPT to write this plugin. Does this look correct?
> ...

There's no `GuiSetLogFile` API exposed in the plugin SDK, ChatGPT is easily getting illusion to make something looks good but actually doesn't work.

I think the main issue is to provide a signal of [`saveSlot()`](https://github.com/x64dbg/x64dbg/blob/86bbdaabb081f1758ce7bbce28f8ac0cf8d0603a/src/gui/Src/Gui/LogView.cpp#L433) just like [`clearLog()`](https://github.com/x64dbg/x64dbg/blob/86bbdaabb081f1758ce7bbce28f8ac0cf8d0603a/src/gui/Src/Gui/LogView.cpp#L40).

It doesn't look to be very hard to do, @mrexodia is there a new contributing doc? I found [the one from readme and wiki](https://github.com/x64dbg/x64dbg/blob/development/CONTRIBUTING.md#contributing) is returning 404. Or can I follow the compile instructions in wiki pages (which is still VS2013 and QT5.6.3)?

**Comment by mrexodia** [comment]
Thanks for the heads-up, I moved the contributing document to the `.github` folder, but clearly forgot to update the links. The compile guide on the wiki is still correct and we indeed use VS2013 and Qt 5.6.3. This is definitely a point of friction and I plan to switch to [cmkr](https://cmkr.build) soon, to at least allow people with newer VS/Qt versions to contribute.
