### ISSUE TITLE
find multiple assembled instructions

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#297]
Like so:

```
push rax
mov rax,rbx
```

**Comment by lupier** [comment]
Also please fix "Failed to assembly" (failed to encode instr.)
example: try to find fsin
http://gyazo.com/9af00c641d916a284862b4f65570d367

**Comment by mrexodia** [comment]
also allow wildcards like:
`mov r32, [esp+?]`

**Comment by mrexodia** [comment]
closed in favor of #779
