### ISSUE TITLE
Tracing synchronization

### ISSUE THREAD

**Issue by oleedd** [x64dbg/x64dbg#2973]
### Feature type

Debugging

### Describe the feature

Please add synchronization between the main and trace windows (it works in OllyDbg):
![111](https://user-images.githubusercontent.com/36125949/201990201-538bd434-39e2-48e2-af8e-2668b7ced916.jpg)
It is a basic and important thing.

**Comment by mrexodia** [comment]
You can toggle this using 'Sync with CPU'

![image](https://user-images.githubusercontent.com/2458265/222382196-0da42c0c-87f6-4dec-a90f-a2e21e5adaaf.png)

**Comment by oleedd** [comment]
Thanks for adding this. Can you add the ability to enable this by default? Or it is already available?

**Comment by mrexodia** [comment]
You can bind it to a hotkey. If that’s not enough, the source code is available and you’re welcome to contribute.

**Comment by oleedd** [comment]
Not enough but better than nothing.
It seems that it is not available there:
![image](https://user-images.githubusercontent.com/36125949/222440115-feced3bc-6187-4226-87ac-a4e76fcba53f.png)
Or it has another name?

**Comment by mrexodia** [comment]
Both new issues you discovered should be fixed now.

**Comment by oleedd** [comment]
Thanks. Why "Sync" instead of "Sync with CPU" (I was confused and understood it by "S" )?

**Comment by oleedd** [comment]
Thanks. Why "Sync" instead of "Sync with CPU" (I was confused and understood it by "S" later)?

**Comment by mrexodia** [comment]
The three sync actions were merged into a common one
