### ISSUE TITLE
no ejecuta el exe 

### ISSUE THREAD

**Issue by flony-hub** [x64dbg/x64dbg#2979]
me esta pasando que al ejecutar un exe, primero que no inicia el exe y a su vez en pantalla se queda diciendo (no responde) 
![image](https://user-images.githubusercontent.com/83675822/203190334-c3173e77-f678-4c41-966f-b98f5c9c9acf.png)

**Comment by flony-hub** [comment]
![image](https://user-images.githubusercontent.com/83675822/203191704-1405dd6e-21c1-4309-965b-8635b9d7af99.png)

**Comment by mrexodia** [comment]
Please share the executable.
