### ISSUE TITLE
callstack window becomes empty after few threadswitches

### ISSUE THREAD

**Issue by neurall** [x64dbg/x64dbg#298]
debbugging managed .net 4.5 app by attaching and pause.
callstacks look perfect. after switching to like 7th thread it becomes empty and remains empty even for old threads. stop and reattach didnt helped only restart

**Comment by mrexodia** [comment]
I failed to reproduce it with the latest snapshot `snapshot_2015-05-11_08-10.7z` on a simple WinForms application. Do you have more specific information on how to reproduce this?

**Comment by Nukem9** [comment]
No issuer response. Considered to be fixed -> closed.
