### ISSUE TITLE
Unable to Hit Breakpoint on Pushad EBP

### ISSUE THREAD

**Issue by Shattacrew** [x64dbg/x64dbg#2980]
I am doing a Udemy Course by Paul Chin.  I really want to understand unpacking a software.  In the course he demonstrate that setting a breakpoint on Pushad EBP DWORD should break on POPAD.  When I run the crackme, it executes bypassing the dword breakpoint.

I can step through the application and find where the POPAD occurs but the breakpoint is not being triggered.  Is there a setting that I am missing in x32dbg? or is there a bug in the current build?

**Comment by mrexodia** [comment]
Try setting a breakpoint on byte. This issue has been reported before, but I was not able to reproduce it…

**Comment by Shattacrew** [comment]
Thank you for the response.  I just tried setting breakpoint on byte.  It is still not being triggered.  I tried placing a breakpoint on each of the byte and still no break.

**Comment by mrexodia** [comment]
Try the following:

- Download https://github.com/upx/upx/releases/download/v4.0.1/upx-4.0.1-win32.zip
- Open `upx.exe` in x32dbg
- Run until you reach the entry point (skip the TLS callback)
- Step over the `pushad`
- Right click in the registers view -> Set hardware breakpoint on ESP
- Run

It should break at `lea eax,dword ptr ss:[esp-80]`. If this is not the case, provide information about your environment (OS version, VM, etc).

**Comment by Shattacrew** [comment]
That works!  It breaks exactly where you said.  I tried the same thing on the crackme I was practicing with and likewise, setting the breakpoint on ESP gives a successful break.  Does this mean anything?

**Comment by mrexodia** [comment]
The idea is that `pushad` stores the contents of the `eflags` on the top of the stack. After this is done you put a hardware breakpoint on a read of `[esp]` because the `popad` instruction will pop the value back into `eflags`. I'm not sure what you were doing, but likely just not breaking on the right address?
