### ISSUE TITLE
Not saved size of window

### ISSUE THREAD

**Issue by gnanashi** [x64dbg/x64dbg#2984]
### Operating System

Windows 10 Build 19045.2311 64bit & 32bit

### x64dbg Version

snapshot_2022-10-28_15-42 and later

### Describe the issue

The size of the main window is not saved (if not maximized).

### Steps to reproduce

1. Resize the main window of x64dbg
2. Restart x64dbg
3. x64dbg starts with the size of the main window as the initial value

**Comment by mrexodia** [comment]
I just tested and I cannot reproduce this issue on the latest version. I'm on Windows 10 19044.2251

**Comment by 793359277** [comment]
> 我刚刚测试了，我无法在最新版本上重现此问题。我使用的是 Windows 10 19044.2251

I have also encountered that starting from a certain version, x64dbg cannot save the position and size information (the size is reset to ≈884*639). I tried to download some old versions of x64dbg and found that it was normal. The current system is WIN10 22H2 19045.2965. After changing to WIN11, the latest x64dbg has no problem.

**Comment by 793359277** [comment]
> I just tested and I cannot reproduce this issue on the latest version. I'm on Windows 10 19044.2251

I have also encountered that starting from a certain version, x64dbg cannot save the position and size information (the size is reset to ≈884*639). I tried to download some old versions of x64dbg and found that it was normal. The current system is WIN10 22H2 19045.2965. After changing to WIN11, the latest x64dbg has no problem.
