### ISSUE TITLE
Customizable plugin directory path

### ISSUE THREAD

**Issue by poxyran** [x64dbg/x64dbg#299]
Add an option to allow users to configure the path to the plugins directory.

**Comment by mrexodia** [comment]
Why? I honestly don't see any use for this except to cause user confusion.

**Comment by poxyran** [comment]
I know it is a matter of preference and I can't think in a particular use case right now but maybe it is a better idea to give the user the possibility to choose the path and not to tie it to a particular location.

Anyway, if you think it is redundant, please, close the PR.

**Comment by duncanisgoed** [comment]
I didn't see a pull request, where is it? The problem with customizable directories is that you cannot move x64dbg without altering those paths every time. OllyDbg did this and I **always** struggled when I moved to a different drive of just put Olly on a thumbstick. I even wrote my own dll and injected it to OllyDbg.exe to fix the problem.

**Comment by mrexodia** [comment]
I didn't see a pull request, where is it? The problem with customizable directories is that you cannot move x64dbg without altering those paths every time. OllyDbg did this and I **always** struggled when I moved to a different drive of just put Olly on a thumbstick. I even wrote my own dll and injected it to OllyDbg.exe to fix the problem.

**Comment by justanotheranonymoususer** [comment]
A path can (and should) be relative, so that's not an issue.

**Comment by mrexodia** [comment]
True, but I still don't see a use case there. Currently it is already relative to `x64dbg.exe` and it's called `plugins`. And relative paths start to break when you try doing `..\..\x64dbgplugins` from `C:` and things like that
