### ISSUE TITLE
Abnormal problems,

### ISSUE THREAD

**Issue by rmhh888** [x64dbg/x64dbg#2998]
### Operating System

Win 11

### x64dbg Version

Each version

### Describe the issue

![image](https://user-images.githubusercontent.com/120655657/208615938-d4a8bfdb-966f-4f86-b23f-b9bea0788c85.png)
Exception problem. X64DBG's exception handling is not as good as OD's!, Can you pay attention to this!

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
You just don’t understand how it works.
