### ISSUE TITLE
multiple dumps windows

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#300]
add a nice grid of memory dump windows possibly with comparison or similiar functionality

**Comment by mrexodia** [comment]
should have a sync option with the various dump windows in the CPU.

**Comment by mrexodia** [comment]
@Herz3h commit dc167504 allows you to use the command `dump va,index` to emit the Bridge::dumpAtN signal

**Comment by Nukem9** [comment]
Is this considered done now? Also - is the number of dump tabs only limited to 5?

**Comment by Herz3h** [comment]
The number of tabs is set to be 5, can be increased or an option could be added to settings to decide how many dump tabs to show.

**Comment by mrexodia** [comment]
I think we should allow opening new and closing tabs, but I consider this
issue solved for now. 5 should be enough for everyone.
