### ISSUE TITLE
x64dbg中使用条件断点, 如何判断1字节的值?

### ISSUE THREAD

**Issue by jiuzhouhan996** [x64dbg/x64dbg#3000]
### Operating System

Win10 x64 1909

### x64dbg Version

Jun 4 2020

### Describe the issue

在64位程序中是8字节对齐, 假如我想判断rdx地址中的1个字节的值, 条件断点该怎么写?
"[rdx] != 1" 这样写是判断8个字节的值是否等于1, 如果我想判断 1个字节的值 该怎么写?
请告诉我写法, 谢谢!

### Steps to reproduce

在64位程序中是8字节对齐, 假如我想判断rdx地址中的1个字节的值, 条件断点该怎么写?
"[rdx] != 1" 这样写是判断8个字节的值是否等于1, 如果我想判断 1个字节的值 该怎么写?
请告诉我写法, 谢谢!

**Comment by mrexodia** [comment]
Like in C: `([rdx] & 0xFF) != 1` or you can use `1:[rdx] != 1` or `ReadByte(rdx) != 1`

**Comment by jiuzhouhan996** [comment]
thanks very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x64dbg/x64dbg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月31日(星期六) 上午8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x64dbg/x64dbg] x64dbg中使用条件断点, 如何判断1字节的值? (Issue #3000)





 
Like in C: ([rdx] &amp; 0xFF) != 1 or you can use 1:[rdx] != 1 or ReadByte(rdx) != 1
