### ISSUE TITLE
Add option to disable the Christmas theme???

### ISSUE THREAD

**Issue by sdasda7777** [x64dbg/x64dbg#3001]
### Feature type

Quality of life

### Describe the feature

Hey, the christmas theme is, to put it very mildly, annoying, and I can't seem to find a way to disable it.
Would it be possible to add an option to disable it?

![image](https://user-images.githubusercontent.com/17746796/209561471-62d790d1-97fb-4a70-9430-ce6b030d88b9.png)

**Comment by mrfearless** [comment]
Options->Preferences->GUI Tab->Hide seasonal icons checkbox.

**Comment by sdasda7777** [comment]
Ah, thanks.
