### ISSUE TITLE
Stack and CPU Window not showing ASCII characters/strings

### ISSUE THREAD

**Issue by iAmG-r00t** [x64dbg/x64dbg#3003]
### Operating System

Windows 7 Ultimate, Service Pack 1

### x64dbg Version

Dec 12,2022

### Describe the issue

This issue #2835 is still present in the current build and I see you pushed a fix 07d6008. I proceeded to check the source code of the current build and the fix 07d6008 hasn't been applied.

![image](https://user-images.githubusercontent.com/29776892/211675091-0725dc24-8624-47e5-a7a7-f9ea80077e95.png)

Thank you for your tool and time.

_No response_

**Comment by iAmG-r00t** [comment]
I am going to close this issue.

**Comment by mrexodia** [comment]
Do you have an example executable?

**Comment by iAmG-r00t** [comment]
I was closing it because I managed to build the dev version and the stack window still doesn't show strings so I am using the show in current dump option to view what the string is.

It doesn't even show the string stack traces of `user32.messageBoxw`

[RE_Lab_6.zip](https://github.com/x64dbg/x64dbg/files/10409052/RE_Lab_6.zip)


Context: I am doing a course from INE for practical reverse engineering and I am trying to learn how to use xdbg instead of using olly.

This is my stack view;

![image](https://user-images.githubusercontent.com/29776892/212257883-ee43f936-59f9-445d-af31-e3fbc8380900.png)

**Comment by iAmG-r00t** [comment]
I know you are busy have you managed to reproduce the issue?

**Comment by iAmG-r00t** [comment]
Here is another issue I have encountered in the call stack, the same issue doesn't show strings but its references.

While in the call stack I am unable to follow DWORD in the current dump, could you recommend a way to fix this either a code base that I can look at and try and fix 😓😓😓

![image](https://user-images.githubusercontent.com/29776892/213080315-8c4620fa-2409-4f3c-97b5-484b5b7a5073.png)

**Comment by mrexodia** [comment]
Please open a separate issue for the call stack thing to avoid growing the scope of the issue. The code is here: https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/CallStackView.cpp

**Comment by mrexodia** [comment]
Okay, I reproduced the issue with the latest build:
![image](https://user-images.githubusercontent.com/2458265/213114633-7dd3a6ef-329b-428b-abaf-4b7d65c3cf2c.png)

**Comment by mrexodia** [comment]
Thanks for the detailed report, appreciated! For following the call stack you should be able to just double click.

**Comment by iAmG-r00t** [comment]
Let me download the new version, also should I proceed and open a new issue for the call stack?

**Comment by mrexodia** [comment]
Sure, please include more details and/or a video to see what's going on and what you expect. I didn't understand the issue.

**Comment by iAmG-r00t** [comment]
Sure will do so.
