### ISSUE TITLE
[zh-CN]bug

### ISSUE THREAD

**Issue by YHSanSheng** [x64dbg/x64dbg#3005]
覆盖安装当前最新版本(Dec 12 2022)后我发现【日志】中的汉化出现了一些问题。在我更新之前它是正常的.

但是很抱歉，我忘记了更新之前的版本号，但是好像是2022年8月份的版本

————————————————————————————————————————

After overwriting and installing the latest version(Dec 12 2022), I found that there were some problems in the localization of [Log]. It is normal before I update it

But I'm sorry, I forgot the version number before the update, but it seems to be the version in August 2022

————————————————————————————————————————
[](url)
当前的状态：
——————
Current status：
——————
![1](https://user-images.githubusercontent.com/112924145/212465807-392e559b-c6ca-4c30-b6ce-482f374d4aec.jpg)
之前的状态：
——————
Previous status：
——————
![2](https://user-images.githubusercontent.com/112924145/212465815-b50a6428-3dea-4cf0-aa1c-883131a758d8.jpg)

**Comment by mrexodia** [comment]
You can improve it at translate.x64dbg.com. The format strings were changed so the translation was invalidated.
