### ISSUE TITLE
findallmem/findmemall addresses of occurences

### ISSUE THREAD

**Issue by navix14** [x64dbg/x64dbg#3008]
### Feature type

Debugging

### Describe the feature

As far as I know, the `findallmem/findmemall` functions only return the _number_ of occurences, but no information about the actual locations where the pattern was found. This is very annoying when you rely on _masked_ patterns to find dynamically allocated code pages. The keyword is masked since otherwise the memory map pattern search suffices.

It is also hard to know in advance which memory page will contain the payload, so trying them all out one by one using the `find` command is very unproductive. Is there a way to search _all_ memory pages for a masked pattern such as

`59 C3 E8 ? ? ? ? 85 C0 74 08 6A 16 E8 ? ? ? ? 59 F6 05 ? ? ? ? ? 74 22 6A 17 FF 15`

**Comment by mrexodia** [comment]
Use this: https://help.x64dbg.com/en/latest/introduction/Expression-functions.html#references

**Comment by mrexodia** [comment]
The documentation of the commands that output to the reference view has been updated with an example as well.

**Comment by Voyager1th** [comment]
![1693536544637](https://github.com/x64dbg/x64dbg/assets/57646967/e43c294e-8eb8-449f-889c-4440ff25221b)
find cip,"hex...."  Failed to read memory, error ERROR_PARTIAL_COPY.

**Comment by mrexodia** [comment]
What Windows version are you on?

**Comment by jamarir** [comment]
Considering 2 instances of the `308202c2308202bea004` pattern are to be found, executing the following [findmemall command](https://help.x64dbg.com/en/latest/commands/searching/findallmem.html) in the `Log` tab would give their respective [references's addresses](https://help.x64dbg.com/en/latest/introduction/Expression-functions.html?highlight=reference#references):
```sh
findmemall 0,308202c2308202bea004; ref.addr(0); ref.addr(1);
```

<div align="center">
  <img width="239" height="83" alt="Image" src="https://github.com/user-attachments/assets/cfb0eb49-65ab-4101-8dfe-3f72bae61cf4" />
</div>
