### ISSUE TITLE
improve callstack output

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#301]
anyone has ideas? Currently it just traverses the stack and finds if the previous instruction is a call (similar to [this](https://gist.github.com/mrexodia/892ff9958d6cae36d867) IDA script)

**Comment by Nukem9** [comment]
StackWalk64? It's single-threaded unfortunately, but I don't think it is used anywhere besides the GUI code.

**Comment by Nukem9** [comment]
https://github.com/x64dbg/x64dbg/commit/ac9953fb7c873f9c512770668e691a4893b38d06

**Comment by mrexodia** [comment]
improve: maybe add push + ret as synonym for a call.

**Comment by Nukem9** [comment]
Technically fixed in https://github.com/Nukem9/x64dbg/commit/eda641f6a77e709b1623f0a731b9eb4231c40941, however the old code was axed....
