### ISSUE TITLE
plugin function `DbgCmdExec` return result

### ISSUE THREAD

**Issue by weituotian** [x64dbg/x64dbg#3011]
### Feature type

Plug-ins

### Describe the feature

example:

`DbgCmdExec(‘dis.text(776258A0)’)`

now it return true of false

can it  return string like 'mov edi, edi'  or other result?

**Comment by weituotian** [comment]
> No, you can use the DbgDisasmFastAt API

what if `DbgCmdExec(‘strstr(utf8(reg/addr),"This")’)`,

may be it is necessary to let DbgCmdExec return the result

![image](https://user-images.githubusercontent.com/7270968/216075017-cf42be74-1b4e-4243-b01f-b2a70eebe1b5.png)
![image](https://user-images.githubusercontent.com/7270968/216075056-5d372958-68c2-47ce-b01e-f833f851d800.png)

**Comment by mrexodia** [comment]
If you want to evaluate an expression you should use `DbgEval` (or without error checking `DbgValFromString`).

The `DbgCmdExec` function does not wait for the command to finish executing. If you need that you can use `DbgCmdExecDirect`, but this only returns whether the command was successful. The output is not captured.

**Comment by weituotian** [comment]
@mrexodia there is a question that DbgEval("utf8(reg/addr)") always return 0

```
src/bridge/bridgemain.cpp
BRIDGE_IMPEXP duint DbgValFromString(const char* string)
{
    duint value = 0;
    _dbg_valfromstring(string, &value);
    return value;
}
```

may it return the true result?

**Comment by mrexodia** [comment]
As I said, there is no way to get the string an expression evaluates to from the API.

**Comment by weituotian** [comment]
so it be a Feature, you can reopen the issue
provide a way to get the string from expression evaluates 
it is the important part to develop a plugin

**Comment by mrexodia** [comment]
If you want to read a string from C++ you can just do this:

char buffer[1024];
DbgMemRead(addr, buffer, sizeof(buffer));
puts(buffer)

**Comment by weituotian** [comment]
if i want to use exp `utf8` , `utf16`, i need to rewrite the functions too.
the way is not a good long way to maintain, why not just use what x64dbg now has?
![image](https://user-images.githubusercontent.com/7270968/216227403-ffd00aff-f5b4-4405-84f9-343e8984b484.png)
