### ISSUE TITLE
Get default thread name with GetThreadDescription (WinAPI)

### ISSUE THREAD

**Issue by p0358** [x64dbg/x64dbg#3016]
### Feature type

Quality of life

### Describe the feature

Starting with Windows 10, apps can set thread names on handles with `SetThreadDescription`. Then later this name can be retrieved by [`GetThreadDescription`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription).

It would tremendously help if x64dbg could dynamically get address of the latter function if it's available, and populate the thread names in Threads tabs using it.

More and more apps are setting up descriptive debug names for their threads, so this would aid a lot instead of trying to manually figure out which thread is for what every time. Some other tools support this and it's very useful.

Currently only the main thread is named "Main Thread" by default:
https://github.com/x64dbg/x64dbg/blob/09bc3aed4f8267126d144e379c4fc14e4954113d/src/dbg/thread.cpp#L40-L44

I'd try making a PR myself, but I fear trying to get the codebase to compile and understand would take me a lot of time, while someone who already has the environment set up and knowledge of codebase could probably take a few minutes to implement this...

**Comment by mrexodia** [comment]
You can just build x64dbg.sln with the latest visual studio. Otherwise just merge the dependencies and x64gui.dll from a snapshot and you’re good to go. Likely the GetThreadDescription needs to be called during enumeration…

**Comment by p0358** [comment]
You were right, I didn't need Qt, and I could successfully use Build Tools 2015 non-XP that I already had installed as-is in VS2022. Would be nice to update the building guide a bit to mention it, that you don't need Qt at all if you don't rebuild UI, to not scare new people off too much xd

**Comment by mrexodia** [comment]
I’m (very slowly) working on moving the build system to CMake, with a fully automated way of fetching dependencies etc. Unfortunately there are some compatibility issues (binary compatible plugins, MSVC runtime, XP support, Python Qt plugins) that are making this a massive slog…
