### ISSUE TITLE
X32dbg

### ISSUE THREAD

**Issue by ahmed22pm7** [x64dbg/x64dbg#3020]
I 
![IMG_20230220_040426](https://user-images.githubusercontent.com/105469178/220265414-c5d4219a-cb78-4148-936e-1f70c7101904.jpg)
trying to to disamble Ex4 file it's loaded on a platform called meta trader and that's an exe but i have to bypass this function called expert remove

Could you tell me how to bypass it

**Comment by Ultritrufnaxx** [comment]
Hi, have you made it this far? I'm stuck in the same place as you.

**Comment by ZehMatt** [comment]
There will be no support for cracking/bypassing things here.

**Comment by ahmed22pm7** [comment]
> Hi, have you made it this far? I'm stuck in the same place as you.

Well i didn't found soultion when you commented this so i give up and i back to to search again now so if i found soultion i will tell you and sorry for replying late i havent entered github since you commented

**Comment by asgg1966** [comment]
Hello, Is there any guide how to override  ExpertRemove function call using x32dbg and patch it to new ex4 file ? Thank you
