### ISSUE TITLE
When X64Dbg debugs something, the module often fails to load at some time. The system is win11

### ISSUE THREAD

**Issue by rmhh888** [x64dbg/x64dbg#3027]
### Operating System

win 11  64Bit 22621.1265

### x64dbg Version

All versions

### Describe the issue

When X64Dbg debugs something, the module often fails to load at some time. The system is win11

### Steps to reproduce

1. 
2. 
3. 
When X64Dbg debugs something, the module often fails to load at some time. The system is win11

### Attachments

When X64Dbg debugs something, the module often fails to load at some time. The system is win11

**Comment by mrexodia** [comment]
Please fill in the template properly and add screenshots/reproduction steps.

**Comment by rmhh888** [comment]
If you have time to open debugging, you will not have this module




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x64dbg/x64dbg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月28日(星期二) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x64dbg/x64dbg] When X64Dbg debugs something, the module often fails to load at some time. The system is win11 (Issue #3027)





 
Please fill in the template properly and add screenshots/reproduction steps.

**Comment by mrexodia** [comment]
Here are some questions:

- What exactly are you doing?
- Are you starting the process through x64dbg?
- Are you attaching to an existing process?
- What is the executable this happens with?
- What does 'often' mean? Does it always fail or only sometimes?
- What exactly fails? Are there any errors in your log?
- Are you running in a VM or natively?
- Do you have any special drivers installed (TitanHide/HyperHide)?
- Do you have any plugins?
- Is the software a game that might have anti-cheat interfering?
