### ISSUE TITLE
Memory map highlighting bug

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#3029]
### Operating System

Win10 x64 10.0.22621.1265

### x64dbg Version

Nov 26 2022

### Describe the issue

![vmware_VtsqMGvwHi](https://user-images.githubusercontent.com/5781692/221967251-8cf8a626-4f73-4b40-b998-7988de7f8d43.gif)

### Steps to reproduce

1. Pause execution
2. Go to memory map
3. Click on the current RIP item as in the gif

**Comment by mrexodia** [comment]
Nov 2022 ;)

**Comment by justanotheranonymoususer** [comment]
Oh, sorry, someone needs to update more often😶
