### ISSUE TITLE
Complete loss of data and debugger crash after multiple restarts

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#303]
When debugging an application and restarting the process being debugged
many multiple times, the debugging data gets completely lost and the debugger eventually crashes.

When i re-open the debugger and attach the same application, the BPs and comments are completely lost, also another weird behavior is that some plugin files cannot be read.

Information thrown after crash:

-------------------------------------------------------

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	5550f014
  Fault Module Name:	QtGui4.dll
  Fault Module Version:	4.8.6.0
  Fault Module Timestamp:	55140866
  Exception Code:	c0000005
  Exception Offset:	002ca6c0
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d1d9
  Additional Information 4:	d1d94a13d3609d6b740644c12508f581

-------------------------------------------------------

To reproduce this issue:
1- open/attach any application in the debugger,
2- restart this application more than 15-20 times (or even more, i can't really remember but it's
    around this range).
** EDIT: got it, exactly after restarting 52 times! **

- Don't restart it so fast, leave a second or two between each restart attempt,
   because if you kept pressing the restart button so fast, the debugger will eventually
   become unresponsive to all the debugging buttons (pause, stop, run, ...).

- The number of restart attempts does not have to be necessarily after each other,
   this means you could be debugging an application for hours (and restarting it of course)
   and suddenly this happens, this is when the real pain occurs since all your work will be lost :(
- Using latest snapshot from sourceforge (snapshot_2015-05-11_08-10)

This picture shows an example of the plugin file that couldn't be loaded
exactly before crash, even though it exist in the directory:
![capture](https://cloud.githubusercontent.com/assets/11916365/7725082/a2bbd238-fef7-11e4-9fbf-3f8c5a7c0351.PNG)

**Comment by mrfearless** [comment]
Does it occur when there are no plugins loaded, as in if you move / rename plugins folder and do the same restart x52? Would be able to narrow it down to x64dbg or a plugin resource exhaustion issue perhaps.

**Comment by wk-952** [comment]
i tried that now, i've removed all the plugins, the databases and my custom UI settings
(colors and instructions spaces), so a completely clean installation,
then i loaded an application and placed a BP with a comment and tried again the restarting session,

but the same result :( after exactly 52 restarts the BP and the comment are gone,
this time the difference is that the debugger didn't crash,
so before closing it i added another BP and a comment and restarted the process (restart # 53)
and as i expected both the BP and the comment are gone.

i've actually tried the last 2 steps multiple times (i reached restart # 64) to make sure that any BPs and comments after that will always be deleted, and unfortunately yes that happens.
restart attempt # 51 will always b

**Comment by mrexodia** [comment]
I always love those tests :smile: quite some time ago there was an issue with restarting more than two times. I will try to reproduce the crash after my exams...

**Comment by wk-952** [comment]
I'll try it today or tomorrow with the build before the latest one from sourceforge (with and without plugins) to see if this issue was only introduced in the latest build or not.
wish you all the luck in your exams.

**Comment by mrexodia** [comment]
probably this was fixed in 0c792c96

**Comment by wk-952** [comment]
tried it now,
and the issue is still persistent :(

**Comment by mrexodia** [comment]
freeze wasn't fixed. checking that now

**Comment by wk-952** [comment]
reached restart attempt #116 and no crashes happened :+1: 
but may i ask, what freeze ?!
i didn't have any freezes even after restart #116 and when i closed the debugger it didn't hang

**Comment by mrexodia** [comment]
If you restart very quickly (spam ctrl+f2) it will not respond to input
anymore.

**Comment by wk-952** [comment]
compiled the project after the last 2 commits <da6b666> and <f297c75> and used the
dependencies from the lastest snapshot at sourceforge (snapshot_2015-06-08_01-07),
and now after restart # 18 the debugger crash (exactly at attempt # 19)

information thrown after crash:

-----------------------------

Problem signature:
  Problem Event Name:	BEX
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	55856f4a
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f7ce6
  Exception Offset:	000a7666
  Exception Code:	c0000409
  Exception Data:	00000007
  OS Version:	6.3.9600.2.0.0.256.4

-----------------------------

callstack table:
when i pressed "Debug this application" x64dbg loaded up to debug itself,
but immediately it said "debugging stopped!"

**Comment by mrexodia** [comment]
@wk-952 is this issue still present in the latest snapshot?

**Comment by wk-952** [comment]
No, it was fixed, reached 77 restart attempts and there seems to be no problem.
Thank you very much, you can close this issue if you want.
