### ISSUE TITLE
Restore previous tab location when closing a detached tab

### ISSUE THREAD

**Issue by oleedd** [x64dbg/x64dbg#3035]
### Operating System

Windows

### x64dbg Version

The last

### Describe the issue

Tabs don't return to their positions after "Detach". It is like a bug.

### Steps to reproduce

1. To move a tab.
2. To detach it.
3. To close it.

The tab should return to its last position. Instead of this, it becomes the last tab. And you have to move it again (to the position you want to see it). If you often need to detach some tab, it will be always the last. Please fix.

**Comment by mrexodia** [comment]
You can find the relevant code here and implement it: https://github.com/x64dbg/x64dbg/blob/52bd144e8727bc77dbdf5543891ee32349d95ac8/src/gui/Src/Gui/MainWindow.cpp#L874

**Comment by oleedd** [comment]
Sorry, I just know web programming... I don't know how gui works...

**Comment by nasusonetrick** [comment]
im not sure if its related to the op issue 
but the tabs position keep returning to default every time i close xdbg and open it again 
so lets say i move the symbols tab to be the first before cpu tab, re-opening xdbg will return it to the default not to my custom position .. and its very annoying tbh, i like the tabs i work with the most to be very close to each other 
specially with a big screen

**Comment by mrexodia** [comment]
How did you install **x64dbg** @nasusonetrick ?

**Comment by nasusonetrick** [comment]
> How did you install **x64dbg** [@nasusonetrick](https://github.com/nasusonetrick) ?

using `snapshot_2025-08-19_19-40.zip ` from this official github and extracting it on top of the previous version at first, 
then when i notice the issue i removed the entire folder and extracted the snapshot again on a clean folder,
even tried it on a virtualbox machine with the same issue, being " Tab order back to default position every time i re-open xdbg"

its not a detach / re-attach issue, but rather the program not remembering the tab order position

**Comment by nasusonetrick** [comment]
or maybe xdbg does not have this feature by default ??  
which is to remembers Tabs ( order / docking positions ) 

which part of the code we can add such feature ? 

because we can create a Dictionary array to save tabs ID's with their position something like : 

```
// ID , Position 
TabsOrder = {
[tab_1 , 1],
[tab_2 , 2],
[tab_3 , 3],
[tab_4 , 4],
}
```
then later we save that inside a local .ini file

**Comment by mrexodia** [comment]
https://github.com/user-attachments/assets/1843ec6a-2a32-4b5b-80dd-f4640791747b

It's already implemented, most likely your settings are just not writable. This happens if you install x64dbg in program files or similar.

**Comment by nasusonetrick** [comment]
> 22-21-17-x64dbg-saved.mp4
> 
> It's already implemented, most likely your settings are just not writable. This happens if you install x64dbg in program files or similar.

oh yeah i see, it was a writing permission issue.  
after changing the installation folder permission its fixed now 

amazing thank you man, and my apology for wasting your time
