### ISSUE TITLE
Memory breakpoint problem

### ISSUE THREAD

**Issue by my913176862** [x64dbg/x64dbg#3037]
Operating System
windows
Describe the feature
When x64dbg sets the memory breakpoint, it will set a page each time, set 4 bytes, 2 bytes will be set as a page, or even larger than a page, so the user can not set the size freely.

**Comment by my913176862** [comment]
Is the problem being solved now?

**Comment by mrexodia** [comment]
No it’s a duplicate issue. It won’t be solved unless someone steps up or I need it personally.
