### ISSUE TITLE
Prevent window from closing (hiding)

### ISSUE THREAD

**Issue by GitUser200607** [x64dbg/x64dbg#3046]
### Feature type

Debugging

### Describe the feature

Currently, its not a problem to change skin of Unity Editor to Dark skin - its available for free. But some time ago, free users cannot choose it. The menu option was greyed-out. I know the way to set it, but its not a problem I wish to solve. its just an example.
We can try [Unity Editor 5.6.7](https://unity.com/releases/editor/archive).
When we open Unity.exe with x32dbg and start a project, we can open _File -> Preferences..._ 
Now we see greyed-out Editor Skin = Personal
Usually we can open in x32dbg **Handles** tab and refresh it.
The problem is when the Preferences window looses the focus, it closes (or set visibility to none).

Is there s feature in x64dbg to freeze the window without hacking the code?

**Comment by mrexodia** [comment]
You can pause the process, a feature like this would be too specific to implement in x64dbg itself.
