### ISSUE TITLE
Setting break points on all API calls

### ISSUE THREAD

**Issue by ektwr** [x64dbg/x64dbg#305]
The program is one of the best. Some suggestions:
Please put the abbility to set break points on all API calls like BPMessageBox, etc. like in ollydbg.
This would be helpfull for all who want's to trap message boxes insted of doing this manually like now.
Another great one would be to count how many time a break point accessed.
Also i would like info's how to bypass the "invalid PE' message which drives the debuger not analyzing and run it at all. 
Thanking in advance.

**Comment by wk-952** [comment]
+1 for that :+1: 
also if possible delete all BPs on a certain API call.

**Comment by NtQuery** [comment]
I think you should open 3 issues for your 3 requests.

1) Why do you need "break on all api calls". This is quite useless, because you can set a breakpoint directly on MessageBoxA inside user32.dll and you will break on all api calls... and you can manipulate the paramters of course.

**Comment by mrexodia** [comment]
this feature is more something for a plugin. the `invalid pe` message is a little misleading because it actually means `CreateProcess` failed. Usually this means windows won't run the executable either, which makes it impossible to debug.

closing this issue and creating one about the 'logging breakpoints'

**Comment by chriskaza81** [comment]
IN dbg64  I am trying to find a message "Activation Failed" (messagebox)      after i click 'Register" button  but unfortunatelly i can not see any messages so i am unable to find the loop . Is there any oter way i can find the loop so i can start debugging ?
