### ISSUE TITLE
Set current value of a register to the value saved in a trace from the register view in trace

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#3050]

**Comment by sid-38** [comment]
Hey,
I was thinking about working on this issue, if that's okay. Here's the plan I had in mind.

Create a QAction in TraceRegisters.cpp and connect it to a public slot defined in TraceRegisters itself. The public slot would be using the DbgValToString function to set the current register value, similar to how the setRegister function in CPURegistersView.cpp work.


Let me know if this is the right way to fix this issue.

**Comment by mrexodia** [comment]
Yeah, sounds about right!
