### ISSUE TITLE
win11 - arm - 22H2 - cannot change cmdline

### ISSUE THREAD

**Issue by WHOLETTHEDOG-OUT** [x64dbg/x64dbg#3054]
### Operating System

win11 - arm - 22H2

### x64dbg Version

snapshot_2023-03-04_02-26.zip

### Describe the issue

<img width="563" alt="image" src="https://user-images.githubusercontent.com/13184758/226279265-213c410c-f563-4622-8b83-50620ca8b085.png">

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Don’t speak Chinese.
