### ISSUE TITLE
BridgeLoadLibraryChecked call conv

### ISSUE THREAD

**Issue by yecate** [x64dbg/x64dbg#3057]
https://github.com/x64dbg/x64dbg/blob/7e17c2ccd27ce6088ad906566c998438f5781133/src/exe/signaturecheck.h#L8
https://github.com/x64dbg/x64dbg/blob/7e17c2ccd27ce6088ad906566c998438f5781133/src/bridge/bridgemain.cpp#L66

There seems to be a problem here. In x64dbg.exe, the calling convention used is __cdcel, but bridgemain is defined as winapi (__stdcall) calling convention.

**Comment by mrexodia** [comment]
Thanks, will be fixed soon!
