### ISSUE TITLE
bc command can't clear a cached breakpoint

### ISSUE THREAD

**Issue by newmsk** [x64dbg/x64dbg#3058]
### Operating System

Win7 64bit

### x64dbg Version

Mar 4 2023

### Describe the issue

bc command can't clear a breakpoint which in an unloaded module

### Steps to reproduce

1. try to load a.dll with regsvr32, make sure the a.dll module is loaded
2. set a software bp in a.dll
3. restart the debugger,  and now the a.dll is not loaded
4. try to use bc command to clear all the breakpoints and it will fail

### Attachments

![image](https://user-images.githubusercontent.com/12833886/228593086-e4c88bd3-c8ab-47fa-b505-135cd6eebc3e.png)

and I read the source code, maybe it's the problem of this part code
![image](https://user-images.githubusercontent.com/12833886/228596044-7e7f9bdf-f3de-45a9-afca-8a26a70d950a.png)
but when execute bc command

![image](https://user-images.githubusercontent.com/12833886/228600904-e2b86bc7-040e-436e-9c9e-7fd821bbdc99.png)
hope I made it clear

**Comment by mrexodia** [comment]
Thanks for your report and investigation! Currently there are some weird things in the breakpoint system that need to be refactored to solve this properly. I started a while ago with 26a776cca5788dce2f19ede7e62f3e82ddc502a2, but it needs testing for all cases and there are a few `TODO` comments left...
