### ISSUE TITLE
 loading of PDB will crash

### ISSUE THREAD

**Issue by avboy1337** [x64dbg/x64dbg#3059]
### Operating System

win 11

### x64dbg Version

latest

### Describe the issue

The default loading of PDB files causes a crash. It could be due to the large size of the PDB or other reasons. I tested it with Chrome.

### Steps to reproduce

1. open x32dbg.exe
2. attach process
3. make sure the pdb file is in x32dbg directory, I test file of chrome.dll
4. crash

### Attachments

https://drive.google.com/file/d/1j-f2b-nFXAHsXxrsiXvnuKWNaMkewXCN/view?usp=share_link

**Comment by ZehMatt** [comment]
It's most likely running out of memory depending on the PDB size.

**Comment by mrexodia** [comment]
Try using the latest msdia140.dll, recent chrome pdbs are using a new
format too.

**Comment by avboy1337** [comment]
> 

is there another way to patch it ? Because we can see windbg won't crash either.

**Comment by mrexodia** [comment]
Like I said, replace msdia140.dll with the latest version.

**Comment by avboy1337** [comment]
> 

OK，I am going to have a try
