### ISSUE TITLE
Crash in Snowman window

### ISSUE THREAD

**Issue by AVJoKe** [x64dbg/x64dbg#306]
Hi, 

In the last snapshot from Sourceforge (snapshot_2015-05-25_12-07.7z) I get a crash of the debugger when using right click in the "Instructions" window of the Snowman tab. This happens either a file is loaded or not.

Keep the good work going! 

Regards
AVJoKe

**Comment by mrexodia** [comment]
Yes, already fixed it. Will get out a new build later on.

**Comment by AVJoKe** [comment]
Thanks!
