### ISSUE TITLE
Random Tool and Settings Tab Symbols in W10 x64 System

### ISSUE THREAD

**Issue by dogisay** [x64dbg/x64dbg#3063]
### Operating System

Windows 10 64Bit Build 19044 and 17134 and Windows Server 2019 64Bit Build 17763 

### x64dbg Version

Dec 12 2022

### Describe the issue

The tool symbols change randomly every x64dbg startup.

The last date of use of the program without the problem: 06.04.2023
The date the problem was noticed: 07.04.2023

Tab symbols must be constant for my automation program.

Thank you for your interest and effort.
Kind regards.

### Steps to reproduce

1. Use these windows versions: Windows 10 64Bit (Build 19044 or 17134) or Windows Server 2019 64Bit Build 17763 (not tested in others)
2. Use this x64dbg version: Dec 12 2022 (TitanEngine)
3. Run as administrator or normally.

### Attachments

![2023-04-07_10-40-48](https://user-images.githubusercontent.com/30574737/230565415-73e2e675-2536-446a-bc5e-6a006c656c3f.png)
![2023-04-07_10-05-59](https://user-images.githubusercontent.com/30574737/230565457-18458bce-cef7-4977-be69-314a9a020388.png)

**Comment by dogisay** [comment]
The problem in question continues but I solved the automation problem I had by customizing the shortcuts.

**Comment by mrexodia** [comment]
It’s easter

**Comment by mrexodia** [comment]
You can disable this in settings.

**Comment by dogisay** [comment]
Thank You and Happy Easter !
