### ISSUE TITLE
Can't step into x64dbg_bridge

### ISSUE THREAD

**Issue by kratkoeimya** [x64dbg/x64dbg#3064]
### Operating System

Windows 10 64 bit

### x64dbg Version

latest

### Describe the issue

 my goal was to take a deeper look at how it sets up its GUI. I'm compiling x64dbg from source in vs2019. Everythng works fine, but I tried to set up a breakpoint in the WinMain function when it's calling BridgeStart()  but I can't step into it it just continues execution as if the breakpoint wasnt there. How do I go about this?

### Steps to reproduce

1. go to WinMain
2. Set a breakpoint in the call to BridgeStart
3. Try to step into

**Comment by mrexodia** [comment]
Probably you didn’t compile the GUI?

**Comment by kratkoeimya** [comment]
yeah I can't find out how to compile  x32gui.dll

**Comment by mrexodia** [comment]
Try the steps on the wiki, there’s an extensive guide there.
