### ISSUE TITLE
x32dbg error finding safe library loading functions

### ISSUE THREAD

**Issue by JamesBalazs** [x64dbg/x64dbg#3068]
Steps to reproduce:
- Download snapshot_2023-04-14_20-57
- Extract all
- Run release/x96dbg.exe
- Install all the options
- Restart PC
- Open release/x96dbg.exe
- Select x32dbg
- Get "BridgeInit Error" - "Error finding safe library loading function"

Fresh download of x32dbg does not run on Windows 10

**Comment by mrexodia** [comment]
Thanks, will fix it again 😂
