### ISSUE TITLE
How to break using condition breakpoint when watch address may be null?

### ISSUE THREAD

**Issue by zeroclear** [x64dbg/x64dbg#3070]
Version Jun 12 2022
I need to watch a memory address, such as rsp+0x28, it‘s content  [rsp+0x28] also a memory pointer, and I hope to break execution when the second byte of [rsp+0x28] satisfies some condition, such as [[rsp+0x28]+2]==0x80. But [rsp+0x28] may be a null pointer, read operation will fail, x64dbg always break when it fail, just like make breakpoint without condition.
In programming, I can check address first, and use && operator to bypass other condition, if it's invalid memory, read operation would not be executed. I tried mem.valid(xxx) && xxx==yyy, but it still failed. How to solve this problem?

**Comment by mrexodia** [comment]
You can use `ReadPtr(rsp+28)`. It will return 0 if the memory isn’t readable.

**Comment by zeroclear** [comment]
Thank you, it works. I replace bracket to function, ReadByte(ReadPtr(rsp+0x28)+2) comes normal.
