### ISSUE TITLE
x32dbg.exe is quarantined by eset antivirus

### ISSUE THREAD

**Issue by AbedKarmi** [x64dbg/x64dbg#3072]
### Operating System

windows 11 22621.1555

### x64dbg Version

Apr 15 2023

### Describe the issue

Recently, since last few versions, ESET antvirus quarantines x32dbg.exe and mark it as suspicious object.

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Crazy, it’s almost like they’re incompetent… 🙄
