### ISSUE TITLE
Bug in x86 Win7, Dll not register dbghelp.dll

### ISSUE THREAD

**Issue by postman1year** [x64dbg/x64dbg#3076]
### Operating System

Win7 x86

### x64dbg Version

27 April 2023 two versions

### Describe the issue

Bug in x86 Win7, Dll not register dbghelp.dll in package 4-27 two versions, but before 4-27, I can use x32dbg.exe only one this file in the 4-15 package replace to  any new version than 4-15, can solve all problem, SO, I guess 4-15 x32dbg.exe is the only Correct file than others package
![1](https://user-images.githubusercontent.com/7483788/235140343-04568a09-d28f-4541-a52c-c49ba14be239.jpg)
![2](https://user-images.githubusercontent.com/7483788/235140369-440d41c5-d436-4492-8fd8-65fe6fba6d40.jpg)

### Steps to reproduce

1. 
2. 
3.

**Comment by postman1year** [comment]
the packages two 4-27 and one 4-15 can perfect running in Win10 22H2 x64, but only 4-15 or replace x32dbg.exe to 4-27 can running in Win7 32bit x86 system!! So please check the differents between 4-15 x32dbg.exe and 4-27

**Comment by mrexodia** [comment]
Not exactly sure what the problem is, `dbghelp.dll` isn't used. What is the error you are seeing exactly?

**Comment by mrexodia** [comment]
Windows 7 x64:

![image](https://user-images.githubusercontent.com/2458265/235162176-775f8197-e0ea-4b5a-b7c3-1bfa1c87168e.png)

Windows XP x64:

![image](https://user-images.githubusercontent.com/2458265/235162839-79c5a5eb-8efc-435a-bd10-733de68f31b2.png)

Windows XP x86:

![image](https://user-images.githubusercontent.com/2458265/235163501-2a47c100-7a95-43b1-9bec-968f9530acd8.png)

I don't have 7 x86 but I don't see why it wouldn't work. Are you using the `dbghelp.dll` shipped with x64dbg?

**Comment by postman1year** [comment]
I just install a new Win7 x86 pro system in VirtualBox, and the same problem appear with 4-28 and 4-27(two versions), but 4-15 is very good(no any problem), and if I copy and replace just only one file in x32 folder (x32dbg.exe) to the 4-28 and 4-27 packages, they all run no problem, SO only can do is replace with 4-15 (x32dbg.exe) to new packages's x32 folder, can slove the probllem run in Win7 x86 32bit OS.
![333](https://user-images.githubusercontent.com/7483788/235294509-152373f2-7c85-462a-a597-3af1aba2161a.jpg)

**Comment by postman1year** [comment]
After I replace only one file (x32dbg.exe in 4-15 x32 folder) to newer than 4-15 (ie 4-27 two versions and 4-28), It will be no problem!!!!
![444](https://user-images.githubusercontent.com/7483788/235295013-ca94ccc3-06cd-43c2-8bad-56aac542793c.jpg)

**Comment by mrexodia** [comment]
As you can see the dbghelp.dll is rejected because it has an invalid signature. Can you show the code signature dialog in the file properties?

**Comment by postman1year** [comment]
> As you can see the dbghelp.dll is rejected because it has an invalid signature. Can you show the code signature dialog in the file properties?

Yes, I can show the code signature dialog in the file properties of dbghelp.dll, buit it is expired(2017), only x32dbg.dll show in 2023, others dll is 2017 and all expired.

**Comment by mrexodia** [comment]
Yeah please show a screenshot. It doesn’t matter that the certificate expired, as long as it has a timestamp proving the DLL was signed before the expiration date.

**Comment by postman1year** [comment]
![555](https://user-images.githubusercontent.com/7483788/235302844-312731d9-0f8c-4ec8-945b-c1e7b79f26be.jpg)

**Comment by mrexodia** [comment]
Yeah I just reproduced this problem. The solution is to update the root certificate store to the latest version: https://support.microsoft.com/en-us/topic/support-for-urgent-trusted-root-updates-for-windows-root-certificate-program-in-windows-a4ac4d6c-7c62-3b6e-dfd2-377982bf3ea5. In your case:

[Windows6.1-KB3004394-v2-x86.msu](https://download.microsoft.com/download/0/4/7/0473DB9B-16DE-41C6-A02A-4CBEEB04E777/Windows6.1-KB3004394-v2-x86.msu)

After installing this update everything works fine on my side:

![image](https://user-images.githubusercontent.com/2458265/235305118-d8bf24a9-15af-4afc-9fa6-f0609c410e85.png)

**Comment by postman1year** [comment]
> Windows6.1-KB3004394-v2-x86.msu

Yes, thank you very much, I solve the problem after install [Windows6.1-KB3004394-v2-x86.msu]
