### ISSUE TITLE
Symbols missing from standard libs

### ISSUE THREAD

**Issue by mich040m** [x64dbg/x64dbg#3078]
### Operating System

win 11 64 22621.1555

### x64dbg Version

Apr 7 2023

### Describe the issue

Symbols are not complete. There are missing symbols for a lot of different calls which come from the user code that are calls to standard C/C++ libraries. Eg here is a comparison between ghidra.

### Steps to reproduce

1. Debug any program that use standard libraries 
2. Notice correct symbols aren't there

### Attachments

![Screenshot 2023-04-29 081802](https://user-images.githubusercontent.com/39919912/235287377-b3f59a95-c52b-40f3-ac7d-f04ea7f3c71f.png)

**Comment by mrexodia** [comment]
You’re showing two different parts of the code.

**Comment by mich040m** [comment]
Its the same code, here I made some arrows so its easier to see, also check the memory addr. Also another example.

![1](https://user-images.githubusercontent.com/39919912/235294790-b4f93867-4ceb-4786-aa51-06377c308a06.png)

![2](https://user-images.githubusercontent.com/39919912/235294745-76aae830-0ca6-49a8-9878-79cd3bca9542.png)

**Comment by mrexodia** [comment]
I don’t think these are symbols. Ghidra automatically recognizes statically linked standard library functions, x64dbg doesn’t. Symbols come from exports or PDB files.

**Comment by mich040m** [comment]
Ah, I understand, thank you. Could this be a feature request, then?

**Comment by mrexodia** [comment]
I’m pretty sure there’s already an issue somewhere, but this is more something for a plugin. One such plugin is called idenLib, but there’s a few others too.

Doing full program analysis isn’t really a goal for x64dbg, so it’s unlikely to be implemented…
