### ISSUE TITLE
x64dbg Base Address Retrieval Issue

### ISSUE THREAD

**Issue by laiyierjiangsu** [x64dbg/x64dbg#3081]
### Operating System

Win10

### x64dbg Version

30. April ,2022

### Describe the issue

In the x64dbg symbol window, the loaded module information is displayed, with the first column showing the base address of the module. For example, if module A is loaded and its address value is 0x800000. According to the official x64dbg documentation, using [A] should output the base address of the module. However, in my test, it displays 0x300905A4D instead of the base address of the module shown in the symbol window. Why is this happening?

### Steps to reproduce

1.mmdevapi.dll 0x7FFC0314000
![image](https://user-images.githubusercontent.com/5535552/235345931-f14a944e-0693-49cf-afe4-d39e57667122.png)

2.  In Command windows, type [mmdevapi.dll] , the output is 
![image](https://user-images.githubusercontent.com/5535552/235346030-3e04ee91-b19b-4b79-a329-cd9e55637964.png)

3. I think I miss something important ,could anyone tell me why?

**Comment by mrexodia** [comment]
You are not reading the documentation right. Just `mmdevapi.dll` will return the base, `[]` reads a pointer-size from that base.

**Comment by laiyierjiangsu** [comment]
Thanks , you are right .mmdevapi.dll is what I want.

But if you are right,  "Loaded module bases "  in the following document  isn't  image base of a module , I just can't figure it out. Can you explain it more? What is the difference between "Loaded module bases " and "imagebase"?
[document link](https://help.x64dbg.com/en/latest/introduction/Values.html?highlight=imagebase#loaded-module-bases)
![image](https://user-images.githubusercontent.com/5535552/236196480-a5a0ef83-70e6-4f19-aea3-ecaddf4e7410.png)

**Comment by mrexodia** [comment]
I see where the confusion is coming from, I’ll update the documentation to clarify.

The syntax `[something]` is often used in technical documentation as an indication that you need to replace the whole thing. In this case `[module]:imagebase` would become `mydll.dll:imagebase`.

As mentioned these are aliases of each other, there is no difference between the “module base” and “image base” conceptually.

**Comment by mrexodia** [comment]
Updated the documentation, thanks for the feedback!

**Comment by laiyierjiangsu** [comment]
You're welcom . This is what I should do. Thanks you  a lot too.
