### ISSUE TITLE
x64dbg updates menu bug

### ISSUE THREAD

**Issue by kemalyuce** [x64dbg/x64dbg#3082]
### Operating System

windows 10 22H2 b19045.2913

### x64dbg Version

30 apr 2023

### Describe the issue

When I run the x64dbg64 update menu, the following error message appears

### Steps to reproduce

1. click "Help" menu
2. click "check for updates"
3. 

### Attachments

![x64dbg update bug](https://user-images.githubusercontent.com/1279565/235367132-a3ce27fe-f6ec-4d35-9810-f5275e5f933c.PNG)

**Comment by kemalyuce** [comment]
[dump-11052023_1147060829.zip](https://github.com/x64dbg/x64dbg/files/11450249/dump-11052023_1147060829.zip)

**Comment by kemalyuce** [comment]
I found the source of the problem. I deleted the ssleay32.dll and libeay32.dll files in the windows\system32 folder. The problem was solved.

**Comment by mrexodia** [comment]
Oh thanks! Probably should preload them from the x64dbg directory to prevent this error in the future.
