### ISSUE TITLE
Scan for patches

### ISSUE THREAD

**Issue by rxznve** [x64dbg/x64dbg#3084]
### Scan for patches

Hello!

Please add functionality that allows you to compare the selected module in the process memory with the module on disk. In Cheat Engine this is called "Scan for patches". This is a very useful thing and I am extremely surprised that no one has yet asked for it.

https://i.imgur.com/wZ9MKBf.png

**Comment by ZehMatt** [comment]
Couldn't you simply do this using Plugins?

**Comment by torusrxxx** [comment]
You can already use Cheat Engine to do that, so just continue using it. It's a very low priority task for x64dbg development.
