### ISSUE TITLE
Command to change XMM registers

### ISSUE THREAD

**Issue by justanotheranonymoususer** [x64dbg/x64dbg#3087]
### Feature type

Debugging

### Describe the feature

Sounds basic so maybe already exists, but I didn't find. I wanted to set a conditional breakpoint which changes the value of a register. For example, after line `xor eax, eax`, I want eax to hold 1234. So I wanted to set a bp with no stop, no log, only cmd which will do something similar to windbg `r eax=1234`. Does something like this exist?

Also having support for XMM registers will be very helpful.

**Comment by mrexodia** [comment]
Sure, you can use the 'command' `eax=1234`. For XMM registers there isn't a way to do this, because expressions are max pointer size.

**Comment by justanotheranonymoususer** [comment]
I assume you can add a command for that? Like: `setxmm 1, 112233445566778, 2233445566778899` will be equivalent to setting XMM1 to `22334455667788990112233445566778`.  And maybe other command syntaxes to use floats:
* Float: setxmmf 1, 0.1, 0.2, 0.3, 0.4
* Double: setxmmlf 1, 0.1, 0.2
* Word: setxmmw 1, 11, 22, 33, 44, 55, 66, 77, 88
* Dword: setxmmdw 1, 11, 22, 33, 44

Would that be possible?

**Comment by torusrxxx** [comment]
We can't use 64-bit integer here because it doesn't work in 32-bit environment.

**Comment by justanotheranonymoususer** [comment]
I don't really know what's best but right now there's nothing. Maybe we can start with assigning from memory. Like there's `rax=[12345678]` and [memcpy](https://help.x64dbg.com/en/latest/commands/memory-operations/memcpy.html) maybe it's possible to do `regcpy xmm0,12345678`.

**Comment by mrexodia** [comment]
Yeah I agree something should be done. The issue is that x64dbg’s expression system is primitive and doesn’t have types. My short term proposal would be to make sure plugins can manipulate the XMM context (I think it’s already done) and then add example commands to Dotx64dbg.

I also don’t think it’s a bad idea to add specialized commands to set the xmm state, but it gets kinda tricky if you also want to read values out of there…

**Comment by torusrxxx** [comment]
Maybe the first step could be implementing "movups" and the like, in the same way as a processor assembly.
