### ISSUE TITLE
Add Navigate Backward and Navigate Forward (like Visual Studio)

### ISSUE THREAD

**Issue by gwotang** [x64dbg/x64dbg#309]
Address Navigate Backward and Navigate Forward ()

http://blogs.msdn.com/b/zainnab/archive/2010/03/01/navigate-backward-and-navigate-forward-vstipedit0024.aspx

The goal is to remember interesting locations so that you can recall where you have been working without remembering so many locations

**Comment by mrexodia** [comment]
Luckily for you this is already implemented. Try using the num +/- buttons.
