### ISSUE TITLE
x64dbg BREAKPOINT crash

### ISSUE THREAD

**Issue by uragan1987** [x64dbg/x64dbg#3099]
### Operating System

win10 x64 20H2 19042

### x64dbg Version

tested with snapshot_2023-05-12_12-32 or Jun 1 2021

### Describe the issue

maybe somebody can explain me why:

i have success to break same adress with Cheat Engine VEH Debug method.

But with x64dbg application crash with TitanEngine and GleeBug

Is there maybe a way to get it workes with TitanEngine?

### Steps to reproduce

start application
attach with x64dbg OR cheat engine
create Hardware OR Memory or Software Breakpoint

**Comment by mrexodia** [comment]
Without the required reproduction steps it is not possible to do anything. From your description it's unclear if x64dbg itself crashes (in which case you should upload a crash dump) or if the application crashes. If it's the application you should make sure there is no `ThreadHideFromDebugger` flag set.

**Comment by uragan1987** [comment]
application is crashed,  x64dbg is fine
ThreadHideFromDebugger is not set, still crash

use x64dbg->Pause  that immediately crash my client

whats different from CE VEH to X64DBG at breakpoint system?
do X64DBG not support VEH?

**Comment by mrexodia** [comment]
No, x64dbg uses the Windows debug api. There is no support for SEH. What are you debugging exactly?

**Comment by uragan1987** [comment]
This gamehttps://gameforge.com/de-DE/play/aion_classicInteresting, how this VEH debugger works and is it a hudge act to add thia to x64dbg?Am 20.05.23, 14:01 schrieb Duncan Ogilvie ***@***.***>:

   
  No, x64dbg uses the Windows debug api. There is no support for SEH. What are you debugging exactly?

**Comment by mrexodia** [comment]
Feel free to try.
