### ISSUE TITLE
please update the version of QT GUI

### ISSUE THREAD

**Issue by hheehhaa** [x64dbg/x64dbg#3104]
### Feature type

Other

### Describe the feature

Hi, I think the version of GUI which is 5.6.3 is a little old. I tried many times to build QT GUI with QT6.6, but it is failed. 
Could you please update the version of QT to be greater than 6.2, and make an easier lesson to the building process.
many thanks!

**Comment by torusrxxx** [comment]
We can't upgrade to a QT version that doesn't support Windows XP. We would like to maintain source code compatibility with new QT and Visual Studio versions though, and you are welcome to help.

**Comment by mrexodia** [comment]
Yeah it’s on my internal TODO to build a binary-compatible Qt 5.6.3 version that runs on XP and uses a “modern” (Visual Studio 2019) compiler. This is a lot of work and I have to set up an automated test infrastructure with all the current plugins to make sure nothing breaks, so this will take quite a while…

**Comment by hheehhaa** [comment]
Great thanks for your invitation, i will be free in three months future, and i am willing to join your  group.

> We can't upgrade to a QT version that doesn't support Windows XP. We would like to maintain source code compatibility with new QT and Visual Studio versions though, and you are welcome to help.

**Comment by hheehhaa** [comment]
OK, take your time.  Great thanks for your reply.

> Yeah it’s on my internal TODO to build a binary-compatible Qt 5.6.3 version that runs on XP and uses a “modern” (Visual Studio 2019) compiler. This is a lot of work and I have to set up an automated test infrastructure with all the current plugins to make sure nothing breaks, so this will take quite a while…

**Comment by jmattioni** [comment]
Any progress on updating GUI to compile with newer QT? I am attempting to do it but there are hundreds of compile errors. It appears that QT made huge changes to the APIs.

**Comment by mrexodia** [comment]
It compiles without issues on Qt 5.12 (any Qt5) and the latest VS2022 compiler. Qt6 will never be supported most likely, there is no point considering XP support.

**Comment by jmattioni** [comment]
@mrexodia Thank you. That leaves me with just 3 link errors at the end. I'm using VS2019. The issues are unresolved externals with zydis_wrapper.lib when building the final dll. Here's the output:

`zydis_wrapper.lib(zydis_wrapper.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl std::exception::exception(char const * const &)" (__imp_??0exception@std@@QEAA@AEBQEBD@Z) referenced in function "public: __cdecl std::logic_error::logic_error(char const *)" (??0logic_error@std@@QEAA@PEBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl std::exception::exception(class std::exception const &)" (__imp_??0exception@std@@QEAA@AEBV01@@Z)
zydis_wrapper.lib(zydis_wrapper.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl std::_Container_base12::~_Container_base12(void)" (__imp_??1_Container_base12@std@@QEAA@XZ) referenced in function "public: __cdecl std::_String_val<struct std::_Simple_types<char> >::~_String_val<struct std::_Simple_types<char> >(void)" (??1?$_String_val@U?$_Simple_types@D@std@@@std@@QEAA@XZ)
zydis_wrapper.lib(zydis_wrapper.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * __cdecl std::_Winerror_map(int)" (__imp_?_Winerror_map@std@@YAPEBDH@Z) referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl std::_System_error_category::message(int)const " (?message@_System_error_category@std@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@H@Z)
..\..\bin\x64d\x64gui.dll : fatal error LNK1120: 3 unresolved externals`

There are also warnings about MSVC lib mismatch. I don't have VS2017, but you mentioned that you used VS2022. Is there an issue with using VS2019?

Thanks.

**Comment by jmattioni** [comment]
@mrexodia what VS toolset are you using when compiling with VS2022? Thanks.

**Comment by jmattioni** [comment]
OK, it's working. Used the VS 2017 toolset combined with the Win 10 SDK v10.0.18362. Also important is to run 
windeployqt.exe --force x64gui.dll

Otherwise, that dll fails to load.
