### ISSUE TITLE
The Chinese characters of the debugging program are not blank in the Windows 7 system

### ISSUE THREAD

**Issue by Mr-zny** [x64dbg/x64dbg#3107]
### Operating System

windows7 

### x64dbg Version

only testing all 2023

### Describe the issue

Running the latest version of X64dbg under the Windows 7 system will not display Chinese characters in the disassembly window, which is blank. If searching for Chinese characters can result in results, but cannot display Chinese characters properly.

### Steps to reproduce

1. 
2. 
3. 

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/80701103/e8abda7b-a34a-46f6-9f0b-dde8714e11c0)

**Comment by torusrxxx** [comment]
Windows 7系统中没有发现你反映的问题，字符串搜索能搜到汉字，也能正常显示，请检查是否是系统问题

**Comment by Mr-zny** [comment]
可能是系统版本的原因，修改字体（具体忘了）可以解决，使用x64dbg_tol插件则任何字体都可以

**Comment by popwilly** [comment]
same issued here . can not find string because unicode are chineses
