### ISSUE TITLE
agents.h missing

### ISSUE THREAD

**Issue by sadida69** [x64dbg/x64dbg#3112]
### Operating System

windows 10, x64, 1904

### x64dbg Version

2023-05-25_00-26

### Describe the issue

after following the steps described in the wiki, I downloaded vs 2013, the correct qt version and i've done all the steps but when I try to compile the project, QT creator warns me that a agents.h file is missing in Bridge.h

I'm sure this file is not  a part of QT nor is it shipped with this repo, how do I go about this?

### Steps to reproduce

1. Follow the wiki guide to compile from source
2. 
3. 

### Attachments

![изображение](https://github.com/x64dbg/x64dbg/assets/135677434/f11a51e8-8879-4038-bf7a-653c41fd6147)

**Comment by torusrxxx** [comment]
agents.h is part of [Asynchronous Agents Library](https://learn.microsoft.com/en-us/cpp/parallel/concrt/asynchronous-agents-library?view=msvc-170). But I have successfully compiled x64dbg with this include removed.
