### ISSUE TITLE
Fix high memory use by trace file reader

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#3114]
Trace file reader uses too much memory.
Especially the `std::vector<REGDUMP> mRegisters;` in all trace file pages use over 1GB memory. This needs to be fixed.
`std::vector<Instruction_t> instructions` is a heavy memory eater as well, although it is filled on demand so memory usage doesn't jump like rocket launch.
Other fields also store mostly redundant data that could be compressed. Luckily all these data are provided to the rest of the program via an interface so fixing that is transparent.
It would be great to run x32dbg in my XP virtual machines with 1GB RAM and while gaming.

**Comment by torusrxxx** [comment]
A new REGDUMP structure without redundant information needs to be created to make it smaller and faster.

**Comment by torusrxxx** [comment]
Currently I plan to divide the REGDUMP into 4 parts, GPR. FPU. SSE and Other. Then a simplified entropy coding is used to compress the registers data while allowing fast random access. The register values are deduplicated. The index to the values array is stored instead, with a variable length 0bit, char, word or full.

**Comment by mrexodia** [comment]
Yeah I guess it sounds good!

**Comment by mrexodia** [comment]
Maybe it would be an idea to vary the amount based on the total available RAM? I don’t mind using 1GB of ram with 32GB available…

**Comment by ZehMatt** [comment]
> Maybe it would be an idea to vary the amount based on the total available RAM? I don’t mind using 1GB of ram with 32GB available…

Until the moment you run x32dbg and all your available ram makes no difference
