### ISSUE TITLE
Can't compile the GUI 

### ISSUE THREAD

**Issue by kratkoeimya** [x64dbg/x64dbg#3119]
### Operating System

Windows 10, 64 bit, Build 19041

### x64dbg Version

Jun 23 2023

### Describe the issue

I'm having a problem trying to compile the GUI.

I've cloned the repo and compiled the project on visual studio 2013. 

When  I hit run I get the message: "x32gui.dll" is missing. Figures, I didn't compile the GUI. 

So I followed the steps described in the wiki, managed to compile the project on vs 2013 with no problems. But when I go to QT creator (version 4.0.3 as per the wiki) I get the following error:

**LNK1181: cannot open input file 'zydis_wrapper.lib'**

The kits seem alright:

![image](https://github.com/x64dbg/x64dbg/assets/130307890/72079d49-250b-40aa-aed7-6c94a57f1e2a)

And indeed this file zydis_wrapper.lib is located at **x64dbg\src\zydis_wrapper\bin\x32**. So what gives?

How do I solve this problem? I've already tried to compile both in release and debug mode.

### Steps to reproduce

1. clone repo
2. compile project in vs 2013
3. open .pro file on qt creator 4.0.3 and hit build

**Comment by mrexodia** [comment]
This should be found automatically after you build x64dbg.sln. Just make sure to also clone submodules

**Comment by kratkoeimya** [comment]
I've done that with 

> git clone --recurse-submodules -b development https://github.com/x64dbg/x64dbg.git

am I supposed to do something else?

**Comment by mrexodia** [comment]
Build x64dbg.sln in Release mode for x64 and then build x64dbg.pro in Release mode for x64 with Qt Creator

**Comment by kratkoeimya** [comment]
> Build x64dbg.sln in Release mode for x64 and then build x64dbg.pro in Release mode for x64 with Qt Creator

Riiight, I finally manage to compile it now. Thanks. I hope i can contribute to the project soon
