### ISSUE TITLE
Calculator causes a random crash

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#312]
When using the calculator for long time, it sometimes causes a crash.
This issue is not persistent, so it's not easy to reproduce,
but it happened for me multiple times specially when using it
for a long period of time

information throw after crash:

------------------------------

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	556507f5
  Fault Module Name:	StackHash_02ec
  Fault Module Version:	6.3.9600.17114
  Fault Module Timestamp:	53648f36
  Exception Code:	c0000374
  Exception Offset:	PCH_94_FROM_ntdll+0x0003D2EC
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	02ec
  Additional Information 2:	02ec2ddb356f6610975e0043eec937bd
  Additional Information 3:	804d
  Additional Information 4:	804d2305650944a81b761d319c6534c0

------------------------------

using (snapshot_2015-05-25_12-07)
on Windows 8.1 64-bit

EDIT: is seems to be happening more often when typing something
like: [ebp-2] or similar many times

**Comment by mrexodia** [comment]
Yea, I also experienced that but at the time I couldn't debug it. Hopefully I can reproduce it :)

**Comment by wk-952** [comment]
i tried to compile the project but this is what i see in Visual Studio 2013 !!!

![err](https://cloud.githubusercontent.com/assets/11916365/8017376/4f6d3cfc-0bf4-11e5-9156-d20879b4ff9e.png)

**Comment by wk-952** [comment]
unfortunately same result :(

----------------------------

 Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	55725575
  Fault Module Name:	StackHash_3dd6
  Fault Module Version:	6.3.9600.17114
  Fault Module Timestamp:	53648f36
  Exception Code:	c0000374
  Exception Offset:	PCH_E5_FROM_ntdll+0x0003D2EC

----------------------------

**Comment by mrexodia** [comment]
Could you attach x64dbg to the crashing program (make x64dbg the JIT debugger) and dump the callstack at the crash (if possible with symbols). I'll keep trying to reproduce it, but I failed multiple times :)

**Comment by wk-952** [comment]
ok, i've set x64dbg as the JIT debugger and loaded the application again,
then opened the calculator and only typed [esp]
and immediately it crashed, so i selected "Debug the program" and x64dbg laoded
up to debug itself.

Very sorry to ask, but could you please tell me how to dump the callstack with symbols?
i'll keep everything as it is until your response, thanks in advance.

**Comment by mrexodia** [comment]
Hi,

x64dbg should be around where the exception happened. Just go to the 'callstack' tab and copy the whole table :)

**Comment by wk-952** [comment]
ok :)

**Comment by mrexodia** [comment]
could you download the symbols in the symbols tab? but this is helpful already!

**Comment by wk-952** [comment]
sure of course, i'll do it now and reproduce the issue

**Comment by mrexodia** [comment]
finally got it to crash!

**Comment by wk-952** [comment]
Good !

this is another attempt with symbols (it took very long to reproduce)

http://rghost.net/private/6vn29yGDH/93bcf6acf32315cfa14232dc6a0d8d63

**Comment by mrexodia** [comment]
i believe i also found the source of the error, it has to do with qt threads. i'm now trying to solve this

**Comment by wk-952** [comment]
:+1: 
amazing!, thank you so much for your hard work

**Comment by mrexodia** [comment]
i'll push a snapshot soon

**Comment by mrexodia** [comment]
if there are still hangs, please reopen this issue

**Comment by wk-952** [comment]
actually a new issue is introduced, now instead of crashing,
the calculator stops calculating expressions as shown in picture
![ads](https://cloud.githubusercontent.com/assets/11916365/8021526/7bf260fe-0ca3-11e5-8a37-f83ed9236272.png)

**Comment by mrexodia** [comment]
oh... thats really weird, probably some deadlock or something damn

**Comment by wk-952** [comment]
i've just compiled the project,
and the calculator is now unusable after the first session of operations.

how to reproduce this:
1) load any application and open the calculator
2) type any number of operation and close the calculator.
3) open the calculator again for the second time

it becomes completely unresponsive to your input,
exactly as shown in the above picture

**Comment by mrexodia** [comment]
just assuming the crashes are gone with the fixes from before

**Comment by wk-952** [comment]
yep :)
spent 15 minutes randomly typing expressions,
while closing and opening the calculator and no crashes occurred.
Thank you so much.
