### ISSUE TITLE
Slow init on windows XP

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#3124]
### Operating System

windows XP

### x64dbg Version

snapshot_2023-06-30_14-26.zip

### Describe the issue

I found that on XP, x32dbg will hang on for a while, and I use older x32dbg to debug, found out the `WinVerifyTrust` call will make x32dbg hang on for a while:
https://github.com/x64dbg/x64dbg/blob/63f6573f5d9a3ad49a2f4845b249c9c052ad5648/src/exe/signaturecheck.cpp#L105

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
There’s no plans to fix this.
