### ISSUE TITLE
Command Line not working

### ISSUE THREAD

**Issue by jakop311** [x64dbg/x64dbg#3127]
### Operating System

Windows 11 64bit, Build 22621

### x64dbg Version

Jul 5 2023

### Describe the issue

From the [Docs](https://help.x64dbg.com/en/latest/introduction/Commandline.html) 
When ran like below, 
2 arguments: **x64dbg** **filename.exe** **cmdline** will debug filename.exe with cmdline as command line.

x64dbg passes "cmdline" as command line inside x64dbg, but it is not working.
it doesn't work with x32dbg too.

### Steps to reproduce

I tried 3 ways running in both 

### x32dbg
1. `x32dbg C:\path\to\file.exe "-c scriptload C:\path\to\script.txt"`
2. `x32dbg "C:\path\to\file.exe" "scriptload C:\path\to\script.txt"`
3. `x32dbg "C:\path\to\file.exe" "scriptload 'C:\path\to\script.txt'"`

### x64dbg
1. `x64dbg C:\path\to\file.exe "-c scriptload C:\path\to\script.txt"`
2. `x64dbg "C:\path\to\file.exe" "scriptload C:\path\to\script.txt"`
3. `x64dbg "C:\path\to\file.exe" "scriptload 'C:\path\to\script.txt'"`

#### In this case
`scriptload "C:\path\to\script.txt"` should be received in the command line of x32dbg/x64dbg

#### Results (Checking the "Change Command Line")
**x32dbg** command line receives
`"C:\path\to\file.exe" scriptload C:\path\to\script.txt`

**x64dbg** command line receives
`"C:\path\to\file.exe" "C:\path\to\file.exe" "C:\path\to\file.exe" scriptload C:\path\to\script.txt`

**Comment by jakop311** [comment]
Either way, it doesn't work as shown in the [docs](https://help.x64dbg.com/en/latest/introduction/Commandline.html). Running it as shown in docs, *cmdline* says **Unknown command/expression**

**Comment by mrexodia** [comment]
Could you show the exact command line you’re using that causes this error? I think there is still a mixup of the process command line and x64dbg commands.

The commands for x64dbg are not documented in the place you linked, that’s the documentation for the x64dbg.exe command line interface…

**Comment by jakop311** [comment]
the command in the bottom part of the window
![x64dbg](https://github.com/x64dbg/x64dbg/assets/98089555/c0ea1dc2-446d-4d9c-9c9c-22aeab5947b8)

**Comment by mrexodia** [comment]
You probably need https://help.x64dbg.com/en/latest/commands/debug-control/InitDebug.html

```
InitDebug "c:\my.exe", "arg1 arg2", "c:\working-directory"

**Comment by jakop311** [comment]
From what I read from the docs and the example you gave me, with the 2nd argument of InitDebug I should be able to run the scriptload like this, right??
`InitDebug "c:\my.exe", "scriptload c:\script.txt", "c:\working-directory"`

**Comment by mrexodia** [comment]
No, there is no connection between the command line of the process and the debugger commands (like scriptload and initdebug). In your case you can use Options -> System breakpoint scripts to execute a script on the start of an application.

**Comment by jakop311** [comment]
I see. Thanks a lot for your help.
