### ISSUE TITLE
Replace fhex and similar macros

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#313]
I stole this idea from IDA:

It is to replace
`dprintf("Delete hardware breakpoint failed: "fhex"\n", bp->addr);`
with
`dprintf("Delete hardware breakpoint failed: %fhex\n", bp->addr);`
by using a find & replace type function.

Just a suggestion though.

**Comment by Nukem9** [comment]
https://github.com/cppformat/cppformat

Considered if this issue is ever actually referenced or implemented.

`dprintf("Delete hardware breakpoint failed: {0:fhex}\n", bp->addr);`

**Comment by mrexodia** [comment]
Yea, that's actually a good idea. I already did a lightweight formatting thing (for the log function) https://github.com/x64dbg/x64dbg/blob/master/x64_dbg_dbg/stringformat.cpp
