### ISSUE TITLE
Some thoughts about my x64dbg

### ISSUE THREAD

**Issue by x64bugreport** [x64dbg/x64dbg#3130]
### Feature type

Other

### Describe the feature

Some thoughts about my x64dbg:
I mainly want to ask, after so many years of development, do you focus on UI development? The function is getting worse and worse.
1. Why do you check the signature with a debugger? Don't accuse me of not applying Microsoft's signature patch, I have a test environment, so what?
![1](https://github.com/x64dbg/x64dbg/assets/34920463/6240cfcb-3954-488a-b5b4-1ee20ac89bd9)
2. When the titian engine is tuned, one page will be displayed once the memory breakpoint is broken. What is the use of this memory breakpoint?
3. alt+m displays read-only memory, and the code can run normally. The memory is actually not read-only at all, and the experience is terrible.
4. Updates are frequent, but sometimes you just change the readme.md and post a new version. What's the point?
5. It’s better to stop changing than to make a mess, and don’t do it at all.
6. Recommend a new debugger, although there are still some problems when it comes out, the author is more attentive than the author of x64dbg, there are not so many problems, and he is active in doing things. Disclaimer that this is not an advertisement.
http://www.ollydbg.com/

**Comment by x64bugreport** [comment]
You open source, I think you are very stalwart, but your attitude is not good, I think you might as well just give up and stop developing. I started using it 5 years ago. So far, bugs that existed before are still present.

**Comment by mrexodia** [comment]
Please report the bugs separately to have a chance at solving them. I’m doing the best I can, but my time is limited and with people like you being cunts it’s not easy to find motivation to work on things I don’t care about personally.

**Comment by mrexodia** [comment]
1. The reason for the signature check is this: https://www.trendmicro.com/en_us/research/23/b/investigating-the-plugx-trojan-disguised-as-a-legitimate-windows.html
2. Duplicate of https://github.com/x64dbg/x64dbg/issues/1513
3. I cannot understand the problem
4. Sometimes updates to dependencies or other minor updates are made
5. 🖕🏻
6. Happy to see there are still people developing debuggers!

**Comment by daaximus** [comment]
China moment.

**Comment by herrcore** [comment]
Certified hood classic 🔥

**Comment by SchizophrenicTerry** [comment]
"chiga chong ching chong" - An intellectual
