### ISSUE TITLE
Highlight mode sometimes works incorrectly with NO-OP instructions 

### ISSUE THREAD

**Issue by shocoman** [x64dbg/x64dbg#3134]
### Gif:
![incorrect_highlight](https://github.com/x64dbg/x64dbg/assets/8329446/5bdde97f-5981-4d34-942b-1d18e82ac172)

### Problem 1:
Some tokens (spaces, commas, etc) of NOP instructions can be highlighted even though they shouldn't be, according to how this feature works with similar-looking non-NOP instructions.
**Cause:** When an instruction has no side effects, all its tokens will be assigned to the type `MnemonicNop` [here](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L358) (to color them all uniformly, I guess). Consequently, the function [ZydisTokenizer::IsHighlightableToken](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L301C29-L301C29) won't be able to filter them out based on the token type alone.
**Solution (the least terrible I've found):** Manually check for certain strings based on the token text in [ZydisTokenizer::IsHighlightableToken](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L301C29-L301C29). Something like this:
```c++
if(token.type == TokenType::MnemonicNop)
    for(QChar ch : " ,{}:+-*")
        if(token.text == QString(ch))
            return false; // do not highlight
```

### Problem 2:
It's only half-related problem but a small one, and it's also shown in the gif above (the first "nop    " case). The instructions that have no operands contain trailing spaces. Aside from the problem 1 above, I think it's only noticeable in exported disassembly (e.g. as a CSV file from the trace view, etc)
**Question:** Why would a function named "tokenizeMnemonic" insert spaces for the operands that may not even exist?
**Solution (probably):** Add a new function that would do the space padding (something like `addMnemonicPadding`). Replace all calls ([all](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L477C33-L477C33) [two](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L177) of them) to [ZydisTokenizer::tokenizeMnemonic(TokenType,QString)](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L452) with an explicit `addToken(type, mnemonic);` and call this `addMnemonicPadding` only if we're sure there are no operands ([here](https://github.com/x64dbg/x64dbg/blob/e796bdce2d3a7f997a61aec007b0237728deefc1/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L125) particularly).

**Comment by foralost** [comment]
This one might be harder, will try to reproduce during the weekend, and maybe solve the problem.

**Comment by foralost** [comment]
I think the main issue is that `nop` instruction has a trailing space for whatever reason, different `nop`s do not have it

**Comment by foralost** [comment]
Ok, I think I have found the bug with potential fix for now (Problem 1).
Later (maybe next year, or right before it, or this week 👀 ) I will see if Problem 2 occurs.
