### ISSUE TITLE
Conditional breakpoint

### ISSUE THREAD

**Issue by siten** [x64dbg/x64dbg#314]
Is the current version supports conditional breakpoints ? How to set conditional breakpoints ?

**Comment by mrexodia** [comment]
Hi, no currently there is no support for conditional breakpoints.

**Comment by siten** [comment]
ok thanks.

**Comment by mrexodia** [comment]
it will be supported one day though, keeping this issue open as a reminder :+1:

**Comment by siten** [comment]
you did a great job

**Comment by mrexodia** [comment]
I did? Don't recall adding conditional breakpoints support

**Comment by siten** [comment]
ok

**Comment by ziab** [comment]
Any update on this? Looking forward for it.

**Comment by mrexodia** [comment]
No update, we are now working on a new debug engine

**Comment by scriptkitz** [comment]
up!
very impotent!

**Comment by my2457** [comment]
Is it possible to write a plugin to support the conditional breakpoint?

**Comment by mrexodia** [comment]
It should be. There are callbacks for breakpoints and it is possible to
resume the debugger from that callback.

**Comment by my2457** [comment]
I see, thanks

Best,
Miao

**Comment by scriptkitz** [comment]
+1

**Comment by torusrxxx** [comment]
Is there anyone already working on this feature? If there isn't I'd like to contribute code. My ideal implementation is: 1.Log text 2.Log expression 3.Automatic resume on condition 4.Run script. These fields are grouped into a structure that links to the BREAKPOINT structure, and can be individually enabled.

**Comment by mrexodia** [comment]
Currently nobody is working on it. The main annoyance is writing a capable
enough boolean expression parser.

For logging there is the stringFormat.cpp (can easily be extended to print
more complex types of needed).

For conditionals I think it should be quite easy to extend the current
expression parser (I will take a look at it today and respond to this issue
with my results).

As for a script to run, I think a command is enough for now (because
scripts give additional complexity and nobody uses them anyway).

If you add just three fields it should be easy to serialize
conditional/logging breakpoints.

**Comment by mrexodia** [comment]
Okay I added evaluation for logical expressions.

**Comment by torusrxxx** [comment]
My first conditional/logging breakpoint is hit.

**Comment by mrexodia** [comment]
Glad to hear! Were the expression parser changes I did useful?

**Comment by torusrxxx** [comment]
Yes, however I have to implement an string formatter to format expressions like `current RDI is {RDI}`
BRIDGEBP structure is expanded. Will it break backward-compatibility with older plugins?

**Comment by mrexodia** [comment]
@torusrxxx yeah probably it will break any existing plugins, however I don't think there are plugins that use this so it should be fine. What is wrong with the current formatter? You can use it like `"current RDI is {0}", rdi`

**Comment by torusrxxx** [comment]
No, the user can't input additional arguments. They must input all the expressions in a single string that is easy to marshal.

**Comment by mrexodia** [comment]
Okay I'm almost finished with a parser for this

**Comment by torusrxxx** [comment]
I haven't worked on this now. It can only log pure text currently.

**Comment by mrexodia** [comment]
I added it in 637aa0f1 it works like you would expect:

```
hex value of rdx: {rdx}
signed decimal value of rdx: {d:rdx}
unsigned decimal value of rdx: {u:rdx}
pointer value of rdx: {p:rdx}
string value of rdx: {s:rdx}
```

**Comment by torusrxxx** [comment]
My local branch is nearly complete. Current implemented feature:
1. Conditional breakpoint for all breakpoint types
2. Replace the system's default log with a user-defined one.
3. Fast resume: If condition is not satisfied and this flag is set, no any GUI/Plugin/Logging is performed, and the debugger just proceed as quickly as possible. If this is not set, user text will be logged(but no system's default log) and the plugin is invoked. Condition "0" is recognised as a shortcut directly in breakpoint handler, enabling higher-performance tracing.
4. Hit counter. There's a counter counting the number of hits. This is unconditional.
5. It's posssible to specify a command that will be executed when the condition is satisfied.
6. Save/load of conditional breakpoints, and GUI for managing conditional breakpoints.
![condition bp branch](https://cloud.githubusercontent.com/assets/15761310/15454084/50b7418c-201d-11e6-8aed-8076f38c3eed.png)

**Comment by mrexodia** [comment]
Looking great! Please don't forget to run `install.bat` so your commits are auto-formatted. Also for expression parser performance you can store an `ExpressionParser` object from 07f18d44 directly in the BREAKPOINT structure. This saves tokenization and preprocessing the expression to RPN. To serialize you can use the new `GetExpression().c_str()`.

**Comment by torusrxxx** [comment]
I'm a anonymous Tor user, and will only commit from the web interface. `install.bat` won't help.

**Comment by mrexodia** [comment]
Alright I'll run the formatter later in that case :+1:

**Comment by torusrxxx** [comment]
I'm worrying about inserting a non-trivally constructable object into `BREAKPOINT`. `BREAKPOINT` is often copied and memset'ed.

**Comment by mrexodia** [comment]
Yeah that's true, probably better to leave it for now it can always be changed in the future.

**Comment by torusrxxx** [comment]
We need to versionify `BRIDGEBP` and any other plugin-related structure so that we can do anything in the future while keeping backward-compatibility.

**Comment by mrexodia** [comment]
Currently plugins have access to far more than they are supposed to. I worked on a rewrite for the communication interface (effectively making the bridge obsolete). This would solve issues like this (by simply making these structures unavailable to plugins).

https://github.com/mrexodia/TemplateHacks

The amount of macro/template stuff makes me doubt this method though. It is far prettier (and adding a new message is far far easier) but it might be confusing especially if it bugs out.

**Comment by mrexodia** [comment]
Have been playing around a little bit with the conditional breakpoints (also made logging support format  strings), but I don't quite understand how logging is supposed to work. Should it log every time the breakpoint is hit or should it only log when the condition resolved to 1?

**Comment by torusrxxx** [comment]
logging is useful only if condition is 0. If it were 1, the debugger halts and you have access to everything.

**Comment by mrexodia** [comment]
Ah makes sense! I pushed some small changes but I consider the issue closed. Thanks a lot, really appreciated!

**Comment by mrexodia** [comment]
I rewrote some of the conditional breakpoint code to drastically reduce the code size (all the logic is in one inline function now), could you please check if everything is still working as intended?

I only changed the thing where logging was not executed if the breakpoint hit. I also added logging condition and command condition allowing people to log/execute a command under certain conditions (separately from the already implemented break condition).

**Comment by FOODzee** [comment]
> Hit counter. There's a counter counting the number of hits. This is unconditional.

@torusrxxx, is it possible to reference this counter in condition and stop at breakpoint if the counter have reached some specific value? If so, what is correct syntax for this?

Typical use case for this is to run program debugging twise to stop at some point just before a crash will happen: at first run the breakpoint is disabled and just counting how many times (N) execution passed through marked point, and at second run the breakpoint is enabled under condition to stop once the counter reached N-1.

**Comment by torusrxxx** [comment]
It's currently not possible to do it, however you have some workaround. You can use "bpgoto" feature to direct the program to some patch area, make some comparison there and then let it trigger a second breakpoint if your counter reaches the value.
Such flexible feature as you describing will be enabled in the upcoming script controllable conditional breakpoint with which you can write a script to evaluate the break condition.

**Comment by MrIQZero** [comment]
Hello guys, Kinda new to this thing. Going to keep it short.
I want to know is there any way i can put 2 commands when a hardware breakpoints condition is met.
Or simply i want to run two commands one after another but automatically, Can i also point to the script which can do the same i cant seems to find any documentation regarding the same would be great if any of you can help me . Thanks.

**Comment by mrexodia** [comment]
You cannot directly at the moment. Eventually there will be a command built in that executes a script so you can then do that. For now you'll have to write a plugin that has a custom command that executes the commands you want to execute :+1:

**Comment by MrIQZero** [comment]
Thanks MrExodia, I'll look into custom plugins too, but for now here is what i want to do, when a hardware breakpoint is hit i want to do 2 things.
1. Change the value of RSI or ESI register and,
2. "erun" or resume the program.
can anyone let me know the best way i can achieve the same. Thanks.

**Comment by mrexodia** [comment]
Well if you set your break condition to 0 (never break) you can just write
"mov rsi, 2" as command.

**Comment by MrIQZero** [comment]
Aw man ! Thanks again.. Works like a charm. !!!

**Comment by mrexodia** [comment]
Take a look at http://help.x64dbg.com/en/latest/introduction/index.html and make sure you understand how commands and expressions work. This section also contains information on exactly how conditional breakpoints are handled.

I think for your case the commands you're looking for would be:

```
bp 0x401000
SetBreakpointCondition 0x401000, "eax == 1"
```

**Comment by JuanJo321** [comment]
Hello Mr Exodia !

thanks a lot for your answer. I'm currently reading thoroughly the whole manual.

But in spite of this, I still don't understand the "mind" of the conditionnal breakpoint as implemented in x32dbg : 

look, I tried of course your suggestion on the "calc.exe" program, but then the memory-location is invalid and I get the answer "Erreur de paramétrage du point d'arrêt en 0040000! (memread)"

My problem is to guess in what memory-location I have to set the breakpoint (!?!)... how can I know in advance a valid one ? Am I confused about something ? What didn't I catch well ?

What do you suggest ?

By the way, I have another question about 'bplist' : 
I set many librarian breakpoint and it worked fine ; I can see all of them in the breakpoint window as you can see here : 

![image](https://cloud.githubusercontent.com/assets/28961652/26529180/9a69fa8c-43bb-11e7-8eda-a85b009f5066.png)

but the 'bplist' command shows only the first one ; I know it must be something stupid I didn't catch, but here I'm stuck ;D ...

![image](https://cloud.githubusercontent.com/assets/28961652/26529242/ca6b7a52-43bc-11e7-9d01-6d0636c64654.png)

Thanks for taking a few minutes to answer me...

Have a nice day ...

**Comment by mrexodia** [comment]
The prerequisite for any breakpoint is that you know _where_ you want to break. If your question is: "Where is EAX equal to 5?" You can try conditional tracing, but this is very slow.

Ignore the `bplist` command. The breakpoint tab is all you need.

**Comment by JuanJo321** [comment]
Hello again and thanks for your answer.


Well, in fact, thanks to your answer, I realized that I asked my question in a wrong way.

My question should rather have been, not "Where is EAX equal to 1 ?", but instead "When is EAX equal to 1 ?"

...and to be even more accurate, "What instructions set EAX equal to 1 ?"

--> what I wanted is x32dbg to break exactly after (or even before) the instruction has set EAX to 1, so that I can identify it.

To give you examples of what I mean, remember the SoftIce command "bpx eip if eax = 1", or "bpx eip if eax >= 1ff && eax <= 300"

This is exactly what I was searching in x32dbg.

You gave me the idea to use TraceIntoConditional which is about equivalent. I will manage with it.

Now, if you can advise me an equivalent x32dbg command to the SoftIce "bpx eip if eax = 1", please let me know.

The fact is that with softIce, in the "bpx eip if eax = 1", the eip arg was parametric and not constant, which is not the case in x32dbg, unless I mistake...

Anyway, thanks a lot again for your help ;D

Have a nice day..

**Comment by mrexodia** [comment]
`TraceIntoConditional "eax == 1"`
