### ISSUE TITLE
Changes not applied

### ISSUE THREAD

**Issue by Sheida69** [x64dbg/x64dbg#3141]
### Operating System

Windows 11

### x64dbg Version

Jul 8 2023

### Describe the issue

Hi, I want to crack a trial version software with 30 days limit, I make all the changes and when I save the patch and run the software again, there is no change, I'm sure the changes I made are fine because I saw it from the Youtube video, if anyone can help me, I will appreciate it.

### Steps to reproduce

1. 
2. 
3.

**Comment by ZehMatt** [comment]
You need to use this:
![x64dbg_2023-07-21_12-03-23ae56d15f071c77678](https://github.com/x64dbg/x64dbg/assets/5415177/2c93c51c-9459-48d4-84ac-ae2a5bd9c3bf)

**Comment by Sheida69** [comment]
> You need to use this: ![x64dbg_2023-07-21_12-03-23ae56d15f071c77678](https://user-images.githubusercontent.com/5415177/255130077-2c93c51c-9459-48d4-84ac-ae2a5bd9c3bf.png)

Thank you for answering, I do this and replace it, but nothing changes.

**Comment by mrexodia** [comment]
See: https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions

**Comment by Sheida69** [comment]
I have the patched file with all the changes that I specified with the breakpoint, can anyone help if I send the file?

**Comment by ZehMatt** [comment]
> I have the patched file with all the changes that I specified with the breakpoint, can anyone help if I send the file?

No, we don't help cracking software.
