### ISSUE TITLE
Remove PidInHex settings, always show PID/TID in decimal

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#3142]
I doubt anyone is enabling that, and by removing it, UI will get more consistent with less code.

**Comment by mrexodia** [comment]
At least one person I know of is using this, but I agree a hexadecimal pid/tid is quite useless in practice...

**Comment by torusrxxx** [comment]
Do you think you want to decline this request?

**Comment by mrexodia** [comment]
I don't think the overhead of keeping this feature isn't very big for us. As long as you use the helper function it's all transparent. Personally I'm not against removing hex necessarily, but don't feel very strong either way.

Iirc it was @justanotheranonymoususer using this feature (could be totally wrong), maybe some input?

**Comment by justanotheranonymoususer** [comment]
I don't remember, but I'm not using it now, so I don't mind

**Comment by torusrxxx** [comment]
Currently call stack always show TID in decimal.
