### ISSUE TITLE
my debugger is broken

### ISSUE THREAD

**Issue by vmoonz21** [x64dbg/x64dbg#3148]
### Operating System

windows 10

### x64dbg Version

idk

### Describe the issue

when I run x64 it auto Elevates and idk why but when I try to attach something it always breaks.

this happened after my pc bluescreened with the debugger opened

### Steps to reproduce

1. 
2. 
3.

**Comment by torusrxxx** [comment]
You need to disable kernel anti-debug, otherwise your PC will keep bluescreen when you use x64dbg.
