### ISSUE TITLE
(minor) LOOP is not treated as a jump command

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#315]
The arrow is not drawn, clicking on ENTER doesn't follow the destination, and analysis detects only part of the function (not sure if the analysis issue is related).
Screenshot:

![here](http://i.imgur.com/UyI0kK3.png)

**Comment by mrexodia** [comment]
Ah nice, totally missed that one!

**Comment by Nukem9** [comment]
Appears to be fixed. 
![image](https://cloud.githubusercontent.com/assets/4228359/8636172/7a8b655a-2821-11e5-9a18-e92a45aa395e.png)

**Comment by mrexodia** [comment]
i didnt touch it, but whatever :D

2015-07-12 5:06 GMT+02:00 Nukem <notifications@github.com>:

**Comment by mrexodia** [comment]
yep, it also works fine on x64

**Comment by RaMMicHaeL** [comment]
This commit looks relevant: https://github.com/x64dbg/x64dbg/commit/53fd990c83a5b407643344f2b81c97b3ee6e9dc3
Will try it when a snapshot is available.

**Comment by RaMMicHaeL** [comment]
It's being shown as an unconditional jump now. It should be conditional, such as `je`/`jne` and friends, and unlike `jmp`.

**Comment by mrexodia** [comment]
This is what it shows for me:

![img](http://i.imgur.com/z30zeUz.png)

**Comment by mrexodia** [comment]
oh I see now... loop is shown as unconditional indeed
