### ISSUE TITLE
Checkboxes are sometimes invisible when using the Dark theme

### ISSUE THREAD

**Issue by shocoman** [x64dbg/x64dbg#3158]
### Win10
![Pasted image 20230731234119_small](https://github.com/x64dbg/x64dbg/assets/8329446/d4e574e3-32c7-4ed0-9bbf-32dc7b858f37)

### Wine (Linux, KDE)
![Pasted image 20230801123956_small](https://github.com/x64dbg/x64dbg/assets/8329446/f3b9856a-252b-4ade-b054-777cb65a918a)

Some checkboxes are not properly displayed at startup.

### Observations:
1) Pressing "Options/Reload style.css" or "Theme/Dark" fixes the problem.
2) Putting the call to `MainWindow::loadSelectedTheme(true)` in `main` after `DbgInit()` fixes the problem.
3) Setting absolute paths for the images fixes the problem.
4) Not using some (probably heavy) plugins fixes a half of the problem.
5) Opening the program from a location other that where the executable is located causes the problem.

### Description:
When the program is launched and `MainWindow::loadSelectedTheme` is called for the first time, the current directory can be almost anywhere. The stylesheets use relative paths for the images, and, as far as I can see, are loaded/applied unpredictably and asynchronously (as shown on the screenshots, at least some icons are fine). These relative paths depend on the current value of `GetCurrentDirectory`. In addition, during the plugin initialization step (which may take some time) inside `DbgInit`, the current directory is changed to their respective directory (`/x32/plugins/`). If Qt tries to load the stuff at this point, it won't find the images.

### Possible Solutions
- Call `loadSelectedTheme` [after `DbgInit`](https://github.com/x64dbg/x64dbg/blob/de494c1fc7e29dce09d3000bb91f0bac3f951e8e/src/gui/Src/main.cpp#L212) and never use `SetCurrentDirectory` again (just to be safe)
- Use absolute paths for images during the css 'generation' ([in the `loadSelectedTheme` function](https://github.com/x64dbg/x64dbg/blob/de494c1fc7e29dce09d3000bb91f0bac3f951e8e/src/gui/Src/Gui/MainWindow.cpp#L657C16-L657C16))

**Comment by mrexodia** [comment]
Thanks for the detailed research! The solution would be to change the current directory earlier in initialization. I’ll adjust BridgeStart to do this

**Comment by mrexodia** [comment]
Should be fixed now, I implemented a combination of your solutions. It should never be the case that x64dbg operates from the directory it started in, so I changed that and additionally switched to replacing the URLs with the full path in `loadSelectedTheme` as suggested.
