### ISSUE TITLE
PDB files not released after detach

### ISSUE THREAD

**Issue by Maktm** [x64dbg/x64dbg#316]
After I detach from a file and try to recompile in my IDE I get errors related to the fact that the PDB files are still in use and cannot be rewritten (since they are open). So I would have to close the debugger then recompile everytime.

**Comment by RaMMicHaeL** [comment]
I have encountered a similar issue: after stopping the debugged executable (Alt+F2), the file is still locked.

**Comment by Nukem9** [comment]
*Should* be easy enough to fix with a call to SymUninitialized. AFAIK it's only called when the debugger exits right now.

**Comment by Nukem9** [comment]
Is this still a problem? I haven't had an error like this in awhile.

**Comment by mrexodia** [comment]
i tested, appears to be gone
