### ISSUE TITLE
x64dbg cant show correct memory page properties

### ISSUE THREAD

**Issue by helloobaby** [x64dbg/x64dbg#3164]
### Operating System

windows 11 21h2

### x64dbg Version

Aug 1 2023

### Describe the issue

![image](https://github.com/x64dbg/x64dbg/assets/84119280/11528c24-34f0-45cf-aa51-0aeea27a498e)
![image](https://github.com/x64dbg/x64dbg/assets/84119280/53541e9c-3cfb-47ec-8543-366cefdb722e)

windbg use !address command, and windbg is correct actually.Because I found that the code can indeed be executed and DEP has been turned on.The size and length of the memory page are also different from those displayed by x64dbg, I am very confused

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Right click -> switch view
