### ISSUE TITLE
Add address recording function to Ctrl+g for x64dbg

### ISSUE THREAD

**Issue by CrxF** [x64dbg/x64dbg#3168]
### Feature type

Debugging

### Describe the feature

![1](https://github.com/x64dbg/x64dbg/assets/141927056/a496ddca-3f86-4c57-b7d6-b54581869239)
Every time I use ctrl+g, the entered address will be cleared. Can I add a memory function similar to the OD plugin, my friend！

**Comment by mrexodia** [comment]
Press arrow up

**Comment by CrxF** [comment]
> 按向上箭头查看历史记录。

Hello friend, this OD Ctrl+g plugin has three great features. The first is to automatically prompt for the full name when entering an API name, and the second is to list all modules when clicking rva. After entering an offset above, you can jump to the module address. I think this is a good feature for debugging user DLLs, and the other is the address recording function. If you enter more than ten addresses during software debugging, I think recording it has brought great convenience to debugging software. All three functions of x64dbg have been implemented, but the display of x64dbg in the view may need to be more convenient. Additionally, when opening ctrl+g, the address of x64dbg will be the address of the disassembly window. Can the address displayed in the x64dbg window be the address entered last time after opening ctrl+g. Perhaps my language organization is not perfect enough, but it should have conveyed my general idea. I hope to adopt my opinion, my friend
![1](https://github.com/x64dbg/x64dbg/assets/141927056/6d0c6d16-08bf-4005-aedf-5244785fe0c0)
![2](https://github.com/x64dbg/x64dbg/assets/141927056/532c7b8e-02ba-41bc-9d9a-c277176e2f8a)
![3](https://github.com/x64dbg/x64dbg/assets/141927056/fa6a76a6-cc23-4fdf-a064-9c9dc42650a9)
