### ISSUE TITLE
GOTO doesn't work after the first time

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#317]
Reproduction steps:
Ctrl+G -> EIP -> Enter -> Ctrl+G -> EIP -> Enter (won't work, the OK button is disabled)

![scr](http://i.imgur.com/v1LoDbK.png)

**Comment by Nukem9** [comment]
I'm assuming these two things are related: https://github.com/x64dbg/x64dbg/issues/312#issuecomment-111004421

**Comment by wk-952** [comment]
after compiling the project with the latest commits,
the GOTO option doesn't seem to be working at all now.

**Comment by Nukem9** [comment]
See https://github.com/x64dbg/x64dbg/commit/aa46809c93c7f8416a162596f7d34af361ee79df

**Comment by wk-952** [comment]
Thank you very much
