### ISSUE TITLE
Improved functionality of Ctrl+g

### ISSUE THREAD

**Issue by CrxF** [x64dbg/x64dbg#3170]
### Feature type

Debugging

### Describe the feature

![2](https://github.com/x64dbg/x64dbg/assets/141927056/2cb6c4a2-6ba2-46ff-9111-ba60e1714010)
Hello, my friend. Thank you for answering the recording question of ctrl+g just now. However, there is a question. If you enter multiple addresses, the number of times you press the up button will be very frequent. Can you add a button to the right of the input address as shown in my screenshot, and click to display the entered address.

**Comment by mrexodia** [comment]
You can reply to the previous issue. I closed it by accident on the phone...
