### ISSUE TITLE
String search and feature matching in x64dbg

### ISSUE THREAD

**Issue by CrxF** [x64dbg/x64dbg#3171]
### Feature type

Other

### Describe the feature

Hello friend, when using x64dbg to search for strings, I found that the interface spacing is too large and will be covered when opened. Each time, I need to drag to the left. This function is used to query strings. Can you make the interface spacing closer? Also, I am using ctrl+b to search for features and feel that its interface is too large. I think it can be made more suitable like my screenshot, Can you add a recording function for him to record the searched features, and then add a forward and backward button to browse through the recorded features, and then match the whole block? I think it can be checked by default because every matching feature is basically a whole block, and my language may not be perfect, but I should have described the general problem and hope to be adopted
![1](https://github.com/x64dbg/x64dbg/assets/141927056/d99e10a2-f73d-4f44-8d6f-f03646a9ba3d)
![2](https://github.com/x64dbg/x64dbg/assets/141927056/195b2a8e-244d-40d7-851a-b66bfae17066)
![3](https://github.com/x64dbg/x64dbg/assets/141927056/7e20bb5b-6017-4ea1-9796-c35353466483)
![4](https://github.com/x64dbg/x64dbg/assets/141927056/a04a0495-3fdf-4596-a099-51c59db3333c)

**Comment by CrxF** [comment]
Also, when using black themes again, the hexadecimal search box will not be displayed. I hope to adopt the ctrl+g question I asked yesterday, my friend.
https://github.com/x64dbg/x64dbg/issues/3168    This is the link to yesterday's question of ctrl+g

**Comment by mrexodia** [comment]
Please open separate issues for separate problems. This way we can keep track of them, now it will just be lost…

I will not be implementing your suggestions from #3168 any time soon. If you really need it soon you can try to add it yourself.

**Comment by CrxF** [comment]
> 请为单独的问题打开单独的问题。这样我们就可以跟踪它们，现在它就会丢失......
> 
> 我不会很快实施您在[#3168中提出的建议。](https://github.com/x64dbg/x64dbg/issues/3168)如果你确实很快需要它，你可以尝试自己添加。

**Comment by CrxF** [comment]
> 请为单独的问题打开单独的问题。这样我们就可以跟踪它们，现在它就会丢失......
> 
> 我不会很快实施您在[#3168中提出的建议。](https://github.com/x64dbg/x64dbg/issues/3168)如果你确实很快需要它，你可以尝试自己添加。

My friend, I don't need these features at the moment, I'm just making suggestions purely for the functionality of x64dbg. If your time is limited, you can also ignore these opinions. Thank you for your reply.

**Comment by mrexodia** [comment]
> Also, when using black themes again, the hexadecimal search box will not be displayed.

@CrxF could you explain this problem with a screenshot of the difference between light/dark theme?
