### ISSUE TITLE
i can not debug application when hardware breakpoint hits

### ISSUE THREAD

**Issue by yc862900** [x64dbg/x64dbg#3173]
i set hardware breakpoint in somewhere,  and when it hits , then i delete hardware breakpoint ,  i run app ,   it seems the threads of app suspend,   then i can not debug application anymore! this is a bug(version is Aug 1 2023, 14:48:59)

**Comment by mrexodia** [comment]
Could you show a video/screenshots of this happening? I tried reproducing it with both execute and write hwbp and I cannot...
