### ISSUE TITLE
QFileDialog filter contains an extra period when saving a trace dump

### ISSUE THREAD

**Issue by shocoman** [x64dbg/x64dbg#3181]
![Pasted image 20230821180447](https://github.com/x64dbg/x64dbg/assets/8329446/59ba8bec-fdcc-4b88-9a19-858704c3254a)

As a result, the dialog won't show other dumps by default. I think the problem is [here](https://github.com/x64dbg/x64dbg/blob/a85f17756791a63ed281f15a1c312510b0339d3a/src/gui/Src/Tracer/TraceBrowser.cpp#L90)

**Comment by mrexodia** [comment]
Yeah that's a bug
