### ISSUE TITLE
mouse laggy issue when hit breakpoint

### ISSUE THREAD

**Issue by qazwsdc** [x64dbg/x64dbg#3182]
### Operating System

windows 11

### x64dbg Version

apr 15 2023

### Describe the issue

when debug some software just hit the breakpoint and the mouse laggy.
It basically makes mouse impossible to control. 

### Steps to reproduce

1. make a breakpoint
2. hit it
3. mouse laggy issue

**Comment by mrexodia** [comment]
Likely this is a mouse hook from the application. There is nothing x64dbg can do to mitigate this.

**Comment by qazwsdc** [comment]
> Likely this is a mouse hook from the application. There is nothing x64dbg can do to mitigate this.

no.because two software have this issue not just one application

**Comment by mrexodia** [comment]
So then please follow the instructions and **provide enough information to reproduce the problem**.

- What software are you using?
- Where are you setting breakpoints?
- VM or not?
- Show it happening on a video

**Comment by qazwsdc** [comment]
software：animcraft   （https://www.animcraft.com/）
breakpoint：ws2_32.send()
not VM

https://github.com/x64dbg/x64dbg/assets/37575412/962bac61-3a84-455c-90f9-4602e6f26c08

when hit breakpoint then mouse laggy.
Another software (https://www.miebo.cn/) have this same issue too.
I have tried switch different computer but same issue happening
