### ISSUE TITLE
translations seem out of date

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#3204]
Last time I checked there are no new strings appear. But now I have been 403 so I'm unable to check.

**Comment by mrexodia** [comment]
What’s your account for the translation site? I didn’t change anything, so you should still have access.

**Comment by torusrxxx** [comment]
Hey, they have been mass blocking low reputation IPs. Good to hear there isn't anything broken except that.

**Comment by mrexodia** [comment]
I reached out to you on https://app.gitter.im, but I can use another method of communication if you prefer...

**Comment by torusrxxx** [comment]
I have trouble loading Gitter and joining conversations on Gitter with Github account. So right now the best method of communication is via Github...
But the tooltip of EFLAGS remains in English.

**Comment by torusrxxx** [comment]
Just confirmed on https://translate.x64dbg.com/project/x64dbg/activity-stream that the last update to x64dbg.ts was in April 2023. New messages are still in English.

**Comment by mrexodia** [comment]
Ahhh, most likely the webhook is not working and Crowdin doesn’t report any error messages…

**Comment by mrexodia** [comment]
I just checked and the job is actually running every single day:

![IMG_5307](https://github.com/x64dbg/x64dbg/assets/2458265/0d7929c4-0af9-4925-9f3f-f63a790038f1)

They recently updated their command line tool though, so I will need to investigate in detail what’s going on.
