### ISSUE TITLE
ReferenceView Widgets: Memory Not Fully Released on Tab Closure

### ISSUE THREAD

**Issue by HayFieldLaps** [x64dbg/x64dbg#3207]
### Operating System

Window 10 64bit, Build 19045

### x64dbg Version

Sep 2 2023

### Describe the issue

Widgets within ReferenceView are not released upon tab closure. I've provided a preliminary solution to this issue [here](https://github.com/x64dbg/x64dbg/commit/b18443e47bfc79ba4e508b3f72e3d348e60404c3). While this resolves most of the memory leak, about one-third of the memory remains unreleased when a tab is closed.

I've been unable to identify the reason for the residual memory usage. Any suggestions?

### Steps to reproduce

1. Load or attach to any process
2. Check x64dbg memory usage
3. Search for string references (or any reference)
4. Close reference tab(s)
5. Check memory usage again

**Comment by mrexodia** [comment]
Most likely this is addressed by https://github.com/x64dbg/x64dbg/pull/3213, could you test?

**Comment by HayFieldLaps** [comment]
It has the same results as the solution I had provided, @torusrxxx did basically the same thing I had done [here](https://github.com/x64dbg/x64dbg/commit/b18443e47bfc79ba4e508b3f72e3d348e60404c3). Most of the memory is freed, yet a considerable amount of memory remains after closing the tabs.

To test I had created two scripts. The first using findallmem, the patterns are irrelavant. The script does this 1000 times and returns.

```
findallmem mod.main() + 0x1000, ??83b104ef, 0x13C4000
findallmem mod.main() + 0x1000, ??40bddac0, 0x13C4000
findallmem mod.main() + 0x1000, ??db2585b7, 0x13C4000
...
``` 

The initial memory before running the script was 48.6MB, after the script completes 376.0MB and after clearing all the reference view tabs 84.2MB. 35.6MB of memory is left unaccounted for.

The second script just repeated bookmarklist 1000 times. I had set 3 arbitrary bookmarks prior to running the script.

```
bookmarklist
bookmarklist
bookmarklist
...
```

The initial memory before running the second script was 45.8MB, after the script completes 380.3MB and after clearing all the reference view tabs 84.2MB. 38.4MB of memory is left unaccounted for.

I tried setting ENABLE_MEM_TRACE to see if this found any issues, it didn't. I also tried using Valgrind to see if it was possibly a Qt issue, but wasn't able to get Valgrind to work properly (haha, I'm dumb). Additionally, I briefly looked through both findallmem and bookmarklist for any potential issues but didn't see anything obvious.

**Comment by mrexodia** [comment]
Does it scale if you do it 1000x? It might be some residual memory in Qt that’s not being deallocated because a vector buffer isn’t freed or something… the Qt memory model is a bit magical, but if the leak has a very small constant factor it’s 🤷‍♂️

**Comment by HayFieldLaps** [comment]
Do you mean if creating more ReferenceView's results in more residual memory after closing the tabs? If so, then yes it does scale, somewhat linearly with how many ReferenceView's were created.

Interestingly, using bookmarklist (or any command that creates a ReferenceView) or constructing a ReferenceView/SearchListView AFTER deleting all the tabs results in most of the memory being freed. I'm unsure why this occurs.

Could just be a Qt issue.
