### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by CXVUSER** [x64dbg/x64dbg#3216]
Please add search box to memory map window, or on all..))  memory map is very biggest table.

**Comment by mrexodia** [comment]
It would be helpful if you could explain what you want to search for @CXVUSER. Perhaps there is another way to do this. I considered adding a search list to the memory map, but my conclusion was that it would be too confusing if parts of it disappear if the user types something by accident…

**Comment by CXVUSER** [comment]
> It would be helpful if you could explain what you want to search for @CXVUSER. Perhaps there is another way to do this. I considered adding a search list to the memory map, but my conclusion was that it would be too confusing if parts of it disappear if the user types something by accident…

Search by (dll, exe) name,

**Comment by mrexodia** [comment]
Ah in that case you can go to the module tab and follow in memory map there. Alternatively you can press Ctrl+G and type `module.dll:0` to jump to the relevant page.

**Comment by CXVUSER** [comment]
> Ah in that case you can go to the module tab and follow in memory map there. Alternatively you can press Ctrl+G and type `module.dll:0` to jump to the relevant page.

Thanks!
