### ISSUE TITLE
Sep 20 update breaks theme

### ISSUE THREAD

**Issue by not6** [x64dbg/x64dbg#3218]
### Operating System

Windows 10 Pro x64 22H2, Build 19045.3448

### x64dbg Version

Sep 20 2023

### Describe the issue

Sep 20 2023 update of x64dbg breaks the theme, this does not occur on Sep 16 2023. Tables are broken and an error shows up when opening Options > Appearance. Note the bugged colors in the dump window in the attached screenshot.

### Steps to reproduce

1. Use dark theme
2. Look at dump/attach window
3. Go to Options > Appearance

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/94708210/df34d9d5-f013-4412-a263-a8911e753e57)

**Comment by mrexodia** [comment]
Thanks for the heads up! It doesn't look the most beautiful, but it's functional again:

![image](https://github.com/x64dbg/x64dbg/assets/2458265/e7b44e55-9469-45ac-b2a0-e41283c9b6e5)

**Comment by not6** [comment]
Works fine now but you need to reload the theme for the colors to get fixed (set theme to default then back to dark)

**Comment by mrexodia** [comment]
Yes, the colors don’t get overwritten to the default in case you manually modified them.
