### ISSUE TITLE
内存窗口增加创建备份，内存有变化时红色标记变动的内容。

### ISSUE THREAD

**Issue by 365DRM** [x64dbg/x64dbg#3220]
### Feature type

Other

### Describe the feature

内存窗口增加创建备份，内存有变化时红色标记变动的内容。
![360截图18720124688490](https://github.com/x64dbg/x64dbg/assets/88992306/e9329a62-b10d-4b3b-a92c-151c53e3482a)

**Comment by torusrxxx** [comment]
same as #3032
