### ISSUE TITLE
Disassembly view wraps around when scrolling up (bug)

### ISSUE THREAD

**Issue by shocoman** [x64dbg/x64dbg#3228]
![wrap-around-bug](https://github.com/x64dbg/x64dbg/assets/8329446/012d30ca-ed56-43a4-8b05-ec1edf0bce22)

I think this bug was introduced in [snapshot_2023-09-20_02-36.zip](https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2023-09-20_02-36.zip/download)

[Link](https://github.com/x64dbg/x64dbg/blob/c65c956f856cba164db9de5cbbc10eded60675fa/src/gui/Src/BasicView/Disassembly.cpp#L1420)
I don't know what that TODO means exactly, but the type of `bottomByteRealRVA` will be inferred as an unsigned `duint`. A few lines down is a check for negativity, which is obviously never true.

**Comment by mrexodia** [comment]
Nice catch, thanks! While refactoring I got rid of signed integers in most places, but clearly missed this TODO I placed 😅
