### ISSUE TITLE
Windows XP SP3 not working (kernel32, PSAPI)

### ISSUE THREAD

**Issue by NIKEA-SOFT** [x64dbg/x64dbg#3230]
### Operating System

Windows XP SP3

### x64dbg Version

May 25 2023

### Describe the issue

Hello, on Windows XP I get the following error at startup:
`Entry point to procedure K32GetModuleBaseNameA not found in kernel32.dll`

After searching I found out that this is due to incorrect use of PSAPI, documentation:
https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulebasenamea
View on REMARKS

### Steps to reproduce

Just run exe

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/57288440/0d1a1b43-b392-4b73-afc6-78d7ace5d079)

**Comment by mrexodia** [comment]
Try the latest version first.

**Comment by NIKEA-SOFT** [comment]
> Try the latest version first.

I checked the latest version yesterday, the problem is still there.

**Comment by mrexodia** [comment]
I tested this on the latest version, working fine:

![image](https://github.com/x64dbg/x64dbg/assets/2458265/718d4a74-b54a-4f53-b197-50d3f5b9cf0b)

Make sure you have all the updates installed.
