### ISSUE TITLE
Topmost function not working properly

### ISSUE THREAD

**Issue by faltur** [x64dbg/x64dbg#324]
Hi, the topmost function is not working properly with one (or some) target application. It's not forcing the debugger window to appear in front of my target. In my case, I tested with Heroes of the Storm game. This is what I'm doing:
1. I run the game normally and attach x64dbg to the game process
2. I set a BP on an API call that will called soon
3. then I go back to the game, type my user and pass and click on the Connect button
4. at this moment, the game freezes indicating that the debugger owned the control over the process. But the game window keeps in front of every application, including the Task Manager. When I press CTRL+F5 I can see the mouse cursor changing, but the game window continues on the top over every other windows, including the debugger one.
Windows 8.1, x32bit

**Comment by Nukem9** [comment]
Is the game fullscreen? This might not be able to be fixed because of how Windows works.

**Comment by faltur** [comment]
Yes, it's a fullscreen game. Ollydbg generally can handle this issue, but I can't test it, since I'm not being able to run the game with Olly attached to this game - probably due to a security detection.

**Comment by mrexodia** [comment]
This sounds like a problem with Windows to me. Try running the game in borderless window or windowed mode or simply use a second monitor :) If the issue is still there in windowed mode I'll look deeper into it.

**Comment by faltur** [comment]
Thanks for the reply, mrexodia. I solved the problem by using the windowed mode, as you have suggested.
