### ISSUE TITLE
Autocomment automatically comments code that is or is not running in its current state

### ISSUE THREAD

**Issue by yellowzq** [x64dbg/x64dbg#3242]
### Operating System

Windows 7 64bit

### x64dbg Version

2023/10/19

### Describe the issue

![image](https://github.com/x64dbg/x64dbg/assets/87900930/514102f6-76a2-4541-bfcb-aac6e52c0624)
When I run to the EIP, the comments of the previously run code and the code that has not run since are updated to the current register state, however, in reality, there should be comments of the state of the register at the time of the run, and should not be updated

### Steps to reproduce

1. *

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/87900930/31650033-56a9-42dd-92d4-6ea866138479)

**Comment by mrexodia** [comment]
Please fill in the steps to reproduce with exact steps on how this reproduces.

**Comment by yellowzq** [comment]
I'm sorry. I seem to have misunderstood the purpose. Actually, what I want is a feature that automatically saves history comment.

**Comment by ZehMatt** [comment]
Given that registers might change this could be misleading. Also you could probably write a plugin to save permanent comments by evaluating the register values.
