### ISSUE TITLE
cant patch files  filenamePRO.exe want let me patch says in use?

### ISSUE THREAD

**Issue by Amit30swgoh** [x64dbg/x64dbg#3246]
### Operating System

windows x64

### x64dbg Version

oct 10 2023

### Describe the issue

cant patch files  filenamePRO.exe wont let me patch says in use?

### Steps to reproduce

1. cant patch files  filenamePRO.exe wont let me patch says in use?
2. cant patch files  filenamePRO.exe wont let me patch says in use?

### Attachments

cant patch files  filenamePRO.exe want let me patch says in use?

**Comment by ZehMatt** [comment]
You can't patch the file when its active in the debugger, create a copy of the binary and patch that instead.

**Comment by Amit30swgoh** [comment]
> You can't patch the file when its active in the debugger, create a copy of the binary and patch that instead.

hey friend can you please help me how to do that ty so much

**Comment by Amit30swgoh** [comment]
![image](https://github.com/x64dbg/x64dbg/assets/42430868/fcbd4aa8-d113-4aab-bdc4-45359f0b1c81)
![image](https://github.com/x64dbg/x64dbg/assets/42430868/645c1773-d255-4dc8-b836-484d09c17480)

**Comment by CXVUSER** [comment]
> ![image](https://github.com/x64dbg/x64dbg/assets/42430868/fcbd4aa8-d113-4aab-bdc4-45359f0b1c81)
> ![image](https://github.com/x64dbg/x64dbg/assets/42430868/645c1773-d255-4dc8-b836-484d09c17480)
> 

1.Copy unpatched exe file to desktop folder. 
2.Select file from desktop for patching

**Comment by Amit30swgoh** [comment]
hi how i do that please
