### ISSUE TITLE
String search poorly effective

### ISSUE THREAD

**Issue by JohnFarl** [x64dbg/x64dbg#3247]
### Operating System

Windows 10

### x64dbg Version

Oct 05 2024

### Describe the issue

The String search doesn't seem working well. 
If I open an exe it should allow to search all Strings in all the exe, unfortunately this isn't the case. 

I have attached a `test.exe` sample. Suppose is needed to find `Wobbly` string

With Ghidra this operation is very easy, the search find all Strings without effort.

With x64Dbg string search points at the module `ntdll.dll` with no option to perform a search in all the modules, and even opening one by one each module I don't find the string, either due to some bug or because it needs some weird digging.

### Steps to reproduce

1. Decompile attached test.exe
2. Search Wobbly String

### Attachments

[test.zip](https://github.com/x64dbg/x64dbg/files/13114117/test.zip)

**Comment by mrexodia** [comment]
It helps if you search inside test.exe and not ntdll. The search per default is from your currently-open code in the disassembly.

**Comment by JohnFarl** [comment]
> It helps if you search inside test.exe and not ntdll. The search per default is from your currently-open code in the disassembly.

I have said that even open the other modules (and so test.exe) I don't find the string. I have noted about the opening of `ntdll.dll` to underline the fact search should search in the opened exe rather than only in that dependency by default.

**Comment by mrexodia** [comment]
Can you share the instruction that references this string?

**Comment by mrexodia** [comment]
The executable is a .NET executable and there are no _references_ to this string. Use a tool like dnSpyEx to explore it.
