### ISSUE TITLE
debugging stopped

### ISSUE THREAD

**Issue by JJSV96** [x64dbg/x64dbg#3249]
### Operating System

Windows 11 64

### x64dbg Version

05 October 2023

### Describe the issue

I'm trying to use dbg, but when I add the exe file, this message appears at the end.
Would anyone know how to help me?

[...
Thread 2172 created, Entry: ntdll.[7729E8B0](x64dbg://localhost/address32#7729E8B0), Parameter: [00CAEDF8](x64dbg://localhost/address32#00CAEDF8)
Thread 8244 created, Entry: ntdll.[7729E8B0](x64dbg://localhost/address32#7729E8B0), Parameter: [00CAEDF8](x64dbg://localhost/address32#00CAEDF8)
DLL carregada: [52410000](x64dbg://localhost/address32#52410000) C:\Windows\SysWOW64\msvcr100.dll
Thread 15552 exit
Thread 2172 exit
Thread 8244 exit
Process stopped with exit code 0xC0000135 (STATUS_DLL_NOT_FOUND)
Saving database to C:\Users... 0ms
Debugging interrupted!]

### Steps to reproduce

1. F3 to open the file
2. Select the file

**Comment by mrexodia** [comment]
It means a DLL dependency wasn't found. Make sure the executable runs without the debugger first.
