### ISSUE TITLE
x64dbg and snowman's qt version

### ISSUE THREAD

**Issue by onesbug** [x64dbg/x64dbg#325]
in newer x64dbg:
i used qt 5.4.0 compiled x64dbg,but the snowman only supports the qt 4.8.6(i use cmake).
qt 4.8.6 only supports msvc2010 and my ide is msvc2013.
so i copied snowman.dll from snapshot version.it crashed.I guess because the qt version conflict。
Snowman's qt version can be updated to 5.4.0?
Or is there another way?

**Comment by mrexodia** [comment]
No, use the exact Qt version described in the wiki or compile snowman with
Qt 5 :+1:

**Comment by onesbug** [comment]
well,thanks

**Comment by mrexodia** [comment]
There are also links available to the correct Qt versions. Just make sure
you compile snowman with the exact same Qt version as x64dbg itself. Then
everything will work.

**Comment by onesbug** [comment]
Boost version: 1.57.0
CMake Error at D:/CMake/share/cmake-3.3/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.4.0" from
  C:/Qt/Qt5.4.0/5.4/msvc2013/bin/qmake.exe, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:107 (find_package)


Configuring incomplete, errors occurred!
See also "D:/snowman/src/build/CMakeFiles/CMakeOutput.log".

i try to use cmake generate snowman's msvc project,but it tell me only supports Qt 4.x

**Comment by mrexodia** [comment]
Hm, in that case you should contact the snowman author with an issue. I
thought it supported Qt 5 :)

**Comment by onesbug** [comment]
ok:)

**Comment by mrexodia** [comment]
I'll also check it out later today.

**Comment by onesbug** [comment]
By the way,i think snowman is a good decompiler,but x64dbg can't give snowman too much useful information.reference IDA,IDA can give hexrays plugin a lot of useful information such as the calling convention,function parameter,data structure,stack variable,etc..x64dbg as a dynamic debugger to analyze these efficiencies is very low(The key is to analyze speed).speed and effect are in a dilemma.
anyhow,I prefer to use hexrays to use snowman.Although hexrays is not open source.

**Comment by mrexodia** [comment]
> By the way,i think snowman is a good decompiler,but x64dbg can't give snowman too much useful information.reference IDA,IDA can give hexrays plugin a lot of useful information such as the calling convention,function parameter,data structure,stack variable,etc..x64dbg as a dynamic debugger to analyze these efficiencies is very low(The key is to analyze speed).speed and effect are in a dilemma.
anyhow,I prefer to use hexrays to use snowman.Although hexrays is not open source.

x64dbg can give snowman all kinds of information, but mainly function labels. Don't see the point of this comment though, I'd also rather use HexRays for decompiling but as you said, it's not free :)

**Comment by lynnux** [comment]
I have the similar problem. I search snowman for a while, maybe https://github.com/x64dbg/snowman should on the https://github.com/x64dbg/x64dbg/wiki/Getting%20the%20Dependencies list (I checked the snowman.dll in snapshot-release, it import the x32bridge.dll, so can I use the official snowman source, like this https://github.com/yegord/snowman ?)

**Comment by mrexodia** [comment]
No, you cannot use the official snowman. I created a wrapper library. But I
have a test right now, so I'll do stuff later.

**Comment by lynnux** [comment]
Well thanks. Finally, I compiled the gui project with "Qt 4.8.6 (x32) for MSVC2013", it can run now(only release version).

**Comment by mrexodia** [comment]
addded snowman to the dependencies
