### ISSUE TITLE
Console window closes instantly after failing the build process

### ISSUE THREAD

**Issue by foralost** [x64dbg/x64dbg#3253]
The console window after launching the build process (`build.bat`), it closes itself upon encountering an error, and I can not see why the build failed or what really happened.

I have managed to prevent this using `goto` statements, so I could create PR instantly if thats allowed.

**Comment by mrexodia** [comment]
You are expected to run `build.bat` from an already-open command prompt. The `build.bat` is also mainly meant for headless builds, you can open `x64dbg.sln` and `x64dbg.pro` to develop in an IDE.

**Comment by foralost** [comment]
_You are expected to run build.bat from an already-open command prompt._

I mean for me it also closes the already-open cmd on Win10 Pro 19045.3570 and I have wondered if it is intentional.
