### ISSUE TITLE
Searching in the symbol view is broken

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#3254]
Sometimes when you search in the symbol view (especially for a known suffix) the results do not display anything (or only part of the expected results).

Working:
![image](https://github.com/x64dbg/x64dbg/assets/2458265/3820ded7-798c-4ab8-907d-4261e79f3b1f)

Broken (same session, just update the edit):
![image](https://github.com/x64dbg/x64dbg/assets/2458265/e12a699a-e607-4b63-99b0-fae7236e1e57)

This appears to be random, so most likely there is a memory issue with the `DbgGetSymbolInfo` function.

Perhaps you have an idea @m417z?

**Comment by m417z** [comment]
Sorry, but I haven't looked at this area in the code.

Speaking of symbol search, from my experience using it, I often find myself wishing for a simple AND/OR search, for example `Get AND Process`, `Get OR Process`. It's possible to use regex, but it's [verbose](https://stackoverflow.com/questions/4389644/regex-to-match-string-containing-two-names-in-any-order), slow, and lacks highlighting. I might look at implementing it one day, but just throwing it out here in case anyone else will like the idea and implement it. LMK if you think that it's worth create an issue for this.
