### ISSUE TITLE
break on specific module

### ISSUE THREAD

**Issue by Volkanite** [x64dbg/x64dbg#326]
like Ollydbg, option to break when a specific module is loaded. Not that important, just something that would help my lazy ass. If this is already supported by console command then i apologize for missing it and would appreciate if you can point me to it.

**Comment by mrexodia** [comment]
http://x64dbg.com/help/scr/LibrarianSetBreakPoint_bpdll.htm

**Comment by mrexodia** [comment]
I'll add a GUI for this maybe later on.

**Comment by Volkanite** [comment]
thank you
