### ISSUE TITLE
String search stopped working

### ISSUE THREAD

**Issue by parserpro0629** [x64dbg/x64dbg#3265]
In versions snapshot_2023-10-28_15-22 and snapshot_2023-11-02_17-30, string search does not work. In version snapshot_2023-10-05_13-38, the search worked.

**Comment by mrexodia** [comment]
Can you explain what doesn’t work exactly? I tested the string search today and fixed it a few hours ago…

**Comment by parserpro0629** [comment]
I load any program, for example a standard calculator, and try to find byte 0xCC. Screenshots of the search results are attached.

![2023-11-05 (2)](https://github.com/x64dbg/x64dbg/assets/148886579/a2898ad4-0000-4a3f-ba97-c843e456f2a5)
![2023-11-05 (3)](https://github.com/x64dbg/x64dbg/assets/148886579/7fcbdaba-ddd5-4f33-94c3-ed9e597455e3)
![2023-11-05 (4)](https://github.com/x64dbg/x64dbg/assets/148886579/b5dd555c-c2bb-4b7e-a598-3043fa8b0d0d)

But if you check “Entire block”, the search works correctly. This was not the case in previous versions.

![2023-11-05 (7)](https://github.com/x64dbg/x64dbg/assets/148886579/f383dca2-2d71-4ddf-83de-ca38bcca6481)
![2023-11-05 (8)](https://github.com/x64dbg/x64dbg/assets/148886579/27be4cfc-02c1-45e5-83de-715f6d603b20)

**Comment by mrexodia** [comment]
Thanks for the reproduction steps, I’ll give it a try when I’m back home!

**Comment by mrexodia** [comment]
Was it fixed?
