### ISSUE TITLE
Command Text (Conditional breakpoint) not working correctly on DWM.exe (Desktop Window Manager)

### ISSUE THREAD

**Issue by rxznve** [x64dbg/x64dbg#3270]
### Operating System

Windows 10 x64 22H2 (OS Build 19045.3570)

### x64dbg Version

Nov 2, 2023

### Describe the issue

Without the «**remote debugging**» feature, debugging «**DWM.exe**» using «**x64dbg**» is extremely difficult, since every time a breakpoint is triggered, everything on my screen freezes. I would like to know which functions are called and which are not. Therefore, I decided to try using «**Conditional Breakpoint**» with the «**run**» command, which, logically, should resume the process after reaching a breakpoint and selected the «**Singleshoot**» checkbox. However, after clicking «**Save**», my monitor still froze (apparently the breakpoint triggered) and I needed to restart the computer. I would like to understand why the «**run**» command did not work. Hotkeys, by the way, also stop working.

### Steps to reproduce

Before reproducing the following steps, go to the «**Preferences** > **Events**» tab and uncheck all the checkboxes. Then, go to the «**Exceptions**» tab, select «**Unknown exceptions**» and select «**Do not break**».

1. Attach to a running «**DWM.exe**» process
2. Select function «**CDXGISwapChainDWMLegacy::PresentDWM**» from «**dxgi.dll**»
3. Right click on the function and select «**Follow in Disassembler**»
4. Open the «**Conditional Breakpoint**» window, enter the command «**run**» in the «**Command Text**» field and check the «**Singleshoot**» box
5. Press the «**Save**» button

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/125130325/ac6d9847-5417-4208-a3f4-e2c387f05ec6)

**Comment by mrexodia** [comment]
It is explicitly mentioned in the documentation that the `run` command is not supported in breakpoints.

Use the condition `0` to not pause the application. Note that any exceptions might still pause so you need to exclude them as well.

**Comment by rxznve** [comment]
The number `0` in the «**Break Condition**» field doesn't help either. Everything freezes.

![image](https://github.com/x64dbg/x64dbg/assets/125130325/934a923d-343a-4ff5-9c3d-8beae55c34c8)

**Comment by mrexodia** [comment]
Yeah it makes sense, the window loop probably doesn’t pump at all. Most likely the best solution is to use a hooking framework or GleeBug directly. Alternatively you can try windbg remote

**Comment by rxznve** [comment]
I don't quite understand what exactly I need to do. Switch «**x64dbg**» engine to «**GleeBug**»?

**Comment by mrexodia** [comment]
No, you will have to write your own debugger to do what you want here…

**Comment by rxznve** [comment]
When I try to debug a running «**DWM.exe**» process with «**GleeBug**» engine enabled, it says «**STATUS_ACCESS_DENIED**».

![image](https://github.com/x64dbg/x64dbg/assets/125130325/2d36d450-caea-4282-a50c-69029a062bb3)

**Comment by rxznve** [comment]
> No, you will have to write your own debugger to do what you want here…

Okay, got it. However, thanks for your input!

**Comment by mrexodia** [comment]
https://github.com/x64dbg/GleeBug/blob/vs2015/MyDebugger/MyDebugger.h#L52 Here is some example code if you need…

**Comment by rxznve** [comment]
Thank you
