### ISSUE TITLE
x64dbg source level debugging not working

### ISSUE THREAD

**Issue by ZsoltKantor** [x64dbg/x64dbg#3273]
### Operating System

Windows 7 64bit, Build 7601

### x64dbg Version

Nov 18 2023

### Describe the issue

I have a 64-bit console code (C++) compiled with cl.exe (Debug environment) and linked with /DEBUG, but in x64dbg the source is not displayed.
I'm using the latest (Nov 18 2023) x64dbg version.
I also loaded the pdb file manually but nu source is visible, the "Source" tab is empty.

### Steps to reproduce

1. Compile a "Hello world" with cl.exe debug environment
2. Load it in x64dbg
3. check the "Source" tab

**Comment by mrexodia** [comment]
Go to the disassembly and look for comments in the form if “myfile.cpp:123”. Right click -> Open source

**Comment by ZsoltKantor** [comment]
> Go to the disassembly and look for comments in the form if “myfile.cpp:123”. Right click -> Open source

That worked, thank you!
