### ISSUE TITLE
The base address of user32.dll(win8) is incorrect in x32dbg, it should be 0x6ba80000 not 75920000.

### ISSUE THREAD

**Issue by atigerdown** [x64dbg/x64dbg#3276]
### Operating System

win8

### x64dbg Version

x32dbg

### Describe the issue

Hi

The base address of user32.dll(win8) is incorrect in x32dbg, it should be 0x6ba80000 not 75920000.

Jack

### Steps to reproduce

1. 
2. 
3. 
no

### Attachments

no

**Comment by mrexodia** [comment]
The base address is randomized on startup. Please fill in the details from the template because I cannot do anything with this…
