### ISSUE TITLE
Hints disappear when scrolling in the disassembler

### ISSUE THREAD

**Issue by rxznve** [x64dbg/x64dbg#3279]
### Operating System

Windows 10 x64 22H2 (OS Build 19045.3693)

### x64dbg Version

Nov 18 2023

### Describe the issue

When I scroll the mouse wheel up, the tooltips in the disassembler disappear. Appear when scrolling down.

### Steps to reproduce

1. Open the **vm3dgl64.dll** (VMWare) in x64dbg
2. Get address of **glCopyConvolutionFilter1D**
3. Convert address to bytes and search by pattern

I don’t know why, but I was able to detect this bug only with the **vm3dgl64.dll** library, so it’s better to check it with it.

### Attachments

https://github.com/x64dbg/x64dbg/assets/125130325/275fbab2-7df0-49cd-b6b0-6d77cfab27c4

**Comment by rxznve** [comment]
[vm3dgl64.zip](https://github.com/x64dbg/x64dbg/files/13466404/vm3dgl64.zip)

**Comment by ZehMatt** [comment]
The hint doesn't disappear, the actual instruction is not listed. When you scroll up and there is a bunch of data it won't be able to properly disassemble, that is just the way it works. You could mark the data as data so it will avoid disassembling it.
