### ISSUE TITLE
Selection shifts when MemoryMap is updated

### ISSUE THREAD

**Issue by rxznve** [x64dbg/x64dbg#3280]
### Operating System

Windows 10 x64 22H2 (OS Build 19045.3693)

### x64dbg Version

Nov 18 2023

### Describe the issue

When updating the MemoryMap, another element is selected and this is annoying.

### Steps to reproduce

1. Attach to any active process (for example DWM.exe)
2. Go to MemoryMap
3. Try to select something

### Attachments

https://github.com/x64dbg/x64dbg/assets/125130325/77d5ffbc-d559-4637-9a6f-c5cdfcaa4e7d

**Comment by foralost** [comment]
in two weeks I will look at it, if someone else wants to work on this earlier, no problem ;)

**Comment by mrexodia** [comment]
It should be relatively straightforward with the recent changes from @ZehMatt
