### ISSUE TITLE
Search in all memory from GUI

### ISSUE THREAD

**Issue by rxznve** [x64dbg/x64dbg#3282]
### Feature type

Quality of life

### Describe the feature

Please add the ability to search the entire memory of a process from the **GUI**, without having to issue the **findallmem** command. Something like this.
![image](https://github.com/x64dbg/x64dbg/assets/125130325/efbbc18a-bee7-48fc-b6c1-796f8c342397)

**Comment by mrexodia** [comment]
Search from the memory map.
