### ISSUE TITLE
Stack area data analysis enhancements

### ISSUE THREAD

**Issue by fairycn** [x64dbg/x64dbg#3286]
### Feature type

Debugging

### Describe the feature

# test program
everything x86 
https://www.voidtools.com/Everything-1.4.1.1024.x86.zip
# ollydbg
![image](https://github.com/x64dbg/x64dbg/assets/74580422/fff8802b-80a6-4fe1-bf35-84d17cd4986c)
# x64dbg
![image](https://github.com/x64dbg/x64dbg/assets/74580422/e69b3c70-4b49-4c4a-8dfe-ec147af03fd3)

Comparison shows that olldbg's stack area is better for data analysis.

**Comment by mrexodia** [comment]
This is a duplicate that’s been reported many times.
