### ISSUE TITLE
GetLogicalProcessorInformation breaks XP SP2 compat

### ISSUE THREAD

**Issue by BohemianGrove** [x64dbg/x64dbg#3287]
### Operating System

XP SP2

### x64dbg Version

11-18-2023

### Describe the issue

Application fails to start due to dependency during linking due to GetLogicalProcessorInformation from Kernel32 (Possibly others as well), on XP SP2 32 bit. If an IfDef could be added around this function to remove it from the code for versions pre XP Sp3, that would solve the issue as SP3 added this function.

### Steps to reproduce

Run on XP sp2 32 bit.

**Comment by mrexodia** [comment]
SP2 is not supported.
