### ISSUE TITLE
dbg x64 crash

### ISSUE THREAD

**Issue by DarkW0001** [x64dbg/x64dbg#3293]
### Operating System

Windows 11

### x64dbg Version

latest

### Describe the issue

When I drag an exe into dbg it crashes "no response"

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
What is the executable? Are you running x64dbg as Admin?

**Comment by DarkW0001** [comment]
> What is the executable? Are you running x64dbg as Admin?

No
