### ISSUE TITLE
Can't resize the CPU window.

### ISSUE THREAD

**Issue by xuri422** [x64dbg/x64dbg#3295]
<img width="630" alt="1703727567411" src="https://github.com/x64dbg/x64dbg/assets/31463272/d119688c-59d1-4e41-af21-5f4d65d08b00">

like in the picture, I can't resize the CPU window. I think this is a BUG.

**Comment by Tobynck** [comment]
I also want to say, this is too ugly.

**Comment by mrexodia** [comment]
> I also want to say, this is too ugly.

Thanks for your constructive feedback 😂
