### ISSUE TITLE
Feature: Add last error to CalculatorDialog

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#3296]
### Feature type

Quality of life

### Describe the feature

There is a tool `errlook.exe` in visual studio, it's very useful to kown what error happened when steped over a API call. Right now I change view to thread view and get the last error, put error code to errlook gui and see error msg.
So add a new line to show error message in CalculatorDialog would be great

**Comment by mrexodia** [comment]
The error code is also listed in the register view and I think the tooltip is Windows’ error description.

**Comment by lynnux** [comment]
Oh, yes, tooltip shows the Windows’ error description, sorry for the trouble.
