### ISSUE TITLE
In addition to log output, I hope to add a function to write out files in the script, because sometimes there are breakpoint events in the log, which can interfere with the output of DLL loading events

### ISSUE THREAD

**Issue by ziyoulang168** [x64dbg/x64dbg#3297]
### Feature type

Other

### Describe the feature

In addition to log output, the script hopes to add a feature for writing to files, as sometimes there may be breakpoint events in the log that interfere with log analysis

**Comment by ziyoulang168** [comment]
wrta "C:\ziji\tmd3API1.txt",{x:api}

**Comment by mrexodia** [comment]
This pull request adds support for outputting the breakpoint logs directly to a file instead of the log view: https://github.com/x64dbg/x64dbg/pull/3317. Please test if you can.
