### ISSUE TITLE
issue with ignore exceptions

### ISSUE THREAD

**Issue by a554335752** [x64dbg/x64dbg#330]
Can we...

add some options to pass unprocessed exceptions to unhandled exception filler like ollydbg.

pluginsdk export BreakPoint list and HardwareBreakPoint list or some callbacks

so we can write a plugin do something with unhandled exception

By the way. This is really a great project. ;-)

**Comment by mrexodia** [comment]
You can already do something with unhandled exceptions. Just register a
plugin event callback.

**Comment by a554335752** [comment]
thx! i find it..
_plugin_registercallback
CB_EXCEPTION, //callbackInfo: PLUG_CB_EXCEPTION*

how about add some options to pass unprocessed exceptions to unhandled exception filler like ollydbg..

**Comment by mrexodia** [comment]
Also there.

**Comment by a554335752** [comment]
NICE! o.O

**Comment by mrexodia** [comment]
Look in titanengine, setdbgcontinueststus or something. You can also call the dbgcontinue command.

**Comment by mrexodia** [comment]
Default is pass to debuggee by the way. This is called first chance. After that you get a second chance, which would mean a debuggee would have crashed under normal circumstances.

**Comment by a554335752** [comment]
Thanks a lot!
