### ISSUE TITLE
[feature]Non intrusive debugging

### ISSUE THREAD

**Issue by bughoho** [x64dbg/x64dbg#331]
Sometimes I don't want debugging,I just want to see the process of memory and and Code,
Hope you can add this feature.
I want to do it myself, but I don't have the snowman wrapper library.   :(

**Comment by mrexodia** [comment]
Copy and paste snowman.dll from the latest snapshot and make sure you
compile with the correct Qt version (even though the gui shouldn't need
changes for this).
