### ISSUE TITLE
Breakpoint's Log Text is limited to 256 chars

### ISSUE THREAD

**Issue by Alligator-1** [x64dbg/x64dbg#3310]
### Feature type

Quality of life, Debugging

### Describe the feature

Breakpoint's Log Text is limited to 256 characters, this may not be enough, for example I needed to log the GUID & IID of the CoCreateInstance function, I intended to do it this way:
`GUID: {x:4:[esp+4]}-{x:2:[esp+4]+4}-{x:2:[esp+4]+6}-{x:1:[esp+4]+8}{x:1:[esp+4]+9}-{x:1:[esp+4]+10}{x:1:[esp+4]+11}{x:1:[esp+4]+12}{x:1:[esp+4]+13}{x:1:[esp+4]+14}{x:1:[esp+4]+15}, IID: {x:4:[esp+10]}-{x:2:[esp+10]+4}-{x:2:[esp+10]+6}-{x:1:[esp+10]+8}{x:1:[esp+10]+9}-{x:1:[esp+10]+10}{x:1:[esp+10]+11}{x:1:[esp+10]+12}{x:1:[esp+10]+13}{x:1:[esp+10]+14}{x:1:[esp+10]+15}`

But all that text didn't fit in the input field.....

Please increase the allowed text length, or remove the restriction altogether

**Comment by Alligator-1** [comment]
Yes, thank you very much!
I downloaded the AppVeyour build (https://ci.appveyor.com/project/mrexodia/x64dbg/builds/49319534/artifacts), and tried inserting a long LogText, but unfortunately it still limited me to 256 characters.

**Comment by Alligator-1** [comment]
I think that's what this is about.
https://github.com/x64dbg/x64dbg/blob/caa578a0297b3847dd9987ded43c03e841f8f8fd/src/gui/Src/Gui/EditBreakpointDialog.ui#L79
☺️

**Comment by mrexodia** [comment]
LOL, thanks a lot. I was checking all the code for hidden limits, but I had no idea this was a thing. Please try the new build when it finishes (a comment should pop up on the pull request).

**Comment by Alligator-1** [comment]
Works very well!☺️ Thanks a lot!
