### ISSUE TITLE
Bug with Scylla plugin

### ISSUE THREAD

**Issue by DarkAnonymous** [x64dbg/x64dbg#332]
Not sure if this goes here, but dlls from the « pick dll » list of scylla never refreshes which makes the plugin only detect a minimal amount of preloaded dlls rather than the complete list when I use the external Scylla/ImportREC tool.

**Comment by DarkAnonymous** [comment]
Dumping the exe from the plugin also dumps the int3 debugger instructions which crashes the application altho I'm not sure if this is an intended behavior or not lol Anyway, I've removed them all to do my stuff.

**Comment by mrexodia** [comment]
To refresh the list, re-select the process from the process list and then use 'Pick DLL' again. This is a thing in Scylla. I cannot do anything about it.

Dumping indeed dumps with breakpoint bytes with it. Also nothing I can do about that.
