### ISSUE TITLE
Renaming a Watch Removes Spaces

### ISSUE THREAD

**Issue by utkonos** [x64dbg/x64dbg#3320]
### Operating System

Windows Server 2022 21H2 20348.169

### x64dbg Version

Feb 19 2024

### Describe the issue

The original name of a Watch contains a space. Example: `Watch 12`. Editing the name to change the number results in an unexpected name due to the space being removed. Changing this example to `Watch 11` results in the name `Watch11`.

### Steps to reproduce

1. Create a new watch
2. Change the number of the watch to a different number
3. Observe name saved with space removed in Watch tab.

### Attachments

<img width="880" alt="image" src="https://github.com/x64dbg/x64dbg/assets/2775739/9dead408-6202-422e-a6b3-129b15e4507c">

**Comment by utkonos** [comment]
Should this be committed to the development branch?

**Comment by mrexodia** [comment]
Yeah after some more testing it will be merged.
