### ISSUE TITLE
Holy mother of god. Copy every thing EXCEPT bytes? I WANT. THE BYTES. LET ME COPY THE BYTES. HOLY MOTHER OF GOD LET ME COPY THE BYTES.

### ISSUE THREAD

**Issue by satandidnowrong** [x64dbg/x64dbg#3321]
### Feature type

Quality of life

### Describe the feature

Thank you I'm going to go now.

**Comment by satandidnowrong** [comment]
it's... called... BINARY? WHEN I WANT. TO COPY BYTES.. OF HEX???????????????

HEX??????????????? IS CALLED.......................... COPY BINARY??????????????????????????????????????
COPY BINARY??????????????????????????????

**Comment by satandidnowrong** [comment]
Guys I really appreciate what you do. This is an awesome tool. You guys have skill and vast knowledge and that it is open to see, modify, use, and distribute is more than what a gift claims in its colloquial usage.

That aside this is TRASH. ABSOLUTE TRASH. I don't know who or what, when, thought that COPY HEX BYTES should be under BINARY menu and labelled COPY BINARY.
For the sake of the city Pho in Kansas, abbreviated.

**Comment by ZehMatt** [comment]
Try to behave like a normal human being and we can have a discussion.

**Comment by mrexodia** [comment]
Skill issue to be honest
