### ISSUE TITLE
x64dbg. exe startup error

### ISSUE THREAD

**Issue by neptunesoft** [x64dbg/x64dbg#3324]
### Operating System

win10

### x64dbg Version

snapshot_2024-03-19_00-55

### Describe the issue

![QQ截图20240319113433](https://github.com/x64dbg/x64dbg/assets/23578819/453a17f1-a02b-4a4b-8d48-6f74841a85bc)

### Steps to reproduce

1. x64dbg. exe startup error, x32dbg. exe is normal
2. 
3.

**Comment by SBBTD** [comment]
I’ve this issue as well. It seems that x64bridge.dll is not signed. use x64dbg-unsigned.exe instead until it's fixed.

**Comment by mrexodia** [comment]
Thanks, there was a connection error during signing that DLL. I improved the script to error properly if it fails again.
