### ISSUE TITLE
x64dbg starts a freezing loop after attaching to or opening a process

### ISSUE THREAD

**Issue by ghost** [x64dbg/x64dbg#3325]
### Operating System

Windows 11, OS Build 22631.3296

### x64dbg Version

Any 

### Describe the issue

When I open a process or attach to a process, x64dbg will get stuck in a loop of freezing and unfreezing, rendering the whole debugger unusable, I cannot click anything, It will simply keep switching between Not Responding and Responding for a few milliseconds, from visual glance I think freeze happens whenever I click in the debugger.

I thought this might have been caused by some malware, but I reinstalled windows and the issue persists for x64 version of the debugger, x32dbg works perfectly fine with absolutely 0 issues.

For reference, I have an MSI Laptop with 4060 and a pretty good i7 so I doubt the problem's there.

Any help/recommendation is welcome.

**Steps that I've done**
- Tried using integrated graphics card/nvidia card
- Reinstalled windows
- Reinstalled vcredist
- Running as admin
- Redownloading a different version

### Steps to reproduce

1.  Open x64dbg
2. Open/Attach any x64 process
3. Freeze will appear after first click on anything

**Comment by mrexodia** [comment]
Could you record a video of this happening? This obviously doesn't happen for me locally. Are you running inside a VM or on bare metal?

**Comment by mrexodia** [comment]
Can you try it with the latest version? This version is from 2023...
