### ISSUE TITLE
It looks the software captured this error in program so I cannot found this error in system log.

### ISSUE THREAD

**Issue by Rian171997** [x64dbg/x64dbg#3330]
It looks the software captured this error in program so I cannot found this error in system log.

Yeah, bad news: the software doesn't write logs either.

_Originally posted by @Flithor in https://github.com/x64dbg/x64dbg/discussions/2999_

**Comment by mrexodia** [comment]
The logs are available in the “Log” tab, it’s difficult to help without any additional information. Can you reproduce it again and send a video?

**Comment by mrexodia** [comment]
You will have to debug the program to find out why a certain LastError was set.
