### ISSUE TITLE
Easily symbolizing call stacks

### ISSUE THREAD

**Issue by ynwarcs** [x64dbg/x64dbg#3332]
### Feature type

Quality of life

### Describe the feature

It would be very nice if we could symbolize callstacks efficiently from the call stack view, i.e. load symbols for all (or selected) modules in the call stack of a thread. This is very useful when debugging complex OS binaries, where a call to e.g. `CreateFile` can be preceded by a chain of functions from 10+ different modules. At the moment, the most efficient way to do this is to switch to the "Symbols" view and load symbols for modules one-by-one, or all loaded modules at once, which can take a crap load of time if the program has a giant module like combase.dll.

I implemented a demo on a local branch (https://github.com/ynwarcs/x64dbg/commit/5e4aa6053e7e5362e530fb1c1fea54536201f9a4), if this is deemed useful enough for the general audience, I can make a PR.

**Comment by mrexodia** [comment]
Yeah, this would be a great feature to have I think! It’s been on my todo list for a while, but never got to it because eventually you load all the relevant DLLs 😅
