### ISSUE TITLE
Run trace failure

### ISSUE THREAD

**Issue by tffzmp** [x64dbg/x64dbg#3339]
### Operating System

Win10 64 19045.4291

### x64dbg Version

2024-04-11_18-47

### Describe the issue

version
[snapshot_2024-04-11_18-47.zip](https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2024-04-11_18-47.zip/download)

trace over.... ctrl + alt + f8 

---------------------------
ERROR
---------------------------
Cannot start a trace when running, pause execution first.
---------------------------
OK   
---------------------------

### Steps to reproduce

1.  select call code
2.  ctrl + alt + f8 
3.  show error message

**Comment by mrexodia** [comment]
Did you pause execution?

**Comment by tffzmp** [comment]
> Did you pause execution?

Oh, I see. Thank you so much
