### ISSUE TITLE
Option to temporarily disable the use of database

### ISSUE THREAD

**Issue by faltur** [x64dbg/x64dbg#3341]
### Feature type

Quality of life

### Describe the feature

I'm working on a relative big target executable 50MB+, and using my own labeler script to apply names to unknown symbols, **when I need them**. Unfortunately, everytime I load the target or restart it, x64dbg will automatically load its internal database and this process is taking too long to be accomplished, wasting my time during debugging. I would like to suggest to implement an option to temporarily disable the use of the database by adding a simple boolean control, such as a check or radio button. I'm aware of the option that clear the database, but it's not enough in my case because I have to restart the target many times in a row.

**Comment by torusrxxx** [comment]
Another group of people complained that they cannot save the database at #2836. Then I have a quick solution for you without modifying any code:
Make all your database files readonly!

**Comment by faltur** [comment]
Thanks for the tip, it solved my problem!

**Comment by justanotheranonymoususer** [comment]
I encountered this so many times... I'd really love to have one or more of the following:
* Not reloading the db when reloading the process, it can take dozens of seconds to unload and reload what's already loaded
* Loading only essential data such as bps right away, and load the rest (labels etc.) in the background, just like symbols are loaded in the background
* Faster db saving and loading (one can wish... not sure how many low hanging fruits are there)
