### ISSUE TITLE
Write file contents to debuggee memory location

### ISSUE THREAD

**Issue by not6** [x64dbg/x64dbg#3347]
### Feature type

Other

### Describe the feature

There is a feature that does about the opposite - saves a memory region to a file. It would be useful to have a simple built-in way to load a binary file and write its contents to a specified address in the debuggee, for example a command similar to memcpy which would take a filename instead of a source address, or a different version of the alloc command which loads a file into memory rather than just allocating zero-initialized memory

**Comment by torusrxxx** [comment]
Same as #1370 - patches welcome!
