### ISSUE TITLE
rizin/radare2 vim philosophy interface fox x96dbg

### ISSUE THREAD

**Issue by gogo2464** [x64dbg/x64dbg#3350]
### Feature type

Other

### Describe the feature

Hello.

I love the r2/rizin commands/console interface. it has a powerfull vim philosophy to navigate really fast. It is also scriptable. The commands work on any os and it is great! Sadly these plugin philosophy encourage dev to rewrite plugins instead of using serious engines.

It follows:

- debugger issue.

I suggest to add a rizin console for x96dbg so that we could use it from a terminal with the good interface philosophy as well as the good internals.

the issue is x96 is windows only and has not linux support.

Might be better to implemnt an rizin plugin instead of forking x96 dbg instead.

I need help and recommendations for the philosophy.

**Comment by mrexodia** [comment]
Personally I think there is nothing good about radare2 commands.

**Comment by gogo2464** [comment]
I personally prefer s sy.my-func instead of scrolling for hours!

Of course i never planned to replace gui by commands.

I just want to add a console interface.

**Comment by mrexodia** [comment]
Fundamentally x64dbg is a GUI application and there is never going to be a terminal-based interface. If your solution to finding a function is to scroll for hours that just means you don't understand the tool you are using. There are commands (documentation here https://help.x64dbg.com/en/latest/commands/index.html), but for almost all use cases there is a faster way to do what you want from the UI.
