### ISSUE TITLE
Chinese characters cannot be displayed correctly（中文乱码）

### ISSUE THREAD

**Issue by iammmmmmm** [x64dbg/x64dbg#3351]
### Operating System

windos 11 home 10.0.22631

### x64dbg Version

apr 11 2024

### Describe the issue

Chinese or other languages ​​cannot be displayed normally and are garbled.
中文或者其他语言无法正常显示，出现乱码。
#2811 also raised this bug, but without any valid information.
#2811 也提出了此bug，但是没有任何有效信息。    
I guess it's caused by me turning on utf8 globally in Windows, I'll try turning it off and check if it's normal.
我猜测是我打开了windows全局utf8导致的，我会尝试关闭它后再检查是否正常。

### Steps to reproduce

1. 打开xdbg
2. 打开任意dll或exe或附加到任意程序（含有中文或其他）
1. Open xdbg
2. Open any dll or exe or attach to any program (including Chinese or other)

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/73742531/1197e707-2302-44a3-8bb9-86bd85a80cbf)
![image](https://github.com/x64dbg/x64dbg/assets/73742531/626ee9d7-e887-4371-bcc9-583bbd14d76e)

**Comment by iammmmmmm** [comment]
![image](https://github.com/x64dbg/x64dbg/assets/73742531/bd899bcd-0573-4c62-a7fb-0234ff459f31)
Unfortunately, I turned off global utf8 and still got garbled characters.
非常不幸的是我关闭了全局utf8依旧是乱码

**Comment by torusrxxx** [comment]
这是因为软件判断不了字符串是不是有意义的，只要可以用中文解码的东西都可以视为中文字符串，如果实际上不是中文字符串的话，直接忽略吧

**Comment by iammmmmmm** [comment]
感谢您的回答。也许还是我太菜了😂分不出来。我之后又拿ce扫描程序里的字符串，有很多乱码字符串应该是程序做的反破解防护。
