### ISSUE TITLE
Assembler allows CR1 register to be assembled

### ISSUE THREAD

**Issue by mazegen** [x64dbg/x64dbg#3370]
### Operating System

Windows 10 x64 build 19045.4412

### x64dbg Version

Jun 3 2024

### Describe the issue

Assembler allows CR1 register to be assembled although this register doesn't exist.

### Steps to reproduce

1. Load any x64 EXE file
2. Move to any address where you can assemble code
3. Press Space and type `mov cr1, rax`
4. Press Enter

The assembler should reject this instruction because CR1 doesn't exist.

The same applies to `mov rax, cr1`.

**Comment by mrexodia** [comment]
This will have to be reported upstream: https://github.com/asmjit/asmtk/
