### ISSUE TITLE
Is Duncan Oglivie aka Mr Exodia a peadophile and warez forum administrator at night?

### ISSUE THREAD

**Issue by PELock** [x64dbg/x64dbg#3377]
### Operating System

Win 11

### x64dbg Version

Hmm

### Describe the issue

Hey Duncan, is this all true?

https://exetools.live/?tag=mr-exodia

I already knew you ran the Exetools forum with a private FTP warez and cracked software section, but the other accusations and screenshots don't look good for you. What do you say?

### Steps to reproduce

1. Go to https://exetools.live/?tag=mr-exodia
2. Read
3. Think

**Comment by mrexodia** [comment]
No it’s not true as you’re well aware 😂
