### ISSUE TITLE
Keep instruction size when assembling (warn before consuming bytes from next instruction)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#338]
Hi, there is a minor option in OllyDbg which prevents you from assembling to the current line
if the new instruction size > current instruction size, it would be helpful if this feature is implemented.

Many times i don't know the size of the new instruction, and instead of warning it simply eats some bytes from the next instruction and fills the rest of it with NOPs.

Here is picture of what am i talking about:
![untitled](https://cloud.githubusercontent.com/assets/11916365/8682513/b97de0c8-2a6d-11e5-9a81-a138453eff23.png)

**Comment by fuguwi** [comment]
+1

**Comment by wk-952** [comment]
Thanks :+1:
