### ISSUE TITLE
Scrolling Options

### ISSUE THREAD

**Issue by Timo2024** [x64dbg/x64dbg#3387]
### Feature type

Quality of life, Other

### Describe the feature

Hey, thank you for this amazing project. I'm not sure if this has been brought up, but I searched for a bit and didn't find a match. Maybe there is an option, here is a video of what I'm talking about. The ability to scroll, maybe the program can detect a long string or have an option to word wrap in the CPU window and the below window as well would be amazing.

https://github.com/x64dbg/x64dbg/assets/45249414/5672537a-5dbb-4ba8-b7d5-91ebc38aa5b7

**Comment by iArtorias** [comment]
Either create a custom script to retrieve the specific string value from the pointer or just press ";" keyboard button and copy an entire string. There is no real need in making it as complex as you described in your post/video.

**Comment by Timo2024** [comment]
I'm sorry I'm new to this stuff, I'll close this, thank you for the response.
