### ISSUE TITLE
Patches window wrong behavior

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#339]
Consider the following 2 instructions:
JMP E71BC5  | E9 79 FE FF FF
MOV edi, edi  | 8B FF

1) Both instructions are below each other and separated by a certain distance (there could be at
most 3 instructions between them otherwise this bug/behavior won't occur).

2) Change the JMP address to E71BC4 for example, and the 2nd operand of
the MOV instruction to EAX (or any register).

3) Now when you open the patches window (Ctrl + P) and deselect the first change you made,
the second one is also deselected with it.

- So both changes are linked together even though they correspond to different instructions,
  it doesn't have to be a JMP followed by MOV, any 2 instructions actually with separating distance
  <= 3 instructions.
- If there are 4 or more instructions between them, you can normally deselect one change only.
- If you couldn't reproduce this on any other application (which i doubt since it happens all the time)
  i can upload the application i used, it's just a trainer i made in Cheat Engine.

This pic shows that you can deselect one change only as you wish if the distance is 4 instructions:
![dist_4](https://cloud.githubusercontent.com/assets/11916365/8683311/3ab95cb8-2a72-11e5-8d9f-11cc086f2929.png)

While in this one as you can see, both must be selected/deselected together:
![dist_3](https://cloud.githubusercontent.com/assets/11916365/8683331/5bdc4518-2a72-11e5-8720-7e78ebea56a9.png)

**Comment by mrexodia** [comment]
The distance for group selection is 9 bytes. This is for the 'Pick Groups' dialog. A better heuristic than bytes cannot really be made (since there is no way to tell alignment or even if the patches are inside code in an easy way).

If you want to select/deselect just one patch, simply hold CTRL and click the checkbox :+1:

**Comment by wk-952** [comment]
Thanks for the info, didn't know about that.
