### ISSUE TITLE
Trace browser goto by virtual address

### ISSUE THREAD

**Issue by Epenko1337** [x64dbg/x64dbg#3390]
### Feature type

Quality of life

### Describe the feature

In trace browser we can do goto by index but i think it will be much useful if we could goto by VA like in cpu browser.

**Comment by mrexodia** [comment]
You cannot really do this in a meaningful way. There might be many occurrences of the same address…

**Comment by Epenko1337** [comment]
For sure but then dont see any use case where goto by index can be used.

**Comment by torusrxxx** [comment]
I agree with @mrexodia. Fortunately a real solution can be made easy by #3098. With indexed search it should work faster than your brute force search and can display an dialog when multiple occurrences are found. It will be released soon.

**Comment by Epenko1337** [comment]
Awesome, will be waiting for release.
