### ISSUE TITLE
jul 11 2024 error is win7

### ISSUE THREAD

**Issue by neptunesoft** [x64dbg/x64dbg#3394]
![QQ截图20240717175229](https://github.com/user-attachments/assets/b50d62bb-516e-4839-937c-b1ed0070b210)

**Comment by mrexodia** [comment]
You need to install the latest service pack and windows update. Or you can use x64dbg-unsigned.exe

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/issues/3076#issuecomment-1528789001

**Comment by torusrxxx** [comment]
The coming issues on DLL signature validation are a bit too many that a FAQ entry could be helpful.

**Comment by mrexodia** [comment]
Alright, I added a FAQ entry. But I don't think people actually read it when encountering issues 😅
