### ISSUE TITLE
能不能像 cheat engine加一个veh debugger 的模式

### ISSUE THREAD

**Issue by jianforgithub** [x64dbg/x64dbg#3408]
### Feature type

Other

### Describe the feature

能不能像 cheat engine加一个veh debugger 的模式，我在实际使用中。xdbg只要触发断点就会程序崩溃掉，根据程序退出的提示是说我没有处理断点异常 使用cheat engine 时候，当使用windows debugger也出现一样的情况 。使用了veh就正常 调试了

**Comment by torusrxxx** [comment]
不能，和#3169相同
