### ISSUE TITLE
Copy -> Selection (Bytes only)

### ISSUE THREAD

**Issue by d2k2-git** [x64dbg/x64dbg#3409]
### Feature type

Quality of life

### Describe the feature

Currently it is possible to copy instruction bytes only with via context menu over "Binary -> Copy". However it would be nice to have also a way to do the same but with keeping the line breaks, so that i don't have to format it output manually.

![image](https://github.com/user-attachments/assets/1e0f2c2e-bc5e-4a7e-8493-7a7f7df2dcd3)

Since are already features to copy the Addresses, assembly instructions, why not also have the possibility to copy instruction bytes line by line :)

There could be a new Context Menu entry under "Copy -> Selection (Bytes only)" or "Binary -> Copy (with Linebreaks)"

The expected result would like like this

```
74 0A 
48 8B C8 
E8 E5 61 00 00 
EB 03 
48 8B C5 
48 89 05 01 60 91 02 
E8 B4 6E 00 00 
E8 2F ED FF FF
```

**Comment by mrexodia** [comment]
Why do you need the feature like this? What are you going to do with the output?

**Comment by torusrxxx** [comment]
Tip: Copy and paste in Microsoft Word
<img width="438" alt="Copy and paste in Microsoft Word" src="https://github.com/user-attachments/assets/3fb3f03b-6391-4400-9072-7fae3bb9c8c4">

**Comment by mrexodia** [comment]
Yeah the reasoning makes sense, I’ll add it. There’s also various sigmaker plugins available though, might be helpful too!
