### ISSUE TITLE
Optionally use symbol displacement

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#341]
Displacement is just the beginning of a symbol + offset. This is better applied along with function analysis.

`Symbol+Offset`
![image](https://cloud.githubusercontent.com/assets/4228359/8714154/b8c5c9c0-2b3f-11e5-8fff-c0ce54c194d5.png)

**Comment by mrexodia** [comment]
looks nice to me..

**Comment by torusrxxx** [comment]
implemented in #1243
