### ISSUE TITLE
 fs: [0x0] is wrong

### ISSUE THREAD

**Issue by ziyoulang168** [x64dbg/x64dbg#3416]
### Operating System

win11

### x64dbg Version

jul12 2024

### Describe the issue

Today I discovered that fs: [0x0] does not point to the starting address of teb, which is a strange issue and the debugger will not make any mistakes

### Steps to reproduce

1. 
2. 
3. 

### Attachments

![image](https://github.com/user-attachments/assets/be10d151-901a-45bc-bdca-f8b2b6edcfef)
![image](https://github.com/user-attachments/assets/81440095-39c3-4706-9593-c57889669196)

**Comment by ziyoulang168** [comment]
![image](https://github.com/user-attachments/assets/c0277ab6-618e-40fc-9e14-9b94ccde17a7)
This is the correct parsing result

**Comment by mrexodia** [comment]
Where did you enter `fs:[0]`? Because this expression reads a DWORD from the FS_BASE address, probably you want to use `teb()` instead?

**Comment by ziyoulang168** [comment]
Thank you for understanding
