### ISSUE TITLE
dll does not have a valid signature

### ISSUE THREAD

**Issue by gomapta** [x64dbg/x64dbg#3419]
### Operating System

window 11 64bit

### x64dbg Version

jul 28 2024

### Describe the issue

i can't run x64dbg because of this error
![dll](https://github.com/user-attachments/assets/9a73913a-8a44-4d58-826f-6211ebf18f6b)
i've already reinstalled x64dbg and visual C++ 2013, but it doesn't work. How can i fix it?

### Steps to reproduce

1. 
2. 
3.

**Comment by mrexodia** [comment]
Please use the previous issue.
