### ISSUE TITLE
[New Feature] Getting additional line reference detail

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#342]
x64dbg fills additional info for quick and easy sight in the section down below the cpu window (References window), concerning to the command being selected or executed. It gets the info but for certain lines, it should be great to get info like: 
- Line Reference based on Jump from/Call from

This OllyDbg view
![olly](https://cloud.githubusercontent.com/assets/13303069/8714161/076a6a06-2b2f-11e5-800a-678ad7bb69be.jpg)

This is x64Dbg view
![x64dbg](https://cloud.githubusercontent.com/assets/13303069/8714167/1d79d9da-2b2f-11e5-9e27-0007a99d85c2.jpg)

I find this characteristic (line reference + dissasembly jump shortcut) really useful on static analysis as it gives a fast command cross reference view without the need of doing that manually pressing Ctrl+R to see if there are any references involved. It's just a point of view of making things even easier and as close at hand as possible, so determine whether it is feasible or not

**Comment by mrexodia** [comment]
should be feasible when static analysis is better

**Comment by fuguwi** [comment]
+1

**Comment by mrexodia** [comment]
implemented in #705 (use the command `analx` and press X to browse through the references)
