### ISSUE TITLE
[issue] xxxdbg.ini

### ISSUE THREAD

**Issue by a554335752** [x64dbg/x64dbg#343]
[Symbols]
CachePath=C:\Documents and Settings\Administrator\桌面\release\x32\symbols

Default CachePath=./symbols Could be better?
After you move the folder...

**Comment by mrexodia** [comment]
Yea, but ./symbols would only work if you start x64dbg from it's own directory. When you use the context menu it will create a symbols folder in the folder of the executable you're debugging.

Will fix this by detecting if `./` was in front of the path and then just replacing that with the x64dbg.exe path.
