### ISSUE TITLE
How to Display Detailed Stack Information in x32dbg Like OllyDbg?

### ISSUE THREAD

**Issue by HongKyoungIn** [x64dbg/x64dbg#3430]
### Feature type

Other

### Describe the feature

Hello,

I am currently using x32dbg for debugging and I'm having trouble displaying stack information in as much detail as OllyDbg does. In OllyDbg, the stack window shows detailed information such as Style, Title, and Text. However, in x32dbg, the stack window does not display these details in the same way, making it difficult to view certain information clearly.

I've heard that using the ScyllaHide plugin might help enhance the stack information display in x32dbg. Could you please provide detailed steps on how to configure ScyllaHide or any other settings in x32dbg to display the stack information more clearly, similar to how it is presented in OllyDbg?

Any guidance or tips on this would be greatly appreciated!

![1](https://github.com/user-attachments/assets/964ce8fa-5cd2-4577-aa02-9dc9d141ad7b)
[x32dbg]

![2](https://github.com/user-attachments/assets/4e61af5c-2b24-4990-97ff-3c6530278272)
[ollydbg]

**Comment by mrexodia** [comment]
Duplicate issue, #2302

**Comment by HongKyoungIn** [comment]
> Duplicate issue, #2302

![ollydbg](https://github.com/user-attachments/assets/f30b3c3c-e1ba-474f-9093-796f024f1bfb)
[ollydbg]

![x32dbg](https://github.com/user-attachments/assets/3adac7d7-48ac-4466-b639-1811d10b8f71)
[x32dbg]


I was referring to the "StackWindow" part. How can I display it in detail, like in OllyDbg?

**Comment by mrexodia** [comment]
See https://github.com/x64dbg/x64dbg/issues/2174
