### ISSUE TITLE
Unusable in right-to-left language

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#3434]
It's absolutely unusable when the language is set to a right-to-left language. No user reported this problem yet, probably they have uninstalled already.

**Comment by torusrxxx** [comment]
paintContent in AbstractTableView needs update. RichTextPainter used to display disassembly also needs update. Then some other minor fixes, for example Sidebar and Registers.

**Comment by mrexodia** [comment]
I honestly don't see a need to prioritize this, especially if it increases the code complexity...

**Comment by mrexodia** [comment]
It's just that the performance of the RichTextPainter is already quite bad, so adding more checks for RTL might decrease the performance for regular users. If there is a way to not get a slowdown then it's of course fine to add.
