### ISSUE TITLE
Main window position and size cannot be saved

### ISSUE THREAD

**Issue by 793359277** [x64dbg/x64dbg#3437]
### Operating System

Win10 x64 22H2 19045.2965

### x64dbg Version

Aug 30 2024

### Describe the issue

Main window position and size cannot be saved

As of today, the latest version still does this
The virtual machine Win11 test is fine.

snapshot_2022-09-07_14-52， This version is ok.
But I used a version of 2024 before, which was normal. I don't know when the above problem started to appear(Previously my system was Win10 2004).

### Steps to reproduce

1. unknown
2. unknown
3. unknown

### Attachments

![12](https://github.com/user-attachments/assets/b10014be-74d6-4e71-9cfb-c58a4de1ef76)

![13](https://github.com/user-attachments/assets/15f8759d-6d1a-4a8d-b404-b4f19a41a17d)

**Comment by 793359277** [comment]
In the virtual machine, Win10 22H2 19045.4046 is fine

![14](https://github.com/user-attachments/assets/a67d1771-47cf-4a6a-8ab8-f67dfdcc84fb)

**Comment by 793359277** [comment]
I think there might be something wrong with my system, but I'm not sure what caused it.

**Comment by 793359277** [comment]
If I run with x64dbg debugging, the window position is magically preserved, but if I run directly I still get the error.

2.4mb GIF
![15](https://github.com/user-attachments/assets/1be2f95d-1524-421d-b353-199e96f2238d)

**Comment by 793359277** [comment]
The test found that if the left position of the window is less than 0 when closing, the window position and size can be saved normally, which is very strange.

![15](https://github.com/user-attachments/assets/2cd70186-3a44-4fcf-b6fc-4b0df9477eac)

**Comment by 793359277** [comment]
I created a new system account and ran x64dbg with this account, but this problem did not occur. What is going on? I can't find the reason. Help me.

**Comment by mrexodia** [comment]
The window position is saved in `x64dbg.ini`. Make sure the folder is writable, otherwise the settings will reset to the default.

**Comment by torusrxxx** [comment]
When x64dbg crashes on exit the settings may not be saved. And system configuration have a role as well. I see inconsistent results when I connect two monitors with different DPI settings. Sometimes the window size saved is magnified by DPI scaling on next startup, but not always. Maybe something buggy with the system. Even the explorer doesn't always look correct with such monitor settings.

**Comment by 793359277** [comment]
> The window position is saved in `x64dbg.ini`. Make sure the folder is writable, otherwise the settings will reset to the default.

All the settings in x64dbg can be saved, such as events, engines, exception settings, etc., but the window position is a problem

**Comment by 793359277** [comment]
> When x64dbg crashes on exit the settings may not be saved. And system configuration have a role as well. I see inconsistent results when I connect two monitors with different DPI settings. Sometimes the window size saved is magnified by DPI scaling on next startup, but not always. Maybe something buggy with the system. Even the explorer doesn't always look correct with such monitor settings.

All the settings in x64dbg can be saved, such as events, engines, exception settings, etc., but the window position is a problem.  
![15](https://github.com/user-attachments/assets/4bd37fcd-a034-4996-9b50-8ec4576f9c8a)

**Comment by 793359277** [comment]
> The window position is saved in `x64dbg.ini`. Make sure the folder is writable, otherwise the settings will reset to the default.

All the settings in x64dbg can be saved, such as events, engines, exception settings, etc., but the window position is a problem.
![15](https://github.com/user-attachments/assets/89a8b9e8-3f86-411a-8ada-482c09fa5976)

**Comment by 793359277** [comment]
> The window position is saved in `x64dbg.ini`. Make sure the folder is writable, otherwise the settings will reset to the default.

The snapshot_2022-09-07_14-52 mentioned above has no problem. I started the latest version, adjusted the window size and position, closed the software, and BridgeSettingFlush returned true. I manually copied the latest version of x64dbg.ini to the 2022-09-07 version directory, started the 2022-09-07 version of x64dbg.exe, and the window position and size were retained and reproduced. This shows that the memory configuration items have been successfully written to x64dbg.ini when exiting, and it should be a problem when starting the software.

**Comment by 793359277** [comment]
This problem does exist, but others cannot reproduce it under normal circumstances. If possible, I hope to optimize the code for saving and reading the window position and size.

In order to use it normally, I had to write a plug-in to record the window position and size. When x64dbg exits, it is recorded with GetWindowRect, and when it starts, MoveWindow is used to adjust the window information, so this problem will not occur.

**Comment by mrexodia** [comment]
The code for saving the window information is rather simple:

https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/MainWindow.cpp#L960-L987

Then the restore is called on startup:

https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/MainWindow.cpp#L989-L1038

**Comment by mrexodia** [comment]
Perhaps the change happens because `restoreGeometry` is called in the constructor of `MainWindow`?

https://github.com/x64dbg/x64dbg/blob/74c6d2a5792ce2f7b8555fd527104f2a469ec168/src/gui/Src/Gui/MainWindow.cpp#L416-L419

For me this is working, but maybe there is some bug in Qt here?

**Comment by mrexodia** [comment]
I pushed an attempted fix to the `development` branch. A new snapshot should be released soon, please try it and let me know (make sure to remove your plugin first obviously).

**Comment by torusrxxx** [comment]
Previously, there is a problem that x64dbg flashes briefly at the initial position before being moved to saved position and size, that's why it was changed.

**Comment by 793359277** [comment]
> I pushed an attempted fix to the `development` branch. A new snapshot should be released soon, please try it and let me know (make sure to remove your plugin first obviously).

snapshot_2024-09-10_15-35 I tested it and it worked fine. The window information was correctly restored at startup.

**Comment by mrexodia** [comment]
Good to hear it's resolved!
