### ISSUE TITLE
x64dbg sets conditional breakpoint on xmm register but fails to work

### ISSUE THREAD

**Issue by jianghupt** [x64dbg/x64dbg#3449]
### Operating System

windows 11  10.0.22631.4169

### x64dbg Version

 Jun 3 2024

### Describe the issue

I used x64dbg to set breakpoints on the xmm register, but the breakpoints did not work. I don't know why. How should I set xmm breakpoints?

### Steps to reproduce

1. It breaks when setting xmm7==0
2. But it doesn't break
3. Other xmm registers such as xmm0 and xmm1 do not work

### Attachments

![image](https://github.com/user-attachments/assets/1b51c025-e330-4094-bc04-b6493b0784fe)

**Comment by mrexodia** [comment]
There is no support for expressions involving XMM registers currently, so this is the expected behavior.

**Comment by jianghupt** [comment]
> There is no support for expressions involving XMM registers currently, so this is the expected behavior.

So how do I determine the value of the xmm register?

**Comment by torusrxxx** [comment]
Yes, you should look at the log, there should be a message saying your expression with XMM is invalid. You can write the XMM register to memory using MOVUPS and use that memory location instead, but when the XMM contains -0.0 or 0.0000001 or something instead it will not work.
