### ISSUE TITLE
[Bug] Registers edition textboxes don't get updated when first opened

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#345]
On editting register/stack values, textboxes don't get updated when first opened, so you have to press a key on the text control to update it and show the rest of the value info.

![captura](https://cloud.githubusercontent.com/assets/13303069/8764131/efd7248a-2d7f-11e5-8844-438d0f931122.PNG)

This might look something insignificant, but I guess this is not the way it was planned to work, however if I'm wrong just omit & close this report

**Comment by fileoffset** [comment]
Fixed in my latest pull request
