### ISSUE TITLE
Issues creating a command that logs when strings are loaded into registers

### ISSUE THREAD

**Issue by rapidgiga** [x64dbg/x64dbg#3456]
I've created a custom command that steps over user code and logs:
- the current address
- the register type
- the string loaded into the register

I'd like to run this command continuously over the entire program as an overnight job (I've redirected logs to a text file).

I'm currently using the `Tracing > Animate command...` feature to run my custom command, however it often gets stuck stepping into system code (e.g. `kernel32.dll`).

To get around this, I added this code to the top of my command handler. The idea was to detect if I've stepped into non-user code, and if so, step out:
```c
SELECTIONDATA selData;
GuiSelectionGet(GUI_DISASSEMBLY, &selData);

char moduleBuffer[1024] {};
DbgGetModuleAt(selData.start, moduleBuffer);

if (strcmp(moduleBuffer, "my_module") != 0)
{
    Script::Debug::StepOut();
}
else
{
    Script::Debug::StepIn();
}
```

This works most of the time, however sometimes the GUI doesn't update in time (my animate command frequency is set to 50ms), causing my command to call `StepOut` twice, therefore skipping over some user code.

Solutions I'm not sure are possible:
- Find a way to run `disasm.sel()` or `p:cip` to get the current instruction's address, instead of `GuiSelectionGet()`
- Find another way to get the current module name. I saw references to `GetModParty` on another GitHub issue, but I'm not sure how to call it
- Call a function to wait for the GUI to update
- Register a callback for when the GUI finishes updating
- Call [RunToParty](https://help.x64dbg.com/en/latest/commands/tracing/RunToParty.html?highlight=party) when the current module is not user code, to run all the way back to user code

I've also thought of writing this whole script as a trace log condition, however I'm unsure how to check if RCX holds a valid string. I tried setting `utf(RCX) != ''` in the log condition, but saw on another post that string expressions aren't supported yet.

![image](https://github.com/user-attachments/assets/ff82f158-0119-46a2-914e-4aefac9a3cca)

Loving using x64dbg so far, this is a powerful tool! I'm still very new so I'd love to know if I'm brute forcing this when there's a more elegant solution available.

Here is my full plugin code, which uses the basic [PluginTemplate](https://github.com/x64dbg/PluginTemplate):

```c
#include "plugin.h"
#include <ctype.h>

unsigned long long lastRAX;
unsigned long long lastRBX;
unsigned long long lastRCX;
unsigned long long lastRDX;
unsigned long long lastR8;
unsigned long long lastR9;
char moduleBuffer[1024] {};
char registerBuffer[1024] {};

bool IsValidChar(char v)
{
    return isdigit(v) || isalpha(v) || v == '.' || v == '/';
}

bool IsValid(bool isAscii)
{
    return IsValidChar(registerBuffer[0]) && IsValidChar(registerBuffer[isAscii ? 1 : 2]);
}

void LogRegisterString(LPCSTR registerName, unsigned long long& registerAddress)
{
    MemoryReadSafe(DbgGetProcessHandle(), (PVOID)registerAddress, registerBuffer, sizeof(registerBuffer), NULL);

    bool isAscii = registerBuffer[1] != 0;

    if (IsValid(isAscii))
    {
        if (isAscii)
            dprintf("%s: 0000%llx, %s\n", registerName, registerAddress, registerBuffer); // ASCII   
        else
            dprintf("%s: 0000%llx, %S\n", registerName, registerAddress, registerBuffer); // UTF-16
    }
}

static bool cbExampleCommand(int argc, char** argv)
{
    // If we stepped into code that isn't ours, step back out.
    //   This doesn't work as sometimes the GUI doesn't update in time, causing us to back out twice and therefore skipping some user code
    SELECTIONDATA selData;
    GuiSelectionGet(GUI_DISASSEMBLY, &selData);
    DbgGetModuleAt(selData.start, moduleBuffer);

    if (strcmp(moduleBuffer, "my_module") != 0)
    {
        Script::Debug::StepOut();
    }
    else
    {
        Script::Debug::StepIn();
    }


    // Log the strings held in registers   
    unsigned long long rax = Script::Register::GetRAX();

    if (rax != lastRAX)
    {
        LogRegisterString("RAX", rax);
        lastRAX = rax;
    }

    unsigned long long rbx = Script::Register::GetRBX();

    if (rbx != lastRBX)
    {
        LogRegisterString("RBX", rbx);
        lastRBX = rbx;
    }

    unsigned long long rcx = Script::Register::GetRCX();

    if (rcx != lastRCX)
    {
        LogRegisterString("RCX", rcx);
        lastRCX = rcx;
    }

    unsigned long long rdx = Script::Register::GetRDX();

    if (rdx != lastRDX)
    {
        LogRegisterString("RDX", rdx);
        lastRDX = rdx;
    }

    unsigned long long r8 = Script::Register::GetR8();

    if (r8 != lastR8)
    {
        LogRegisterString("R8", r8);
        lastR8 = r8;
    }

    unsigned long long r9 = Script::Register::GetR9();

    if (r9 != lastR9)
    {
        LogRegisterString("R9", r9);
        lastR8 = r9;
    }

    return true;
}

bool pluginInit(PLUG_INITSTRUCT* initStruct)
{
    dprintf("pluginInit(pluginHandle: %d)\n", pluginHandle);

    _plugin_registercommand(pluginHandle, "stepandlog", cbExampleCommand, true);

    return true;
}

void pluginStop()
{
    dprintf("pluginStop(pluginHandle: %d)\n", pluginHandle);
}

void pluginSetup()
{
    dprintf("pluginSetup(pluginHandle: %d)\n", pluginHandle);
}

**Comment by mrexodia** [comment]
As mentioned in the other issue, the tracing functionality currently does not support quietly skipping instructions located in system DLLs. That being said, you can set your own tracing callback:

https://help.x64dbg.com/en/latest/developers/plugins/Callbacks/plugcbtraceexecute.html

```
PLUG_EXPORT void CBTRACEEXECUTE(CBTYPE cbType, PLUG_CB_TRACEEXECUTE* info)
{
    if(DbgFunctions()->ModGetParty(info->cip) == mod_system)
        return; // skip system modules

    // TODO: read relevant registers
}
```

Then you can start a trace like this:

```
static bool cbExampleCommand(int argc, char** argv)
{
    // TODO: reset some state

    DbgCmdExecDirect("TraceIntoConditional \"0\", 0x1000000")
}
```

This might be a bit faster than manually calling `StepUser`, since you skip the constant command parsing. Eventually I will a command like `TraceSetParty user` to have the trace call `StepIntoUser` internally.

You might also take a look at [dumpulator](https://github.com/mrexodia/dumpulator) btw, might be easier to achieve what you want using some kind of emulation.

**Comment by rapidgiga** [comment]
`CBTRACEEXECUTE` is perfect, my script is now running much faster. Thank you for the help and quick responses!
