### ISSUE TITLE
In last version Scylla is no more in plugin directory

### ISSUE THREAD

**Issue by melectronvolt** [x64dbg/x64dbg#3460]
### Operating System

Windows 11

### x64dbg Version

snapshot_2024-10-18_19-09

### Describe the issue

In menu -> plugin. It's empty.
To open Scylla, Ctrl + I Works. 

### Steps to reproduce

1.  open x64dbg
2.  click on menu
3.  empty

**Comment by mrexodia** [comment]
This is on purpose, it will be removed from x64dbg in the future.

**Comment by mrexodia** [comment]
You can still use it from the menu bar btw:

![image](https://github.com/user-attachments/assets/b80bc143-9bbd-4115-9b5f-2544ca75fe25)
