### ISSUE TITLE
[Issues] with pluginsdk/_plugin_types.h

### ISSUE THREAD

**Issue by a554335752** [x64dbg/x64dbg#347]
../include/x64dbg/pluginsdk/_plugin_types.h:11:29: fatal error: dbghelp\dbghelp.h: No such file or directory
 #include "dbghelp\dbghelp.h"

//_plugin_types.h -----------------------------------------------
#ifdef __GNUC__
#include "dbghelp\dbghelp.h" // FIXME #include "dbghelp/dbghelp.h"
#else
#include <dbghelp.h>
#endif // __GNUC__

**Comment by a554335752** [comment]
Building with MinGW-GCC 
And the other two errors i got ...
../include/x64dbg/pluginsdk/TitanEngine/TitanEngine.h:860:8: error: expected identifier or '(' before string constant
 extern "C" __declspec(dllexport) ULONG_PTR TITCALL Find(LPVOID MemoryStart, DWORD MemorySize, LPVOID SearchPattern, DWORD PatternSize, LPBYTE WildCard);
        ^
../include/x64dbg/pluginsdk/TitanEngine/TitanEngine.h:916:150: error: expected ';', ',' or ')' before '=' token
 __declspec(dllexport) bool TITCALL ImporterExportIATExW(const wchar_t* szDumpFileName, const wchar_t* szExportFileName, const wchar_t* szSectionName = L".RL!TEv2");
                                                                                                                                                      ^

What should I do? I'm just commented these two lines and it work now

**Comment by Nukem9** [comment]
We've never actually made the SDK to support other compilers. `__declspec(dllexport)` is Visual Studio only and not GCC. If you can get everything working that's great, but right now I can't do much to help (I don't know the replacements/differences).

**Comment by a554335752** [comment]
thx.. everything working fine now

//In file plugin_types.h line 11 already did something with GUNC
#ifdef __GNUC_
#include "dbghelp\dbghelp.h" // -> #include "dbghelp/dbghelp.h" GUNC use "/" will be fine
#else
#include
#endif // GNUC

**Comment by mrexodia** [comment]
Initially there was support for MinGW, but it is probably broken. Feel free to do a pull request.
