### ISSUE TITLE
Xdbg hardware breakpoint issue 

### ISSUE THREAD

**Issue by Rivinorman** [x64dbg/x64dbg#3470]
### Operating System

Window 10

### x64dbg Version

Oct 18 2024

### Describe the issue

Xdbg32 showing the following error (address not aligned to 4) when putting a hardware breakpoint on dword in memory.here is a screenshot.i am searching a strings in memory with script
![hardwaree](https://github.com/user-attachments/assets/75436068-49b0-4c60-9c92-e5de3a227b87)

### Steps to reproduce

I am searching for string in memory with script by putting hardware breakpoint on dword 

### Attachments

![hardwaree](https://github.com/user-attachments/assets/ae58a7b7-aa0a-42c3-95b3-eb201cc45f6d)

**Comment by mrexodia** [comment]
This is not an error, the CPU wouldn’t break if the address isn’t aligned. Set one on byte.

Also take a look at the name in the title bar and what you typed…

**Comment by Rivinorman** [comment]
> This is not an error, the CPU wouldn’t break if the address isn’t aligned. Set one on byte.
> 
> Also take a look at the name in the title bar and what you typed…

Bro what if I changes the length of the string.will it helpful
