### ISSUE TITLE
Issue while assembling a call instruction to run a dll function

### ISSUE THREAD

**Issue by gameplayoffert** [x64dbg/x64dbg#3482]
### Operating System

Windows 10 22H2 19045.5131

### x64dbg Version

Jul 28 2024

### Describe the issue

So, i wanted to use a function of my dll inside an other program, i injected my dll by using the "LoadLibrary" function inside the "Symbols" tab of x64dbg. After that i allocated 256 bytes of memory and i started making my code but when it's coming to the "call" instruction, it is saying "unresolved location" or "Branch displacement is too large". I tried to set the bytecode myself but i'm not really sure about how the address is encoded. It seems to be an offset but i'm not sure how you can decode it. I tried in cheat engine, i injected the dll using it and changed the function in the memory viewer in cheat engine and that worked perfectly. I'm not sure what i need to do to allow x64dbg to jump outside of the main code but atm, i'm not able to get it work. My DLL is working perfectly and the function is exported, i even tried it inside an other c++ software so it's not the problem.

### Steps to reproduce

1. Load the library using x64dbg
2. Copy the address of the function inside the dll using x64dbg
3. Go to an other module, the main one for example and replace or add the instruction "call your_address_here" and you will get "unresolved location" etc

**Comment by mrexodia** [comment]
Yeah this is a fundamental limitation of the x86_64 instruction set. The maximum displacement for a relative address is `INT_MAX`. You either have to use `mov rax, 0x1122334455667788` or do a call with a rip-relative memory displacement and the absolute address stored in memory (pseudocode, this will not compile:

```
mov rcx, dummyarg
call qword ptr: [address] ; assembles to `call qword ptr:[rip+X]`
ret

address:
dq 0x1122334455667788
```

**Comment by gameplayoffert** [comment]
Oh ok, i didn't know it was needed to use a register for that, i didn't even think about it so thank you for your help :D. I have an other question ? How the addresses are encoded ? Because it seems to be an offset but is it like the (offset - "max_int64" or "max_int32") depending on the platform ? or it is an other thing ?
