### ISSUE TITLE
Displaying Strings in x32dbg Disassembly View

### ISSUE THREAD

**Issue by HongKyoungIn** [x64dbg/x64dbg#3487]
### Feature type

Debugging

### Describe the feature

I am encountering an issue with the string display in the disassembly view of x32dbg. Specifically, I have the following situation:

The plug-in is currently using "xAnalyzer".

At address 00402A2A, there is a PUSH instruction referencing the memory address 401DDC. In the disassembly window, the argument is displayed as:
`00402A2A  PUSH 401DDC  ; Arg1 = 'mlena151'`

However, when inspecting the memory dump at address 401DDC, the correct string "I'mlena151" is stored. It seems that the disassembly window is not displaying the string accurately and omits the first character (I).

Could you please advise on how to resolve this issue? Is there a specific setting in x32dbg that controls how strings are displayed in the disassembly view? Alternatively, is this a known limitation or bug?

Thank you in advance for your assistance. I appreciate all the hard work you put into developing this fantastic tool.
![문의하기](https://github.com/user-attachments/assets/34152800-b4ba-47a0-8e8c-4e28dcff3c31)

**Comment by mrexodia** [comment]
This is a bug in xAnalyzer, you should report the issue there. Once you remove the comment the string should be detected correctly...
