### ISSUE TITLE
Check what jumped to X address

### ISSUE THREAD

**Issue by gameplayoffert** [x64dbg/x64dbg#3489]
### Feature type

Debugging

### Describe the feature

Hi, i really don't want annoy everyone that work on this project because it is awesome, however i have a question. I tried to search on Google but i wasn't able to find that so i'm not sure if that feature exist or not. If that feature exist, i'm really sorry about that.

Is there a way to see what jumped to an instruction/address ? Because you can put breakpoints and it is awesome, you can even see where a "ret" instruction will bring you, however, i didn't see the inverse of that operation. I mean, when you put a breakpoint, it will be triggered but you have no idea about where is the code that brings you here. Because it can be a call or even a jump.

**Comment by ZehMatt** [comment]
The x86-64 architecture does not keep track of branching instructions, so this is impossible, if you want to know you have to rely on tracing and see what the previous executed instruction is.

**Comment by gameplayoffert** [comment]
> The x86-64 architecture does not keep track of branching instructions, so this is impossible, if you want to know you have to rely on tracing and see what the previous executed instruction is.

Oh ok i didn't know that. By tracing, do you mean the "Trace" tab ? Because i tried to start to record but nothing is showing. I will try to search about that then and see how it works, nvm thank you a lot for your answer :D
