### ISSUE TITLE
Disassembly issue of the MOVQ instruction

### ISSUE THREAD

**Issue by Alastor27** [x64dbg/x64dbg#349]
There is a disassembly problem with the MOVQ instruction, when data moved from an XMM register to a general purpose register and vice versa.

For example:

x64dbg translates the "movq rax, xmm0" command to "movq eax, xmm0", which is invalid.

![movq_bug](https://cloud.githubusercontent.com/assets/13459642/8840664/c8dec3de-30e4-11e5-80eb-0f011f9857f3.jpg)

**Comment by Nukem9** [comment]
This will be fixed after https://github.com/x64dbg/x64dbg/issues/337 is implemented.

**Comment by mrexodia** [comment]
I checked and this issue has been resolved:

![screenshot](http://i.imgur.com/JekpM2E.png)
