### ISSUE TITLE
add support to directly open process without attaching the debugger

### ISSUE THREAD

**Issue by thewanderingtraderm** [x64dbg/x64dbg#3499]
### Feature type

Debugging

### Describe the feature

attaching the debugger could sometimes slow down processes, or sometimes the application instantly closes after the debugger is attached

**Comment by mrexodia** [comment]
```
[Engine]
DebugEngine=2
```

It's not properly supported though, kinda out of scope for a _debugger_.  The implementation is here, improvements are welcome: https://github.com/x64dbg/GleeBug/blob/vs2015/StaticEngine/Emulator.h

**Comment by flarejune** [comment]
> ```
> [Engine]
> DebugEngine=2
> ```
> 
> It's not properly supported though, kinda out of scope for a _debugger_. The implementation is here, improvements are welcome: https://github.com/x64dbg/GleeBug/blob/vs2015/StaticEngine/Emulator.h

He just wants a 'Run Process' button. like VS "Start Without Debugging".
emulator is just a joke

**Comment by mrexodia** [comment]
Either way it’s out of scope.
