### ISSUE TITLE
Change automatic dependency / build scripts

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#351]
https://github.com/x64dbg/x64dbg/commit/f4970331e9dd30479fb5b28419d69eae23851a7f
This is a continuation from the commit comments. I was just wondering how/if this _could_ change.

Right now I think one of the deterrents for anyone wanting to contribute is the initial setup difficulty. It's not obvious that you can take Qt DLLs from snapshots and drop them in (or swapping them with debug builds for that matter).
Even then, if you want to edit the gui, you need to download a 500MB installer.

An example is with [xenia](https://github.com/benvanik/xenia):
```
> git clone https://github.com/benvanik/xenia.git
> cd xenia
> xb setup
> xb build
```

Just running those 4 commands builds everything - including ~10 dependencies - and you're able to run or modify it. While it'd be nice, I don't think this is possible with the GUI part for x64dbg at least.

AFAIK all x64dbg components are separated in a similar way, but there's no easy way to find or compile them.

**Comment by mrexodia** [comment]
yea.. maybe I should write in more clear wording that you don't need to build any dependencies in order to contribute. But sure, I could also write a massive repository with submodules and custom Visual Studio files (since most dependencies use CMake or other annoying stuff to build)
