### ISSUE TITLE
Race condition when setting/removing software breakpoints which may lead to unhandled exception

### ISSUE THREAD

**Issue by fxpJustRob** [x64dbg/x64dbg#353]
When removing software breakpoints, there is a small window between the WriteProcessMemory call and the FlushInstructionCache call, where a thread might execute cached code containing breakpoint instruction, this will cause a breakpont exception which the debugger wont handle.

two ways it can be fixed:
1. Suspending all threads before modifying the code and resuming them afterwards.
2. Unregister the specific breakpoint with a delay.

**Comment by Nukem9** [comment]
I like option 2 better. WriteProcessMemory/Flush then remove it from TitanEngine's database. Suspending threads can work except it would be incredibly slow or cause synchronization problems. (Not to mention a batch insert of breakpoints, i.e 10+ at once)

**Comment by mrexodia** [comment]
I won't fix this until GleeBug is finished... Then it can be fixed
properly.

**Comment by mrexodia** [comment]
Closed as duplicate/related to #1764 I have been doing some experiments and either solution proposed here does not actually work so I'm not sure how to go about fixing this.
