### ISSUE TITLE
Follow in disassembly in code

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#354]
Context menu option to follow memory references in disassembly from the disassembly context menu

**Comment by faltur** [comment]
mrexodia, please, add the "Follow DWORD in Dump". When selecting a sequence of bytes in the dump window (eg: 4 bytes), the user may want to follow it in the dump window (very useful for looking the content of vtables). Currently it only shows the "Follow DWORD in Disassembler" option.

**Comment by mrexodia** [comment]
Yea, I already added that. Are you on the latest snapshot?

**Comment by faltur** [comment]
Yes, I'm using  the snapshot_2015-07-14_02-09, and it doesn't have the context menu inside the dump window (only in the Disasm, Registers and Stack windows). 
Look at the image.
![x64dbg-dump-context-menu](https://cloud.githubusercontent.com/assets/12991774/9240129/1b016bda-4139-11e5-91b1-3891d635259b.png)

**Comment by Nukem9** [comment]
The newest snapshot isn't updated with each commit.

Newest snapshot: July 14(?)
Feature commit date: July 23

**Comment by faltur** [comment]
Nukem9: I downloaded the latest binaries from Sourceforge. Is it possible to get the latest binaries from here without having to compile the source?

About the old Windows XP theme, I prefer using it than the one which comes with Windows 7/8,  just a matter of taste :)

**Comment by Nukem9** [comment]
It's not possible without the source. @mrexodia handles the build server (VPS afaik) and it doesn't automatically build anything.

If you really need the updated version I can compile it quickly and send it to you.

**Comment by faltur** [comment]
I would really appreciate it!

**Comment by Nukem9** [comment]
http://uppit.com/0wjh9wp3abg2/release.7z

(Took longer than expected; forgot to reinstall VS2013/Qt32/Qt64)

**Comment by faltur** [comment]
Thank you very much Nukem! I gonna test it right now.

**Comment by mrexodia** [comment]
Latest commit is always here http://jenkins.x64dbg.com/job/vs13/ws/release

The sourceforge build is not automatically triggered. I might change that in the future.

**Comment by mrexodia** [comment]
lolwtf?

**Comment by mrexodia** [comment]
should be pretty easy, basically a big copypasta from the follow in dump thing

**Comment by blaquee** [comment]
Do you mean this?
![dump](https://cloud.githubusercontent.com/assets/1324227/13309631/9d8dcb9a-db4c-11e5-9e7d-f200283a3c34.png)

**Comment by mrexodia** [comment]
No, I mean in the disassembly view it should have a follow in disassembly
like the follow in dump. Basically for following function pointers

**Comment by blaquee** [comment]
oo, ok.

**Comment by blaquee** [comment]
This should be closed now
