### ISSUE TITLE
[bug] Debugger doesn't display a fully analysed data

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#355]
Sometimes the analysed string at a certain address is not fully displayed,
here is an example:

- Reproduced after building with commit f3ad2bc
- This also happened in other parts of the debugger, for example when searching for strings

With commit f3ad2bc :
![bug](https://cloud.githubusercontent.com/assets/11916365/9021289/b6dc987e-383b-11e5-81d8-43667b50c530.png)

With (very old) build (snapshot_2014-2-20) v0.24
![done](https://cloud.githubusercontent.com/assets/11916365/9021307/311cccc6-383c-11e5-9a04-51d5e2738b49.png)

**Comment by mrexodia** [comment]
hm, very weird... I the commit you mention has absolutely nothing to do with string search as far as I can see :smile:

**Comment by wk-952** [comment]
No i didn't mean that the commit itself was the problem,
but just to give you information about the build i used, sorry for any misunderstandings
i caused.

**Comment by mrexodia** [comment]
Ah okay.. I will check it out. Can you reproduce it reliably?

**Comment by wk-952** [comment]
i'll try to find a reliable reproduction steps later today (not home right now)
but i guess it happens whenever you debug an application.

**Comment by wk-952** [comment]
You can debug x96dbg.exe
then select Search for -> String references
and you can clearly see that the strings are eaten from the end
![bg](https://cloud.githubusercontent.com/assets/11916365/9022860/773f134a-3886-11e5-9777-0360cb562441.png)

**Comment by mrexodia** [comment]
I will check the string code later on. Probably some weird mistakes again :D

**Comment by wk-952** [comment]
found it, this was introduced since commit: f041498

**Comment by mrexodia** [comment]
thanks for the input! The bug was resolved (and another one that nobody reported yet too)

**Comment by wk-952** [comment]
Thank you mrexodia
