### ISSUE TITLE
Patches created at null bytes cannot be saved (rva offset)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#356]
I'm not sure if this is how x64dbg is working or is it a bug, but please if you can
implement this feature don't hesitate.

As the title says,
1- for example find a code cave (i mean a sequence of null bytes)
2- write some code at this code cave, then press `Ctrl + P` -> Patch File -> give it a name and press save
3- 0/x patch(es) applied

This makes it impossible to make use of code caves in applications,
which is really a downside to the debugger especially in gaming field.

**Comment by mrexodia** [comment]
Usually the zeroes at the end of the section have no representation as raw
address. You need to patch at a place that has a raw address representation
in the file.

**Comment by wk-952** [comment]
sorry if i'm not getting this right but their existence in the executable file is certain,
i mean they have a consistent file offset and VA (at least in many cases),
for example in diablo2oo2's patcher you could explicitly define the file offset or the VA of the
byte and apply the required patch to it even if it's a null byte.

Could their be for example a feature/option where you could apply a patch
not by its address but relative to another one ?
so for example instead of the address of the null byte, it would be the address of the last
valid instruction + a certain offset, that way the debugger has a raw address representation
+ a user explicitly-defined offset.

**Comment by mrexodia** [comment]
Well, I just do VA to file offset conversion. If there is no result from
that conversion the patch is discarded.

Do you have a small example file that shows this behaviour?

**Comment by wk-952** [comment]
sure, the following is just nonsense but to show the issue:
1- degug x96dbg.exe, you should land at address 00802E64
2- at the next instruction @ 00802E69 (which is a jmp) assemble the following:
JMP 00803501  // 00803501 is the beginning of a null bytes sequence

3- @ 00803501 assemble the following instructions:
PUSH EAX
POP EAX
JMP 00802E6E

4- try to save the patches
5- you'll get (2/10 patches applied!)

i think this is a bug because i tried it on the first crackme from lena's tutorials
and all the patches were applied

**Comment by wk-952** [comment]
Here is the crackme (normal and patched one):
http://rghost.net/private/66ry5sN4D/836ae4b4bbe5f131e3cbbf0be52ea729
pasword: asd123

1- @ 00401078 assemble: JMP 40111A
2- @ 0040111A assemble:
PUSH EAX
POP EAX
JMP 40107D

3- save patches, this time all of them will succeed.

**Comment by wk-952** [comment]
So you mean those null bytes could have physical existence and a certain disk offset (could be viewed with HxD) but not VA or vice versa ?
If so then please feel free to close here.

**Comment by mrexodia** [comment]
yea, there might be a bug somewhere... probably the VA to offset conversion is broken :)

**Comment by wk-952** [comment]
i've sent you an e-mail (the one at your profile page) with more details on this issue, please check it out.

**Comment by mrexodia** [comment]
Yea, I got the mail will work on it later. Broke my toe yesterday :D

**Comment by wk-952** [comment]
This is going to be long, so please bear with me.

I want to give you more details because i feel that i didn't give you enough
helpful information in my last e-mail and my previous post was nearly completely useless,
also because i found another issue in the 64-bit version of the debugger which i guess is related
to the parser:

1- First, please download this simple "hello world" application (source code and debugging data are
of course included), if you want to compile it manually do a "Debug|x64" build:
http://rghost.net/private/7szD5ZRzf/f257a2f116857734a7420603bba91396
password: asd123zxc

2- Open the exe file with HxD (or any hex editor) and look at the disk offset: AB54,
you'll clearly see a sequence of null bytes. (this step is just to make sure
that they exist)

3- Start debugging the exe file and reach the null-bytes sequence @RVA: B754 (offset from image base), then assemble the following:
push rax // opcode: 50
pop rax // opcode: 58
try to save the patches and it will fail.

4- Again open the exe file with HxD and reach the disk offset AB54, then manually
type the opcodes: 50 58 and save.

5- Debug the exe file and reach the null-bytes sequence again,
this time you can clearly see the instructions:
push rax
pop rax

- This of course applies to the 32-bit version of the debugger.
- I've also included the patched exe file along with the original one

**Comment by wk-952** [comment]
... continued from above

Now to the new bug:

1- Again start debugging the exe file and reach the first line of the "main()" function,
that should be @RVA: 23E0
If that doesn't help, here are the opcodes of the "main()" if you want to search for it as a pattern:
{ 40 57 48 83 EC 20 48 8B FC B9 08 00 00 00 B8 CC CC CC CC F3 AB 48 8D 15 64 A6 00 00 48 8B 0D 1D FD 00 00 E8 06 ED FF FF 33 C0 48 83 C4 20 5F C3 }

2- Now the 7th line/instruction (@VA: 7FF699A723F5 or @RVA: 23F5) should be:
lea rdx, qword ptr ds:[7FF699A7CA60] // mov the address of "Hello World \n" to RDX
assemble the following on that line:
mov qword ptr ds:[7FF7F672CA60], 0
unfortunately what gets assembled is:
mov qword ptr ds:[7FF7F672CA64], 0 // notice the increased 4 bytes

3- So now we know that with the instruction 'mov qword ptr [address]' the address gets
increased by 4, let's assemble again but this time we'll remove 4 from the address:
mov qword ptr ds:[7FF7F672CA5C], 0
what gets assembled is:
mov qword ptr ds:[7FF7F672CA60], 0

- This also applies to other forms of 'mov xxx ptr [address]',
for example: 'mov byte ptr [address]' increases the address by 1
- This does not apply to the 32-bit version of the debugger,
it's perfectly fine at this point.

**Comment by mrexodia** [comment]
Hey, The email was very detailed already. I was just on holiday so I
couldn't respond :) but thanks for this information too. It helps
tremendously!

**Comment by Nukem9** [comment]
The instruction assembling is another XEDParse bug, probably something to do with RIP-relativeness again.

**Comment by wk-952** [comment]
More info regarding this,
with the new implementation of `File-offset <---> VA` conversion, It seems that the debugger
could correctly convert the disk-offset of those null bytes to its corresponding VA and
properly follow that VA in the CPU/disassem. window using `Ctrl + Shift + G` (yaaay!)
but obviously not the opposite :( .

Pic:
![err](https://cloud.githubusercontent.com/assets/11916365/12008272/18f73728-ac39-11e5-9a23-f186157eb104.png)

- Notice how the conversion failed in the details window
(so i guess the conversion in the details window is VA --> file-offset ?)

**Comment by mrexodia** [comment]
Yea I noticed some issues with this as well. Probably this will be fixed
when TitanEngine is replaced by GleeBug :)

**Comment by mrexodia** [comment]
should be fixed in a few hours when the new TitanEngine rolls out

**Comment by wk-952** [comment]
I couldn't build TitanEngine on Visual Studio 2013 to try it out,
if you have any free time, could you please release a build of it with the new fix ?
i'm very passionate to try it out.

**Comment by mrexodia** [comment]
A new build should be released already. I will issue a rebuild.

**Comment by wk-952** [comment]
Working perfectly in x32 and x64.
Thank you so much for all your work.
