### ISSUE TITLE
[Plugin API] Adding shortcuts and access to the last used window

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#357]
First of all, THANK YOU.  I'm making the switch to x64dbg after years of using Olly.  It's been a huge joy to switch so painlessly.  

I've written a plugin to automatically handle the following "Follow in dump" feature, but it should be a native shortcut.

Requests:
1. Please add a hotkey to allow me to "Follow DWORD in dump" from the stack window/dump/disasm
2. Please add a plugin function that would allow me to check the focus window so I can add additional logic to my hotkey checker code to operate differently based on which window had focus last GUI_DUMP, GUI_STACK, etc.  (Here's pertaining other requests that you've responded to: https://github.com/x64dbg/x64dbg/issues/195)
3. Lastly, please add a MENU to the registers window in the PLUG_SETUPSTRUCT, why is it missing?  Olly didn't have it either so I'm assuming this might not be that simple?

Thanks for everything guys/gals.

**Comment by mrexodia** [comment]
Hey,

Thanks for reporting :) I do wonder what kind of 'Follow in dump' function
you want to make. As far as I know I added everything.

Custom hotkeys is on the issue list.
Focus is only on my internal list (so thanks for reporting)
Register menu could be added, but you cannot interact with the selection of
the registers so it seemed pointless at the time. What do you want to do
with it?

Greetings

**Comment by MoonDoggie42** [comment]
mrexodia, 
Thanks for responding.  

I wrote a plugin that has two functions:
1. Gets RTTI information for a selection of dwords in the dump/stack/ or in a register

I'm sure you're familiar, but I consulted this for how to get the RTTI object name: http://blog.quarkslab.com/visual-c-rtti-inspection.html

![rtti](https://cloud.githubusercontent.com/assets/13701799/9153147/693677ec-3dfa-11e5-9a2e-5e4a895658b7.jpg)

This is super handy if an exe has been compiled with RTTI, the plugin will spit out all the RTTI information of the class name in the log and autolabel the addresses as well if you want it to.  Although, there's a small problem with it as seen at [ebp] (The address referenced by the CompleteObjectLocator is not in the data segment).

Followup question: How can I check if an address is in a specific segment?  :)

2. The plugin makes available a hotkey press to automate the action "Follow in Dump".  I'm constantly following dwords in the dump to see if they're ptrs to objects I'm looking for.  (I do this maybe 200 times a session).  Right-clicking the stack and selecting my plugin's hMenu then doing "Follow in Dump" is tiresome which is why I want the last active "Focus window" so I can GuiGetSelection() on the correct window to know what I clicked on, currently without a separate hotkey for the dump, this is impossible.

Also, Olly's plugin interface included a shortcut key exposed function that made it really easy to register hotkeys with olly plugins.  I'm using CBWINEVENTGLOBAL to do all of my GetAsyncKeyState's for my hotkeys, is there a better way?  

Thanks for reading.  Cheers!

**Comment by codecat** [comment]
@MoonDoggie42 Do you have this rtti plugin available somewhere?

**Comment by MoonDoggie42** [comment]
Yes @codecat if you email me I'll send them to you.  Eventually when I clean up the code I'll post it publicly.  Colin dot Senner @ g mail dot com

**Comment by mrexodia** [comment]
Hm @MoonDoggie42 I see I never actually answered your question...

You can use Script::Module functions to get the section associated section from an address 😄

**Comment by MoonDoggie42** [comment]
Thanks @mrexodia you're awesome.

**Comment by mrexodia** [comment]
@MoonDoggie42 I recently added an api for plugin hotkeys, what are you missing before you can release your plugin?

**Comment by MoonDoggie42** [comment]
@mrexodia Hey Exodia, I see I completely missed your message from over a year ago.  Jesus.  

What I was writing at this time was a plugin so I could select a dword in dump and press CTRL+G to do "Follow dword in dump", it's clearly functionality we do a lot and I wanted just to hotkey it.  

I ended up accomplishing this with a CBGLOBALWINEVENT (I believe this is what it was) so I could detect the hotkey.

Is the api plugin-hotkey example documented?  I'll grab the latest plugin full sdk and take a look.  

I'll cleanup the RTTI code (which is messy as hell because of the need to use DbgMemRead (or a function named similarly) and have to read fields and pointers off explicitly rather than just casting it as something like a 
RTTI_t* pRtti;

I couldn't find another way around it, just reading single values using DbgMemRead() and putting it in a struct manually (really ugly looking code).

If you're still on telegram, I'll drop by there for clarity on these things.

Thanks a ton,
Moon

**Comment by ShRyDeR** [comment]
Hello! I wonder if you ever got the chance to clean up the code and upload it?

**Comment by colinsenner** [comment]
I've uploaded it and linked it here on the plugins site:
https://github.com/x64dbg/x64dbg/wiki/Plugins

Please let me know if you find any issues or feel free to do a merge
request with any changes.  It's not perfect or anything, but it does what I
need it to do. Always open to suggestions :).

Colin
www.colinsenner.com

**Comment by mrexodia** [comment]
Very nice, thanks!
