### ISSUE TITLE
[Feature Request] "Search for text" in the "String References" window

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#358]
Currently we have to copy out the entire table of string references and paste it in Sublime Text or notepad to do a simple "Find" operation.  It'd be great if this was added.

**Comment by Nukem9** [comment]
See the bottom. (Unless if you are using an old version...?)
![image](https://cloud.githubusercontent.com/assets/4228359/9153262/83b5c4aa-3e19-11e5-9bb0-2fdc2521df5a.png)

**Comment by MoonDoggie42** [comment]
Nope, I'm blind.  Thank you.

**Comment by Nukem9** [comment]
@mrexodia Since this is the 3rd(?) issue about this, even though it exists at the bottom, do you have any idea to make it more obvious?

**Comment by mrexodia** [comment]
Yea.. Many people had issues with this before. One option would be to add
it to the faq. Or add a "Find" menu option and then simply give a message
box :D

**Comment by MoonDoggie42** [comment]
A right click in the references "Search for Text", and a tooltip popup next
to the "Search" dialog at the bottom might be more elegant.


On Sun, Aug 9, 2015 at 4:18 AM, Duncan Ogilvie <notifications@github.com>
wrote:

> Yea.. Many people had issues with this before. One option would be to add
> it to the faq. Or add a "Find" menu option and then simply give a message
> box :D
>
> On Sun, 9 Aug 2015 06:31 Nukem <notifications@github.com> wrote:
>
> > @mrexodia <https://github.com/mrexodia> Since this is the 3rd(?) issue
> > about this, even though it exists at the bottom, do you have any idea to
> > make it more obvious?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/x64dbg/x64dbg/issues/358#issuecomment-129106831>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/358#issuecomment-129167721>.
>



-- 
-Colin

**Comment by ThomasThelen** [comment]
I was actually about to request this feature but I fond this. Knowing this earlier would have saved me hours and about two points on my vision!
Since most people end up not reading the FAQ, I would just run a check if the user is in the strings window -> add search for text to the right click menu.

**Comment by Nukem9** [comment]
QLineEdit::setPlaceholderText might be useful. Although it will just show faded gray "Type here to filter results..." text in the background (similar to what you find on some login pages).

**Comment by dnutiu** [comment]
But how can you search and edit strings in the .data section?

**Comment by mrexodia** [comment]
You cannot @dnutiu
