### ISSUE TITLE
Mistake in links to plugins on your website

### ISSUE THREAD

**Issue by encoree1337** [x64dbg/x64dbg#359]
http://x64dbg.com/#plugins

look at ollydumpex, link is pointing to: http://low-priority.appspot.com/ollymigrate/OllyMigrate.zip
and link from ollymigrate is pointing to http://low-priority.appspot.com/ollydumpex/OllyDumpEx.zip

**Comment by mrexodia** [comment]
Oh, thanks! If you have time for a pullreq please do. Otherwise I'll do it
when I get home.

**Comment by Nukem9** [comment]
https://github.com/x64dbg/x64dbg.github.io/commit/f706e41d422a71e8266ae7eeb00a3a1fb7a7b61e

Technically the issue doesn't apply to this repo. Closed anyway.
