### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#361]
Random idea: Add another tab that is purely a notepad replacement for debugging. Also saved with the database obviously.

**Comment by MoonDoggie42** [comment]
+1


On Tue, Aug 11, 2015 at 11:00 PM, Nukem <notifications@github.com> wrote:

> Random idea: Add another tab that is purely a notepad replacement for
> debugging. Also saved with the database obviously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/361>.
>



-- 
-Colin

**Comment by ThomasThelen** [comment]
Agreed. I am constantly writing notes on paper and in notepad.

**Comment by mrexodia** [comment]
So I have an idea for this. I add multiple notepads:

- A superglobal notepad (saved in x64dbg.ini and x32dbg.ini, so you
actually have one notepad per architecture)
- A debuggee notpad (saved in the debug database)
- A notepad for each module in the debuggee (also saved in the database)

Does this sound good, or is it overkill?



Op do 13 aug. 2015 om 03:56 schreef Thomas Thelen <notifications@github.com

**Comment by MoonDoggie42** [comment]
That sounds great to me.  As long as it's easy to get to the right one.  If there's a "default" notepad to get to via a hotkey my vote is for it going to the debugee.  Just my two cents.

-Colin
