### ISSUE TITLE
PE module in yara script

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#362]
Entrypoint checks dont work even if i import PE module example:
import "pe"

rule borland_delphi {
	meta:
		author = "_pusher_"
		description = "Borland Delphi 6.0 - 7.0 / 2005 - 2007"
		date = "2015-08"
		version = "0.1"
	strings:
		$c0 = { 53 8B D8 33 C0 A3 ?? ?? ?? ?? 6A ?? E8 ?? ?? ?? FF A3 ?? ?? ?? ?? A1 ?? ?? ?? ?? A3 ?? ?? ?? ?? 33 C0 A3 ?? ?? ?? ?? 33 C0 A3 ?? ?? ?? ?? E8 }
	condition:
		$c0 at pe.entry_point
}

this doest work and i think you said you dont load the modules..
hopefully you know what todo :)

**Comment by mrexodia** [comment]
the reason this does not work is that Yara didn't expect the PE file to be mapped. A solution for this would be to allow the user to scan the file instead of the memory regions.
