### ISSUE TITLE
Bug with Goto in Dump?

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#364]
Not sure if this is specifically related to goto behavior only in dump as I'm at work at the moment and can't check but it's easy to reproduce.

1. In the dump label a byte/dword etc "ab".
2. scroll up in the dump
3. in the dump press ctrl+g type "ab".  (Correct expression appears)
4. hit enter (goes correctly to the labeled byte)
5. scroll up in the dump
6. press ctrl+g ("ab" is already there, "correct expression appears", but the "go" or "ok" button is not enabled), thus you cannot press [enter] to go back to "ab", you have to erase 'b' and re-add it to get the button enabled.

**Comment by faltur** [comment]
This problem also occurs inside Disasm window when using copy-paste sometimes. I was able to simulate this bug in the following way:
1-open your target and choose an address (can be any addr)
2-open the "Go to expression" window (CTRL+G), enter the address into it, and then OK (the first time it will work fine)
3-now copy the address to the clipboard, select other addr in the Disam window (just for testing the Go to expression function), press CTRL+G, and paste the addr using either the CTRL+V keys or the mouse right-click. This time the OK button will become disabled.

**Comment by MoonDoggie42** [comment]
Mrexodia and team, you guys are awesome, keep that shit up.
