### ISSUE TITLE
Weird freeze under Windows XP when pressing several time on Ctrl+F2

### ISSUE THREAD

**Issue by dummys** [x64dbg/x64dbg#365]
Hi,

The crash log, dump and screen of the stack trace of the thread is available here:
https://anonfiles.com/file/2d747ccecb09f4b8f5f32e53869fa729

The os is Windows XP SP3 eng, the version of the debugger is the latest build get on jenkins and the cpu is hanging at 100%.

**Comment by Nukem9** [comment]
Nothing in the dump helps to determine the reason. My best guess is an integer overflow around `x32dbg_e60000!_patchinrange` looping forever (running on the GUI thread).

**Comment by ApertureSecurity** [comment]
I am surprised to see we're supporting XP.

**Comment by mrexodia** [comment]
Well, my initial thoughts were to not support it, but if the freeze happens
on XP, it could also happen on higher versions of Windows.

**Comment by EpicJhon** [comment]
the problem persists.

The os is Windows XP SP3 esp.

The problem occurs when the screen resolution is large (2560x1080) , when I put the program to a resolution of 1024x768 there is no problem.

**Comment by Nukem9** [comment]
I have a feeling the problems are similar but the reasons behind it are different. Are you quickly pressing/spamming `Ctrl+F2`?

**Comment by mrexodia** [comment]
Notice that XP is unsupported.

**Comment by mrexodia** [comment]
https://mega.nz/#!D9hmjYBD!lIQUQe54bd1S5u-ACGE8ih6g8Wfwp_SZ3_c54ETUjvE

**Comment by mrexodia** [comment]
I'm assuming this is fixed. Please tell me when it's still an issue.
