### ISSUE TITLE
Save column widths

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#368]
A feature that would be nice is x64 remembering the widths of my columns so I can see my labels easily in the the disasm and dump.

**Comment by MoonDoggie42** [comment]
Thanks for referencing this.  How do I add a bounty?

**Comment by mrexodia** [comment]
https://www.bountysource.com/issues/25785690-save-column-widths i think you can do it from there

**Comment by MoonDoggie42** [comment]
Great, got a team member and I bounty-ing this bug.  Thanks mrexodia.

**Comment by mrexodia** [comment]
Should be fixed now, the bounty is for @torusrxxx
