### ISSUE TITLE
All addresses relative to another one but from different section

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#370]
Currently this is already implemented (by double clicking the addresses column),
but once you switch to another section other than the one you're currently at in the
"Memory Map" tab (for example switching to ".text" section) the relativity is lost
and you're back to normal VA.

It would be helpful with applications whose image base address is not consistent/static
so their RVA is more helpful than their VA.

A small suggestion, for example when you right click on an address in the addresses
column a small drop down menu appears, like this:
![asd](https://cloud.githubusercontent.com/assets/11916365/9290249/a28869a6-438b-11e5-86f9-60959f41a59a.png)

I have to admit this feature is kind of useless, you could simply open the calculator
and type "your address - IMbase" and you'll get the RVA, but you know, just for laziness.

Feel free to close here immediately if you want :D

**Comment by mrexodia** [comment]
you could also look at the infobox for the rva of the currently-selected address :+1: 

but i will look into this.

**Comment by wk-952** [comment]
The menu item `Copy -> RVA`, along with displaying the `RVA` in the info box (can be copied also from there) are more than enough.
![untitled](https://cloud.githubusercontent.com/assets/11916365/18624961/9d6fb7ca-7e4b-11e6-879d-2ffe09acfbd8.png)

Thanks.
