### ISSUE TITLE
Minidumps, second debugging of the same file

### ISSUE THREAD

**Issue by TheAifam5** [x64dbg/x64dbg#374]
So, 
the first why x96dbg making sooo many files in minidump every debugging ?
the second, i can only debugging on first attach, second debugging using the same file dont works, like my application returning 0xC0000135, but before that worked.
Also after restart dont works.

When I delete file from "db" folder, again works.

Also breakpoints dont works. I breakpointed "DefWindowProcA" and "DefWindowProcW".. In OllyDBG works. And when i restart process, again the same, the same return value "0xC0000135".

Version: snapshot_2015-08-16_12-45.7z
Here minidumps: http://speedy.sh/keDUr/minidump.rar

Time to back to OllyDBG and wait for release(not alpha) of x96dbg :(

**Comment by mrexodia** [comment]
Sorry to hear about your issue, but could you please provide the software you tried to breakpoint `DefWindowProcA` and `DefWindowProcW` on? I tried the latest master and it appears to be working fine:

![breakpoint](http://i.imgur.com/Ut8L8HF.png)

In OllyDbg, do you use any plugins (like anti-anti-debug)? Do you use Olly1 or Olly2? And what version of Windows are you on?

To answer your question about the minidump: I have no idea, possibly there are some exceptions saved that should be ignored.

**Comment by Nukem9** [comment]
The minidumps look like the result of a new exception status being used in OutputDebugStringW -> 0x4001000A (Windows 10, no results on google). I'll add it to the ignored exceptions for the minidump.

**Comment by TheAifam5** [comment]
Yea i'm using Windows 10 x64.
No i dont using any plugins like anti-anti-gebug in OllyDBG..

So, i wait for patch :) if is only with that problem.

**Comment by mrexodia** [comment]
And what is the program you try to breakpoint? Without this information
there is not much we can do really.

**Comment by TheAifam5** [comment]
And what about "db" folder. So i show you where is problem:
First debugging that file: http://prntscr.com/86ddt3
Breakpointed DefWindowProcA and DefWindowProcW: http://prntscr.com/86de6u http://prntscr.com/86degu
Application works but breakpoints not: http://prntscr.com/86det4
Then i close the application and try to run again my program: http://prntscr.com/86df8d
Program made database: http://prntscr.com/86dfkc
So, don't work. But after database file from "C:\Program Files\x96dbg\x32\db\TestEnvironment.exe.dd32" and clicked "Restart"...
http://prntscr.com/86dgch
WORKS AGAIN 

So that must be enough for check :) if you need more info just ask :)

**Comment by mrexodia** [comment]
Could you also please post the source of TestEnvironment.exe? Obviously we
will check it, but we ask as much information as possible to minimize the
risk of chasing bugs that don't exist.

Could you also try if breakpoints on other places (for example in the
executable image) work normally?

Thanks

**Comment by TheAifam5** [comment]
About breakpoints in other places.. Yes works:
http://prntscr.com/86dj69


Lastest source: https://github.com/TheAifam5/Test-Environment

**Comment by TheAifam5** [comment]
Minidump: http://speedy.sh/N2tKB/dump-20082015-1857170966.rar

Breakpoints still don't works, also restart app don't works.
About restart see here: https://github.com/x64dbg/x64dbg/issues/374#issuecomment-132522777
(After remove db, restart works)

And also i seen some problems with x64 version...

**Comment by TheAifam5** [comment]
REFRESH
(snapshot_2015-10-20_01-56)
Still not fixed on Windows 10.
Dump x64: http://speedy.sh/HkQ6A/dump-27102015-1601330068.rar

**Comment by Nukem9** [comment]
@TheAifam5 This isn't going to be fixed until my branch is merged or it is fixed in master.

**Comment by mrexodia** [comment]
assuming this was fixed since Nukems branch was merged in development.
