### ISSUE TITLE
Patched file is missing

### ISSUE THREAD

**Issue by hitman00009** [x64dbg/x64dbg#375]
Hello, I am using x64dbg on Windows 7. I am able to create patches and patch file using the patches window. However, patched files are not shown in Windows Explorer. I think there is a problem with used file operations. 

The patched file name is shown if i try to patch second time; but i can not access file using Windows Explorer
![missingfilebug](https://cloud.githubusercontent.com/assets/13847770/9325549/d5afe95a-459b-11e5-8265-baf099519b3d.png)

**Comment by mrexodia** [comment]
How did you save the file? Notice that you need to type the extension manually.

**Comment by hitman00009** [comment]
Ok, i found out the problem. The folder was read only. "Patch file" button somehow created the file in the read-only folder without any error. When i removed read-only attribute from the folder, i can now see and access those missing files. 

Also, i found out that read-only files can not be drag/dropped to x64dbg. I don't know if this is intended or not. But an error message indicating "file is read only" would be nice

**Comment by mrexodia** [comment]
there now is an error when you try to do this.
