### ISSUE TITLE
Debugging second time with changes

### ISSUE THREAD

**Issue by hitman00009** [x64dbg/x64dbg#376]
After changing some opcodes, the user might need to restart debugging and obverve the effect of changes a few times. But, all changes in opcodes (patches) are removed, if debugging is restarted. 
Removal of changes is problematic since the user might accidentally press continue/step forward etc. 

I dont know if there is an easy way to preserve changes. If not, I present this as an improvement.

**Comment by mrexodia** [comment]
The current way to go would be to export the patches and import them on
start of the program. Keeping the issue open, maybe we can add a 'Preserve
Patches' option.

**Comment by mrexodia** [comment]
same as #542
