### ISSUE TITLE
Code graphing

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#378]
Was already worked on, but there is no issue yet :dancer:

**Comment by hitman00009** [comment]
That would be a wonderful feature. Especially debugging on graph and taking/not taking jumps are so helpful.

**Comment by tr4ceflow** [comment]
There was already code in an extra branch. To my best knowledge, I will have again time to pursue this issue and update old code. Is there a backup?

**Comment by mrexodia** [comment]
Hey,

The code for doing the control flow graph as a structure has been rewritten
and is available with the cfanalyze command. The current thing to do is
fully implement it with OGDF (I will push this code).

**Comment by Nukem9** [comment]
@tr4ceflow just for reference, the old code is still in the 2 separate branches:

https://github.com/x64dbg/x64dbg/tree/flowgraph
https://github.com/x64dbg/x64dbg/tree/basic_analysis

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/blob/Nukem9-master/src/dbg/controlflowanalysis.cpp this code creates some sort of tree in the form of basic blocks i will make some more comments later
