### ISSUE TITLE
"Search for references" not returning any results

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#379]
I have a selection in the dump window of the VFTable for a class.  I hit Ctrl+R to find references to that vftable and nothing comes up as found.  

Olly correctly returns 2 references to that VFTable.  Am I doing something wrong?  I've tried selecting just the first byte, the first dword, etc.

**Comment by Nukem9** [comment]
*Assuming this is how the search is supposed to work: It only scans the entire range of a PE section. I.e if you are in .rdata it will only scan .rdata (or .text, .data, ....)

You can see the separated PE sections in the memory map view. They would need to be merged in the search function (I don't know what mrexodia will want to do)

**Comment by wk-952** [comment]
There is also a similar behavior in the pattern search window (actually in every "Search for" -> <option>), it's only looking in the currently selected section.
If this issue here is solved I assume this behavior will be fixed in all parts of the debugger, right ?
or is this totally different and I should create a new issue with it ?

**Comment by mrexodia** [comment]
It's the designed behaviour, but I can make an option (like olly) to search
in multiple sections.

Basically what you need to do is select the section you want to search in
in the disassembly window and then you can search for references you select
in the dump window.

**Comment by wk-952** [comment]
Yes! please, if you can make such an option that would allow searching in multiple (or better all)
sections, that would be a very great enhancement to the debugger.

If possible, could this be also implemented in all options of the "Search for" and
"Find references to" menus ?
Please don't hesitate to implement this option, i really encourage you to do it.

**Comment by MoonDoggie42** [comment]
Totally agreed.  Once results are found for references it could be labeled what code section they're in, however, there's no reason to not search all sections.  IDA even returns results in all sections or at least displays them iirc.  

Thank you thank you.

**Comment by mrexodia** [comment]
Searching all memory sections takes a lot of time. However, I can implement
searching in all sections of the currently selected module in the
disassembly. I don't like the behaviour where the search is done always in
the module section.

**Comment by MoonDoggie42** [comment]
Ah yes completely.  Just searching all sections of the module I'm currently
in is what I intended to say.  My apologies.

On Thu, Aug 20, 2015 at 12:38 PM, Duncan Ogilvie <notifications@github.com>
wrote:

> Searching all memory sections takes a lot of time. However, I can implement
> searching in all sections of the currently selected module in the
> disassembly. I don't like the behaviour where the search is done always in
> the module section.
>
> On Thu, 20 Aug 2015 21:32 MoonDoggie42 <notifications@github.com> wrote:
>
> > Totally agreed. Once results are found for references it could be labeled
> > what code section they're in, however, there's no reason to not search
> all
> > sections. IDA even returns results in all sections or at least displays
> > them iirc.
> >
> > Thank you thank you.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/x64dbg/x64dbg/issues/379#issuecomment-133143055>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/379#issuecomment-133147360>.
>



-- 
-Colin

**Comment by wk-952** [comment]
@mrexodia since now you have the ability to search for anything in the current region (PE section), the whole module or even all modules, could you please implement searching in the whole module for references too?

It's currently the only option that supports searching in the current region only. Thanks in advance.

**Comment by mrexodia** [comment]
Sure but I have no idea how this searching in multiple regions works ;) I
will check it though.

**Comment by mrexodia** [comment]
Needs more menu options.

**Comment by mrexodia** [comment]
I think this has been implemented.
