### ISSUE TITLE
Option to disable analysis of windows modules etc

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#381]
x64dbg's load time is much longer than Olly's (I'm sure you're sick of comparisons to Olly by now?).  I suspect this is because of analysis on windows modules (which I have turned off in Olly).  Any chance we can get analysis off unless we specifically ask x64 to analyze the current module?

Thanks!

**Comment by Nukem9** [comment]
x64dbg doesn't do automatic analysis yet. Symbols are probably being downloaded or used in the background. Try disabling symbols, then check the load time.

**Comment by MoonDoggie42** [comment]
Ok, I assume you mean to turn off "Undecorate symbol names" which now I've
done and it seems to have sped it up a bit.  Thanks for the reply nukem.

On Wed, Aug 19, 2015 at 7:33 PM, Nukem <notifications@github.com> wrote:

> x64dbg doesn't do automatic analysis yet. Symbols are probably being
> downloaded or used in the background. Try disabling symbols, then check the
> load time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/381#issuecomment-132859134>.
>



-- 
-Colin

**Comment by mrexodia** [comment]
Dbghelp is notoriously slow unfortunately. You can 'fix' this by setting
the symbol path to nothing or by deleting the symbol files of large system
libraries.

**Comment by mrexodia** [comment]
has this been fixed since?
