### ISSUE TITLE
trailing spaces in follow expression window

### ISSUE THREAD

**Issue by joseph-giron** [x64dbg/x64dbg#383]
IDA, Immunity, and ollydbg don't care about trailing spaces in their expression follow window, but x64dbg does. 

Make it so x64dbg doesn't complain about trailing spaces in the window. 

See pic http://i.snag.gy/P4cgA.jpg

**Comment by mrexodia** [comment]
weird actually, I thought I ignored spaces :) will fix it.

**Comment by wk-952** [comment]
It does ignore spaces, see the leading spaces and the cursor at the end of the expression in those pics:
![aa](https://cloud.githubusercontent.com/assets/11916365/9542512/b1eaa28e-4d71-11e5-8797-a3c0efa6017a.png)
![asd](https://cloud.githubusercontent.com/assets/11916365/9542594/72ebe98e-4d72-11e5-86bf-a253a8e104f0.png)

every expression parser in the debugger ignores spaces perfectly fine nearly everywhere.

**Comment by mrexodia** [comment]
Right, maybe Joseph isn't using the latest snapshot...

**Comment by Nukem9** [comment]
Invalid. User didn't have newest version.
