### ISSUE TITLE
Can't skip exception (C0000005)

### ISSUE THREAD

**Issue by cobrce** [x64dbg/x64dbg#384]
Hi,
I have ignored exceptions range from 0000000 to FFFFFFFF but can't skip C0000005 (EXCEPTION_ACCESS_VIOLATION)
version : v25, Aug 20 2015
target : themida /.net / x64
(I'm using scyllahide)

**Comment by mrexodia** [comment]
If the program crashed there is no way to skip an exception.

**Comment by cobrce** [comment]
in normal execution (without debugger) it doesn't crash, is it a way to say debugger found?

**Comment by mrexodia** [comment]
Could very well be. If you say it's themida the chances are it is the case.

**Comment by mrexodia** [comment]
No response, so considering this solved. Feel free to reopen if the issue is from x64dbg.

**Comment by CrcakOnDemand** [comment]
to solve the problem
untick NTQueryInformationprocess in scyllahide settings

**Comment by ScyllaHide** [comment]
if the target is not protected/packed with anything and you get the Access violation @ C0000005, the best way is to turn everything in ScyllaHide off and then try again, for me it worked fine.

**Comment by Setaran** [comment]
@CrcakOnDemand Hello,
Where is Skycllahide's settings?
I only see a Skyccal button on top bar.
Thanks.

**Comment by lich0821** [comment]
> @CrcakOnDemand Hello, Where is Skycllahide's settings? I only see a Skyccal button on top bar. Thanks.

`Plugin`->`ScyllaHide`->`Options`
