### ISSUE TITLE
x64dbg crash when clicking my pc

### ISSUE THREAD

**Issue by techbliss** [x64dbg/x64dbg#385]
If i open file, and click "my PC", it makes x64dbg crash and produce a mini dump.
clicking c drive work, so only clicking my pc make the crash.

regards.

**Comment by mrfearless** [comment]
Could be a shell extension issue, maybe one takes longer than normal to load up, causing a hang in the explorer part, which in turn causes x64dbg to freak out. Could be worth checking out what extensions are installed with ShellExView: http://www.nirsoft.net/utils/shexview.html - i recall having a problem with a mkv shell extension years ago that caused explorer to hang/crash regardless of file i clicked on. Once i disabled it, all worked fine. Maybe load ShellExView up, disable a few, see if that helps, try an few more disabled then try again etc etc. Only other thing it might be is low disk space.

**Comment by techbliss** [comment]
I tried disabled all shell exensions in my pc category.
It does seems to hang before crashing, but turning them of dosent help.
It could be that it have something todo with storage.
Here is the crashdump analyze http://pastebin.com/ie87t4wx

then in ShellEXViev there is actuelly Microsoft WinRT Storage-API extension that is somehow the problem described in the crash dump.
but turning those of dos not seems to have a affect either.
Could this be one of those wierd windows 10 bugs.
