### ISSUE TITLE
Some patches for Windows 10?

### ISSUE THREAD

**Issue by TheAifam5** [x64dbg/x64dbg#386]
Hi,
I want to ask, when you want add some patches for Windows 10? 
Because on W10 x64dbg don't works.

Regards TheAifam5

**Comment by Nukem9** [comment]
What do you mean by "it doesn't work"

**Comment by MoonDoggie42** [comment]
Works fine for me on win10 64bit

-Colin

**Comment by TheAifam5** [comment]
yea?
I have W10, fresh install .. for me, for example breakpoints in DefWindowProcA and DefWindowProcW don't works in other applications.
when I debugging x86dbg, all works perfectly but in others apps not.

**Comment by mrexodia** [comment]
Isn't this the same issue as before (#374)? Making more issues doesn't solve problems quicker...

What I'm trying to say is: we work in our free time. Donations help, but do not cover even a day of working on x64dbg this is why it might seem we do not *want* to help you. In reality we just have things to attend to in our real lives.

Thank you for your understanding.
