### ISSUE TITLE
Win10 Improvement: Use WaitForDebugEventEx instead of WaitForDebugEvent

### ISSUE THREAD

**Issue by NtQuery** [x64dbg/x64dbg#388]
WaitForDebugEventEx

https://msdn.microsoft.com/en-us/library/windows/desktop/mt171594(v=vs.85).aspx

**Comment by Nukem9** [comment]
Probably better if this issue is closed and moved to GleeBug. x64dbg itself doesn't handle raw debug events.

**Comment by mrexodia** [comment]
Yup
