### ISSUE TITLE
issue when unpacking (possibly invalid)

### ISSUE THREAD

**Issue by frustreated** [x64dbg/x64dbg#390]
when i am unpacking a program, i found a slightly difference between Ollydbg and x64 dbg, Ollydbg can unpack it correctly ,and x64 go the same address but a different code displaying for us.
i will post a little movie to youtube , I dont konw why, 3q for your reading, the address of youtube movie will be posted later

https://www.youtube.com/watch?v=e0fTXmgxnxQ&feature=youtu.be
and files can be downloaded here
链接：http://pan.baidu.com/s/1c08qSHq
密码：hlxx
be care :
files in rar can be executed！

问题已经得到解决，谢谢楼下
(this Problem is solved！！ another is up ,and when all is solved , I will delete all. 3Q!)
a554335752!

**Comment by a554335752** [comment]
醉了... 这个问题都来了
这小东西有反调试 你OD开了反反调试插件出来结果当然不一样了
![3](https://cloud.githubusercontent.com/assets/3873164/9728971/6ffb3e26-563e-11e5-945d-3b2c0c9f7e5f.png)
还有百度网盘他们也访问不了吧.

**Comment by frustreated** [comment]
谢谢啊，不好意思，我对脱壳也是刚开始学。见谅~

**Comment by frustreated** [comment]
好容易碰到大牛，还有一个x64软件疑问，冒昧多问两句哦

对esp单击右键，数据窗口中跟随时
如果数据窗口中为地址显示，能够准确的跟到相应的数据，并且第一位显示

如果数据窗口中为asii显示，第一位不是要显示的数据，但是软件的焦点已经定位到要显示的数据了

谢谢您的阅读！
因为过分追求完美，也特别希望x64dbg能完美，所以只有有问题就没保留的问问了。望见谅~~

**Comment by a554335752** [comment]
刚试了一下 我用的版本好像没有你说的这个问题
你用的什么版本?

**Comment by frustreated** [comment]
难道我又犯低级错误了？
我做个短视频，留一个下载地址可以么？
谢谢了啊！我现在就开始做！

**Comment by a554335752** [comment]
@frustreated 确实有问题,

**Comment by frustreated** [comment]
链接：http://pan.baidu.com/s/1sjJvR2X 密码：nzr1
特别感谢啊，我平时没个一起讨论的~
翻很多东西，自己查来查去……
希望x64dbg能更强大！不知道您是不是这个项目的贡献者。
里面我想还有个功能是不是可以加上，当使用二次内存镜像法脱壳的时候，x64dbg对程序较低地址部分，我没找到对程序区段的显示，其他高地址都有。
我进一步确定下，如果同僚一起研究的话。

**Comment by a554335752** [comment]
我和你一样就偶尔来报个BUG. :D

**Comment by mrexodia** [comment]
If you guys solved the issue, please close it :+1:

**Comment by frustreated** [comment]
@mrexodia 
@a554335752 and i have make sure that the follow in dump function has a little flaw、

mouse point to esp or ebp , then right button , fullow data in dump
if the displaying mode is address , then the right position can displayed correctly 
but when we change the mode to asii or unicode mode , the current position (focus) has been set to the right position ,but is was not displayed rightly.
if any description is not clearly , just post questions~

**Comment by a554335752** [comment]
那两个下载不了 27%都不动了
不同的问题最好还是新建一个 issues, 这样比较清晰
要不他们看到上面的中文都不敢往下看

**Comment by mrexodia** [comment]
It looks like you're not using the latest version of x64dbg. You might want to update to the latest snapshot: http://jenkins.x64dbg.com/job/vs13/ws/release

As far as I can tell this is some anti-debug trick or something.

**Comment by a554335752** [comment]
My English is too bad - -!
![41](https://cloud.githubusercontent.com/assets/3873164/9899705/46c9cb20-5c8e-11e5-999b-d84ec47941b2.png)
![6](https://cloud.githubusercontent.com/assets/3873164/9899709/4ee588b2-5c8e-11e5-924c-7a477d4b1180.png)

**Comment by frustreated** [comment]
you are so amazing,that is what i wanna to describe!!
and you can give another publish or small talk to show to the official website~~
@a554335752

**Comment by frustreated** [comment]
@mrexodia ，
 Yes  ，researcher @a554335752 told me this too. and we fond another flaw described by @a554335752 ，lots of thanks for your url of the newest vertion ,and i am going to have a look to be sure whether the flow described by @a554335752 has corrected~
i love x64 dbg~ and thanks for your answers~

**Comment by a554335752** [comment]
@frustreated 没找到私聊在哪里.. blog-xiaoe.rhcloud.com
