### ISSUE TITLE
Move off Sourceforge

### ISSUE THREAD

**Issue by golergka** [x64dbg/x64dbg#391]
Sourceforge has recently started to bundle malware with downloads.
See this site: http://helb.github.io/goodbye-sourceforge/

Github seems like a good and logical place to put binary releases.

**Comment by mrexodia** [comment]
I looked at the various other alternatives (BinTray being the number one), but until anyone finds a release bundled with malware I don't see the point in changing. If you don't trust SourceForge you should build x64dbg yourself.

**Comment by ThomasThelen** [comment]
SourceForge has been known to bundle third party PUPs in with binaries under DevShare. I'm pretty sure the owner of the binary gets a small portion of money for it. 

There are also allegations that projects have been taken over by staff accounts, which is totally unethical.
For more info check out these developers' problems.

GIMP
https://mail.gnome.org/archives/gimp-developer-list/2015-May/msg00144.html
http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/

NMAP
http://seclists.org/nmap-dev/2015/q2/194
http://arstechnica.com/information-technology/2015/06/black-mirror-sourceforge-has-now-siezed-nmap-audit-tool-project/

VLC Media Player
https://blog.l0cal.com/2015/06/02/what-happened-to-sourceforge/

These are all reputable softwares which have had issues with SourceForge. If it were up to me I wouldn't support the actions of the company and move locations.

**Comment by mrexodia** [comment]
@ThomasThelen Yea, but like I said we didn't have any issues so far. I know all these things, but it's not like there is a comparable service out there that does the same.

Idealism doesn't really get us anywhere in this case so we stick with source forge until a good alternative presents itself.

**Comment by RaMMicHaeL** [comment]
You can use GitHub for releases.
https://github.com/x64dbg/x64dbg/releases

**Comment by golergka** [comment]
While you know that there weren't any issues, a potential new user will
just seek an alternative when he sees that the only source for a binary
download is from SF.

On Wed, Sep 23, 2015 at 12:24 PM, RaMMicHaeL <notifications@github.com>
wrote:

> You can use GitHub for releases.
> https://github.com/x64dbg/x64dbg/releases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x64dbg/x64dbg/issues/391#issuecomment-142542312>.
>



-- 

Best regards,

Max Yankov

Phone:  +972 58-690-0233
Email: golergka@gmail.com
Skype: golergka

**Comment by mrexodia** [comment]
@golergka Yea, I do recommend building everything yourself if you want to know with 100% certainty that nothing was modified. Soon I will start signing the binaries with an open source certificate which might help.

@RaMMicHaeL I'll look into GitHub releases, I didn't know they had an API before.

**Comment by mrexodia** [comment]
The latest snapshot will always be available at http://releases.x64dbg.com in addition to SourceForge.
