### ISSUE TITLE
Wrong determine asm instruction "MOV CH,xx"

### ISSUE THREAD

**Issue by ELFRUS** [x64dbg/x64dbg#394]
![image](https://cloud.githubusercontent.com/assets/14360574/9976309/e0c85e6a-5ee8-11e5-9ea1-0e135d2b5d4d.png)

x64 dbg v2.5:
000007FEEE4D2F01 | 40 B5 86                 | MOV CH,86                               |
CH - high 8-bit register part of ECX(RCX)

IRL:
40 B5 86 == MOV BPL, 86
B5 86 ==  MOV CH,86

BPL - low 8bit of EBP(RBP)

Action:
Fix CH to BPL

**Comment by mrexodia** [comment]
should be fixed once #337 is resolved.

**Comment by mrexodia** [comment]
I checked and this issue has been resolved:

![screenshot](http://i.imgur.com/JekpM2E.png)
