### ISSUE TITLE
Imported symbols

### ISSUE THREAD

**Issue by Jiwan** [x64dbg/x64dbg#395]
When you go in the symbols tab you will only see the exported symbols. It can also be really handy to also get the imported symbols of a given executable module "à la OllyDbg".

**Comment by mrexodia** [comment]
yea, sounds like a good idea!

**Comment by JetCrusherTorpedo** [comment]
I agree. This would be nice.

**Comment by Nukem9** [comment]
Has been implemented (date unknown).
