### ISSUE TITLE
Memory Map: Protection and Initial Strings not properly 0 terminated

### ISSUE THREAD

**Issue by mrgreywater** [x64dbg/x64dbg#396]
See: http://imgur.com/LqmGhTL

Debug Build, x32 on Windows 10 compiled with VC14

**Comment by mrexodia** [comment]
dont compile with vc14 :+1: anyways will leave the issue open.

**Comment by mrgreywater** [comment]
This will most likely also happen with VC12 with debug heap. Release mode will probably work in most cases, as the memory is deliberately initialized with values different from 0 in debug mode.

**Comment by mrexodia** [comment]
yea, probably.. thats why i will leave the issue open :)

**Comment by mrgreywater** [comment]
This line is removing the zero termination: https://github.com/x64dbg/x64dbg/blob/master/x64_dbg_dbg/memory.cpp#L436
