### ISSUE TITLE
Follow in ((option)) doesn't correctly scroll down at the end of a PE section

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#401]
The `Follow in dump/disassembler` option fails to scroll down correctly when the target address
is near the end of the PE section.

The range of failure (in **decimal**) is: `[0, 38]` bytes from the __*end*__, which means that if the required
address has an offset *between-or-equal-to* `[0, 38]` from the end of the PE section
( `last_address_in_section` - `target_address` = `[0, 38]` ) this issue will occur.

1- Debug any application (32-bit or 64-bit, it doesn't matter) and follow any PE section
in dump or in disassembler.
2- Get the address of any byte, such that this byte is the last one or has an order __<= 38__
from the end of the section.
3- Scroll up and select any byte that is very far from the target byte.
4- Press `Ctrl + G` --> paste the address --> hit 'Enter'.
5- The window (dump or disassembler) won't be scrolled down to the correct address,
but if you do it manually, you'll see that the target address is correctly selected.

- If the address offset is __>= 39__ then the scrolling works fine.
- Again as mentioned above, this happens when following in disassembler too
not only in dump, and when it occurs the address is properly selected (pure scrolling issue).

EDIT:
Looking at older issues, this seems to be an exact duplicate of #243.
If so, very sorry and please feel free to close here immediately.

**Comment by mrexodia** [comment]
the 38 value depends on the height of the dump/disasm window. Keeping both issues open because this one has a better description on how to reproduce.

**Comment by wk-952** [comment]
@Nukem9
Seems to be completely fixed after your commiit, thank you very much.
feel free to close here you or mrexodia, i always appreciate your work guys.
Thanks again.

**Comment by wk-952** [comment]
Seems to be solved.
