### ISSUE TITLE
Follows jmp instruction to incorrect offset

### ISSUE THREAD

**Issue by megatron23** [x64dbg/x64dbg#402]
![dissasm](https://cloud.githubusercontent.com/assets/14837723/10102025/9ccf0160-639c-11e5-88ae-c77857fb7e3e.png)

Instead of the highlighted instruction to be executed correctly the application jumped to the current instruction at RIP. Here the value at RSP is null and the RET instruction triggers an exception.

The bug appeared when I inserted the PUSH RDI instruction at 0x1400012F5, the entry point of a function. It dissapears if I remove it or insert another instruction at that point.

The bug does not appear when executing the application without a or with another debugger.

Im using Windows 7 Ultimate and x64_dbg v24.

**Comment by megatron23** [comment]
It seems it has something to do with code alignment. Another PUSH aligns the JMP instruction at an even byte, so does aligning the entry point. Maybe it as something to do with windows' debbugging functions.

**Comment by megatron23** [comment]
The problem was with the database file saved for the debugging environment. something gets corrupted there which then messes around with register values or offsets while debugging.
After deleting the .dd64 file it works again. I did restart and close the debugged application quite often and fast. maybe there is a problem with syncronization. I am not sure if i can reproduce that weird bug again.

**Comment by mrexodia** [comment]
do you still have the corrupted database?

**Comment by megatron23** [comment]
yes i do: http://s000.tinyupload.com/index.php?file_id=01306886889323187004

**Comment by mrexodia** [comment]
```
{
    "breakpoints": [
        {
            "name": "",
            "titantype": "0x0",
            "address": "0x11AF",
            "enabled": true,
            "oldbytes": "0xFFFFFFFFFFFF8B4C",
            "type": 0,
            "module": "test.exe"
        },
        {
            "name": "",
            "titantype": "0x0",
            "address": "0x134D",
            "enabled": true,
            "oldbytes": "0xFFFFFFFFFFFF8349",
            "type": 0,
            "module": "test.exe"
        }
    ]
}
```

Did you have breakpoints on these locations?

**Comment by megatron23** [comment]
yes. but both got shifted after rebuilding the exe. 0x134D now points into the middle of an instruction.

**Comment by megatron23** [comment]
another thing, after the exception is handled, i cannot close the debuggee anymore and when closing the debugger a window pops up for a fraction of a second saying something about a memory leak.

**Comment by mrexodia** [comment]
Is this still an issue @megatron23 ?

**Comment by megatron23** [comment]
@mrexodia No, I tried the latest snapshot and it now disables the breakpoints if the application is rebuilt.
