### ISSUE TITLE
add a warning when people try to set the IP to non-executable memory regions

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#403]
https://en.wikipedia.org/wiki/Data_Execution_Prevention

new sections need executable rights

**Comment by Nukem9** [comment]
Should check if DEP is enabled on the process first: [GetProcessDEPPolicy](https://msdn.microsoft.com/en-us/library/windows/desktop/bb736297(v=vs.85).aspx)

**Comment by mrexodia** [comment]
`assemble.cpp` has pretty much all the code. this should be moved to `memory.cpp` and exported for the GUI.
