### ISSUE TITLE
Problem with Goto->Expression

### ISSUE THREAD

**Issue by StrongCod3r** [x64dbg/x64dbg#406]
https://youtu.be/p2MD-wgjCuQ

sc.

**Comment by mrexodia** [comment]
Assuming it is a bug. Cannot check the video right now because of slow connection. Would it be possible to give a simple textual description or is it too complicated to replicate?

Thanks!

**Comment by wk-952** [comment]
It's the same issue of following/going to an address near the end of a PE section ( #243 and #401 ).
In the video he tried following a certain address in the dump window but it didn't scroll down properly, so I assume it's near the bottom.

**Comment by mrexodia** [comment]
Yea, this issue is annoying and kinda fundamental so I'm not sure it can be
fixed quickly. Will check it later.

**Comment by mrexodia** [comment]
Here is a similar problem (reported by GIV): https://mega.nz/#!Kkph2b5T!fY0I0hNxT4uxURhat5XHLf1WvSjmNelQgH7vx0BAilg
