### ISSUE TITLE
copy address

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#407]
allow copying rva in dump and disassembly

**Comment by wk-952** [comment]
If possible, could you also please add "copy address" (normal VA) in the dump window,
it's already implemented in the disassem window but when selecting a certain byte in the dump window I can't copy it's address.
Sorry if this is already implemented.

**Comment by mrexodia** [comment]
Copy address is hidden. Try middle mouse button. The idea is good though. I
will also add copy address as a menu option.
