### ISSUE TITLE
Add Screenshot Feature

### ISSUE THREAD

**Issue by ThomasThelen** [x64dbg/x64dbg#408]
I know I am not alone on this issue. When writing documents regarding a disassembly I use the windows snipping tool to grab a screenshot. It usually takes two to three tries to get the exact lines that I need without cropping other pieces of the window. 

I was thinking that it would be nice to have an option to select a block of code, and then have an option to save it as an image.

**Comment by mrexodia** [comment]
yea, looks like a good idea. Don't have a clue how that would work with Qt though. Ideas are appreciated.

**Comment by mrfearless** [comment]
If its the currently selected rows or row, is it possible to get the coords of the left most column relative to screen, and then a getwindowrect for the selected highlight (the grey bar), enumerate that for all selected rows adding the rect.bottom to the previous result till you have the area to 'grab' - if that possible then you might be able to get the dc for the main window and create a compatible bitmap and bitblt that into the new in memory bitmap - then once you have that you could export it as a bmp at least. Or use an open source lib to generate a png from the captured in memory bitmap. Maybe?

**Comment by mrexodia** [comment]
Yea, sounds like a massive pain in the butt haha. I might try this later,
but it won't be high on my priority list.

**Comment by Nukem9** [comment]
http://doc.qt.io/qt-4.8/qpixmap.html#grabWindow

Significantly easier to do this with Qt-only code and saving the file.

**Comment by ThomasThelen** [comment]
I'll gladly add this feature. thanks for the info fearless and nukem.
