### ISSUE TITLE
Push instruction with 0x40000000 argument results in pushing 0xCC000000 dword in stack

### ISSUE THREAD

**Issue by deselect** [x64dbg/x64dbg#410]
Hello. I am debugging simple WinInet downloader.

1. Opened x32dbg.exe
2. Opened downloader in it (https://dl.dropboxusercontent.com/u/16265626/loader.exe)
3. Stepped by pressing F8 and stopped at "push 40000000" instruction (EIP: 0040109C)
4. Pressed F8 again and see "CC000000" instead of "40000000" dword on the top of stack.
5. Stepped to CreateFileA call, pressed F8 and got FFFFFFFF in eax (INVALID_HANDLE_VALUE).

Program itself works correctly. In OllyDBG it works correctly too, no bug with stack.
Video: https://dl.dropboxusercontent.com/u/16265626/push_bug.avi

UPDATE: I have tested it again by loading program to debugger and setting EIP to 0040109C via "Set new origin here" and pressing F8. Bug still persists.

**Comment by Nukem9** [comment]
`0xCC` is the breakpoint instruction, so TitanEngine is screwing up the command I guess. Less related to the debugger itself.

**Comment by deselect** [comment]
Maybe. See this video: https://dl.dropboxusercontent.com/u/16265626/push_bug1.avi

**Comment by deselect** [comment]
Added "nop" instruction before pushing arguments for CreateFileA. Now it pushes 0x40CC0000 instead of 0x40000000. Added two nops and it pushes 0x4000CC00.

**Comment by mrexodia** [comment]
is this still an issue @deselect ?

**Comment by mrexodia** [comment]
is this still an issue @deselect ?
