### ISSUE TITLE
Labels when copying disassembly are not copied.

### ISSUE THREAD

**Issue by ghost** [x64dbg/x64dbg#413]
When clicking "Copy > Disassembly", labels for jumps are not copied when copying ASM text. Example:

pop ecx
mov esi,dword ptr ss:[ebp-8]
mov edx,dword ptr ss:[ebp+C]
movzx esi,byte ptr ds:[esi]
shl edx,8
or edx,esi
inc dword ptr ss:[ebp-8]
dec ecx
mov dword ptr ss:[ebp+C],edx
jnz pj6417patch.44422E

the label for the JNZ is not copied in that code fragment (should be at pop ecx)

**Comment by wk-952** [comment]
Tried that now with build 10/29 (snapshot_2015-10-29_11-55), and it's copying custom labels correctly,
in a test app, at address 6140C943, i've added the label "some custom label",
correspondingly the jump to that address became "JMP <tst_prog.some custom label>",
when i right-clicked this jump then (copy -> selection) the label was copied correctly,
again right-clicked the jump then (copy -> disassembly) it was also copied correctly.
You might want to try the latest build snapshot, i guess it's fixed.

**Comment by mrexodia** [comment]
this has been implemented in a plugin: http://rammichael.com/multimate-assembler
