### ISSUE TITLE
Script is very annoying

### ISSUE THREAD

**Issue by githob605608886** [x64dbg/x64dbg#414]
I want to capture the specified message number,
I set a breakpoint on DefWindowProcW
breakpoint causes the debugger to activate
So I can not operate at all

I am using Google translate, hope you can understand

**Comment by githob605608886** [comment]
var $addr
var $keyDown,0x100
gpa "CallWindowProcW","user32.dll"
mov $addr,$result
bp $addr
_goBreakPoint:
cmp $addr,rip
jne _next 
cmp rdx,$keyDown
jne _next:
jmp _pause:
_next:
log "next {0} {1}",rdx,$keyDown
go
jmp _goBreakPoint
_pause:
log "pause breakPoint"
pause
jmp _goBreakPoint

----------------------------------------

This is my script code

**Comment by mrexodia** [comment]
Simplified script:

```
$keyDown = 0x100
$addr = user32:CallWindowProcW
bp $addr
_goBreakPoint:
cmp $addr, rip
jne _next 
cmp rdx, $keyDown
jne _next:
jmp _pause:
_next:
log "next {0} {1}",rdx, $keyDown
go
jmp _goBreakPoint
_pause:
log "pause breakPoint"
pause
jmp _goBreakPoint
```

I will check the behavior. Probably it is related to https://github.com/x64dbg/x64dbg/blob/master/x64_dbg_dbg/debugger.cpp#L293

**Comment by mrexodia** [comment]
probably solved. feel free to reopen if not.
