### ISSUE TITLE
Unable to delete breakpoints after stopping debugged process

### ISSUE THREAD

**Issue by vans163** [x64dbg/x64dbg#415]
You should be able to delete breakpoints once the process is killed.

**Comment by mrexodia** [comment]
Once the process is killed there are no longer any breakpoints to delete,
so this is not possible.

Do you mean that the breakpoint list is not cleared after a process closes?

**Comment by vans163** [comment]
None of the BP lists are cleared.  Unable to do remove all.   v02_31_41.  I should really use the latest snapshot.

**Comment by mrexodia** [comment]
Hello,

The latest snapshot is available on http://snapshots.x64dbg.com I recall
fixing this issue.

**Comment by mrexodia** [comment]
Considered fixed, feel free to reopen if it wasn't.
