### ISSUE TITLE
x64dbg not accepting arguments

### ISSUE THREAD

**Issue by TreeOone** [x64dbg/x64dbg#417]
Hello!

I have problems with x64dbg and it's ability to invoke debugging sesion with arguments.

This board has few threads with simmilar problems, but non of the proposed solutions seem to work for me.

x64dbg has also help file which I do not understand.

So, my test application is located here:

C:\Program Files\TEST\MyApp.exe

, and it should be started with following arguments:

/Par:"Advanced"

As per manual, one is supposed to open x64dbg, and enter command InitDebug with file path and arguments.

I have tried many combinations, and all ended with message File does not exist!.

So my question is what should be inserted in command textbox to invoke debugging sesion with arguments.

I have tried following:

InitDebug "C:\Program Files\TEST\MyApp.exe" /Par:"Advanced"

InitDebug C:\Program\ Files\TEST\MyApp.exe /Par:"Advanced"

InitDebug "C:\Program\ Files\TEST\MyApp.exe /Par:"Advanced""

Any suggestions?

**Comment by mrexodia** [comment]
Hello,

In your case I recommend using the change command line function (see the
FAQ). However you need to string escape the quotes like so:

Init "c:\test dieectory\test.exe", "/Par:\"Advanced\""

You can see if you did things right in the Debug -> Change command line menu

**Comment by TreeOone** [comment]
Thank you mrexodia for your help.

Comma and few backslashes solved my problem.
