### ISSUE TITLE
Unexpected behavior in the text cursor of the search textbox

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#418]
Anything that involves the search box in bottom of the References tab will have the same effect,
i.e: searching for string references, patterns in the memory map, intermodular calls.

*Problem 1:
1) Debug an application and try searching for any of the above-mentioned stuff.
2) In the search textbox at the bottom, type anything.
3) The typing/text cursor will disappear,
you can still type and 'backspace' characters but you can't move the cursor left/right.

*Problem 2:
4) Manually place the cursor in the middle of your text and again start typing.
5) Only 2 characters will be written at the desired location, but the rest will be typed at the end.

I know it's not a big deal or anything, you can barely notice it actually,
but just as a reminder.

**Comment by mrexodia** [comment]
Yea, the reason for this is that i want people to be able to type in the
texbox while their focus is on the list. Its fixable but involves keeping
track of a virtual cursor.

**Comment by wk-952** [comment]
Oh, right, i missed the point of keeping the results list in focus.
Sorry about that, i'll close here then since it's invalid.

**Comment by mrexodia** [comment]
Nah, its possible to fix I think. Please keep it open.

**Comment by wk-952** [comment]
A new issue is introduced,
1. Search for example for strings in the current region/module
2. Select the search textbox when it's finished. and start typing anything.
3. The first 2 chars will be typed normally,
but then the imaginary cursor will be in the middle of the 2 chars (will decrease its position by 1),
so if you continued typing the 2nd char will always be at the end.

4. Press `ESC` then start typing again --> everything will be normal

**Comment by Nukem9** [comment]
Should be fixed in https://github.com/x64dbg/x64dbg/commit/0d17101ba87e9e4414a9af13d378e4653fe9bd3c. Nothing messes with the cursor anymore.
