### ISSUE TITLE
x64 relative address not processed correctly for LEA opcodes

### ISSUE THREAD

**Issue by sunbeam906** [x64dbg/x64dbg#421]
I'm using latest build of the debugger, v25v Oct 28 2015. When debugging ACC.exe (Assassin's Creed: Rogue executable), I did the following:

- open executable
- memory map > acc.exe (right-click on .text section and follow in disassembler)
- right-click and search for string references

Once finished, I filtered the list for what I was looking for - "vanish" word - and found my reference. Upon following it in disassembler, I noticed the below:

0000000141EBDC4A | 48 8D 15 97 05 C1 00     | lea rdx,qword ptr ds:[142ACE1E1]        |

Looking at the same address with Cheat Engine shows the following:

141EBDC4A - 48 8D 15 9705C100     - lea rdx,[142ACE1E8] : ["[Blend Action] Toggle Player Vanish :"]

As you can see, even though the hex bytes are identical, the translation of the referenced address fails in x64_dbg. It should show 142ACE1E8 instead of 142ACE1E1.

Eagerly waiting for a small fix.

Just FYI, issue's not present in this build: snapshot_2015-10-15_05-48.7z.

Best regards,
Sun

**Comment by mrexodia** [comment]
This should have been fixed. Could you try today's build from the releases
section in the repo?

**Comment by mrexodia** [comment]
Just verified, it has been fixed:

![screenshot](http://i.imgur.com/lqF729B.png)

Feel free to reopen if the issue is still there with the latest snapshot.
