### ISSUE TITLE
fix the gui calling all kinds of dbg apis during/after shutdown

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#424]
cancel all paint events with some global filter and add DebugBreak statements that hard crash when people mess up

**Comment by Nukem9** [comment]
This would probably be easiest by doing `if (DbgIsDebugging()) return;` at [this line](https://github.com/x64dbg/x64dbg/blob/master/x64_dbg_gui/Project/Src/BasicView/AbstractTableView.cpp#L146). Headers would still be drawn, but no content (values) would be.

Don't know of any other global ways to do that right now.

**Comment by mrexodia** [comment]
Hey, I had a similar solution in mind. Doing this however will disable
attach and maybe other features. I think its best to make a 'debugOnly'
bool to make sure only certain views are affected. I'll check it out later
today.
