### ISSUE TITLE
Make cbUserBreakpoint only notify CB_BREAKPOINT when we set it.

### ISSUE THREAD

**Issue by meepdarknessmeep** [x64dbg/x64dbg#426]
```
plugincbcall(CB_BREAKPOINT, &bpInfo);
```

This line will break in some uncommon antidebugger tricks. There is an undocumented function I have came across that will break under this line of code running for every "int3" instruction.

`RtlAddVectoredExceptionHandler` from ntdll will set an exception handler, and when int3 is ran, it will call the second argument to the function. However, when you use x64dbg, it will go over the int3 and continue to the opcode in front of it.

## Solution
Only call `plugincbcall(CB_BREAKPOINT, &bpInfo);` when we have set the breakpoint.

**Comment by mrexodia** [comment]
As far as I know this callback is only called with user breakpoints, but I
will check.

**Comment by meepdarknessmeep** [comment]
At least when I was debugging an application, it would just run over the int3 to the next opcode after it. When I removed the line and compiled it - it seemed to work fine.

**Comment by mrexodia** [comment]
just checked, CB_BREAKPOINT is only called when a breakpoint was set by the user. It does not trigger on random INT3 exceptions (unless something is horrible wrong with TitanEngine that I didn't notice before).

Possibly you are getting a notification for an automatically set breakpoint for the entry point or TLS callbacks (these are included).
