### ISSUE TITLE
Last chance exceptions are not ignored, even if set to ignored

### ISSUE THREAD

**Issue by meepdarknessmeep** [x64dbg/x64dbg#427]
This is hurting a program that is using `RtlAddVectoredExceptionHandler` to antidebug.

## Solution

Move the code:
```
if(bSkipExceptions || dbgisignoredexception(ExceptionCode)
    return;
```
before the `if(ExceptionData->dwFirstChance)` ... `else` .. clause

**Comment by mrexodia** [comment]
Last chance exceptions cannot he ignored as far as I know. Could you
provide a pull request to see what you mean?

AddVectoredExceptiom handling can be used for anti debug because the
exception is not reported to the debugger.

**Comment by meepdarknessmeep** [comment]
It actually is reported to the debugger in this case. It is reported to the debugger, and if the debugger provides an action to do with the exception, it will step over the exception. If you provide nothing for the exception, it will follow AddVectoredException.

**Comment by meepdarknessmeep** [comment]
Also they can be ignored, I changed the code and it works fine.

**Comment by mrexodia** [comment]
Ignoring a second chance exception is like ignoring that a crash happened.
Please provide some code samples and a pull request so I can check if it is
a bug tomorrow.

**Comment by meepdarknessmeep** [comment]
I don't have access to the code that causes this bug, but I can assure it it does happen.

The program I am debugging right now does this:

TlsCallback 0 -> 
Bunches of things for imports ->
Manually maps it's own exe into itself, and unloads the original ->
`RtlAddVectoredException(1, &function);` ->
Proceeds with loading the exe, but with modified start address and such ->
runs opcode `17h` (which is an invalid opcode) ->
calls exception function ->
go back to running opcode `17h`

I should also mention this is a 64bit application.

I am not providing a pull request because I believe that disabling last chance exceptions completely is not a good idea, and should be an option of some sort in the gui. I am also not changing the gui since I was unable to get it to compile correctly and I am not familiar with qt.

**Comment by mrexodia** [comment]
Alright, I will take a look at it tomorrow.

**Comment by lupier** [comment]
Dear meepdarknessmeep, can you try scyllahide plugin for your target and report what you get?
https://bitbucket.org/NtQuery/scyllahide

**Comment by meepdarknessmeep** [comment]
It doesn't appear to change anything when I am debugging.

**Comment by mrexodia** [comment]
I did some tests. VEH is working correctly:

```
#include <windows.h>
#include <stdio.h>

LONG WINAPI VectoredHandler1(PEXCEPTION_POINTERS ExceptionInfo)
{
    puts("VectoredHandler1");
    return EXCEPTION_CONTINUE_SEARCH;
}

LONG WINAPI VectoredHandler2(PEXCEPTION_POINTERS ExceptionInfo)
{
    puts("VectoredHandler2");
    if (ExceptionInfo->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT)
    {
#ifdef _WIN64
        ExceptionInfo->ContextRecord->Rip++;
#else
        ExceptionInfo->ContextRecord->Eip++;
#endif
        return EXCEPTION_CONTINUE_EXECUTION;
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

int main()
{
    puts("Start main()");
    AddVectoredExceptionHandler(1, VectoredHandler1);
    AddVectoredExceptionHandler(0, VectoredHandler2);
    __debugbreak();
    puts("End main()");
}
```

Output without debugger:
```
Start main()
VectoredHandler1
VectoredHandler2
End main()
```

Output with debugger:
```
Start main()
VectoredHandler1
VectoredHandler2
End main()
```

**However** when you add the line `system("pause");` at the end of main, the output in the debugger will be:

```
Start main()
VectoredHandler1
VectoredHandler2
End main()
VectoredHandler1
VectoredHandler2
```

The log shows:
```
DebugString: "Application \"\\??\\C:\\Windows\\system32\\cmd.exe\" found in cache\n"
```

So this appears to be related to https://repo.palkeo.com/repositories/mirror7.meh.or.id/Todo/NtSetDebugFilterState.pdf (it does something with query filter state somewhere). It will be resolved by hiding the debugger in the PEB (use the `dbh` command).

**Comment by mrexodia** [comment]
This has now been implemented as you can choose that happens to an exception now.

**Comment by speidy** [comment]
Is this issue resolved?
I still cann't ignore last chance exception with latest git.

**Comment by mrexodia** [comment]
You can but probably you use the wrong function for it.

**Comment by brandonros** [comment]
I think this is still an issue. I am on 2019-06-19 snapshot, I attach with ScyllaHide, I have C00000005 added as an ignored exception, and I still get asked to pass the last chance exception.
