### ISSUE TITLE
VA -> file offset support

### ISSUE THREAD

**Issue by kitt3n** [x64dbg/x64dbg#428]
In Ollydbg it's possible to go from VA to file offsets by using View -> Executable file, which displays the file offset for a selected offset in VA. it's missing in x64dbg, would be nice to have it added.

**Comment by mrexodia** [comment]
Selected RVA in disassembly is available in the infobox (little box under
disassembly) it also shows the section and some other info.

You can navigate to an rva using "module:$rva" (use ":$rva" for the current
module). Replace the $ with a # for file offset.

You can copy the RVA by going in the context menu -> copy -> rva

Is this enough?

**Comment by Nukem9** [comment]
Just to clarify - he means to view the _file offset_ itself, similar to a hex editor, not the relative virtual address.

The infobox is:
`MOUDLE[RVA] | SECTION:VA`

Maybe something like this could work:
`MODULE[RVA:FILE_OFFSET] | SECTION:VA`

**Comment by mrexodia** [comment]
Oh right, sounds like a good idea to me!
