### ISSUE TITLE
fix refresh problems with the memory map

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#429]
There are some serious issues with the 'automatic' refresh option of the memory map (reproduced in Nukem9-master but possibly also in the master). Can be reproduced with some program that does memory allocation. Will provide a sample later.

This issue has been reported to me privately before, but I was never able to reproduce it and I'm not sure if there is an issue already.

**Comment by mrexodia** [comment]
Probably related to https://github.com/x64dbg/x64dbg/blob/Nukem9-master/src/dbg/debugger.cpp#L68 

@Nukem9 do you think it will hurt performance much to force update the memory map every second?

**Comment by Nukem9** [comment]
Given that it runs on a separate thread from everything else, I wouldn't be worried about it very much.

**Comment by mrexodia** [comment]
Alright, I'll remove the check then. I'm now actively using your branch for
debugging. So far no hickups I didn't fix yet. I'll be back home on sunday
so maybe we can then merge the current stuff.

I had the idea of using the master branch as a 'stable' branch and then
using this (or another) branch for refactoring and stuff. How does that
sound to you?

**Comment by Nukem9** [comment]
Yeah the branches are fine. I think having a `master` and `development` should be good enough.
