### ISSUE TITLE
filter symbol names that say `string`

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#431]
some symbol names are really bad and prevent you from reading the code. filter these out.

**Comment by mrexodia** [comment]
also filter out stuff like __imp__GetCurrentProcess?

**Comment by Nukem9** [comment]
Alternatively, \`string\` could be renamed to `aSomeString`, similar to IDA.

`__imp__` is a prefix to a pointer (i.e `call dword ptr [__imp__GetCurrentProcess]`). I don't think they should be filtered, but should be renamed.

**Comment by mrexodia** [comment]
Yea, the string is a good idea. But the engine resolves those imports so it
makes no sense to have them as symbols.

**Comment by Nukem9** [comment]
Probably want to filter these too.

![image](https://cloud.githubusercontent.com/assets/4228359/11385893/2bb8d478-92eb-11e5-98b2-3d5826c2d0c2.png)

**Comment by mrexodia** [comment]
why? they look like legit symbols to me.

solution: custom symbol filters with regex (YAY)
