### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by MyGameFrame** [x64dbg/x64dbg#436]
Hi. Thank you for releasing the tool. Am I doing something wrong?

![x64dbg](https://cloud.githubusercontent.com/assets/12815172/11323554/655007a8-911d-11e5-8b59-f9d7d2356cf9.png)

The game has some kind of anti-debug protection but I am able to debug it with Cheat Engine after enabling a VEH debugger in the debug options. A friend suggested me to use ScyllaHide plugin with your tool and I installed it but can't debug as the game crashes even when I enable that plugin.

PS. Is it possible to analyze a dumped executable similar to IDA with your tool? I tried to load a dumped executable of the game but failed to debug it.

**Comment by Nukem9** [comment]
Possibly related to #427.

For your second question:
As it stands right now, there's no way to analyze dumps. The executable needs to be able to run (as far as `CreateProcess` is concerned).

**Comment by MyGameFrame** [comment]
Well I found reason why this game cannot be debugged with x64dbg: http://www.unknowncheats.me/forum/1356038-post1.html

It has some anti-debug protection. ScyllaHide does not fix the issue. I can debug the game with CheatEngine by enabling a VEH debugger. Maybe author can consider this as a feature request. 
Thanks.

**Comment by mrexodia** [comment]
@MyGameFrame the only anti-anti-debug measures that are (and will be) built in are the ones that are non-invasive (eg don't modify code). Stuff like IsDebuggerPresent and HeapFlags can be bypassed with the `dbh` command.

If you want special anti-anti-debug measures write a plugin or script that does them for you. At the moment scripting is not meant for these kind of things but there are plans for integrating scripting engines to allow this kind of behavior.
