### ISSUE TITLE
Crash issue when stopping then restarting an application (related to "Nukem9-master" branch only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#438]
- This is related to the `Nukem9-master` branch only, `master` branch is fine.
- The occurrence probability of this issue is higher in the 64-bit version of the debugger,
but it also happens in the 32-bit one (just takes more time).
- The faulty module and the info thrown after crash was different every time,
but many times the faulty module was `StackHash_217b`

Reproduction steps:
1) Debug any application (preferably a 64-bit one)
2) Press the stop button
3) Press the restart button
4) The debugger will crash immediately
5) (Additional) Repeat from step 2 if it didn't crash from the first time,
but it's guaranteed to crash!

here are the dump files generated:
http://rghost.net/private/69RxXHnCx/04cf8d3dc27cace79dc4c3bee4f438fb

- This issue won't occur if you restarted the application any number of times without stopping it at least once, so it must be stopped at least once.
- It also won't occur if you kept opening applications `(F3)` without stopping one of them at least once.

**Comment by wk-952** [comment]
I tried rebuilding in reverse order from the latest commit then going backwards,
but eventually gave up at 5e9a330 .
The last known commit that doesn't have this issue is 3de99ea and there are 4 commits between
the above mentioned 2 commits, so if none of this information is helpful i'll gladly continue building
the remaining 4 commits tomorrow to tell you which one specifically is the problem.

**Comment by Nukem9** [comment]
Holding down `Ctrl+F2` has been crashing since before the commit you have (at least in my branch). Same reason: `Fault Module Name:	StackHash_5e69`

It's probably related, I'll try to figure out what the problem is.

**Comment by wk-952** [comment]
Just to clarify, i didn't mean holding or spam-pressing `Ctrl + F2`, i'm already aware of that issue
since a very long time ago (almost a year).
The above mentioned issue involves restarting the debugger instantaneously,
but this one is a little bit different, you have to stop the application at least once and when it's stopped
you can wait any amount of time you want, after that the next restart is guaranteed to crash the debugger.

**Comment by mrexodia** [comment]
Damn, I thought the restarting bug was fixed...

**Comment by wk-952** [comment]
Did you mean those 2 old issues ( #303 or #323 ), in which the debugger would crash after a certain
number of restarts ?
If yes, then that's not what i meant, in this new issue you can restart as much as you want as long
as the stop button `(Alt + F2)` is not pressed at least once (that's actually why i didn't notice it before,
since i always restarted the target application without having to stop/ terminate it).

**Comment by mrexodia** [comment]
I know this is a different issue but you said:

> Just to clarify, i didn't mean holding or spam-pressing Ctrl + F2, i'm
already aware of that issue since a very long time ago (almost a year).

**Comment by wk-952** [comment]
This is fixed now :+1:
