### ISSUE TITLE
working executable is not running under debugger.

### ISSUE THREAD

**Issue by uzyszkodnik** [x64dbg/x64dbg#440]
Hey this executable https://www.dropbox.com/s/2ra85o4gaf4g7i8/test.exe?dl=0 is working perfectly fine when ran from console but somehow when loaded into debugger is causing "First chance exception on 771B8009 (c0000005, EXCEPTION_ACCESS_VIOLATION)!".

Im quite sure it's not due to any kind of anti-debugging tricks since I am the creator of it and I'm sure I haven't used any.

**Comment by uzyszkodnik** [comment]
although it works when opened from different path what i have just encountered,
so for "C:\Users\user\Documents\Visual Studio 2015\Projects\evm-compiler\x64\Debug"
it doesnt but for "C:\Users\user\Downloads" it works.

**Comment by mrexodia** [comment]
Do you have any plugins installed? At which point does the application
crash? For example do you see the entry point?

**Comment by uzyszkodnik** [comment]
Just scylla, the x64dbg version I'm running is 25 , from 0ct 15 .
It seems to get the exception from LdrSystemDllInitBlock so im not entirely sure whether it's x64dbg bug.

**Comment by mrexodia** [comment]
Doubt it, probably anti debug. ScyllaHide has a reputation of crashing
issues like these.

**Comment by uzyszkodnik** [comment]
But how can be anti-debug if I made this thing without it?

**Comment by Nukem9** [comment]
ScyllaHide does hooking and modifies your program at runtime. If ScyllaHide does something wrong, you program crashes. Using antidebug is irrelevant.

**Comment by uzyszkodnik** [comment]
Under plugin tab it's called Scylla, the bar says Scylla x64 v0.9.8 .

**Comment by mrexodia** [comment]
right, i'll check it out again

**Comment by uzyszkodnik** [comment]
I think the issue can be closed it seems that my operating system is showing some kind of strange behavior, when ran under vm x64dbg works correctly.

**Comment by Nukem9** [comment]
If you do figure out the reason, please let us know. Chances are you won't be the last person to report this. Closed for now.
