### ISSUE TITLE
Assemble create wrong instruction

### ISSUE THREAD

**Issue by Djamana** [x64dbg/x64dbg#441]
if I enter 
**mov dil, 1** it is assembled to
**mov bh, 1**

**mov sil, 1** it is assembled to
**mov dh, 1**

But well at least
**or dil, 1** works as expected

Note: applies to x64Dbg Version 24 [apr 3 2015]

**Comment by mrexodia** [comment]
![](http://i.imgur.com/PMcJ4EO.png)

update to the latest snapshot from http://releases.x64dbg.com
