### ISSUE TITLE
Odd behaviour is programmes involving System.windows.forms and mscorwks

### ISSUE THREAD

**Issue by PB314** [x64dbg/x64dbg#444]
Applications that incorporate mscorwks and system.windows.forms cause x32dbg some difficulty.  For example it will not break on entry and the database is not updated either when attaching to a process or opening it to debug it.  Biggest issue is the database not being updated as this means all breakpoints and comments are lost after eaching debugging session.

**Comment by mrexodia** [comment]
Hello, do you have a sample application for me to test with? Also which
version are you using? Maybe yesterdays merge fixed the problem.

Notice that .NET is not supported so the entry point break is as expected.

**Comment by PB314** [comment]
Thanks for the response.  Yes, try this application as an example.

http://www.cambam.co.uk/downloads/CamBamPlus-0.9.8P.msi

**Comment by PB314** [comment]
Sorry forgot the version number.  7Nov2015
