### ISSUE TITLE
symbol filter callback

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#445]
See issue #431 for more information (basically allow plugins to filter the symbols emitted from dbghelp to improve readability in a certain domain like Qt)

**Comment by Nukem9** [comment]
I remembered this repo today: https://github.com/zyantific/REtypedef

It would fit perfectly with the filter callback. Or use some kind of regex.

**Comment by mrexodia** [comment]
shouldn't be too hard to implement.
