### ISSUE TITLE
return to/from addresses in the callstack tab are swapped

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#446]
Looking at the `return to` address, it's now pointing to the beginning of the routine/function
instead of pointing to the instruction below the caller,
similarly the `return from` is pointing to the the instruction below the caller instead of pointing to
the beginning of the routine.

Is this intentional ?!

**Comment by mrexodia** [comment]
Probably not

**Comment by wk-952** [comment]
Solved, thanks Nukem.
