### ISSUE TITLE
something with tooltips

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#447]
show a tooltip when you hover over an address (maybe the offset or something)

**Comment by farmdve** [comment]
Show offset of some byte, from the starting address in the dump.

**Comment by Herz3h** [comment]
As there is already this option in the bottom status bar when there is a selection in dump window, how about having it show the content of where the Pointer is pointing when hovering over a pointer ?

**Comment by mrexodia** [comment]
This has been implemented in the dump, but keeping it open as a reminder for something similar in the disasm (with mnemonic briefs)
