### ISSUE TITLE
Search for constant accepts hex expressions only

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#448]
1) Debug any program and select search for ---> constant
2) Enter any number in the signed/unsigned textboxes
3) The OK button will be grey-ed out.

4) Again enter any number in the signed/unsigned textboxes followed by a mathematical operator
5) The OK will be active.

**Comment by Nukem9** [comment]
@wk-952 are you using x64dbg 24/7 or something? Very nice job finding bugs.

@mrexodia:
`Expression` unchanged
`Signed` only allows an optional negative and then numbers
`Unsigned` only allows numbers

No idea if this was the original intent.

**Comment by mrexodia** [comment]
Expression can be any valid expression, signed indeed a signed decimal
unsigned a unsigned decimal. Im 100% certain this used to work. Probably
more weird textChanged bugs

**Comment by wk-952** [comment]
In the old build i had, i didn't notice that it's not only a "search for constant" issue,
pretty much everything that involved the "Edit" dialogue box had this issue (for example changing registers), but now it's solved. Thanks :+1: .

@Nukem9 yeah nearly 3-4 hours a day, i'm very interested in and love this project.
On the other hand, i seriously hope i'm not bothering you or @mrexodia that much, i'm really just trying to help.

**Comment by mrexodia** [comment]
No, bug reports never bother! Thanks for your interest in the project!
