### ISSUE TITLE
Hardware BP not always triggered

### ISSUE THREAD

**Issue by Herz3h** [x64dbg/x64dbg#450]
Steps to reproduce this :

1) Set HW BP somewhere
2) Run program
3) Once Breakpoint triggered, set software BP by pressing F2 once
4) Run the program so it'll break on SW BP and then delete it by pressing F2 again
5) Run program and this time the HW BP is gone

Once the software BP is deleted, the HW BP is not triggered anymore even though a bplist shows that its still in breakpoints list and enabled. 

I've tried to look into this and from what i saw hwbp callback is not called after software BP is deleted, so i think the problem is in titanengine.

**Comment by Herz3h** [comment]
Found the fix, internally the breakpoint is reset everytime it's hit, and in the reset if, it does this : 

if(ResetBPX == true)
else if(ResetHwBPX == true)
else if(ResetMemBPX == true)

when it should be 3 If, so it sets back all breakpoints

**Comment by mrexodia** [comment]
Right sounds plausible. Please do a pull request if you have time.

**Comment by Herz3h** [comment]
Just sent the PR on bitbucket (pain in the ass to clone the repo.....)

**Comment by mrexodia** [comment]
reminds me that I should move TitanEngine to x64dbg/TitanEngine...

Op vr 11 dec. 2015 om 12:58 schreef Herz3h <notifications@github.com>:
