### ISSUE TITLE
yara rules not breaking with pe module

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#452]
sample:
https://mega.nz/#!sVcBxC7S!EoMFKV2kG3yZcRSZPXtFb4j3DyfSfv8tyNfx5mFxhgg

import "pe"

rule Morphine : Holy_Father Ratter29A
{
      meta:
		author="_pusher_"
		date = "2015-11"
		description="Polymorphic Cryptor"
condition:
		(pe.number_of_sections>=2) and
		(uint32(uint32(0x3C)+0x84) == 0x00000200) and
		pe.sections[0].raw_data_offset == 0x00000400 and
		pe.sections[1].virtual_size == 0x00001000 and
		//checking for GetProcAddress
		(uint32(pe.sections[1].raw_data_offset+0x4E) == 0x50746547) and
		//double check
		pe.imports ("kernel32.dll","GetProcAddress") and
		pe.imports ("kernel32.dll","LoadLibraryA")
}

**Comment by mrexodia** [comment]
What is the exact issue?

**Comment by Chandlr** [comment]
None of the checks works ive tested with yara itself and that works

**Comment by mrexodia** [comment]
works without problems for me: https://mega.nz/#!bsJUALbb!g1kkdTCYVQ6q88elsWbJGfkCwmyssAF8Djfb03susEY

**Comment by llallum** [comment]
Thanks for this. I found this helpful.
