### ISSUE TITLE
"Go to expression" window doesn't scale

### ISSUE THREAD

**Issue by trixnz** [x64dbg/x64dbg#454]
The "Go to expression" window doesn't seem to scale properly on 4K monitors. Image attached:
<img width="278" alt="2015-12-06_21-53-55" src="https://cloud.githubusercontent.com/assets/2995953/11613194/0f8a6f50-9c64-11e5-9e59-8fa64fb4e4c2.png">

**Comment by mrexodia** [comment]
Yea, its a known issue. I don't have a 4k monitor so I cannot test it.
Probably a proper layout would solve things but I read stuff about Qt and
4k not mixing very well too.

**Comment by trixnz** [comment]
No worries, thanks for looking into it. For now, I've just increased the size of the dialog and built from source.

**Comment by mrexodia** [comment]
Alright. If you can build it means you can also try to make a layout work.
Please try it and tell us if it helped.

**Comment by Herz3h** [comment]
I noticed that the lineEdit vertical sizePolicy is set to Fixed.
In the GotoDialog.ui try setting the label and lineEdit Vertical sizePolicy to Expanding and see what result you get

**Comment by namreeb** [comment]
I can confirm this issue on my 4K display.  I will plan to try what @Herz3h has suggested and report back.

**Comment by zwestfall** [comment]
Same problem with retina Macbook running Win10 in VMware Fusion. I have to drop down to 1280x800 and tolerate the fuzziness.

**Comment by Nukem9** [comment]
@zwestfall same thing as #492 - you either need to compile it for qt5 or use that custom resolution. Qt4 doesn't support Hi-DPI natively.

**Comment by mrexodia** [comment]
I want to fix this issue, but I'm too poor to buy a high DPI screen now and
don't know anyone to borrow one from. To any Qt developers out there,
please make a fix and do some tests. If need be we switch to Qt 5.x.

**Comment by zwestfall** [comment]
OK I rebuilt it with Qt 5.5.1, and this issue plus the tiny icons problem are both fixed.  There was no need to change any of the GUI source (except to comment out the Snowman references in MainWindow).

I did have to add the line:

`putenv("QT_DEVICE_PIXEL_RATIO=auto");`

at the beginning of function main (main.cpp) for the scaling to work properly.

I'll let you know if I encounter any issues with this build.

Cheers
Z

**Comment by mrexodia** [comment]
Thank you very much for confirming. We will switch to Qt5 soon then.

**Comment by torusrxxx** [comment]
I have removed the fixed size limit. Please test on latest snapshot again.

**Comment by mrexodia** [comment]
I'm currently porting everything to Qt 5.6.0 so all hidpi issues should be
fixed after that

**Comment by mrexodia** [comment]
Assuming this to be fixed now, please comment if it's not working.
