### ISSUE TITLE
Getting exported name from a function

### ISSUE THREAD

**Issue by dummy0stud** [x64dbg/x64dbg#455]
Can I get the moduleName and functionName from an address from command line?

ex:
log"{0}",eip
output:
user32.GetWindowLongPtrW

**Comment by mrexodia** [comment]
At the moment there is no way to do this due to the way the variables work
(they are essentially all integers). A hack I suggest is to implement a
plugin command that logs the way you want and then use that one in your
script.

**Comment by dummy0stud** [comment]
Ok, thanks, you can use std::map to solve the problem? how are you planning 2 solve this?

**Comment by mrexodia** [comment]
What? Internally there is no problem with this but the scripting language
just doesnt support it.

Yea, we're using map with some custom range hacks.

**Comment by dummy0stud** [comment]
mrexodia, 
I successfully made the plugin and it's working as expected with (x32dbg v25 compiled on Jul 14 2015, 14:08:07)
But when I try 2 load it inside compiled on (x32dbg v25 compiled on Oct 28 2015, 05:26:58)
I get an error inside Log Window("[PLUGIN] Failed to load plugin: myPlug.dp32")
Is there any plugin error logger that would make me catch why it's not loading inside this newer version of x32dbg?

**Comment by dummy0stud** [comment]
Well, just trying 2 figure out what's the problem, and it turns out that it's not related to the version, I just opened x32dbg inside x32dbg(lol) and the error is that LoadLibraryW returns ERROR_MOD_NOT_FOUND even with correct plugin path, it is only happening inside virtualbox

**Comment by dummy0stud** [comment]
Problem solved and thread can be closed, the problem is my plugin was being compiled with MTDLL and dependent of visual studio 14.0 distributable runtime packages, compiling with MT solved the problem, thanks again
