### ISSUE TITLE
Some instructions are parsed but cannot be manually assembled (floating-point instructions)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#456]
Example, this instruction is correctly shown in the disassem window `fistp qword ptr ss:[esp]`
__EDIT:__ (opcode: `DF 3C 24 `)
but if you tried to assemble this instruction anywhere else (manually i mean) you'll get the error msg:
__`Failed to assemble instruction ... XED could not encode the given instruction.)`__

I came across this one only, but i'm sure someone opened an issue in the past asking to add
support for floating-point instructions, can't find/remember it though :(
if that issue is still open (i couldn't find it), please feel free to close here and apologies for duplicate.

**Comment by mrexodia** [comment]
Probably xedparse doesnt support this instruction yet. Will need a fix.

**Comment by Nukem9** [comment]
It's because Xed itself also requires an explicit FPU operand, even though the instruction itself only uses one single operand.

i.e
`fistp qword ptr ss:[esp]` Real instruction. Not parsed correctly.
`fistp qword ptr ss:[esp], st0` Fake instruction. Parsed correctly to `DF 3C 24`

I'll have to determine a way to make this automatic.

**Comment by mrexodia** [comment]
How about hardcoded? Get all instructions with implicit fpu operands and
add the appropriate operand if the user didn't:D

**Comment by Nukem9** [comment]
If you want to make a giant list from the IFORM enum, sure.
It's probably easier to just do `if (strstr(xed_iform_to_string(iformType), "_st0"))`

**Comment by Nukem9** [comment]
https://github.com/x64dbg/XEDParse/commit/d3f8d6fd5440624a4825c99e3bf4a4f519ad416a

Fixed in x64dbg when xedparse.dll is replaced.

**Comment by wk-952** [comment]
Thank you so much! :+1:
