### ISSUE TITLE
Crashing bug

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#460]
sample:
https://forum.tuts4you.com/applications/core/interface/file/attachment.php?id=13277
F9 to allow it to run normally
then press the buy button, crash

**Comment by Nukem9** [comment]
Pressed "Buy" and nothing happened except for the website opening. Can't reproduce.

**Comment by Chandlr** [comment]
did you check with: snapshot_2015-12-14_11-17.7z ?

**Comment by Nukem9** [comment]
Tested with the snapshot and latest commit. Both have the same result: program runs fine. Do you happen to have a DMP file in the `minidump` folder to upload?

**Comment by Chandlr** [comment]
No sorry no dumps at all

**Comment by Chandlr** [comment]
Link to a video that shows it happening, with another bug at the same time. 
https://mega.nz/#!VYUTDRCD!ZflIkatwvpBDA_yLekYree7fCz3Oi6i9ak32BVBV8Rs

**Comment by Chandlr** [comment]
The bug is fixed with: snapshot_2015-12-20_05-03.7z
the build: snapshot_2015-12-17_05-29.7z atleast gave a error msg but now its fixed :)
