### ISSUE TITLE
Snowman decompiler only works on a defined function (GUI only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#461]
1. Debug any program and select a block of instructions
2. Right click --> Decompile.
At this point you should get a sub-menu with the option `"Selection"`,
but instead, you'll get the option `"Function"`.
3. Select that option (it's already the wrong one) --> nothing happens in Snowman tab.

4. Define the selected block of instructions as a function `(Ctrl + F)`,
then again Right click --> Decompile,
5. This time the sub-menu will properly show the 2 options:
  a. `"Function"`
   b. `"Selection"`
and selecting any of these will have an effect in Snowman tab.

- When the defined function is selected you can see the 2 proper sub-menu items,
but if you selected anything outside the scope of the function, you'll only get
the `"Function"` as a sub-menu item.

**Comment by wk-952** [comment]
It seems that the default menu item was just changed from `"Selection"` to `"Function"`,
since pressing `Shift + F5` (which corresponds to `"Selection"`) will have the proper desired effect in Snowman tab.

**Comment by mrexodia** [comment]
There was no change in the default behavior as far as I know but everything
works again?

**Comment by wk-952** [comment]
Yes, if you selected a block of instructions and then pressed `Shift + F5`, everything will work as expected.

**Comment by mrexodia** [comment]
But there still is a bug with the menus. I will check it

**Comment by wk-952** [comment]
introduced on commit 087362d,
```
    decompileMenu->addAction(makeShortcutAction("Selection", SLOT(decompileSelectionSlot()), "ActionDecompileSelection"), [this](QMenu*)
    {
        return DbgFunctionGet(rvaToVa(getInitialSelection()), 0, 0);
    });
    decompileMenu->addAction(makeShortcutAction("Function", SLOT(decompileFunctionSlot()), "ActionDecompileFunction"));
```
should be swapped like this i guess:
```
    decompileMenu->addAction(makeShortcutAction("Selection", SLOT(decompileSelectionSlot()), "ActionDecompileSelection"));
    decompileMenu->addAction(makeShortcutAction("Function", SLOT(decompileFunctionSlot()), "ActionDecompileFunction"), [this](QMenu*)
    {
        return DbgFunctionGet(rvaToVa(getInitialSelection()), 0, 0);
    });
```

**Comment by mrexodia** [comment]
Yea I thought it was this already

**Comment by wk-952** [comment]
May i nag you on this ?
Seriously, it's just a swapped option in the GUI, so why the long wait,
or is there more to it than just that, like a real functionality issue or similar ?
