### ISSUE TITLE
Rare hang (not responding) issue when downloading symbols

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#462]
0. Make sure you don't have any symbols.
1. Debug any program that relies heavily on external modules,
as an example Adobe products.
2. Go to Symbols tab then right click on any module
and select `"Download symbols for all modules"`.
3. Try going to the CPU/disassembly tab .
4. Both, the debugger and the process being debugged will hang.

You'll have to wait for all the symbols to be downloaded before you can use the
debugger again.

**Comment by wk-952** [comment]
Another thing, if you searched for strings/patterns/calls, you also can't do anything (even closing the debugger) until it finishes (but at least switching to the CPU tab won't hang it),
so i guess it's just how the debugger works and not a _rare_ situation or anything.
Closing here since i guess it's useless/invalid.

**Comment by mrexodia** [comment]
the debugger shouldn't freeze when symbols are being downloaded..

Op za 19 dec. 2015 om 17:04 schreef wk <notifications@github.com>:

**Comment by Nukem9** [comment]
Probably a deadlock when using multiple `SafeSym*` functions.

**Comment by mrexodia** [comment]
Hahah yea thats possible

**Comment by mrexodia** [comment]
should have been resolved
