### ISSUE TITLE
Nearly all SW BPs become invalid on the next restart

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#463]
After this commit 8e34d10 , nearly all SW BPs get interpreted as invalid (old bytes mis-match),
and consequently they get disabled.

When i check the `.dd32` file, you seem to record only the first 2 bytes of the instruction
and the rest are `0xFFFF`, so i checked the first 2 bytes of the target instruction and it matched
the `oldbytes` value (also the application doesn't write itself at startup), but still the SW BP got disabled.

Example, consider this instruction:
`004F7A08   |   68 85 7A 4F 00   |   push 4F7A85`

its corresponding data in `.dd32` is:
```
{
            "address": "0xF7A08",
            "oldbytes": "0xFFFF8568",
            "enabled": true,
            "name": "",
            "type": 0,
            "titantype": "0x0",
}
```
the SW BP on this instruction will always be disabled.

- This issue of course doesn't apply to HW BPs.

__EDIT:__
log tab:
```
Breakpoint 004F7A0D has been disabled because the bytes don't match! Expected: 64 FF, Found: 64 FF
Breakpoint 004F7A10 has been disabled because the bytes don't match! Expected: 64 89, Found: 64 89
Breakpoint 004F7A1A has been disabled because the bytes don't match! Expected: E8 B5, Found: E8 B5
```
?!!!

**Comment by mrexodia** [comment]
Thats odd. I will look into it :)

**Comment by mrexodia** [comment]
should be fixed. old databases will be loaded correctly and then updated to have the correct value. please reopen if you still encouter the issue

**Comment by wk-952** [comment]
There is another problem here related to patched programs:

- Case 1:
1. Debug any program, then place a SW BP anywhere.
2. Change the instruction on which the BP is placed (so that the original bytes get changed).
3. Restart the application
4. The BP stays as it is (correct)

- Case 2 (placing a BP after patching):
1. Debug any program.
2. Change any instruction then place a SW BP on it.
3. Restart the application
4. The BP gets disabled (wrong).
This happens since of course the bytes after patching are the ones that get recorded,
so on the next restart (when all the patches are lost) the original bytes are read and compared
against the patch bytes ---> which will always be a mismatch.

Here's when it gets really annoying, assume you have the application __XXX.exe__,
you've placed some SW BPs on that application, then after that you made some patches,
and eventually saved it back to the file.
If you debugged the patched file, all your SW BPs will be disabled (case 2),

I know you did this to eliminate errors, for example in case the application structure changed
(because of a new version maybe) and the BPs become misplaced which will of course
cause exceptions, but what about this situation ?
Even if you recorded the original bytes before patching, the above-mentioned scenario
of debugging the patched file will also fail

**Comment by mrexodia** [comment]
Yea, I anticiated a report with this. Its the reason I didn't want to have
checks like this. What do you propose as a solution? Check for patches on
database save and restore the old patch bytes as the oldbytes parameter?

**Comment by wk-952** [comment]
Well, honestly i can't think of a proper solution,
but if you could do the following, it may suit all the situations:

-Solution 1:
1) First thing try not to record the patch bytes, instead record the original ones, because chances of debugging the patched file is less than that of debugging the original one.
(also if by mistake someone patched then added a BP, it will be disabled on the next restart)
2) When the application is loaded, check all the BPs and flag the mismatched ones,
if any mismatches found, then throw a warning to the user asking whether he likes to keep those
BPs or disable them.
- This way, at the end of the execution (when a stop signal is sent), there won't be any need
to check for bytes again i guess, and it will please everyone.
- You can then make an option in the `Misc.`tab in the preferences to ignore mismatches
by default, so it won't be annoying for people who know that the application structure is the same.

-Solution 2:
Just get rid of this check!

Seriously and no punning intended, was this needed ?!
if you already knew the bad consequences of this check, why did you implement it ?

**Comment by mrexodia** [comment]
The reason this check was added is because someone reported an issue with
breakpoints set after unpacking and then causing weird decryption errors
during unpacking because the 0xCC bytes were placed in the region that is
zero on start.

An option with this extra behavior of not recording patch bytes sounds like
a good idea. I will check it.

**Comment by wk-952** [comment]
Just out of complete curiosity, let's assume the decryption routine starts at address `18FE7`,
and the normal application execution should start at `32A00`, and this address along with a long
range underneath it are null at start-up, i.e. from `32A00` till `4FFFF` is simply a code cave.

I guess the following is what you thought of:
Take into consideration case 2, and assume the decryption starts by xor-ing this code cave for
example, and after the decryption routine has done its job, i've placed a SW BP @ `32A00`,
then we should expect correct results since the byte @ `32A00` was 0x00 during decryption.
And if the application is restarted, this BP will definitely be disabled since you'll be comparing
some value against 0x00, that sounds very ok, isn't it ?

Now take into consideration case 1, which means that i placed a SW BP @ `32A00` when it is a
null byte (before decryption), then we should expect wrong results since the byte @ `32A00`
was 0xCC during decryption.
And if the application is restarted, this BP won't be disabled since each time you're comparing
0x00 against itself (remember that the BP was placed before decryption).
__Conclusion:__ decryption will always fail in this scenario.

In this case, neither recording the original bytes (0x00) nor flaging the mismatches and throwing
a warning will work.
Also if you want to Check for patches on database save and store the patch bytes as the `oldbytes`
parameter, won't that make all SW BPs invalid since on the next restart (when patches are
discarded) you'll be comparing patch bytes against original bytes ? which is always a mismatch.

**Comment by mrexodia** [comment]
An (undocumented) option has been added:

```
[Engine]
IgnoreInconsistentBreakpoints=1
```
