### ISSUE TITLE
Jump arrows for register-based JMPs

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#470]
A GUI feature request. Instructions like `JMP RCX` or `JMP EAX` don't have jump arrows,
is it possible to implement them ?

**Comment by mrexodia** [comment]
Yes, it will be possible eventually.

**Comment by Herz3h** [comment]
Just added that to my branch, tested with a hand crafted (patched manually) jmp to a register and it worked, needs real testing

**Comment by mrexodia** [comment]
Yea, that's not a clean enough solution for me. Capstone needs to get a
register context and from there calculate the value directly.

**Comment by Herz3h** [comment]
Yeh that'd be better, will try to look at it tomorrow

**Comment by mrexodia** [comment]
No, I want to do that if you don't mind :)

**Comment by Herz3h** [comment]
sure as you wish
