### ISSUE TITLE
Wrong positioning of cursor of the search textbox

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#471]
1. Search for anything, i.e. strings, calls, comments, etc...
2. Select the search text-box then start typing.
3. The first 2 chars will be typed correctly,
but the imaginary cursor will decrease its position by 1, so if you continued typing the 2nd char
will always be at the end.
4. Press `ESC` then start typing again, this issue won't occur.

I mentioned this as a comment briefly here #418,
but since this is different, i thought it should have a separate issue.

**Comment by Herz3h** [comment]
Have you tried the latest dev snapshot ? It has a fix for this

**Comment by wk-952** [comment]
I tried 2 things, first using `snapshot_2015-12-20_05-03` and it has this issue,
then i manually compiled the project with the latest commit in the `development` branch and
it also has this issue too.

Are there any other snapshots/builds that i missed ?

**Comment by Herz3h** [comment]
Oh yeh actually i didn't click in the searchbox first before typing anything, so it didn't trigger the problem, will try to look at it now

**Comment by Herz3h** [comment]
Pushed a fix in my branch

**Comment by wk-952** [comment]
@Herz3h 
It's solved after your commit, thanks.
Just one last thing concerning the search textbox (not related to this issue),
could you please consider making it possible in the future so that highlighting a text then
pressing `Backspace`/`Delete` would actually delete it ?

**Comment by mrexodia** [comment]
@wk ctrl+backspace also clears the textbox, not very related but that's
just in case you wanna select all and delete.

**Comment by Herz3h** [comment]
Added that option too @wk-952

**Comment by wk-952** [comment]
Thank you, much appreciated.
