### ISSUE TITLE
error loading library "x32dbg.dll"

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#472]
new build snapshot_2015-12-24_09-47.7z have problem, error loading library "x32dbg.dll", i think missing some files.

**Comment by mrexodia** [comment]
Possibly, there were some build issues recently.

**Comment by wk-952** [comment]
also when building the project manually as `"Release|Win32"` you'll get this error:
```
error C3861: 'GetProcessDEPPolicy': identifier not found	\src\dbg\assemble.cpp	164	1	x64_dbg_dbg
```

**Comment by mrexodia** [comment]
Yes, I'm pushing a fix now. Ntversion was changed but it shouldn't have
because it breaks xp support

**Comment by mrexodia** [comment]
fixed
