### ISSUE TITLE
fix isInstructionPointingToExMemory

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#473]
`isInstructionPointingToExMemory` uses `DbgMemMap` and then iterates over the pages, it should directly use `memory.cpp` instead.

**Comment by mrexodia** [comment]
(.)Y(.)

**Comment by Nukem9** [comment]
tl;dr export `MemIsCodePage`

**Comment by mrexodia** [comment]
oh and there is also issues with when you assemble in ntdll, it tells me it's not executable even though my IP is in that region :+1:

**Comment by wk-952** [comment]
I guess there is a problem here:

instead of `sbb eax, eax`, i tried to assemble `xor eax, eax` and i got this message!
![err](https://cloud.githubusercontent.com/assets/11916365/12171289/4c83ef2a-b551-11e5-8e47-aa25f6dfb644.png)

using `snapshot_2016-01-07_01-41.7z`
