### ISSUE TITLE
Deselected patches are incorrectly ticked as enabled after selecting "Restore Selected"

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#474]
1. Debug any program.
2. Patch 2 locations (instructions), so that the distance between them is >=12 bytes, or simply the distance between them is large enough so that they're not grouped together.
3. Press `Ctrl + P` then deselect one of them (disable the patches) and keep the other.
4. Select the `Restore Selected` button.
5. The selected bytes will be restored normally,
but the previously-deselected ones will have their checkboxes ticked as if they're selected.

- Pic:
![err](https://cloud.githubusercontent.com/assets/11916365/12003310/be8a4928-ab21-11e5-9c2f-e497f5d9ea31.png)

- This is not introduced because of one of the new commits or anything,
it is a very very very old issue that's still there.
- To solve this, you have to deselect then select them again.
- Also the GUI incorrectly shows the original bytes (that are incorrectly ticked in the patches window)
as red ones as if they're patched. (so, could i assume that bytes coloring depends on the tick-box ?)
- This issue shines (becomes annoying) when you're doing a lot of patches (really a lot)
that are not near each other (not grouped), so when they're incorrectly ticked you have to
deselect and select them again one by one for them to become active/effective again.

**Comment by mrexodia** [comment]
The gui also shows restored patches in red at this moment (to distinguish
from non-patched bytes). I'll look into the issue and see if I can fix it :)

**Comment by mrexodia** [comment]
should be fixed now (the bug part), the deleted patches are still red, but I might change that later so they are green/another colour instead.

**Comment by mrexodia** [comment]
now there are different colours for unchecked (effectively disabled) and checked patches

**Comment by wk-952** [comment]
Totally forgot how the coloring works, sorry.

1. Do the steps from 1) till 4) again.
2. The previously-deselected bytes won't be ticked (yaay!) 
3. Now close the patches window and re-open it again, guess what happens :smile: 

Merry Christmas to you btw and everyone here.

**Comment by mrexodia** [comment]
Ah yea, I just noticed how stupid I was :D now I found the real issue...
Merry Christmas!

**Comment by mrexodia** [comment]
Alright, should be fully fixed now!

**Comment by wk-952** [comment]
any chance you would add this coloring option to the dump window ?
![paint](https://cloud.githubusercontent.com/assets/11916365/12051953/ba683946-af12-11e5-8253-2874db114d31.png)
