### ISSUE TITLE
Log tab completely spammed with bytes changes

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#484]
![log_spammed](https://cloud.githubusercontent.com/assets/11916365/12055474/4b933cae-af36-11e5-9f62-4ac8e68750f1.png)

currently when selecting the patched instructions, the changes are mentioned in the log tab
immediately, so 3 or 4 single-clicks on one patched instruction would result is this mess.
Got any better ideas instead of this ?

**Comment by mrexodia** [comment]
oh lol, it was a debug think i forgot to remove :smile:

**Comment by mrexodia** [comment]
should be resolved now
