### ISSUE TITLE
Performance penalty when right-clicking in calls references 

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#485]
1. Debug any program and search for intermodular calls (preferably in the whole module).
2. When the search is finished, right click on any call instruction that is not pointing
to a windows API, i.e. don't right click instructions like: `call dword ptr ds:[<&GetStartupInfoA>]`
but rather calls like this: `call <XYZ.sub_438C00>`
3. You'll wait around 3-4 seconds before the menu appears, and the CPU usage
in the task manager could reach up to 22% on a hyper-threaded dual core processor.

- Not an issue though nor an annoying thing, but just as a reminder in case you'd like
to add this to your enhancements list.

**Comment by mrexodia** [comment]
kinda weird, for me right clicking is instant on everything. you found a bug though. the calls to `sub_` should not be listed because they are not cross-module :smile:

**Comment by wk-952** [comment]
Have you tried it on a single or dual core CPU ?
Windows API calls are instantaneous, but for example extremely long call names like this
(call to `apphelp.dll`):
`call dword ptr ds:[<&unsigned int __stdcall DWM8AND16BitHook_GetPaletteEntries(struct HPALETTE__ *,unsigned int,unsigned int,struct tagPALETTEENTRY *)>]`
would trigger this issue easily.

This seems to happen when `Undecorate Symbol Names` is selected,
when i deselected this option it took nearly no time.

On the other hand, yea `sub_xxx` labels created when defining functions `Shift + F` are
listed too, thought that's a new feature xD

**Comment by wk-952** [comment]
Not valid anymore.
