### ISSUE TITLE
Analysis in details window

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#491]
![anls](https://cloud.githubusercontent.com/assets/11916365/12088104/017f03c4-b2e1-11e5-82f3-0f887f47a261.png)

useless enhancement for more laziness :+1: , so it's easier to look for strings.
Feel free to close here immediately if it's just a waste of time.

__EDIT:__ seems to be working on registers (not sure though)
![wrk_anls](https://cloud.githubusercontent.com/assets/11916365/12088472/47096c24-b2e4-11e5-926b-27b9f4c02297.png)

**Comment by mrexodia** [comment]
Hey, is this a video or an image? I cannot view it on mobile. Could you
describe the enhancement in words briefly?

**Comment by wk-952** [comment]
Yea sure, the qword memory address `1402ED1C0` contains the unicode string `Key`,
this string is properly displayed by the analysis in the comments section but in the details
window it's not, so my suggestion was if you could implement this analysis in the details window.

Oddly in the second pic. when RAX and RBX were pointing to address `2FF870` which
contains the unicode string `555asdzxc#!@#`, the analysis in the comments section
as expected displayed it correctly, but also in the details window.

So now i'm not sure if the analysis in the details window is analyzing addresses in registers
only or it is it analyzing all addresses but for some weird reason it didn't do that in the 1st pic.

**Comment by wk-952** [comment]
Oh never mind i'm dumb :+1: 
Found my mistake.

**Comment by mrexodia** [comment]
so what was the mistake? i didnt quite get it :D

**Comment by wk-952** [comment]
The address `1402ED1CO` contains the bytes `790065004B` (corresponds to unicode  `K.e.y`), so the analysis displayed this in the comments section:
`1402ED1CO`:L"Key"`
but the analysis in the details window displayed this:
`qword [1402ED1CO]=790065004B` (no mention of `L"Key"`)
so I was asking if you could implement analysis in the details windows, but I totally forgot that the analysis is done on the result of the ptr as if it's an address itself, i.e. `790065004B`
and since those bytes are not the address of anything, nothing should be displayed.
