### ISSUE TITLE
Icons are too small in 4k display

### ISSUE THREAD

**Issue by holdsworth** [x64dbg/x64dbg#492]
using an Alienware 15 R2

![image](https://cloud.githubusercontent.com/assets/3804774/12098091/9acad462-b328-11e5-8720-32c7ca76df90.png)

**Comment by holdsworth** [comment]
Windows 10 Professional 64-bit

**Comment by Nukem9** [comment]
While this is a bug, this is still pretty funny. #454 is related.

@mrexodia it seems like Qt4 doesn't have any support for Hi-DPI resolutions. `QT_DEVICE_PIXEL_RATIO` might be a workaround.

(Similar issue, different project)
https://bugs.launchpad.net/stellarium/+bug/1372781/comments/10
```final: Qt 5.3 has initial support of 4K monitors. I guess Qt 5.4 and, better, Qt 5.5 has more good support of 4K monitors.
Apparently you need build Stellarium from source code with Qt 5.4.1 or Qt 5.5.```

**Comment by mrexodia** [comment]
Great so we have an incentive to go to Qt 5. I would suggest waiting for
5.6.0 and also until stuff is more stable.

**Comment by holdsworth** [comment]
@mrexodia so what should I do in the meanwhile? I can't use x64dbg :(

**Comment by mrexodia** [comment]
Set your resolution to 1080p? Fix the issue? I don't know. For me it is
kind of low priority because I don't have a 4k monitor to reproduce the bug
or test a potential fix on.

You could also try compiling with qt 5.4 or whatever version has a fix for
this. Make sure to disable snowman first though.

**Comment by holdsworth** [comment]
I tried setting it to 1080p, I think it is about DPI and not about the pixels, I will try although I am not familiar with the source code at all

**Comment by mrexodia** [comment]
There is a guide available on the wiki. It should be pretty straightforward
to compile with a different qt version. Maybe someone with qt 5 installed
can provide you with a build (nukem?)

For disabling snowman, comment it out here
https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/MainWindow.cpp
(somewhere in the constructor).

**Comment by alexmaloteaux** [comment]
hi @mrexodia  whi is it required to disable snowman ?

**Comment by mrexodia** [comment]
If you want to compile snowman with qt 5 you don't have to, but compiling
snowman is a pain in the ass.
