### ISSUE TITLE
Export Symbols disappeared for some modules

### ISSUE THREAD

**Issue by TomSie** [x64dbg/x64dbg#496]
Hey,

i am currently using x64dbg's latest debug build (Jenkins #305).

In that build it seems as if for some dlls no "Export" Symbols are listed in the Symbols section.

How to reproduce: 
- Download latest build.
- Start x64dbg
- Open x64dbg.exe
- Go to Symbols
- Click on user32.dll

On my system there are only "Import" Symbols - not a single "Export" Symbol.

I observed the same phenomenon for other dlls such as ws2_32.dll, and libssl32.dll. Some dlls, however, such as kernel32.dll seem to show their "Export" symbols.

Any Idea, why that happens?

**Comment by mrexodia** [comment]
I have no clue. Here everything appears to be working just fine.

**Comment by TomSie** [comment]
My setup: 
- Windows 7 Virtual Machine. 
- I downloaded the "bin" folder from Jenkins and started x64dbg.exe directly. 
- I did not download symbols from Microsoft.

Here is a sreenshot of by screen: 
![bug](https://cloud.githubusercontent.com/assets/16607413/12197317/3088175a-b606-11e5-8e7e-faef7e95079b.png)

**Comment by mrexodia** [comment]
yep, symbol shit is utterly broken on for me too. I was looking at x32 (which is looks like it's working but it actually isn't).

**Comment by mrexodia** [comment]
The code in `symbolinfo.cpp` is **not** working from what I can tell. The best solution would be to build a fully custom symbol engine and then simply dump all the symbols from dbghelp in there on module load (or on request by the user). This would also enable stuff like DWARF support.

**Comment by TomSie** [comment]
Keep up the good work. You guys are amazing :)

**Comment by isodota** [comment]
This bug is extremely annoying, I stopped using this debugger because of that.

x32dbg - Win8.1 clean install.

**Comment by isodota** [comment]
@mrexodia You should reattach the bug label.

**Comment by mrexodia** [comment]
I'm aware of the issue, but my PC is broken right now so I can't do much.

**Comment by isodota** [comment]
@mrexodia 

goto->expression and manually inserting the address of an exported function,
function is identified correctly.

example:

- _75986B65_ exported function found with CheatEngine

- **goto->expression**: _75986B65_ gives **Correct Expression! ->** _ws2_32.WSARecv_

**Comment by mrexodia** [comment]
I know. The symbol thing was rewritten some time ago.

**Comment by mrexodia** [comment]
Lol I didn't finish that email somehow. The goto dialog exports resolving
is completely separate from the symbol view. It might be some problem with
dbghelp or something.

**Comment by mrexodia** [comment]
This is assumed to be resolved now. Please test again and respond if it's still broken.
