### ISSUE TITLE
Ability to force-terminate the debugger and generate dump file

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#499]
In some situations the debugger hangs, and when you press the close button
it won't terminate, eventually you'll be looking at the message `"Closing Debugger..."`
and the log output area at the very bottom will have the message `"Cleaning wait objects..."`,
and of course it can only be closed from the task manager.
Add to that in most of these situations the database file is completely deleted.

Could you please implement an ability to force-terminate the debugger, but that option would
generate the minidump files as it would do it the normal crash scenarios ?

The problem is, in that specific scenario no dump files are generated and i don't get the option
to debug x64dbg itself to copy the callstack table or to provide you with any useful information.

*(off-topic): could you also please make the debugger generate a backup of the db file
that would get written on a successful termination ?

**Comment by Nukem9** [comment]
mrexodia:
Should x64dbg create a `dbname.dd32.bak` as a copy of the database before loading it in `DbLoad()`?
As far as the hanging part.......some kind of timeout could throw an exception after X seconds. Won't be necessary if the root cause is found.

wk-952:
Task manager should allow you to create a dump file, though I don't know if it's present in all windows versions. (The DMP from here should be kept/uploaded privately).
![image](https://cloud.githubusercontent.com/assets/4228359/12227506/a34c721c-b7fb-11e5-8a44-92f86d231cea.png)

**Comment by mrexodia** [comment]
yea, it should make a bak* thing with `DbLoad`

**Comment by wk-952** [comment]
So when the debugger hangs and can't be closed normally, all i have to do is generate a dump file from the taskmanager right ?

@mrexodia as Nukem said, they should be uploaded privately, so could i just send you those dumps directly to your e-mail, or is there anywhere else to upload them privately ?

**Comment by wk-952** [comment]
@mrexodia i would appreciate any response from you to the above 2 questions please.

**Comment by mrexodia** [comment]
Eh yeah sure I wasn't paying attention when this originally happened. Will
check it out.

**Comment by mrexodia** [comment]
Just a quick note, you can save the database if the command thread is not hanging with the `dbsave` command.

**Comment by wk-952** [comment]
Yeah sure of course, from time to time while debugging i invoke the `dbsave` command.
What i meant in the very first post is that the debugger will sometimes becomes completely unresponsive (you can't do anything except closing it from TaskManager).

So i was asking whether you can somehow make a thread (running in the background for example) that has one and only one purpose; if the debugger stayed in the hanging state for a certain period of time, it would throw a message to the user asking him whether he wants to generate minidump files with the necessary info and close the debugger, or not.

A very close example to what am i talking about is in Cheat Engine, let's say you did an initial scan of type `unknown initial value` and you got millions of results, then to refine those results you searched for the 2nd time for `unchanged value`, if you attempted to cancel this 2nd scan, Cheat Engine may hang and becomes unresponsive.
At this point you get an option to force terminate the scan process so that Cheat Engine becomes responsive again.

**Comment by mrexodia** [comment]
Hm right, it is very hard to detect this kind of unresponsiveness though.
There are many threads involved but if anybody has ideas I'm all ears!

Op di 12 jul. 2016 om 16:26 schreef wk <notifications@github.com>:
