### ISSUE TITLE
Add more menus with favourite tools

### ISSUE THREAD

**Issue by aimtsou** [x64dbg/x64dbg#500]
It would be nice if somewhere in the options we could specify a path or many paths with our selected tools and then to get a new entry into the menu or in the toolbar as a button.

**Comment by Nukem9** [comment]
The idea is alright, but what is the purpose? Why not just use a launcher program or the Windows taskbar shortcuts?

**Comment by mrexodia** [comment]
Nukem too easy thinking :D

**Comment by mrexodia** [comment]
might be a good idea to start a tool with the current debuggee as argument.

**Comment by torusrxxx** [comment]
Progress have been made on this.
