### ISSUE TITLE
Remove the read-only flag from the patched file before applying the patches

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#502]
Little enhancement request, assume you're debugging a file on a CD/DVD,
after applying the required patches, you won't be able to save the patches to 
a file on your hard disk since the patched file will have the same attributes (read-only),
so the debugger - after copying the original file to the specified location - will attempt to
write to a read-only file.

pic:
![err](https://cloud.githubusercontent.com/assets/11916365/12269459/2757ccdc-b95a-11e5-8195-718eddea90b4.png)

**Comment by Nukem9** [comment]
Untested - I'm too lazy right now.

**Comment by wk-952** [comment]
It works very fine!, thanks
