### ISSUE TITLE
Thread sorting partially broken

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#503]
1
10
100
....

![image](https://cloud.githubusercontent.com/assets/4228359/12276872/3e1500ca-b946-11e5-8e75-a0cb9af97e96.png)

**Comment by mrexodia** [comment]
Its not a real bug, sorting is on alphabet

**Comment by farmdve** [comment]
LOL? Alphabet != number. All IDs are integers represented in hex.

**Comment by mrexodia** [comment]
Yea maybe there should be number sorting though.

**Comment by mrexodia** [comment]
shouldn't be too hard, however requires a flag `bSortOnNumbers` that interprets the data and sorts that way.
