### ISSUE TITLE
Opening Visual Basic Programs causes an Invalid Pe

### ISSUE THREAD

**Issue by aimtsou** [x64dbg/x64dbg#504]
I have 2 samples that are using Visual basic and X32Dbg cannot open them. Both of them report:

Initialization successful!
Database file: C:\Users\user\AppData\Local\Temp\Rar$EXa0.042\release\x32\db\xxx.exe.dd32
Error starting process (invalid pe?)!

**Comment by mrexodia** [comment]
This means windows could not start the file (CreateProcess failed).
Probably your antivirus triggered or something.

**Comment by mrexodia** [comment]
Oh what version are you on by the way? I changed that message.

**Comment by aimtsou** [comment]
Version Compiled on 3 of January, Windows 7 SP1, no antivirus

**Comment by mrexodia** [comment]
Well, if Windows fails on CreateProcess I cannot do anything. This message is **not related** to the file being a 'valid pe'. It just means that x64dbg cannot start the process (meaning it will also throw an error message when you try to start it from the explorer). If you still believe this is an error, reopen the issue and also attach the file.

**Comment by aimtsou** [comment]
No program starts fine from explorer, so I guess it should be on debugger.

**Comment by mrexodia** [comment]
Good for you. Where is the executable?
