### ISSUE TITLE
Dump window doesn't show 2bytes unicode strings

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#507]
1) Put in memory bytes 34 78 e3 89 ff 52 d5 8b
2) Unicode view doesn't recognize strings in this bytes 
As 2 byte unicode chars bytes combined in 7834 89e3 52ff 8bd5
And this is text in Chinese  破解勿试
It would be great to get support for such 2byte strings

**Comment by mrexodia** [comment]
Yea, only extended ascii is supported. You can try by disabling a check in
disasm_helper.cpp but it will not look pretty (everything will be
recognized as a unicode string).

**Comment by mrexodia** [comment]
should be fixed now
