### ISSUE TITLE
vmx instruction "invept" does not appear in disassembly view

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#508]
vmx instruction "invept eax, [eax]" does not appear in cpu view but correctly parsed to "66 0F 38 80 00" in manual assembly mode and even in lower subpanel we can see references to EAX as opcode №1 - r32 and opcode №2 - memory128

**Comment by lupier** [comment]
offtopic: funny fact - ida pro 6.1 can't handle "invept  eax, [eax]" in patch (assemble) mode

**Comment by Nukem9** [comment]
Probably something to do with capstone directly. VMX instructions are relatively "unused" and they don't always check all ring0 ones.

Same for IDA 6.1 afaik.

**Comment by mrexodia** [comment]
don't know what version you're on, but the latest snapshot appears to be working fine:

![img](http://i.imgur.com/yJDacCt.png)
