### ISSUE TITLE
Unable to follow the automatic label EntryPoint in the expression window

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#511]
1. Load any application in debugger and wait until it breaks at its entry point.
2. Press `Ctrl + G` and type `EntryPoint`
3. You'll get an "invalid expression" error message

**Comment by mrexodia** [comment]
It is not a label. Try ":EntryPoint" or "module:EntryPoint"

**Comment by mrexodia** [comment]
The reason for this is that labels are global so `EntryPoint` wouldn't resolve to one location.
