### ISSUE TITLE
??? (GetFileNameFromHandle failed!) in MemoryTab

### ISSUE THREAD

**Issue by Djamana** [x64dbg/x64dbg#514]
That's how it look like:
![Image of MemoryTab with GetFileNameFromHandle Error](http://imagizer.imageshack.com/img911/5254/mto9Xn.png)

Happens when I attach to some of the processes[tabs] created by opera.exe.
Guess that has to do with the limitations that have assigned to these sandbox 'satellite' processes by the job object assigned to them since on the 'main' opera.exe the Pageinformation column in X32DBG's MemoryTab is okay.
That's the job:
![JobObject](http://imagizer.imageshack.com/img907/4082/f4M7Z3.png)

Well this is not really a bug, 
But maybe during development of X64DBG you get idea's for some workaround / nice fallback case if GetFileNameFromHandle fails.
Memory access still works.
Some not very sophisticated way that comes to my mind would be
to maybe check if it's a PE-image and use it's sections name + make the way to it's exports-table and get the *.dll Name from there.

**Comment by mrexodia** [comment]
Are you executing opera.exe from a network location? And what version of x64dbg are you using? Could you give me a link to the opera version you are using? Thanks.

**Comment by Djamana** [comment]
It's Opera 34 (32-bit) on some Win7 64-bit. I'm run it locally from the harddisk.(No netshare....)
X32DBG v25 (jan 2016)
How I guess (but haven't tried it) Google chrome will show the same behavior. So you may not need installed opera to reproduce this thing(Hmm it's not really a bug).

**Comment by Nukem9** [comment]
x64dbg vs process hacker

`apisetschema.dll` silenty fails:
![image](https://cloud.githubusercontent.com/assets/4228359/12657127/c7f6220c-c5cf-11e5-84ed-509881ab54f6.png)
![image](https://cloud.githubusercontent.com/assets/4228359/12657134/cf105a9e-c5cf-11e5-827b-9d1d880bb258.png)

Randomly mapped (`MAP`) dlls work:
![image](https://cloud.githubusercontent.com/assets/4228359/12657196/139b4dea-c5d0-11e5-8a04-3bc0965157f7.png)
![image](https://cloud.githubusercontent.com/assets/4228359/12657201/19246e2c-c5d0-11e5-8a85-3bb2b8e21661.png)

Every other `IMG` map besides `opera.exe` fails:
![image](https://cloud.githubusercontent.com/assets/4228359/12657255/6f70b3ee-c5d0-11e5-9669-4a58cf20f7c6.png)
![image](https://cloud.githubusercontent.com/assets/4228359/12657236/4e488552-c5d0-11e5-8ac5-bfd29a1fe2da.png)

Notice that some of the memory protection constants are also broken. I have no idea what's going on.

**Comment by mrexodia** [comment]
golden! bugs

**Comment by mrexodia** [comment]
Okay I finally managed to reproduce this, the reason is that `hFile` is NULL so it's not unexpected that getting the filename fails...
