### ISSUE TITLE
Calculation in Commandbar like softice

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#517]
A Calculation in commandbar like softice
ex: ? 5F xor 5E maybe its a stupid idea if so delete this feature request ;)

**Comment by Nukem9** [comment]
![image](https://cloud.githubusercontent.com/assets/4228359/12666822/30d0c5b0-c612-11e5-9c60-35b78631b5a0.png)

???

**Comment by Chandlr** [comment]
Ah cool its already in :)
