### ISSUE TITLE
different hardware breakpoints view

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#519]
small view of hardware breakpoints since there is a limited number anyway.

**Comment by mrexodia** [comment]
shouldn't be rocket science to implement.

**Comment by aimtsou** [comment]
Just leaving the idea of the implementation i pmed you for reference.
Toolbar should have option to enable or disable and maybe it should be draggable.
It should contain a field for the address and 3 small buttons with set, follow, delete as S,F,D
(maybe disable also)

**Comment by torusrxxx** [comment]
The breakpoints view can be detached to become a small window.
