### ISSUE TITLE
fix the stack view

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#520]
currently the stack view is utterly shit with navigation, it needs things like follow stack in dump X etc.

**Comment by blaquee** [comment]
this should be closed now.

**Comment by mrexodia** [comment]
Isn't there any others useful features to implement in the stack view? What
about push / pop?

**Comment by mrexodia** [comment]
I gotta check myself but I'm on mobile. Is there both follow in dump for
the currently selected stack address (show stack data in dump) and follow
in dump for the pointer?

**Comment by blaquee** [comment]
are you saying to follow the address pointed to by the value on the stack? is this something we care to add? once could follow the address in the dump if they wanted too.

**Comment by blaquee** [comment]
if anything we could make this issue more specific to "Add follow in dump" for stack view and add more issues for other enhancements?

**Comment by mrexodia** [comment]
Hm I don't know. I will check it later...
