### ISSUE TITLE
Wrong view for cmp asm command (0x82 opcode)

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#522]
Wrong view in picture. Latest snapshot
![67b9e706ccbf903cc269d553291bc421](https://cloud.githubusercontent.com/assets/1623540/12759913/d3ef6d56-c9f4-11e5-81d2-a0ca58bb83c6.png)

**Comment by Nukem9** [comment]
I don't know what you are talking about. As far as I know 0x82 is not a valid starting opcode for any instruction.

**Comment by lupier** [comment]
At least this with 82 can start few commands: ADD, OR, ADC, SBB, AND, SUB, XOR, CMP
Please check
http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf
page 1515, table A-6

**Comment by Nukem9** [comment]
I've seen a few typos/incorrect entries in Intel's manuals. None of the specific instruction tables match:
```
(pages)
add  95
or   701
adc  90
sbb  1036
and  121
sub  1085
xor  1271
cmp  209
```

I see 0x80/0x81/0x83 but not 0x82.... Unless I'm blind, google doesn't show anything either.

Does it execute? If you press F7 and single-step, does it work?

**Comment by lupier** [comment]
Yes, it work as expected in single step. Also ida pro, ollydbg v1 and v2 show 0x82 op. in normal way.

**Comment by mrexodia** [comment]
http://onlinedisassembler.com also tells me it's an invalid instruction.

**Comment by lupier** [comment]
For example: just try instuction via opcodes 82 3D 01 00 40 00 5A
![2](https://cloud.githubusercontent.com/assets/1623540/12768787/4428bb94-ca23-11e5-981c-e10a7d4bb6ac.png)

It will work as expected, and compare 'Z' from 'MZ' sign in some classic 0x400000 image based exe

**Comment by Aut0matA** [comment]
82 used to be valid, not sure if it is still or not. Also lit isn't valid in 64 bit mode as far as I know, but long answer short, it should be valid. I had a similar problem with the view when i would scroll after a breakpoints on occasion, but after I updated x64dbg the issue went away so I didn't submit it as a bug. What release are you using?

**Comment by Aut0matA** [comment]
just did a quick search, see here -> https://github.com/aquynh/capstone/issues/238 may be an issue with capstone

**Comment by mrexodia** [comment]
@Aut0matA: I will soon update capstone to the next branch. Hopefully that
solves the issue :)

**Comment by Nukem9** [comment]
Fixed with the newest capstone version. 
![image](https://cloud.githubusercontent.com/assets/4228359/13036583/201cc08c-d339-11e5-8113-cd5243c04e82.png)
