### ISSUE TITLE
Does x64dbg make entries in registry or create files in system directories?

### ISSUE THREAD

**Issue by darkred** [x64dbg/x64dbg#524]
I want to try x64dbg (in win10 x64) 
but I have a question *(for which I couldn't find any info in the site or in the wiki page)*:

after I download+extract the [latest snapshot](https://github.com/x64dbg/x64dbg/releases), and run `release\x64\x64dbg.exe` 
will it make any entries in registry or create files in system directories?
*(I won't run `x96dbg.exe` that creates a `Debug with x64dbg` entry in file explorer context menu)*
Or it's portable (like ollydbg)?

**Comment by Nukem9** [comment]
Everything, including config, is written to disk under the x64dbg folder. It should all be portable except for `x96dbg.exe`.

**Comment by mrexodia** [comment]
Unlike OllyDbg, x64dbg is fully portable (all paths are relative to the
x64dbg executables and in Olly you have absolute plugin and UDD paths).
This means you can copy you x64dbg.ini anywhere without having to change
anything.

Per default x64dbg will not create any registry entries. However if you use
it as a JIT debugger it will change that key. Same (as you mentioned) for
x96dbg.

**Comment by darkred** [comment]
Thanks both for tour answers. So, I added this in the [Wiki|FAQ](https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions)
