### ISSUE TITLE
Issue when opening file open window

### ISSUE THREAD

**Issue by Pr00bit** [x64dbg/x64dbg#525]
hello,

windows 8
- using snapshot_2016-01-25_01-04 
- trying to run x64dbg.exe
- when I go to file >> open below error appears

![przechwytywanie](https://cloud.githubusercontent.com/assets/17089041/12865890/7d25bf5c-ccba-11e5-923c-cc5f683fcdbf.PNG)

**Comment by mrfearless** [comment]
I downloaded the snapshot and tried the same - file->open, and x64dbg.exe does crash for me as well. It seems to have created the minidump folder and filled it with dump files.
x32dbg.exe seems to work fine. 
I then checked the version i had installed (in another location) and the x64dbg.exe from Jan 19th also crashes and fills the mindump folder with dump files

![Minidump folder](http://postimg.org/image/xvt5kx52d/)

**Comment by mrfearless** [comment]
I done some searching and think this might related to an issue with QFileDialog getopenfilename with windows 7 x64, i tried disabling all shell extensions with nirsoft's ShellExView, just to be sure its not an issue with a shell extension, but still same issue with x64dbg.exe. I might try it in a bare bones vm of win7 x64, see if it helps me figure out if its to do with some software installed on my machine.

**Comment by Nukem9** [comment]
It's not so much a bug....rather it's a regular C++ exception (`throw`) being caught by my handler instead of the runtime dll. I'll swap `AddVectoredExceptionHandler` for `SetUnhandledExceptionHandler`, which should fix it.

\*note for later: might not work on certain machines

**Comment by mrfearless** [comment]
I take it that the might not work on certain machines is related to this: Exceptions that are thrown from an application that runs in a 64-bit version of Windows are ignored (https://support.microsoft.com/en-gb/kb/976038)

**Comment by Nukem9** [comment]
Added code which should \*hopefully\* work around that bug.

Meanwhile at Microsoft:
```
Restart requirement

You must restart the computer after you apply this hotfix.
```

**Comment by mrfearless** [comment]
Pr00bit, I compiled the latest development release last night from Nukem9's commit and checked the file open on x64dbg.exe - it is working. The latest snapshot has this fix: https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2016-02-16_10-56.7z

**Comment by Pr00bit** [comment]
mrfearless - it is working now :)

Thanks a lot for your assistance

**Comment by SHH600725** [comment]
Hello all.  I'm having the same issue as OP.  x64dbg also doesn't show many comments (including "Entry Point") in the comment pane.

System:
 - x64 Win7 VM w/ FLARE-VM (has VC++2015-2022 and other redistributables installed).
 - x64dbg from 2022-05-18 (also same behavior when an older version: 2020-01-21 via sourceforge), no plugins installed.
Disabled TLS Callbacks and enabled 00000000-ffffffff exceptions.

Behavior:
 - ["Mexican flag" exercise program](https://crackmes.one/crackme/5d63011533c5d46f00e2c305) works fine.
 - Another [sample program](https://crackmes.one/crackme/5e45850133c5d4439bb2db3f) written in VC++ 2017 has the same issues as the video above though: Program runs. Entrypoint, comments, and strings don't display in the debugger window like in the video.  Module name is not displayed.  "Search for >" only shows "Current region" and "All modules (doesn't have "in current module" as an option).  Searching for strings in current region shows the badmessage, but double-clicking on it causes the dump window background to flash red (like the vid above).  Searching for strings in all modules crashes the program. Searching for strings in current region, right-clicking and selecting "Follow disassembler" works though.  Same behavior whether running as admin or not.
 - On my regular Win10 laptop: Everything works fine.

A video of another user running FLARE-VM w/ Win7 w/ x64dbg shows things working ok.  Not sure what might be different in my setup and OP's than a standard Windows setup.

Thank you for your time :)

**Comment by SHH600725** [comment]
Using [snapshot_2016-02-16_10-56.7z](https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2016-02-16_10-56.7z/download) does work, though Module: says "???" on Win7 x64.  I'll see if I can bisect releases later.
