### ISSUE TITLE
x64dbg  not loading after windows 10 updates

### ISSUE THREAD

**Issue by dooley71** [x64dbg/x64dbg#529]
I recently bagan getting an error when trying to start x64dbg in windows 10. It was working fine up until about one month ago. The original error was a msvcr120.dll is missing error then it changed to:

"The application was unable to start correctly (0x000007b). Click OK to close the application."

The second error started when I tried to load the latest MS visual C++ updates to resolve the dll error.

Any help would be much appreciated.

Thanks

**Comment by mrexodia** [comment]
I have no idea what could cause this error. I'm working on Windows 8.1
myself, maybe @Nukem9 has any idea what's going on here...

**Comment by dooley71** [comment]
Also, for additional info, the 32bit version (x32dbg) is working fine.

**Comment by mrfearless** [comment]
Im guessing its related to the Visual C++ Runtimes. Probably need to re-download and re-install them: Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 (VC++ 12.0) https://www.microsoft.com/en-us/download/details.aspx?id=40784

It should come with both 32 and 64bit versions, both need to be installed if your on a 64bit os and are going to use x64dbg.exe (and/or the 32bit version for x32dbg.exe, which you say is working anyhow)

Only other link i found that is kindof related is this one (referring to older vc++ runtimes), but the method to install is still valid, and you might have to try this approach if your vc++12 (= vs2013) runtimes they arent installed correctly: http://www.bitdefender.com/support/how-to-solve-error-message-%22the-application-was-unable-to-start-correctly-%280x000007b%29-click-ok-to-close-the-application%22-1106.html

**Comment by dooley71** [comment]
Thanks for the input. I will give it a try and report back so others can benefit.

**Comment by dooley71** [comment]
Good news! I tried mrfearless' suggestions of re-installing the C++ runtime packages and x64dbg is now working again. I actually tried just repairing them with the install package and that did not work, so I unistalled both packages and reinstalled them and the problem went away.

Not sure how it worked but I will take it.

Thank you mrfearless and mrexodia for your help.

**Comment by mrexodia** [comment]
Glad to hear your issue is solved! Feel free to close the issue.
