### ISSUE TITLE
pass exception to program or swallow shortcut

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#53]
already possible in the API, now it needs a simple shortcut. default is pass to program.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/53
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:02:15.998

**Comment by mrexodia** [comment]
implemented as 'Debug -> Skip next instruction (Ctrl+F8)'
