### ISSUE TITLE
TODO list?

### ISSUE THREAD

**Issue by mat0thew** [x64dbg/x64dbg#531]
Hello, im dont dinf TODO list. help me to find it :lollipop:

**Comment by mrexodia** [comment]
There is a notes tab, is this what you mean? Or are you talking about a
roadmap for development?

**Comment by mat0thew** [comment]
@mrexodia  in the sense of the priorities of the project, fixes, innovations

**Comment by mat0thew** [comment]
OOPS. Labels )
