### ISSUE TITLE
Decompiler crash/error

### ISSUE THREAD

**Issue by vgturtle127** [x64dbg/x64dbg#532]
So I was experimenting with debugging/disassembling/decompiling my hello world application, and I decided I would just try to decompile the entire application. I selected from the first line to the last line (the line before the ???) and I right-clicked and hit decompile.

After about 15 minutes of dataflow analysis, the debugger then spits an error out every second or so, and doesn't stop. The only way to make it stop is to terminate all the processes involved (debugger, the application you were debugging, and any related windows).

It is always toward the end that it crashes, and it seems random.

Here is the source to the application I am using:

```

#include<stdio.h>

int main() {
	printf("Hello World!\n");
	return 0;
}
```

Tell me what other info I can give you guys and I will do my best to help.

**Comment by mrexodia** [comment]
not sure if you're on the latest snapshot but if you aren't try to update. otherwise go to the snowman repository yegord/snowman and file a bug report there :)

**Comment by vgturtle127** [comment]
@mrexodia I was using the latest snapshot, but thanks, I didn't realize it was a separate project. :blush:

**Comment by nihilus** [comment]
@mrexodia: Hush, don't send him to me plz ;-)

**Comment by vgturtle127** [comment]
@nihilus :laughing:
