### ISSUE TITLE
Allow x96dbg to make shortcuts on the desktop

### ISSUE THREAD

**Issue by idzireit** [x64dbg/x64dbg#538]
When I try to run the main interface it asks if I want to register a shell extension.  I have had to manually put shortcuts on my desktop for both the 64 and 32 bit versions of x64dbg.  

I have the latest version of x64dbg v25 compiled February 15, 2016   05:08:22
I am running windows 7 SP 1

**Comment by mrexodia** [comment]
Yes you do, x96dbg.exe doesnt create shortcuts it just registers a shell
extension (right click menu).

**Comment by mrexodia** [comment]
Keeping this issue open as a reference

**Comment by mrexodia** [comment]
similar to the shell extension, ask the user Yes/No for desktop shortcuts

**Comment by mrfearless** [comment]
Also if you adding in this to the x96dbg.exe, maybe also add in an Icon string under the 'Debug With x64dbg' shell command:

exefile->shell->Debug with x64dbg
Icon REG_SZ "M:\x64dbg\x96dbg.exe",0

Which is like this in regedit:
![x96dbg.exe registry settings for icon](http://s15.postimg.org/kngo9ytm3/x96dbg_regicon.png)

Then when a user right clicks on an exe or dll in explorer they see the x96dbg icon in the menu item:

![x96dbg.exe right click menu in explorer](http://s23.postimg.org/jlixs2y23/x96shellicon.png)

**Comment by mrexodia** [comment]
Yeah, that's a good idea!

**Comment by blaquee** [comment]
Icon added in PR #552

**Comment by vgturtle127** [comment]
@mrfearless @mrexodia Awesome! This will save me scads of time, I'm sure!

**Comment by mrexodia** [comment]
should be here, won't save you any time though :smile:

**Comment by vgturtle127** [comment]
@mrexodia Sure, it will. Instead of opening x64dbg or x32dbg, selecting my executable, and THEN debugging, now I can just right-click and select debug!
