### ISSUE TITLE
Restore patches of previous session 

### ISSUE THREAD

**Issue by philicious** [x64dbg/x64dbg#542]
When working on patches and program exits, you have to redo them all or constantly export them.

Have x64dbg auto-save / temp-save the last patches in the debuggees db file and ask user if he wants to restore patches from previous session or not:
- yes: load em + delete from db
- no: delete them from db

**Comment by mrexodia** [comment]
There is a plugin available that does this now: https://github.com/x64dbg/AutoExportPatches
