### ISSUE TITLE
show winapi arguments in stack

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#545]
As suggested on tuts4you:

![img](http://s25.postimg.org/x7nzpymbz/x64dbg_call_parameters.png)

**Comment by Nukem9** [comment]
How will this work? As soon as RIP moves to `CreateProcessW+0x1`, RCX/RDX/R8/R9 will be invalid as far as the debugger knows.

**Comment by mrexodia** [comment]
Yea so the plan was to only show then once on there and then maybe cache
them or something...

**Comment by mrexodia** [comment]
Implemented with the argument widget.
