### ISSUE TITLE
Assembler API

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#570]
I have noticed that there's a difference between the built-in (dis)assembler and Multiline Ultimate Assembler, which uses the API of x64dbg.
For example, the following command doesn't get assembled correctly with the API:

    cmp word ptr [rax + 0x18], 0x20b

Has the API changed? Do I have to change anything, as the plugin maintainer?

Here's what the plugin uses at the moment:
https://gist.github.com/RaMMicHaeL/adf29c90db9d5bbdbd7b

**Comment by mrexodia** [comment]
XEDParse indeed assembles this instruction incorrectly.

I don't quite get what you mean with if the difference in disassemblers. Everything uses capstone, but the disassembly you get is indeed different (mainly because of highlighting)

**Comment by RaMMicHaeL** [comment]
I got confused because what you see in the list is not what you see when editing the command. For example, the constants are prefixed with `0x` when editing commands. What's the reason for that? Multiline Ultimate Assembler is not designed for this, and it works incorrectly in some cases.

About the buggy command, the behavior seems inconsistent: if you click space on the command above (`cmp ...`, which is `66 81 78 18 0B 02`), and then press enter, it seems to be re-assembled correctly. On the other hand, if you choose another command, press space, enter the command above (`cmp ...`), and press enter, you see an incorrect command.
...OK, while writing this, I found out the reason: if the command wasn't changed, it's not being re-assembled. It's enough to add a space at the end of it, and the bug can be seen. I think that this is confusing, and the command should always be re-assembled. If the bytes change as a result, that's not always a bug; some commands have more than one representation.

In general, I tried to play with a block of code and Multiline Ultimate Assembler, and saw several issues. Here are some of them:
* `and rsp, 0xfffffffffffffff0` is assembled as `48 81 E4 F0 FF FF FF`, while it can be as short as `48 83 E4 F0`.
* `movabs r8, 1` is assembled as `mov r8, 1`. Should be `49 B8 01 00 00 00 00 00 00 00`.

If you want to stress-test XEDParse, you can disassemble blocks of code with Multiline Ultimate Assembler, and then re-assemble them. The result should be the same, or very similar. It works very well with Ollydbg, unfortunately not as well with x64dbg.

**Comment by mrexodia** [comment]
The first instruction appears to assemble correctly now. The sign-extended versions of instructions are still not working properly though.

**Comment by RaMMicHaeL** [comment]
Thanks, I'll check it out when I have the chance.
I see that the new engine treats numeric literals as decimal numbers.
e.g. `add eax, 60` is assembled as `add eax, 0x3c`.
This breaks Multiline Ultimate Assembler in several places, as it assumes that literals are hexadecimal.
Is there a setting for Keystone to preserve the old behavior?

**Comment by mrexodia** [comment]
Keystone is a separate project, I asked for this feature but it was not
implemented before the release. The only workaround would be writing a
custom parser that outputs to a keystone compatible format. This is in my
to do, but for now it won't be implemented.

**Comment by mrexodia** [comment]
There is now a new 'asmjit' assembler engine, I think this has been solved.
