### ISSUE TITLE
Highlight all sizes of a register

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#571]
A feature request: when highlighting `RAX`, for example, also highlight `EAX`, `AX`, `AL`, and `AH`.

**Comment by RaMMicHaeL** [comment]
It can be implemented by double clicking the register name in the registers window, like OllyDbg 2 does it. This way, a register of a specific size can still be highlighted using Ctrl+H, like it works now.

**Comment by mrexodia** [comment]
should be fixed now, but you cannot highlight specific sizes anymore (which I would never use anyway). If you think this is a required feature, please open another issue. A boolean setting that disables highlighting like this is pretty easy.
