### ISSUE TITLE
Disassemble short jumps as "jxx short (address)"

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#574]
I remember requesting it before, but x64dbg wasn't using Capstone back then. Perhaps now it's easier to implement.
Disassembling short jumps as `jxx short` will allow the Multiline Ultimate Assembler plugin to assemble back the jump as a short jump. Otherwise, if that's a jump to an address which is a label, it's difficult to know beforehand whether the jump can be a short jump.

**Comment by mrexodia** [comment]
shouldn't be hard to do, currently I think the disassembled text is directly using capstone, would require some custom output.

**Comment by RaMMicHaeL** [comment]
I ended up implementing it in Multiline Ultimate Assembler. It turned out to be easier than I expected. As my plugin is probably the only consumer for this issue, you might want to close it :)
You can download the new version of the plugin [here](http://rammichael.com/multimate-assembler). It works much better with x64dbg now. Currently, the most visible issue is probably the fact that commands of the form `and rsp, 0xfffffffffffffff0` assemble in a longer version than necessary, which causes all of the assembly to shift down. This can be worked around by replacing the command with the following in the plugin:
`"\x48\x83\xE4\xF0" ;; and rsp, 0xfffffffffffffff0`
But in general, many blocks re-assemble cleanly, which is great.

**Comment by mrexodia** [comment]
This is a bug in XEDParse @Nukem9, I will keep it open until at least that is fixed (probably other instructions are affected too)
