### ISSUE TITLE
DbgClearAutoLabelRange and DbgClearAutoCommentRange for manual labels and comments

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#575]
Sorry for spamming with issues. I tried to use Multiline Ultimate Assembler with x64dbg today, and found out that it doesn't work so well.

One of the issues is that I used the `xxxAuto` APIs, which refer to the automatic labels and comments. So I changed it to use the non-Auto APIs, but for DbgClearAutoLabelRange and DbgClearAutoCommentRange, there's no non-auto equivalent.

Can these APIs be added? An alternative would be to loop through every address, and that's not very efficient.

**Comment by mrexodia** [comment]
The reason there is no non-auto one is that tools cannot add user made
labels (since they are tools). It can be added though :)

**Comment by RaMMicHaeL** [comment]
> tools cannot add user made labels

They can use the `DbgSetLabelAt` API (versus `DbgSetAutoLabelAt`), can't they?
I don't know what's the difference for labels, but for comments, the auto ones are gray, and I believe that comments that are set by Multiline Ultimate Assembler has to be black, because they are not auto-generated or something. The user wrote them.
