### ISSUE TITLE
Label assigned to address only when entered twice

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#583]
Let's place label to some address. For example, go to the address N and enter a label MyStrPos. After the first attempt to enter the label nothing happens. When you try to enter some label again at this address you'll see label doesn't exists at this address.
Let's try to enter label second time and the label assigned to the appropriate address on the left is highlighted in red. (Now all looks right)
Now, if you remove label from address N and enter it again, the label will be assigned at first try and not at 2nd attempt.

**Comment by blaquee** [comment]
I tried this with latest snapshot and I can't seem to reproduce, are you using the latest build?

**Comment by lupier** [comment]
Yes, latest. This is very strange but I can't reproduce bug in same file and at same conditions. But believe me in previous test run labels placed only at 2nd attempt.

**Comment by mrexodia** [comment]
@lupier It might have been fixed in a snapshot somewhere, so don't worry about it if it's not reproducible anymore. I will close the issue. If you manage to reproduce it later, please comment and I will reopen.
