### ISSUE TITLE
Feature Request: Ability to save memory section to disk

### ISSUE THREAD

**Issue by havokeachday** [x64dbg/x64dbg#585]
When viewing the allocated memory (alt+m view), being able to right click and choosing to save the entire section to disk/file would be very handy.

**Comment by mrexodia** [comment]
I thought this was implemented... But yeah good idea otherwise!

**Comment by havokeachday** [comment]
I was just looking for a way to do this last night using a build from Jan 25th. If it is implemented, I wasn't able to figure it out. My first attempt was to try to do it from the dump view, but it only saved the bytes I had selected.

**Comment by mrexodia** [comment]
Try the 'savedata' command. I kinda forgot the syntax but I think it was
'savedata file.dump, address, size'

**Comment by havokeachday** [comment]
that works, thanks. I still think a GUI means to do that would be useful.

**Comment by mrexodia** [comment]
Sure, I'll keep the issue open and mark it as easy so anyone can implement
it.

**Comment by blaquee** [comment]
I thought I added this feature already its #533. In Memory Map view, you can right click any memory region and select "Dump Memory To File"

**Comment by havokeachday** [comment]
Thanks. I was using a build that was older than that.
