### ISSUE TITLE
dump view selection of bytes is limited in usability

### ISSUE THREAD

**Issue by havokeachday** [x64dbg/x64dbg#586]
If you attempt to select bytes and scroll, the dump view does not scroll to accommodate a larger selection area. Similarly if you press and hold the shift key and press any arrow keys, a selection is not made. Supporting a wider variety of selection features would improve usability of the view.

**Comment by havokeachday** [comment]
Looks like https://github.com/Simsys/qhexedit2 could be usable for the hex view as it allows selection/edit of the bytes. Also Okteta is KDE/Qt based, but might allow for a better UI as well.

**Comment by mrexodia** [comment]
Yeah unfortunately it's not very suited. I forked this and wrote QHexEdit3
which is used for the binary edit. But it's not suitable for gigabytes of
data. And it only shows bytes or ascii

**Comment by mrexodia** [comment]
Assumed to be closed with #1035
