### ISSUE TITLE
Following expression to follow - dl not dll

### ISSUE THREAD

**Issue by NarutoUA** [x64dbg/x64dbg#588]
Enter following expression to follow -> you need to type %dllname%.dl intead of %dllname%.dll

**Comment by mrexodia** [comment]
What do you mean? Can you give meaningful examples or screenshots? Because
I'm not aware that "%dllname%" is a valid expression.

**Comment by NarutoUA** [comment]
http://prntscr.com/aaoz12  -- is
http://prntscr.com/aaozcw -- must be (i think)

**Comment by mrexodia** [comment]
I think in this particular case the `wsock` library might have an export called `dl`. However I cannot reproduce the issue here.

**Comment by NarutoUA** [comment]
1) Download the lattest version from here: https://sourceforge.net/projects/x64dbg/files/snapshots/
2) Open x32dbg.exe
3) Attach to any process
4) Go to Memory - double click on any .dll module .text section
5) Press "Ctrl+G" -> try to type any loaded module with .dl and .dll extension

**Comment by mrexodia** [comment]
Yes I know I cannot reproduce it.

**Comment by florian0** [comment]
The parser will evaluate kernel.<Ordinal>
Somehow `dl` evaluates to `0x64 ('d')`

Test it with the internal Calculator or `log "{0}", dl`

**Comment by mrexodia** [comment]
dl is the lower byte of rdx so it's not strange that it will evaluate to
something. I think I see what the 'problem' is but I think it's the desired
behavior.

**Comment by florian0** [comment]
Ooohhhh that explains it. `dl` is indeed 0x64 in both of my tested binaries.

**Comment by mrexodia** [comment]
closed it because its not a bug
