### ISSUE TITLE
Invalid parameter passed to CRT function!

### ISSUE THREAD

**Issue by petkovic** [x64dbg/x64dbg#589]
I was trying to debug an dll, and got this error, and dbg after clicking on OK crashed

dump file

https://www.sendspace.com/file/g8zfp7

**Comment by revmischa** [comment]
I get this error constantly if I try to view the symbols for the current exe. Open any 64-bit exe, click symbols, click the first module in the list. Crash boom. Latest snapshot version.

**Comment by mrexodia** [comment]
is this still an issue @petkovic @revmischa ?

**Comment by mrexodia** [comment]
Assumed to be fixed.

**Comment by petkovic** [comment]
I was busy with some stuff ill check asap

**Comment by DwordXor** [comment]
Hello

I use the last snapshot and  xLCB plugin from ThunderCls.
If i try to exports comments have i this error.
