### ISSUE TITLE
Switching to CPU while searching leads to crash

### ISSUE THREAD

**Issue by florian0** [x64dbg/x64dbg#590]
As the title says. If you start a search (in my case Search for Strings in current module) and switch to the CPU-Tab while the search is in progress, x64 dies.

Should be reproduceable, and Github doesn't want my crashdump anyway, so ... :/

Using latest Snapshot (2016-03-04_05-04), 32 bit version.

**Comment by florian0** [comment]
Crashdump attached (why did it work now?)
[dump-05032016_0236500515.zip](https://github.com/x64dbg/x64dbg/files/159622/dump-05032016_0236500515.zip)

**Comment by mrexodia** [comment]
just tried and I cannot reproduce it.

**Comment by florian0** [comment]
Just tried on snapshot of May 28 2016, still reproduceable. The search has to consume enough time to switch to CPU before the search ends.
Giving out my binary might cause "problems", so managed to reproduce it with other files shipped with x64dbg.

It also occurs on (string search):
- QtCore4.dll (4836ms total)
- QtGui4.dll (15881ms total)
- capstone.dll (4821ms total)

I noticed: It does not crash immediately on tabswitch. Sometimes, switching wont lead to a crash at all; while clicking or scrolling the CPU-Tab seems to cause a crash pretty reliable.

I can provide more tests or crashdumps, if requried.

Some specs:
- snapshot_2016-05-28_05-51
- Windows 7 Pro X64
- ScyllaHide v1.2

**Comment by Nukem9** [comment]
Can't reproduce. Crashdump says the fault was in std::map/CapstoneTokenizer.

**Comment by mrexodia** [comment]
Ah I think I know where...

**Comment by torusrxxx** [comment]
Already resolved
