### ISSUE TITLE
Incorrect JMP-marker placement when target is not excatly on instruction

### ISSUE THREAD

**Issue by florian0** [x64dbg/x64dbg#591]
I got an executable that got messed up by Themida, which messes up the analyzer so some instructions are wrong.
Bit hard to explain, this screenshot will help:
![jmp-miscalculated](https://cloud.githubusercontent.com/assets/768730/13544919/d57ae3c0-e27d-11e5-97c5-a285b34ca20f.PNG)
The big arrow on the left points down to the scrollbar, while the little arrow between address and bytecode is correct.

Obviously not a high-priority bug, but worth to mention.

Using latest Snapshot (2016-03-04_05-04), 32 bit version.

**Comment by mrexodia** [comment]
shouldn't be too hard to fix. Needs some heuristics in `Disassembly::paintJumpsGraphic`

**Comment by blaquee** [comment]
Could you provide this executable?

**Comment by mrexodia** [comment]
this might be fixed now 7c0b179c
