### ISSUE TITLE
Stop Debug does not release File Handle

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#592]
Stop Debug command (or hitting the stop button to end a debugging session) does not release the file handle. If you stop debug and try to delete the debugged file, you can't and Windows complains about it being in use by x64dbg.

**Comment by florian0** [comment]
Applies for loaded libraries, too.

**Comment by blaquee** [comment]
nice! i didnt think to look there! thx @RaMMicHaeL
