### ISSUE TITLE
Ability to attach to non-exe processes

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#597]
Working on some coding with renamed exes to another extension.  Currently, I have to patch the program to CreateProcessA a version of the file it wants but as a .exe so I can attach.

**Comment by torusrxxx** [comment]
I'm not able to reproduce the problem. Non-exes can be attached.

**Comment by mrexodia** [comment]
closed for now. comment if this is still an issue @MoonDoggie42
