### ISSUE TITLE
Remember Column Widths [Trying to put a bounty on this]

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#598]
Please remember my column widths between x64dbg sessions :).

I've been to the bounty source website and I'd like to put $$ on this issue, mrexordia/et al, if you can direct me how to do this I'd be greatful.

**Comment by MoonDoggie42** [comment]
I think I successfully added a $10 bounty to this.

**Comment by mrexodia** [comment]
duplicate of #368
