### ISSUE TITLE
Ctrl+A for analysis

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#600]
I think that the analysis is helpful enough to warrant a hotkey.

P.S. is there a difference between `analyze`, `cfanalyze` and `analyze_nukem`?

**Comment by mrexodia** [comment]
Yes they are different analysis algorithms, some work better in some
scenarios.

**Comment by RaMMicHaeL** [comment]
Was the hotkey added? I only see Ctrl+Shift+A for a single function.

**Comment by mrexodia** [comment]
Oh, seems like I closed this by accident 👍

**Comment by torusrxxx** [comment]
This menu is added for a long time.
