### ISSUE TITLE
"Refresh list" button on the attach process window

### ISSUE THREAD

**Issue by Alastor27** [x64dbg/x64dbg#601]
We have to close and reopen the attach window in order to refresh the process list.
It would be more convenient to do this with a dedicated button.

**Comment by mrfearless** [comment]
There is a refresh option already - F5 to refresh or right click on process listview for menu that shows refresh. But maybe a button saying "Refresh Process List" (maybe bottom left on dialog) would help to highlight this option.

**Comment by Alastor27** [comment]
Oh, I never noticed that!
But still, a button would be nice.

**Comment by torusrxxx** [comment]
The refresh button is available. Can it be closed now?
