### ISSUE TITLE
Wrong software BP at unexisted addresses in BP list after restart

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#602]
1) start program X.exe
2) program X.exe load library YYY.dll and after some work there are few breakpoints in BP list.
3) delete YYY.dll , restart X.exe
now debugger show dll name YYY in module\label column but dll already deleted from disk
and I can't delete such BP's from list and debugger reports >> No such breakpoint "001E3001"

**Comment by Atvaark** [comment]
I can reproduce this bug. The BPs in a a DLL I injected into a process can't be deleted.

Steps to reproduce:
1. Open a db with an invalid breakpoint
Example:

Software          | Name              | Module/Label  |  State 
----------------- | ----------------- | ------------- | ------
00000000000010C7  |                   | ds3-hash.dll  | Inactive

2\. Remove the breakpoint via the context menu
3. The GUI will send the message **bc 00000000000010C7**
4\. [CMDRESULT cbDebugDeleteBPX(int argc, char* argv[])](https://github.com/x64dbg/x64dbg/blob/913012dfa768fe13dc3463e4e3e13e40f1a0591a/src/dbg/debugger_commands.cpp#L267)  is called
5. [if(BpGet(0, BPNORMAL, argv[1], &found))](https://github.com/x64dbg/x64dbg/blob/913012dfa768fe13dc3463e4e3e13e40f1a0591a/src/dbg/debugger_commands.cpp#L286) fails to get the BP by name
6. [if(!valfromstring(argv[1], &addr) || !BpGet(addr, BPNORMAL, 0, &found))](https://github.com/x64dbg/x64dbg/blob/913012dfa768fe13dc3463e4e3e13e40f1a0591a/src/dbg/debugger_commands.cpp#L304) fails to get the BP by address.

**Comment by mrexodia** [comment]
Has the issue been fixed?

**Comment by Atvaark** [comment]
The invalid BSs still show up in the list and deleting them hasn't been fixed in the latest snapshot.
