### ISSUE TITLE
group bytes in instructions

### ISSUE THREAD

**Issue by Siarogak** [x64dbg/x64dbg#603]
![x64dbg](https://cloud.githubusercontent.com/assets/17321601/13572893/ca5fe78a-e48d-11e5-853f-f2c8550bc9a0.PNG)
is it possible to make  same logic?

**Comment by mrexodia** [comment]
Yes it's possible, but for me its not even close to important. It requires the disassembler to give information about byte locations.

**Comment by torusrxxx** [comment]
Supported
