### ISSUE TITLE
add variables that resolve to the selected dump/disasm/stack addresses

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#605]
please come with suggestions for how to name them (`stacksel`, `disasmsel` and `dumpsel`?)

**Comment by mrfearless** [comment]
uservar = addr[ess] [dump][stack][disasm] (defaulting to disasm if empty)

so basically a command that has optionally one parameter, that can be assigned to a user defined variable

Or if only looking to define variables then perhaps:

'addr' for selected disasm address
'stack' for selected stack address
'dump' is already a command, so something else for that, maybe 'hexdump' or prefix all three with a specific identifier: #addr, #stack, #dump or @addr, @stack, @dump

**Comment by mrexodia** [comment]
That might work but I was thinking making it part of the expression engine.
Then if you want to assign your variable you just put myvar = &dumpsel and
you have it in your variable.

**Comment by blaquee** [comment]
perhaps just curstack, curdisasm, cursel
