### ISSUE TITLE
Truncate file name in debugger CPU View

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#607]
I don't know if there is a hard limit, but files with long names should probably be truncated in the CPU view.
![truncate](https://cloud.githubusercontent.com/assets/1324227/13673531/5dcda3de-e6a7-11e5-949f-35d800aaf6ee.PNG)

**Comment by mrexodia** [comment]
I think someone added an option to do that. Personally I wouldn't use it
though 😀

**Comment by blaquee** [comment]
Yea I mean, visually its an eye sore when the name is kept that long and you have to expand the view to see the API calls. I know the sensible option would be to rename the file, but sometimes that's not a good option (i.e If I prefer to know the files sha I'm working on)

**Comment by mrexodia** [comment]
It was implemented I'm pretty sure about that maybe it's an hidden option
somewhere? I can't remember.

**Comment by blaquee** [comment]
I'll look around, if I find it I'll report and close.

**Comment by mrexodia** [comment]
It was implemented as it turns out. A hidden option:

```
[Disassembler]
MaxModuleSize=10
```

**Comment by mrexodia** [comment]
left open for the alias option
