### ISSUE TITLE
Threads get unpaused when stepping?

### ISSUE THREAD

**Issue by MoonDoggie42** [x64dbg/x64dbg#608]
Can't verify, but it seems like when x64dbg is on an int3, when you single step, other threads come unpaused for a brief moment?  Having problem debugging some multi-threaded code, where it appears the only way I could be getting access violations would be another thread unpaused itself briefly.  Any guidance?

**Comment by mrexodia** [comment]
Yeah, once you single step it will release all the threads and stuff might
run. That's currently how the debug engine works...

**Comment by MoonDoggie42** [comment]
Shouldn't all other threads but the one I'm stepping stay suspended?  The other threads then generate an access violation on a valid instruction.  I'll write a quick program that might illustrate the problem better.

-Colin

**Comment by MoonDoggie42** [comment]
I'll check into the source and see if I can make it suspend all other threads.  It's difficult to step in x64 at all with 60 threads running on the same data I'm operating on.
