### ISSUE TITLE
0x prefix for values

### ISSUE THREAD

**Issue by gise88** [x64dbg/x64dbg#614]
EDIT: only the 0x prefix is important (other part of the issue was resolved)

Hi all! 

I'd like to know if exists a plugin that shows a "bracket" (ollydbg style) from start of a function to its end? If not would be a great enhancement/feature.. =)

The second request is to add a option (checkbox in `preferences->disasm` ?) that adds or not the 0x prefix for values in the disassembly view.

Just to make things clearer this is a screenshot from olly:
![untitled](https://cloud.githubusercontent.com/assets/6855163/14049626/c0906356-f2b6-11e5-858b-ddfae6a304dc.png)

I really appreciate what you guys are doing..
Thank you very much for giving us this amazing powerful tool!

**Comment by mrexodia** [comment]
You can manually add functions or use the analysis commands to get function
boundaries (use 'anal' 'cfanal' or 'anal_nukem'. The 0x prefix seems super
useless to me (since everything is in hex per default) but I guess someone
can add it if they are interested.

**Comment by gise88** [comment]
> You can manually add functions or use the analysis commands to get function boundaries (use 'anal' 'cfanal' or 'anal_nukem'. 

Can you tell me where I can found those options? Searching for "anal" on google.. You know... :laughing: 

> The 0x prefix seems super useless to me (since everything is in hex per default) ..

Yes, you are completely right. I would use it because sometimes I need to copy and paste same part of the assembly on VS, in the __asm {} statement, and than need to add 0x manually.. 
It would only be for convenience, nothing more!

However thank you for your answer!

**Comment by mrexodia** [comment]
Just enter them as command in the command bar. I will keep this issue open
for the 0x prefix. It shouldn't be hard to add.

**Comment by gise88** [comment]
> Just enter them as command in the command bar.
Omg.. I didn't know this functionality.. I just fell in love!

>  I will keep this issue open for the 0x prefix. It shouldn't be hard to add.
Ok, thank you again.

**Comment by mrexodia** [comment]
The different commands have different analysis engines so you might get
better results sometimes with another engine.

**Comment by clshack** [comment]
If you are using notepad++ you can replace the hex value and adding the 0x prefix with this regex:
Find:
`[0-9A-F]+`

Replace:
`0x$0`
