### ISSUE TITLE
POS1 and END keys don't move the cursor in References-Search-field

### ISSUE THREAD

**Issue by florian0** [x64dbg/x64dbg#616]
Again, a minor bug. The Pos1 and End keys don't move the cursor in the search field of the references-tab.
Ctrl + Arrow-keys are working.

Latest snapshot (snapshot_2016-03-21_09-55.7z), x32-build.
Windows 7 x64

**Comment by mrexodia** [comment]
Yeah ctrl+V isn't working either.

**Comment by Avinm** [comment]
I think the issue is at SearchListView::eventFilter(), there's no default case to forward the event back to the QLineEdit, adding a `default: return false;` seems to fix the issue.

**Comment by Avinm** [comment]
I think the issue is at SearchListView::eventFilter(), there's no default case to forward the event back to the QLineEdit. All keys other than the ones listed in the switch gets forwarded to the search view.
