### ISSUE TITLE
Antidebugging functionality downgrade

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#618]
Hi! In latest build something changed (IMO in BP handling or in HWBP section) and as a result 
my target program doesn't run somewhere in the "middle" of running time. Target uses lot of antidebug tricks (total ntdll code section read from disk and scan for hooks, DRx usage, tons of exceptions, lots of classic antidebug trick, NtSetInformationProcess, etc)
After look into all 3 last month snapshots:
Something changed in snapshot_2016-03-20_01-44 - antidebug - fail
snapshot_2016-03-05_10-48 - antidebug - ok
Unfortunately I can't explain what exactly broken in target code because lot of antidebug code under vmprotect protection. (classic vmprotect antidebug isn't a problem for me, sure)
p.s. I'm use scyllahide plugin with settings
![4ec1db69b92ad324c31a040814b652e0](https://cloud.githubusercontent.com/assets/1623540/14217295/00095534-f86f-11e5-94cb-bed6ecbf0c0b.png)

**Comment by mrexodia** [comment]
Everything works fine for me... The issue is rather unspecific, could you
give more information on what the problem is and what I can do about it?
Scyllahide is not supported and if the plugin is broken there is not much I
can do about that.

**Comment by lupier** [comment]
Scyllahide plugin are ok because nothing changed in settings between "good" snapshot and "bad".

Unfortunately I can not give more information and all the other 99% of the targets work well as expected. I was trying to find all code changes for March but there are lot of changes in HWBP handling and I need time to understand what changed and what it means. If I find the reason for this bug I'll report it.

**Comment by mrexodia** [comment]
The main changes with hardware breakpoints is with how the command works.
There was also a change that involves automatically setting hardware
breakpoints when they are not inside a module. But what is the problem with
your target?
