### ISSUE TITLE
Debugger can not show the Chinese?

### ISSUE THREAD

**Issue by LzwCracker** [x64dbg/x64dbg#619]
![1](https://cloud.githubusercontent.com/assets/18252512/14236049/49fbd652-fa41-11e5-8f35-4c3bae165651.jpg)
![3](https://cloud.githubusercontent.com/assets/18252512/14236050/4b3b4f52-fa41-11e5-928b-1ad629012f1b.jpg)
x32&ollydbg     show the difference thing~!   x32 show the messy code~!

dr.uncle@163.com

**Comment by blaquee** [comment]
Hi, yes, might be also related with #507 . International characters don't seem to be yet properly supported. There is room for improvements there and much needed PRs for it :)

**Comment by mrexodia** [comment]
Bytes are interpreted as ascii so it's normal that they are not shown as
Chinese. Would require a code page change if it did.

**Comment by blaquee** [comment]
perhaps using the current systems locale to determine the code page change?

**Comment by mrexodia** [comment]
It shouldn't be very hard to add an option in the dump to show text in a specific code page. Doing so would resolve the issue.

**Comment by mrexodia** [comment]
Code page was added.
