### ISSUE TITLE
TitanHide

### ISSUE THREAD

**Issue by AN3Orik** [x64dbg/x64dbg#620]
Last version of build can't see any plugin (as TitanHide) in plugin directory.

**Comment by mrexodia** [comment]
Okay? There are currently no plugins shipped with x64dbg by default so that's expected I guess...

**Comment by AN3Orik** [comment]
Even if i put TitanHide plugin to plugins directory? =\

**Comment by mrexodia** [comment]
I have no idea to be honest. It might be that plugins without menu are not
shown. What does the log say?

**Comment by babbsgit** [comment]
@mrexodia How to load the titanhide plugin on x64dbg? I have placed the plugins files in plugins folder. But when I open x64dbg I can't find it in plugins menu.
