### ISSUE TITLE
Changed CMP-instruction is (re)assembled incorrectly

### ISSUE THREAD

**Issue by florian0** [x64dbg/x64dbg#621]
I guess this is not a bug in x64dbg itself. But i don't know which dependency is responsible for this behavior, so I'll just report it here.

I've got this command:

`83 7C 24 08 7E           | cmp     dword ptr ss:[esp+8], 7E`

When i change the constant to 80, the command should extend to its 4-byte-version (from OllyDBG):
`817C24 08 80000000    CMP     DWORD PTR SS:[ESP+8], 80`

But instead, it does this:
`83 7C 24 08 80           | cmp     dword ptr ss:[esp+8], FFFFFF80`
(Overflowing into the sign-bit)

~~It works correctly, if i nop the command first and reassemble it.~~ no it doesn't. It even changes the 4-byte-version to a 1-byte version
The "Keep Size"-option has no influence on it.

Latest Build (snapshot_2016-03-31_11-32.7z)
x32-edition
Windows 7 x64

**Comment by wk-952** [comment]
Similar to #539

**Comment by florian0** [comment]
correct. I missed that one, sorry.

**Comment by mrexodia** [comment]
Duplicate (as mentioned by @wk-952). This requires fixes in XEDParse which is a code base that I'm not very familiar with. Probably this will be fixed once Keystone comes out.
