### ISSUE TITLE
XMM and YMM Registers Displayed Wrong

### ISSUE THREAD

**Issue by Elhardt** [x64dbg/x64dbg#623]
I was just trying out x64dbg for the first time and when my code loaded scalar single precision floating point values into the XMM vector registers, they loaded in the upper 4 bytes of those registers and in byte reversed (backwards) order according to your register display. They should load into the lower 4 bytes and normal human byte order (they're only stored in memory in byte reversed order). So x64dgb is displaying everything in those registers backwards and that needs to be fixed.

**Comment by mrexodia** [comment]
Duplicate of #257
