### ISSUE TITLE
Handles

### ISSUE THREAD

**Issue by cobrce** [x64dbg/x64dbg#624]
is it possible to add a windows that shows handle (if the feature already exists tell me where to find it) and to show it's value API parameters, like when I put a BP in ReadFile shows the file path next to handle value

**Comment by mrexodia** [comment]
Hello, Could you make separate issues for each request? This is kind of
confusing since some are duplicate and some are not going to be implemented.

**Comment by cobrce** [comment]
done

**Comment by mrexodia** [comment]
duplicate of #79
