### ISSUE TITLE
Assemble directly

### ISSUE THREAD

**Issue by cobrce** [x64dbg/x64dbg#625]
Assemble directly, I mean no need to press space, I just write something (in CPU window) and the "assemble at" window shows directly containing the char I introduced

**Comment by mrexodia** [comment]
Personally I don't like this feature. Pressing space first shouldn't be much of a hassle and on top of that you can bind keys to stuff like setting labels so it would get weird and inconsistent very quickly. Is there any other way to improve the experience you think?

**Comment by cobrce** [comment]
It's just a matter of habits, I'll try to get used to it (or I'll try to write a plugin for this xD)
thanks for your reply

**Comment by mrexodia** [comment]
You will not be able to write a plugin that does this ;)
