### ISSUE TITLE
Small gui bug - splitter not working

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#626]
At the bottom of the cpu tab the splitter doesnt work. The splitter cursor shows up when you hover over it, but moving up or down does not do anything. The splitter seperating the next section and the hex dumps does work however.

Attached is image to show the location where splitter appeas but doesnt work - area in red. I couldnt capture the actual splitter cursor, so i just pasted one in for a frame of reference.

![splittercursor](http://s21.postimg.org/vjnl4zkdj/splittertop_notworking.png)

**Comment by mrexodia** [comment]
Yeah I couldn't find how to disable this cursor change so I just left it this way. Is is the intended behavior.
