### ISSUE TITLE
How to develop a plugin?

### ISSUE THREAD

**Issue by xxxxnnxxxx** [x64dbg/x64dbg#627]
i create a dll project in vc2015 and import the latest pluginsdk,
build the project and rename the dll to .dp64, put the file into the directory of x64dbg/plugins
but it is not loaded by x64dbg,why? the follow is the code of my project:
```
DLL_EXPORT bool pluginit(PLUG_INITSTRUCT* initStruct)
{
    initStruct->pluginVersion = plugin_version;
    initStruct->sdkVersion = PLUG_SDKVERSION;
    strcpy_s(initStruct->pluginName,256, plugin_name);
    g_pluginHandle = initStruct->pluginHandle;
    return true;
}

DLL_EXPORT bool plugstop()
{
    return true;
}

DLL_EXPORT void plugsetup(PLUG_SETUPSTRUCT* setupStruct)
{
    return;
}
```

**Comment by mrexodia** [comment]
Take a look at the example plugin. https://github.com/x64dbg/testplugin

**Comment by mrexodia** [comment]
From what I can see here you don't define `extern "C"` which might mess up the generated DLL file.

**Comment by mrexodia** [comment]
closed for now, everything appears to be working fine here.

**Comment by xxxxnnxxxx** [comment]
thanks your answers 
it 's ok ,the plugin has been loaded into the memory,but the name of the plugin is not diplayed in the menu. there are some wrong in my code :)
thanks again

**Comment by mrexodia** [comment]
It should say in the log. If you don't add a menu option manually it
doesn't show the plugin in the menu (since it wouldn't have any menu
options anyway).
