### ISSUE TITLE
Glitchy horisontal scrollbars

### ISSUE THREAD

**Issue by Archer-Dante** [x64dbg/x64dbg#631]
huge empty space makes all the gui parts show horizontal scrollbar even if it not nessesary
i don't really know why, but looks like gui fixed to some screen resolutions or display type
demo: http://i.imgur.com/Hj4vLKk.gif

**Comment by mrexodia** [comment]
your resolution seems to be pretty low. anyway the reason is that there is a fixed size for the last column (because comments can usually be in there). A possible workaround would be to add an option that enables the themed horizontal scrollbar (the one in the registers view).

**Comment by Archer-Dante** [comment]
yea, it's 1280x1024
but with olly or immunity it's fine, so i wonder what's going on
thanks for fast response

**Comment by mrexodia** [comment]
Probably they don't use a fixed size column at the end 😀 you can fix it by
resizing the last column (which isn't saved but that's a work in progress).

**Comment by mrexodia** [comment]
Column widths are now saved so the issue should be fixed.
