### ISSUE TITLE
Unable to detect ASCII?

### ISSUE THREAD

**Issue by DigiAngel** [x64dbg/x64dbg#632]
Not sure this is the right question...I have a very simple Win32 GUI app that just pops up a message.  x64dbg appears to disassemble the actual message of "Hi! I'm the example program!" as code.  How can I manually set this to ASCII?  Screenshot enclosed, thank you.

![2016-04-21 15_20_23-x32dbg - file_ blehx32 exe - pid_ 2b24 - module_ blehx32 exe - thread_ ac4](https://cloud.githubusercontent.com/assets/947191/14724716/127ba1fc-07d5-11e6-950b-a5a817ee40fd.jpg)

**Comment by mrexodia** [comment]
You cannot at the moment. Code and data mixed is not supported.

**Comment by DigiAngel** [comment]
Ah...well there it is then...thank you much.

**Comment by mrexodia** [comment]
No need to close the issue. It's simply not implemented right now

**Comment by DigiAngel** [comment]
Ah...awesome thank you :)  Love this app..I use it daily.

**Comment by mrexodia** [comment]
Data instructions are implemented now.

**Comment by DigiAngel** [comment]
Awesome...thanks so much!

**Comment by fenderluvr** [comment]
I don't see how this bug is fixed.  If I am incorrect, please explain.  I am looking at a Delphi application and can see ZERO strings, such as TForm1, when doing a string search.  Olly has not issue with this.

**Comment by mrexodia** [comment]
Then use Olly. The bug was fixed because it is possible to mark data ranges as ASCII.

**Comment by fenderluvr** [comment]
So you can manually mark a data range as ASCII that you are unaware of, got it. 

:)

Trying very hard to get away from Olly, but it seems will never happen.

**Comment by mrexodia** [comment]
You can write an analysis plugin, that was the original request. The cunty snark certainly isn’t going to help you here so I’ll close this.
