### ISSUE TITLE
wiki's regfile missed

### ISSUE THREAD

**Issue by Archer-Dante** [x64dbg/x64dbg#633]
Dunno if it's fine place to report Wiki trouble, but there is no regfile to remove context menu.

or maybe you can just answer if there is only "HKCR\exefile\shell\Debug with x64dbg" + "HKCR\dllfile\shell\Debug with x64dbg" paths or i miss something..?

**Comment by wk-952** [comment]
If i'm not mistaken, what you're asking about is in the "frequently asked questions" section in the wiki, it's the first question.
https://github.com/x64dbg/x64dbg/wiki/Frequently-Asked-Questions

**Comment by wk-952** [comment]
Ouch!, the link  to the file says: "Not Found"
i guess it needs a re-upload.

**Comment by mrexodia** [comment]
someone the link was messed up. well fixed that now :+1:
