### ISSUE TITLE
scaling issues.

### ISSUE THREAD

**Issue by gijoe50000** [x64dbg/x64dbg#634]
A lot of the text in the application itself is not aligned correctly and there's some text missing in the options menu due to scaling. I'm using Windows Scaling at 175% on my pc, as I have a 4k monitor. Icons are tiny as well.

**Comment by mrexodia** [comment]
Duplicate (feel free to fix it and send a pull request. I don't have a 4k monitor to test). Probably it will be fixed once we switch to Qt 5.6
