### ISSUE TITLE
script command

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#637]
Hi !
example from ollyscript
1. mov variable1, [variable2], size    or   mov variable1, byte/word/dword [variable2]
2. dm/dma address, size, file
In help there are analogues, but the dump does not work, even from the context menu (SaveDialog)
moving only qword
In the context menu of the disassembler no scripting commands.
And if you can, add a pagecontrol, the Windows dump tab for scripts. Very handy when all before my eyes.
It is urgent to fix...)))

**Comment by mrexodia** [comment]
Ollyscript is not supported in x64dbg.
1. I believe there is a memcpy command. You can also do 2:[addr] = 54 to
set a word at addr
2. Dump works fine, it changes the address of the dump window. There is a
command to dump memory regions. However it is currently undocumented :)

**Comment by mrexodia** [comment]
The command to dump memory is 'savedata'.

https://github.com/x64dbg/x64dbg/blob/development/src/dbg/instruction.cpp#L2330

**Comment by Paliha** [comment]
ок...Дякую !!!

**Comment by Paliha** [comment]
Hi! 
savedata works.
how to form a file name string?
sorry, but there's only experience of ollyscript
eval "bla-bla{address}.mem" or str address
savedata $RESULT, address, rax
Well, no, the filename is reserved as a variable...(((((
Ох...Беда...))))

**Comment by Paliha** [comment]
format string only log

**Comment by mrexodia** [comment]
Yeah currently it is not supported

**Comment by Paliha** [comment]
The project is large to study completely no desire. Temporarily under their tasks have done so:
-------------------------
CMDRESULT cbInstrSavedata(int argc, char* argv[])
                    {  if(argc < 3)  //savedata filename,addr,size
                        {  dputs("Not enough arguments...");
                           return STATUS_ERROR;  }
                       duint addr, size;
                      if(!valfromstring(argv[2], &addr, false) || !valfromstring(argv[3], &size, false))
                          return STATUS_ERROR;

                      Memory<unsigned char*> data(size);
                      if(!MemRead(addr, data(), data.size()))
                        { dputs("Failed to read memory...");
                           return STATUS_ERROR;  }
	              char buff[500];
	              sprintf(buff, "%p", addr);
	              String str = buff;
	              String name =".\\minidump\\" + str + ".mem";
	              strcat(argv[1], name.c_str());
                      if(!FileHelper::WriteAllData(name, data(), data.size()))
                        { dputs("Failed to write file...");
                          return STATUS_ERROR; }

                      dprintf("%p[% " fext "X] written to \"%s\" !\n", addr, size, argv[1]);
                      return STATUS_CONTINUE; }
------------------------------------
Sadly, that simple everyday tasks from scripting language lacks possibilities.

**Comment by mrexodia** [comment]
Developing and maintaining a project like this is not simple and I simply
don't have time to work on everything. Contribute code if you want new
features, complaining is not going to help you.

**Comment by mrexodia** [comment]
The `savedata` command now has an option `:memdump:` as filename to save it under a predicatable name. see help.x64dbg.com
