### ISSUE TITLE
Add relative offset to symbol view at (at least) Stack

### ISSUE THREAD

**Issue by Shaddy** [x64dbg/x64dbg#638]
Not sure if discussed but I didn't find anything related.

So far the stack view shows up any symbol whenever the address is exactly pointing at the start of the function. But, if the pointer is in the middle it only shows the offset. Would like to have something more "windbg" like or IDA.

Is there any "hidden" setting to do this?

**Comment by mrexodia** [comment]
No hidden setting but a good idea to implement.

**Comment by Nukem9** [comment]
#341

**Comment by mrexodia** [comment]
duplicate
