### ISSUE TITLE
Color scheme bug ?

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#639]
While using other colors than the standard one i go to for example to string reference tab 
and hit Ctrl+F2 and go back to CPU tab  i get this: http://prnt.sc/b1tuy4
It seems that it only happends when having diffrent colours.. 
could someone else confirm this bug ?

**Comment by mrexodia** [comment]
Still cannot reproduce it. I used [this](https://gist.github.com/mrexodia/5b560dd1671577d1f214dec549f3edc0) color scheme to test.

**Comment by mrexodia** [comment]
Okay, as noted can be reproduced (with default color settings) with the following settings:

![c](http://i.imgur.com/xcJBpHC.png)
