### ISSUE TITLE
Debugger hangs

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#653]
1. Debug anything
2. Try to continue the application's execution flow, by pressing `F9` or `Shift + F9`,
or run until a certain selection (`F4`).

The debugger will just hang and the debugee won't continue its execution,
only stepping (`F7` or `F8`) works now.

EDIT:
No dumps are created too.

**Comment by mrexodia** [comment]
yeah, just reproduced this one.

**Comment by mrexodia** [comment]
okay should be fixed, forgot to release some locks on time :smile:

**Comment by wk-952** [comment]
Thank you so much.
