### ISSUE TITLE
Trace record

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#654]
Trace record is the next major feature I'd like to introduce. When enabled on a page/module, it will record any location the executable have accessed/executed, and show they with different color in disassambly so you know you've been there before. It works only if you're stepping and no exception or thread switching occurs.

**Comment by mrexodia** [comment]
Sounds cool! I'm interested to see your approach. Tell me if you need any
facilities that I can help with.

**Comment by torusrxxx** [comment]
It was supposed to work by disassembling the current instruction before, though I have changed my mind and decided to implement it by defining a new type of memory breakpoint. It should work with previous restrictions removed.
But I have to fix another issue right now. If you're using a translated version of x64dbg and reordering tabs, it produces dozens of message boxes, which is very disturbing.

**Comment by mrexodia** [comment]
I wouldn't use memory breakpoints for anything that needs performance. Placing a logger before you disassemble is probably much faster.

**Comment by torusrxxx** [comment]
When testing current memory breakpoint capability I found memory breakpoint doesn't work. code is:
resume:
ADD R11,1
MOV RDI,table
MOVZX RAX,R11B
LEA RAX,QWORD PTR DS:[RAX+RDI]
XCHG RAX,RDI
MOV AL,BYTE PTR DS:[RDI]
ADD AL,1
MOV BYTE PTR DS:[RDI],AL
MOV RAX,QWORD PTR DS:[table]
JMP resume
table:
NOP...(256)
apply a memory breakpoint to all these and see it.

**Comment by mrexodia** [comment]
Memory breakpoint works but you can only break on page sized buffers.

**Comment by torusrxxx** [comment]
Oh no! Olly's memory breakpoint can be set to any buffer. Olly will bypass false hits automatically.

**Comment by torusrxxx** [comment]
I'll defer the work until both memory breakpoint solution and disassemble solution are compared further.
Trace record data is useful not only in UI, but also in analysising. You can first run a "coverage" run,labelling every executable instructions and during analysising or next run, simply treat all instructions not executed before as junk bytes. I won't forget it.

**Comment by mrexodia** [comment]
Yes I know. I plan to implement more flexible memory breakpoints in GleeBug.

Memory breakpoints will never be faster though. To set a memory breakpoint you need `VirtualProtect` (which is really slow), then `VirtualProtect` again on hit of the breakpoint (restore original protection), then single step with the trap flag and finally restoring the memory breakpoint with `VirtualProtect`. If you are going to break on every instruction you have three `VirtualProtect` calls overhead over the single step you would have done anyway.

As for coverage, it can be useful as supplementary data, but one path through your program is not enough to cover all branch decisions so it cannot be immediately discarded from analysis. I think it would be very interesting to see how many times certain instructions are executed to identify code/memory hotspots.

One feature that could be implemented with what is available right now is history debugging. This is just for every `DebugUpdateGui` storing some context and then allowing to view these contexts in the disassembler.

**Comment by torusrxxx** [comment]
Trace record is not going to be intended for identifying hot spots. I will store a bit for every byte at most. If you want to identify hot spots then breakpoint counter is waiting for you.

**Comment by Avinm** [comment]
But bp should be set for bp counter to work...

**Comment by mrexodia** [comment]
Yes I think he was referring to the new breakpoint features.

**Comment by Avinm** [comment]
Yeah but still, this one would tell you the hot areas without you having to mark/guess it with a bp.

**Comment by torusrxxx** [comment]
I have decided to implement this feature by disassemble approach, in the GUI. Every byte will be given a bit indicating whether it has been executed or not. When stepping in, all bytes covered by the current instruction will be marked. This takes 512 bytes every page. For a typical 20MB VMProtect'ed executable, the memory footprint will be around 2.5MB. Can be extended so every byte takes 8bit or 16bit, but that will not be implemented first. This works best with currently unimplemented "Animate into" operation.

**Comment by mrexodia** [comment]
Why not just store a struct per byte covered? It's not like we are low on memory these days. This would also allow it to be extended very easily. It would just reserve  `0x1000 * sizeof(infoStruct)` on the first hit and store that buffer in an `std::map<Range, std::vector<infoStruct>>`

**Comment by torusrxxx** [comment]
How to store and load large amounts of binary data such as the trace record to and from the database?

**Comment by mrexodia** [comment]
Just serialize the data like breakpoints. Databases are only loaded on
start and stop of the debuggee.

**Comment by torusrxxx** [comment]
I've finished `TraceRecordManager` class, however I'm facing difficulties in connecting it to the stepping event and fetching current instruction. Moving it into DBG now.

**Comment by torusrxxx** [comment]
The code in DBG is freezed now. Currently implemented feature: 3 types of trace record, and a framework enabling future expanding.
The single-bit mode records whether the byte have been executed.
The byte mode includes a 6-bit hit counter and 2-bit byte type. Byte type records if the byte was an instruction heading, body, or tailing, or overlapped. An overlapped byte is the byte interpreted as differing instructions. If any byte of the current instruction overlaps with another one then the entire instruction is considered overlapped.
The word mode increases the hit counter to 14 bits.
There is an instruction counter counting number of instructions stepped, but that's currently unused. It will be recorded in future modes.

**Comment by torusrxxx** [comment]
Trace record can be enabled on 4096-byte buffer. Each buffer can have different modes.

**Comment by mrexodia** [comment]
Sounds cool!

Are you using `ModHashFromAddr` to allow for relocations on saving to the database?

**Comment by torusrxxx** [comment]
I've change the code to use that. Working on database load/store now.
![x64dbg trace record interface](https://cloud.githubusercontent.com/assets/15761310/15531158/47807bec-2248-11e6-9983-d253a0078710.png)

**Comment by mrexodia** [comment]
That looks really cool!
