### ISSUE TITLE
Question about FastResume

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#655]
Before anything, this is not an issue,
just inquiry about the new `FastResume` flag since there's nowhere else to ask (sorry).

So if understand it correctly, normally whenever the debugger passes by a breakpoint-ed
instruction its log text will be written ignoring whether the condition is met or not,
but when `FastResume` is enabled, the log text will only be written when the condition is true.
Is that it ?

Another question please, why is the `Command on hit` not executed when `FastResume` is enabled ?
Also the button `Reset hit count` doesn't work at all, although changing number of hits from the edit menu is working.

I really apologize for this, but i couldn't think of another place to ask.

**Comment by mrexodia** [comment]
We do have a gitter channel where you can ask directly ;) anyway you
already found a bug. Fast resume should not do any logging/commands if the
debugger would not break.

I fixed this just now. Will look in the other issue.

**Comment by wk-952** [comment]
The reset button is now working and the hit command is executed when `FastResume` is enabled.
Thank you.
I'll ask later on gitter about this new flag.
