### ISSUE TITLE
GUI: QActions, QMenus and other QWidgets are not deleted?

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#660]
In the source code of GUI I saw huge number of `new`s but nearly no `delete`s. Are these huge number of objects going to stay in memory until the process is terminated? It looks so terrible.

**Comment by minlexx** [comment]
In Qt I think objects which are created with parent, are deleted when their parent is deleted...

**Comment by torusrxxx** [comment]
No. These objects are created with `new` operators, not with some methods provided by Qt, so Qt probably won't help. And I remembered have commited a commit called "delete wMenu" ebaf188 . It works, without any consequences like memory have been freed twice would have had.
Besides this, I found the menu system so wired. I have finished Trace Record feature #654 . However I'm currently facing difficulty adding a menu into the disassembly view. The project really needs restructuring.

**Comment by torusrxxx** [comment]
I'm not very familiar with Qt, though. If there is anything wrong with my ideas please forgive me.

**Comment by torusrxxx** [comment]
Yes, Qt have object tree feature. I'm going to check if there is any object without a parent is created or any parent is not deleted.

**Comment by mrexodia** [comment]
If a QObject has a parent it will be deleted when the parent is deleted.
Also I rewrote the menu generation system so that should solve any issues
you have with adding additional menus.

**Comment by mrexodia** [comment]
[This article](http://mrexodia.cf/x64dbg/2016/02/03/Dynamic-menu-builder) explains how the new menu builder system works and what the motivations behind it were.

**Comment by torusrxxx** [comment]
While most QObjects are deleted when parent is deleted, in reality some parents may never be deleted until the application terminates. The main window and the views are among those parents. When a context menu is built, it is held in memory until their parents are deleted(which is at the application termination time). This is in fact just like a memory leak. I'll add "delete wMenu" whenever I spot such condition.
I'm going to run xxxdbg in a low-memory virtual machine and instead of stopping debug and saving db, I just suspend the entire OS and save it on disk. These context menus are going to be an issue when you debug continuously for months without restarting.

**Comment by mrexodia** [comment]
Yes, that might be the case, there are also a few known memory leaks for various widgets, but they shouldn't matter because they are only created on start and will be deleted on exit anyway.

I pushed a fix.
