### ISSUE TITLE
String reference search too slow.

### ISSUE THREAD

**Issue by Avinm** [x64dbg/x64dbg#661]
Searching for string references is too slow(by a big margin compared to ida or olly) for large modules, maybe this can be improved?

**Comment by mrexodia** [comment]
During my initial tests string searching was faster than olly by a huge amount. Will check this.

**Comment by mrexodia** [comment]
Should be *at least* the same speed as Olly now, please test and report back. Will assume the issue was fixed for now.

**Comment by Avinm** [comment]
Still atleast twice as slow as olly : https://dl.dropboxusercontent.com/u/34019964/Comparison.swf

**Comment by Avinm** [comment]
Still at least twice as slow as olly: https://dl.dropboxusercontent.com/u/34019964/Comparison.swf

**Comment by mrexodia** [comment]
Actually your comparison is unfair. Search in module will do
ReadMemory(moduleBase, moduleSize, buffer) and then disassemble that buffer
entirely (which is gigantic on this 50mb file). Olly will only disassemble
the buffer of the .text section thus making it an unfair comparison.

Op za 4 jun. 2016 om 13:35 schreef Avin <notifications@github.com>:

**Comment by mrexodia** [comment]
When just doing string search in the .text section Ollydbg is still faster
(10.2 seconds vs 12.6 seconds) but the difference is far less. I will see
how I can further optimize this.

Op za 4 jun. 2016 om 13:40 schreef TPoDT|Mr. eXoDia <
mr.exodia.tpodt@gmail.com>:

**Comment by Avinm** [comment]
So what's x64's equivalent of the search I did in olly?

**Comment by mrexodia** [comment]
The region search (I believe, didn't write that menu code). Basically the button with the 'Az' icon in the menu bar.
