### ISSUE TITLE
I've encountered some Call Stack issues

### ISSUE THREAD

**Issue by Squaal** [x64dbg/x64dbg#662]
Hello, 

First of all thank you for your awesome work.
I was debugging some x32 apps, but x32dbg doesn't seem to pickup every event in the call stack. 

It's working fine in Olly, it grabs the <JMP.&MFC42.#2514> procedure from program.00480C24 to capture a nag that shows when you exit the app, however it doesn't show in x32dbg.

I don't know if it's some mistakes on my part, I'll link a comparaison screenshot here.
![callstack](https://cloud.githubusercontent.com/assets/19558032/15515939/ba9db9da-21f0-11e6-905a-8937fcdd781c.png)

**Comment by mrexodia** [comment]
We use the function from dbghelp to do this. Can you see the addresses olly
shows on the stack somewhere?

**Comment by Squaal** [comment]
All the Olly adresses are fine, can't see them anywhere on x32dbg, but it goes to them just fine with goto->expression I guess it doesn't pick up MFC42.dll ?

**Comment by mrexodia** [comment]
I mean, if you go to `ESP` and scroll down do you see all the `return to XXX from XXX` in the stack?

**Comment by Squaal** [comment]
It worked once while I was trying some stuff, but it doesn't seems to pick it up again... I can see every return that is listed in the Call Stack in the stack, but some are missing as I said before, or i'm doing something wrong to pick them up. I go as follow run->manually exit to get the exit nag->pause -> call stack. I can't see the call i'm looking for in the stack either.

**Comment by mrexodia** [comment]
If you pause it will break on a new thread that has no callstack. Could you try switching to the main thread (by double clicking on it in the Threads view)?

**Comment by wk-952** [comment]
@Squaal, I remember facing something like this, try the following (assuming your program runs on the `Main` thread):

1. Go to the `Threads` tab and right click on the thread whose name is `Main`, then select `Switch thread`
2. Go back to the `Call stack` tab and it should show the return addresses and args just as expected.

Please tell me if it worked for you.

**Comment by Squaal** [comment]
Oh it worked perfectly, thank you for your time.  It indeed broke on thread 4, I switched back to main and everything worked OK.
