### ISSUE TITLE
The Manual is broken (cannot be opened)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#663]
Pressing `F1` or selecting `Help` -> `Manual` won't do anything.

**Comment by mrexodia** [comment]
Should be fixed now :+1:

**Comment by wk-952** [comment]
Easter Egg:
When you extract the `.7z` file, there should be 2 folders: `pluginsdk` and `release`,
rename the `release` folder to `x64dbg v0.25_dev_build` and the help file won't open !!!

In other words, if the root folder of the debugger (that contains the `x96dbg.exe`) is named `x64dbg v0.25_dev_build`, the help file won't open, and unfortunately that's my case :smile:

**Comment by wk-952** [comment]
Can't re-open here because of the permissions.

**Comment by mrexodia** [comment]
Yeah you need to unlock the chm file for viewing.

**Comment by wk-952** [comment]
What ? you mean right click -> properties -> unlock ?
If yes, then i've actually this Windows feature from the local group policy a long time ago.

**Comment by mrexodia** [comment]
Yeah I cannot view downloaded chm files without doing this.

**Comment by wk-952** [comment]
It's already unlocked for me,
if the root folder is named anything then it opens, else if it's called `x64dbg v0.25_dev_build` then it doesn't open

![untitled](https://cloud.githubusercontent.com/assets/11916365/15537854/055ea546-2279-11e6-847e-84e2b8130da6.jpg)

**Comment by mrexodia** [comment]
strange.. perhaps Qt messes up paths with a `.` in them.

**Comment by wk-952** [comment]
Oh wait, if the path contains spaces then this issue occurs.

**Comment by mrexodia** [comment]
should be fixed now

Op wo 25 mei 2016 om 13:04 schreef wk <notifications@github.com>:
