### ISSUE TITLE
"Show mnemonic brief" button gets stuck in hide mode (GUI only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#666]
Just a very tiny GUI issue.
1. Right click and select `Show mnemonic brief`
2. Again right click and select `Hide mnemonic brief`

If you right click-ed again, it'll always show `Hide mnemonic brief`.
By the way, thanks for the incredible and stunning amount of work/contributions lately, it's really amazing.

**Comment by mrexodia** [comment]
working now, thanks a lot!
