### ISSUE TITLE
Supress all Gui message in plugin

### ISSUE THREAD

**Issue by wynick27** [x64dbg/x64dbg#669]
I was trying to write a analyze plugin for vmprotect. The plugin sets hundreds of breakpoints and trace every vm instruction. It only took several seconds for the analyze to finish, but the gui thread takes several minute to respond to all related update view messages. I think it would be nice if there is an option to supress all message when the plugin is running.

**Comment by mrexodia** [comment]
I believe somebody added an option to disable the log, you could try that.

**Comment by torusrxxx** [comment]
You may minimize the window as a workaround, so that all the GUI drawing will not happen, speeding up the plugin.

**Comment by mrexodia** [comment]
Assumed to be fixed, comment if you want to reopen this issue.
