### ISSUE TITLE
Degugger can't open because the export "_dbg_gethandlename" cannot be found

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#672]
Applies to both x32 and x64.

pic:
![untitled](https://cloud.githubusercontent.com/assets/11916365/15621524/d563ca16-2461-11e6-9b2e-d5bb4a189e79.png)

**Comment by wk-952** [comment]
Is this related to 1bff3d5 ?

**Comment by mrexodia** [comment]
Should be fixed now :+1:

**Comment by wk-952** [comment]
Sorry, i didn't actually see the commits before posting this

**Comment by mrexodia** [comment]
Nah you were two seconds before this commit 😀
