### ISSUE TITLE
"Invalid parameter passed to CRT function" when following the main() of a program

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#673]
1. Debug this application
2. Go to the `Symbols` tab and select the exe file (`bubble_sort.exe`)
3. In the search box type: `main` and try following this symbol

This error will pop up.
![qdsad](https://cloud.githubusercontent.com/assets/11916365/15622427/df5a9084-2468-11e6-8a2f-d53f4952448c.png)

- Application:
http://rgho.st/private/7MygGqz67/780e1720b0d66334ffc683200136c175

- minidump:
http://rgho.st/private/6vCKM68xN/cefb68240fbe930a0ffb85665be66fe1

Password: `asd123`

**Comment by wk-952** [comment]
I have some other questions please,
when i press `Ctrl + G` and type `__ImageBase` it doesn't resolve correctly,
also typing `bubble_sort.main` doesn't resolve.
Am i doing something wrong ? i'm sure at least `__ImageBase` used to work in the past (when it was called `IMbase`)

**Comment by blaquee** [comment]
For your original post, I just downloaded that executable and followed your steps and it went to main fine.
<img width="1062" alt="bubble" src="https://cloud.githubusercontent.com/assets/1324227/15623334/7b341c9c-2440-11e6-8f87-1bf14113e7d0.PNG">

For the second issue, I'll get back to you on that one.

**Comment by blaquee** [comment]
Actually, nvm. Testing on an old build.

**Comment by blaquee** [comment]
I fixed the original issue, but the second comment still seems to not work. Although typing "main" gets you to main directly. __ImageBase doesn't work.

**Comment by wk-952** [comment]
Thank you so much @blaquee.
So, should i leave this issue open, or open a new issue regarding this second comment, or just close here and ignore the issue described in the second comment ?

**Comment by houjingyi233** [comment]
I had the same problem in Win10,but in Win7 its fine.
