### ISSUE TITLE
Adding / removing columns in breakpoint tab

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#679]
It would be really useful to have a popup menu where you can chose
which columns to be active, currently comments are the last column now
and i would like it a little closer to the beginning.
The checkboxes would represent which columns should be in breakpoint tab
example of column thing i speak of:
![column](https://cloud.githubusercontent.com/assets/1159592/15630498/42e4b690-253e-11e6-8b03-8cd99444ccaa.png)

**Comment by mrexodia** [comment]
Just tried to implement it, but it's quite a pain to implemented. Requires quite some pieces of `AbstractTableView` to be rewritten to hide columns and then adjust every function that deals with columns (such as `getColumnCount`, `getColumnWidth`, `paintEvent` and probably several others).

**Comment by Chandlr** [comment]
oh .. but some day maybe :+1: 
Comments are important ;)

**Comment by mrexodia** [comment]
Just commenting for my future self :smile:

**Comment by mrexodia** [comment]
Should be implemented.
