### ISSUE TITLE
Cannot goto the entry point of the executable

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#683]
`EntryPoint`,`EP` and `OEP` do not work. However `[exe name].EntryPoint` works.
![x64dbg-entrypoint-cannot-be-find](https://cloud.githubusercontent.com/assets/15761310/15632367/9c2fd0aa-257e-11e6-9b1c-8d6578d7b8cf.png)

**Comment by wk-952** [comment]
Similar to #511 (explained there by mrexodia)

@torusrxxx there are similar behaviors, take a look here for example [#673 (comment)] (https://github.com/x64dbg/x64dbg/issues/673#issuecomment-222264518).
If you're interested, here's the application from that issue:
http://rgho.st/private/6hWXt2T2x/2279bee8d448c7b62cd5c49c2c86a8ba

**Comment by mrexodia** [comment]
I think you can use ":EntryPoint" to go to the entry point of the current
module.

**Comment by mrexodia** [comment]
Assumed to be resolved, comment if you would like to reopen.
