### ISSUE TITLE
Jump arrows in side bar is misleading if the destination is embedded in another instruction

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#684]
![x64dbg-jmp-arrow-misplace](https://cloud.githubusercontent.com/assets/15761310/15632389/3afe5490-257f-11e6-966a-69661b13c59e.png)
The jump arrow points at infinite destination, instead of breaking suddenly at the instruction which embeds the destination.

**Comment by florian0** [comment]
Related/Similar: #591

**Comment by biolavickram442** [comment]
pls unsubscribed me from your site
