### ISSUE TITLE
A way of repeating func pointer ?

### ISSUE THREAD

**Issue by LeaklessGfy** [x64dbg/x64dbg#689]
Hello guys,

I just started to use your tool. For what I just saw it's a great soft same if doc is not that perfect :).
On linux I'm on gdb (no gui, all in terminal) and there's some cool function inside it like the:
call {pointer}() wich just replay the function associated to the pointer. Is there such feature in your dbg ?

I tried call in command line but it's not recognized and I think it's from script ?

Thank you guys :)

**Comment by mrexodia** [comment]
It would be pretty easy to add a command that does this. It would push the current EIP/RIP on the stack and then change it to the pointer. 

Now the problem is with passing the arguments. There are many different calling conventions and thing like stack cleanup are a problem. Do you have any idea how to solve this?

**Comment by mrexodia** [comment]
My current idea is to have one command per calling convention.

**Comment by torusrxxx** [comment]
A "monkey" feature is also good. A "monkey" feeds the function with random arguments so any potential vulunability will be exposed quickly.

**Comment by mrexodia** [comment]
sure but you could write a script/plugin that calls this command with random arguments :smile:

**Comment by torusrxxx** [comment]
I think so. The feature proposed in this issue can be implemented in script
already. I suggest instead of implementing it we instead provide a "script
library/market" where some useful script are provided. And is it possible
to get a random value in script?

**Comment by mrexodia** [comment]
There is https://github.com/x64dbg/Scripts

With scripts I'm more talking about the C++ 'scripts' that are DLLs with a simple interface. But yeah I will provide an API that does remote calls.

**Comment by LeaklessGfy** [comment]
Your way of thinking seems good, now got to wait for that perfect feature.
For more info about GDB and the way it handles this feature you can refere to: 
http://stackoverflow.com/questions/1354731/gdb-evaluation-of-a-function

or gdb man: 
https://www.chemie.fu-berlin.de/chemnet/use/info/gdb/gdb_12.html#SEC96

For the latest sources of gdb: 
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=tree;h=7484106c3821da36585c31c9b3cfaa5266121aa2;hb=41d82368c333de4f7ec3fd7734ee683055e8c35c

and for all sources:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git

Don't know if it can help you to achieve this goal. Hope this !

**Comment by torusrxxx** [comment]
This could be useful when calculating something after patching some code.
Proposed implementation:
**command**: ``call mydll:myfunction, stdcall, 1, 2, 3``
Store the previous registers context, put some guard zeros on the stack, then put the arguments on the stack and registers, other registers are zeroed. Then put current RIP on the stack and set a software breakpoint on RIP and continue execution at called function. When the function returns it will stop at the breakpoint, and the registers are restored to previous context, RAX,RDX are stored in ``$result`` and ``$result2``.
An alternative way is to use zero as the return address, and capture that exception then restore the context.

calling conventions:
x86: stdcall, cdecl, fastcall, thiscall
amd64: stdcall

**Comment by mrexodia** [comment]
Yeah I agree 100% on the implementation...

**Comment by mrexodia** [comment]
Should be implemented as a plugin.
