### ISSUE TITLE
plugin shortcut register api

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#69]
---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/69
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:08:11.864

**Comment by Nukem9** [comment]
Issue #195 was marked as a duplicate of this issue.

----------------------------------------
Original comment by: [lynnux](http://bitbucket.org/lynnux)

**Comment by torusrxxx** [comment]
Temporarily supported by the favourites commands.

**Comment by bhatch11** [comment]
Stop
