### ISSUE TITLE
Animate into

### ISSUE THREAD

**Issue by msaly** [x64dbg/x64dbg#694]
#Hi
very nice and usefully tool.
if possible to add animate into (like ollydbg) ,for debugging and debugging events in options.this items is very useful for debugging .
thankyou

**Comment by blaquee** [comment]
Could you change the title to reflect the feature you want. Like "Animate Into Feature"

**Comment by mrexodia** [comment]
Removed the debugging events part since there are already options to break on every debug event.

**Comment by torusrxxx** [comment]
In Olly, there is a blinking text in the status bar telling you how many
debug events are processed per second, so you know how fast is the progress.

**Comment by mrexodia** [comment]
Ah okay that will be added in that case

**Comment by msaly** [comment]
I correct.exactly there is an option named "only on the fallowing modules".that i can not see in @x64 debug events.sometimes need to break on specially dll when loading.
and second , "animate into" options can help to fast checking.
