### ISSUE TITLE
Search is not re-applied when refreshing process list of attach-dlg

### ISSUE THREAD

**Issue by florian0** [x64dbg/x64dbg#697]
When refreshing the process list of the Attach-Dialog, the refresh button shows the entire process list and does not apply the previous search string. It is required to change the string to trigger the search again.

Minor bug, should be reproduceable.

Using latest snapshot (snapshot_2016-06-01_11-17), x32 edition.

**Comment by blaquee** [comment]
This issue is resolved now. Can be closed.
