### ISSUE TITLE
Register view is too small to display YMM8~YMM15

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#701]
![x64dbg-register-window-too-small](https://cloud.githubusercontent.com/assets/15761310/15739924/f3db038a-28a1-11e6-87f3-6c21e06b0786.png)

**Comment by mrexodia** [comment]
Yeah this will most probably not be changed, if you want to fully see them it might be advisable to change the font (or we could use fontSize-2 for YMM registers)

**Comment by mrexodia** [comment]
Also YMM registers are not supported in the debug engine
