### ISSUE TITLE
Modify Value in Dump Only modifies one byte

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#706]
If you select more than one byte in the Dump View and select the Modify Value menu. Only one byte is prompted for change.
<img width="430" alt="modify" src="https://cloud.githubusercontent.com/assets/1324227/15776840/c8608380-2958-11e6-9c9f-ae1326da1d6c.PNG">

**Comment by mrexodia** [comment]
yeah its how it was designed. it modifies the value of the size of one entry in the dump (so if you select modify value when you selected two words it would not edit a dword). could be changed though.

**Comment by blaquee** [comment]
So no matter how many bytes you select it will always only allow one byte modifications?

**Comment by mrexodia** [comment]
when the data type in the dump is bytes, yes. it could be changed though upto editing a value of min(sizeOfSelection, sizeof(void*))

**Comment by blaquee** [comment]
Fill Data seems to have a similar constraint, where even if you decide to fill more than one byte of data (and Keep size is not selected), it will only fill the first byte you entered.

**Comment by mrexodia** [comment]
That really strange, it should fill the data with your pattern. Have to
confirm that

**Comment by mrexodia** [comment]
agreed upon solution: hide the 'Keep size' checkbox because it is misleading
