### ISSUE TITLE
Cannot use the latest snapshot(2016-06-04_03-52) because x32gui.dll cannot be found

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#713]

**Comment by saidelike** [comment]
Hi,

Looks like this problem reappeared in snapshot_2017-07-29_18-24.

Regards

**Comment by stonedreamforest** [comment]
try this [https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2017-08-02_04-13.zip](https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2017-08-02_04-13.zip)

**Comment by mrexodia** [comment]
@saidelike Yes I have been updating the build process recently, probably I messed up a build. I do believe this has been fixed since though...

**Comment by mrexodia** [comment]
Okay this issue should never occur anymore I fixed the build scripts to work properly with CI.
