### ISSUE TITLE
pop up two error message.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#714]
why popup me two error messages on startup, how to fix?

1. The program can't start because BeaEngine.dll is missing from your computer. Try reinstalling the program to fix this problem.

2. The procedure entry point GuiGetFocusedCPUWindow could not be located in the dynamic link library x32bridge.dll.

**Comment by mrexodia** [comment]
probably you are using an ancient version of x64dbg. BeaEngine hasn't been used for more than a year now.

**Comment by cxj98** [comment]
i use lasted build version.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/releases if I open x64dbg.exe or x32dbg.exe it runs fine.

**Comment by cxj98** [comment]
previous version no this issue.

**Comment by mrexodia** [comment]
Make sure to completely remove your older files and extract in a new directory.

**Comment by cxj98** [comment]
definitely did as you say exactly.

**Comment by cxj98** [comment]
[url=https://postimg.org/image/411gv65kr/][img]https://s33.postimg.org/411gv65kr/2016_06_05_040825.jpg[/img][/url]

[url=https://postimg.org/image/6wek219kr/][img]https://s33.postimg.org/6wek219kr/2016_06_05_040506.jpg[/img][/url]

[url=https://postimg.org/image/h7qwup1a3/][img]https://s33.postimg.org/h7qwup1a3/2016_06_05_040441.jpg[/img][/url]

[url=https://postimg.org/image/ymb52yyez/][img]https://s33.postimg.org/ymb52yyez/2016_06_05_040427.jpg[/img][/url]


[url=https://postimage.org/]forum image hosting[/url]

**Comment by mrexodia** [comment]
those screenshots cannot be a clean version of x64dbg, the default settings look different.

**Comment by cxj98** [comment]
at startup.

https://s33.postimg.org/upxt6zdfj/2016_06_05_040427.jpg

https://s33.postimg.org/6xohvgben/2016_06_05_040441.jpg

bug on assemb and hex, show incomplete info.

https://s33.postimg.org/dycho8d6n/2016_06_05_040825.jpg

**Comment by mrexodia** [comment]
Like I said that cannot be a clean install of x64dbg.

**Comment by cxj98** [comment]
this issue happen today, why yesterday build version no this issue.

**Comment by mrexodia** [comment]
I don't know and I don't care. Just do a clean install and restore your
plugins and settings from there gradually until you find what caused the
error.

**Comment by cxj98** [comment]
does labeless plugin related? let me try to remove it.

**Comment by cxj98** [comment]
labeless looks work well, after remove this issue consist.

**Comment by mrexodia** [comment]
Extract the latest snapshot in a separate directory and go from there. I will not provide support for old plugins or configurations.

**Comment by cxj98** [comment]
i don't do any plugin and any setting on configurations, download latest build and upzip it and straight use it. then not show me error messages on startup, but bug on disassembly window and hexdata window, show incomplete info.

https://s33.postimg.org/dycho8d6n/2016_06_05_040825.jpg

I was thought translated language file mattered, but it not, how to fix?

**Comment by mrexodia** [comment]
Can you try with the default configuration (delete x32dbg.ini)?

**Comment by mrexodia** [comment]
The disassembly drawing bug should be resolved now.

**Comment by cxj98** [comment]
you are right, disassembly drawing bug fixed now.
