### ISSUE TITLE
The disassembly interface is too messy

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#715]
![x64dbg-disassembly-messy](https://cloud.githubusercontent.com/assets/15761310/15803562/9480c9cc-2ad3-11e6-84ca-e3252f9d4441.png)
New installation with default settings.

**Comment by ViRb3** [comment]
Same with x64.

**Comment by torusrxxx** [comment]
I know what's happening. I'll pull a fix now.

**Comment by mrexodia** [comment]
It's so weird. I had this issue for 1 run but then it wasn't visible on my
computer anymore...

**Comment by cxj98** [comment]
not fix.

**Comment by mrexodia** [comment]
What exactly?

**Comment by torusrxxx** [comment]
You should clean and rebuild the entire project.

**Comment by cxj98** [comment]
right, fixed now.
