### ISSUE TITLE
Add pseudo instruction DB, DD, etc

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#716]
DB emits a byte into the disassembly.

**Comment by wynick27** [comment]
I think analysis hint and structure view should be added to disasm engine, just like ollydbg and IDA.  And the Instruction_t and QBeaEngine for drawing GUI should be an abstract class, so it can be changed dynamically to debug vm code like IL or from a virtualizing obfuscator.

**Comment by mrexodia** [comment]
I don't think an abstract class for Instruction_t will do anything useful. In my opinion it's best to customize the CapstoneTokenizer in combination with analysis hints that are pulled from the DBG. I have some ideas for this but there are a lot of things going on right now so I cannot focus on it.

**Comment by torusrxxx** [comment]
I just want DB/DD. These pseudo-instructions are easy to implement in XEDParse.

**Comment by mrexodia** [comment]
Should be implemented.

**Comment by wqj66** [comment]
怎么添加伪指令？
