### ISSUE TITLE
Error starting process (CreateProcess, ERROR_NOT_SUPPORTED)!

### ISSUE THREAD

**Issue by Cheater4free** [x64dbg/x64dbg#720]
x32dbg always fail to debug anything

**Comment by mrexodia** [comment]
Did you run as administrator? I cannot do anything about this error. It
means that Windows could not start the process.

**Comment by Cheater4free** [comment]
Yes, I have run it as admin, it failes at Launchbox and some Vb.Net Apllications I have written.
I can debug AndyRootkit as example, but these Programs doesn't work.
I am using Windows 10 Pro 64 Bit and 4 GB Ram.
Here is the full Log:

Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing capstone...
Initializing Yara...
Getting directory information...
Mnemonic help database loaded!
Symbol Path: H:\Desktop Alt\Cracking\x64 Dbg\release\x32\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Starting command loop...
Loading plugins...
Handling command line...
Reading notes file...
Initialization successful!
Database file: H:\Desktop Alt\Cracking\x64 Dbg\release\x32\db\LaunchBox.exe.dd32
Error starting process (CreateProcess, ERROR_NOT_SUPPORTED)!

**Comment by torusrxxx** [comment]
dotNET is not supported. It's best to analysis these files with Microsoft's
IL disassembler.

**Comment by ViRb3** [comment]
Just a follow-up: are there any plans to support x64 dotNET PEs? Is there any specific difficulty in making it work? I noticed IDA Pro cannot debug them either.

**Comment by mrexodia** [comment]
I don't have any plans, feel free to contribute though.

**Comment by torusrxxx** [comment]
dotNET is a x86 PE file which contains additional dotNET-specific headers. It will automatically switch to the native instruction set(x86-64 or IA64) upon boot. I'm not very clear about how they boot.

**Comment by ViRb3** [comment]
Fixed in #1124 ?

**Comment by mrexodia** [comment]
Assumed to be fixed.
