### ISSUE TITLE
Increase the font

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#724]
![image 1](https://cloud.githubusercontent.com/assets/16466330/15820791/fb77eb4c-2beb-11e6-87c9-e6fbb02a2a36.jpg)
![image 2](https://cloud.githubusercontent.com/assets/16466330/15820793/fb925630-2beb-11e6-9198-b740a63a1ae5.jpg)
![image 3](https://cloud.githubusercontent.com/assets/16466330/15820794/fba44318-2beb-11e6-99e1-e93203d2c728.jpg)

When you increase the font on the wide screen, text borders are not controlled. Font size 10. Pictures are attached.

**Comment by mrexodia** [comment]
This is intentional and you can fix it by restarting x64dbg.

**Comment by UnlimitedChild** [comment]
Thank you! Restart solves this problem!

Can I keep the position of the window, so that it is preserved after a restart?

**Comment by mrexodia** [comment]
At the moment this is not supported, you can follow #368 for progress (although I consider it to be a less important feature so it might take a long time).

**Comment by UnlimitedChild** [comment]
Thanks!
