### ISSUE TITLE
Add support for backward value tracing and symbolic execution

### ISSUE THREAD

**Issue by wynick27** [x64dbg/x64dbg#737]
Backtracing can find possible values for an expression at a specific address. Symbolic execution can generate an expression that describes what a block of code does. And can bind values to get executed result. Metasm has those features, very useful for analyzing obfuscated code. Not easy to implement since it requires a custom IR and a map from x86 to IR. IR can also be translated to llvm IR, then optimized and recompiled to x86 code. With this feature, code deobfuscation can be done automatically.

**Comment by torusrxxx** [comment]
There's a x86 to IR converter in Snowman. Will that be useful?

**Comment by mrexodia** [comment]
I really think this is beyond the scope of the project, however we need to
look if the plugin interface is powerful enough to handle a plugin that
would like to do this...

**Comment by mrexodia** [comment]
Also, if someone would like to create a plugin I can add a repository in the team so we can semi-support something like this. The main reason I don't want this in the main code is that it takes so much code to write something like this and I don't want that code affecting the current codebase too much. A plugin would be perfect for this.

**Comment by wynick27** [comment]
I can work on this once I finish other parts. The snowman IR is useful but the library must be changed to support symbolic execution. I think backtrace and symbolic execution won't be much code, only expression defination, translater and several algorithms.
