### ISSUE TITLE
Formating "Data Copy" bytes/dword/qword

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#740]
Would be nice if Data copy bytes were formated to have 100 bytes per line or so
not all in one line.

this is messy:
![datacopy](https://cloud.githubusercontent.com/assets/1159592/15968338/c9e41f0e-2f2b-11e6-801f-6be81160ac5d.png)

**Comment by Chandlr** [comment]
This seems to be fixed :)

**Comment by mrexodia** [comment]
Yeah it has been replaced with another issue. I only fixed this for Delphi but it needs a more generic solution...
