### ISSUE TITLE
Translate strings in the DBG

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#742]
There are 2 ways to do it as far as I know. One is windows's `LoadString`(have to update translation templates manually). The another one is to create a dummy Qt project file, mark every string in the DBG with QT_TR_NOOP, and then load the translations dynamically from the GUI where Qt stays.(more complicated, but we can use `lupdate` tools.)

**Comment by mrexodia** [comment]
Yeah I think the dummy qt project is the best option, especially since we
will crowd source the translations.
