### ISSUE TITLE
Instruction parsing status isn't updated

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#745]
Assemble `mov rax, rbx` (correct)
![1](https://cloud.githubusercontent.com/assets/11916365/15997272/5a753884-3132-11e6-8a35-6bb4153e0073.png)

then assemble `mov rax, eax` (wrong)
![2](https://cloud.githubusercontent.com/assets/11916365/15997279/682bdb9a-3132-11e6-90a5-be3b11ab5670.png)

To force it to update, switch to 'XEDParse' then to 'Keystone' (or vice versa).

**Comment by wk-952** [comment]
Forgot to mention that it dynamically updates the status, but only when `Keep Size` is selected.

**Comment by mrexodia** [comment]
This should be fixed now

**Comment by wk-952** [comment]
Thank you so much.
