### ISSUE TITLE
F7 Trace & F8 Step doesn't work inside spoolsv.exe

### ISSUE THREAD

**Issue by Djamana** [x64dbg/x64dbg#752]
How to reproduce:
1. Options/Pref/Engine
  [v] Enable Debug Privilege (so spoolsv.exe will get visible in the attach dialog)
2. ALT+a to open Attach dialog - there attach to spoolsv.exe
-> well on the 'Attach breakpoint reached!' everything works fine F7, F8, F4 everything as expected
F9 to let it run
3. Try Pause F12  -> No Pause but log says: Error suspending thread
4. Anyway go to Memory map spoolsv.exe .text  + F2 to set a memory breakpoint there
->finally that hit and spoolsv is pause again

Now:
The only breakpoints that work are when use F2 or F4. 
At F4 the first strangeness occurs.  1. x64dbg halt **after** the breakpoint and 2. the breakpoint **didn't got deleted** (place where I pointed with F4 is red)
Okay the list goes on:
Stepping or Tracing with F7 or F8 does works (works half). 
The program runs, but **doesn't stops on next instruction**

Well I'm using Win7 sp1 X64 with x64dbg jun13 2016

**Comment by mrexodia** [comment]
Trace and step is exactly the same unless you are on a call (just in case
someone is going to reproduce this).

Generally the pause feature doesn't work very well. A fix was submitted
recently, but apparently to no avail.

**Comment by Djamana** [comment]
Oh cool that was quick.
What trace and step is unless when you are on a call?
Hmm don't understand what ya mean by that.

Would ya mind I show this to ya via Teamviewer?
570 059 624
q169sy

**Comment by mrexodia** [comment]
I know what step and trace are. In x64dbg **StepOver** is implemented as a **StepInfo** (eg trap flag), unless the instruction is a `call` or `ret`. The reason for this is performance.

**Comment by BiTOk** [comment]
I have same problems as @Djamana. After attach to process stepping doesn't work, after switching CPU->threads->CPU tabs all registers are zero. Problem with F4 also present. Reproduces well.
Win 7 SP1 x64. x64dbg snapshot_2016-06-26_11-55 and several previous.

**Comment by mrexodia** [comment]
I tried this today. Basically I attached (with x64dbg as admin+debug priv enabled), then went to the main thread and put a breakpoint after the `ZwWaitForMultipleObjects` that's on that thread's call stack.

Then I opened notepad, put some characters and pressed Ctrl+P. Everything works fine (stepping etc) once it breaks.
