### ISSUE TITLE
entry point SymGetDiaSession could not be located

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#754]
x32dbg.exe - Entry Point Not Found
The procedure entry point SymGetDiaSession could not be located in the dynamic link library C:\WINDOWS\SYSTEM32\DbgEng.dll. 

![image 1](https://cloud.githubusercontent.com/assets/16466330/16089801/14e5f9d2-332d-11e6-8e29-892649d642c5.jpg)

![image 2](https://cloud.githubusercontent.com/assets/16466330/16089999/ec286dc6-332d-11e6-94f3-d38015df719e.jpg)

**Comment by mrexodia** [comment]
What os version are you on? Dbgeng should be included with the snapshot.

**Comment by UnlimitedChild** [comment]
Windows 10 Ent version 1511 OS Build 10586.420 Eng

**Comment by mrexodia** [comment]
Not sure what version of x64dbg this is, there is no linking with `dbgeng.dll` as far as I know.

**Comment by UnlimitedChild** [comment]
Сan be a problem in the plug-ins? Just in the previous versions that did not happen ... Perhaps an error occurs due to the updated windows. I'll try to catch this message.

**Comment by mrexodia** [comment]
Sure if you have a custom plugin it can be a plugin issue. Try vanilla
x64dbg

**Comment by UnlimitedChild** [comment]
it is an error in the plugin - [PLUGIN] Failed to load plugin: APIComments.dp32 - I have not thought to see the log file. 

Perhaps as in IDApro to make a message that the plugin is not loaded because of an error?

**Comment by mrfearless** [comment]
Sounds like one of my older plugins. I had a plugin called APIComments that was an early version of what is now called APIInfo plugin. Ive since updated the plugins and the code i used to create them as the earlier version had a few errors. If it is this plugin i would suggest deleting it and download the APIInfo one to see if that helps: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-masm/downloads

**Comment by UnlimitedChild** [comment]
> Sounds like one of my older plugins. I had a plugin called APIComments that was an early version of what is now called APIInfo plugin. Ive since updated the plugins and the code i used to create them as the earlier version had a few errors. If it is this plugin i would suggest deleting it and download the APIInfo one to see if that helps: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-masm/downloads

Thank you! I did so, the problem is solved.
Regards
