### ISSUE TITLE
Could not get module filename...

### ISSUE THREAD

**Issue by jscho21** [x64dbg/x64dbg#755]
When I go to file -> attach, and choose the application I want to attach to, it says "Could not get module filename E0C!" E0C being the PID. 

I think the reason for this is because this particular application has no file path, just the file name and '.exe' at the end. So while all other process say things like "C:\program Files\whatever\whatever.exe", this one just says "Name.exe". 

This application automatically detects when programs like cheat engine or ollybg are running and shuts off. x64dbg was the only one I could get to run at the same time as the application, so I'm hoping there's a fix for this!

**Comment by mrexodia** [comment]
You could try enabling the debug privilege. But maybe the application uses
some kind of trick to remove it's module from the peb.

**Comment by jscho21** [comment]
That didn't make a difference. If it matters at all, the Scylla plugin can attach and load the modules. I just don't think I can do much with that.

**Comment by mrexodia** [comment]
How exactly does this executable have no path?

**Comment by jscho21** [comment]
It has a path in my hard-drive obviously but none shows up in the debugger attach window.  It must be some security feature that hides it from debuggers. All the other applications in the attach window have full paths

**Comment by mrexodia** [comment]
So what is this mysterious application? Are there drivers involved?

**Comment by jscho21** [comment]
It's a video game called Black Desert Online. Came out in March I think

**Comment by mrexodia** [comment]
it might be that their anti cheat is being weird or they hide the process
path in some way. does Scylla show the full path?

Op za 18 jun. 2016 om 22:12 schreef jscho21 <notifications@github.com>:

**Comment by jscho21** [comment]
Yes scylla shows the whole path. I know the game can be debugger because there's q company selling a bot for it.
