### ISSUE TITLE
fpu/mmx support (multi-type variables)

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#76]
---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/76
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:11:59.696

**Comment by Nukem9** [comment]
I am working on this

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by Nukem9** [comment]
I am coding support for MMX, x87 and XMM (SSE support),

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by Nukem9** [comment]
I tried x64_dbg for the first time, and immediately noticed lack of xmm register display.  Can't wait to see that added, thanks for working on it!
- ejamesr

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
how about YMM, ZMM register set
AVX, AVX2, AVX512 command set?

details to be read here  https://en.wikipedia.org/wiki/Advanced_Vector_Extensions


----------------------------------------
Original comment by: [alex_b3](http://bitbucket.org/alex_b3)

**Comment by Nukem9** [comment]
I need more time to code for 3dnow etc. But all FPU support its comming :-)

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by Nukem9** [comment]
x64_dbg will become a rocket science once it'll be familiar to that kind of bits...

so far so good I know 0 debuggers support that all......
cheers

----------------------------------------
Original comment by: [alex_b3](http://bitbucket.org/alex_b3)

**Comment by Nukem9** [comment]
Yes to all, but especially xmm and ymm.  And here's my wish list for
display features for registers (I use FASM extensively, and need a better
debugger than WinDbg, which is barely adequate for 64-bit debugging):

- Have a "drill down" feature for the registers. For example, display the
GP regs (rax, rbx, etc.; or eax, ebx, etc. for 32-bit code). But if I click
on the + next to it, then also show eax, ax, ah and al, etc.
- For all displayed regs, show both signed and unsigned values (or make it
simple to switch between them).
- Make it easy to switch between hex and decimal display.
- The flags should always be displayed

For xmm/ymm/zmm regs: xmm is a subset of ymm, ymm is a subset of zmm.  But,
we sometimes think of them as separate.  So:

- Show xmm, ymm, and zmm regs on separate lines with ability to drill down.
  - For example, in 64-bit code, when I click on ymm, show drop-down with
all 32 regs.  Then let me see the data as bytes, words, dwords, etc., with
option for signed/unsigned, hex/decimal, float/integers/byte display formats
- DO NOT close or modify the register display, let it remain as I set it;
let me save the format so it is "remembered" each time.
- Bonus feature: allow me to change the display order. For example, I
always need the flags, so I'll put that on top; but since I don't normally
care about r12-r15, let me move those near the bottom.

Look at Microsoft WinDbg - has lots of format options for memory display
(this is good!), but lacks ability to change format of register display
(but it allows me to change the order of the registers).

Thanks,

ejamesr


----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by Nukem9** [comment]
Agree with your wishes. A lot of GUI work with this hehe.

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by Nukem9** [comment]
I am finishing the first -basic- FPU Support. but Microsoft says something like: Win64 process not support x87+MMX+3dnow in context switch, but the instruction works fine... I dont know what is best... keep the display of registers (ST0, MM0 ...)? (because the instructions and registers works fine) or not... :?

----------------------------------------
Original comment by: David Reguera Garcia (Dreg)

**Comment by Nukem9** [comment]
The FPU registers are not used by Windows in Win64 (I'm not sure about
MMX).  3dnow has been essentially dropped, no longer used.  But xmm (and
ymm and larger) regsiters are vital for Win64.  You can certainly show the
other regs; if Win64 doesn't use them, they won't get trashed during
context switches.

----------------------------------------
Original comment by: [ejamesr](http://bitbucket.org/ejamesr)

**Comment by torusrxxx** [comment]
I have been working on a "Edit floating-point register" dialog. The user can view and edit multiple floating-point values stored in an FPU, XMM or YMM register.

**Comment by mrexodia** [comment]
I think editing one value at a time would be all that's needed. Notice that long double is not supported by Windows and needs a custom parser.

**Comment by torusrxxx** [comment]
Okay. I just want a dialog which looks like OllyDBG's. The initial implementation targets XMM/YMM registers. Since we cannot store a long double value inside these registers, a custom parser is not needed.

**Comment by mrexodia** [comment]
The FPU register edit dialog of Olly edits 80 bits, for which you would need a custom parser. I'm not sure how the XMM/YMM registers work with floating point representation though...

**Comment by Nukem9** [comment]
Parsing 80-bit floats would just be the reverse operation of this function: https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Utils/StringUtil.cpp#L38 (don't think anyone will need it though)

XMM/YMM/ZMM registers are not a single full-width variable. They're calculated as multiple 8/16/32/64 bit variables (floats or integers) depending on what instruction is used. The user would need to choose the display mode.

**Comment by senyai** [comment]
Command `log "{rax} {xmm0}"` outputs `3 ???`. Is it because of this issue?

**Comment by mrexodia** [comment]
xmm0 is not a register you can print this way. You could write a plugin
that does though.

**Comment by torusrxxx** [comment]
Nobody uses MMX anymore.
