### ISSUE TITLE
Add an interface to allow GUI and plugins to save data in the database

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#763]
`jansson` is already included in the plugin sdk.

**Comment by mrfearless** [comment]
Might be handy to also expose certain default paths for plugins (and/or scripts) to use:

Could be default variables obtained via a function call or a structure passed back or something like that?

x64dbg_ini - stores a path to x32dbg.ini/x64dbg.ini for example m:\x64dbg\x32\x32dbg.ini
x64dbg_root_folder - stores path to root folder containing exe - m:\x64dbg\x64\
x64dbg_plugins_folder - stores path to plugins folder: m:\x64dbg\x32\plugins\
x64dbg_db_folder - stores path to db folder: m:\x64dbg\x64\db\

Maybe a _plugin_getpaths function that returns a structure with the path information populated for some locations that might be required.

**Comment by mrexodia** [comment]
Yeah sounds like a good idea!

**Comment by wynick27** [comment]
I think we need apis for both local setting storage and global setting storage.

**Comment by mrexodia** [comment]
There is already an api for global settings (the ini). For local I assume
you mean per debuggee settings? That should be implemented once we export
the database api.
