### ISSUE TITLE
Bug When Trying To Debug iTunes 64-Bit

### ISSUE THREAD

**Issue by falhumai** [x64dbg/x64dbg#765]
It always crashes upon startup when trying to debug iTunes. Any fix to this problem?

**Comment by mrexodia** [comment]
What version of iTunes and what operating system? Please provide direct links to the setup.

**Comment by falhumai** [comment]
Hi,
Sorry if I made a confusion, but the is the one that crashes, x64dbg. Anyways, so the version of iTunes I have is 12.4.0.119, and I am using the latest version of x64dbg. I am using Windows 10 as my OS. The scenario is that every time I run iTunes through x64dbg, and I skip all the system breakpoints made from the start and run without stopping at any exceptions, the iTunes app start for about 1 second and crashes. The same thing almost happens when I attach to the iTunes process. iTunes will crash after some seconds after attaching to it.

**Comment by falhumai** [comment]
So,
I tried the same thing with Windbg and iTunes crashes as well. I guess it is not a problem of x64dbg itself. It's just that iTunes is protected from debugging.

**Comment by mrexodia** [comment]
You should try scyllahide. See github.com/x64dbg/ScyllaHide (there is a
link to appveyor with artifacts there).
