### ISSUE TITLE
[Minor UI Bug] Dump Window Size/Re-Size Constrain

### ISSUE THREAD

**Issue by AxDSan** [x64dbg/x64dbg#767]
Hi, 

Problem: Size constrains stays widely opened to the right of the screen leaving an open space to the left and the user without the ability to shrink it down or to reset it.

Reproduce: 
1. At the Dump Window, Right Click, select 'Text' -> 'ASCII' Close x32/64DBG.
2. Re-Open x32/64DBG, At the Dump Window, Right Click, Select 'Hex' -> 'ASCII'.

I understand this is a minor ui bug, and will probably end up in the TODO list so anyways just wanted to report it.

Best Regards!
AxDSan

**Comment by AxDSan** [comment]
Hello,

I see this problem has been already reported:
https://forum.tuts4you.com/topic/35915-feature-suggestions/?do=findComment&comment=183610

please close my issue.

Cheers!

**Comment by mrexodia** [comment]
It was also already fixed. The dump no longer saves the position. Did I push a bad fix or are you on an older snapshot?

**Comment by mrexodia** [comment]
Also this is not a duplicate report. This is the right place to report issues

**Comment by mrexodia** [comment]
Is this what you mean @AxDSan http://www53.zippyshare.com/v/xcluE8mo/file.html

**Comment by AxDSan** [comment]
@mrexodia Nope, this is what I meant:

https://i.imgur.com/yMfcQ5L.gifv

Thanks for looking into this issue! :ok_hand: 
Appreciated!

Best Regards,
AxDSan

**Comment by mrexodia** [comment]
Yes this has been fixed.

**Comment by AxDSan** [comment]
@mrexodia Alrighty then! Thank you for working on it :dart:
