### ISSUE TITLE
missing GUI icons

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#775]
Not all actions have icons from http://p.yusukekamiyamane.com yet, needs appropriate icons.

**Comment by mrexodia** [comment]
# Missing Icons

## Disassembly

[ ] Binary -> Edit
[ ] Binary -> Fill
[ ] Binary -> Fill with NOPs
[ ] Binary -> Copy
[ ] Binary -> Paste
[ ] Binary -> Paste (Ignore Size)
[ ] Copy -> Selection
[ ] Copy -> Selection (No Bytes)
[ ] Copy -> Address
[ ] Copy -> RVA
[ ] Copy -> Disassembly
[ ] Breakpoint -> Edit
[ ] Breakpoint -> Toggle
[ ] Breakpoint -> Set Hardware on Execution
[ ] Breakpoint -> Remove Hardware
[ ] Breakpoint -> Set Hardware on Execution -> Replace Slot 1
[ ] Breakpoint -> Set Hardware on Execution -> Replace Slot 2
[ ] Breakpoint -> Set Hardware on Execution -> Replace Slot 3
[ ] Breakpoint -> Set Hardware on Execution -> Replace Slot 4
[ ] Decompile -> Selection
[ ] Decompile -> Function
[ ] Search For -> Current Region
[ ] Search For -> Current Module
[ ] Search For -> All Modules
[ ] Search For -> * -> Command
[ ] Search For -> * -> Constant
[ ] Search For -> * -> String references
[ ] Search For -> * -> Pattern

## Dump

[ ] Binary menu (from Disasm)
[ ] Copy menu (from Disasm)
[ ] Follow DWORD/QWORD in Disassembler
[ ] Follow DWORD/QWORD in Current Dump
[ ] Follow DWORD/QWORD in Dump N
[ ] Breakpoint -> Hardware, Access
[ ] Breakpoint -> Hardware, Write
[ ] Breakpoint -> Hardware, Execute
[ ] Breakpoint -> Hardware, * -> Byte
[ ] Breakpoint -> Hardware, * -> Word
[ ] Breakpoint -> Hardware, * -> Dword
[ ] Breakpoint -> Hardware, * -> Qword
[ ] Breakpoint -> Memory, Access
[ ] Breakpoint -> Memory, Write
[ ] Breakpoint -> Memory, Execute
[ ] Breakpoint -> Memory, * -> Singleshoot
[ ] Breakpoint -> Memory, * -> Restore on hit
[ ] Hex/Text -> ASCII
[ ] Hex/Text -> Extended ASCII
[ ] Hex/Text -> Codepage...
[ ] Integer -> Signed short (16-bit)
[ ] Integer -> Signed long (64-bit)
[ ] Integer -> Signed long long (64-bit)
[ ] Integer -> Unsigned short (16-bit)
[ ] Integer -> Unsigned long (32-bit)
[ ] Integer -> Unsigned long long (64-bit)
[ ] Integer -> Hex short (16-bit)
[ ] Integer -> Hex long (32-bit)
[ ] Float -> Float (32-bit)
[ ] Float -> Double (64-bit)
[ ] Float -> Long double (80-bit)
[ ] Integer -> Hex long long (64-bit)

## Stack

[ ] Binary menu (from Disasm)
[ ] Copy menu (from Disasm)
[ ] Breakpoint menu (from Dump)
[ ] Follow DWORD/QWORD in Dump N

## Arguments

[ ] Follow X in Disassembler
[ ] Follow X in Dump
[ ] Copy menu (from Disasm)

## Info widget

[ ] Follow in Dump
[ ] Copy menu (from Disasm)

## Symbols

[ ] Left -> Follow in Disassembler
[ ] Left -> Follow Entry Point in Disassembler
[ ] Left -> Download Symbols for This Module
[ ] Left -> Download Symbols for all Modules
[ ] Left -> Copy File Path
[ ] Left -> Mark as user module
[ ] Left -> Mark as party...
[ ] Left -> Search..
[ ] Left -> Copy menu (from Disasm)
[ ] Right -> Follow in Disassembler
[ ] Right -> Toggle Breakpoint
[ ] Right -> Toggle Bookmark
[ ] Search...
[ ] Copy menu (from Disasm)

## StdTable

[ ] Copy -> Line
[ ] Copy -> Cropped Table
[ ] Copy -> Full Table

**Comment by mrfearless** [comment]
All icons previewed here are packaged in a zip: [x64dbg_#775_newer_icons.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/x64dbg_%23775_newer_icons.zip)

# Disassembly
## Binary
Link to gallery (http://postimg.org/gallery/d6r5d17u/)

![](https://s20.postimg.org/k4l8cp3fh/binary_edit.png) Binary -> Edit 
![](https://s20.postimg.org/vi7rnwdy5/binary_fill.png) Binary -> Fill 
![](https://s20.postimg.org/8usihqye5/binary_fill_nop.png) Binary -> Fill with NOPs 
![](https://s20.postimg.org/r6j5yw719/binary_copy.png) Binary -> Copy 
![](https://s20.postimg.org/k8jn6oyal/binary_paste.png) Binary -> Paste 
![](https://s20.postimg.org/mr5c7dk0t/binary_paste_ignoresize.png) Binary -> Paste (Ignore Size)

## Copy
Link to gallery (http://postimg.org/gallery/2mh3aw60a/)

![](https://s20.postimg.org/dxjhne3dp/copy_selection.png) Copy -> Selection
![](https://s20.postimg.org/b4qa3d319/copy_selection_no_bytes.png)Copy -> Selection (No Bytes)
![](https://s20.postimg.org/ex9sj3ijh/copy_address.png) Copy -> Address
![](https://s20.postimg.org/ex9sj3ijh/copy_address.png) Copy -> RVA - same or need different?
![](https://s20.postimg.org/5qrhvtdb1/copy_disassembly.png) Copy -> Disassembly

## Breakpoint
Link to gallery (http://postimg.org/gallery/2wxslpze2/)

![](https://s20.postimg.org/w1hgawuql/breakpoint_edit.png) or ![](https://s20.postimg.org/evm2kgckd/breakpoint_write.png) Breakpoint -> Edit
![](https://s20.postimg.org/60z0f5rx9/breakpoint_toggle.png) Breakpoint -> Toggle
![](https://s20.postimg.org/bsu2p6vfh/breakpoint_add.png) Breakpoint -> Set Hardware on Execution - or normal breakpoint image
![](https://s20.postimg.org/bnqbfio4d/breakpoint_remove.png) Breakpoint -> Remove Hardware
![](https://s20.postimg.org/dn6x6xifx/breakpoint_execute_slot1.png) Breakpoint -> Set Hardware on Execution -> Replace Slot 1
![](https://s20.postimg.org/t9y6kaw7x/breakpoint_execute_slot2.png) Breakpoint -> Set Hardware on Execution -> Replace Slot 2
![](https://s20.postimg.org/4hykd2f19/breakpoint_execute_slot3.png) Breakpoint -> Set Hardware on Execution -> Replace Slot 3
![](https://s20.postimg.org/hne2j68wt/breakpoint_execute_slot4.png) Breakpoint -> Set Hardware on Execution -> Replace Slot 4
![](https://s20.postimg.org/5o2kbv3bx/breakpoint_settings.png) Extra: Breakpoint Settings

## Decompile 
Link to gallery (http://postimg.org/gallery/35h4n1r3e/)

![](https://s20.postimg.org/9s8l1h5lp/decompile_selection.png) Decompile -> Selection
![](https://s20.postimg.org/pp7cy6xzx/decompile_function.png) Decompile -> Function

## Search For
Link to gallery (http://postimg.org/gallery/voeyjsru/)

![](https://s20.postimg.org/5zp2lqq3h/search_current_region.png) Search For -> Current Region
![](https://s20.postimg.org/fvq5ldvvh/search_current_module.png) Search For -> Current Module
![](https://s20.postimg.org/zcav7wqzh/search_all_modules.png) Search For -> All Modules
![](https://s20.postimg.org/ejd1x8ntp/search_for_command.png) Search For -> * -> Command
![](https://s20.postimg.org/ao9nuo4nx/search_for_constant.png) Search For -> * -> Constant
![](https://s20.postimg.org/gezu8ecnx/search_for_string.png) Search For -> * -> String references
![](https://s20.postimg.org/3mbq8h125/search_for_pattern.png) Search For -> * -> Pattern

# Dump
## Follow
Link to gallery (http://postimg.org/gallery/37z64dyzu/)

![](https://s20.postimg.org/66pqlji59/follow_in_cpu.png) Follow DWORD/QWORD in Disassembler - or normal cpu image
![](https://s20.postimg.org/keffa6uu5/follow_in_dump.png) Follow DWORD/QWORD in Current Dump - or normal dump truck image
![](https://s20.postimg.org/3rxv141wd/follow_in_dump1.png) ![](https://s20.postimg.org/g7ukuuv8d/follow_in_dump2.png) ![](https://s20.postimg.org/fwd4i3esd/follow_in_dump3.png) ![](https://s20.postimg.org/5nknc9qql/follow_in_dump4.png) ![](https://s20.postimg.org/ohb1n0ecd/follow_in_dump5.png) Follow DWORD/QWORD in Dump N - or normal dump truck image

not sure if these suit, perhaps or perhaps not?

## Breakpoint
Link to gallery (http://postimg.org/gallery/1f5wqx9ii/)

![](https://s20.postimg.org/gm0i874pp/breakpoint_access.png) Breakpoint -> Hardware, Access
![](https://s20.postimg.org/evm2kgckd/breakpoint_write.png) Breakpoint -> Hardware, Write
![](https://s20.postimg.org/dj4dikf4t/breakpoint_execute.png) Breakpoint -> Hardware, Execute
![](https://s20.postimg.org/nqibh8bz1/breakpoint_byte.png) Breakpoint -> Hardware, * -> Byte
![](https://s20.postimg.org/jszn5kejh/breakpoint_word.png) Breakpoint -> Hardware, * -> Word
![](https://s20.postimg.org/61v63cplp/breakpoint_dword.png) Breakpoint -> Hardware, * -> Dword
![](https://s20.postimg.org/psne97zbx/breakpoint_qword.png) Breakpoint -> Hardware, * -> Qword
![](https://s20.postimg.org/h4091sjod/breakpoint_memory_access.png) Breakpoint -> Memory, Access
![](https://s20.postimg.org/3s71slgnx/breakpoint_memory_write.png) Breakpoint -> Memory, Write
![](https://s20.postimg.org/4dw0opbq5/breakpoint_memory_execute.png) Breakpoint -> Memory, Execute
![](https://s20.postimg.org/qsdp4xehp/breakpoint_memory_singleshot.png) Breakpoint -> Memory, * -> Singleshoot
![](https://s20.postimg.org/xubmr4i3h/breakpoint_memory_restore_on_hit.png) Breakpoint -> Memory, * -> Restore on hit

## Hex-Text
Link to gallery (http://postimg.org/gallery/1i85wq6p6/)

![](https://s20.postimg.org/pl4cqgdr1/ascii.png) Hex/Text -> ASCII
![](https://s20.postimg.org/r1fv8lgnx/ascii_extended.png) Hex/Text -> Extended ASCII
![](https://s20.postimg.org/8adxyfm3h/unicode.png) Hex/Text -> Codepage... - unicode? or some other image? a world/globe image maybe?

# Arguments
![](https://s20.postimg.org/66pqlji59/follow_in_cpu.png) Follow X in Disassembler - or normal cpu image
![](https://s20.postimg.org/keffa6uu5/follow_in_dump.png) Follow X in Dump - or normal dump truck image

# Info widget

![](https://s20.postimg.org/keffa6uu5/follow_in_dump.png) Follow in Dump- or normal dump truck image

# Symbols
Link to gallery (http://postimg.org/gallery/2v88hkxnu/)

![](https://s20.postimg.org/66pqlji59/follow_in_cpu.png) Left -> Follow in Disassembler - or normal cpu image
![](https://s20.postimg.org/fophll3tp/entrypoint.png) or ![](https://s20.postimg.org/bgupcu2e5/follow_entrypoint.png) Left -> Follow Entry Point in Disassembler - or normal cpu image
![](https://s20.postimg.org/k8k3q2f8d/download_symbols.png) Left -> Download Symbols for This Module
![](https://s20.postimg.org/k8k3q2f8d/download_symbols.png) Left -> Download Symbols for all Modules - not sure if needs a different image?
![](https://s20.postimg.org/4yfn54ucd/copyfilepath.png) Left -> Copy File Path - unsure of this one
Left -> Mark as user module
Left -> Mark as party...
Left -> Search..
![](https://s20.postimg.org/66pqlji59/follow_in_cpu.png) Right -> Follow in Disassembler - or normal cpu image
![](https://s20.postimg.org/ehpbylhul/breakpoint_toggle.png) Right -> Toggle Breakpoint
![](https://s20.postimg.org/9hrvqnc7x/bookmark_toggle.png) Right -> Toggle Bookmark
Search...
![](https://s20.postimg.org/6g5oufogt/pdb.png) - Extra - pdb

# StdTable
Link to gallery (http://postimg.org/gallery/nzefx2zu/)

![](https://s20.postimg.org/8e7reorkt/copy_table_line.png) Copy -> Line
![](https://s20.postimg.org/hw7ieqd99/copy_cropped_table.png) Copy -> Cropped Table
![](https://s20.postimg.org/ltus4502l/copy_full_table.png) Copy -> Full Table

Feel free to use or not use any of them.

**Comment by mrexodia** [comment]
Thanks a lot! However, this foot icon is already used for tracing but it
doesn't really matter, that one is only used once so it's easier to replace
it.

**Comment by mrfearless** [comment]
Additional threads icons [thread.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/thread.zip)

# Threads

Link to gallery (http://postimg.org/gallery/ni1arwbu/)

![](https://s20.postimg.org/4w19ysdy5/thread_switch.png) Switch Thread
![](https://s20.postimg.org/op8sdr1y5/thread_pause.png) Suspend Thread
![](https://s20.postimg.org/6791799jx/thread_resume.png) Resume Thread
![](https://s20.postimg.org/53tysev8d/thread_kill.png) Kill Thread
![](https://s20.postimg.org/hkvkigk2l/thread_setpriority.png) or ![](https://s20.postimg.org/prnka1a59/thread_setpriority_alt.png) Set Priority
![](https://s20.postimg.org/8og70s42l/thread_entry.png) Go to Thread Entry

![](https://s20.postimg.org/myprc9kf1/thread_priority_above_normal.png) Set Priority -> Above Normal
![](https://s20.postimg.org/xa244xc4d/thread_priority_below_normal.png) Set Priority -> Below Normal 
![](https://s20.postimg.org/moi8sx5st/thread_priority_highest.png) Set Priority -> Highest
![](https://s20.postimg.org/vxp0gs42l/thread_priority_idle.png)  Set Priority -> Idle
![](https://s20.postimg.org/ngpi5uzdp/thread_priority_lowest.png) Set Priority -> Lowest
![](https://s20.postimg.org/ea77iku59/thread_priority_normal.png) Set Priority -> Normal
![](https://s20.postimg.org/oyayhf44d/thread_priority_timecritical.png) Set Priority -> Time Critical

**Comment by mrfearless** [comment]
# Breakpoint Tab - Right Click Menu
Link to gallery (http://postimg.org/gallery/1yso2aaui/)
Zip: [breakpoint.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/breakpoint.zip)

![](https://s20.postimg.org/i0w7k1eot/breakpoint_remove.png) Remove
![](https://s20.postimg.org/3zk7yhb4t/breakpoint_disable.png) Disable
![](https://s20.postimg.org/qqtakvw65/breakpoint_edit.png) or ![](https://s20.postimg.org/ah34hzli5/breakpoint_editcaret.png) Edit
![](https://s20.postimg.org/4b69ozgyl/breakpoint_reset_hitcount.png) Reset hit count
![](https://s20.postimg.org/b95sh6pp9/breakpoint_enable_all.png) Enable All
![](https://s20.postimg.org/4dljy2v8d/breakpoint_disable_all.png) Disable All
![](https://s20.postimg.org/73zh90hb1/breakpoint_remove_all.png) Remove All

Extra:
![](https://s20.postimg.org/q3udvcza5/breakpoint_enable.png) Enable

**Comment by mrfearless** [comment]
# Memory Map Tab - Right Click Menu
Links to gallery (http://postimg.org/gallery/gpar4tii/)
Zip: [memorymap.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/memorymap.zip)

![](https://s20.postimg.org/fdbcnfb19/memmap_alloc_memory.png) Allocate memory
![](https://s20.postimg.org/55stb0ot9/memmap_free_memory.png) Free memory
![](https://s20.postimg.org/428oz2465/memmap_find_address_page.png) Find address page
![](https://s20.postimg.org/ip9ngq2sd/memmap_set_page_memory_rights.png) Set Page Memory Rights
![](https://s20.postimg.org/4hjys2q3h/memmap_memory_breakpoint.png) Memory Breakpoint

**Comment by mrexodia** [comment]
Really nice, thanks a lot! I put in some of the icons I'll try to add in
these as soon as possible :)

**Comment by mrfearless** [comment]
# References - Right Click Menu
Link to gallery (http://postimg.org/gallery/2c3cu6kiy/)
Zip: [Refs.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/Refs.zip)

Toggle breakpoint (same icon as above from Disassembly->Breakpoint)
![](https://s20.postimg.org/qn8nw45gd/breakpoint_remove_all_commands.png) Set breakpoint on all commands
![](https://s20.postimg.org/bfsobrdlp/breakpoint_seton_all_commands.png) Remove breakpoint on all commands

**Comment by mrfearless** [comment]
# Dump - Integer Icons
Link to gallery (http://postimg.org/gallery/13gwupnl6/)
Zip: [integer.zip](https://dl.dropboxusercontent.com/u/17077376/x64dbgicons/integer.zip)

Not sure about these, made a couple playing round with the idea, might have to just assign the basic ones (16bit, 32bit, 64bit, 80bit if the text on the others look a little shitty - which it does look)

Other option is to use the notification numbers: 16, 32, 64 and 80: ![](https://s20.postimg.org/bv0d4ux0d/image.png) ![](https://s20.postimg.org/oax2ylqcd/image.png) ![](https://s20.postimg.org/ftxknolnh/image.png) ![](https://s20.postimg.org/dyasciwt9/image.png)

Basic Ones:

![](https://s20.postimg.org/e78d2g9lp/16bit.png)
![](https://s20.postimg.org/axpci8w4d/32bit.png)
![](https://s20.postimg.org/w3j5cu6xp/64bit.png)
![](https://s20.postimg.org/ivjrjw9el/80bit.png)

Difficult to incorporate signed vs unsigned in the icon, so just a bit more info text-wise:

Integer:
![](https://s20.postimg.org/am7w5hfod/16bit_short.png)
![](https://s20.postimg.org/eerel7v6l/32bit_long.png)
![](https://s20.postimg.org/komo87ul9/64bit_long.png)

Float:
![](https://s20.postimg.org/x8d7i7tel/32bit_float.png)
![](https://s20.postimg.org/l2o07teot/64bit_float.png)
![](https://s20.postimg.org/6fn1q5g2l/80bit_float.png)

**Comment by mrfearless** [comment]
fatcow farmfresh icons have a collection of country flags that could be used for the languages menu and submenu - the languages menu item can be set to the current language and when selecting another language from the submenu it could update the language menu item icon.

![](https://s20.postimg.org/xi5zoi999/flags.png)

http://www.fatcow.com/free-icons

**Comment by torusrxxx** [comment]
New menu entries:

- [ ] Increase 8
- [ ] Decrease 8
- [ ] Push
- [ ] Pop
- [ ] Create New Thread Here
- [ ] Browse in Explorer (Modules)

**Comment by torusrxxx** [comment]
New menu entries:
- [ ] Animate into
- [ ] Animate over
- [ ] Animate command

**Comment by mrfearless** [comment]
Hopefully these suit as its based on a frequency or time frame. If not let me know.
![](https://s20.postimg.org/fhlg8xiql/animate_into.png) Animate into
![](https://s20.postimg.org/cc0uiq04d/animate_over.png) Animate Over
![](https://s20.postimg.org/ckyf8ncwt/animate_cmd.png) or ![](https://s20.postimg.org/9fdtifual/animate_command.png) Animate Command

**Comment by mrfearless** [comment]
Optional icons for push/pop:
![](https://s20.postimg.org/p63y96jvh/push.png) push
![](https://s20.postimg.org/bp1xt738d/pop.png) pop

**Comment by mrfearless** [comment]
![](https://s20.postimg.org/ovinkm13x/thread_new.png) Create new thread here

**Comment by mrfearless** [comment]
For the browse in explorer (symbol-modules) fugue has two icons that could represent this:
![](http://p.yusukekamiyamane.com/icons/search/fugue/icons/computer.png)
![](http://p.yusukekamiyamane.com/icons/search/fugue/icons/folder-tree.png)

**Comment by mrexodia** [comment]
@mrfearless Thanks again for all the icons! I have now added most of them.

**Comment by mrfearless** [comment]
cool, let me know if there are any others that need icons for (future or presently) and i can work some of them up.
