### ISSUE TITLE
rename dqword to xmmword?

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#777]
Not sure what to do, capstone uses `xmmword` I just came up with `dqword` myself. Which one to use?

**Comment by wynick27** [comment]
MASM supports xmmword and oword, c++ have __m128, __m128d and __m128i. Currently display name can be changed to long or short, there is a map in the QBeaEngine.cpp and I already added a option for it, maybe we can add more options.

**Comment by mrexodia** [comment]
Renamed to `xmmword`.
