### ISSUE TITLE
heap corruption issues

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#786]
Certain actions cause heap corruptions near `DisassembleAt` and `MemRead` (probably related to changes to the disasm engine). If any other people find heap corruption crashes please comment in this thread.

Coverity had memory corruptions in `_global.cpp` and `module.cpp` (invalid parameters to winapi, `sizeof` instead of `_countof`). There are also various uninitialized members in the new code.

This error was emitted but Visual Studio crashed after that `Unhandled exception at 0x00007FFA1454184E (ntdll.dll) in x64dbg.exe: A LIST_ENTRY has been corrupted (i.e. double remove).`

Possibly related to invalid read sizes being passed to `MemRead` (invalid write pointer message was triggered).

Executable: `overwatch.exe`, version `1.4.29666` remove all breakpoints, hide with ScyllaHide, run and first chance exception will not disassemble there correctly. Doing random actions will cause heap corruption. Issues are caused by a page with the `NO_ACCESS` flag apparently...

I will add more information as I find it.

**Comment by Nukem9** [comment]
enable heap debugging and/or callstack traces

**Comment by mrexodia** [comment]
Isn't it enabled in debug mode per default? Sadly I cannot reproduce it in
debug mode...

**Comment by mrexodia** [comment]
I believe these are fixed now.
