### ISSUE TITLE
Instructions are decoded/displayed incorrectly

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#789]
That's the `Entry Breakpoint` of `x32dbg.exe`
![untitled](https://cloud.githubusercontent.com/assets/11916365/16291408/ec19be82-3906-11e6-9b1e-c4f227292372.png)

Single stepping and all debugging actions are working fine.
- Using `snapshot_2016-06-23_04-57.7z`
- OS: Win10 x64

**Comment by torusrxxx** [comment]
confirmed on 32bit release.

**Comment by torusrxxx** [comment]
This problem can be resolved by reverting capstone to an earlier version.

**Comment by wk-952** [comment]
It seems that on the 64-bit version of the debugger, all instructions are assumed to be using `DS` segment register even if they're not, hence, the segment register opcode is ignored (or at least that's how it seems to be).

Old snapshot from 6/15:
![06-15](https://cloud.githubusercontent.com/assets/11916365/16298251/c49e03a8-3934-11e6-8215-05850a9a9e9e.png)

Latest snapshot:
![06-23](https://cloud.githubusercontent.com/assets/11916365/16298286/fdff72b2-3934-11e6-895f-9ef33cc0d5c6.png)

**Comment by mrexodia** [comment]
Hm I will revert back to an older capstone...

**Comment by mrexodia** [comment]
Possibly this is introduced by #758 there was a bug in the code but @wynick27 didn't provide a fix yet.
