### ISSUE TITLE
handle view

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#79]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/79
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:13:57.001

**Comment by torusrxxx** [comment]
I've added the GUI. However the related features are only found deep in the TitanEngine. I have to pop them up through the dbg and the bridge. Working.
![x64dbg handles view](https://cloud.githubusercontent.com/assets/15761310/15563783/97fc4b06-22fb-11e6-91dc-a195971ee13a.png)
The table at the top is Handles(`HandlerEnumerateOpenHandles()`). The table in the middle is TCP connections(`GetTcpTables()`). The table at the bottom is Privileges(`LookupPrivilegeValue()`).
And, how often are you upgrading the TitanEngine? I find it quite old now.

**Comment by mrexodia** [comment]
TitanEngine will not be updated.

**Comment by torusrxxx** [comment]
TitanEngine's `HandlerEnumerateOpenHandles()` doesn't work as expected, and it wastes me lots of time digging into the disassembly of it.

**Comment by mrexodia** [comment]
The code should be available here
https://bitbucket.org/titanengineupdate/titanengine-update

**Comment by torusrxxx** [comment]
I have already reimplemented it in a separate source file.

**Comment by torusrxxx** [comment]
In my opinion enumeration of handles, tcp connections and privileges should be implemented in the debug engine instead of in the x64dbg project. It messes up the source code.

**Comment by mrexodia** [comment]
Should be implemented now.

**Comment by ThunderCls** [comment]
Any chance of getting something like this but for the debugged app windows?, something like the windows manager olly has?

**Comment by torusrxxx** [comment]
Already mentioned in #989. Almost all the information can,be get with
EnumWindows and appropiate APIs, but I don't know how to get the Window
procedure from another process(GetWindowLong does a check) and that's the
blocker.

**Comment by mrexodia** [comment]
So just ignore the window proc for now?

**Comment by ThunderCls** [comment]
@torusrxxx I don't get it...what kind of check you mean that GetWindowLong does? What's the issue with that?
