### ISSUE TITLE
CPU disassembler getting lost, creating invalid opcode messages

### ISSUE THREAD

**Issue by BillHeckel** [x64dbg/x64dbg#795]
Note the 6th instruction in the CPU window compared with the same opcodes in Scylla.

![x86dbg-invinst](https://cloud.githubusercontent.com/assets/3452543/16311486/734c56d8-3936-11e6-9d0f-80ee9ff216f8.jpg)

This is a clean install of the current build on windows 10 with all symbols loaded.

**Comment by mrexodia** [comment]
![s](http://i.imgur.com/JqcAwca.png) this issue has been recently reported and fixed. Thanks!
