### ISSUE TITLE
Trable in DisASM

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#796]
x64dbg:
0000000143044B56 | 4C 8D 44 24 50                       | LEA R8, QWORD PTR SS:[RSP + 50]  
0000000143044B5B | 48                                            | ???  
0000000143044B5C | C7 44 24 50 00 00 00 00        | MOV DWORD PTR SS:[RSP + 50], 0 
------------------
0000000143044B56 | 4C 8D 44 24 50                       | LEA R8, QWORD PTR SS:[RSP + 50]  
0000000143044B5B | 48 C7 44 24 50 00 00 00 00   | MOV DWORD PTR SS:[RSP + 50], 0

**Comment by mrexodia** [comment]
already reported and fixed

**Comment by Paliha** [comment]
good...))

**Comment by mrexodia** [comment]
See http://releases.x64dbg.com
