### ISSUE TITLE
"UTF-16" menu option is not the same as selecting codepage then "UTF-16"

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#798]
In the dump window, the following 2 options produces different results
- Option 1:
right click --> `Hex` --> `UTF-16`
- Option 2:
right click --> `Hex` --> `Codepage` --> `UTF-16`

As a test, i wrote the word `hello` in russian (`Здравствуйте`) in a `UTF-16` format,
using option 1 won't display it correctly, but using option 2 displays it correctly.
 
What am i missing here ?

**Comment by mrexodia** [comment]
The description is just incorrect. One of them is really utf16 the other
one is just extended ascii.

**Comment by wk-952** [comment]
Oh!, that makes sense then.
Thank you.
