### ISSUE TITLE
step to user code

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#80]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/80
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:14:05.964

**Comment by pandasauce** [comment]
What needs to happen for this to get implemented? Any pointers?

**Comment by mrexodia** [comment]
Not really, someone looked in to it for me (how olly does it) but I don't
remember from the top of my head what was happening.

I think it was something with tracing until rip points somewhere inside a
user module.

**Comment by torusrxxx** [comment]
I have finished implementing this feature, however I'm too tired to push it now. Going to sleep.
![x64dbg-usr-code-reached](https://cloud.githubusercontent.com/assets/15761310/16158426/b19af87e-34ac-11e6-8d79-fe0a395a0d4d.png)

**Comment by mrexodia** [comment]
Cool! Have a good night!

**Comment by mrexodia** [comment]
Should be implemented now.
