### ISSUE TITLE
The debugger does not switch to another thread if the current thread terminates

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#800]

**Comment by mrexodia** [comment]
I have a fix on my local branch. I'm testing it now.

**Comment by mrexodia** [comment]
resolved by switching to the main thread.

**Comment by torusrxxx** [comment]
Nope, I have some executables which intentionally exits from its main thread and runs on a secondary thread.

**Comment by mrexodia** [comment]
doesn't that terminate the process? I will push a fix.

Op vr 24 jun. 2016 om 17:46 schreef Torusrxxx <notifications@github.com>:

**Comment by torusrxxx** [comment]
From [https://msdn.microsoft.com/en-us/library/windows/desktop/ms686722(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686722(v=vs.85).aspx)

How Processes are Terminated

- A process executes until one of the following events occurs:
- Any thread of the process calls the ExitProcess function. Note that some implementation of the C run-time library (CRT) call ExitProcess if the primary thread of the process returns.
- The last thread of the process terminates.
- Any thread calls the TerminateProcess function with a handle to the process.
- For console processes, the default console control handler calls ExitProcess when the console receives a CTRL+C or CTRL+BREAK signal.
- The user shuts down the system or logs off.

**Comment by mrexodia** [comment]
Okay now if the main thread doesn't work it will choose the first thread from the list.
