### ISSUE TITLE
Breakpoint hit count correlation analysis

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#802]
Basic idea is to build a tree structure from all the breakpoints, so that for any parent node, its hit counter is exactly equal to the sum of all direct children's hit counters. Then the program will show the graph in a dialog. Child nodes are allowed to be used multiple times. This analysis is informative. It is allowed to display any one of them when there are many possible solutions i. But it is better to allow the user to switch to a next one.
_I have not come up with a good algorithm to do it. Any ideas?_

**Comment by mrexodia** [comment]
Shouldn't be too hard to implement, might require some AI though. Don't you think this is more something to do for a plugin though?

**Comment by torusrxxx** [comment]
Yes. But this feature is too insignificant to become a standalone plugin.

**Comment by mrexodia** [comment]
Well nothing is too insignificant as a plug-in 😀

**Comment by torusrxxx** [comment]
Maybe some day I will create a "x64dbg easy" plugin that collects all these
tiny features together. Do you know any algorithm to do such analysis
efficiently among thousands of breakpoints?

**Comment by mrexodia** [comment]
From the top of my head I have no idea. You can probably try a greedy algorithm that sorts the nodes by size and takes the highest and tries to find two other nodes that add to this value, then repeat. If an invalid tree was found (eg values dont equal), backtrack and try three nodes. Pretty damn slow, but might work.

**Comment by jvoisin** [comment]
It seems to be a simplified [knapsack]( https://en.wikipedia.org/wiki/Knapsack_problem ) problem, which is NP-complete.

**Comment by torusrxxx** [comment]
It does not really fit in the definition of knapsack problem. The hit counters must sum up exactly equal to the parent node, instead of less and equal.

**Comment by jvoisin** [comment]
Maybe it's just me that failed to understand the issue in the first place :)

**Comment by mrexodia** [comment]
Currently fooling around with it. Some observations so far:

- The root always has to be the breakpoint with the biggest counter to include all breakpoints
- Trees can be infinitely deep by adding themselves as their child
- Nodes with 0 can be placed infinitely all over the tree
- It might not be always possible to form this tree: `10, 2`

**Comment by torusrxxx** [comment]
To those who still do not get the idea yet:

You debug the following virtualized program:

```
function main() // <-breakpoint1
{
subroutine_1();
if(condition)
subroutine_2();
else
subroutine_3();
subroutine_4();
}

function subroutine_1() // <-breakpoint2
{
subroutine_5();
}

function subroutine_2() // <-breakpoint3
{
}

function subroutine_3() // <-breakpoint4
{
subroutine_5();
}

function subroutine_4() // <-breakpoint5
{
subroutine_5();
}

function subroutine_5() // <-breakpoint6
{
}

function subroutine_6() // <-breakpoint7
{
}
```

You run main() four times, then you probably get the hit counters:

breakpoint1 : 4
breakpoint2 : 4
breakpoint3 : 3
breakpoint4 : 1
breakpoint5 : 4
breakpoint6 : 9
breakpoint7 : 0

We can guess the probable control flow. There are many breakpoints executed 4 times, so these breakpoints are executed sequentially probably. And we can see breakpoint3+breakpoint4 is 4 times, so it is possible that they are a pair of statements in a "if-else" statement. breakpoint6 is executed 9 times, and 9=4+4+1, so it is possible that breakpoint6 is executed twice in the main control flow, and executed once more in subroutine_3. breakpoint7 is not executed, so it is not in the control flow. A possible graph is given below:

breakpoint6 -> (breakpoint1->breakpoint3+breakpoint4)+breakpoint2+breakpoint4

Under pratical condition, it is usually the case the graph must have many roots, because there is no subroutine that is called in all control flow branches. Nodes with zero hit count can be ignored. Nodes with equal hit count can be assumed to be executed one after another, so they can be graphed as a list instead of a tree. A node cannot be the child of itself. Child node may be used many times because it is possible to call the same subroutine many times.

**Comment by jdavidberger** [comment]
I like the idea, but I think just using hit counts might be an intractable problem under most circumstances. Also, as far as I can tell, any sort of looping would be an issue. 

I think if you add a little more information though, you can get some very interesting analysis for relatively cheap. In particular, I'm thinking keep track of which breakpoint was hit directly before another breakpoint. Something as simple as 

````
hitGraph[thisBPId][lastBPId]++; 
lastBPId = thisBPId;
````

would give you a graph that you could almost just analyze visually. On top of that you could throw some generic graph algorithms at it to maybe get some automated analysis. I'm thinking you could pretty easily sort out chunks which were part of a loop -- it'd look like a subgraph with one entry point, relatively few exit points, and a ton of inter-connectivity in between.

**Comment by torusrxxx** [comment]
Yes, it will be better to add more information. This analysis is intended to be a very cheap yet useful dynamic analysis.

**Comment by torusrxxx** [comment]
Given the exponential computational complexity, I think it is out of scope now. For more info, view https://csgrid.org/csg/subset_sum/
