### ISSUE TITLE
long jump assemble broken(keystone only)

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#805]
![x64dbg-long-jump-assemble-broken](https://cloud.githubusercontent.com/assets/15761310/16362434/3fa5b7c4-3b9e-11e6-8a28-daa7a63a6f2a.png)

Both the expression validator and the error message seems to be broken.

**Comment by mrexodia** [comment]
Quite weird. It seems like keystone assembles it fine, but writing of the memory fails somehow. Notice that 08 will actually emit an octal number in keystone though.

**Comment by mrexodia** [comment]
forwarded to https://github.com/keystone-engine/keystone/issues/214
