### ISSUE TITLE
Adding an API to suspend GUI updates 

### ISSUE THREAD

**Issue by KurapicaBS** [x64dbg/x64dbg#806]
Can this feature be added because I found most of the time was wasted during GUI updates when 
I tried to write that simple tracing plugin.

It would be great the debugger will still be working but GUI won't 
refresh to new state unless the lock is removed, but the GUI shouldn't be frozen or something.

Thanks

**Comment by mrexodia** [comment]
It's already present

**Comment by mrexodia** [comment]
Well it's present but the GUI freezes. Basically we implemented tracing though, just needs a plugin interface so its high performance.

**Comment by mrexodia** [comment]
Did you try this? https://github.com/x64dbg/x64dbg/blob/development/src/bridge/bridgemain.cpp#L1003

**Comment by KurapicaBS** [comment]
This API wasn't present in the SDK I have !

Thanks a lot.

**Comment by mrexodia** [comment]
the latest version (the compile of the latest commit in the development branch) of x64dbg (with the sdk) will always be available on http://releases.x64dbg.com, which will be pushed on update every day at http://snapshots.x64dbg.com

Some snapshots are redacted if they contain blocking issues (which is actually a secret, but whatever :+1:)

**Comment by mrexodia** [comment]
So is it fixed or should I keep this open? For now I marked it as feature, but please close the issue if it does what you want.

**Comment by KurapicaBS** [comment]
I think it can be closed.
