### ISSUE TITLE
Please do not open every tabs at startup

### ISSUE THREAD

**Issue by jvoisin** [x64dbg/x64dbg#812]
Currently, every single tab are open at startup, while most of the time, you don't need every of them.

**Comment by aimtsou** [comment]
Better to be a configurable option which tabs to open

**Comment by jvoisin** [comment]
Why? If you need a tab, just open it :)

**Comment by aimtsou** [comment]
Then if you do not need a tab just close it. Come on now.

**Comment by wk-952** [comment]
It would be very irritating if you have to open every required tab at startup.

Alternatively there is an option to save tabs order, what i do is just arrange them to suit my needs and put the least used ones at the very end/right, so whenever i open the debugger they'll always be like that.

**Comment by mrexodia** [comment]
Closing tabs has been implemented but their closed state is not yet saved. #1122 is left open for that.
