### ISSUE TITLE
Register arrow and jump arrows may be confusing

### ISSUE THREAD

**Issue by jvoisin** [x64dbg/x64dbg#814]
![Arrows are confusing]( http://i.imgur.com/tQGcXO3.png )
The arrows is jumping downwards, but since there is the register (EIP) arrow, it's confusing.

**Comment by mrexodia** [comment]
Not sure what to do with this. Possibly remove the register arrow all together?

**Comment by jvoisin** [comment]
Just keep the line, or the label.

**Comment by mrexodia** [comment]
It now looks like this:

![s](http://i.imgur.com/lQd38ro.png)

**Comment by torusrxxx** [comment]
That's too bad

**Comment by mrexodia** [comment]
I couldn't think of a better solution out of the box. I left the original
code in a comment so it should be easy to revert if undesired (personally I
couldn't care less).

Op wo 6 jul. 2016 om 08:53 schreef Torusrxxx <notifications@github.com>:

**Comment by torusrxxx** [comment]
Notice the slight misalignment of the bolded down jump arrow.

**Comment by mrexodia** [comment]
I think that is because it cannot be aligned (1 pixel off). That would require some QPointF trickery possibly...

**Comment by jvoisin** [comment]
Maybe keel the arrow's line, but remove its head?

**Comment by torusrxxx** [comment]
I have come up with an idea about a new appearance. Just drew a sketch on mspaint:
![687474703a2f2f692e696d6775722e636f6d2f6c51643338726f2e706e67](https://cloud.githubusercontent.com/assets/15761310/16705822/e7c6b0ac-4585-11e6-9385-c9a3d3d563a5.png)

**Comment by jvoisin** [comment]
> Just drew a sketch on mspaint

That's the spirit!

**Comment by torusrxxx** [comment]
Can this issue be closed now, jvoisin?

**Comment by mrexodia** [comment]
Assumed to be fixed, please reopen if it's not.
