### ISSUE TITLE
Rapidly executing breakpoints causes access violation

### ISSUE THREAD

**Issue by jdavidberger** [x64dbg/x64dbg#817]
To reproduce, set a breakpoint somewhere in a loop and add 'run' as its command. 

Namely coming from [here](https://github.com/x64dbg/x64dbg/blob/development/src/dbg/dbghelp_safe.cpp#L13). 

The comment there is correct; with the lock it deadlocks almost immediately. However without it, the access violation is possible, and I expect that the reproduction instructions just stress test it, and that it can happen without a somewhat useless BP command set. 

I'm not sure what would be the preference for a fix, or I'd submit a PR. In my development environment I fixed it by adding recursive lock logic in threading.h. It is decently lightweight, but I'd understand if there was an end goal of not needing any recursive locks.

**Comment by torusrxxx** [comment]
We should not use "run", "erun", "sti" or anything like that inside a breakpoint handler. It is going to produce problems. Use the condition to resume the debuggee.

**Comment by jdavidberger** [comment]
I don't think this is purely a result of continuing in a breakpoint, I think this has a small chance to hit whenever there is a state transition from paused to running. 

I think continues in breakpoints should be handled though; albeit maybe with performance caveats. The case here was running arbitrary logic from a plugin command which included some runs. I can maybe move that to condition logic, but it isn't clear how you'd do something like run to return in this way.

**Comment by mrexodia** [comment]
You can run an async callback and use the script api that way you can do
stuff like running. The script api will also wait until the debugger is
paused again. I forgot the api name is something with 'thread' in it.

**Comment by jdavidberger** [comment]
I'll look into the API for the async stuff. But I think the access should still be guarded, no?
