### ISSUE TITLE
Jump line drawing bug (when passing by a defined function)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#823]
If there is a branch instruction that passes by a user-defined function, then the jump line along with the opcodes contained in this function will be indented to the right
![untitled](https://cloud.githubusercontent.com/assets/11916365/16590977/11e432f0-42da-11e6-83f6-72b31f5c03cd.png)

I've edited this pic in the almighty `MS Paint` just to figure out how things would look like if they weren't indented, and i guess they don't look too bad (apart from the dots that are too close to the jump line)
![edited](https://cloud.githubusercontent.com/assets/11916365/16590980/1684a7fe-42da-11e6-84d4-f61f169d4745.png)

**Comment by mrexodia** [comment]
Oh.. I forgot to do a small add there, should be an easy fix 👍

**Comment by wk-952** [comment]
Thank you very much.

**Comment by mrexodia** [comment]
No problem 👍
