### ISSUE TITLE
Feature request: Breakpoints from source view 

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#828]
Right clicking in source view, only gives a "Follow in disassembler" menu option. Would be nice to be able to toggle breakpoints from this view, doesn't require a breakpoint icon in left column where the line numbers are - but could be something to add in later as well to add completeness to this feature request. maybe even the black background with red text on the line no that has the breakpoint - similar to what is shown in the cpu view address column when a breakpoint is set.

Also maybe a "Open source file" right click menu option when the source view is empty, currently there is no right click menu for this tab, except for detach if you right click on the tab itself.

**Comment by mrexodia** [comment]
Shouldn't be too hard to implement. I was also thinking of implementing the Olly way of displaying source lines:

```
>0001 | int test() { return 0; }
 0002 | //comment (has no disasm mapping so no >)
>0003 | int blub() { return 1; }
```

**Comment by mrexodia** [comment]
![s](http://i.imgur.com/lx6YDQC.png)
