### ISSUE TITLE
Following a Constant dump

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#832]
Example if i want to follow dump 0x579d4903 in the instruction line:
57912030 | 0F B6 88 03 49 9D 57     | movzx ecx,byte ptr ds:[eax+579D4903]
that only works when eax is not 0
screenshots:
![dump](https://cloud.githubusercontent.com/assets/1159592/16709771/8f262488-461a-11e6-919c-c9db5b83e3b4.png)
![dump2](https://cloud.githubusercontent.com/assets/1159592/16709772/945b6760-461a-11e6-8f24-c612ac6242b9.png)

**Comment by mrexodia** [comment]
Shouldn't be too hard to fix. Should invert the check for constants and addresses.

**Comment by Chandlr** [comment]
inverted easy fix ? 👍

**Comment by Chandlr** [comment]
Sample binary of the issue : https://drive.google.com/open?id=0B4oj4vkQkuQfRHduWDhVZjExMDQ
