### ISSUE TITLE
Are not displayed page is in the memory card

### ISSUE THREAD

**Issue by Paliha** [x64dbg/x64dbg#836]
Hi!
Protection (Denuvo) at the stage of the loader allocates memory pages for the stolen code. In the memory map of these pages no.

**Comment by mrexodia** [comment]
Could you give more details (possibly through Telegram or Gitter or IRC)?

There has been a bug found with memory pages that are not shown but I have not been able to reproduce it so far...

**Comment by mrexodia** [comment]
This has probably been fixed (unless you were using a really old version). Please reopen when it's not fixed.

**Comment by Paliha** [comment]
Thanks for the prompt, everything works...))))
