### ISSUE TITLE
Many intra-module calls appear in intermodular call search after analyzing the module

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#841]
sample file: http://mrexodia.cf/reversing/2015/10/24/Crackme

**Comment by torusrxxx** [comment]
![x64dbg-crackme-calls](https://cloud.githubusercontent.com/assets/15761310/16765759/774786b0-4825-11e6-99a3-00d7fa86b237.png)

**Comment by mrexodia** [comment]
Should be relatively easy to fix. Need to check for the module instead of just if there is a label.

**Comment by blaquee** [comment]
This issue is fixed now. Can it be closed?

**Comment by mrexodia** [comment]
No, over my dead body!
