### ISSUE TITLE
Add CPU time into threads view

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#842]
The timing information is available via [GetThreadTimes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683237(v=vs.85).aspx).

**Comment by mrexodia** [comment]
Might also be interesting to show [QueryThreadCycleTime](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684943(v=vs.85).aspx) in that case.
