### ISSUE TITLE
Deleting bps & ignoring exception with Armadillo 1.90

### ISSUE THREAD

**Issue by 0xRumple** [x64dbg/x64dbg#845]
To reproduce the bug
1- add exception range 00000000 - FFFFFFFF
2- run
3- it won't pass the exception so shift + F9
4- it won't again... so I tried to to go inside the SEH manually by bp on the instruction that triggers the exception
5- it won't hit the software the bp so I used the hardware bp
6- didn't reach the hardware bp too !
7- I tried to try all over again by deleting bps... failed when deleting !

target: https://tuts4you.com/download.php?view.911

**Comment by mrexodia** [comment]
Smells like anti debug to me. Whats the log output?

**Comment by Z-Rantom** [comment]
Nothing really interesting in the log:

> System breakpoint reached!
> INT3 breakpoint "entry breakpoint" at <unpackme_armadillo1.90.b.EntryPoint> (00409E5E)!
> [ScyllaHide] Apply hooks again
> DLL Loaded: 5AD70000 C:\WINDOWS\system32\uxtheme.dll
> [ScyllaHide] Apply hooks again
> DLL Loaded: 77DD0000 C:\WINDOWS\system32\advapi32.dll
> [ScyllaHide] Apply hooks again
> DLL Loaded: 77E70000 C:\WINDOWS\system32\rpcrt4.dll
> [ScyllaHide] Apply hooks again
> DLL Loaded: 77FE0000 C:\WINDOWS\system32\secur32.dll
> [ScyllaHide] Apply hooks again
> DLL Loaded: 77C10000 C:\WINDOWS\system32\msvcrt.dll
> First chance exception on 7C90100B (C0000005, EXCEPTION_ACCESS_VIOLATION)!
> Last chance exception on 7C90100B (C0000005, EXCEPTION_ACCESS_VIOLATION)!

* Scylla Hide is used with Armadillo profile

**Comment by mrexodia** [comment]
The program crashed. The first chance exception was correctly passed to the
program and no exception handler handled it which means you get a crash
(last chance exception).

If you want to swallow the exception (generally a bad idea) you can use the
'con' command on the last chance exception. Generally this will introduce
the first chance exception again because you are in a crash state.

**Comment by mrexodia** [comment]
I checked the unpackmes and they don't run on Windows 8. Please reopen if this is still an issue.
