### ISSUE TITLE
ImporterGetRemoteDLLBaseEx throws an exception in the application x64dbg

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#846]
code here 
```
		  Invoke TitanGetProcessInformation
    				mov rax, [rax].PROCESS_INFORMATION.hProcess
    					mov hProcess_, rax		
lea rax, sntDLL
	invoke ImporterGetRemoteDLLBaseEx,hProcess_,rax
```
descriptors - 
ImporterGetRemoteDLLBaseEx gets the remote DLL base for a specified file. This function does not
require that the remote module is loaded locally. Parameters
hProcess
[in] Handle of the process which will be queried for local module presence.
szModuleName
[in] Name of the module inside the remote process whose loaded base address will be
returned.
```
 ImporterGetRemoteDLLBaseEx(
HANDLE hProcess,
char* szModuleName
);
```
Perhaps this happens because of a stack fault, but I create custom prologue, which would not allow to spoil stack. Maybe someone will be able quickly check it in C .. 

**How can I debug x64dbg plug-ins?**

**Comment by mrexodia** [comment]
TitanEngine is not supported over here. Be wary that it can be replaced by GleeBug at any time so your APIs might not work in the future.

As for debugging plugins, just use Visual Studio or whatever you usually use. Should be no problem.

**Comment by mrexodia** [comment]
Also there is an API that does this that is supported. Use DbgFunctions()->ModBaseFromName
