### ISSUE TITLE
"INFO" Automatically attaching a process as soon as its launched. 

### ISSUE THREAD

**Issue by MrIQZero** [x64dbg/x64dbg#847]
I wanted to know is there any way x64dbg can auto attach a process as soon as that process is launched by the user.

example paint.exe, as soon the the paint.exe launches x64dbg automatically attach the process in its debugger.

Thanks,

**Comment by torusrxxx** [comment]
You cannot do it directly. You can write a launcher that start the process with CREATE_SUSPENDED and start x64dbg to debug it though. The launcher might not work due to #635 .

**Comment by mrexodia** [comment]
You can do it directly. Use gflags.exe from windbg and link it to
x96dbg.exe

**Comment by mrexodia** [comment]
Use this configuration (learned this from a guy at the conference):

![mspaint](http://i.prntscr.com/4878cad5105543e5ae37a7908d597035.png)

**Comment by FlafyDev** [comment]
> Use this configuration (learned this from a guy at the conference):
> 
> ![mspaint](https://camo.githubusercontent.com/b0ad8497ad99fcf75ed2ccfc15c1248db2f3785b9ef371b656dafd34b29a094b/687474703a2f2f692e70726e747363722e636f6d2f34383738636164353130353534336535616533376137393038643539373033352e706e67)

Where are these settings today?

**Comment by redthing1** [comment]
That link isn't accessible, what's in it?
