### ISSUE TITLE
View doesn't change to Dump when in Watch View

### ISSUE THREAD

**Issue by blaquee** [x64dbg/x64dbg#851]
If you have the watch view tab active, and try to dump a register value in dump. The view does not change to the dump tab. This also occurs for the CPU view.

**Comment by mrexodia** [comment]
Yeah it's because the watch view is hacked in as a dump window. The manager
expects the watch view to be a dump window

**Comment by torusrxxx** [comment]
Does this issue still persist?

**Comment by blaquee** [comment]
I'll check this today and comment/close with response

**Comment by mrexodia** [comment]
Just checked, it switches to the dump now!
