### ISSUE TITLE
Debugging system-level processes like explorer.exe

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#853]
I know IDA Pro is capable of doing this by running the remote debugger and then connecting to it. However, I really prefer to use x64dbg. Is there any way I can attach x64dbg to a system-level process like explorer.exe?

**Comment by mrexodia** [comment]
Yes, use debug privilege.

**Comment by ViRb3** [comment]
I have turned it on, yet it doesn't work. Correct me if my setup is wrong.

![img](https://i.imgur.com/L0GkeYf.png)

**Comment by mrexodia** [comment]
Windows 10 is not tested, possibly the debug privilege is not enough there to debug system processes. Try `EnableLUA=0`

**Comment by ViRb3** [comment]
Unfortunately that didn't help. Is there any way I can investigate the issue?

**Comment by mrexodia** [comment]
You could check what happens in TitanOpenProcess

**Comment by ViRb3** [comment]
Will do. Just a followup issue, I cannot even open x64 .NET PE, I get CreateProcessA: NOT_SUPPORTED. IDA Pro cannot debug them either though.

**Comment by mrexodia** [comment]
X64dbg will only debug things that actually start with CreateProcess.

**Comment by ViRb3** [comment]
Latest x64dbg successfully attached to and debugged explorer.exe! Still running Windows 10 with UAC.
