### ISSUE TITLE
new drag drop intents

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#857]
1. CTRL+drag a constant or an address from disassembly into dump : goto
2. CTRL+drag a range of instructions from disassembly into time wasted counter : fill with NOP
3. CTRL+drag a constant from disassembly into watch : watch
4. CTRL+drag a range of instructions from disassembly into snowman : decompile selection
5. drag a text file from explorer into the workspace : load script
6. CTRL+drag a range of data from dump into time wasted counter : fill with 00
7. CTRL+drag a thread from threads into time wasted counter : kill
8. CTRL+drag an address from dump or stack into watch : watch
9. drag a DLL into the workspace while debugging : inject
10. CTRL+drag some instructions, data or table items from AbstractTableView into notepad, Notes View or browser : copy

More creative ideas are welcome.

**Comment by mrexodia** [comment]
I disagree with 9, dragging a DLL should debug that DLL. Nice suggestions though!

**Comment by torusrxxx** [comment]
Nobody will use this, and hard to implement.
