### ISSUE TITLE
Allow plugins to add some items in the info box below the disassembly.

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#858]

**Comment by mrexodia** [comment]
Sounds like a good plan! Gotta see that we don't bottleneck the GUI at that point again though, last time there was a fun bottleneck where the info box would read a file every time the disasm selection changed 😄

**Comment by torusrxxx** [comment]
The plugin can now use GuiAddInfoLine() inside callback CB_SELCHANGED to add the items.
