### ISSUE TITLE
Crash while handling string references

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#862]
load a file with string references quickly goto reference tab
and follow in disassembler or Dump both works but when clicking disassembler it
shows jumpy code or something.. chose a file with loads of strings so it doest load so quickly
it seems its a blank string it tries to goto but thats only me guessing
![crash](https://cloud.githubusercontent.com/assets/1159592/16901007/e02c552e-4c36-11e6-8b85-570fd6b26f45.png)

**Comment by torusrxxx** [comment]
This bug cannot be reproduced because token color bug has been fixed.

**Comment by Chandlr** [comment]
Seems to been fixed yep
