### ISSUE TITLE
Set default language to English

### ISSUE THREAD

**Issue by ax330d** [x64dbg/x64dbg#867]
I am having German keyboard layout, but English Windows 10, so x64dbg picks German as a default language (which is not my default language I use). It would be nice if there was an option to pick language at any given moment through menu. 

Also, I was am still unable to change language to English, was trying to edit config file, w/o success, and obviously did not find such option in menu.

**Comment by mrexodia** [comment]
Look for 'Language' in the INI currently it takes your system locale. Maybe this can be changed to system language if qt exposes that.

Use 'Language=en' for English.

**Comment by ax330d** [comment]
Do you mean following entry in x96.dbg.ini:
[Engine]
Language=en
If so, then it does not help.

**Comment by mrexodia** [comment]
No you need to put it in your x64dbg.ini and x32dbg.ini alternatively just
remove the 'translations' directory.

**Comment by torusrxxx** [comment]
in x64dbg.ini: set 

[Engine]
Language=en_US

**Comment by ax330d** [comment]
I see, removing directory worked. But as I said, it would be nice to have a possibility to change it from menu.

**Comment by mrexodia** [comment]
The latest commit supports partial locales you should update.

Feel free to send a pull request for that menu. I think this behavior is
generally fine although the system language should be taken instead of the
system locale.

**Comment by mrexodia** [comment]
The default language should now be the most preferred system UI language (my locale is nl_NL, system language en_US so it will take en_US for x64dbg per default).

**Comment by torusrxxx** [comment]
Languages menu is added. Please close this issue.
