### ISSUE TITLE
lua/python support

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#87]
----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/87
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:16:06.336

**Comment by Nukem9** [comment]
Who can write detailed this task?

----------------------------------------
Original comment by: [sys_dev](http://bitbucket.org/sys_dev)

**Comment by Nukem9** [comment]
currently someone is working on a plugin, it's not really needed anymore. If you are interested in joining up with the development, please contact me on skype :)

Greetings

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by jvoisin** [comment]
It's done [here]( https://github.com/x64dbg/x64dbgpy )
