### ISSUE TITLE
Hotswappable plugins

### ISSUE THREAD

**Issue by jdavidberger** [x64dbg/x64dbg#870]
This would primarily be for plug-in developers. One of the biggest issues in developing plugins is the need to shut down the debugger before compiling, and then having to restart everything and re-setup the debugee state for whatever you were testing. 

If we copy the dp files to a temp location and load that temp location, we can set up file watchers on the plugin directory and the individual original dp files.

**Comment by blaquee** [comment]
Perhaps an option to just load plugins on demand? Unload/Reload?

**Comment by mrfearless** [comment]
Some example code (poorly written) but to give an idea of what these extra functions might be: http://pastebin.com/ppNcCSPM

**Comment by blaquee** [comment]
This has now been implemented. Test it out with commands `plugload` and `plugunload`

**Comment by mrfearless** [comment]
Noticed an issue with plugload, if you type `plugload` and press enter (without specifying a plugin name) it shows that it cant find `x.dp32`, where `x` can be a random letter or non-printable character each time the command is entered on the command bar:
![](https://s20.postimg.org/cxueskkkd/plugloaderror.png)
