### ISSUE TITLE
Set Chinese Language when displaying annotate incomplete on CPU windows. ver x32dlg Jul 19 2016

### ISSUE THREAD

**Issue by tanlin0066** [x64dbg/x64dbg#873]
Set Chinese Language when displaying annotate incomplete on CPU windows. ver x32dlg Jul 19 2016

**Comment by mrexodia** [comment]
Just use your own font. You can change it in options.

**Comment by tanlin0066** [comment]
@mrexodia  Not the problem. Such as setting annotate a "测试模式", but CPU WINDOWS display  a "测试",  text Is truncated..

**Comment by mrexodia** [comment]
Thanks for the report!
