### ISSUE TITLE
Look up addresses in memory map

### ISSUE THREAD

**Issue by dwendt** [x64dbg/x64dbg#874]
So in gdb-peda and such you can instantly look up protections, ranges, etc for a given address. I think x64dbg could have the equivalent by adding a context menu entry "Follow in Memory Map" that jumps over to that tab and shows which line represents an address's mapping.

Would be super useful in the register window, and maybe the data dump when it's in "address" mode.

**Comment by blaquee** [comment]
hmm, I like this idea. Will put it on my todo for the weekend.

**Comment by mrexodia** [comment]
This has been partially implemented in the memory map as "Find address page":

![s](https://i.imgur.com/W3hP48H.png)

**Comment by mrexodia** [comment]
Has been fully implemented in registers, disassembly, dump and stack and the command `memmapdump`.
