### ISSUE TITLE
jump to no man's land when scrolling upwards near the entry point

### ISSUE THREAD

**Issue by sdcode** [x64dbg/x64dbg#875]
Near the entry point:
`0000000140001001  | 48 83 EC 58               | sub rsp, 58                                 |
`

Clicked on the up arrow in the scrollbar, or used the arrow up key, or the mouse wheel:
```
0000000140002FFD  | 00 00                     | add byte ptr ds:[rax], al                   |
0000000140002FFF  | 00                        | ???                                         |
```
And clicking downwards etc won't get you back. Only way out is to press F7/F8.

IMHO user should NOT go before the entry point until he explicitly declares his intention to do so.

**Comment by mrexodia** [comment]
You clicked the up button so there is your intention. Still something fishy
going on here though, it appears to have scrolled down.

**Comment by sdcode** [comment]
> so there is your intention

Thanks, Duncan. With Olly, I had developed the bad habit to simply push forward the mouse wheel until the entry point was reached. That was careless. I promise I will from now on control my intentions, and push the mouse wheel very, very gently until I can see the entry point. Maybe I will have to find the Windows setting that limits the mouse wheel scroll factor to one line, but really, no problem!

**Comment by mrexodia** [comment]
Your description was rather vague and I didn't reproduce it yet. From what
I gathered it jumped to some weird place when you pressed the scroll up
button while on the entry point.

No idea what you mean with "IMHO user should NOT go before the entry point
until he explicitly declares his intention to do so." You clicked up so why
would you expect it to do nothing.

**Comment by sdcode** [comment]
Never mind, I had used the "stable" version of 19 June, but now I downloaded the latest snapshot, and it seems somebody has fixed this behaviour. Thanks, it was driving me crazy.

**Comment by mrexodia** [comment]
So if you confirmed everything is fixed, please close the issue. Thanks!
