### ISSUE TITLE
Goto expression easy bug

### ISSUE THREAD

**Issue by or75** [x64dbg/x64dbg#881]
Wat ???

engine.dl work

![1](https://cloud.githubusercontent.com/assets/5619678/17078855/64a23218-5107-11e6-9e8f-ad878fc974a3.png)

engine.dll not work

![2](https://cloud.githubusercontent.com/assets/5619678/17078858/687bdc90-5107-11e6-89f8-24436f129acd.png)

**Comment by mrexodia** [comment]
It's actually not a bug, just a fun thing in the `valapifromstring` function. What you are doing here is getting the api value of the module `engine` with the value `dl` (which will resolve to an ordinal if the `dl` register has a small enough value).

`engine.dll` is not a valid expression, if you want the module base you can use `engine.dll:0`
