### ISSUE TITLE
Debugger crash on "vardel"

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#886]
In the command bar type this:
1. var $asd, 123
2. vardel $asd

- Using an old build: 21-7
- OS: Win10 x64

minidump:
http://rgho.st/private/8cwJNRmMp/e99751d8cfea6dba9cf5ab2e8d9f9728
password: asd123

EDIT: seems to have a really higher occurrence probability with `x32dbg.exe` as opposed to `x64dbg.exe`

**Comment by Chandlr** [comment]
Iam using 23 Jul release and it didt crash (x32/x64) tested both

log:
$asd=123 (291d)
deleted variable "$asd"

**Comment by PB314** [comment]
The x32dbg crashed for me "23 Jul 2016".   The x64dgb didn't crash immediately but when closing it did.  Using Windows 7

**Comment by mrexodia** [comment]
Smells like heal corruption 💩

**Comment by Chandlr** [comment]
crashed for me too now :(

**Comment by PB314** [comment]
Well agree with wk-952 it appears to be associated with W32 X64dbg.   The error can be recreated by using vardel without a valid variable.   Once the error has been instantiated, it is just about impossible to create a new variable, hence it will crash every time vardel is used.  This test was carried out with 31-7-2016.

**Comment by PB314** [comment]
Agree with dk-952 it does appear to be limited to the W32 version, but there is some odd behaviour going on that is difficult to pin down.   One thing you should be able to reproduce which may point you in the right direction is that if you run the X32dbg up and the type in

`var $asd,123 <- ok
 var $kkk, 124 <-ok
 var $aaa, 56 <- invalid variable name
  `
same applies to $bbb etc.
Now try and apply vardel to variable $asd.

**Comment by wk-952** [comment]
I guess variable names like `aaa`, `bbb`, `ccc`, `ddd`, `eee`, `fff`
are not accepted because it seems that the variable name is being resolved into a hex number.

In other words, `var $eee, 123` and `var $fff, 123` are exactly similar to something like this:
`var $7ee, 123`
`var $7ff, 123`
which of course are not valid variable names since they start with a number, hence `eee` and `fff` are not valid variable names.

I don't think it's a weakness in the expression parser though, think of a situation like this:
```
var $qqq
mov qqq, 123
```
that would work fine, but if variable names with hex numbers were accepted then it would be confusing to the debugger:
```
var $fff
mov fff, 123
```
@mrexodia i guess a solution to this would be restricting the dollar sign `$` before var names, that way instructions like `mov $fff, 123` would be accepted since the user has explicitly marked the token `fff` as a var name.

**Comment by mrexodia** [comment]
Yeah the variable thing needs a complete rewrite. It's about 3 years old
now and horribly coded.

**Comment by torusrxxx** [comment]
fixed. In ``bool vardel(const char* Name, bool DelSystem)`` function, it does some weird and dangerous logic to delete a variable. We can simply erase the variable we already found without that dangerous logic.

**Comment by wk-952** [comment]
Thank you very much for all your work.
