### ISSUE TITLE
preview call or jump destination

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#890]
When the mouse hovers a call or jump instruction, show a tooltip with the disassembly of the destination in it if the destination is not in the view.

**Comment by mrexodia** [comment]
That's a nice idea, tool tips are generally ugly though so you'd have to manually draw it 💩

**Comment by mrfearless** [comment]
Probably be useful to create a hidden tool popup dialog/window, that is shown when the mouse is over the call/jmp and hidden again when it is moved away.

Possibly create it with an instance of your cpu window grid listview thing, which will have address, instructions etc. 

Plus an arrow top or bottom to show where this code is (above or below) in relation to where we are now. Also another possible feature to add to this is mousewheel up/down increases or decrease this 'tooltip' dialog height (from a default size) to show or hide more disassembly.

**Comment by mrexodia** [comment]
Another idea might be a button or something that you press in the sidebar or a context menu option. It's quite easy to draw disassembly in a random dialog because of the richtextpainter and capstonetokenizer

**Comment by blaquee** [comment]
Something that works similar to IDA's popup would be cool. Scrollable + a hotkey to jump to destination while popup is open would be neat. Although [Enter] takes you there anyways now.
