### ISSUE TITLE
x64dbg.exe crashes with "%rcx" in breakpoint log text

### ISSUE THREAD

**Issue by deselect** [x64dbg/x64dbg#893]
1. Start x64dbg.exe.
2. Open any executable in it.
3. Add a breakpoint anywhere.
4. In Breakpoints tab, select this breakpoint and press "Edit".
5. Input "%rcx" in "Log Text" editbox. Or in any other editbox.
6. Press save and get it crashed.

P. S. "%d" format specifier is replaced with some number. "%s" results in "0" after saving.

**Comment by Chandlr** [comment]
Bug confirmed in x32 build: 27 July

**Comment by mrexodia** [comment]
Should be fixed.
