### ISSUE TITLE
assemble x64dbg as a loader and a patcher for a protected executable without the need for a graphical interface

### ISSUE THREAD

**Issue by veejnas** [x64dbg/x64dbg#894]
Hi, I see a great utility in being able to turn x64dbg into a dedicated loader and patcher for a protected executable. The premise is that x64dbg opens the target on startup, loads a script and executes in the background. The first challenge is to embed all the dependencies including the db file for the target and the script for reversing into one single executable loader. The rest am sure will not be that challenging.
Can you point me to the places in code where I can make changes so x64dbg:
1. Load a target on start up
2. Reads its db that can be extracted in temp folder
3. Loads the script and execute it allowing the packed target to be patched at runtime. 
4. Runs in the background, without showing GUI and exiting and cleaning up after the target has been closed. 
5. And finally to make a self contained executable with all depending dll's, db file, script packed in one executable.
Thanks for making this wonderful debugger, that has rekindled my interest in reversing after the era of softice and winxp.

**Comment by Chandlr** [comment]
Sorry but i dont see the use for a Loader patcher for a packed program, just unpack it normally and keep the .exe i guess that is more like a plugin thing i think

**Comment by mrexodia** [comment]
I don't have any plans to support this, however feel free to go crazy with
the source code...

My suggestion would be to just get GleeBug and use that as a loader instead.
