### ISSUE TITLE
Debugger loses "sense" of debugee when following the results of a memory map search (32-bit version only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#898]
1. Debug any 32-bit application
2. Make sure the target is paused or else you may trigger issue (#877)
3. Go to the `Memory Map` tab and search for any pattern that exists
4. When the results are displayed, right click on any one of them and select `Follow in Disassembler`

All the registers will be reset to 0 (including CIP), also if you tried to continue running the debugee nothing will happen nor the debugger will crash (as if the debugger had a coma).
- Reproduced on a clean version of `snapshot_2016-07-28_12-52` (and also the build from 21 july)
- Antivirus was turned off
- OS: Win10 x64

**Comment by mrexodia** [comment]
Just tried on Windows 8.1 x64, seems like there are some issues with Windows 10 haha

**Comment by mrexodia** [comment]
Could you try replacing TitanEngine.dll with the GleeBug one temporarily? https://ci.appveyor.com/api/buildjobs/6re934i5432y0vpv/artifacts/bin.zip Also if possible with issue #877 TitanEngine probably messes with page protection constants: https://bitbucket.org/titanengineupdate/titanengine-update/src/e089f4af41a461b69017db3750f79fbaed1008df/TitanEngine/TitanEngine.Debugger.Memory.cpp?at=master&fileviewer=file-view-default#TitanEngine.Debugger.Memory.cpp-353

**Comment by wk-952** [comment]
I know i'm going to sound really stupid but here's what i did, after downloading the .zip file you provided, i extracted it then copy/past-ed `TitanEngine.dll` (the 64-bit version from "release" folder) and replaced the original one .
Upon opening x64dbg.exe, i got the error message: `procedure entry point GetTEBLocation can't be located in x64dbg.dll` followed by another one `Error loading library "x64gui.dll"`

**Comment by wk-952** [comment]
Never mind, i manually recompiled the `GleeBug` repository and it worked.
Issue #877 is solved when i replaced `TitanEngine` with `GleeBug` :+1: 
but this one still persists.

**Comment by mrexodia** [comment]
Yeah I forgot to run the appveyor for the latest commit. Thanks for
checking! I will try to reproduce these when I have access to a Windows 10
machine.

**Comment by wk-952** [comment]
Original post updated, this seems to be happening only with 32-bit applications, 64-bit applications are fine.
This statement also applies to issue #877 .

**Comment by wk-952** [comment]
After PR #1406 this issue and #877 are both fixed.
Thanks a ton @changeofpace.
