### ISSUE TITLE
Wrong "SysWOW64" redirection when debugging anything from "System32" on a 64-bit OS

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#899]
1. Go to `%windir%\System32` 
2. Right click on any `.exe` file and select `Debug with x64dbg`

If the file exists in `%windir%\SysWOW64`, then this 32-bit version of the file will be loaded in the debugger.
If the file does not exist in `%windir%\SysWOW64`, then you'll get an error message stating that the file is in use or does not exist.
Of course opening `x64dbg.exe` manually then loading the desired application will work fine.

- Reproduced on Win10 x64
- Using a clean version of `snapshot_2016-07-29_08-23`

**Comment by mrexodia** [comment]
Yeah I'm not sure how to fix this. Wow64 programs will have some redirecting per default. Dont know how how to turn it off. Anyone have ideas?

**Comment by wk-952** [comment]
Are those of any help ?
[Wow64DisableWow64FsRedirection function (msdn)] (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365743(v=vs.85).aspx)
[Wow64RevertWow64FsRedirection function (msdn)] (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365745(v=vs.85).aspx)

**Comment by blaquee** [comment]
Do we want this to be the default behavior for the loader? I think I can add/test this tonight in the loader.

**Comment by mrexodia** [comment]
The default is redirection enabled...

**Comment by wk-952** [comment]
I tried it on snapshot from 26/8 and it's still redirecting.

**Comment by blaquee** [comment]
Impossible. Could you outline your exact steps for me. And details about system?

**Comment by wk-952** [comment]
- OS: Windows 10 Enterprise LTSB x64 (version 1607, aka `Anniversary Update`). Main OS
- OS: Windows 8.1 Enterprise x64. Virtual machine
- Snapshot: 26/8

Here's what i did:
1. Go to `"C:\Windows\System32"`
2. Right click on `notepad.exe` then select `Debug with x64dbg`.
3. You'll see that `x32dbg.exe` is started instead of `x64dbg.exe` and
the `notepad.exe` from `SysWOW64` is loaded in it.

**Comment by wk-952** [comment]
Found the problem, the function `static arch GetFileArchitecture(const TCHAR* szFileName)` is always returning 2 (`x32`), i debugged `x96dbg.exe` and manually changed the return value to 3 (`x64`) and the redirection was successfully disabled.

**Comment by blaquee** [comment]
Ah, ok then I'll review this function for accuracy. Thank you for testing!

**Comment by wk-952** [comment]
One more thing that may help, the function `GetFileArchitecture()` returns 2 (`x32`) because it relies on the windows function `CreateFile()`, which itself seems to be depending on redirection.

From the msdn page [Wow64DisableWow64FsRedirection function] (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365743(v=vs.85).aspx)
> ... To avoid these problems, disable file system redirection immediately before calls to specific file I/O functions __(such as CreateFile)__ that must not be redirected, and re-enable file system redirection immediately afterward using Wow64RevertWow64FsRedirection.

To verify this try `CreateFile()` on an executable file that doesn't exist in the folder `SysWOW64`, example `"C:\Windows\System32\acu.exe"`. You'll see that it returns `0xFFFFFFFF`.

**Comment by torusrxxx** [comment]
Can you reopen the issue wk?

**Comment by wk-952** [comment]
Github doesn't allow this permission because the repository owner @mrexodia closed it himself.

**Comment by mrexodia** [comment]
@wk-952 I believe this has been fixed with pull request #1013

**Comment by wk-952** [comment]
The redirection is successfully disabled now. Thanks :+1:
But if the application doesn't exist in `SysWOW64` the problem will still persist,
are you sick of me yet :smile: 

I'm not sure why does that happen, but even when the redirection is disabled,
the check `if(pnth->FileHeader.Machine == IMAGE_FILE_MACHINE_I386) ` in the function `GetFileArchitecture()` will return true.
![untitled](https://cloud.githubusercontent.com/assets/11916365/18029881/28a62062-6ca5-11e6-897d-3eb16df8a24b.png)
see how the conditional jump line is gray (jump isn't taken).

**Comment by blaquee** [comment]
@wk-952 If the application doesn't have an equivalent 32-bit version, there is nothing to redirect to. Is that what you were referring to? Is everything working ok now?

**Comment by wk-952** [comment]
I was referring to the binary file `acu.exe`, it seems to be only visible in the explorer, when i tried to debug it i got the `file not found` error, it's not even visible in the open file dialogue (`F3`).
But anyway, aside from that application, everything works perfectly now, even if the target doesn't have an equivalent 32-bit version, its 64-bit version will be loaded correctly in `x64dbg.exe`.
