### ISSUE TITLE
Unable to see "jump from" lines.

### ISSUE THREAD

**Issue by soyasoya5** [x64dbg/x64dbg#901]
If the JMP instruction moves out of sight from the disassembly, the JMP destination will not show any lines from the line that jumps to it.

[For example, when the JMP is selected, the lines to the destination is shown.](http://puu.sh/qjFVH/7f6f7af800.png)

[However, if you select the destination and scroll down, moving the JMP instruction out of sight, the line disappears.](http://puu.sh/qjFXK/2b29435f74.png)

To find the JMP instruction, you'd have to search for references, which you are unlikely to do if you don't know if there is a jump to the address you selected.

[In ollydbg, the JMP line is shown regardless if the instruction is in sight or not. It even tells you where the jump is.](http://puu.sh/qjGsJ/5dc620c92f.png)

I'd personally like to see this feature implemented as it might come in handy.

**Comment by mrexodia** [comment]
It's already implemented. Use xanal or hit 'a' on the function start.

**Comment by soyasoya5** [comment]
Oh okay. Thanks for responding.
