### ISSUE TITLE
Following Exports or EntryPoint of a module with non-alphanumeric chars in its name

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#904]
Assuming there's an application with the name `"xxx yyy.exe"` (contains spaces) or `"xxx-yyy"` (contains dashes), how should i follow for example its entrypoint or one of its exports without selecting it from the memory map ?

Typing something simple as `ntdll.dll:isupper` will work perfectly, but when the module name contains non-alphanumeric chars it won't work.

**Comment by wk-952** [comment]
Another question please, by design, we can't follow Imports, right ?
I mean if the application `xxx.exe` for example calls `kernel32.TerminateProcess`, then i typed `xxx.TerminateProcess` or `xxx.exe:TerminateProcess` it won't resolve to its location in the imports table ?

**Comment by mrexodia** [comment]
Yeah you cannot follow import address table entries. As for modules with spaces or dashes I don't actually have an answer to that at this point. Spaces *should* work but dashes will be recognized as a minus.

**Comment by torusrxxx** [comment]
Can't we surround these DLL names with quotation marks "" ?

**Comment by mrexodia** [comment]
Possibly, yes

**Comment by mrexodia** [comment]
I added quotes to the expression parser (hopefully without side effects). You can now use "'xedparsetest - copy':EntryPoint+4"

**Comment by wk-952** [comment]
Thank you so much :+1:

**Comment by wk-952** [comment]
There's one thing though, you seem to be also using single quotes `'` as a text wrapper, that actually will cause problems with modules whose names contain single quotes.

For example you can't do that
`"yyy's xxx.exe":EntryPoint`

**Comment by mrexodia** [comment]
I removed the single quotes from the expression parser, now everything should work as expected.
