### ISSUE TITLE
Feature request: GUID type in "Data copy..." window

### ISSUE THREAD

**Issue by deselect** [x64dbg/x64dbg#907]
Hello. I think it would be useful to have GUID type in the list of types in "Data Copy" window to copy 16-bytes length blocks in standard GUID text format like "{6F9619FF-8B86-D011-B42D-00CF4FC964FF}". Selected data can be split to N blocks by 16 bytes, last block length can be aligned up to 16 with zero filling, and N GUIDs are to be displayed.

**Comment by mrexodia** [comment]
I already wrote all the conversion code so I'll probably push that somewhere tonight or tomorrow
