### ISSUE TITLE
Init Callbacks Issues

### ISSUE THREAD

**Issue by dummy0stud** [x64dbg/x64dbg#908]
Why there is no moduleBase in PLUG_CB_INITDEBUG structure?
It looks like I am incapable of getting moduleName in CBLOADDLL, any tips of what is going on?
```
extern "C" __declspec(dllexport) void CBLOADDLL(CBTYPE cbType, PLUG_CB_LOADDLL* info){
    _plugin_logprintf("[TEST] BaseOfImage:%04x dll_name:%s \n", info->modInfo->BaseOfImage, (const char*)info->modInfo->ImageName);
}
```
Output from Log window is:
```
DLL Loaded: 77E00000 C:\Windows\SysWOW64\ntdll.dll
[TEST] BaseOfImage:77e00000 dll_name:(null) 
```

**Comment by mrfearless** [comment]
`PLUG_CB_INITDEBUG` has a `szFileName` field - the name of the file being debugged.

For getting a module base you could try something like
```cpp
    duint entry = GetContextData(UE_CIP);
    char modname[MAX_MODULE_SIZE] = "";
    DbgGetModuleAt(entry, modname);
    duint base = DbgModBaseFromName(modname)
```
My c coding isnt great, so some of that might be off slightly, in assembler x86 (which i use) it is:
```nasm
    Invoke GetContextData, UE_CIP
    mov entry, eax
    Invoke DbgGetModuleAt, entry, Addr modname
    Invoke DbgModBaseFromName, Addr modname
    mov base, eax
```

`GetContextData` is defined in `TitanEngine.h` which is included in the pluginsdk folder.

or you could try via the `DbgFunctions` `ModNameFromAddr` call:

```cpp
    duint base;
    char modname[MAX_MODULE_SIZE] = "";
    DbgFunctions()->ModNameFromAddr(sel.start, modname, true);
    base = DbgFunctions()->ModBaseFromName(modname);
```
To get current address (from cpu view) you can use `GuiSelectionGet`

```cpp
    SELECTIONDATA sel;
    GuiSelectionGet(GUI_DISASSEMBLY, &sel);
```
Again apologies if my c coding isn't correct, but hopefully it will point you in the right direction

**Comment by dummy0stud** [comment]
the problem is, these callbacks are called in early stage of program execution and I believe that is the reason everything is failing

**Comment by mrexodia** [comment]
It worked fine for me when I tested it. Perhaps a recent pull request broke
things.

**Comment by dummy0stud** [comment]
v25 Compiled on Jul 29 2016, 20:20:43

**Comment by mrexodia** [comment]
Wasn't this resolved in the x64dbg group?
