### ISSUE TITLE
Ability to see breaking type of a Hardware Breakpoint

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#909]
In the HW BP section in the `Breakpoints` tab, you can see if it's enabled or not along with its conditional stuff, but you can't see its breaking type; whether it's `On Execute`, `On Read (Byte, Word, DWord, QWord)` or `On Write  (Byte, Word, DWord, QWord)`.

It would be helpful if this could be shown.

**Comment by wk-952** [comment]
The new view looks really good especially with large amount of breakpoints,
the side-by-side stacked info in the `Summary` column makes it easier to keep track of the details for each breakpoint.
Thanks a ton!

One thing though, if you pressed on any column ex: `Summary`, `Hit`, etc... this GUI bug will occur:
![err](https://user-images.githubusercontent.com/11916365/29251852-48ff6fb8-805d-11e7-8248-40c9b4448d2e.png)
I know you don't like this, but I didn't want to open a complete new issue for this tiny bug.

Again thanks for all the work.

**Comment by mrexodia** [comment]
Okay, should be fixed now!

**Comment by mrexodia** [comment]
Thanks a lot for reporting that by the way. I definitely like it :)

Now there was a refactor and everything is really clean, without your report that probably wouldn't have happened...
