### ISSUE TITLE
Feature Request: Save to exe

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#912]
Option to save a modified file back to an exe - default filename shown in Save As... dialog is same name as original filename - automatically makes a `originalfilename.ext.bak` file - just in case (maybe in same location?)

Option could be in File menu. "Save file", or "Export file" or something similar, with maybe option being greyed out of no changes have been made to file - requires a dirty flag somewhere to indicate changes made to enable the save menu option.

**Comment by mrexodia** [comment]
You cannot override the original file anyway because it's in use right?

**Comment by mrfearless** [comment]
Yes true, an export option might be more practical then - export to `originalfilename_patched.ext` ?

**Comment by mrexodia** [comment]
Or just use patches save file?

**Comment by mrfearless** [comment]
Yes, although i didnt notice that option before, could be an option to still have a prominent menu item for exporting - which can go straight to the patch file save as dialog option, bypassing the patch dialog entirely and just showing file save as dialog.

**Comment by mrexodia** [comment]
Right, like how I added the useless search context menu in the symbol views.

**Comment by mrfearless** [comment]
Already in x64dbg under patches

**Comment by mrexodia** [comment]
No this was a good plan, creating a dummy menu to educate.

**Comment by mrexodia** [comment]
![s](https://i.imgur.com/UQD7MbX.png)

**Comment by Joshua2point0** [comment]
doesn't work mrexodia
