### ISSUE TITLE
Feature request: expose additional gui properties

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#917]
Hi I'm looking at the feasibility of exposing additional gui properties that can be read by plugins.

I have a specific use in mind but I'll list the properties I would like to be able to access and include a few additional comments.
# Gui accessible properties
## Handle to `MHTabWidgetClassWindow`

Currently when x64dbg starts it has 5 child windows, the first of which is this HTabWidgetClassWindow window, which contains everything below the toolbar and ends before the command bar. I can get this handle currently via a call to [EnumChildWindows](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633494%28v=vs.85%29.aspx) and doing enumeration and comparison till i find the name of the window and save the handle required. 

Proposed function in Bridge:
`GuiGetMainWindowHandle` (or any other name). Returns handle to window.

This would save processing whilst in the start of the plugin (pluginit or plugsetup) eliminating the need to enumerate child windows. Also if these child windows are obfuscated by x64dbg or another plugin to prevent x64dbg being detected then this function call would be convenient.

Highlighted in the image is the bounding box of the MHTabWidgetClassWindow window:
![](https://s20.postimg.org/lmsaz5s65/1st_Child_Window_MHTab_Widget_Class_Window.png)
## Get active tab

Ability to determine which tab view is active:

Proposed function in Bridge:
`GuiGetActiveTabWindow` (or GuiGetActiveTab or whatever). Returns integer that equates to a specific tab that is active.
0=cpu 1=graph, 2=log ... etc
## Get column width

Column widths are saved in the x32dbg.ini/x64dbg.ini, but only at close. If columns are moved/resized after their initial value once x64dbg has started, the value cannot be read currently.

Proposed function in Bridge:
`GuiGetColumnWidth(int activetab, int columnno);` 

Ive a specific interest in getting the column sizes for the cpu tab, but this function would allow to read column widths in other tabs at runtime for plugins and possible other future uses.
## Get widget width/height or rect

`GuiGetWidgetWidth` and `GuiGetWidgetHeight` or a `GuiGetWidgetRect` function.
Parameter could be an integer that represents the widget required, 0=registers widget, 1 = dump widget, 3 = infobox, 4 = stack etc etc
Returns width/height of the widget in question, or bounding rect structure if using `GuiGetWidgetRect` (left,top,right,bottom)
# Example of usage in a specific plugin I'm creating

Currently I've hit an impasse with developing a 'CodeShot' plugin, which is designed to capture the cpu disassembly window and save the image to a file (png, jpeg, gif, bmp). It currently works by getting the hdc of the MHTabWidgetClassWindow window, generates the output filename based on the current module name and datetime and converts the internal captured bitmap to the file format requested (currently works with png in testing, but can do the other formats) and saves this file in a folder.

I can get the bounding rectangle for MHTabWidgetClassWindow, and guesstimate the width to capture based on the column widths saved in x32dbg.ini. Height is guesstimated as well (to cut out the dump view) and leave just the code showing in the final saved image file.

If the columns are resized or the left jump sidebar is resized i cant accurately get this information currently, and if registers view is resized then guesstimate of width can be out as well. Similarly with height if the main window is resized or the dump window height is increased/decreased.

If the active tab is another view other than cpu, it will capture the MHTabWidgetClassWindow window but will instead capture the specific active tabs content, but adjusted for what would have been the guesstimated cpu disassembly rectangle.

Ideally i could adjust what portion of screen to capture based on the currently active tab, and in the case of the cpu window i can adjust the captured screen portion to only the disassembly output. Optionally via other plugin options i could allow user to only capture disassembly and exclude comments column or left jump sidebar or other combinations.
# Highlighted areas to get gui properties for

To help illustrate this, specifically for the cpu disassembly widget:

![Disasm widget](https://s20.postimg.org/5uxac4731/disassembly.png)

If i can get the width & height or bounding rect of the following:
![Left sidebar](https://s20.postimg.org/5yr3sdckd/Left_jump_line_sidebit.png)
![Registers view](https://s20.postimg.org/ga3gl149p/registerview.png)
![Dump view](https://s20.postimg.org/5w785j8wt/Dumpview.png)

and the column widths in the cpu disassembly widget, i can accurately capture this screen to a file.

Hopefully some or all of this is feasible and can be incorporated.

Thanks for reading this and taking the time to review it.

**Comment by torusrxxx** [comment]
The indexes of these widgets, columns and tabs are going to be highly volatile during rapid development process. We may break these indexes everytime a new feature is introduced. (For example, the introduction of CPU Time in the threads view would break the indexes of that view)

**Comment by mrexodia** [comment]
While chatting mrfearless and me came to the conclusion that it might be
enough to just provide a function that gets the HWND for each widget. We
can keep this function up to date probably...

**Comment by mrexodia** [comment]
Something has been implemented, but it cannot be documented at the moment.

```
ACTIVEVIEW activeView;
GuiGetActiveView(&activeView);
printf("activeTitle: %s, activeClass: %s\n", activeView.title, activeView.className);
```

`activeTitle` might be translated, `className` might be a child of the `activeHwnd` but is always constant.

**Comment by mrfearless** [comment]
Thank you. I'll hopefully get a chance to look at it Sunday onwards when I'm free.
