### ISSUE TITLE
Make an option to save graph as .png or .jpg ...

### ISSUE THREAD

**Issue by TheServer201** [x64dbg/x64dbg#918]

**Comment by mrfearless** [comment]
Somewhat related to #917 and a plugin im developing, that will be able to save screenshots to png, jpg or bmp for cpu disasm or whichever tab view is active - including graph

**Comment by mrexodia** [comment]
Yeah that's definitely a good plan! It should be really easy as the paint
event is separated enough for it to work.

**Comment by dummy0stud** [comment]
consider implementing ZOOM feature

**Comment by mrexodia** [comment]
Consider adding a separate issue. Also consider trying to implement it
yourself please...
