### ISSUE TITLE
Tracing in x64dbg 

### ISSUE THREAD

**Issue by parthibdutta** [x64dbg/x64dbg#923]
I was wondering if tracing options like instruction tracing, function tracing and basic block tracing will be implemented in x64dbg? They do come a lot useful when analyzing virtually obfuscated code.

**Comment by mrexodia** [comment]
Tracing has been implemented, but no data will be collected yet.

**Comment by parthibdutta** [comment]
I saw tracing option but without any sort of trace history like IDA I think its pretty much feature incomplete?

**Comment by mrexodia** [comment]
I don't disagree with you in any way, but no amount of thinking about how
feature incomplete tracing is will fix it...

One way you can have a sort of trace history is by tracing with trace
record. That way you can at least see which instructions were executed.

Another way to fix it is to implement data recording. Generally all you
need to do is add a data recording statement to the condition check (see
debugger.cpp).

**Comment by torusrxxx** [comment]
related to #75.

**Comment by mrexodia** [comment]
Yeah, I consider it a duplicate.
