### ISSUE TITLE
add autocomment for call $0

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#940]
the sequence `E8 00 00 00 00` should get a comment that it's calling the next instruction.

**Comment by joesavage** [comment]
I'd be up for giving this a whirl as my first contribution to x64dbg. I've managed to set up a development and build environment, but despite searching the codebase for calls to `CommentSet(x, x, false)`, `DBG_SET_AUTO_COMMENT_AT`, and `DbgSetAutoCommentAt` I can't quite figure out where the pattern matching code is for the automatic comments. Any chance of a helping hand?

**Comment by mrexodia** [comment]
@joesavage Yeah, auto comments are actually generated in [_exports.cpp:254](https://github.com/x64dbg/x64dbg/blob/development/src/dbg/_exports.cpp#L254). Beware that this code is performance critical so make sure your code doesn't do anything extravagant...
