### ISSUE TITLE
select the found entry in SearchListView

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#97]
---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/97
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-05-07T20:53:51.138

**Comment by Nukem9** [comment]
AFAIK this has been done for a long time.

**Comment by mrexodia** [comment]
No, if you search it removes all the entries that don't match. Basically
selection should be persistent also if you delete the search text.
