### ISSUE TITLE
Copy cryptographic hash of selected data

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#975]

**Comment by mrexodia** [comment]
generally I have refrained from this to avoid horrible dependency issues, might be a plan to create an impossible to compile module that has an interface for all hash types.

**Comment by mrfearless** [comment]
Could use the extra space beside the dump for something like the checksum option that hex workshop has for checksums
![](https://s20.postimg.org/n7om1xejh/dump.png)
![](https://s20.postimg.org/dbnj2a8rh/hwchecksum.png)

And could be an option to outsource that stuff to a plugin, which if loaded calls a function to display this 'extra' widget beside the dump for this purpose, adding in right click menus to generate checksums / crypto hashes for selection/entire file, which are then shown on the right in the new 'crypto' widget.

**Comment by torusrxxx** [comment]
Closed with #1785. An (orphaned) project "FrozenStorm" is still left there.
