### ISSUE TITLE
why debug all exe files always break on leave?

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#982]
why debug all exe files breaked on:

LEAVE   
RET     10
INT3    
INT3    
INT3    
INT3    
INT3    
MOV     EDI,EDI
PUSH    EBP
MOV     EBP,ESP

then debug can't contiune, please look at picture link:
http://oi68.tinypic.com/21n05zm.jpg

**Comment by blaquee** [comment]
Go to the Options and disable System Breakpoint.

**Comment by cxj98** [comment]
already disable, press f9 can't straight run, must press many times, and always break on http://i68.tinypic.com/21n05zm.jpg

**Comment by blaquee** [comment]
Could you provide some more information on your setup? OS, x64dbg version. Also maybe your application is exiting after you press F9? Check the Call stack Tab when it breaks on that Leave to see what has happened up to that point

**Comment by cxj98** [comment]
load any exe, then press F9 run, then break on that. some exe can run after maybe 4, 5, 10, 20 or more times clicked F9. but c point still breaked on:
 LEAVE

RET 10
INT3

INT3

INT3

INT3

INT3

MOV EDI,EDI
PUSH EBP
MOV EBP,ESP

**Comment by cxj98** [comment]
please download this video to see more info:

http://www110.zippyshare.com/v/mJdntWnj/file.html

**Comment by mrexodia** [comment]
As you can see in the log and status bar, the application throws an exception `RPC_S_SERVER_UNAVAILABLE`, you can go to Settings -> Exceptions -> Add Last to ignore the first chance exception.
