### ISSUE TITLE
The header's sort function of list view is unstable (include the patch code)

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#985]
![1](https://cloud.githubusercontent.com/assets/367894/17691190/b4aac236-63c5-11e6-8013-33547e4f4cd0.png)
![2](https://cloud.githubusercontent.com/assets/367894/17691199/be473dce-63c5-11e6-85e5-9a9e24b28738.png)

this can also cause that when sort by "export", some lines will change when set break point one by one.

I finally found a solution:

```c++
bool AbstractTableView::SortBy::AsText(const QString & a, const QString & b)
{
    int i = QString::compare(a, b, Qt::CaseInsensitive);
    if(i < 0)
    {
        return true;
    }
    else if (i > 0)
    {
        return false;
    }
    else
    {
        return (size_t)&a < (size_t)&b;
    }
}
```

When two string are equal, compare string by memory address. It just work!

Myabe AbstractTableView::SortBy::AsInt and AbstractTableView::SortBy::AsHex also need to modify.

**Comment by mrexodia** [comment]
Thanks for your proposed solution, maybe @jdavidberger could verify if it needs changes in other locations?
