### ISSUE TITLE
Wrong results for Ctrl-G search

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#992]
I've got some weird results when searching for API to navigate.
kernel32.GetProcAddress - ok
GetProcAddress - ok
GradientFill - ok -> (msimg32.GradientFill)
msimg32.GradientFill - invalid expression (??)

**Comment by lupier** [comment]
probably same issue as https://github.com/x64dbg/x64dbg/issues/988

**Comment by mrexodia** [comment]
No the issues are unrelated. Anyway the official syntax is msimg32:GradientFill so you might want to try that

**Comment by mrexodia** [comment]
Has the issues been fixed?
