### ISSUE TITLE
Some lines are empty in strings search result

### ISSUE THREAD

**Issue by lynnux** [x64dbg/x64dbg#995]
![11](https://cloud.githubusercontent.com/assets/367894/17829926/fda46b30-66f0-11e6-9846-a4e803fb6efa.jpg)
![22](https://cloud.githubusercontent.com/assets/367894/17829953/6db6c576-66f1-11e6-84c8-d7e79ec0a91e.png)

it seems that when asm code have two memory address can cause this

**Comment by Chandlr** [comment]
If you can you should include sample file
Maybe it's a language bug? :+1:

**Comment by lynnux** [comment]
Just search all modules, then sort by strings.
It seems only in x32 version.

**Comment by mrexodia** [comment]
What do the strings show when you go to them in the disassembly?

**Comment by kkthx** [comment]
This is my example from some executable
![aaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/4583553/17846543/818d9062-6849-11e6-93e6-ca505b6ba1e6.png)

**Comment by lynnux** [comment]
on win10 64bit, C:\Windows.old\WINDOWS\syswow64\notepad.exe:
![image](https://cloud.githubusercontent.com/assets/367894/17876914/1c8a7158-6911-11e6-8728-a55b74c66553.png)
can see string in disassembly window:
![image](https://cloud.githubusercontent.com/assets/367894/17876927/2f4920fa-6911-11e6-88ad-9073503b6293.png)

**Comment by Chandlr** [comment]
Search string reference->All Modules
Also i found empty lines but there when following in Disassembler
http://prnt.sc/c99amy
http://prnt.sc/c99ayi

**Comment by mrexodia** [comment]
> <torusrxxx> #995 Some lines are empty in strings search result is also one of that because almost every search algorithm only looks for one operand.
